// packages/lit/demo/Preferences.ts
import { html, type TemplateResult } from 'lit';
import '../src/index.js';
import type { BreadcrumbItem, RadioGroupOption } from '../src/index.js';

const trail: BreadcrumbItem[] = [{ label: 'Settings', href: '#settings' }, { label: 'Notifications' }];

const digestOptions: RadioGroupOption[] = [
  { value: 'daily', label: 'Daily', description: 'One summary every morning' },
  { value: 'weekly', label: 'Weekly', description: 'A summary every Monday' },
  { value: 'never', label: 'Never', description: 'Only the alerts you turn on below' },
];

/**
 * Notification-preferences screen composed from the Calm & precise Lit elements.
 *
 * Expects the token custom properties to be loaded once at the app root
 * (`import '@design-schema/tokens/calm-precise/css'`) and, optionally,
 * `data-mode="dark"` on `<html>`.
 */
export function renderPreferences(): TemplateResult {
  return html`
    <ds-landmark role="main">
      <ds-stack gap="6" align="stretch">
        <ds-stack gap="2">
          <ds-breadcrumb .items=${trail}></ds-breadcrumb>
          <ds-heading level="1">Notifications</ds-heading>
          <ds-text tone="muted">Choose what we send you and how often.</ds-text>
        </ds-stack>

        <ds-alert tone="info" live="off" heading="Applies to every device">
          <ds-text>These preferences follow your account, not this browser.</ds-text>
        </ds-alert>

        <ds-form name="preferences" label="Notification preferences">
          <ds-radio-group
            name="digest"
            label="Email digest"
            description="A single email that collects the activity you missed."
            .options=${digestOptions}
            default-value="weekly"
            required
          ></ds-radio-group>

          <ds-stack gap="0">
            <ds-checkbox
              name="mentions"
              label="Mentions and replies"
              description="When someone mentions you or replies to your comment."
              default-checked
            ></ds-checkbox>
            <ds-checkbox
              name="product"
              label="Product updates"
              description="About one email a month."
            ></ds-checkbox>
          </ds-stack>

          <ds-switch
            name="push"
            label="Push notifications"
            description="Delivered to this device right away."
            default-checked
          ></ds-switch>

          <ds-meter
            label="Attachment storage used"
            value="82"
            value-text="8.2 GB of 10 GB"
            tone="warning"
          ></ds-meter>

          <ds-disclosure summary="Advanced options" keep-mounted>
            <ds-checkbox
              name="quiet-hours"
              label="Pause notifications overnight"
              description="Nothing is sent between 22:00 and 07:00 in your time zone."
            ></ds-checkbox>
          </ds-disclosure>

          <ds-stack direction="horizontal" gap="2" align="center" wrap>
            <ds-button type="submit" label="Save"></ds-button>
            <ds-button variant="secondary" label="Cancel"></ds-button>
          </ds-stack>
        </ds-form>
      </ds-stack>
    </ds-landmark>
  `;
}

// packages/react/demo/Preferences.tsx
import {
  Alert,
  Breadcrumb,
  Button,
  Checkbox,
  Disclosure,
  Form,
  Heading,
  Landmark,
  Meter,
  RadioGroup,
  Stack,
  Switch,
  Text,
  type FormErrors,
  type FormValues,
} from '../src/index';

export interface PreferencesProps {
  /** Called with the collected values when the form passes validation. Defaults to logging the values. */
  onSubmit?: (values: FormValues) => void;
  /** Called with the errors keyed by field name when submission is blocked. */
  onInvalid?: (errors: FormErrors) => void;
  /** Called when "Cancel" is activated. */
  onCancel?: () => void;
  /** Called when the info alert is dismissed. */
  onDismissAlert?: () => void;
  /** Storage used, in GB, out of 10. Drives the meter. */
  storageUsedGb?: number;
}

const DIGEST_OPTIONS = [
  { value: 'daily', label: 'Daily', description: 'One summary each morning at 9:00' },
  { value: 'weekly', label: 'Weekly', description: 'One summary every Monday' },
  { value: 'never', label: 'Never', description: 'Only the notifications you enable below' },
];

const STORAGE_MAX_GB = 10;

/**
 * Notification-preferences screen composed from the Calm & precise React components:
 * Landmark (main) → Breadcrumb + Heading + Alert + Form → RadioGroup, Checkboxes, Switch, Meter,
 * Disclosure with advanced options, and the Save / Cancel actions.
 */
export function Preferences({ onSubmit, onInvalid, onCancel, onDismissAlert, storageUsedGb = 8.2 }: PreferencesProps) {
  const handleSubmit = (values: FormValues) => {
    if (onSubmit) {
      onSubmit(values);
    } else {
      console.log('Save preferences', values);
    }
  };

  const storageTone = storageUsedGb / STORAGE_MAX_GB >= 0.9 ? 'danger' : storageUsedGb / STORAGE_MAX_GB >= 0.75 ? 'warning' : 'info';

  return (
    <Landmark role="main">
      <Stack gap="6" align="stretch">
        <Stack gap="2">
          <Breadcrumb
            items={[
              { label: 'Settings', href: '/settings' },
              { label: 'Notifications', href: '/settings/notifications' },
            ]}
          />
          <Heading level="1" id="preferences-title">
            Notifications
          </Heading>
          <Text tone="muted">Choose how and when we contact you.</Text>
        </Stack>

        <Alert tone="info" heading="Changes apply from the next digest" dismissible onDismiss={onDismissAlert}>
          Notifications already scheduled for today are sent with your current settings.
        </Alert>

        <Form name="preferences" label="Notification preferences" validate="submit" onSubmit={handleSubmit} onInvalid={onInvalid}>
          <Stack gap="5">
            <RadioGroup label="Email digest" name="digest" options={DIGEST_OPTIONS} defaultValue="weekly" required />

            <Stack gap="0">
              <Checkbox
                label="Mentions"
                name="mentions"
                description="When someone mentions you in a comment."
                defaultChecked
              />
              <Checkbox label="Product updates" name="updates" description="One email a month about new features." />
            </Stack>

            <Switch
              label="Push notifications"
              name="push"
              description="Sent to this device as soon as something happens."
              defaultChecked
            />

            <Meter
              label="Attachment storage used"
              value={storageUsedGb}
              min={0}
              max={STORAGE_MAX_GB}
              valueText={`${storageUsedGb} GB of ${STORAGE_MAX_GB} GB`}
              tone={storageTone}
            />

            <Disclosure summary="Advanced options" keepMounted>
              <Checkbox
                label="Include attachments in digest emails"
                name="digestAttachments"
                description="Larger emails; counts against attachment storage."
              />
            </Disclosure>

            <Stack direction="horizontal" gap="2" align="center" wrap>
              <Button label="Save" type="submit" variant="primary" />
              <Button label="Cancel" variant="secondary" onClick={onCancel} />
            </Stack>
          </Stack>
        </Form>
      </Stack>
    </Landmark>
  );
}
