// packages/lit/src/BottomSheet.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Heading.js';
import './Button.js';
import './Icon.js';
import './Box.js';
import './Stack.js';
import './FocusScope.js';
import './Dialog.js';

export type BottomSheetHeight = 'content' | 'half' | 'full';
export type BottomSheetCloseReason = 'escape' | 'close-button' | 'scrim' | 'drag' | 'action';

/** Detail carried by the `close` CustomEvent. */
export interface BottomSheetCloseDetail {
  reason: BottomSheetCloseReason;
}

/** Detail carried by the `drag-dismiss` CustomEvent (none). */
export type BottomSheetDragDismissDetail = void;

/** Overridable style hooks; see the `overrides` property. `surface`, `handle`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type BottomSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'handleHeight'
  | 'handleWidth'
  | 'inset'
  | 'partGap'
  | 'footerGap'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

const HOOKS: Record<BottomSheetOverridableBinding, string> = {
  scrim: '--ds-bottom-sheet-scrim',
  shadow: '--ds-bottom-sheet-shadow',
  radius: '--ds-bottom-sheet-radius',
  handleHeight: '--ds-bottom-sheet-handle-height',
  handleWidth: '--ds-bottom-sheet-handle-width',
  inset: '--ds-bottom-sheet-inset',
  partGap: '--ds-bottom-sheet-part-gap',
  footerGap: '--ds-bottom-sheet-footer-gap',
  maxWidth: '--ds-bottom-sheet-max-width',
  layer: '--ds-bottom-sheet-layer',
  enter: '--ds-bottom-sheet-enter',
  exit: '--ds-bottom-sheet-exit',
};

/** copy.closeLabel */
const COPY_CLOSE_LABEL = 'Close';

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
  'ds-button',
  'ds-link',
  'ds-input',
  'ds-checkbox',
  'ds-switch',
  'ds-radio-group',
  'ds-disclosure',
].join(',');

function findFirstFocusable(root: Element): HTMLElement | null {
  if (root instanceof HTMLElement && root.matches(FOCUSABLE_SELECTOR)) {
    return root;
  }
  return root.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
}

/** How many `<ds-bottom-sheet>` instances (in their bottom-edge presentation) currently hold the body-scroll lock. */
let openSheetCount = 0;

function lockBodyScroll(): void {
  openSheetCount += 1;
  if (openSheetCount === 1) {
    document.documentElement.style.overflow = 'hidden';
  }
}

function unlockBodyScroll(): void {
  openSheetCount = Math.max(0, openSheetCount - 1);
  if (openSheetCount === 0) {
    document.documentElement.style.removeProperty('overflow');
  }
}

function getDeepActiveElement(): Element | null {
  let active = document.activeElement;
  while (active?.shadowRoot?.activeElement) {
    active = active.shadowRoot.activeElement;
  }
  return active;
}

function prefersReducedMotion(): boolean {
  return matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * `<ds-bottom-sheet>` — BottomSheet (category: overlay, APG pattern: dialog-modal).
 *
 * The phone's dialog: rises from the bottom edge behind a scrim, and above
 * the `maxWidth` breakpoint renders `<ds-dialog size="md">` instead — a
 * `matchMedia` listener on the resolved `layout.maxWidth.prose` token decides
 * which, so consumers write the screen once. Below the breakpoint a shadow
 * `<dialog>` is opened with `showModal()` for the top layer, background
 * inertness and `::backdrop` scrim; `<ds-focus-scope trapped>` wraps the
 * header, body and footer. A downward drag on the header (Pointer Events,
 * `setPointerCapture`) past a distance or velocity threshold fires
 * `drag-dismiss` then `close` with reason `drag`; it is purely additive, the
 * close button and Escape always work.
 *
 * ## When to use
 *
 * Use a BottomSheet on phones for a task or a set of choices that would
 * otherwise be a Dialog: filters, a form of a few fields, details of a
 * selected item, a picker with many options. Use `height="content"` by
 * default; `full` for a task that needs the whole screen but should still
 * feel dismissable; `half` for a browsable list where seeing the page behind
 * matters (a map with results). For a flat list of actions, ActionSheet is
 * the lighter component.
 *
 * ## When not to use
 *
 * Not as a menu (ActionSheet or Menu), a persistent panel (a bottom Landmark
 * region), or content the user must read at length (a page). Never stack
 * sheets, and never rely on the drag gesture as the only way to dismiss.
 *
 * @fires close - Requests close, with `{ reason: 'escape' | 'close-button' | 'scrim' | 'drag' | 'action' }`.
 *   The consumer sets `open` to false (or not).
 * @fires drag-dismiss - Fired before `close` (reason `drag`) when a drag gesture crosses the dismiss threshold.
 * @slot - The body. Scrolls inside the sheet when taller than the sheet's height.
 * @slot footer - Action row, pinned above the safe area.
 * @csspart surface - The padded, bordered surface (anatomy: surface).
 * @csspart focus-scope - The focus-trapping wrapper (anatomy: focusScope).
 * @csspart handle - The decorative drag handle (anatomy: handle).
 * @csspart header - The header row (anatomy: header).
 * @csspart title - The `<ds-heading>` (anatomy: title).
 * @csspart body - The body wrapper (anatomy: body).
 * @csspart footer - The footer row (anatomy: footer).
 * @csspart close-button - The close `<ds-button>` (anatomy: closeButton).
 */
@customElement('ds-bottom-sheet')
export class DsBottomSheet extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      --ds-bottom-sheet-scrim: var(--color-overlay-scrim);
      --ds-bottom-sheet-shadow: var(--shadow-overlay);
      --ds-bottom-sheet-radius: var(--radius-lg);
      --ds-bottom-sheet-handle-height: var(--space-1);
      --ds-bottom-sheet-handle-width: var(--space-10);
      --ds-bottom-sheet-inset: var(--layout-inset-lg);
      --ds-bottom-sheet-part-gap: var(--layout-gap-loose);
      --ds-bottom-sheet-footer-gap: var(--layout-gap-tight);
      --ds-bottom-sheet-max-width: var(--layout-max-width-prose);
      --ds-bottom-sheet-layer: var(--layer-sheet);
      --ds-bottom-sheet-enter: var(--motion-duration-base);
      --ds-bottom-sheet-exit: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    dialog {
      box-sizing: border-box;
      position: fixed;
      inset-block-end: 0;
      inset-inline: 0;
      margin: 0;
      padding: 0;
      border: 0;
      inline-size: 100%;
      max-inline-size: none;
      max-block-size: 90dvh;
      background: transparent;
      color: inherit;
      z-index: var(--ds-bottom-sheet-layer);
    }

    /* height: content (default) sizes to the body up to the dialog's own 90dvh max-block-size; half
       and full set an exact block-size instead, so the 90dvh cap must not also apply to them. */
    :host([height='half']) dialog {
      max-block-size: none;
      block-size: 50dvh;
    }
    :host([height='full']) dialog {
      max-block-size: none;
      block-size: calc(100dvh - var(--layout-gutter));
    }

    /* scrim: color.overlay.scrim */
    dialog::backdrop {
      background: var(--ds-bottom-sheet-scrim);
      transition: opacity var(--ds-bottom-sheet-enter) var(--motion-easing-standard);
    }

    @starting-style {
      dialog[open]::backdrop {
        opacity: 0;
      }
    }

    .surface {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      block-size: 100%;
      gap: var(--ds-bottom-sheet-part-gap);
      font-family: var(--font-family-body);
      /* surface: color.overlay.surface, locked — no override hook */
      background: var(--color-overlay-surface);
      /* radius: top corners only on phones; ds-dialog rounds all corners for the wide presentation */
      border-start-start-radius: var(--ds-bottom-sheet-radius);
      border-start-end-radius: var(--ds-bottom-sheet-radius);
      box-shadow: var(--ds-bottom-sheet-shadow);
      overflow: hidden;
      padding-block-end: env(safe-area-inset-bottom);
      transform: translateY(0);
      transition: transform var(--ds-bottom-sheet-enter) var(--motion-easing-standard);
    }

    .surface.closing {
      transform: translateY(100%);
      transition-duration: var(--ds-bottom-sheet-exit);
      transition-timing-function: var(--motion-easing-exit);
    }

    @starting-style {
      dialog[open] .surface {
        transform: translateY(100%);
      }
    }

    @media (prefers-reduced-motion: reduce) {
      dialog::backdrop,
      .surface {
        transition: none;
      }
    }

    .header {
      display: flex;
      flex-direction: column;
      gap: var(--layout-gap-tight);
      padding-inline: var(--ds-bottom-sheet-inset);
      padding-block-start: var(--layout-gap-tight);
      flex: 0 0 auto;
      touch-action: none;
    }

    /* handle: color.foreground.muted, locked — a 4×36 decorative pill, aria-hidden and not focusable */
    .handle {
      align-self: center;
      inline-size: var(--ds-bottom-sheet-handle-width);
      block-size: var(--ds-bottom-sheet-handle-height);
      border-radius: var(--radius-full);
      background: var(--color-foreground-muted);
    }

    .heading-row {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: var(--layout-gap-normal);
      min-inline-size: 0;
    }

    .title {
      min-inline-size: 0;
    }

    /* hideTitle: kept for the accessible name, removed from the visual layout. */
    .title--hidden {
      /* literal-ok: standard visually-hidden clip pattern, exempt from token-only rule */
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }

    #heading:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
      border-radius: var(--radius-sm);
    }

    .close {
      flex: none;
    }

    .body {
      flex: 1 1 auto;
      min-block-size: 0;
      overflow-y: auto;
    }
  `;

  /** Controlled visibility, as in Dialog. */
  @property({ type: Boolean, reflect: true }) open = false;

  /**
   * The sheet's title and accessible name. Named `heading`, not `title` —
   * `HTMLElement` already defines `title` as the tooltip attribute (see
   * Dialog and AlertDialog).
   */
  @property() heading!: string;

  /** Keep the title for assistive technology but do not render it. The accessible name is required regardless. */
  @property({ type: Boolean, attribute: 'hide-title' }) hideTitle = false;

  /** `content` sizes to the body up to 90% of the viewport; `half` is a fixed half-height; `full` is near-full-screen. */
  @property({ reflect: true }) height: BottomSheetHeight = 'content';

  /** Escape, the close button, a scrim tap and the drag gesture all request close. Escape still reports when false. */
  @property({ type: Boolean, reflect: true }) dismissible = true;

  /** Drag the handle (or header) downward to dismiss. Purely additive: the close button and Escape always exist. */
  @property({ type: Boolean, reflect: true }) draggable = true;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings (surface, handle, focusRing, focusRingWidth) are ignored. Only applied below the wide-viewport breakpoint; above it the sheet renders as Dialog and uses Dialog's own overrides contract. */
  @property({ attribute: false }) overrides?: Partial<Record<BottomSheetOverridableBinding, TokenRef>>;

  /** Above `layout.maxWidth.prose` the sheet renders as a centered `<ds-dialog size="md">` instead. */
  @state() private isWide = false;

  /** Whether the exit transition is playing (kept open a beat past the `open` flip so it can animate out). */
  @state() private closing = false;

  @query('dialog') private readonly dialogEl!: HTMLDialogElement;
  @query('#heading') private readonly headingEl!: HTMLElement;
  @query('.close') private readonly closeButtonEl!: HTMLElement;

  private openerElement: Element | null = null;
  private closingProgrammatically = false;
  private suppressCloseSync = false;
  private wideQuery: MediaQueryList | null = null;
  private dragState: { startY: number; startTime: number } | null = null;

  private readonly handleWideChange = (event: MediaQueryListEvent): void => {
    this.isWide = event.matches;
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'BottomSheet');
    const breakpoint = getComputedStyle(document.documentElement).getPropertyValue('--layout-max-width-prose').trim();
    if (breakpoint) {
      this.wideQuery = matchMedia(`(min-width: ${breakpoint})`);
      this.isWide = this.wideQuery.matches;
      this.wideQuery.addEventListener('change', this.handleWideChange);
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.wideQuery?.removeEventListener('change', this.handleWideChange);
    if (!this.isWide && this.dialogEl?.open) {
      unlockBodyScroll();
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (!this.isWide && changed.has('open')) {
      if (this.open) {
        this.handleOpen();
      } else if (changed.get('open') as boolean) {
        if (this.suppressCloseSync) {
          this.suppressCloseSync = false;
        } else {
          this.playExit();
        }
      }
    }
    this.warnInDev();
  }

  protected override render() {
    if (this.isWide) {
      return this.renderAsDialog();
    }
    return this.renderAsSheet();
  }

  private renderAsDialog() {
    return html`
      <ds-dialog ?open=${this.open} heading=${this.heading} size="md" ?dismissible=${this.dismissible}>
        <slot></slot>
        <slot name="footer" slot="footer"></slot>
      </ds-dialog>
    `;
  }

  private renderAsSheet() {
    const hasFooter = this.querySelector('[slot="footer"]') !== null;
    const titleClasses = classMap({ title: true, 'title--hidden': this.hideTitle });

    return html`
      <dialog
        aria-modal="true"
        aria-labelledby="heading"
        @cancel=${this.handleCancel}
        @close=${this.handleNativeClose}
        @click=${this.handleDialogClick}
      >
        <div class="surface${this.closing ? ' closing' : ''}" part="surface">
          <ds-focus-scope
            part="focus-scope"
            trapped
            ?active=${this.open}
            auto-focus="none"
            ?restore-focus=${false}
            style="display: flex; flex-direction: column; gap: var(--ds-bottom-sheet-part-gap)"
          >
            <div
              class="header"
              part="header"
              @pointerdown=${this.handleHeaderPointerDown}
              @pointermove=${this.handleHeaderPointerMove}
              @pointerup=${this.handleHeaderPointerUp}
              @pointercancel=${this.handleHeaderPointerUp}
            >
              <span class="handle" part="handle" aria-hidden="true"></span>
              <div class="heading-row">
                <ds-heading id="heading" part="title" class=${titleClasses} level="2" size="lg" tabindex="-1"
                  >${this.heading}</ds-heading
                >
                <ds-button
                  class="close"
                  part="close-button"
                  variant="ghost"
                  size="md"
                  icon-only
                  label=${COPY_CLOSE_LABEL}
                  @press=${this.handleCloseButtonPress}
                >
                  <ds-icon slot="leading-icon" name="close"></ds-icon>
                </ds-button>
              </div>
            </div>
            <ds-box class="body" part="body" inset="lg" .overrides=${this.bodyOverrides()}>
              <slot></slot>
            </ds-box>
            ${hasFooter
              ? html`
                  <ds-stack part="footer" direction="horizontal" justify="end" style="gap: var(--ds-bottom-sheet-footer-gap)">
                    <slot name="footer"></slot>
                  </ds-stack>
                `
              : nothing}
          </ds-focus-scope>
        </div>
      </dialog>
    `;
  }

  private bodyOverrides() {
    const inset = this.overrides?.inset;
    return inset ? { paddingBlock: inset, paddingInline: inset } : undefined;
  }

  private readonly handleCancel = (event: Event): void => {
    // The native default would close the <dialog> itself; the consumer owns `open` instead.
    event.preventDefault();
    this.dispatchClose('escape');
  };

  private readonly handleDialogClick = (event: MouseEvent): void => {
    if (!this.dismissible || event.target !== this.dialogEl) {
      return;
    }
    this.dispatchClose('scrim');
  };

  private readonly handleCloseButtonPress = (event: Event): void => {
    // Keep the button's `press` inside the sheet; consumers listen for `close`.
    event.stopPropagation();
    if (!this.dismissible) {
      return;
    }
    this.dispatchClose('close-button');
  };

  private readonly handleNativeClose = (): void => {
    if (this.closingProgrammatically) {
      this.closingProgrammatically = false;
      return;
    }
    unlockBodyScroll();
    this.restoreFocus();
    this.suppressCloseSync = true;
    this.open = false;
    this.dispatchClose('action');
  };

  private readonly handleHeaderPointerDown = (event: PointerEvent): void => {
    if (!this.draggable) {
      return;
    }
    if ((event.target as HTMLElement).closest('.close')) {
      return;
    }
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      return;
    }
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
    this.dragState = { startY: event.clientY, startTime: event.timeStamp };
    surface.style.transition = 'none';
  };

  private readonly handleHeaderPointerMove = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!drag || !surface) {
      return;
    }
    const deltaY = Math.max(0, event.clientY - drag.startY);
    surface.style.transform = `translateY(${deltaY}px)`;
  };

  private readonly handleHeaderPointerUp = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    this.dragState = null;
    if (!drag || !surface) {
      return;
    }

    const deltaY = Math.max(0, event.clientY - drag.startY);
    const elapsed = Math.max(1, event.timeStamp - drag.startTime);
    const velocity = deltaY / elapsed;
    const sheetHeight = surface.getBoundingClientRect().height || 1;
    const pastThreshold = deltaY / sheetHeight > 0.25 || velocity > 0.5;

    surface.style.transition = prefersReducedMotion() ? 'none' : '';
    surface.style.transform = '';

    if (pastThreshold && this.dismissible) {
      this.dispatchEvent(
        new CustomEvent<BottomSheetDragDismissDetail>('drag-dismiss', { bubbles: true, composed: true }),
      );
      this.dispatchClose('drag');
    }
  };

  private handleOpen(): void {
    this.closing = false;
    this.openerElement = getDeepActiveElement();
    lockBodyScroll();
    this.dialogEl.showModal();
    this.applyInitialFocus();
  }

  private playExit(): void {
    const finish = (): void => {
      this.closingProgrammatically = true;
      this.dialogEl.close();
      unlockBodyScroll();
      this.restoreFocus();
      this.closing = false;
    };
    if (prefersReducedMotion()) {
      finish();
      return;
    }
    this.closing = true;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      finish();
      return;
    }
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target !== surface || event.propertyName !== 'transform') {
        return;
      }
      surface.removeEventListener('transitionend', handleTransitionEnd);
      finish();
    };
    surface.addEventListener('transitionend', handleTransitionEnd);
  }

  private applyInitialFocus(): void {
    const target = this.findFirstBodyFocusable() ?? this.closeButtonEl ?? this.headingEl;
    target?.focus();
  }

  private findFirstBodyFocusable(): HTMLElement | null {
    const slot = this.renderRoot.querySelector<HTMLSlotElement>('slot:not([name])');
    if (!slot) {
      return null;
    }
    for (const element of slot.assignedElements({ flatten: true })) {
      const found = findFirstFocusable(element);
      if (found) {
        return found;
      }
    }
    return null;
  }

  private restoreFocus(): void {
    const opener = this.openerElement;
    this.openerElement = null;
    if (opener instanceof HTMLElement && opener.isConnected) {
      opener.focus();
    }
  }

  private dispatchClose(reason: BottomSheetCloseReason): void {
    this.dispatchEvent(
      new CustomEvent<BottomSheetCloseDetail>('close', { detail: { reason }, bubbles: true, composed: true }),
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as BottomSheetOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.heading) {
      console.warn('<ds-bottom-sheet> requires a `heading`, used as the accessible name.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-bottom-sheet': DsBottomSheet;
  }
}

// packages/rn/src/BottomSheet.tsx
import * as React from 'react';
import {
  Animated,
  Modal,
  PanResponder,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  View,
  useWindowDimensions,
} from 'react-native';
import type { LayoutChangeEvent, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Box } from './Box';
import { Button } from './Button';
import { Dialog } from './Dialog';
import type { DialogOverridableBinding } from './Dialog';
import { FocusScope } from './FocusScope';
import { Heading } from './Heading';
import { Icon } from './Icon';
import { Stack } from './Stack';
import { toEasing, useReducedMotion, useTheme } from './theme';

export type BottomSheetHeight = 'content' | 'half' | 'full';
/** Why `onClose` fired. `action` is never emitted by BottomSheet itself — it exists for a consumer whose footer action also wants to report a close through the same callback. */
export type BottomSheetCloseReason = 'escape' | 'close-button' | 'scrim' | 'drag' | 'action';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type BottomSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'handleHeight'
  | 'handleWidth'
  | 'inset'
  | 'partGap'
  | 'footerGap'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

export interface BottomSheetProps {
  /** Controlled visibility, as in Dialog. */
  open: boolean;
  /** The sheet's title and accessible name. May be visually hidden with `hideTitle` when the content is self-explanatory (a share sheet). */
  title: string;
  /** Keep the title for assistive technology but do not render it. The accessible name is required regardless. */
  hideTitle?: boolean;
  /** The body. Scrolls inside the sheet when taller than the sheet's height. */
  children: React.ReactNode;
  /** Action row, pinned to the bottom of the sheet above the safe area. */
  footer?: React.ReactNode;
  /** `content` sizes to the body up to 90% of the viewport; `half` is a fixed half-height; `full` is a near-full-screen sheet with the top gutter visible so the scrim still shows. */
  height?: BottomSheetHeight;
  /** Escape, the close button, a scrim tap and the drag gesture all request close. When false, only the footer actions close it; Escape still reports. */
  dismissible?: boolean;
  /** Drag the handle (or the sheet) downward to dismiss, with a velocity threshold. Purely additive: the close button and Escape always exist. */
  draggable?: boolean;
  /** Requested close with reason: `escape`, `close-button`, `scrim`, `drag`, or `action`. */
  onClose?: (reason: BottomSheetCloseReason) => void;
  /** The user dragged the sheet past the dismiss threshold. Fired before `onClose` with reason drag; provided so analytics can distinguish gestures. */
  onDragDismiss?: () => void;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<BottomSheetOverridableBinding, TokenRef>>;
}

const COPY = {
  closeLabel: 'Close',
} as const;

// The bindings BottomSheet shares with Dialog's own overrides contract, forwarded
// when the sheet presents as a Dialog above `maxWidth`; `handleHeight`, `handleWidth`
// and `maxWidth` have no Dialog equivalent and are dropped.
const SHARED_DIALOG_BINDING: Partial<Record<BottomSheetOverridableBinding, DialogOverridableBinding>> = {
  scrim: 'scrim',
  shadow: 'shadow',
  radius: 'radius',
  inset: 'inset',
  partGap: 'partGap',
  footerGap: 'footerGap',
  layer: 'layer',
  enter: 'enter',
  exit: 'exit',
};

const DRAG_DISMISS_RATIO = 0.25; // literal-ok: fraction of sheet height past which a drag dismisses, per spec ("> 25%" on web)
const DRAG_DISMISS_VELOCITY = 1.5; // literal-ok: release velocity (px/ms) past which a drag dismisses regardless of distance

/**
 * BottomSheet — the phone's dialog. Rises from the edge the thumb can reach, keeps
 * the page visible behind a scrim, and goes away with a swipe, a tap outside, the
 * close button or Escape.
 *
 * When to use: Use on phones for a task or a set of choices that would otherwise be
 * a Dialog: filters, a short form, details of a selected item, a picker with many
 * options. `height: content` by default; `full` for a task that needs the whole
 * screen but should still feel dismissable; `half` for a browsable list where seeing
 * the page behind matters. Do not use it as a menu (ActionSheet/Menu), a persistent
 * panel (Landmark), or for content the user must read at length (a page). Do not
 * stack sheets or rely on the drag gesture as the only way to dismiss.
 *
 * Renders a native `Modal` (`transparent`, `statusBarTranslucent`) with a full-screen
 * scrim `Pressable` and an `Animated.View` surface anchored to the bottom, sliding up
 * on open (skipped under reduced motion). The surface composes `FocusScope`
 * (`trapped`, `restoreFocus`) for the trap and focus-restore-on-close, `Heading`
 * (level 2) for the title, `Button` for the close control, `Box` for the scrollable
 * body and `Stack` for the footer row — never restyled directly. A `PanResponder` on
 * the header (handle plus title row) tracks a downward drag; past 25% of the measured
 * surface height or a fast flick, it fires `onDragDismiss` then `onClose('drag')` and
 * continues the motion off-screen with `Animated.decay` at the release velocity
 * (instant, no decay, under reduced motion); otherwise it springs back. The gesture
 * is additive — the close button and Escape (mapped from the Android back button via
 * `onRequestClose`) always exist and are never gated by `draggable`, only by
 * `dismissible`. `height` sets the surface's fixed height as a fraction of
 * `useWindowDimensions()` for `half`/`full`, or lets it size to content up to 90% of
 * the viewport (`content`). Bottom padding for the footer uses `SafeAreaView`, the
 * only inset mechanism available without a new dependency. Above `maxWidth`, the
 * component renders `Dialog` directly (composition, not duplication) with the shared
 * bindings forwarded through `overrides`; `hideTitle` has no Dialog equivalent, so the
 * title always renders in that presentation. Scroll-lock has no native equivalent —
 * there is no page scroll for a modal window to suppress — so it is not implemented,
 * the same acknowledged limit as Dialog.
 */
export function BottomSheet({
  open,
  title,
  hideTitle = false,
  children,
  footer,
  height = 'content',
  dismissible = true,
  draggable = true,
  onClose,
  onDragDismiss,
  overrides,
}: BottomSheetProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const { height: windowHeight, width: windowWidth } = useWindowDimensions();

  const [mounted, setMounted] = React.useState(open);
  const progress = React.useRef(new Animated.Value(open ? 1 : 0)).current;
  const dragY = React.useRef(new Animated.Value(0)).current;
  const surfaceHeightRef = React.useRef(0);

  const scrimColor = overrides?.scrim ? (resolveToken(t, overrides.scrim) as string) : t.colorOverlayScrim;
  const surfaceColor = t.colorOverlaySurface;
  const shadow = overrides?.shadow ? (resolveToken(t, overrides.shadow) as typeof t.shadowOverlay) : t.shadowOverlay;
  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusLg;
  const handleHeight = overrides?.handleHeight ? (resolveToken(t, overrides.handleHeight) as number) : t.space1;
  const handleWidth = overrides?.handleWidth ? (resolveToken(t, overrides.handleWidth) as number) : t.space10;
  const inset = overrides?.inset ? (resolveToken(t, overrides.inset) as number) : t.layoutInsetLg;
  const partGap = overrides?.partGap ? (resolveToken(t, overrides.partGap) as number) : t.layoutGapLoose;
  const maxWidth = overrides?.maxWidth ? (resolveToken(t, overrides.maxWidth) as number) : t.layoutMaxWidthProse;
  const layer = overrides?.layer ? (resolveToken(t, overrides.layer) as number) : t.layerSheet;
  const enterDuration = overrides?.enter ? (resolveToken(t, overrides.enter) as number) : t.motionDurationBase;
  const exitDuration = overrides?.exit ? (resolveToken(t, overrides.exit) as number) : t.motionDurationFast;

  const isWide = windowWidth > maxWidth;

  React.useEffect(() => {
    if (open) {
      setMounted(true);
    }
  }, [open]);

  React.useEffect(() => {
    if (!mounted) {
      return undefined;
    }
    if (open) {
      dragY.setValue(0);
      if (reducedMotion) {
        progress.setValue(1);
        return undefined;
      }
      const animation = Animated.timing(progress, {
        toValue: 1,
        duration: enterDuration,
        easing: toEasing(t.motionEasingStandard),
        // react-native-web has no native animated module.
        useNativeDriver: false,
      });
      animation.start();
      return () => animation.stop();
    }
    if (reducedMotion) {
      progress.setValue(0);
      setMounted(false);
      return undefined;
    }
    const animation = Animated.timing(progress, {
      toValue: 0,
      duration: exitDuration,
      easing: toEasing(t.motionEasingExit),
      useNativeDriver: false,
    });
    animation.start(({ finished }) => {
      if (finished) {
        setMounted(false);
      }
    });
    return () => animation.stop();
    // Reacts to the open/closed transition and the mount gate it drives; the
    // animation's own config is read fresh each run rather than tracked as a dep.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, mounted, reducedMotion]);

  React.useEffect(() => {
    if (__DEV__ && footer === undefined && !dismissible) {
      console.warn('BottomSheet: with no footer and dismissible={false}, provide a way to close the sheet in its body.');
    }
  }, [footer, dismissible]);

  const handleScrimPress = (): void => {
    if (dismissible) {
      onClose?.('scrim');
    }
  };

  const handleCloseButtonPress = (): void => {
    onClose?.('close-button');
  };

  const handleRequestClose = (): void => {
    onClose?.('escape');
  };

  const handleSurfaceLayout = (event: LayoutChangeEvent): void => {
    surfaceHeightRef.current = event.nativeEvent.layout.height;
  };

  const panResponder = React.useMemo(
    () =>
      PanResponder.create({
        // False at touch-start so a tap on the close button inside the header is not
        // stolen by the responder; only an actual downward drag claims it.
        onStartShouldSetPanResponder: () => false,
        onMoveShouldSetPanResponder: (_, gestureState) =>
          draggable && dismissible && gestureState.dy > 4 && Math.abs(gestureState.dy) > Math.abs(gestureState.dx),
        onPanResponderMove: (_, gestureState) => {
          if (gestureState.dy > 0) {
            dragY.setValue(gestureState.dy);
          }
        },
        onPanResponderRelease: (_, gestureState) => {
          const threshold = (surfaceHeightRef.current || windowHeight * 0.5) * DRAG_DISMISS_RATIO;
          const shouldDismiss = gestureState.dy > threshold || gestureState.vy > DRAG_DISMISS_VELOCITY;
          if (shouldDismiss) {
            onDragDismiss?.();
            onClose?.('drag');
            if (reducedMotion) {
              dragY.setValue(windowHeight);
            } else {
              Animated.decay(dragY, {
                velocity: Math.max(gestureState.vy, 0.5),
                deceleration: 0.998,
                useNativeDriver: false,
              }).start();
            }
            return;
          }
          if (reducedMotion) {
            dragY.setValue(0);
            return;
          }
          Animated.timing(dragY, {
            toValue: 0,
            duration: exitDuration,
            easing: toEasing(t.motionEasingStandard),
            useNativeDriver: false,
          }).start();
        },
        onPanResponderTerminate: () => {
          if (reducedMotion) {
            dragY.setValue(0);
            return;
          }
          Animated.timing(dragY, { toValue: 0, duration: exitDuration, useNativeDriver: false }).start();
        },
      }),
    [draggable, dismissible, dragY, windowHeight, onDragDismiss, onClose, reducedMotion, exitDuration, t.motionEasingStandard],
  );

  if (isWide) {
    const dialogOverrides = overrides
      ? (Object.fromEntries(
          Object.entries(overrides)
            .map(([key, value]) => [SHARED_DIALOG_BINDING[key as BottomSheetOverridableBinding], value] as const)
            .filter((entry): entry is [DialogOverridableBinding, TokenRef] => entry[0] !== undefined),
        ) as Partial<Record<DialogOverridableBinding, TokenRef>>)
      : undefined;
    return (
      <Dialog open={open} heading={title} size="md" dismissible={dismissible} footer={footer} onClose={onClose} overrides={dialogOverrides}>
        {children}
      </Dialog>
    );
  }

  const hostStyle: ViewStyle = { flex: 1 };

  const scrimStyle: Animated.WithAnimatedObject<ViewStyle> = {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: scrimColor,
    opacity: progress,
  };

  const anchorStyle: ViewStyle = { flex: 1, justifyContent: 'flex-end', zIndex: layer };

  const entryTranslateY = progress.interpolate({ inputRange: [0, 1], outputRange: [windowHeight, 0] });

  const fixedHeight = height === 'half' ? windowHeight * 0.5 : height === 'full' ? windowHeight - t.layoutGutter : undefined;

  const surfaceStyle: Animated.WithAnimatedObject<ViewStyle> = {
    width: '100%',
    height: fixedHeight,
    maxHeight: height === 'content' ? windowHeight * 0.9 : undefined, // literal-ok: proportion of viewport per spec ("up to 90%")
    borderTopLeftRadius: radius,
    borderTopRightRadius: radius,
    ...shadow,
    backgroundColor: surfaceColor,
    overflow: 'hidden',
    gap: partGap,
    transform: [{ translateY: Animated.add(entryTranslateY, dragY) }],
  };

  const headerStyle: ViewStyle = {
    paddingHorizontal: inset,
    paddingTop: t.spaceSm, // not named by any binding; matches Dialog's title-group gap precedent
    gap: t.layoutGapTight,
  };

  const handleStyle: ViewStyle = {
    alignSelf: 'center',
    width: handleWidth,
    height: handleHeight,
    borderRadius: t.radiusFull,
    backgroundColor: t.colorForegroundMuted,
  };

  const titleRowStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: t.layoutGapNormal,
  };

  const bodyFlexStyle: ViewStyle = { flexShrink: 1 };
  const bodyContentStyle: ViewStyle = { flexGrow: 1 };

  const footerStyle: ViewStyle = {
    paddingHorizontal: inset,
    paddingBottom: inset,
  };

  return (
    <Modal visible={mounted} transparent onRequestClose={handleRequestClose} statusBarTranslucent>
      <View style={hostStyle}>
        <Animated.View style={scrimStyle} />
        <Pressable
          style={StyleSheet.absoluteFillObject}
          onPress={handleScrimPress}
          accessible={false}
          testID="BottomSheet.scrim"
        />
        <View style={anchorStyle} pointerEvents="box-none">
          <FocusScope trapped active={mounted} autoFocus="first" restoreFocus>
            <Animated.View
              style={surfaceStyle}
              onLayout={handleSurfaceLayout}
              accessibilityViewIsModal
              accessibilityLabel={title}
              testID="BottomSheet"
            >
              <View {...(draggable && dismissible ? panResponder.panHandlers : null)} style={headerStyle} testID="BottomSheet.header">
                <View style={handleStyle} accessibilityElementsHidden importantForAccessibility="no" testID="BottomSheet.handle" />
                <View style={titleRowStyle}>
                  {!hideTitle ? <Heading level={2}>{title}</Heading> : null}
                  <Button
                    label={COPY.closeLabel}
                    variant="ghost"
                    size="sm"
                    iconOnly
                    disabled={!dismissible}
                    leadingIcon={<Icon name="close" color={t.colorActionGhostForeground} />}
                    onPress={handleCloseButtonPress}
                  />
                </View>
              </View>
              <ScrollView
                testID="BottomSheet.body"
                style={bodyFlexStyle}
                contentContainerStyle={bodyContentStyle}
                keyboardShouldPersistTaps="handled"
              >
                <Box inset="lg" overrides={overrides?.inset ? { paddingBlock: overrides.inset, paddingInline: overrides.inset } : undefined}>
                  {children}
                </Box>
              </ScrollView>
              {footer !== undefined ? (
                <SafeAreaView style={footerStyle} testID="BottomSheet.footer">
                  <Stack
                    direction="horizontal"
                    gap="tight"
                    justify="end"
                    overrides={overrides?.footerGap ? { gap: overrides.footerGap } : undefined}
                  >
                    {footer}
                  </Stack>
                </SafeAreaView>
              ) : null}
            </Animated.View>
          </FocusScope>
        </View>
      </View>
    </Modal>
  );
}
