// packages/lit/src/Card.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Heading.js';

export type CardHeadingLevel = '2' | '3' | '4' | '5' | '6';
export type CardInset = 'sm' | 'md' | 'lg';
export type CardSurface = 'default' | 'subtle';

/** Overridable style hooks; see the `overrides` property. `background`, `hoverBackground`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type CardOverridableBinding =
  | 'paddingBlock'
  | 'paddingInline'
  | 'partGap'
  | 'headerGap'
  | 'footerGap'
  | 'actionsGap'
  | 'border'
  | 'borderWidth'
  | 'radius'
  | 'transition';

const HOOKS: Record<CardOverridableBinding, string> = {
  paddingBlock: '--ds-card-padding-block',
  paddingInline: '--ds-card-padding-inline',
  partGap: '--ds-card-part-gap',
  headerGap: '--ds-card-header-gap',
  footerGap: '--ds-card-footer-gap',
  actionsGap: '--ds-card-actions-gap',
  border: '--ds-card-border',
  borderWidth: '--ds-card-border-width',
  radius: '--ds-card-radius',
  transition: '--ds-card-transition',
};

/** Elements an interactive Card treats as its single action target. */
const HIT_AREA_SELECTOR = 'ds-link, ds-button, a[href], button';
/** Marks the light-DOM link/button whose hit area extends across the whole card. */
const HIT_AREA_CLASS = 'ds-card-hit-area';
/** The target itself stays unpositioned so its `::after` resolves against the card host (`position: relative`). */
const HIT_AREA_STYLE = `.${HIT_AREA_CLASS}::after { content: ''; position: absolute; inset: 0; }`;

/** Roots that already carry the hit-area rule (a Document per page, a ShadowRoot per nesting host). */
const styledHitAreaRoots = new WeakSet<Document | ShadowRoot>();

/**
 * Injects the hit-area pseudo-element rule once into the tree the slotted link
 * or button lives in (the document head, or the nearest ancestor shadow root).
 * A shadow stylesheet cannot give light-DOM content an `::after`.
 */
function ensureHitAreaStyle(root: Node): void {
  if (!(root instanceof Document || root instanceof ShadowRoot) || styledHitAreaRoots.has(root)) {
    return;
  }
  styledHitAreaRoots.add(root);
  const target = root instanceof Document ? root.head : root;
  if (target.querySelector(`style[data-${HIT_AREA_CLASS}]`) !== null) {
    return;
  }
  const style = document.createElement('style');
  style.setAttribute(`data-${HIT_AREA_CLASS}`, '');
  style.textContent = HIT_AREA_STYLE;
  target.appendChild(style);
}

/**
 * `<ds-card>` — Card (category: container).
 *
 * `<ds-card heading="Plan" heading-level="3" inset="md">…</ds-card>`. With a
 * `heading` the host is `role="article"` named by `aria-label` (ids do not
 * cross the shadow root); without one it has no role. Inside the shadow root a
 * surface holds the header row (`<ds-heading size="lg">` plus the
 * `header-actions` slot, shown when either is present), the default slot as
 * the body, and the footer row (shown when footer content is slotted). The
 * rows are the card's own flex rows so their gaps stay overridable.
 *
 * `interactive` extends the single slotted `ds-link`/`ds-button` (or raw
 * `a[href]`/`button`) in the default slot across the whole card and draws the
 * ring on the card via `:focus-within`; the card is never a focus stop.
 * `focusable` gives the host `tabindex="-1"` for scripted focus (Feed) and
 * draws the ring on `:focus-visible`; with `interactive` it is a no-op.
 *
 * @slot - The body. Usually a Stack of Text and controls.
 * @slot header-actions - Controls at the end of the header row — a ghost icon-only Button, a Link. At most two.
 * @slot footer - The action row. Buttons in a row, primary first, following Form's action-order rule.
 */
@customElement('ds-card')
export class DsCard extends LitElement {
  static override styles: CSSResult = css`
    :host {
      display: block;
      box-sizing: border-box;
      --ds-card-padding-block: var(--layout-inset-md);
      --ds-card-padding-inline: var(--layout-inset-md);
      --ds-card-part-gap: var(--layout-gap-loose);
      --ds-card-header-gap: var(--layout-gap-normal);
      --ds-card-footer-gap: var(--layout-gap-tight);
      --ds-card-actions-gap: var(--layout-gap-tight);
      --ds-card-border: var(--color-border);
      --ds-card-border-width: var(--border-width-thin);
      --ds-card-radius: var(--radius-lg);
      --ds-card-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    /* paddingBlock / paddingInline: layout.inset.{inset} */
    :host([inset='sm']) {
      --ds-card-padding-block: var(--layout-inset-sm);
      --ds-card-padding-inline: var(--layout-inset-sm);
    }
    :host([inset='md']) {
      --ds-card-padding-block: var(--layout-inset-md);
      --ds-card-padding-inline: var(--layout-inset-md);
    }
    :host([inset='lg']) {
      --ds-card-padding-block: var(--layout-inset-lg);
      --ds-card-padding-inline: var(--layout-inset-lg);
    }

    [data-part='surface'] {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      gap: var(--ds-card-part-gap);
      padding-block: var(--ds-card-padding-block);
      padding-inline: var(--ds-card-padding-inline);
      border-style: solid;
      border-width: 0;
      border-color: transparent;
      border-radius: var(--ds-card-radius);
      /* background: color.background.{surface}, locked; default drops the segment */
      background-color: var(--color-background);
    }

    :host([surface='subtle']) [data-part='surface'] {
      background-color: var(--color-background-subtle);
    }

    /* borderWidth / border: rendered only with surface default */
    :host([surface='default']) [data-part='surface'] {
      border-width: var(--ds-card-border-width);
      border-color: var(--ds-card-border);
    }

    /* headerGap: layout.gap.normal, between the heading and headerActions */
    [data-part='header'] {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: var(--ds-card-header-gap);
      min-inline-size: 0;
    }

    /* actionsGap: layout.gap.tight, between the headerActions controls */
    [data-part='headerActions'] {
      display: flex;
      align-items: center;
      gap: var(--ds-card-actions-gap);
      flex: 0 0 auto;
      margin-inline-start: auto;
    }

    [data-part='body'] {
      display: block;
      min-inline-size: 0;
    }

    /* footerGap: layout.gap.tight, between footer actions */
    [data-part='footer'] {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: var(--ds-card-footer-gap);
    }

    [hidden] {
      display: none;
    }

    /*
     * interactive: position context for the slotted target's ::after. The card always reserves
     * border.width.focus, transparent until focused, so the ring never shifts the layout.
     */
    :host([interactive]) {
      position: relative;
    }
    :host([interactive]) [data-part='surface'] {
      border-width: var(--border-width-focus);
      border-color: transparent;
      transition:
        background-color var(--ds-card-transition) var(--motion-easing-standard),
        border-color var(--ds-card-transition) var(--motion-easing-standard);
    }
    /* Header actions and footer controls keep their own targets above the extended hit area. */
    :host([interactive]) [data-part='headerActions'],
    :host([interactive]) [data-part='footer'] {
      position: relative;
      z-index: 1;
    }

    /* hoverBackground: color.background.subtle, locked; subtle cards use color.background.strong */
    :host([interactive]:hover) [data-part='surface'] {
      background-color: var(--color-background-subtle);
    }
    :host([interactive][surface='subtle']:hover) [data-part='surface'] {
      background-color: var(--color-background-strong);
    }

    /* focusRing / focusRingWidth: locked; drawn on the card while its target has focus */
    :host([interactive]:focus-within) [data-part='surface'] {
      border-color: var(--color-border-focus);
    }

    /* focusable: scripted focus only; the card draws its own ring */
    :host([focusable]:not([interactive])) {
      outline: none;
    }
    :host([focusable]:not([interactive]):focus-visible) [data-part='surface'] {
      outline: var(--border-width-focus) solid var(--color-border-focus);
    }

    @media (prefers-reduced-motion: reduce) {
      :host([interactive]) [data-part='surface'] {
        transition: none;
      }
    }
  `;

  /** The card's title, rendered as a Heading at the card's level. Omit for cards that are a single piece of content. */
  @property() accessor heading: string | undefined;

  /** Heading level for `heading`, so cards fit the page outline. Cards in a list share a level. */
  @property({ type: String, reflect: true, attribute: 'heading-level' }) accessor headingLevel: CardHeadingLevel = '3';

  /** Padding inside the card from the layout inset presets. `sm` for dense grids, `lg` for a single featured card. */
  @property({ type: String, reflect: true }) accessor inset: CardInset = 'md';

  /** `default` is the page background with a border — the calm option; `subtle` is a tinted surface without a border. */
  @property({ type: String, reflect: true }) accessor surface: CardSurface = 'default';

  /**
   * The whole card is one link or button target. Requires exactly one
   * interactive child (a Link or Button) whose action the card extends to its
   * full area; the card itself is not focusable.
   */
  @property({ type: Boolean, reflect: true }) accessor interactive = false;

  /**
   * The card root takes tabindex=-1 so a container (Feed) can move focus to it
   * by script, and draws its own focus ring when focused that way. Not a tab
   * stop. With `interactive` also set, `interactive` wins and this is a no-op.
   */
  @property({ type: Boolean, reflect: true }) accessor focusable = false;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings are not accepted. */
  @property({ attribute: false }) accessor overrides: Partial<Record<CardOverridableBinding, TokenRef | undefined>> | undefined;

  @state() private accessor hasHeaderActions = false;
  @state() private accessor hasFooter = false;

  private hitAreaTarget: Element | null = null;
  /** Host attributes this element wrote, so a consumer's own `role`/`tabindex` is never removed. */
  private ownsRole = false;
  private ownsTabindex = false;

  constructor() {
    super();
    this.addEventListener('click', this.handleHostClick);
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Card');
    this.hasHeaderActions = this.querySelector(':scope > [slot="header-actions"]') !== null;
    this.hasFooter = this.querySelector(':scope > [slot="footer"]') !== null;
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('heading')) {
      this.syncName();
    }
    if (changed.has('focusable') || changed.has('interactive')) {
      this.syncTabindex();
    }
  }

  protected override render(): TemplateResult {
    const hasHeading = Boolean(this.heading);
    return html`
      <div part="surface" data-part="surface">
        <div part="header" data-part="header" ?hidden=${!hasHeading && !this.hasHeaderActions}>
          ${hasHeading
            ? html`<ds-heading part="heading" data-part="heading" level=${this.headingLevel} size="lg"
                >${this.heading}</ds-heading
              >`
            : nothing}
          <slot
            name="header-actions"
            data-part="headerActions"
            @slotchange=${this.handleHeaderActionsSlotChange}
          ></slot>
        </div>
        <slot data-part="body" @slotchange=${this.handleBodySlotChange}></slot>
        <div part="footer" data-part="footer" ?hidden=${!this.hasFooter}>
          <slot name="footer" @slotchange=${this.handleFooterSlotChange}></slot>
        </div>
      </div>
    `;
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('interactive')) {
      this.syncHitArea();
    }
  }

  private handleHeaderActionsSlotChange(event: Event): void {
    const next = (event.target as HTMLSlotElement).assignedNodes({ flatten: true }).length > 0;
    if (this.hasHeaderActions !== next) this.hasHeaderActions = next;
  }

  private handleFooterSlotChange(event: Event): void {
    const next = (event.target as HTMLSlotElement).assignedNodes({ flatten: true }).length > 0;
    if (this.hasFooter !== next) this.hasFooter = next;
  }

  private handleBodySlotChange(): void {
    this.syncHitArea();
  }

  /** Finds the single interactive child in the body and marks it as the card's extended hit area. */
  private syncHitArea(): void {
    const slot = this.renderRoot.querySelector<HTMLSlotElement>('slot:not([name])');
    const candidates = this.interactive && slot !== null
      ? slot.assignedElements({ flatten: true }).flatMap((element) =>
          element.matches(HIT_AREA_SELECTOR) ? [element] : Array.from(element.querySelectorAll(HIT_AREA_SELECTOR)),
        )
      : [];
    const [target, ...rest] = candidates;
    const next = target !== undefined && rest.length === 0 ? target : null;
    if (this.hitAreaTarget !== null && this.hitAreaTarget !== next) {
      this.hitAreaTarget.classList.remove(HIT_AREA_CLASS);
    }
    this.hitAreaTarget = next;
    if (next !== null) {
      ensureHitAreaStyle(next.getRootNode());
      if (!next.classList.contains(HIT_AREA_CLASS)) next.classList.add(HIT_AREA_CLASS);
    } else if (this.interactive && import.meta.env.DEV) {
      console.warn(
        `<ds-card interactive> requires exactly one interactive child (a ds-link or ds-button); found ${candidates.length}. The card stays non-interactive.`,
      );
    }
  }

  /**
   * A click on the extended area lands on the target's own host box (its `::after`), not on the
   * native control inside a `ds-link`/`ds-button` shadow root, so it is forwarded to that control.
   */
  private readonly handleHostClick = (event: MouseEvent): void => {
    const target = this.hitAreaTarget;
    if (target === null || !this.interactive || event.composedPath()[0] !== target || target.shadowRoot === null) {
      return;
    }
    const control = target.shadowRoot.querySelector<HTMLElement>('a[href], button');
    control?.click();
  };

  /** `role="article"` named by `aria-label` when a heading is set; plain attributes so accessible-name tests see them. */
  private syncName(): void {
    if (this.heading) {
      if (!this.hasAttribute('role') || this.ownsRole) {
        if (this.getAttribute('role') !== 'article') this.setAttribute('role', 'article');
        this.ownsRole = true;
      }
      if (this.getAttribute('aria-label') !== this.heading) this.setAttribute('aria-label', this.heading);
    } else {
      if (this.ownsRole) {
        this.removeAttribute('role');
        this.ownsRole = false;
      }
      this.removeAttribute('aria-label');
    }
  }

  private syncTabindex(): void {
    if (this.focusable && this.interactive && import.meta.env.DEV) {
      console.warn('<ds-card>: `focusable` has no effect with `interactive`; the card already has a target.');
    }
    if (this.focusable && !this.interactive) {
      if (this.getAttribute('tabindex') !== '-1') this.setAttribute('tabindex', '-1');
      this.ownsTabindex = true;
    } else if (this.ownsTabindex) {
      this.removeAttribute('tabindex');
      this.ownsTabindex = false;
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as CardOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-card': DsCard;
  }
}

// packages/rn/src/Card.tsx
import * as React from 'react';
import { Linking, Pressable, View } from 'react-native';
import type { ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import type { ButtonProps } from './Button';
import { Heading } from './Heading';
import { Link, LINK_EXTERNAL_SUFFIX } from './Link';
import type { LinkProps } from './Link';
import { useTheme } from './theme';
import type { Tokens } from './theme';

/** Heading level for `heading`. The schema declares the values as strings; numbers are accepted too. */
export type CardHeadingLevel = '2' | '3' | '4' | '5' | '6' | 2 | 3 | 4 | 5 | 6;
export type CardInset = 'sm' | 'md' | 'lg';
export type CardSurface = 'default' | 'subtle';

/** The style bindings a caller may replace with a different token. Locked: background, hoverBackground, focusRing, focusRingWidth. */
export type CardOverridableBinding =
  | 'paddingBlock'
  | 'paddingInline'
  | 'partGap'
  | 'headerGap'
  | 'footerGap'
  | 'actionsGap'
  | 'border'
  | 'borderWidth'
  | 'radius'
  | 'transition';

export interface CardProps {
  /** The body. Usually a Stack of Text and controls. */
  children: React.ReactNode;
  /** The card's title, rendered as a Heading at the card's level. Omit for cards that are a single piece of content. */
  heading?: string | undefined;
  /**
   * Heading level for `heading`, so cards fit the page outline. Cards in a list share
   * a level. React Native has no heading levels: the heading carries the `header`
   * role, and the level is passed to `Heading` for parity only (its size is `lg`).
   */
  headingLevel?: CardHeadingLevel | undefined;
  /** Controls at the end of the header row — a ghost icon-only Button, a Link. At most two (a content guideline, not a runtime check). */
  headerActions?: React.ReactNode;
  /** The action row. Buttons in a row, primary first, following Form's action-order rule. */
  footer?: React.ReactNode;
  /** Padding inside the card from the layout inset presets. `sm` for dense grids, `lg` for a single featured card. */
  inset?: CardInset | undefined;
  /** `default` is the page background with a border — the calm option; `subtle` is a tinted surface without a border. */
  surface?: CardSurface | undefined;
  /**
   * The whole card is one link or button target. Requires exactly one interactive
   * child (a Link or Button) in `children`, whose action, role and name move onto a
   * wrapping Pressable — the card's single target and single focus stop.
   */
  interactive?: boolean | undefined;
  /**
   * The card root takes `tabIndex={-1}` so a container (Feed) can move focus to it by
   * script through `ref`, and draws its own focus ring when focused that way. Not a
   * tab stop; not for making cards clickable (`interactive`). With `interactive` also
   * set, `interactive` wins, this is a no-op, and a development warning says so.
   */
  focusable?: boolean | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<CardOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root view: the surface `View`, or the wrapping `Pressable` when `interactive`. */
  ref?: React.Ref<ViewInstance> | undefined;
}

interface InteractiveTarget {
  activate: () => void;
  role: 'button' | 'link';
  label: string;
  disabled: boolean;
}

interface InteractiveScan {
  target: InteractiveTarget | null;
  count: number;
}

const INSET = {
  sm: 'layoutInsetSm',
  md: 'layoutInsetMd',
  lg: 'layoutInsetLg',
} as const satisfies Record<CardInset, keyof Tokens>;

const BACKGROUND = {
  default: 'colorBackground',
  subtle: 'colorBackgroundSubtle',
} as const satisfies Record<CardSurface, keyof Tokens>;

/** hoverBackground: `color.background.subtle`; subtle cards use `color.background.strong`. */
const HOVER_BACKGROUND = {
  default: 'colorBackgroundSubtle',
  subtle: 'colorBackgroundStrong',
} as const satisfies Record<CardSurface, keyof Tokens>;

/**
 * RN core's `View` type omits `onFocus`/`onBlur`, which the runtime and
 * react-native-web (where scripted focus is exercised) support; this alias types them.
 */
type FocusableViewProps = React.ComponentProps<typeof View> & {
  onFocus?: (() => void) | undefined;
  onBlur?: (() => void) | undefined;
  ref?: React.Ref<ViewInstance> | undefined;
};
const FocusableView = View as unknown as React.ComponentType<FocusableViewProps>;

function wrapInert(element: React.ReactNode): React.JSX.Element {
  return (
    <View pointerEvents="none" accessibilityElementsHidden importantForAccessibility="no">
      {element}
    </View>
  );
}

/**
 * Walks `children` (only `children`: header actions and footer keep their own
 * targets), neutralises every `Button`/`Link` it finds and records how to activate
 * the last one. The count lets the card warn when there is not exactly one.
 */
function collapseInteractiveChild(node: React.ReactNode, scan: InteractiveScan): React.ReactNode {
  if (Array.isArray(node)) {
    return node.map((child, index) => (
      <React.Fragment key={index}>{collapseInteractiveChild(child, scan)}</React.Fragment>
    ));
  }
  if (!React.isValidElement(node)) {
    return node;
  }

  if (node.type === Button) {
    const props = node.props as ButtonProps;
    scan.count += 1;
    scan.target = {
      activate: () => props.onPress?.(),
      role: 'button',
      label: props.label,
      disabled: props.disabled ?? false,
    };
    return wrapInert(node);
  }

  if (node.type === Link) {
    const props = node.props as LinkProps;
    scan.count += 1;
    scan.target = {
      // Same default action as Link: cancelable onPress, then Linking when Link would use it.
      activate: () => {
        if (props.onPress?.(props.href) === false) {
          return;
        }
        if (props.external || props.onPress === undefined) {
          Promise.resolve(Linking.openURL(props.href)).catch(() => undefined);
        }
      },
      role: 'link',
      label: props.external ? `${props.label}${LINK_EXTERNAL_SUFFIX}` : props.label,
      disabled: false,
    };
    return wrapInert(node);
  }

  const childProps = node.props as { children?: React.ReactNode };
  if (childProps.children === undefined) {
    return node;
  }
  return React.cloneElement(
    node as React.ReactElement<{ children?: React.ReactNode }>,
    undefined,
    collapseInteractiveChild(childProps.children, scan),
  );
}

/**
 * Card — frames one thing so it can sit among others: a search result, a plan to
 * choose, a setting group, a dashboard panel.
 *
 * When to use: collections of like items where each needs its own boundary, and a
 * single panel that groups a heading, content and actions. Give it a `heading` when it
 * is a unit in a list and set `headingLevel` to fit the page. Use `interactive` when
 * the entire card leads somewhere and it contains exactly one Link or Button.
 *
 * A `View` with padding, background, border and radius from tokens. The header
 * (`heading` or `headerActions`) and footer are Card's own row Views styled from its
 * gap bindings, not Stack, so they stay overridable per instance.
 *
 * `interactive` wraps the content in a `Pressable` that takes the single child's
 * role, accessible name and action; the child is made inert and hidden from assistive
 * technology, so the Pressable is exactly one target and one focus stop. The ring's
 * width (`border.width.focus`) is always reserved, transparent until focused (or the
 * border color on `surface: default`), so focus never shifts the layout. Hover and
 * press show `hoverBackground` instantly; native has no continuous hover to animate,
 * so `transition` has no runtime effect.
 *
 * `focusable` sets `tabIndex={-1}` (scriptable, not a tab stop under react-native-web;
 * on native Android `-1` means not focusable) and draws the ring on focus.
 */
export function Card({
  children,
  heading,
  headingLevel = '3',
  headerActions,
  footer,
  inset = 'md',
  surface = 'default',
  interactive = false,
  focusable = false,
  overrides,
  ref,
}: CardProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const [focused, setFocused] = React.useState(false);
  const [hovered, setHovered] = React.useState(false);
  const [pressed, setPressed] = React.useState(false);

  const warnedFocusable = React.useRef(false);
  if (__DEV__ && interactive && focusable && !warnedFocusable.current) {
    warnedFocusable.current = true;
    console.warn('Card: `focusable` has no effect while `interactive` is set; the card already has a target.');
  }

  const token = <V,>(override: TokenRef | undefined, fallback: V): V =>
    override ? (resolveToken(t, override) as V) : fallback;

  const paddingBlock = token<number>(overrides?.paddingBlock, t[INSET[inset]]);
  const paddingInline = token<number>(overrides?.paddingInline, t[INSET[inset]]);
  const partGap = token<number>(overrides?.partGap, t.layoutGapLoose);
  const headerGap = token<number>(overrides?.headerGap, t.layoutGapNormal);
  const footerGap = token<number>(overrides?.footerGap, t.layoutGapTight);
  const actionsGap = token<number>(overrides?.actionsGap, t.layoutGapTight);
  const radius = token<number>(overrides?.radius, t.radiusLg);
  const borderColor = token<string>(overrides?.border, t.colorBorder);
  const borderWidth = token<number>(overrides?.borderWidth, t.borderWidthThin);
  const background = t[BACKGROUND[surface]];
  const hoverBackground = t[HOVER_BACKGROUND[surface]];

  const scanned = React.useMemo((): { content: React.ReactNode; target: InteractiveTarget | null } => {
    if (!interactive) {
      return { content: children, target: null };
    }
    const scan: InteractiveScan = { target: null, count: 0 };
    const content = collapseInteractiveChild(children, scan);
    if (__DEV__ && scan.count !== 1) {
      console.warn(`Card: \`interactive\` requires exactly one Link or Button in children; found ${scan.count}.`);
    }
    return { content, target: scan.count === 1 ? scan.target : null };
  }, [interactive, children]);

  const ringReserved = interactive || focusable;
  const restingBorder = surface === 'default' ? borderColor : 'transparent';
  const surfaceStyle: ViewStyle = {
    paddingVertical: paddingBlock,
    paddingHorizontal: paddingInline,
    gap: partGap,
    borderRadius: radius,
    backgroundColor: interactive && (hovered || pressed) ? hoverBackground : background,
    ...(ringReserved
      ? { borderWidth: t.borderWidthFocus, borderColor: focused ? t.colorBorderFocus : restingBorder }
      : surface === 'default'
        ? { borderWidth, borderColor }
        : {}),
  };

  const headerStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: heading !== undefined ? 'space-between' : 'flex-end',
    gap: headerGap,
  };
  const actionsStyle: ViewStyle = { flexDirection: 'row', alignItems: 'center', gap: actionsGap };
  const footerStyle: ViewStyle = { flexDirection: 'row', alignItems: 'center', gap: footerGap };

  const content = (
    <>
      {heading !== undefined || headerActions !== undefined ? (
        <View style={headerStyle} testID="Card.header">
          {heading !== undefined ? (
            <View style={{ flexShrink: 1 }} testID="Card.heading">
              <Heading level={headingLevel} size="lg">
                {heading}
              </Heading>
            </View>
          ) : null}
          {headerActions !== undefined ? (
            <View style={actionsStyle} testID="Card.headerActions">
              {headerActions}
            </View>
          ) : null}
        </View>
      ) : null}
      <View testID="Card.body">{scanned.content}</View>
      {footer !== undefined ? (
        <View style={footerStyle} testID="Card.footer">
          {footer}
        </View>
      ) : null}
    </>
  );

  if (!interactive) {
    return (
      <FocusableView
        ref={ref}
        style={surfaceStyle}
        testID="Card"
        {...(focusable
          ? { tabIndex: -1 as const, onFocus: () => setFocused(true), onBlur: () => setFocused(false) }
          : {})}
      >
        {content}
      </FocusableView>
    );
  }

  const target = scanned.target;
  return (
    <Pressable
      ref={ref}
      accessibilityRole={target?.role}
      accessibilityLabel={target?.label}
      accessibilityState={{ disabled: target?.disabled ?? false }}
      onPress={() => {
        if (target !== null && !target.disabled) {
          target.activate();
        }
      }}
      onPressIn={() => setPressed(true)}
      onPressOut={() => setPressed(false)}
      onHoverIn={() => setHovered(true)}
      onHoverOut={() => setHovered(false)}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      style={surfaceStyle}
      testID="Card"
    >
      {content}
    </Pressable>
  );
}
