// packages/lit/src/Form.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import './Link.js';
import './Stack.js';

export type FormValidate = 'submit' | 'blur' | 'change';

/** Detail carried by the `submit` CustomEvent. */
export interface FormSubmitDetail {
  values: Record<string, string | number | boolean | string[] | [number, number]>;
}

/** Detail carried by the `invalid` CustomEvent. */
export interface FormInvalidDetail {
  errors: Record<string, string>;
}

/**
 * The contract a light-DOM element must implement to be collected by
 * `<ds-form>`. Form finds fields by the `data-ds-field` attribute on their host,
 * never by tag, so any element that sets it and implements this interface is
 * collected. `error` and `validationMessage` are optional: a field that never
 * validates (Switch) omits them, and Form treats absence as valid.
 * `currentValue` is `null` when the field contributes no key (empty, unchecked,
 * unselected).
 */
export interface DsFormField extends HTMLElement {
  name: string;
  label: string;
  required: boolean;
  disabled: boolean;
  error?: string | undefined;
  /**
   * Set by Form from the result of `checkValidity()`, which is how the field
   * renders its own message (every field documents `invalid` as "usually set by
   * the Form"). Optional: a field that never validates omits it.
   */
  invalid?: boolean | undefined;
  readonly currentValue: string | number | boolean | string[] | [number, number] | null;
  id: string;
  focus(): void;
  checkValidity(): boolean;
  readonly validationMessage?: string | undefined;
}

/** Overridable style hooks; see the `overrides` property. `errorSummaryText` and `errorSummaryBackground` are locked and excluded. */
export type FormOverridableBinding =
  | 'gap'
  | 'errorSummaryBorder'
  | 'errorSummaryBorderWidth'
  | 'errorSummaryRadius'
  | 'errorSummaryPadding'
  | 'errorSummaryGap';

/** `errorSummaryGap` has no hook: it is forwarded to the summary Stacks' `overrides.gap`. */
const HOOKS: Record<Exclude<FormOverridableBinding, 'errorSummaryGap'>, string> = {
  gap: '--ds-form-gap',
  errorSummaryBorder: '--ds-form-error-summary-border',
  errorSummaryBorderWidth: '--ds-form-error-summary-border-width',
  errorSummaryRadius: '--ds-form-error-summary-radius',
  errorSummaryPadding: '--ds-form-error-summary-padding',
};

type FieldValue = FormSubmitDetail['values'][string];

/** A null, empty-string or empty-array value contributes no key. */
function isEmptyValue(value: FieldValue | null | undefined): boolean {
  return value === null || value === undefined || value === '' || (Array.isArray(value) && value.length === 0);
}

/** copy.summaryHeading, plural by `count`. */
const COPY_SUMMARY_HEADING: Record<'one' | 'other', string> = {
  one: '1 problem with this form',
  other: '{count} problems with this form',
};

/** Every field component sets this attribute on its host; Form discovers fields by it alone. */
const FIELD_SELECTOR = '[data-ds-field]';

/** Negates a boolean attribute: `no-error-summary` present means `errorSummary` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

let formInstanceCount = 0;

type Disableable = HTMLElement & { disabled: boolean };

/**
 * `<ds-form>` — Form (category: container).
 *
 * `<ds-form name="sign-in" label="Sign in">` wraps a native `<form novalidate>`
 * in its shadow root, with a default slot for fields (Input etc. and layout
 * like Stack) and a named `actions` slot for the action row, but form
 * ownership is DOM-tree based, so the slotted fields are not owned by it.
 * Instead it collects light-DOM descendants carrying `data-ds-field` that have
 * a `name` and implement `DsFormField` (skipping any inside a closed
 * `ds-disclosure` without `keep-mounted`), submits on a composed `press` from
 * a `ds-button[type=submit]` and on Enter in any field (a `keydown` listener on
 * the host, never a CustomEvent named after a native event), and propagates
 * `disabled` to the fields it found and to every `ds-button` slotted into
 * `actions`, remembering which ones it disabled so it never re-enables one
 * already disabled on its own. The host carries `role="form"` and
 * `aria-label` / `aria-labelledby` (`labelledBy` winning over `label`) as plain
 * attributes, so the landmark lives in the light DOM tree. Dispatches composed
 * `submit` (`{ values }`) and `invalid` (`{ errors }`) CustomEvents; never
 * navigates. Never nest inside a native form or another `<ds-form>`.
 *
 * ## When to use
 *
 * Use Form whenever two or more fields are submitted together, and for any
 * single field whose submission has consequences (sign-in, search with side
 * effects). Place actions (submit, cancel) at the end in a Stack. Give the
 * form a `label` when the page contains more than one.
 *
 * @fires submit - Fired when every field is valid, with `{ values }` (keyed by each field's `name`) in `detail`.
 * @fires invalid - Fired when submission is blocked by validation, with `{ errors }` in `detail`.
 * @slot - Fields (Input etc.) and layout (Stack) (anatomy: fields).
 * @slot actions - The action row: at least one Button with `type: submit`, primary first (anatomy: actions).
 */
@customElement('ds-form')
export class DsForm extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-form-gap: var(--layout-gap-loose);
      --ds-form-error-summary-border: var(--color-border-danger);
      --ds-form-error-summary-border-width: var(--border-width-thin);
      --ds-form-error-summary-radius: var(--radius-md);
      --ds-form-error-summary-padding: var(--space-md);
      /* Locked: no overrides key, but the hook stays so a page stylesheet or the naming codemod can reach it. */
      --ds-form-error-summary-text: var(--color-foreground-danger);
      --ds-form-error-summary-background: var(--color-background-subtle);
      --ds-form-error-summary-line-height: var(--font-line-height-normal);
    }

    :host([hidden]) {
      display: none;
    }

    [data-part='container'] {
      display: flex;
      flex-direction: column;
      gap: var(--ds-form-gap);
      margin: 0;
      padding: 0;
    }

    /* A bare single action keeps its own width instead of stretching across the column. */
    slot[name='actions'] {
      display: flex;
      align-items: flex-start;
    }

    /* errorSummaryBackground / errorSummaryText / errorSummaryLineHeight are locked: out of the
       overrides type, but read through their :host hooks like every other binding. */
    [data-part='errorSummary'] {
      box-sizing: border-box;
      padding: var(--ds-form-error-summary-padding);
      border: var(--ds-form-error-summary-border-width) solid var(--ds-form-error-summary-border);
      border-radius: var(--ds-form-error-summary-radius);
      background: var(--ds-form-error-summary-background);
      color: var(--ds-form-error-summary-text);
      /* The item Links are bare text in this box, so without this they inherit the document's
         line-height: normal and each link's box falls under the 24px target floor (WCAG 2.5.8).
         Form may not give the Links a target of their own, so the box sets the body rhythm and the
         Links inherit it, as they inherit the danger color. Locked for exactly that reason. */
      line-height: var(--ds-form-error-summary-line-height);
    }

    [data-part='errorSummary']:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }
  `;

  /** Identifier for the form, used for analytics and as the base of generated field ids. */
  @property() accessor name = '';

  /** Accessible name for the form landmark. Required when a page has more than one form and `labelledBy` is not set. */
  @property() accessor label: string | undefined;

  /** Id of a visible Heading that names the form. Wins over `label` when both are set. */
  @property({ attribute: 'labelled-by' }) accessor labelledBy: string | undefined;

  /** When field-level validation runs. `submit` is the least noisy; `blur` is the usual choice for longer forms. */
  @property() accessor validate: FormValidate = 'submit';

  /** Disables every field and action inside. Use while submitting. The container applies no opacity of its own. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /**
   * When submission fails validation, render a summary of errors above the fields that links to each field.
   * Attribute is the negation, `no-error-summary`, because a boolean attribute cannot express `false` for a
   * prop that defaults `true`.
   */
  @property({ attribute: 'no-error-summary', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER })
  accessor errorSummary = true;

  /** Per-instance style overrides: `{ gap: 'layout.gap.normal' }`. Locked bindings (errorSummaryText, errorSummaryBackground) are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<FormOverridableBinding, TokenRef | undefined>> | undefined;

  /**
   * Field name -> message for the error summary: document order at the failed submit, with errors that
   * blur or change validation finds later appended at the end. Empty until a submission fails.
   */
  @state() private accessor errors: ReadonlyMap<string, string> = new Map();

  /** Each errored field's `label` as registered, so an entry whose field has since gone keeps its fallback text. */
  private readonly errorLabels = new Map<string, string>();

  /** Once a submission has failed, fields re-validate on blur/change even in `submit` mode; a successful one clears it. */
  private hasFailedSubmission = false;

  /** The plural locale, read at the failed submit (nearest `lang` ancestor, else the runtime default). */
  private summaryLocale: string | undefined;

  /** Fields and actions this Form disabled itself, so re-enabling never touches one already disabled by the consumer. */
  private readonly disabledByForm = new Set<Disableable>();

  /** Fields this Form marked invalid, so re-validating never clears one the consumer marked itself. */
  private readonly invalidByForm = new Set<DsFormField>();

  /** Re-syncs disabled propagation when fields are added or removed; observes `childList` only, never the attributes it writes. */
  private readonly mutationObserver = new MutationObserver(() => {
    if (this.disabled) this.syncDisabled();
  });

  /** Focus the error summary once it exists, after the render that follows a failed submission. */
  private pendingSummaryFocus = false;

  private readonly instanceId = `ds-form-${++formInstanceCount}`;

  /** The forbidden-nesting dev warning is emitted once per element, not on every reconnection. */
  private warnedAboutNesting = false;

  constructor() {
    super();
    this.addEventListener('keydown', (event) => this.handleKeydown(event));
    this.addEventListener('press', (event) => this.handlePress(event));
    this.addEventListener('change', (event) => this.handleFieldChange(event));
    this.addEventListener('focusout', (event) => this.handleFieldFocusOut(event));
  }

  private get idBase(): string {
    return this.name || this.instanceId;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Form');
    if (this.getAttribute('role') !== 'form') this.setAttribute('role', 'form');
    this.mutationObserver.observe(this, { childList: true, subtree: true });
    if (import.meta.env.DEV && !this.warnedAboutNesting && this.parentElement?.closest('form, ds-form')) {
      this.warnedAboutNesting = true;
      console.warn('<ds-form> must not be nested inside a native <form> or another <ds-form>.');
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.mutationObserver.disconnect();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('label') || changed.has('labelledBy')) {
      this.syncName();
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('disabled')) {
      this.syncDisabled();
    }
    if (this.pendingSummaryFocus) {
      this.pendingSummaryFocus = false;
      this.renderRoot.querySelector<HTMLElement>('[data-part="errorSummary"]')?.focus();
    }
  }

  protected override render(): TemplateResult {
    const errorEntries = Array.from(this.errors);
    const showSummary = this.errorSummary && this.hasFailedSubmission && errorEntries.length > 0;

    return html`
      <form
        part="container"
        data-part="container"
        novalidate
        name=${ifDefined(this.name || undefined)}
        @submit=${this.handleNativeSubmit}
      >
        ${showSummary ? this.renderSummary(errorEntries) : nothing}
        <slot data-part="fields"></slot>
        <slot name="actions" data-part="actions"></slot>
      </form>
    `;
  }

  private renderSummary(errorEntries: [string, string][]): TemplateResult {
    const fieldsByName = new Map(this.queryFields().map((field) => [field.name, field] as const));
    // errorSummaryGap is forwarded to both Stacks; their `gap="tight"` is the binding's default token.
    const gapRef = this.overrides?.errorSummaryGap;
    const stackOverrides = gapRef === undefined ? undefined : { gap: gapRef };
    return html`
      <div
        part="errorSummary"
        data-part="errorSummary"
        id=${`${this.idBase}-error-summary`}
        role="alert"
        tabindex="-1"
      >
        <ds-stack gap="tight" .overrides=${stackOverrides}>
          <ds-text element="p" weight="semibold" tone="danger">${this.summaryHeading(errorEntries.length)}</ds-text>
          <ds-stack element="ul" gap="tight" .overrides=${stackOverrides}>
            ${errorEntries.map(([name, message]) => {
              const field = fieldsByName.get(name);
              // The field's own message verbatim; its label only when the message is empty.
              const text = message || (field?.label ?? this.errorLabels.get(name)) || name;
              // A field that has since unregistered keeps its entry as plain danger Text, with no Link.
              if (field === undefined) {
                return html`<ds-text tone="danger">${text}</ds-text>`;
              }
              return html`
                <ds-link
                  tone="inherit"
                  href=${`#${field.id}`}
                  label=${text}
                  @click=${(event: MouseEvent) => this.handleSummaryLinkClick(event, name)}
                ></ds-link>
              `;
            })}
          </ds-stack>
        </ds-stack>
      </div>
    `;
  }

  /**
   * copy.summaryHeading, pluralised by `count` in the locale read at the failed submit. A `lang` tag
   * `Intl.PluralRules` rejects falls back to the runtime default locale rather than throwing.
   */
  private summaryHeading(count: number): string {
    let rules: Intl.PluralRules;
    try {
      rules = new Intl.PluralRules(this.summaryLocale);
    } catch {
      rules = new Intl.PluralRules();
    }
    const form = rules.select(count) === 'one' ? 'one' : 'other';
    return COPY_SUMMARY_HEADING[form].replace('{count}', String(count));
  }

  /** Validate every field and, only if all pass, dispatch `submit` with the collected values. */
  submit(): void {
    if (this.disabled) {
      return;
    }
    const fields = this.queryFields();
    this.assignFieldIds(fields);

    const errors = new Map<string, string>();
    this.errorLabels.clear();
    const values: FormSubmitDetail['values'] = {};
    let firstInvalid: DsFormField | undefined;

    for (const field of fields) {
      if (field.disabled) {
        continue;
      }
      if (this.runFieldValidation(field)) {
        const value = field.currentValue;
        if (!isEmptyValue(value)) {
          values[field.name] = value as FieldValue;
        }
      } else {
        errors.set(field.name, field.validationMessage ?? '');
        this.errorLabels.set(field.name, field.label);
        firstInvalid ??= field;
      }
    }

    this.errors = errors;

    if (firstInvalid !== undefined) {
      this.hasFailedSubmission = true;
      this.summaryLocale = this.closest('[lang]')?.getAttribute('lang') || undefined;
      this.dispatchEvent(
        new CustomEvent<FormInvalidDetail>('invalid', {
          detail: { errors: Object.fromEntries(errors) },
          bubbles: true,
          composed: true,
        }),
      );
      if (this.errorSummary) {
        this.pendingSummaryFocus = true;
      } else {
        firstInvalid.focus();
      }
      return;
    }

    // A successful submission removes the summary.
    this.hasFailedSubmission = false;
    this.dispatchEvent(
      new CustomEvent<FormSubmitDetail>('submit', { detail: { values }, bubbles: true, composed: true }),
    );
  }

  private handleNativeSubmit(event: Event): void {
    // The shadow <form> owns no controls; never let it navigate.
    event.preventDefault();
  }

  private handleKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' || event.defaultPrevented || event.isComposing) {
      return;
    }
    if (this.fieldFor(event.target) === null) {
      return;
    }
    // Enter in a multi-line control inserts a line break; on a button or link it activates it.
    const origin = event.composedPath()[0];
    if (
      origin instanceof HTMLTextAreaElement ||
      origin instanceof HTMLButtonElement ||
      origin instanceof HTMLAnchorElement
    ) {
      return;
    }
    event.preventDefault();
    this.submit();
  }

  private handlePress(event: Event): void {
    const target = event.target;
    if (!(target instanceof HTMLElement) || target.tagName !== 'DS-BUTTON') {
      return;
    }
    if ((target as HTMLElement & { type?: string | undefined }).type !== 'submit') {
      return;
    }
    this.submit();
  }

  private handleFieldChange(event: Event): void {
    const field = this.fieldFor(event.target);
    if (field === null) {
      return;
    }
    const shouldValidate =
      this.validate === 'change' ||
      (this.validate === 'blur' && this.validatesOnChange(field)) ||
      this.hasFailedSubmission;
    if (shouldValidate) {
      this.validateField(field);
    }
  }

  private handleFieldFocusOut(event: FocusEvent): void {
    const field = this.fieldFor(event.target);
    if (field === null) {
      return;
    }
    const related = event.relatedTarget;
    if (related instanceof Node && (related === field || field.contains(related))) {
      // Focus moved within the same field (two radios in one group), not out of it.
      return;
    }
    const shouldValidate =
      (this.validate === 'blur' && !this.validatesOnChange(field)) || this.hasFailedSubmission;
    if (shouldValidate) {
      this.validateField(field);
    }
  }

  /**
   * Runs the field's own synchronous validation and mirrors the result onto its
   * `invalid` property, which is what makes the field render its own message.
   * Form never composes a message of its own: the text shown is the field's
   * copy, and `validationMessage` is what the summary repeats.
   */
  private runFieldValidation(field: DsFormField): boolean {
    // Clear only a flag this Form set, so the field's validity is measured
    // afresh while an `invalid` the consumer set itself still counts as a
    // failure (a field's `invalid` is both an input to and a result of
    // validation, so a blanket clear would erase consumer state and a blanket
    // set would be sticky forever).
    if (this.invalidByForm.has(field) && field.invalid === true) {
      field.invalid = false;
    }
    const valid = field.checkValidity();
    if (typeof field.invalid === 'boolean') {
      if (!valid) {
        field.invalid = true;
        this.invalidByForm.add(field);
      } else {
        this.invalidByForm.delete(field);
      }
    }
    return valid;
  }

  /** A field with no useful blur moment (Checkbox, Switch) declares `data-ds-field="change"`. */
  private validatesOnChange(field: DsFormField): boolean {
    return field.getAttribute('data-ds-field') === 'change';
  }

  private handleSummaryLinkClick(event: MouseEvent, name: string): void {
    // Moves focus to the field; never navigates or changes the URL hash.
    event.preventDefault();
    this.queryFields()
      .find((candidate) => candidate.name === name)
      ?.focus();
  }

  /**
   * Runs the field's own validation (the field shows its error). The summary only tracks it after a failed
   * submission: a fixed field drops out, a still-listed one keeps its place, a newly invalid one is appended.
   */
  private validateField(field: DsFormField): void {
    const invalid = !field.disabled && !this.runFieldValidation(field);
    if (!this.hasFailedSubmission) {
      return;
    }
    const next = new Map(this.errors);
    if (invalid) {
      next.set(field.name, field.validationMessage ?? '');
      this.errorLabels.set(field.name, field.label);
    } else {
      next.delete(field.name);
    }
    this.errors = next;
  }

  /** The collected field an event came from, or `null`. */
  private fieldFor(target: EventTarget | null): DsFormField | null {
    if (!(target instanceof Element)) {
      return null;
    }
    const el = target.closest<HTMLElement>(FIELD_SELECTOR);
    if (el === null || !this.contains(el)) {
      return null;
    }
    const field = el as DsFormField;
    return field.name && !this.isInsideClosedDisclosure(el) ? field : null;
  }

  /** Fields with a `name`, in document order, not inside a closed `ds-disclosure` without `keep-mounted`. */
  private queryFields(): DsFormField[] {
    return Array.from(this.querySelectorAll<HTMLElement>(FIELD_SELECTOR)).filter(
      (el): el is DsFormField => Boolean((el as DsFormField).name) && !this.isInsideClosedDisclosure(el),
    );
  }

  private isInsideClosedDisclosure(el: HTMLElement): boolean {
    let node = el.parentElement;
    while (node !== null && node !== this) {
      if (node.tagName === 'DS-DISCLOSURE') {
        const disclosure = node as HTMLElement & { currentOpen?: boolean | undefined; keepMounted?: boolean | undefined };
        if (!disclosure.keepMounted && !disclosure.currentOpen) {
          return true;
        }
      }
      node = node.parentElement;
    }
    return false;
  }

  /** A field missing an `id` gets `{name}-{field.name}`, so an error summary link always has somewhere to point. */
  private assignFieldIds(fields: readonly DsFormField[]): void {
    for (const field of fields) {
      if (!field.id) {
        field.id = `${this.idBase}-${field.name}`;
      }
    }
  }

  /** Every `ds-button` slotted into `actions`, including the slotted element itself. */
  private queryActionButtons(): Disableable[] {
    const buttons: Disableable[] = [];
    for (const child of Array.from(this.children)) {
      if (child.getAttribute('slot') !== 'actions') continue;
      if (child.tagName === 'DS-BUTTON') buttons.push(child as Disableable);
      buttons.push(...Array.from(child.querySelectorAll<Disableable>('ds-button')));
    }
    return buttons;
  }

  /** Disables every found field and action button, remembering which it disabled so re-enabling is exact. */
  private syncDisabled(): void {
    if (this.disabled) {
      for (const control of [...this.queryFields(), ...this.queryActionButtons()] as Disableable[]) {
        if (!control.disabled) {
          this.disabledByForm.add(control);
          control.disabled = true;
        }
      }
      return;
    }
    for (const control of this.disabledByForm) {
      if (control.disabled) control.disabled = false;
    }
    this.disabledByForm.clear();
  }

  /** Accessible name as plain host attributes, `labelledBy` winning over `label`. */
  private syncName(): void {
    if (this.labelledBy) {
      this.setAttribute('aria-labelledby', this.labelledBy);
      this.removeAttribute('aria-label');
    } else {
      this.removeAttribute('aria-labelledby');
      if (this.label) {
        this.setAttribute('aria-label', this.label);
      } else {
        this.removeAttribute('aria-label');
      }
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as (keyof typeof HOOKS)[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-form': DsForm;
  }
}

// packages/rn/src/Form.tsx
import * as React from 'react';
import { AccessibilityInfo, Platform, View, findNodeHandle } from 'react-native';
import type { TextInstance, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { FormContext } from './FormContext';
import type { FormContextValue, FormFieldHandle, FormValidateMode, FormValues } from './FormContext';
import { Link } from './Link';
import { Stack } from './Stack';
import { Text } from './Text';
import type { TextOverridableBinding } from './Text';
import { useTheme } from './theme';

export type { FormFieldValue, FormValidateMode, FormValues } from './FormContext';

/**
 * The style bindings a caller may replace with a different token; see the component's
 * overrides contract. `errorSummaryText` and `errorSummaryBackground` are locked — they
 * carry the summary's contrast pair — and are not in the union.
 */
export type FormOverridableBinding =
  | 'gap'
  | 'errorSummaryBorder'
  | 'errorSummaryBorderWidth'
  | 'errorSummaryRadius'
  | 'errorSummaryPadding'
  | 'errorSummaryGap';

export interface FormProps {
  /** Fields (Input etc.) and layout (Stack). The action row goes in `actions`. */
  children: React.ReactNode;
  /**
   * The action row: at least one Button with `type: submit`, primary first (Form's
   * action-order rule). Rendered after the fields with the form gap. A single action
   * renders bare; two or more go in a horizontal Stack the consumer supplies. The
   * actions part aligns its content to the inline start, so a single bare action keeps
   * its natural width rather than stretching.
   */
  actions: React.ReactNode;
  /**
   * Identifier for the form, used for analytics and as the base of generated ids. React
   * Native has no ids and focuses by ref, so it is inert here and exists for parity.
   */
  name?: string | undefined;
  /**
   * Accessible name for the form, e.g. "Sign in". Required when a screen has more than one
   * form. Nothing enforces this at runtime and no dev warning is emitted.
   */
  label?: string | undefined;
  /**
   * When field-level validation runs. `submit` is the least noisy; `blur` is the usual
   * choice for longer forms. `change` validates on change only, not also on blur; after a
   * failed submission every mode re-validates on blur and change, until a successful
   * submission resets that state.
   */
  validate?: FormValidateMode | undefined;
  /**
   * Disables every field and action inside. Use while submitting. Each field and action
   * dims itself with its own disabled style; the Form container applies no opacity of its
   * own (it would compound) and only exposes the disabled state.
   */
  disabled?: boolean | undefined;
  /**
   * When submission fails validation, render a summary of errors above the fields that
   * links to each field. Each item's text is the field's own message verbatim; a field that
   * is invalid with an empty message shows its `label` instead, and its `name` when the
   * label is empty too. The summary appears only after a failed submission, shrinks as
   * fields are fixed, and is removed by a successful submission.
   */
  errorSummary?: boolean | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<FormOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root view, so a parent can measure it. */
  ref?: React.Ref<ViewInstance> | undefined;
  /**
   * Fired when the form is submitted and every field is valid. Receives the collected values
   * keyed by field name: Input and RadioGroup contribute strings, Switch a boolean, Checkbox
   * its `value` when checked, NumberInput and Slider a number, multi-select Listbox, Select
   * and Combobox a string array, a range Slider or DatePicker a pair; an unchecked Checkbox,
   * an unselected RadioGroup, an empty field (a null, empty-string or empty-array value) and
   * a disabled field contribute no key at all.
   */
  onSubmit?: ((values: FormValues) => void) | undefined;
  /** Fired when submission is blocked by validation. Receives the errors keyed by field name. */
  onInvalid?: ((errors: Record<string, string>) => void) | undefined;
}

/**
 * copy.* — used verbatim. `summaryHeading` is selected by `Intl.PluralRules` on `count`;
 * `summaryHeadingOne` and `invalidSummary` are not rendered on React Native and are kept
 * here so the doc's copy block stays complete on this platform.
 */
const COPY = {
  summaryHeading: {
    one: '1 problem with this form',
    other: '{count} problems with this form',
  },
  summaryHeadingOne: '1 problem with this form',
  invalidSummary: 'This form has errors.',
} as const;

function summaryHeading(count: number, locale: string | undefined): string {
  const plural = new Intl.PluralRules(locale).select(count);
  return (plural === 'one' ? COPY.summaryHeading.one : COPY.summaryHeading.other).replace('{count}', String(count));
}

/** A null, empty-string or empty-array value contributes no key, so fields need not normalise. */
function isEmptyValue(value: unknown): boolean {
  return value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0);
}

/**
 * errorSummaryLineHeight — locked at `font.lineHeight.normal`, the binding that keeps the
 * item Links above the target floor. There is no cascade on native, so the box cannot set a
 * line height its Texts inherit: it is handed to each summary Text instead, and the item
 * Links take it from the Text they are nested in.
 */
const SUMMARY_LINE_HEIGHT = { lineHeight: 'font.lineHeight.normal' } as const satisfies Partial<Record<TextOverridableBinding, TokenRef>>;

/** One line of the error summary. `registered` is false once its field has unmounted. */
interface SummaryEntry {
  name: string;
  text: string;
  registered: boolean;
}

/**
 * Form — the container that makes fields behave as a group.
 *
 * When to use: Use Form whenever two or more fields are submitted together, and for any
 * single field whose submission has consequences (sign-in, search with side effects). Pass
 * the submit and cancel Buttons in `actions`, primary first. Give the form a `label` when
 * the screen contains more than one. Do not use it for instant-apply settings, do not nest
 * forms, and do not use it as a layout container — that is Stack.
 *
 * There is no form element on native. Form renders a `View` with `role="form"` (a landmark
 * only on react-native-web; `accessibilityLabel` is the native alternative) and provides a
 * context: each field calls `register(name, { label, getValue, isDisabled, validate, focus })`
 * in mount order, a Button with `type: submit` calls `submit()`, non-last Inputs get
 * `returnKeyType="next"` and the last one's return key submits. A disabled field is left out
 * of the values, out of validation and out of `order`, so the previous field's "next" key
 * skips past it.
 *
 * On a failed submission `onInvalid` fires, the summary is announced
 * (`accessibilityLiveRegion="assertive"` for Android, `announceForAccessibility` on iOS —
 * the heading followed by each item joined with '. ', once per failed submit) and
 * accessibility focus moves to the summary heading, or to the first invalid field when
 * `errorSummary` is off. Items are in field order at the failed submit; an error a later
 * blur or change finds is appended. Each item is a `Link` (`tone: inherit`, nested in a
 * danger `Text`, which is how the danger color reaches it) that focuses its field and
 * returns `false` so nothing opens; an item whose field has since unmounted stays as plain
 * danger text with no link.
 */
export function Form({
  children,
  actions,
  name: _name,
  label,
  validate = 'submit',
  disabled = false,
  errorSummary = true,
  overrides,
  ref,
  onSubmit,
  onInvalid,
}: FormProps): React.JSX.Element {
  const { tokens: t } = useTheme();

  const handles = React.useRef<Map<string, FormFieldHandle>>(new Map());
  // Labels outlive their handles: a summary item whose field has unmounted still needs the
  // label fallback for an invalid field with an empty message.
  const labels = React.useRef<Map<string, string>>(new Map());
  const orderRef = React.useRef<string[]>([]);
  const [order, setOrder] = React.useState<readonly string[]>([]);
  const [errors, setErrors] = React.useState<Readonly<Partial<Record<string, string | undefined>>>>({});
  // True from a failed submission until a successful one: gates the summary and turns on
  // re-validation on blur and change in every mode.
  const [submitFailed, setSubmitFailed] = React.useState(false);
  const submitFailedRef = React.useRef(false);
  // Summary item order: field order at the failed submit, later errors appended.
  const [summaryOrder, setSummaryOrder] = React.useState<readonly string[]>([]);
  // The plural locale, captured at the failed submit — RN has no `lang` ancestor, so it is
  // always the runtime default.
  const [pluralLocale, setPluralLocale] = React.useState<string | undefined>(undefined);
  const [failedAttempt, setFailedAttempt] = React.useState(0);
  const headingRef = React.useRef<TextInstance>(null);

  const latest = React.useRef({ disabled, errorSummary, onSubmit, onInvalid });
  latest.current = { disabled, errorSummary, onSubmit, onInvalid };

  // A disabled field stays registered and reports `isDisabled()`; it is left out of the
  // order the fields read, so the previous field's "next" key skips past it.
  const syncOrder = React.useCallback(() => {
    const next = orderRef.current.filter((fieldName) => handles.current.get(fieldName)?.isDisabled?.() !== true);
    setOrder((prev) => (prev.length === next.length && prev.every((fieldName, index) => fieldName === next[index]) ? prev : next));
  }, []);

  const register = React.useCallback(
    (fieldName: string, handle: FormFieldHandle) => {
      handles.current.set(fieldName, handle);
      labels.current.set(fieldName, handle.label ?? '');
      if (!orderRef.current.includes(fieldName)) {
        orderRef.current = [...orderRef.current, fieldName];
      }
      syncOrder();
    },
    [syncOrder],
  );

  const unregister = React.useCallback(
    (fieldName: string) => {
      handles.current.delete(fieldName);
      if (orderRef.current.includes(fieldName)) {
        orderRef.current = orderRef.current.filter((registered) => registered !== fieldName);
      }
      syncOrder();
      // The error is kept: an entry whose field has gone (a Disclosure closed after the failed
      // submit) stays in the summary, without its link, until the next validation replaces it.
    },
    [syncOrder],
  );

  const reportValidity = React.useCallback((fieldName: string, error: string | null) => {
    setErrors((prev) => {
      if (error === null) {
        if (!(fieldName in prev)) {
          return prev;
        }
        const next = { ...prev };
        delete next[fieldName];
        return next;
      }
      return prev[fieldName] === error ? prev : { ...prev, [fieldName]: error };
    });
    if (error !== null && submitFailedRef.current) {
      setSummaryOrder((prev) => (prev.includes(fieldName) ? prev : [...prev, fieldName]));
    }
  }, []);

  const submit = React.useCallback(() => {
    if (latest.current.disabled) {
      return;
    }
    const nextErrors: Record<string, string> = {};
    const values: FormValues = {};
    let firstInvalid: FormFieldHandle | null = null;
    for (const fieldName of orderRef.current) {
      const handle = handles.current.get(fieldName);
      // A disabled field is neither validated nor collected, whether it left the order or
      // stayed registered and reported it.
      if (handle === undefined || handle.isDisabled?.() === true) {
        continue;
      }
      const error = handle.validate();
      if (error !== null) {
        nextErrors[fieldName] = error;
        if (firstInvalid === null) {
          firstInvalid = handle;
        }
      }
      const value = handle.getValue();
      if (!isEmptyValue(value)) {
        values[fieldName] = value!;
      }
    }
    setErrors(nextErrors);
    if (firstInvalid !== null) {
      submitFailedRef.current = true;
      setSubmitFailed(true);
      setSummaryOrder(orderRef.current.filter((fieldName) => fieldName in nextErrors));
      setPluralLocale(new Intl.PluralRules().resolvedOptions().locale);
      latest.current.onInvalid?.(nextErrors);
      if (latest.current.errorSummary) {
        // Announcement and focus wait for the summary to render — see the effect below.
        setFailedAttempt((attempt) => attempt + 1);
      } else {
        firstInvalid.focus();
      }
      return;
    }
    submitFailedRef.current = false;
    setSubmitFailed(false);
    setSummaryOrder([]);
    latest.current.onSubmit?.(values);
  }, []);

  const focusField = React.useCallback((fieldName: string) => {
    handles.current.get(fieldName)?.focus();
  }, []);

  // After a failed submission every mode re-validates on blur and change. Fields read
  // `submitFailed` for that; `validateMode` also reports `change` from then on, so a field
  // that reads only the mode keeps re-validating as it is fixed.
  const validateMode: FormValidateMode = submitFailed ? 'change' : validate;

  const contextValue = React.useMemo<FormContextValue>(
    () => ({
      register,
      unregister,
      submit,
      focusField,
      reportValidity,
      disabled,
      validateMode,
      submitFailed,
      errorSummary,
      errors,
      order,
    }),
    [register, unregister, submit, focusField, reportValidity, disabled, validateMode, submitFailed, errorSummary, errors, order],
  );

  // Each item is the field's own message verbatim; an empty message falls back to the
  // field's label, and to its name when the label is empty too.
  const errorEntries: readonly SummaryEntry[] = summaryOrder
    .filter((fieldName) => errors[fieldName] !== undefined)
    .map((fieldName) => {
      const message = errors[fieldName] ?? '';
      const fieldLabel = labels.current.get(fieldName) ?? '';
      const text = message !== '' ? message : fieldLabel !== '' ? fieldLabel : fieldName;
      return { name: fieldName, text, registered: handles.current.has(fieldName) };
    });

  // If every invalid field has unregistered by the time a failed submit renders, no summary
  // is drawn for that attempt and accessibility focus stays where it was. Decided once, on
  // the attempt's first render: an entry whose field unregisters later stays as plain text.
  const renderedAttempt = React.useRef(0);
  const summaryWithheld = React.useRef(false);
  if (renderedAttempt.current !== failedAttempt) {
    renderedAttempt.current = failedAttempt;
    summaryWithheld.current = !errorEntries.some((entry) => entry.registered);
  }

  const showSummary = errorSummary && submitFailed && errorEntries.length > 0 && !summaryWithheld.current;
  const heading = summaryHeading(errorEntries.length, pluralLocale);

  // After a failed submission: accessibility focus to the summary heading, and on iOS (which
  // has no live regions) the heading followed by each item, once. Android is covered by
  // `accessibilityLiveRegion` on the summary view, so neither repeats as the summary shrinks.
  const announcementRef = React.useRef('');
  announcementRef.current = showSummary ? [heading, ...errorEntries.map((entry) => entry.text)].join('. ') : '';
  React.useEffect(() => {
    if (failedAttempt === 0 || summaryWithheld.current) {
      return;
    }
    const node = findNodeHandle(headingRef.current);
    if (node != null) {
      AccessibilityInfo.setAccessibilityFocus(node);
    }
    if (Platform.OS === 'ios' && announcementRef.current !== '') {
      AccessibilityInfo.announceForAccessibility(announcementRef.current);
    }
  }, [failedAttempt]);

  const styles = React.useMemo(() => {
    const gap = overrides?.gap ? (resolveToken(t, overrides.gap) as number) : t.layoutGapLoose;
    // No opacity here: every field and action inside dims itself from the context, and
    // dimming the container too would compound the two.
    const container: ViewStyle = { flexDirection: 'column', gap };
    // The same gap separates the fields part's direct children, so the rhythm is uniform
    // whether the siblings are two fields or the fields block and the action row.
    const fields: ViewStyle = { flexDirection: 'column', gap };
    // Inline start, so a single bare action keeps its natural width rather than stretching.
    const actionsPart: ViewStyle = { alignItems: 'flex-start' };
    const summary: ViewStyle = {
      flexDirection: 'column',
      borderStyle: 'solid',
      borderWidth: overrides?.errorSummaryBorderWidth
        ? (resolveToken(t, overrides.errorSummaryBorderWidth) as number)
        : t.borderWidthThin,
      borderColor: overrides?.errorSummaryBorder ? (resolveToken(t, overrides.errorSummaryBorder) as string) : t.colorBorderDanger,
      borderRadius: overrides?.errorSummaryRadius ? (resolveToken(t, overrides.errorSummaryRadius) as number) : t.radiusMd,
      // Locked: the summary's contrast pair with `color.foreground.danger`.
      backgroundColor: t.colorBackgroundSubtle,
      padding: overrides?.errorSummaryPadding ? (resolveToken(t, overrides.errorSummaryPadding) as number) : t.spaceMd,
    };
    return { container, fields, actions: actionsPart, summary };
  }, [
    t,
    overrides?.gap,
    overrides?.errorSummaryBorder,
    overrides?.errorSummaryBorderWidth,
    overrides?.errorSummaryRadius,
    overrides?.errorSummaryPadding,
  ]);

  // errorSummaryGap reaches both Stacks through their own `overrides`, never resolved here.
  const summaryGapOverrides = { gap: overrides?.errorSummaryGap };

  return (
    <FormContext.Provider value={contextValue}>
      <View
        ref={ref}
        testID="Form"
        role="form"
        accessibilityLabel={label}
        aria-label={label}
        accessibilityState={{ disabled }}
        aria-disabled={disabled}
        style={styles.container}
      >
        {showSummary ? (
          // Not `accessible`, so every item Link stays separately focusable.
          <View testID="Form.errorSummary" accessibilityLiveRegion="assertive" style={styles.summary}>
            <Stack gap="tight" overrides={summaryGapOverrides}>
              <Text ref={headingRef} tone="danger" weight="semibold" overrides={SUMMARY_LINE_HEIGHT}>
                {heading}
              </Text>
              <Stack gap="tight" overrides={summaryGapOverrides}>
                {errorEntries.map((entry) =>
                  entry.registered ? (
                    <Text key={entry.name} tone="danger" overrides={SUMMARY_LINE_HEIGHT}>
                      <Link
                        href={entry.name}
                        label={entry.text}
                        tone="inherit"
                        onPress={() => {
                          handles.current.get(entry.name)?.focus();
                          // Moves focus only; never hands off to Linking.
                          return false;
                        }}
                      />
                    </Text>
                  ) : (
                    <Text key={entry.name} tone="danger" overrides={SUMMARY_LINE_HEIGHT}>
                      {entry.text}
                    </Text>
                  ),
                )}
              </Stack>
            </Stack>
          </View>
        ) : null}
        <View testID="Form.fields" style={styles.fields}>
          {children}
        </View>
        <View testID="Form.actions" style={styles.actions}>
          {actions}
        </View>
      </View>
    </FormContext.Provider>
  );
}
