// packages/lit/src/Input.ts
import { LitElement, css, html, nothing, type CSSResult, type PropertyValues, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { live } from 'lit/directives/live.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import type { TextOverridableBinding } from './Text.js';

export type InputType = 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url';
export type InputSize = 'sm' | 'md';

/** Detail carried by the `change` CustomEvent. */
export interface InputChangeDetail {
  /** The new value. */
  value: string;
}

/**
 * Overridable style hooks; see the `overrides` property. `background`,
 * `foreground`, `placeholder`, `border`, `borderFocus`, `errorText`,
 * `descriptionText`, `minTarget`, `minTargetSm` and `focusRingWidth` are
 * locked and excluded.
 */
export type InputOverridableBinding =
  | 'borderInvalid'
  | 'borderWidth'
  | 'radius'
  | 'paddingInline'
  | 'paddingBlock'
  | 'partGap'
  | 'fontFamily'
  | 'fontSize'
  | 'labelWeight'
  | 'helperSize'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

const HOOKS: Record<InputOverridableBinding, string> = {
  borderInvalid: '--ds-input-border-invalid',
  borderWidth: '--ds-input-border-width',
  radius: '--ds-input-radius',
  paddingInline: '--ds-input-padding-inline',
  paddingBlock: '--ds-input-padding-block',
  partGap: '--ds-input-part-gap',
  fontFamily: '--ds-input-font-family',
  fontSize: '--ds-input-font-size',
  labelWeight: '--ds-input-label-weight',
  helperSize: '--ds-input-helper-size',
  lineHeight: '--ds-input-line-height',
  disabledOpacity: '--ds-input-disabled-opacity',
  transition: '--ds-input-transition',
};

/** copy.required */
const COPY_REQUIRED = (label: string): string => `${label} is required.`;
/** copy.invalid */
const COPY_INVALID = (label: string): string => `${label} is not valid.`;
/** copy.requiredIndicator */
const COPY_REQUIRED_INDICATOR = ' (required)';

/**
 * `<ds-input>` — Input (category: input, role: textbox).
 *
 * `<ds-input name="email" type="email" label="Email address">`. The native
 * `<label for>` and `<input id>` live together in the shadow root, so the label
 * association is always intact; description and error are `<ds-text>` linked
 * with `aria-describedby`, the error carrying `role="alert"`. The element is
 * form-associated via `ElementInternals`, so a native `<form>` that directly
 * contains it sees its value and validity, and `<ds-form>` collects it by
 * `name`. Dispatches a composed `change` CustomEvent carrying `{ value }`;
 * `focus` and `blur` are the native events, retargeted to the host.
 *
 * ## When to use
 *
 * Use Input for names, emails, passwords, search terms, and short free-text
 * values. Choose `type` for the value so touch keyboards and browser validation
 * match. Provide `description` when the format matters ("Use the email you
 * signed up with"). Set `autocomplete` whenever the value is personal data so
 * browsers and assistive tools can fill it.
 *
 * @fires change - Fired on every value change with `{ value }` in `detail`.
 * @fires focus - The native focus event, retargeted to the host (no CustomEvent).
 * @fires blur - The native blur event, retargeted to the host. The usual moment to validate.
 */
@customElement('ds-input')
export class DsInput extends LitElement {
  static formAssociated: boolean = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-input-border-invalid: var(--color-border-danger);
      --ds-input-border-width: var(--border-width-thin);
      --ds-input-radius: var(--radius-md);
      --ds-input-padding-inline: var(--space-md);
      --ds-input-padding-block: var(--space-sm);
      --ds-input-part-gap: var(--space-1);
      --ds-input-font-family: var(--font-family-body);
      --ds-input-font-size: var(--font-size-md);
      --ds-input-label-weight: var(--font-weight-medium);
      --ds-input-helper-size: var(--font-size-sm);
      --ds-input-line-height: var(--font-line-height-normal);
      --ds-input-disabled-opacity: var(--opacity-disabled);
      --ds-input-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    /* paddingInline / paddingBlock by size; fontSize: font.size.{size} */
    :host([size='sm']) {
      --ds-input-padding-inline: var(--space-2);
      --ds-input-padding-block: var(--space-1);
      --ds-input-font-size: var(--font-size-sm);
    }
    :host([size='md']) {
      --ds-input-padding-inline: var(--space-md);
      --ds-input-padding-block: var(--space-sm);
      --ds-input-font-size: var(--font-size-md);
    }

    /* partGap: the vertical gap between label, description, field and error */
    .group {
      display: grid;
      gap: var(--ds-input-part-gap);
      position: relative;
      font-family: var(--ds-input-font-family);
    }

    /* disabledOpacity: the whole field group dims, as Button dims the whole control */
    .group.disabled {
      opacity: var(--ds-input-disabled-opacity);
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }

    /* labelWeight: font.weight.medium on the label part */
    [data-part='label'] {
      font-family: var(--ds-input-font-family);
      font-size: var(--ds-input-font-size);
      font-weight: var(--ds-input-label-weight);
      line-height: var(--ds-input-line-height);
      color: var(--color-foreground);
    }

    [data-part='field'] {
      box-sizing: border-box;
      display: block;
      inline-size: 100%;
      min-block-size: var(--size-target-comfortable);
      margin: 0;
      padding-block: var(--ds-input-padding-block);
      padding-inline: var(--ds-input-padding-inline);
      border: var(--ds-input-border-width) solid var(--color-border-strong);
      border-radius: var(--ds-input-radius);
      outline: none;
      font-family: var(--ds-input-font-family);
      font-size: var(--ds-input-font-size);
      line-height: var(--ds-input-line-height);
      color: var(--color-foreground);
      background: var(--color-background);
      appearance: none;
      -webkit-appearance: none;
      /* transition: border color only; border width and padding change instantly */
      transition: border-color var(--ds-input-transition) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='field'] {
        transition: none;
      }
    }

    /* minTargetSm: the field height floor at size sm */
    :host([size='sm']) [data-part='field'] {
      min-block-size: var(--size-target-min);
    }

    /* placeholder: color.foreground.muted */
    [data-part='field']::placeholder {
      color: var(--color-foreground-muted);
      opacity: 1;
    }

    /*
     * The border is the focus ring: focusRingWidth replaces borderWidth, and the
     * padding shrinks by the difference so the field does not shift.
     */
    [data-part='field']:focus-visible {
      border-color: var(--color-border-focus);
      border-width: var(--border-width-focus);
      padding-inline: calc(var(--ds-input-padding-inline) - (var(--border-width-focus) - var(--ds-input-border-width)));
      padding-block: calc(var(--ds-input-padding-block) - (var(--border-width-focus) - var(--ds-input-border-width)));
    }

    /* borderInvalid: the danger color stays while focused; only the width changes */
    :host([invalid]) [data-part='field'],
    :host([invalid]) [data-part='field']:focus-visible {
      border-color: var(--ds-input-border-invalid);
    }

    .group.disabled [data-part='field'] {
      cursor: not-allowed;
    }
  `;

  /** Visible label (visually hidden with `hideLabel`). Never replaced by a placeholder. */
  @property() accessor label = '';

  /** Field name used by the enclosing Form when collecting values. */
  @property() accessor name = '';

  /** Controlled value. Omit for an uncontrolled field. */
  @property({ attribute: false }) accessor value: string | undefined;

  /** Initial value for an uncontrolled field. */
  @property({ attribute: 'default-value' }) accessor defaultValue: string | undefined;

  /** Example input shown while empty. Never the only description of what to enter. */
  @property() accessor placeholder: string | undefined;

  /** Persistent helper text below the label explaining format or purpose. */
  @property() accessor description: string | undefined;

  /** Input type. Drives the keyboard on touch platforms and browser validation on web. */
  @property({ type: String, reflect: true }) accessor type: InputType = 'text';

  /** The field must have a value to submit. Shown in the label, not only by color. */
  @property({ type: Boolean, reflect: true }) accessor required = false;

  /** Visually hide the label (it remains the accessible name). */
  @property({ type: Boolean, attribute: 'hide-label' }) accessor hideLabel = false;

  /** sm for fields inside grid cells and toolbars: minimum target height, tighter padding, small type. */
  @property({ type: String, reflect: true }) accessor size: InputSize = 'md';

  /** Not editable and not submitted. Stays visible, readable and focusable. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Marks the field as failing validation. Usually set by the Form; can be set directly. */
  @property({ type: Boolean, reflect: true }) accessor invalid = false;

  private errorValue: string | undefined;

  /** The error message. Setting it implies `invalid`. Explain what is wrong and how to fix it. */
  get error(): string | undefined {
    return this.errorValue;
  }
  @property()
  set error(value: string | undefined) {
    const old = this.errorValue;
    this.errorValue = value;
    // Setting `error` implies `invalid` and clearing it removes the invalid state,
    // synchronously, so validity is correct right after the assignment.
    if (value) {
      this.invalid = true;
    } else if (old) {
      this.invalid = false;
    }
    this.syncInternals();
  }

  /** HTML autocomplete token (e.g. `email`, `given-name`). WCAG 1.3.5 input purpose. */
  @property() accessor autocomplete: string | undefined;

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<InputOverridableBinding, TokenRef | undefined>> | undefined;

  /** The uncontrolled value once the user has edited it; `undefined` until then. */
  @state() private accessor editedValue: string | undefined;

  /** Disabled by an owning native `<form>` / `<fieldset>` (via `formDisabledCallback`). */
  @state() private accessor formDisabled = false;

  @query('#field') private accessor inputEl!: HTMLInputElement | null;

  private readonly internals: ElementInternals = this.attachInternals();

  /** The current string value: `value` when controlled, the uncontrolled value otherwise. */
  get currentValue(): string {
    return this.value ?? this.editedValue ?? this.defaultValue ?? '';
  }

  /** The owning native form, if any. */
  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  get validity(): ValidityState {
    this.syncInternals();
    return this.internals.validity;
  }

  get validationMessage(): string {
    this.syncInternals();
    return this.internals.validationMessage;
  }

  checkValidity(): boolean {
    this.syncInternals();
    return this.internals.checkValidity();
  }

  reportValidity(): boolean {
    this.syncInternals();
    return this.internals.reportValidity();
  }

  formDisabledCallback(disabled: boolean): void {
    this.formDisabled = disabled;
  }

  formResetCallback(): void {
    this.editedValue = undefined;
  }

  formStateRestoreCallback(restored: File | string | FormData | null): void {
    if (typeof restored === 'string' && this.value === undefined) {
      this.editedValue = restored;
    }
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Input');
    this.setAttribute('data-ds-field', '');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.syncInternals();
  }

  protected override render(): TemplateResult {
    const isDisabled = this.isDisabled;
    const message = this.displayedError;
    const describedBy = [this.description ? 'description' : '', message ? 'error' : ''].filter(Boolean).join(' ');
    const textOverrides = this.textOverrides;

    return html`
      <div class=${classMap({ group: true, disabled: isDisabled })}>
        <label
          class=${classMap({ 'visually-hidden': this.hideLabel })}
          part="label"
          data-part="label"
          for="field"
          >${this.label}${this.required ? COPY_REQUIRED_INDICATOR : nothing}</label
        >
        ${this.description
          ? html`<ds-text
              id="description"
              part="description"
              data-part="description"
              element="p"
              size="sm"
              tone="muted"
              .overrides=${textOverrides}
              >${this.description}</ds-text
            >`
          : nothing}
        <input
          id="field"
          part="field"
          data-part="field"
          name=${this.name}
          type=${this.type}
          .value=${live(this.currentValue)}
          placeholder=${ifDefined(this.placeholder)}
          autocomplete=${ifDefined(this.autocomplete)}
          aria-describedby=${ifDefined(describedBy || undefined)}
          aria-invalid=${ifDefined(this.invalid ? 'true' : undefined)}
          aria-required=${ifDefined(this.required ? 'true' : undefined)}
          aria-disabled=${ifDefined(isDisabled ? 'true' : undefined)}
          ?readonly=${isDisabled}
          @input=${this.handleInput}
        />
        ${message
          ? html`<ds-text
              id="error"
              role="alert"
              part="errorMessage"
              data-part="errorMessage"
              element="p"
              size="sm"
              tone="danger"
              .overrides=${textOverrides}
              >${message}</ds-text
            >`
          : nothing}
      </div>
    `;
  }

  private get isDisabled(): boolean {
    return this.disabled || this.formDisabled;
  }

  /**
   * The message in the error slot, by the doc's precedence: `error`, then
   * copy.required for an empty required field, then copy.invalid. Nothing is
   * shown unless the field is marked invalid.
   */
  private get displayedError(): string {
    if (this.error) {
      return this.error;
    }
    if (!this.invalid) {
      return '';
    }
    return this.required && this.currentValue.trim() === '' ? COPY_REQUIRED(this.label) : COPY_INVALID(this.label);
  }

  /** helperSize, fontFamily and lineHeight forwarded to the description and error Text. */
  private get textOverrides(): Partial<Record<TextOverridableBinding, TokenRef | undefined>> | undefined {
    const o = this.overrides;
    if (!o) {
      return undefined;
    }
    return { fontSize: o.helperSize, fontFamily: o.fontFamily, lineHeight: o.lineHeight };
  }

  private handleInput(event: Event): void {
    const input = event.currentTarget as HTMLInputElement;
    if (this.isDisabled) {
      return;
    }
    const next = input.value;
    if (this.value === undefined) {
      this.editedValue = next;
    } else {
      // Controlled: show the new value only once `.value` is rebound; re-render
      // so `live()` restores the controlled value if the consumer keeps it.
      this.requestUpdate();
    }
    this.dispatchEvent(
      new CustomEvent<InputChangeDetail>('change', {
        detail: { value: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as InputOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  /** Mirror value and validity into ElementInternals so an owning form sees them. */
  private syncInternals(): void {
    // A disabled field is left out of submission and validity, as a native
    // disabled control is, while staying focusable and read-only.
    if (this.isDisabled) {
      this.internals.setFormValue(null);
      this.internals.setValidity({});
      return;
    }

    const value = this.currentValue;
    const anchor = this.inputEl ?? undefined;
    this.internals.setFormValue(value);

    if (this.error) {
      this.internals.setValidity({ customError: true }, this.error, anchor);
    } else if (this.required && value.trim() === '') {
      this.internals.setValidity({ valueMissing: true }, COPY_REQUIRED(this.label), anchor);
    } else if (this.invalid) {
      this.internals.setValidity({ customError: true }, COPY_INVALID(this.label), anchor);
    } else if (anchor && !anchor.validity.valid) {
      // Browser validity for the chosen `type` (e.g. email format), reported with copy.invalid.
      this.internals.setValidity(anchor.validity, COPY_INVALID(this.label), anchor);
    } else {
      this.internals.setValidity({});
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-input': DsInput;
  }
}

// packages/rn/src/Input.tsx
import * as React from 'react';
import { AccessibilityInfo, Platform, TextInput, View, findNodeHandle } from 'react-native';
import type {
  KeyboardTypeOptions,
  NativeSyntheticEvent,
  ReturnKeyTypeOptions,
  TextInputFocusEventData,
  TextInputProps,
  TextStyle,
  ViewStyle,
} from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { useFieldsetContext } from './Fieldset';
import { useFormContext } from './FormContext';
import type { FormFieldHandle } from './FormContext';
import { Text } from './Text';
import { toLineHeight, useTheme } from './theme';
import type { Tokens } from './theme';

export type InputType = 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url';
export type InputSize = 'sm' | 'md';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type InputOverridableBinding =
  | 'borderFocus'
  | 'borderInvalid'
  | 'borderWidth'
  | 'radius'
  | 'paddingInline'
  | 'paddingBlock'
  | 'paddingBlockSm'
  | 'paddingInlineSm'
  | 'partGap'
  | 'fontFamily'
  | 'fontSize'
  | 'labelWeight'
  | 'helperSize'
  | 'lineHeight'
  | 'minTargetSm'
  | 'disabledOpacity';

export interface InputProps {
  /** Visible label. Always rendered; never replaced by a placeholder. Also the field's `accessibilityLabel`. */
  label: string;
  /** Field name used by the enclosing Form when collecting values. */
  name: string;
  /** Controlled value. Omit for an uncontrolled field. */
  value?: string;
  /** Initial value for an uncontrolled field. */
  defaultValue?: string;
  /** Example input shown while empty. Never the only description of what to enter. */
  placeholder?: string;
  /** Persistent helper text below the label explaining format or purpose. Also the field's `accessibilityHint`. */
  description?: string;
  /** Input type. Drives the keyboard (`keyboardType`, `textContentType`, `secureTextEntry`). */
  type?: InputType;
  /** The field must have a value to submit. Shown in the label, not only by color. */
  required?: boolean;
  /** Visually hide the label (it remains the field's `accessibilityLabel`). Only for a field whose context already names it. */
  hideLabel?: boolean;
  /** `sm` for fields inside grid cells and toolbars: minimum target height, tighter padding, small type. */
  size?: InputSize;
  /** Not editable and not submitted. Stays visible and readable. */
  disabled?: boolean;
  /** Marks the field as failing validation. Usually set by the Form; can be set directly. */
  invalid?: boolean;
  /** The error message. Setting it implies `invalid`. Explain what is wrong and how to fix it. */
  error?: string;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<InputOverridableBinding, TokenRef>>;
  /** Fired on every value change with the new string value. */
  onChange?: (value: string) => void;
  /** Fired when the field receives focus. */
  onFocus?: (event: NativeSyntheticEvent<TextInputFocusEventData>) => void;
  /** Fired when the field loses focus. The usual moment to validate. */
  onBlur?: (event: NativeSyntheticEvent<TextInputFocusEventData>) => void;
}

const KEYBOARD_TYPE: Record<InputType, KeyboardTypeOptions> = {
  text: 'default',
  email: 'email-address',
  password: 'default',
  number: 'numeric',
  search: 'default',
  tel: 'phone-pad',
  url: 'url',
};

const TEXT_CONTENT_TYPE: Record<InputType, TextInputProps['textContentType']> = {
  text: 'none',
  email: 'emailAddress',
  password: 'password',
  number: 'none',
  search: 'none',
  tel: 'telephoneNumber',
  url: 'URL',
};

/** Types whose values must not be auto-capitalized or auto-corrected by the keyboard. */
const VERBATIM_TYPES: ReadonlySet<InputType> = new Set<InputType>(['email', 'password', 'url']);

const FONT_SIZE_TOKEN = { sm: 'fontSizeSm', md: 'fontSizeMd' } as const satisfies Record<InputSize, keyof Tokens>;

const COPY = {
  required: (label: string): string => `${label} is required.`,
  invalid: (label: string): string => `${label} is not valid.`,
  requiredIndicator: ' (required)',
} as const;

/**
 * Input — collects a single line of text, bundling label, helper text, field and
 * error message so their association is always correct.
 *
 * When to use: Use Input for names, emails, passwords, search terms, and short
 * free-text values. Choose `type` for the value so touch keyboards and browser
 * validation match. Provide `description` when the format matters ("Use the email
 * you signed up with"). Set `autocomplete` on web whenever the value is personal
 * data so browsers and assistive tools can fill it.
 *
 * Renders a `Text` label, optional description, a `TextInput`, and an error `Text`.
 * The label is also passed as `accessibilityLabel`, description as
 * `accessibilityHint`, and `accessibilityState={{ disabled }}`. `type` maps to
 * `keyboardType`, `textContentType` and `secureTextEntry`. Inside a Form the field
 * registers `{ getValue, validate, focus }` by `name`; the last field's return key
 * submits the form. The focus ring replaces the border with `focusRingWidth`
 * (locked to `border.width.focus`) and padding shrinks by the same amount so the
 * field never shifts; `disabled` dims the whole label/description/field/error
 * group with `disabledOpacity` rather than inventing a disabled color. Inside a
 * Fieldset, the group's `disabled` applies as if set on the field and the legend
 * prefixes the field's `accessibilityLabel` ("Shipping address, Street"). `size:
 * sm` swaps `paddingBlock`/`paddingInline`/the target height for their `Sm`
 * bindings and the field text to `font.size.sm`; nothing else changes.
 */
export function Input({
  label,
  name,
  value,
  defaultValue,
  placeholder,
  description,
  type = 'text',
  required = false,
  hideLabel = false,
  size = 'md',
  disabled = false,
  invalid = false,
  error,
  overrides,
  onChange,
  onFocus,
  onBlur,
}: InputProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const form = useFormContext();
  const fieldset = useFieldsetContext();
  const inputRef = React.useRef<TextInput>(null);
  const [internalValue, setInternalValue] = React.useState<string>(defaultValue ?? '');
  const [focused, setFocused] = React.useState(false);

  const currentValue = value ?? internalValue;
  const isDisabled = disabled || (form?.disabled ?? false) || (fieldset?.disabled ?? false);
  const formError = form?.errors[name];
  const displayedError = error !== undefined && error !== '' ? error : formError;
  const isInvalid = invalid || displayedError !== undefined;
  const summarised = form !== null && form.errorSummary;

  const validateValue = React.useCallback(
    (candidate: string): string | null => {
      // Precedence: `error` prop, then `required`, then `invalid`.
      if (error !== undefined && error !== '') {
        return error;
      }
      if (required && candidate.trim() === '') {
        return COPY.required(label);
      }
      if (invalid) {
        return COPY.invalid(label);
      }
      return null;
    },
    [required, label, error, invalid],
  );

  // A stable handle whose methods read the latest render, so re-registering never
  // reorders the Form's field list.
  const latest = React.useRef({ currentValue, validateValue });
  latest.current = { currentValue, validateValue };
  const handle = React.useMemo<FormFieldHandle>(
    () => ({
      getValue: () => latest.current.currentValue,
      validate: () => latest.current.validateValue(latest.current.currentValue),
      focus: () => {
        const input = inputRef.current;
        if (input === null) {
          return;
        }
        input.focus();
        const node = findNodeHandle(input);
        if (node !== null) {
          AccessibilityInfo.setAccessibilityFocus(node);
        }
      },
    }),
    [],
  );

  const register = form?.register;
  const unregister = form?.unregister;
  React.useEffect(() => {
    if (register === undefined || unregister === undefined || isDisabled) {
      return undefined;
    }
    register(name, handle);
    return () => unregister(name);
  }, [register, unregister, name, handle, isDisabled]);

  // iOS: announce an error the moment it appears, unless the Form's summary already does.
  React.useEffect(() => {
    if (Platform.OS === 'ios' && !summarised && displayedError !== undefined) {
      AccessibilityInfo.announceForAccessibility(displayedError);
    }
  }, [displayedError, summarised]);

  const handleChangeText = (next: string): void => {
    if (value === undefined) {
      setInternalValue(next);
    }
    onChange?.(next);
    if (form !== null && form.validateMode === 'change') {
      form.reportValidity(name, validateValue(next));
    }
  };

  const handleFocus = (event: NativeSyntheticEvent<TextInputFocusEventData>): void => {
    setFocused(true);
    onFocus?.(event);
  };

  const handleBlur = (event: NativeSyntheticEvent<TextInputFocusEventData>): void => {
    setFocused(false);
    onBlur?.(event);
    if (form !== null && form.validateMode === 'blur') {
      form.reportValidity(name, validateValue(currentValue));
    }
  };

  const position = form === null ? -1 : form.order.indexOf(name);
  const isLast = form !== null && position !== -1 && position === form.order.length - 1;
  const nextName = form !== null && position !== -1 ? form.order[position + 1] : undefined;
  const returnKeyType: ReturnKeyTypeOptions | undefined = form === null ? undefined : isLast ? 'done' : 'next';

  const handleSubmitEditing = (): void => {
    if (form === null) {
      return;
    }
    if (isLast) {
      form.submit();
    } else if (nextName !== undefined) {
      form.focusField(nextName);
    }
  };

  const visibleLabel = required ? `${label}${COPY.requiredIndicator}` : label;
  const accessibleLabel = fieldset !== null ? `${fieldset.legend}, ${visibleLabel}` : visibleLabel;

  const borderFocusColor = overrides?.borderFocus ? (resolveToken(t, overrides.borderFocus) as string) : t.colorBorderFocus;
  const borderInvalidColor = overrides?.borderInvalid ? (resolveToken(t, overrides.borderInvalid) as string) : t.colorBorderDanger;
  const borderWidth = overrides?.borderWidth ? (resolveToken(t, overrides.borderWidth) as number) : t.borderWidthThin;
  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusMd;
  const paddingInline =
    size === 'sm'
      ? overrides?.paddingInlineSm
        ? (resolveToken(t, overrides.paddingInlineSm) as number)
        : t.space2
      : overrides?.paddingInline
        ? (resolveToken(t, overrides.paddingInline) as number)
        : t.spaceMd;
  const paddingBlock =
    size === 'sm'
      ? overrides?.paddingBlockSm
        ? (resolveToken(t, overrides.paddingBlockSm) as number)
        : t.space1
      : overrides?.paddingBlock
        ? (resolveToken(t, overrides.paddingBlock) as number)
        : t.spaceSm;
  const minTarget =
    size === 'sm'
      ? overrides?.minTargetSm
        ? (resolveToken(t, overrides.minTargetSm) as number)
        : t.sizeTargetMin
      : t.sizeTargetComfortable;
  const partGap = overrides?.partGap ? (resolveToken(t, overrides.partGap) as number) : t.space1;
  const fontFamily = overrides?.fontFamily ? (resolveToken(t, overrides.fontFamily) as string) : t.fontFamilyBody;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t[FONT_SIZE_TOKEN[size]];
  const lineHeightMultiplier = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;
  const disabledOpacity = overrides?.disabledOpacity ? (resolveToken(t, overrides.disabledOpacity) as number) : t.opacityDisabled;

  // The focus ring is drawn by widening the border to the locked `focusRingWidth`;
  // padding shrinks by the same amount so the field never shifts when it gains focus.
  const activeBorderWidth = focused ? t.borderWidthFocus : borderWidth;
  const inset = t.borderWidthFocus - borderWidth;

  const containerStyle: ViewStyle = {
    flexDirection: 'column',
    gap: partGap,
    opacity: isDisabled ? disabledOpacity : 1,
  };

  const fieldStyle: TextStyle = {
    minHeight: minTarget,
    backgroundColor: t.colorBackground,
    color: t.colorForeground,
    borderWidth: activeBorderWidth,
    borderColor: focused ? borderFocusColor : isInvalid ? borderInvalidColor : t.colorBorderStrong,
    borderRadius: radius,
    paddingHorizontal: paddingInline + inset,
    paddingVertical: paddingBlock + inset,
    fontFamily,
    fontSize,
    lineHeight: toLineHeight(fontSize, lineHeightMultiplier),
  };

  const helperOverrides = { fontFamily: overrides?.fontFamily, fontSize: overrides?.helperSize, lineHeight: overrides?.lineHeight };

  return (
    <View style={containerStyle} testID="Input">
      {hideLabel ? null : (
        <Text
          weight="medium"
          overrides={{ fontFamily: overrides?.fontFamily, fontSize: overrides?.fontSize, fontWeight: overrides?.labelWeight, lineHeight: overrides?.lineHeight }}
        >
          {visibleLabel}
        </Text>
      )}
      {description !== undefined ? (
        <Text size="sm" tone="muted" overrides={helperOverrides}>
          {description}
        </Text>
      ) : null}
      <TextInput
        ref={inputRef}
        accessibilityLabel={accessibleLabel}
        accessibilityHint={description}
        accessibilityState={{ disabled: isDisabled }}
        keyboardType={KEYBOARD_TYPE[type]}
        textContentType={TEXT_CONTENT_TYPE[type]}
        secureTextEntry={type === 'password'}
        autoCapitalize={VERBATIM_TYPES.has(type) ? 'none' : 'sentences'}
        autoCorrect={!VERBATIM_TYPES.has(type)}
        allowFontScaling
        editable={!isDisabled}
        value={currentValue}
        placeholder={placeholder}
        placeholderTextColor={t.colorForegroundMuted}
        returnKeyType={returnKeyType}
        blurOnSubmit={isLast}
        onSubmitEditing={handleSubmitEditing}
        onChangeText={handleChangeText}
        onFocus={handleFocus}
        onBlur={handleBlur}
        style={fieldStyle}
      />
      {displayedError !== undefined ? (
        <View accessibilityLiveRegion={summarised ? 'none' : 'assertive'}>
          <Text size="sm" tone="danger" overrides={helperOverrides}>
            {displayedError}
          </Text>
        </View>
      ) : null}
    </View>
  );
}
