// packages/lit/src/Link.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';

export type LinkTone = 'default' | 'inherit';

/** copy.externalSuffix — appended to the accessible name of an external link. */
const EXTERNAL_SUFFIX = ' (opens in new tab)';

/** Overridable style hooks; see the `overrides` property. `color`, `colorHover`, `colorVisited`, `focusRing`, `focusRingWidth` and `focusRingRadius` are locked and excluded. */
export type LinkOverridableBinding = 'underlineThickness' | 'underlineOffset' | 'externalIconGap' | 'transition';

const HOOKS: Record<LinkOverridableBinding, string> = {
  underlineThickness: '--ds-link-underline-thickness',
  underlineOffset: '--ds-link-underline-offset',
  externalIconGap: '--ds-link-external-icon-gap',
  transition: '--ds-link-transition',
};

/**
 * `<ds-link>` — Link (category: navigation, APG pattern: link).
 *
 * Wraps a native `<a href>` in a shadow root created with `delegatesFocus`, so
 * focusing the host focuses the anchor. There is no custom event: the native
 * `click` bubbles and retargets to the host, and consumers who route
 * client-side call `preventDefault()` on it there. The host is `display: inline`
 * so a link can sit inside a `<ds-text>` paragraph.
 *
 * ## When to use
 *
 * Use a Link for any navigation: another page, a screen, an anchor, an
 * external site, or a downloadable file. Use `external` whenever the
 * destination leaves the product so people are warned before they lose their
 * place. Do not use a Link to trigger an action; that is a ghost Button.
 *
 * @csspart anchor - The native `<a>` (anatomy: anchor).
 * @csspart label - The visible link text (anatomy: label).
 * @csspart external-icon - The decorative trailing icon shown when `external` (anatomy: externalIcon).
 */
@customElement('ds-link')
export class DsLink extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: inline;
      --ds-link-underline-thickness: var(--border-width-thin);
      --ds-link-underline-offset: var(--space-1);
      --ds-link-external-icon-gap: var(--space-1);
      --ds-link-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    a {
      /* Inherit the surrounding font so the link flows with its paragraph. */
      font: inherit;
      color: var(--color-link);
      text-decoration-line: underline;
      text-decoration-thickness: var(--ds-link-underline-thickness);
      text-underline-offset: var(--ds-link-underline-offset);
      border-radius: var(--radius-sm);
      cursor: pointer;
      transition: color var(--ds-link-transition) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      a {
        transition: none;
      }
    }

    /* colorVisited: web and Lit only */
    a:visited {
      color: var(--color-link-visited);
    }

    /* colorHover: pointer hover and active state */
    a:is(:hover, :active) {
      color: var(--color-link-hover);
    }

    /* tone=inherit: takes the surrounding text color; the underline alone marks the link */
    :host([tone='inherit']) a,
    :host([tone='inherit']) a:visited,
    :host([tone='inherit']) a:is(:hover, :active) {
      color: inherit;
    }

    /* focus-visible: the ring follows the text box (inline), rounded by focusRingRadius */
    a:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
      border-radius: var(--radius-sm);
    }

    /* externalIcon: 1em of the surrounding font size (ds-icon's own inline sizing), never larger */
    ds-icon {
      margin-inline-start: var(--ds-link-external-icon-gap);
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** The destination URL. */
  @property() accessor href = '';

  /** The link text. Also the accessible name. Says where the link goes, not "click here". */
  @property() accessor label = '';

  /** Opens in a new tab and appends the external suffix to the accessible name, with a decorative trailing icon. */
  @property({ type: Boolean, reflect: true }) accessor external = false;

  /** `default` uses the link colors. `inherit` takes the surrounding text color and relies on the underline alone. */
  @property({ reflect: true }) accessor tone: LinkTone = 'default';

  /** Downloads the resource instead of navigating. */
  @property({ type: Boolean, reflect: true }) accessor download = false;

  /** Per-instance style overrides: `{ underlineOffset: 'space.2' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<LinkOverridableBinding, TokenRef | undefined>> | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Link');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    return html`
      <a
        part="anchor"
        href=${this.href}
        target=${ifDefined(this.external ? '_blank' : undefined)}
        rel=${ifDefined(this.external ? 'noopener noreferrer' : undefined)}
        ?download=${this.download}
      >
        <span part="label">${this.label}</span>${this.external
          ? html`<span class="visually-hidden">${EXTERNAL_SUFFIX}</span
              ><ds-icon part="external-icon" name="external" inline></ds-icon>`
          : nothing}
      </a>
    `;
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as LinkOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-link': DsLink;
  }
}

// packages/rn/src/Link.tsx
import * as React from 'react';
import { Animated, Linking, Text as RNText } from 'react-native';
import type { TextStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import { TextNestingContext } from './Text';
import { toEasing, toFontWeight, toLineHeight, useReducedMotion, useTheme } from './theme';

export type LinkTone = 'default' | 'inherit';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type LinkOverridableBinding = 'transition';

export interface LinkProps {
  /** The destination. A URL or app route on native, resolved by `onPress` when the consumer provides it. */
  href: string;
  /** The link text. Also the accessible name. Says where the link goes, not "click here". */
  label: string;
  /** Marks a destination outside the product: appends `copy.externalSuffix` to the accessible name, with a decorative trailing icon. Navigation is still `onPress` or `Linking`. */
  external?: boolean;
  /** `default` uses the link colors. `inherit` takes the surrounding text color and relies on the underline alone. */
  tone?: LinkTone;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<LinkOverridableBinding, TokenRef>>;
  /**
   * Fired when the link is activated, with `href`. On native the consumer's handler
   * is the navigation; when no handler is given the system opens the URL with `Linking`.
   */
  onPress?: (href: string) => void;
}

const COPY = {
  externalSuffix: ' (opens in new tab)',
} as const;

/** `copy.externalSuffix`, exposed so composites (e.g. `Card`) can reproduce a Link's accessible name when they move it onto a wrapping element. */
export const LINK_EXTERNAL_SUFFIX = COPY.externalSuffix;

/**
 * Link — takes people somewhere. Buttons do things; links navigate.
 *
 * When to use: Use a Link for any navigation: to another screen, to an external
 * site, or inline inside body text. Use `external` whenever the destination leaves
 * the product, so people are warned before they lose their place. Do not use a Link
 * to trigger an action — that is a `ghost` Button.
 *
 * Renders `Text` with `accessibilityRole="link"` so it flows inline inside a parent
 * `Text`; standalone it is its own line. `accessibilityLabel` is the label plus
 * `copy.externalSuffix` when `external`. Activation calls `onPress(href)` when
 * provided, otherwise `Linking.openURL(href)` — never both. Standalone, the Link
 * sets the body typography via Text's helpers since there is no cascade; nested in
 * a system `Text` (detected through `TextNestingContext`) it inherits.
 *
 * There is no hover or visited state on native, so `colorHover` styles the pressed
 * state (`colorVisited` unused) and the color crossfades over `transition` (eased
 * with `motion.easing.standard`, skipped under reduced motion) the same way Button
 * animates its background. RN cannot set underline offset or thickness, and nested
 * `Text` ignores margins, so `underlineThickness`, `underlineOffset` and
 * `externalIconGap` have no effect on this platform and are excluded from
 * `LinkOverridableBinding`; a literal space separates the label from the external
 * glyph instead. `Text` has no focus events, so the focus ring (`focusRing*` tokens)
 * cannot be drawn by hand: hardware-keyboard focus relies on the platform's own
 * indicator, and react-native-web renders a real anchor with the browser's focus
 * outline. The external glyph is the shared `Icon` (`name="external"`, `inline`),
 * matching Icon's own documented use for this mark; because Icon has no
 * `currentColor` fallback for animated color, its color swaps instantly with the
 * pressed state rather than crossfading. The link is never disabled: a destination
 * that is not available is rendered as Text.
 */
export function Link({
  href,
  label,
  external = false,
  tone = 'default',
  overrides,
  onPress,
}: LinkProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const nested = React.useContext(TextNestingContext);
  const reducedMotion = useReducedMotion();
  const [pressed, setPressed] = React.useState(false);

  const transitionDuration = overrides?.transition
    ? (resolveToken(t, overrides.transition) as number)
    : t.motionDurationFast;

  // Crossfades between rest and pressed since there is no hover on touch, mirroring Button.
  const highlight = React.useRef(new Animated.Value(0)).current;
  React.useEffect(() => {
    if (tone === 'inherit') {
      return undefined;
    }
    const toValue = pressed ? 1 : 0;
    if (reducedMotion) {
      highlight.setValue(toValue);
      return undefined;
    }
    const animation = Animated.timing(highlight, {
      toValue,
      duration: transitionDuration,
      easing: toEasing(t.motionEasingStandard),
      // Color is not a layout property, but react-native-web has no native animated module.
      useNativeDriver: false,
    });
    animation.start();
    return () => animation.stop();
  }, [pressed, reducedMotion, highlight, transitionDuration, t.motionEasingStandard, tone]);

  const animatedColor = highlight.interpolate({ inputRange: [0, 1], outputRange: [t.colorLink, t.colorLinkHover] });
  const iconColor = tone === 'inherit' ? undefined : pressed ? t.colorLinkHover : t.colorLink;

  const handlePress = (): void => {
    // The consumer's handler is the navigation; only without one does the system open the URL.
    if (onPress !== undefined) {
      onPress(href);
      return;
    }
    Linking.openURL(href).catch(() => undefined);
  };

  // Standalone, the Link sets the body typography (there is no cascade); nested in
  // a system Text it sets none and inherits the surrounding style.
  const typography: TextStyle = nested
    ? {}
    : {
        fontFamily: t.fontFamilyBody,
        fontWeight: toFontWeight(t.fontWeightRegular),
        fontSize: t.fontSizeMd,
        lineHeight: toLineHeight(t.fontSizeMd, t.fontLineHeightNormal),
      };

  const style: TextStyle = {
    ...typography,
    textDecorationLine: 'underline',
  };

  return (
    <Animated.Text
      testID="Link"
      accessibilityRole="link"
      accessibilityLabel={external ? `${label}${COPY.externalSuffix}` : label}
      allowFontScaling
      onPress={handlePress}
      onPressIn={() => setPressed(true)}
      onPressOut={() => setPressed(false)}
      style={[
        style,
        tone === 'inherit' ? null : { color: animatedColor, textDecorationColor: animatedColor },
      ]}
    >
      {label}
      {external ? ' ' : null}
      {external ? <Icon name="external" inline color={iconColor} /> : null}
    </Animated.Text>
  );
}
