// packages/lit/src/Tooltip.ts
import { LitElement, css, html, render as litRender, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import type { TextOverridableBinding } from './Text.js';

export type TooltipPlacement = 'top' | 'bottom' | 'start' | 'end';
export type TooltipDelay = 'default' | 'none';

/** Overridable style hooks; see the `overrides` property. `surface` and `text` are locked and excluded. */
export type TooltipOverridableBinding =
  | 'radius'
  | 'paddingBlock'
  | 'paddingInline'
  | 'offset'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'shadow'
  | 'layer'
  | 'enter'
  | 'exit';

/**
 * Typography belongs to the composed Text, so `fontFamily`, `fontSize` and `lineHeight` are
 * forward-only: they have no `--ds-tooltip-*` hook, and the value — an override or this default —
 * is always passed to Text's `overrides` under the same name.
 */
type TooltipTextBinding = TooltipOverridableBinding & TextOverridableBinding;

const TEXT_DEFAULT: Record<TooltipTextBinding, TokenRef> = {
  fontFamily: 'font.family.body', // literal-ok: a TokenRef forwarded to Text, not a font stack
  fontSize: 'font.size.sm',
  lineHeight: 'font.lineHeight.normal',
};

/** Hooks for the bindings the bubble styles itself; the typography three are forwarded instead. */
const HOOKS: Record<Exclude<TooltipOverridableBinding, TooltipTextBinding>, string> = {
  radius: '--ds-tooltip-radius',
  paddingBlock: '--ds-tooltip-padding-block',
  paddingInline: '--ds-tooltip-padding-inline',
  offset: '--ds-tooltip-offset',
  maxWidth: '--ds-tooltip-max-width',
  shadow: '--ds-tooltip-shadow',
  layer: '--ds-tooltip-layer',
  enter: '--ds-tooltip-enter',
  exit: '--ds-tooltip-exit',
};

/** Whether the running browser implements the Popover API. Evaluated once. */
const POPOVER_SUPPORTED = typeof HTMLElement !== 'undefined' && typeof HTMLElement.prototype.showPopover === 'function';

/* Constants and the offset length, as their token expressions; resolved through getComputedStyle when needed. */
/** hoverDelay: motion.duration.base × 3, when `delay` is `default`. */
const HOVER_DELAY = 'calc(var(--motion-duration-base) * 3)';
/** warmWindow: motion.duration.base — after one tooltip hides, the next sibling shows with no delay. */
const WARM_WINDOW = 'var(--motion-duration-base)';
/** pointerGrace: motion.duration.fast — the pointer may cross the `offset` gap onto the bubble. */
const POINTER_GRACE = 'var(--motion-duration-fast)';
/** offset: the gap between the trigger and the bubble, read in px from the hook. */
const OFFSET = 'var(--ds-tooltip-offset)';

let idCounter = 0;
function nextTooltipId(): string {
  idCounter += 1;
  return `ds-tooltip-${idCounter}`;
}

/** Parses a computed `<time>` list ("0.6s", "200ms") into ms; anything unresolved is 0. */
function parseTimeMs(raw: string): number {
  const first = (raw.split(',')[0] ?? '').trim();
  let ms = 0;
  if (first.endsWith('ms')) {
    ms = parseFloat(first);
  } else if (first.endsWith('s')) {
    ms = parseFloat(first) * 1000;
  }
  return Number.isFinite(ms) ? ms : 0;
}

/** Shared "warm" state: until this timestamp a newly hovered tooltip shows with no delay. Set whenever any tooltip hides. */
let warmUntil = 0;

const BUBBLE_CLASS = 'ds-tooltip-bubble';
const DESCRIPTION_CLASS = 'ds-tooltip-description';
const LIGHT_STYLE_MARKER = 'data-ds-tooltip-style';

/* The description copy and the bubble live in the light DOM (so the trigger's ID reference resolves), which
   `ds-tooltip`'s shadow stylesheet cannot reach; their rules are injected into the tree they live in.
   surface: color.inverse.surface and text: color.inverse.foreground are locked. Text's color is locked too,
   so the bubble re-scopes --color-foreground on its own container and composes <ds-text> unchanged.
   fontFamily, fontSize and lineHeight are absent here on purpose: they are forwarded to that <ds-text>. */
const LIGHT_STYLE_CSS = `
.${DESCRIPTION_CLASS} {
  /* literal-ok: standard visually-hidden clip pattern, exempt from token-only rule */
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
.${BUBBLE_CLASS} {
  --color-foreground: var(--color-inverse-foreground);
  position: fixed;
  inset: auto;
  box-sizing: border-box;
  margin: 0;
  border: none;
  padding-block: var(--ds-tooltip-padding-block);
  padding-inline: var(--ds-tooltip-padding-inline);
  border-radius: var(--ds-tooltip-radius);
  background: var(--color-inverse-surface);
  color: var(--color-inverse-foreground);
  box-shadow: var(--ds-tooltip-shadow);
  inline-size: max-content;
  max-inline-size: calc(var(--ds-tooltip-max-width) * 3);
  overflow-wrap: break-word;
  z-index: var(--ds-tooltip-layer);
  opacity: 0;
  pointer-events: none;
  transition:
    opacity var(--ds-tooltip-exit) var(--motion-easing-standard),
    display var(--ds-tooltip-exit) allow-discrete,
    overlay var(--ds-tooltip-exit) allow-discrete;
}
.${BUBBLE_CLASS}:popover-open,
.${BUBBLE_CLASS}[data-open] {
  opacity: 1;
  pointer-events: auto;
  transition:
    opacity var(--ds-tooltip-enter) var(--motion-easing-standard),
    display var(--ds-tooltip-enter) allow-discrete,
    overlay var(--ds-tooltip-enter) allow-discrete;
}
@starting-style {
  .${BUBBLE_CLASS}:popover-open,
  .${BUBBLE_CLASS}[data-open] {
    opacity: 0;
  }
}
.${BUBBLE_CLASS}[hidden] {
  display: none;
}
@media (prefers-reduced-motion: reduce) {
  .${BUBBLE_CLASS},
  .${BUBBLE_CLASS}:popover-open,
  .${BUBBLE_CLASS}[data-open] {
    transition: none;
  }
}
`;

/** Roots that already carry the light-DOM stylesheet (a Document per page, a ShadowRoot per nesting host). */
const styledRoots = new WeakSet<Document | ShadowRoot>();

function ensureLightStyle(root: Node): void {
  if (!(root instanceof Document) && !(root instanceof ShadowRoot)) {
    return;
  }
  if (styledRoots.has(root)) {
    return;
  }
  styledRoots.add(root);
  const target = root instanceof Document ? root.head : root;
  if (target.querySelector(`style[${LIGHT_STYLE_MARKER}]`) !== null) {
    return;
  }
  const style = document.createElement('style');
  style.setAttribute(LIGHT_STYLE_MARKER, '');
  style.textContent = LIGHT_STYLE_CSS;
  target.appendChild(style);
}

/** The attribute Tooltip wrote onto the trigger, so it only ever removes its own value. */
interface TriggerLink {
  attribute: 'aria-describedby' | 'aria-labelledby' | 'aria-description' | 'aria-label';
  value: string;
}

/**
 * `<ds-tooltip>` — Tooltip (category: overlay, APG pattern: tooltip).
 *
 * `<ds-tooltip content="Bold" no-describes><ds-button icon-only label="Bold">…</ds-button></ds-tooltip>`
 * wraps its single focusable child. Because ID references cannot cross a shadow
 * boundary, the tooltip is not rendered in this element's shadow root. Two
 * light-DOM nodes are appended to the host, siblings of the trigger: a
 * visually-hidden `<span role="tooltip" id>`, always in the accessibility tree,
 * and the positioned bubble (`data-part="popup"`, `aria-hidden`, the visible
 * copy) shown with the Popover API (`popover="manual"`) or a `position: fixed`
 * fallback. A plain light-DOM trigger gets `aria-describedby` (or
 * `aria-labelledby` with `describes: false`) pointing at the span; a custom
 * element (a hyphenated tag name) gets the text itself as `aria-description`
 * (or `aria-label`). The bubble shows after `delay` on hover, immediately on focus,
 * stays while the pointer is over it (hoverable), and hides on Escape without
 * moving focus, when focus leaves the trigger, or when the pointer leaves both.
 *
 * ## When to use
 *
 * On an icon-only Button to show its name (`describes: false`, content equal to
 * the child's label), or on a labelled control to add a short clarification.
 * Keep it to a phrase.
 *
 * ## When not to use
 *
 * Not for content the user must read (helper text, an Alert or a Disclosure),
 * not for anything interactive (a Popover, planned), and never on a
 * non-focusable child — keyboard users could never see it.
 *
 * @slot - Exactly one focusable element (a Button, Link, Input) the tooltip attaches to.
 */
@customElement('ds-tooltip')
export class DsTooltip extends LitElement {
  static override styles: CSSResult = css`
    :host {
      display: contents;
      --ds-tooltip-radius: var(--radius-sm);
      --ds-tooltip-padding-block: var(--space-1);
      --ds-tooltip-padding-inline: var(--space-2);
      --ds-tooltip-offset: var(--space-1);
      --ds-tooltip-max-width: var(--space-20);
      /* fontFamily, fontSize and lineHeight are forward-only: no hook here, they reach the composed Text. */
      --ds-tooltip-shadow: var(--shadow-raised);
      --ds-tooltip-layer: var(--layer-toast);
      --ds-tooltip-enter: var(--motion-duration-fast);
      --ds-tooltip-exit: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }
  `;

  /** The tooltip text. One short phrase or sentence; no markup, no links, no line breaks. */
  @property() accessor content: string = '';

  /** Preferred side; flips when it would overflow the viewport. `start`/`end` are logical and mirror in right-to-left writing. */
  @property({ type: String, reflect: true }) accessor placement: TooltipPlacement = 'top';

  /**
   * `true`: supplementary, the child's accessible description. `false`: the tooltip IS the child's name.
   * Defaults to true, so the attribute is the negated `no-describes`.
   */
  @property({
    type: Boolean,
    reflect: true,
    attribute: 'no-describes',
    converter: {
      fromAttribute: (value: string | null): boolean => value === null,
      toAttribute: (value: boolean): string | null => (value ? null : ''),
    },
  })
  accessor describes: boolean = true;

  /** Hover delay before showing: `default` (motion.duration.base × 3) or `none` for a warm toolbar. */
  @property({ type: String }) accessor delay: TooltipDelay = 'default';

  /**
   * Controlled visibility, for stories and tests only (the `Keyboard` story renders the tooltip open with it).
   * Product code never sets it: a tooltip is hover and focus driven. Escape still hides a tooltip rendered
   * with `open`, and it stays hidden until `open` next changes.
   */
  @property({ type: Boolean }) accessor open: boolean | undefined;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings are not in the type. */
  @property({ attribute: false }) accessor overrides: Partial<Record<TooltipOverridableBinding, TokenRef | undefined>> | undefined;

  private readonly tooltipId: string = nextTooltipId();
  private descriptionEl: HTMLSpanElement | null = null;
  private bubbleEl: HTMLDivElement | null = null;
  private triggerEl: HTMLElement | null = null;
  private triggerLink: TriggerLink | null = null;
  private visible = false;
  /** Escape hides the tooltip until the trigger loses hover and focus, or (controlled) `open` next changes. */
  private dismissed = false;
  private pointerOverTrigger = false;
  private pointerOverBubble = false;
  private triggerFocused = false;
  private showTimerId: ReturnType<typeof setTimeout> | undefined;
  private hideGraceTimerId: ReturnType<typeof setTimeout> | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Tooltip');
    this.ensureLightNodes();
    ensureLightStyle(this.getRootNode());
    this.renderLightContent();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    clearTimeout(this.showTimerId);
    clearTimeout(this.hideGraceTimerId);
    this.hideBubble();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('content') || changed.has('overrides')) {
      this.renderLightContent();
    }
    if (changed.has('describes') || changed.has('content')) {
      this.updateTriggerAria();
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('open')) {
      // A tooltip dismissed with Escape stays hidden until `open` next changes.
      this.dismissed = false;
      if (this.open === true) {
        this.showBubble();
      } else if (this.open === false) {
        this.hideBubble();
      }
    }
    if (this.visible && changed.has('placement')) {
      this.updatePosition();
    }
    if (changed.has('content')) {
      this.warnInDev();
    }
  }

  protected override render(): TemplateResult {
    return html`<slot @slotchange=${this.handleSlotChange}></slot>`;
  }

  /** `open` set: visibility follows the property (and Escape), not hover or focus. */
  private get controlled(): boolean {
    return this.open !== undefined;
  }

  /** Creates the description copy and the bubble once, and appends them only when not already in place. */
  private ensureLightNodes(): void {
    if (!this.descriptionEl) {
      const description = document.createElement('span');
      description.id = this.tooltipId;
      description.setAttribute('role', 'tooltip');
      description.className = DESCRIPTION_CLASS;
      this.descriptionEl = description;
    }
    if (!this.bubbleEl) {
      const bubble = document.createElement('div');
      bubble.className = BUBBLE_CLASS;
      bubble.setAttribute('aria-hidden', 'true');
      bubble.setAttribute('data-part', 'popup');
      if (POPOVER_SUPPORTED) {
        bubble.setAttribute('popover', 'manual');
      } else {
        bubble.hidden = true;
      }
      bubble.addEventListener('pointerenter', this.handleBubblePointerEnter);
      bubble.addEventListener('pointerleave', this.handleBubblePointerLeave);
      this.bubbleEl = bubble;
    }
    if (this.descriptionEl.parentElement !== this) {
      this.appendChild(this.descriptionEl);
    }
    if (this.bubbleEl.parentElement !== this) {
      this.appendChild(this.bubbleEl);
    }
  }

  private readonly handleSlotChange = (event: Event): void => {
    const slot = event.target as HTMLSlotElement;
    const assigned = slot
      .assignedElements({ flatten: true })
      .filter((el): el is HTMLElement => el !== this.bubbleEl && el !== this.descriptionEl && el instanceof HTMLElement);
    if (import.meta.env.DEV && assigned.length > 1) {
      console.warn('<ds-tooltip> takes exactly one focusable child; only the first is the trigger.', this);
    }
    const next = assigned[0] ?? null;
    if (next === this.triggerEl) {
      return;
    }
    this.detachTrigger();
    this.triggerEl = next;
    this.attachTrigger();
    if (this.open === true && !this.dismissed) {
      this.showBubble();
    }
  };

  private attachTrigger(): void {
    const trigger = this.triggerEl;
    if (!trigger) {
      return;
    }
    trigger.addEventListener('pointerenter', this.handleTriggerPointerEnter);
    trigger.addEventListener('pointerleave', this.handleTriggerPointerLeave);
    trigger.addEventListener('focusin', this.handleTriggerFocusIn);
    trigger.addEventListener('focusout', this.handleTriggerFocusOut);
    this.updateTriggerAria();
    this.warnInDev();
  }

  private detachTrigger(): void {
    const trigger = this.triggerEl;
    if (!trigger) {
      return;
    }
    trigger.removeEventListener('pointerenter', this.handleTriggerPointerEnter);
    trigger.removeEventListener('pointerleave', this.handleTriggerPointerLeave);
    trigger.removeEventListener('focusin', this.handleTriggerFocusIn);
    trigger.removeEventListener('focusout', this.handleTriggerFocusOut);
    this.clearTriggerLink();
    this.pointerOverTrigger = false;
    this.triggerFocused = false;
    this.hideBubble();
  }

  /**
   * Links the trigger to the tooltip text. ID references do not reach into a trigger's shadow root, so a custom
   * element — one whose tag name contains a hyphen, whether or not it is upgraded or its shadow root is open —
   * gets the text itself (`aria-description`, or `aria-label` when the tooltip is the name), which ds-button,
   * ds-link and ds-input forward to their inner control; a plain light-DOM trigger gets `aria-describedby` /
   * `aria-labelledby` pointing at the description copy.
   */
  private updateTriggerAria(): void {
    const trigger = this.triggerEl;
    if (!trigger) {
      return;
    }
    const byText = trigger.tagName.includes('-');
    const next: TriggerLink = byText
      ? { attribute: this.describes ? 'aria-description' : 'aria-label', value: this.content }
      : { attribute: this.describes ? 'aria-describedby' : 'aria-labelledby', value: this.tooltipId };
    const previous = this.triggerLink;
    if (previous && previous.attribute !== next.attribute) {
      this.clearTriggerLink();
    }
    if (trigger.getAttribute(next.attribute) !== next.value) {
      trigger.setAttribute(next.attribute, next.value);
    }
    this.triggerLink = next;
  }

  private clearTriggerLink(): void {
    const trigger = this.triggerEl;
    const link = this.triggerLink;
    if (trigger && link && trigger.getAttribute(link.attribute) === link.value) {
      trigger.removeAttribute(link.attribute);
    }
    this.triggerLink = null;
  }

  private readonly handleTriggerPointerEnter = (event: PointerEvent): void => {
    // Never shown on touch (no hover); the text stays in the tree through the description copy.
    if (event.pointerType === 'touch') {
      return;
    }
    this.pointerOverTrigger = true;
    clearTimeout(this.hideGraceTimerId);
    this.requestShow(false);
  };

  private readonly handleTriggerPointerLeave = (event: PointerEvent): void => {
    if (event.pointerType === 'touch') {
      return;
    }
    this.pointerOverTrigger = false;
    this.scheduleMaybeHide();
  };

  private readonly handleTriggerFocusIn = (): void => {
    this.triggerFocused = true;
    this.requestShow(true);
  };

  private readonly handleTriggerFocusOut = (event: FocusEvent): void => {
    const next = event.relatedTarget;
    if (next instanceof Node && this.triggerEl?.contains(next)) {
      return;
    }
    this.triggerFocused = false;
    this.scheduleMaybeHide();
  };

  /**
   * Escape hides the tooltip without moving focus, wherever focus is (WCAG 1.4.13). Attached to the document in
   * the capture phase only while the bubble is visible, and it stops that Escape, so inside a Dialog the first
   * Escape hides the tooltip and the second closes the Dialog.
   */
  private readonly handleDocumentKeydown = (event: KeyboardEvent): void => {
    if (event.key !== 'Escape' || !this.visible) {
      return;
    }
    event.stopPropagation();
    event.preventDefault();
    this.dismissed = true;
    this.hideBubble();
  };

  private readonly handleBubblePointerEnter = (): void => {
    this.pointerOverBubble = true;
    clearTimeout(this.hideGraceTimerId);
  };

  private readonly handleBubblePointerLeave = (): void => {
    this.pointerOverBubble = false;
    this.scheduleMaybeHide();
  };

  private readonly handleReposition = (): void => {
    if (this.visible) {
      this.updatePosition();
    }
  };

  private requestShow(immediate: boolean): void {
    if (this.visible || this.controlled || this.dismissed) {
      return;
    }
    clearTimeout(this.showTimerId);
    this.showTimerId = undefined;
    if (immediate || this.delay === 'none' || Date.now() < warmUntil) {
      this.showBubble();
    } else {
      this.showTimerId = setTimeout(() => this.showBubble(), this.resolveMs(HOVER_DELAY));
    }
  }

  /**
   * Waits one pointerGrace so the pointer can cross the `offset` gap to the bubble, then hides if the trigger
   * has lost hover and focus. Losing both also clears an Escape dismissal, so the next hover shows it again.
   */
  private scheduleMaybeHide(): void {
    if (this.controlled) {
      return;
    }
    clearTimeout(this.showTimerId);
    this.showTimerId = undefined;
    clearTimeout(this.hideGraceTimerId);
    this.hideGraceTimerId = setTimeout(() => {
      if (this.pointerOverTrigger || this.pointerOverBubble || this.triggerFocused) {
        return;
      }
      this.dismissed = false;
      this.hideBubble();
    }, this.resolveMs(POINTER_GRACE));
  }

  private showBubble(): void {
    const bubble = this.bubbleEl;
    if (this.visible || !this.triggerEl || !bubble || !this.isConnected) {
      return;
    }
    this.visible = true;
    clearTimeout(this.showTimerId);
    this.showTimerId = undefined;
    if (POPOVER_SUPPORTED) {
      if (!bubble.matches(':popover-open')) {
        bubble.showPopover();
      }
    } else {
      bubble.hidden = false;
      bubble.toggleAttribute('data-open', true);
    }
    this.updatePosition();
    window.addEventListener('scroll', this.handleReposition, true);
    window.addEventListener('resize', this.handleReposition);
    document.addEventListener('keydown', this.handleDocumentKeydown, true);
  }

  private hideBubble(): void {
    clearTimeout(this.showTimerId);
    this.showTimerId = undefined;
    if (!this.visible) {
      return;
    }
    this.visible = false;
    clearTimeout(this.hideGraceTimerId);
    const bubble = this.bubbleEl;
    if (bubble) {
      if (POPOVER_SUPPORTED) {
        if (bubble.matches(':popover-open')) {
          bubble.hidePopover();
        }
      } else {
        bubble.toggleAttribute('data-open', false);
        bubble.hidden = true;
      }
    }
    window.removeEventListener('scroll', this.handleReposition, true);
    window.removeEventListener('resize', this.handleReposition);
    document.removeEventListener('keydown', this.handleDocumentKeydown, true);
    warmUntil = Date.now() + this.resolveMs(WARM_WINDOW);
  }

  /**
   * Lets the browser evaluate a token expression by setting it on the always-present, visually-hidden
   * description node — a hidden probe inside this element, so it sees the hooks set on the host — and
   * reading the computed value back. An unresolved value (no theme loaded) computes to 0.
   */
  private resolveComputed(property: 'transition-duration' | 'padding-left', expression: string): string {
    const probe = this.descriptionEl;
    if (!probe || !probe.isConnected) {
      return '';
    }
    probe.style.setProperty(property, expression);
    const value = getComputedStyle(probe).getPropertyValue(property);
    probe.style.removeProperty(property);
    return value;
  }

  /** Resolves a duration token expression in ms; unresolved (no theme) is 0. */
  private resolveMs(expression: string): number {
    return parseTimeMs(this.resolveComputed('transition-duration', expression));
  }

  /** Resolves a length token expression in px through a hidden probe's `padding-left`; unresolved is 0. */
  private resolvePx(expression: string): number {
    return Number.parseFloat(this.resolveComputed('padding-left', expression)) || 0;
  }

  /** Positions the bubble from the trigger rect at `placement`, resolving start/end from the trigger's direction and flipping on overflow. */
  private updatePosition(): void {
    const trigger = this.triggerEl;
    const bubble = this.bubbleEl;
    if (!trigger || !bubble) {
      return;
    }
    const triggerRect = trigger.getBoundingClientRect();
    const bubbleRect = bubble.getBoundingClientRect();
    const viewportWidth = document.documentElement.clientWidth;
    const viewportHeight = document.documentElement.clientHeight;
    const gap = this.resolvePx(OFFSET);
    const rtl = getComputedStyle(trigger).direction === 'rtl';

    type Side = 'top' | 'bottom' | 'left' | 'right';
    let side: Side =
      this.placement === 'start' ? (rtl ? 'right' : 'left') : this.placement === 'end' ? (rtl ? 'left' : 'right') : this.placement;
    if (side === 'top' && triggerRect.top - gap - bubbleRect.height < 0) {
      side = 'bottom';
    } else if (side === 'bottom' && triggerRect.bottom + gap + bubbleRect.height > viewportHeight) {
      side = 'top';
    } else if (side === 'left' && triggerRect.left - gap - bubbleRect.width < 0) {
      side = 'right';
    } else if (side === 'right' && triggerRect.right + gap + bubbleRect.width > viewportWidth) {
      side = 'left';
    }

    let top: number;
    let left: number;
    switch (side) {
      case 'top':
        top = triggerRect.top - gap - bubbleRect.height;
        left = triggerRect.left + triggerRect.width / 2 - bubbleRect.width / 2;
        break;
      case 'bottom':
        top = triggerRect.bottom + gap;
        left = triggerRect.left + triggerRect.width / 2 - bubbleRect.width / 2;
        break;
      case 'left':
        left = triggerRect.left - gap - bubbleRect.width;
        top = triggerRect.top + triggerRect.height / 2 - bubbleRect.height / 2;
        break;
      default:
        left = triggerRect.right + gap;
        top = triggerRect.top + triggerRect.height / 2 - bubbleRect.height / 2;
        break;
    }

    const resolved: TooltipPlacement =
      side === 'top' || side === 'bottom' ? side : (side === 'left') !== rtl ? 'start' : 'end';
    if (bubble.getAttribute('data-placement') !== resolved) {
      bubble.setAttribute('data-placement', resolved);
    }

    left = Math.min(Math.max(left, 0), Math.max(0, viewportWidth - bubbleRect.width));
    top = Math.min(Math.max(top, 0), Math.max(0, viewportHeight - bubbleRect.height));
    bubble.style.top = `${top}px`;
    bubble.style.left = `${left}px`;
  }

  /** Writes `content` into both copies: plain text in the description, a composed <ds-text data-part="text"> in the bubble. */
  private renderLightContent(): void {
    if (this.descriptionEl && this.descriptionEl.textContent !== this.content) {
      this.descriptionEl.textContent = this.content;
    }
    if (!this.bubbleEl) {
      return;
    }
    // Typography is forward-only: the value, an override or the binding's own token, is always passed.
    const textOverrides: Partial<Record<TextOverridableBinding, TokenRef | undefined>> = {};
    for (const binding of Object.keys(TEXT_DEFAULT) as TooltipTextBinding[]) {
      textOverrides[binding] = this.overrides?.[binding] ?? TEXT_DEFAULT[binding];
    }
    litRender(
      html`<ds-text data-part="text" size="sm" element="span" .overrides=${textOverrides}>${this.content}</ds-text>`,
      this.bubbleEl,
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as Exclude<TooltipOverridableBinding, TooltipTextBinding>[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.content) {
      console.warn('<ds-tooltip> requires `content`.', this);
    }
    const trigger = this.triggerEl;
    // A custom element carries its own focusable control, so only a plain element's tabindex is readable here.
    if (trigger && !trigger.tagName.includes('-') && trigger.tabIndex < 0) {
      console.warn(
        '<ds-tooltip> child must be focusable, so hover and keyboard focus are equivalent (WCAG 1.4.13, 2.1.1).',
        this,
      );
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-tooltip': DsTooltip;
  }
}

// packages/rn/src/Tooltip.tsx
import * as React from 'react';
import { Animated, I18nManager, Platform, View, useWindowDimensions } from 'react-native';
import type { LayoutChangeEvent, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Text, TextForegroundContext } from './Text';
import type { TextOverridableBinding } from './Text';
import { toEasing, useReducedMotion, useTheme } from './theme';

export type TooltipPlacement = 'top' | 'bottom' | 'start' | 'end';
export type TooltipDelay = 'default' | 'none';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type TooltipOverridableBinding =
  | 'radius'
  | 'paddingBlock'
  | 'paddingInline'
  | 'offset'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'shadow'
  | 'layer'
  | 'enter'
  | 'exit';

/**
 * Typography belongs to the composed Text, so `fontFamily`, `fontSize` and `lineHeight` are
 * forward-only: the bubble never styles them itself, and the value — an override or this
 * default — is always passed to Text's `overrides` under the same name.
 */
type TooltipTextBinding = TooltipOverridableBinding & TextOverridableBinding;

const TEXT_DEFAULT: Record<TooltipTextBinding, TokenRef> = {
  fontFamily: 'font.family.body', // literal-ok: a TokenRef forwarded to Text, not a font stack
  fontSize: 'font.size.sm',
  lineHeight: 'font.lineHeight.normal',
};

export interface TooltipProps {
  /** The tooltip text. One short phrase or sentence; no markup, no links, no line breaks. */
  content: string;
  /** Exactly one focusable element (a Button, Link, Input). The tooltip attaches to it; a non-focusable child is an error. */
  children: React.ReactNode;
  /** Preferred side; flips when it would overflow the window (measured with `measureInWindow`). `start`/`end` are logical and mirror in right-to-left. */
  placement?: TooltipPlacement | undefined;
  /** `true`: supplementary, becomes the child's `accessibilityHint`. `false`: it IS the child's name and becomes `accessibilityLabel` instead. */
  describes?: boolean | undefined;
  /** Controlled visibility, for stories and tests only. Product code never sets it: a tooltip is hover, focus and long-press driven. */
  open?: boolean | undefined;
  /** Hover delay before showing (react-native-web): `default` waits `motion.duration.base` × 3; `none` shows instantly. */
  delay?: TooltipDelay | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<TooltipOverridableBinding, TokenRef | undefined>> | undefined;
}

type Size = { width: number; height: number };
type Rect = Size & { x: number; y: number };

/** Module-level "warm until" timestamp shared by every Tooltip: after one hides, a sibling hovered within `warmWindow` shows with no delay. */
let warmUntil = 0;

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(value, max));
}

/**
 * Positions the bubble from the trigger's window rect for `placement`, flipping to the
 * opposite side when the preferred one would overflow the window and shifting the cross
 * axis to stay inside it. Returns coordinates relative to the trigger, because the bubble
 * is laid out inside Tooltip's own root rather than a portal.
 */
function computeBubblePosition(
  placement: TooltipPlacement,
  trigger: Rect,
  bubble: Size,
  windowSize: Size,
  offset: number,
): { top: number; left: number } {
  if (placement === 'start' || placement === 'end') {
    let onLeft = I18nManager.isRTL ? placement === 'end' : placement === 'start';
    const spaceLeft = trigger.x;
    const spaceRight = windowSize.width - (trigger.x + trigger.width);
    if (onLeft && spaceLeft < bubble.width + offset && spaceRight >= bubble.width + offset) {
      onLeft = false;
    } else if (!onLeft && spaceRight < bubble.width + offset && spaceLeft >= bubble.width + offset) {
      onLeft = true;
    }
    const left = onLeft ? trigger.x - offset - bubble.width : trigger.x + trigger.width + offset;
    const top = clamp(trigger.y + trigger.height / 2 - bubble.height / 2, 0, windowSize.height - bubble.height);
    return { top: top - trigger.y, left: left - trigger.x };
  }

  let below = placement === 'bottom';
  const spaceAbove = trigger.y;
  const spaceBelow = windowSize.height - (trigger.y + trigger.height);
  if (below && spaceBelow < bubble.height + offset && spaceAbove > spaceBelow) {
    below = false;
  } else if (!below && spaceAbove < bubble.height + offset && spaceBelow > spaceAbove) {
    below = true;
  }
  const top = below ? trigger.y + trigger.height + offset : trigger.y - offset - bubble.height;
  const left = clamp(trigger.x + trigger.width / 2 - bubble.width / 2, 0, windowSize.width - bubble.width);
  return { top: top - trigger.y, left: left - trigger.x };
}

type Handler = ((event: unknown) => void) | undefined;

/**
 * Tooltip — the smallest overlay: a label that names an icon-only button or adds a
 * short clarification to a control, shown while attention is on it.
 *
 * When to use: attach it to an icon-only Button (`describes={false}`, so the tooltip is
 * the accessible name rather than a second announcement) or to a labelled control that
 * needs one more short phrase. Never put essential information, links or controls in it.
 *
 * There is no hover on touch, so native shows nothing by default: `content` is cloned
 * onto the single child as `accessibilityHint` (or `accessibilityLabel` when `describes`
 * is `false`), so the information is never hover-only. A long-press shows the inverted
 * bubble above the child until the press ends, as a sighted-user aid. On
 * react-native-web hover and focus behave as on web: focus shows it immediately, hover
 * waits `hoverDelay` (none when `delay` is `none` or a sibling hid within `warmWindow`),
 * leaving the trigger hides it after `pointerGrace` unless the pointer reaches the
 * bubble, and Escape hides it without moving focus. The bubble is hidden from
 * accessibility — the hint or label on the trigger already carries the text.
 *
 * An Escape dismissal outlives a re-hover: the tooltip stays hidden until the trigger
 * has lost both hover and focus (or, controlled, until `open` next changes).
 *
 * The bubble is not portaled: it is absolutely positioned inside Tooltip's root on
 * `layer.toast`, placed from the trigger's `measureInWindow` rect and flipped on
 * overflow. An ancestor that clips (`overflow: 'hidden'`) or a sibling stacking context
 * above the root can still cover it — the acknowledged native limit.
 *
 * Tooltip exposes no `ref`: it adds no root a caller needs; a caller that wants the
 * trigger refs its own child. Inside a Toolbar it adds no focus stop and no role.
 */
export function Tooltip({
  content,
  children,
  placement = 'top',
  describes = true,
  open: openProp,
  delay = 'default',
  overrides,
}: TooltipProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const windowSize = useWindowDimensions();

  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusSm;
  const paddingBlock = overrides?.paddingBlock ? (resolveToken(t, overrides.paddingBlock) as number) : t.space1;
  const paddingInline = overrides?.paddingInline ? (resolveToken(t, overrides.paddingInline) as number) : t.space2;
  const offset = overrides?.offset ? (resolveToken(t, overrides.offset) as number) : t.space1;
  // An override replaces the base token; the × 3 of the computed rule stays either way.
  const maxWidthBase = overrides?.maxWidth ? (resolveToken(t, overrides.maxWidth) as number) : t.space20;
  const maxWidth = maxWidthBase * 3; // literal-ok: schema computed times 3
  const shadow = overrides?.shadow ? (resolveToken(t, overrides.shadow) as typeof t.shadowRaised) : t.shadowRaised;
  const layer = overrides?.layer ? (resolveToken(t, overrides.layer) as number) : t.layerToast;
  const enterDuration = overrides?.enter ? (resolveToken(t, overrides.enter) as number) : t.motionDurationFast;
  const exitDuration = overrides?.exit ? (resolveToken(t, overrides.exit) as number) : t.motionDurationFast;

  // Constants, read through their token expressions.
  const hoverDelay = t.motionDurationBase * 3; // literal-ok: schema constant hoverDelay multiply 3
  const warmWindow = t.motionDurationBase;
  const pointerGrace = t.motionDurationFast;

  const controlled = openProp !== undefined;

  /** The uncontrolled visibility; `open` replaces it when the caller provides one. */
  const [shown, setShown] = React.useState(false);
  /** Escape hides the tooltip until the trigger loses hover and focus, or `open` next changes. */
  const [dismissed, setDismissed] = React.useState(false);
  React.useEffect(() => {
    setDismissed(false);
  }, [openProp]);

  const visible = !dismissed && (openProp ?? shown);

  // Pointer, focus and press presence, tracked in refs so the grace timer reads the
  // current state rather than the state it closed over.
  const hoveringTrigger = React.useRef(false);
  const hoveringBubble = React.useRef(false);
  const focused = React.useRef(false);
  const pressing = React.useRef(false);

  const showTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  const hideTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  const clearShow = (): void => {
    if (showTimer.current !== null) {
      clearTimeout(showTimer.current);
      showTimer.current = null;
    }
  };
  const clearHide = (): void => {
    if (hideTimer.current !== null) {
      clearTimeout(hideTimer.current);
      hideTimer.current = null;
    }
  };
  React.useEffect(
    () => () => {
      clearShow();
      clearHide();
    },
    [],
  );

  // Leaving a visible tooltip opens the shared warm window for its siblings.
  const wasVisible = React.useRef(visible);
  React.useEffect(() => {
    if (wasVisible.current && !visible) {
      warmUntil = Date.now() + warmWindow;
    }
    wasVisible.current = visible;
  }, [visible, warmWindow]);

  /**
   * Waits one `pointerGrace` so the pointer can cross the `offset` gap onto the bubble,
   * then hides if nothing still holds the tooltip open. Losing hover and focus also
   * clears an Escape dismissal, so the next hover shows the tooltip again.
   */
  const scheduleHide = (): void => {
    if (controlled) {
      return;
    }
    clearShow();
    if (hideTimer.current !== null) {
      return;
    }
    hideTimer.current = setTimeout(() => {
      hideTimer.current = null;
      if (hoveringTrigger.current || hoveringBubble.current || focused.current || pressing.current) {
        return;
      }
      setShown(false);
      setDismissed(false);
    }, pointerGrace);
  };

  const handleHoverIn = (): void => {
    hoveringTrigger.current = true;
    if (controlled) {
      return;
    }
    clearHide();
    clearShow();
    // Warm skips the delay for `default` tooltips too; `none` is always instant.
    if (delay === 'none' || shown || Date.now() < warmUntil) {
      setShown(true);
      return;
    }
    showTimer.current = setTimeout(() => {
      showTimer.current = null;
      setShown(true);
    }, hoverDelay);
  };

  const handleHoverOut = (): void => {
    hoveringTrigger.current = false;
    scheduleHide();
  };

  // Focus of any kind shows it immediately, so the tooltip is never hover-only.
  const handleFocus = (): void => {
    focused.current = true;
    if (controlled) {
      return;
    }
    clearHide();
    clearShow();
    setShown(true);
  };

  const handleBlur = (): void => {
    focused.current = false;
    scheduleHide();
  };

  const handleBubbleEnter = (): void => {
    hoveringBubble.current = true;
    if (controlled) {
      return;
    }
    clearHide();
  };

  const handleBubbleLeave = (): void => {
    hoveringBubble.current = false;
    scheduleHide();
  };

  const handleLongPress = (): void => {
    pressing.current = true;
    if (controlled) {
      return;
    }
    clearHide();
    clearShow();
    setShown(true);
  };

  // Releasing hides at once: `pointerGrace` covers a pointer crossing the gap, not a
  // finger lifting. Hover or focus still holding the tooltip open wins.
  const handlePressOut = (): void => {
    pressing.current = false;
    if (controlled || hoveringTrigger.current || hoveringBubble.current || focused.current) {
      return;
    }
    clearShow();
    clearHide();
    setShown(false);
    setDismissed(false);
  };

  const dismiss = React.useCallback(() => {
    clearShow();
    setDismissed(true);
  }, []);

  // Escape hides without moving focus, also when the tooltip was opened by hover alone.
  // Only react-native-web has a keyboard event to listen for; native hardware keyboards
  // have no Escape binding for a non-modal view. The listener is attached only while the
  // bubble is visible, in the capture phase, and consumes the event with both
  // stopPropagation and preventDefault — a native <dialog> closes on an Escape that is
  // not default-prevented, so inside a Dialog the first Escape hides the tooltip and the
  // second closes the Dialog.
  React.useEffect(() => {
    if (Platform.OS !== 'web' || !visible) {
      return undefined;
    }
    type KeyEvent = { key?: string | undefined; stopPropagation: () => void; preventDefault: () => void };
    type KeyListener = (event: KeyEvent) => void;
    type KeyTarget = {
      addEventListener: (type: 'keydown', listener: KeyListener, capture: boolean) => void;
      removeEventListener: (type: 'keydown', listener: KeyListener, capture: boolean) => void;
    };
    const globalWindow = (globalThis as { window?: KeyTarget | undefined }).window;
    if (globalWindow === undefined) {
      return undefined;
    }
    const handleKeyDown: KeyListener = (event) => {
      if (event.key === 'Escape') {
        event.stopPropagation();
        event.preventDefault();
        dismiss();
      }
    };
    globalWindow.addEventListener('keydown', handleKeyDown, true);
    return () => globalWindow.removeEventListener('keydown', handleKeyDown, true);
  }, [visible, dismiss]);

  const isSingleElement = React.isValidElement(children) && React.Children.count(children) === 1;
  React.useEffect(() => {
    if (__DEV__ && !isSingleElement) {
      console.warn('Tooltip: `children` must be exactly one focusable element (a Button, Link or Input).');
    }
  }, [isSingleElement]);

  const child = isSingleElement ? (children as React.ReactElement<Record<string, unknown>>) : null;
  const childProps = child?.props ?? {};
  const chain =
    (name: string, own: () => void) =>
    (event: unknown): void => {
      (childProps[name] as Handler)?.(event);
      own();
    };

  const trigger =
    child !== null
      ? React.cloneElement(child, {
          ...(describes ? { accessibilityHint: content } : { accessibilityLabel: content }),
          onLongPress: chain('onLongPress', handleLongPress),
          onPressOut: chain('onPressOut', handlePressOut),
          // Hover and focus exist only under react-native-web; on native the bubble is
          // long-press only.
          ...(Platform.OS === 'web'
            ? {
                onHoverIn: chain('onHoverIn', handleHoverIn),
                onHoverOut: chain('onHoverOut', handleHoverOut),
                onFocus: chain('onFocus', handleFocus),
                onBlur: chain('onBlur', handleBlur),
              }
            : {}),
        })
      : children;

  // Mounted stays true through the exit fade.
  const [mounted, setMounted] = React.useState(visible);
  const progress = React.useRef(new Animated.Value(0)).current;
  React.useEffect(() => {
    if (visible) {
      setMounted(true);
    }
  }, [visible]);

  React.useEffect(() => {
    if (!mounted) {
      return undefined;
    }
    const easing = toEasing(t.motionEasingStandard);
    if (visible) {
      if (reducedMotion) {
        progress.setValue(1);
        return undefined;
      }
      // react-native-web has no native animated module.
      const animation = Animated.timing(progress, { toValue: 1, duration: enterDuration, easing, useNativeDriver: false });
      animation.start();
      return () => animation.stop();
    }
    if (reducedMotion) {
      progress.setValue(0);
      setMounted(false);
      return undefined;
    }
    const animation = Animated.timing(progress, { toValue: 0, duration: exitDuration, easing, useNativeDriver: false });
    animation.start(({ finished }) => {
      if (finished) {
        setMounted(false);
      }
    });
    return () => animation.stop();
  }, [visible, mounted, reducedMotion, enterDuration, exitDuration, progress, t.motionEasingStandard]);

  const triggerRef = React.useRef<ViewInstance>(null);
  const [triggerRect, setTriggerRect] = React.useState<Rect | null>(null);
  const [bubbleSize, setBubbleSize] = React.useState<Size | null>(null);

  const measureTrigger = React.useCallback(() => {
    triggerRef.current?.measureInWindow((x, y, width, height) => {
      setTriggerRect((prev) =>
        prev !== null && prev.x === x && prev.y === y && prev.width === width && prev.height === height
          ? prev
          : { x, y, width, height },
      );
    });
  }, []);

  React.useEffect(() => {
    if (mounted) {
      measureTrigger();
    }
  }, [mounted, measureTrigger, windowSize.width, windowSize.height]);

  const handleBubbleLayout = (event: LayoutChangeEvent): void => {
    const { width, height } = event.nativeEvent.layout;
    setBubbleSize((prev) => (prev !== null && prev.width === width && prev.height === height ? prev : { width, height }));
  };

  const position =
    triggerRect !== null
      ? computeBubblePosition(placement, triggerRect, bubbleSize ?? { width: 0, height: 0 }, windowSize, offset)
      : null;

  const bubbleStyle: Animated.WithAnimatedValue<ViewStyle> = {
    position: 'absolute',
    top: position?.top ?? 0,
    left: position?.left ?? 0,
    maxWidth,
    paddingVertical: paddingBlock,
    paddingHorizontal: paddingInline,
    borderRadius: radius,
    backgroundColor: t.colorInverseSurface,
    zIndex: layer,
    // Stays transparent until it has been measured and placed.
    opacity: position !== null && bubbleSize !== null ? progress : 0,
    ...shadow,
  };

  // Typography is forward-only: the value, an override or the binding's own token, is
  // always passed to the composed Text rather than drawn on the bubble.
  const textOverrides = React.useMemo<Partial<Record<TextOverridableBinding, TokenRef | undefined>>>(() => {
    const next: Partial<Record<TextOverridableBinding, TokenRef | undefined>> = {};
    for (const binding of Object.keys(TEXT_DEFAULT) as TooltipTextBinding[]) {
      next[binding] = overrides?.[binding] ?? TEXT_DEFAULT[binding];
    }
    return next;
  }, [overrides]);

  return (
    <View testID="Tooltip" style={{ position: 'relative', alignSelf: 'flex-start', ...(mounted ? { zIndex: layer } : {}) }}>
      {/* `collapsable={false}` keeps this View in the native tree on Android so measureInWindow stays reliable. */}
      <View ref={triggerRef} collapsable={false}>
        {trigger}
      </View>
      {mounted ? (
        <Animated.View
          testID="Tooltip.popup"
          onLayout={handleBubbleLayout}
          // Hoverable under react-native-web (WCAG 1.4.13); inert on touch.
          pointerEvents={Platform.OS === 'web' ? 'auto' : 'none'}
          onPointerEnter={handleBubbleEnter}
          onPointerLeave={handleBubbleLeave}
          accessibilityElementsHidden
          importantForAccessibility="no-hide-descendants"
          aria-hidden
          style={bubbleStyle}
        >
          {/* surface and text are locked: the bubble provides its foreground to the composed Text (whose color is locked too) instead of overriding it. */}
          <TextForegroundContext.Provider value={t.colorInverseForeground}>
            <Text size="sm" overrides={textOverrides}>
              {content}
            </Text>
          </TextForegroundContext.Provider>
        </Animated.View>
      ) : null}
    </View>
  );
}
