// packages/rn/demo/SignIn.tsx
import * as React from 'react';
import { View } from 'react-native';
import type { ViewStyle } from 'react-native';
import { Button, Form, Heading, Input, Stack, Text, useTheme } from '../src';
import type { FormValues } from '../src';

export interface SignInProps {
  /** Receives `{ email, password }` once both fields pass validation. */
  onSubmit?: (values: FormValues) => void;
  /** Activated by the low-emphasis "Forgot password?" action. */
  onForgotPassword?: () => void;
  /** Disables the form while a sign-in request is in flight. */
  submitting?: boolean;
}

/**
 * Sign-in screen composed entirely from Design Schema React Native components.
 *
 * The outline is one `level: 1` Heading. The Form is labelled so it is a named
 * region, both Inputs are required, the primary Button submits, and the ghost
 * Button is the only other action so nothing competes with sign-in.
 */
export function SignIn({ onSubmit, onForgotPassword, submitting = false }: SignInProps): React.JSX.Element {
  const { tokens } = useTheme();

  const screenStyle: ViewStyle = {
    flex: 1,
    backgroundColor: tokens.colorBackground,
    paddingHorizontal: tokens.spaceLg,
    paddingVertical: tokens.space8,
  };

  return (
    <View style={screenStyle}>
      <Stack gap="6">
        <Stack gap="1">
          <Heading level={1} size="2xl">
            Sign in
          </Heading>
          <Text tone="muted">Use the email you signed up with.</Text>
        </Stack>
        <Form name="sign-in" label="Sign in" disabled={submitting} onSubmit={onSubmit}>
          <Input label="Email address" name="email" type="email" required placeholder="name@example.com" />
          <Input label="Password" name="password" type="password" required />
          <Stack gap="2" align="start">
            <Button label="Sign in" type="submit" loading={submitting} />
            <Button label="Forgot password?" variant="ghost" onPress={onForgotPassword} />
          </Stack>
        </Form>
      </Stack>
    </View>
  );
}

// packages/lit/demo/sign-in.ts
import { html, type TemplateResult } from 'lit';
import '../src/index.js';

/**
 * Sign-in screen composed from the Calm & precise Lit elements.
 *
 * Expects the token custom properties to be loaded once at the app root
 * (`import '@design-schema/tokens/calm-precise/css'`) and, optionally,
 * `data-mode="dark"` on `<html>`.
 */
export function renderSignIn(): TemplateResult {
  return html`
    <ds-stack gap="6" align="stretch">
      <ds-stack gap="1">
        <ds-heading level="1">Sign in</ds-heading>
        <ds-text tone="muted">Use the email you signed up with.</ds-text>
      </ds-stack>

      <ds-form name="sign-in" label="Sign in">
        <ds-input
          label="Email address"
          name="email"
          type="email"
          autocomplete="email"
          required
        ></ds-input>
        <ds-input
          label="Password"
          name="password"
          type="password"
          autocomplete="current-password"
          required
        ></ds-input>
        <ds-stack direction="horizontal" gap="2" align="center" justify="between" wrap>
          <ds-button type="submit" label="Sign in"></ds-button>
          <ds-button variant="ghost" label="Forgot password?"></ds-button>
        </ds-stack>
      </ds-form>
    </ds-stack>
  `;
}
