// packages/react/demo/SignIn.tsx
import { Button, Form, Heading, Input, Stack, Text, type FormErrors, type FormValues } from '../src/index';

export interface SignInProps {
  /** Called with `{ email, password }` when the form passes validation. Defaults to logging the values. */
  onSubmit?: (values: FormValues) => void;
  /** Called with the errors keyed by field name when submission is blocked. */
  onInvalid?: (errors: FormErrors) => void;
  /** Called when "Forgot password?" is activated. */
  onForgotPassword?: () => void;
}

/**
 * Sign-in screen composed from the Calm & precise React components:
 * Stack → Heading (level 1) + Text + Form → two Inputs + actions.
 */
export function SignIn({ onSubmit, onInvalid, onForgotPassword }: SignInProps) {
  const handleSubmit = (values: FormValues) => {
    if (onSubmit) {
      onSubmit(values);
    } else {
      console.log('Sign in', values);
    }
  };

  return (
    <Stack gap="6" align="stretch" element="section" aria-labelledby="sign-in-title">
      <Stack gap="1">
        <Heading level="1" id="sign-in-title">
          Sign in
        </Heading>
        <Text tone="muted">Use the email you signed up with.</Text>
      </Stack>

      <Form name="sign-in" label="Sign in" validate="submit" onSubmit={handleSubmit} onInvalid={onInvalid}>
        <Stack gap="4">
          <Input label="Email address" name="email" type="email" required autocomplete="email" />
          <Input label="Password" name="password" type="password" required autocomplete="current-password" />
          <Stack direction="horizontal" gap="2" align="center" justify="between" wrap>
            <Button label="Sign in" type="submit" variant="primary" />
            <Button label="Forgot password?" variant="ghost" onClick={onForgotPassword} />
          </Stack>
        </Stack>
      </Form>
    </Stack>
  );
}

// packages/lit/demo/sign-in.ts
import { html, type TemplateResult } from 'lit';
import '../src/index.js';

/**
 * Sign-in screen composed from the Calm & precise Lit elements.
 *
 * Expects the token custom properties to be loaded once at the app root
 * (`import '@design-schema/tokens/calm-precise/css'`) and, optionally,
 * `data-mode="dark"` on `<html>`.
 */
export function renderSignIn(): TemplateResult {
  return html`
    <ds-stack gap="6" align="stretch">
      <ds-stack gap="1">
        <ds-heading level="1">Sign in</ds-heading>
        <ds-text tone="muted">Use the email you signed up with.</ds-text>
      </ds-stack>

      <ds-form name="sign-in" label="Sign in">
        <ds-input
          label="Email address"
          name="email"
          type="email"
          autocomplete="email"
          required
        ></ds-input>
        <ds-input
          label="Password"
          name="password"
          type="password"
          autocomplete="current-password"
          required
        ></ds-input>
        <ds-stack direction="horizontal" gap="2" align="center" justify="between" wrap>
          <ds-button type="submit" label="Sign in"></ds-button>
          <ds-button variant="ghost" label="Forgot password?"></ds-button>
        </ds-stack>
      </ds-form>
    </ds-stack>
  `;
}
