// packages/react/src/Accordion.tsx
import {
  useEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import {
  Disclosure,
  type DisclosureOverridableBinding,
  type DisclosureToggleReason,
} from './Disclosure';
import { Divider, type DividerOverridableBinding } from './Divider';
import './Accordion.css';

/** One section. `content` is the panel body. */
export type AccordionItem = { id: string; summary: string; content: ReactNode; disabled?: boolean | undefined };

/** Accepts the schema's string values and their numeric equivalents. */
export type AccordionHeadingLevel = '2' | '3' | '4' | '5' | '6' | 2 | 3 | 4 | 5 | 6;

/**
 * Why a section's open state changed: `trigger` (activated by pointer), `keyboard` (toggled from the keyboard, as
 * Disclosure reports it), `exclusive` (another section opened and closed this one), `controlled` (the `value` prop
 * changed to a set the accordion did not itself just emit).
 */
export type AccordionOpenChangeReason = 'trigger' | 'keyboard' | 'exclusive' | 'controlled';

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type AccordionOverridableBinding =
  | 'divider'
  | 'dividerWidth'
  | 'itemGap'
  | 'triggerPaddingBlock'
  | 'fontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight';

/* Only declared when the bundler defines it; never assumed. */
declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

/** An empty array or an empty string means nothing is open. */
function toIdArray(value: string | string[] | undefined): string[] | undefined {
  if (value === undefined) return undefined;
  if (Array.isArray(value)) return value;
  return value === '' ? [] : [value];
}

/** Under `exclusive` only the first id opens; the rest are reported by a development warning. */
function limitExclusive(ids: string[], exclusive: boolean): string[] {
  return exclusive && ids.length > 1 ? ids.slice(0, 1) : ids;
}

function sameSet(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((id) => b.includes(id));
}

export interface AccordionProps
  extends Omit<ComponentPropsWithoutRef<'div'>, 'children' | 'onChange' | 'defaultValue' | 'className' | 'style'> {
  /**
   * The sections in order. `content` is the panel body; on Lit it is dropped from the item type and the body is a
   * light-DOM child slotted by the item id (`<div slot="faq-1">`).
   */
  items: AccordionItem[];
  /** Heading level for every trigger, so sections appear in the page outline. */
  headingLevel?: AccordionHeadingLevel | undefined;
  /**
   * Opening one section closes the others. Off by default: users usually want to compare, and forced-closing is a
   * common frustration. Turning it on while several sections are open trims the open set to the first open id
   * without firing any event (the same as several ids in `value`/`defaultValue`).
   */
  exclusive?: boolean | undefined;
  /**
   * Controlled open ids. A bare `string` is accepted as shorthand for a one-id array; an empty array or an empty
   * string means nothing is open. Events always report an array, with zero or one entry when `exclusive`.
   */
  value?: string | string[] | undefined;
  /** Initially open ids; the same shapes as `value`. */
  defaultValue?: string | string[] | undefined;
  /** A hairline between items. */
  divided?: boolean | undefined;
  /** Passed to every Disclosure; required when panels contain form fields. */
  keepMounted?: boolean | undefined;
  /**
   * Per-instance style overrides. `itemGap` sets the root hook; the trigger bindings are forwarded to each composed
   * Disclosure's `overrides`, `divider`/`dividerWidth` to each Divider's `color`/`thickness`.
   */
  overrides?: Partial<Record<AccordionOverridableBinding, TokenRef | undefined>> | undefined;
  /**
   * Fired when the set of open sections changes, with the open ids — always an array, even under `exclusive`, where
   * it carries zero or one entry.
   */
  onChange?: ((openIds: string[]) => void) | undefined;
  /**
   * Fired per section as it opens or closes. The per-item trigger for analytics, lazy loading of a panel's content,
   * or scrolling the opened section into view; `onChange` remains the set-level event for state.
   */
  onOpenChange?: ((id: string, open: boolean, reason: AccordionOpenChangeReason) => void) | undefined;
}

/**
 * Accordion — Design Schema, category: container.
 *
 * When to use:
 * Use an Accordion for a series of independent sections a user scans by heading and opens selectively: an FAQ, a
 * settings page grouped by topic, a multi-part form where each part is optional. Set `headingLevel` to fit the page
 * outline. Leave `exclusive` off unless the panels are heavy or mutually exclusive by nature (a wizard-like "choose
 * one plan to see details").
 *
 * Each item is a Disclosure (the `item` part is its root, a direct child of this `<div>`); Dividers sit between them.
 */
export function Accordion({
  ref,
  items,
  headingLevel = '3',
  exclusive = false,
  value,
  defaultValue,
  divided = true,
  keepMounted = false,
  overrides,
  onChange,
  onOpenChange,
  onKeyDown,
  ...rest
}: AccordionProps & { ref?: Ref<HTMLDivElement> | undefined }): ReactElement {
  const triggerRefs = useRef(new Map<string, HTMLButtonElement>());
  const setTriggerRef = (id: string) => (el: HTMLButtonElement | null) => {
    if (el) triggerRefs.current.set(id, el);
    else triggerRefs.current.delete(id);
  };

  const isControlled = value !== undefined;
  const [internalOpenIds, setInternalOpenIds] = useState<string[]>(() =>
    limitExclusive(toIdArray(defaultValue) ?? [], exclusive),
  );
  // Turning `exclusive` on while several sections are open trims the set to the first open id, firing nothing.
  if (!isControlled && exclusive && internalOpenIds.length > 1) {
    setInternalOpenIds(internalOpenIds.slice(0, 1));
  }
  const openIds = limitExclusive(isControlled ? (toIdArray(value) ?? []) : internalOpenIds, exclusive);
  const valueKey = isControlled ? JSON.stringify(toIdArray(value) ?? []) : null;

  // Development warning: several ids under `exclusive` open only the first. Warned once per distinct input.
  const requestedIds = toIdArray(isControlled ? value : defaultValue) ?? [];
  const warnedRef = useRef<string | null>(null);
  useEffect(() => {
    if (!isDev || !exclusive || requestedIds.length <= 1) return;
    const key = requestedIds.join(' ');
    if (warnedRef.current === key) return;
    warnedRef.current = key;
    const source = isControlled ? 'value' : 'defaultValue';
    console.warn(
      `Accordion: \`exclusive\` opens one section, but \`${source}\` has ${requestedIds.length} ids. Opening "${requestedIds[0]}"; ignoring ${requestedIds.slice(1).join(', ')}.`,
    );
  });

  // `controlled`: a `value` change to a set the accordion did not itself just emit reports each section that changed,
  // in item order. Only a change of the `value` prop reports; an `exclusive` trim of the same value changes the set
  // silently. The just-emitted set is compared with the next `value` change only, then cleared.
  const previousRef = useRef<{ valueKey: string | null; openIds: string[] }>({ valueKey, openIds });
  const lastEmittedRef = useRef<string[] | null>(null);
  useEffect(() => {
    const previous = previousRef.current;
    previousRef.current = { valueKey, openIds };
    if (!isControlled) {
      lastEmittedRef.current = null;
      return;
    }
    if (previous.valueKey === valueKey) return;
    const emitted = lastEmittedRef.current;
    lastEmittedRef.current = null;
    if (emitted !== null && sameSet(emitted, openIds)) return;
    for (const item of items) {
      const was = previous.openIds.includes(item.id);
      const is = openIds.includes(item.id);
      if (was !== is) onOpenChange?.(item.id, is, 'controlled');
    }
  });

  const handleToggle = (id: string, open: boolean, toggleReason: DisclosureToggleReason) => {
    // Disclosure reports `controlled` when the accordion itself changed its `open`; that is not a user toggle.
    if (toggleReason === 'controlled') return;
    const previous = openIds;
    const next = open
      ? exclusive
        ? [id]
        : previous.includes(id)
          ? previous
          : [...previous, id]
      : previous.filter((openId) => openId !== id);
    const reason: AccordionOpenChangeReason = toggleReason === 'keyboard' ? 'keyboard' : 'trigger';

    if (isControlled) lastEmittedRef.current = next;
    else setInternalOpenIds(next);

    onChange?.(next);
    onOpenChange?.(id, open, reason);
    if (open && exclusive) {
      // One report per section `exclusive` closed, in item order.
      for (const item of items) {
        if (item.id !== id && previous.includes(item.id)) onOpenChange?.(item.id, false, 'exclusive');
      }
    }
  };

  // ArrowUp/Down wrap, Home/End jump; disabled sections are skipped. Every trigger stays an ordinary tab stop.
  const handleKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    const { key } = event;
    if (key !== 'ArrowDown' && key !== 'ArrowUp' && key !== 'Home' && key !== 'End') return;
    const current = items.findIndex((item) => triggerRefs.current.get(item.id) === event.target);
    if (current === -1) return;

    const count = items.length;
    const step = (from: number, delta: number): number => {
      let index = from;
      for (let i = 0; i < count; i += 1) {
        index = (index + delta + count) % count;
        if (!items[index]!.disabled) return index;
      }
      return -1;
    };

    let next = -1;
    if (key === 'ArrowDown') next = step(current, 1);
    else if (key === 'ArrowUp') next = step(current, -1);
    else if (key === 'Home') next = step(count - 1, 1);
    else next = step(0, -1);

    if (next === -1) return;
    event.preventDefault();
    triggerRefs.current.get(items[next]!.id)?.focus();
  };

  // Every forward carries the resolved token — the consumer's override, else the Accordion default — even when it
  // equals the child's own default, so the accordion's value always wins over the child's.
  const disclosureOverrides: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>> = {
    triggerPaddingBlock: overrides?.triggerPaddingBlock ?? 'space.md',
    triggerFontFamily: overrides?.fontFamily ?? 'font.family.body',
    triggerFontSize: overrides?.triggerFontSize ?? 'font.size.md',
    triggerFontWeight: overrides?.triggerFontWeight ?? 'font.weight.medium',
  };

  const dividerOverrides: Partial<Record<DividerOverridableBinding, TokenRef | undefined>> = {
    color: overrides?.divider ?? 'color.border',
    thickness: overrides?.dividerWidth ?? 'border.width.thin',
  };

  const rootStyle: CSSProperties | undefined = overrides?.itemGap
    ? ({ '--ds-accordion-item-gap': cssVar(overrides.itemGap) } as CSSProperties)
    : undefined;

  const children: ReactNode[] = [];
  items.forEach((item, index) => {
    if (divided && index > 0) {
      children.push(<Divider key={`divider-${item.id}`} overrides={dividerOverrides} />);
    }
    children.push(
      <Disclosure
        key={item.id}
        ref={setTriggerRef(item.id)}
        summary={item.summary}
        headingLevel={headingLevel}
        open={openIds.includes(item.id)}
        disabled={item.disabled}
        keepMounted={keepMounted}
        overrides={disclosureOverrides}
        onToggle={(open, reason) => handleToggle(item.id, open, reason)}
      >
        {item.content}
      </Disclosure>,
    );
  });

  return (
    <div
      {...rest}
      ref={ref}
      data-ds="Accordion"
      data-part="list"
      className="ds-accordion"
      style={rootStyle}
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
  );
}

// packages/lit/src/Accordion.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Disclosure.js';
import './Divider.js';
import type { DisclosureHeadingLevel, DisclosureToggleDetail, DsDisclosure } from './Disclosure.js';

export type AccordionHeadingLevel = DisclosureHeadingLevel;

/**
 * One section. On Lit the schema's `content` is dropped: the panel body is a
 * light-DOM child slotted by the item id (`<div slot="faq-1">…</div>`).
 */
export interface AccordionItem {
  id: string;
  summary: string;
  disabled?: boolean | undefined;
}

/** Why a section's open state changed. */
export type AccordionOpenChangeReason = 'trigger' | 'keyboard' | 'exclusive' | 'controlled';

/** Detail carried by the `change` CustomEvent: every open id, zero or one entry under `exclusive`. */
export interface AccordionChangeDetail {
  openIds: string[];
}

/** Detail carried by the `open-change` CustomEvent, fired once per section as it opens or closes. */
export interface AccordionOpenChangeDetail {
  id: string;
  open: boolean;
  reason: AccordionOpenChangeReason;
}

/** Overridable style hooks; see the `overrides` property. `minTarget`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type AccordionOverridableBinding =
  | 'divider'
  | 'dividerWidth'
  | 'itemGap'
  | 'triggerPaddingBlock'
  | 'fontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight';

const HOOKS: Record<AccordionOverridableBinding, string> = {
  divider: '--ds-accordion-divider',
  dividerWidth: '--ds-accordion-divider-width',
  itemGap: '--ds-accordion-item-gap',
  triggerPaddingBlock: '--ds-accordion-trigger-padding-block',
  fontFamily: '--ds-accordion-font-family',
  triggerFontSize: '--ds-accordion-trigger-font-size',
  triggerFontWeight: '--ds-accordion-trigger-font-weight',
};

const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute: (value: string | null): boolean => value === null,
  toAttribute: (value: boolean): string | null => (value ? null : ''),
};

function isDisclosure(el: Element): el is DsDisclosure {
  return el.localName === 'ds-disclosure';
}

function sameMembers(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((id) => b.includes(id));
}

/**
 * `<ds-accordion>` — Accordion (category: container, APG pattern: accordion).
 *
 * A list of `<ds-disclosure>` sections that know about each other: a shared
 * `heading-level` and `keep-mounted`, a roomier trigger padding, arrow-key
 * navigation between triggers, and (with `exclusive`) the rule that opening
 * one closes the rest. Sections are light-DOM `<ds-disclosure>` children, so
 * their content stays in the document, or are generated from the `items`
 * property, in which case each item's panel body is the light-DOM child whose
 * `slot` is the item's id. Every section is identified by its `id`.
 *
 * The shadow root assigns slots manually, so each section sits in its own slot
 * and a `<ds-divider>` can be rendered between items without touching the
 * light DOM. The accordion always sets each disclosure's `open`, so `value` /
 * `defaultValue` and the `change` / `open-change` events stay authoritative.
 * Every trigger remains a tab stop; arrow keys are a convenience on top of Tab.
 *
 * ## When to use
 *
 * Use an Accordion for a series of independent sections a user scans by
 * heading and opens selectively: an FAQ, a settings page grouped by topic, a
 * multi-part form where each part is optional. Set `headingLevel` to fit the
 * page outline. Leave `exclusive` off unless the panels are heavy or mutually
 * exclusive by nature.
 *
 * ## When not to use
 *
 * Do not use an Accordion for content most users need — show it. Do not use it
 * as navigation or as tabs. Do not nest accordions. Do not use one for a single
 * section; that is a `<ds-disclosure>`.
 *
 * @fires change - The set of open sections changed, with `{ openIds }` in `detail`.
 * @fires open-change - A section opened or closed, with `{ id, open, reason }` in `detail`.
 * @slot - Light-DOM `<ds-disclosure>` children, used when `items` is not set.
 * @slot [item.id] - With `items`, the panel body of the item with that id.
 */
@customElement('ds-accordion')
export class DsAccordion extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    slotAssignment: 'manual',
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-accordion-divider: var(--color-border);
      --ds-accordion-divider-width: var(--border-width-thin);
      --ds-accordion-item-gap: var(--layout-gap-none);
      --ds-accordion-trigger-padding-block: var(--space-md);
      --ds-accordion-font-family: var(--font-family-body);
      --ds-accordion-trigger-font-size: var(--font-size-md);
      --ds-accordion-trigger-font-weight: var(--font-weight-medium);
      /* Locked: no overrides entry, but the hook stays themeable from page CSS. Disclosure applies them. */
      --ds-accordion-min-target: var(--size-target-min);
      --ds-accordion-focus-ring: var(--color-border-focus);
      --ds-accordion-focus-ring-width: var(--border-width-focus);
    }

    :host([hidden]) {
      display: none;
    }

    /* itemGap: items touch; the divider separates them */
    [data-part='list'] {
      display: flex;
      flex-direction: column;
      gap: var(--ds-accordion-item-gap);
    }

    /* triggerPaddingBlock / fontFamily / triggerFontSize / triggerFontWeight (and the locked hooks) reach each Disclosure through its documented hooks */
    [data-part='list'] > ds-disclosure,
    ::slotted(ds-disclosure) {
      --ds-disclosure-trigger-padding-block: var(--ds-accordion-trigger-padding-block);
      --ds-disclosure-trigger-font-family: var(--ds-accordion-font-family);
      --ds-disclosure-trigger-font-size: var(--ds-accordion-trigger-font-size);
      --ds-disclosure-trigger-font-weight: var(--ds-accordion-trigger-font-weight);
      /* minTarget / focusRing / focusRingWidth (locked): the Disclosure trigger draws them from its own hooks */
      --ds-disclosure-min-target: var(--ds-accordion-min-target);
      --ds-disclosure-focus-ring: var(--ds-accordion-focus-ring);
      --ds-disclosure-focus-ring-width: var(--ds-accordion-focus-ring-width);
    }

    /* divider / dividerWidth reach each Divider through its documented hooks */
    [data-part='list'] > ds-divider {
      --ds-divider-color: var(--ds-accordion-divider);
      --ds-divider-thickness: var(--ds-accordion-divider-width);
    }
  `;

  /** The sections in order. When set, the accordion renders the `<ds-disclosure>` elements itself. */
  @property({ attribute: false }) accessor items: AccordionItem[] | undefined;

  /** Heading level for every trigger, so sections appear in the page outline. */
  @property({ type: String, reflect: true, attribute: 'heading-level' }) accessor headingLevel: AccordionHeadingLevel = '3';

  /** Opening one section closes the others. */
  @property({ type: Boolean, reflect: true }) accessor exclusive = false;

  /** Controlled open ids. A bare string is a one-id array; `[]` or `''` means nothing is open. Omit for uncontrolled. */
  @property({ attribute: false }) accessor value: string | string[] | undefined;

  /** Initially open ids; the same shapes as `value`. */
  @property({ attribute: false }) accessor defaultValue: string | string[] | undefined;

  /** A hairline between items. Exposed as the negated `no-divided` attribute. */
  @property({ attribute: 'no-divided', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER }) accessor divided = true;

  /** Passed to every Disclosure; required when panels contain form fields. */
  @property({ type: Boolean, reflect: true, attribute: 'keep-mounted' }) accessor keepMounted = false;

  /** Per-instance style overrides: `{ divider: 'color.border.strong' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<AccordionOverridableBinding, TokenRef | undefined>> | undefined;

  /** Uncontrolled open ids, seeded from `defaultValue`. */
  @state() private accessor internalOpenIds: string[] = [];

  /** Light-DOM `<ds-disclosure>` children, each assigned to its own slot. */
  @state() private accessor slottedItems: DsDisclosure[] = [];

  /** The open set the sections currently show, for diffing a controlled `value`. */
  private renderedIds: string[] = [];

  /** The set last emitted while controlled; a `value` equal to it is not reported as `controlled`. */
  private emittedIds: string[] | undefined;

  private readonly childObserver = new MutationObserver(() => {
    this.readChildren();
    this.assignSlots();
  });

  /** The open ids right now, controlled or not; the first id only under `exclusive`. */
  get openIds(): string[] {
    return this.value !== undefined ? this.toOpenIds(this.value) : this.internalOpenIds;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Accordion');
    this.readChildren();
    // childList only: assigning slots never changes the host's children, so this cannot loop.
    this.childObserver.observe(this, { childList: true });
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.childObserver.disconnect();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (!this.hasUpdated) {
      // Given both, `value` controls and `defaultValue` is ignored.
      this.warnExclusive(this.value !== undefined ? this.value : this.defaultValue);
      this.internalOpenIds = this.toOpenIds(this.defaultValue);
      this.renderedIds = this.openIds;
    } else {
      if (changed.has('exclusive') && this.exclusive && this.internalOpenIds.length > 1) {
        // Turning `exclusive` on trims the uncontrolled set to its first-opened id, silently and for good.
        this.internalOpenIds = this.internalOpenIds.slice(0, 1);
      }
      if (changed.has('value') || changed.has('exclusive')) {
        // A standing controlled `value` with several ids keeps warning, once per distinct id list.
        this.warnExclusive(this.value);
      }
      if (changed.has('value')) {
        this.reportControlledChange();
      } else if (changed.has('exclusive')) {
        // Toggling `exclusive` changes only what is shown: no events, and a pending emitted set stays pending.
        this.renderedIds = this.openIds;
      }
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    const sections = this.items
      ? this.items.map((item, index) => html`${this.renderDivider(index)}${this.renderItem(item)}`)
      : this.slottedItems.map((_, index) => html`${this.renderDivider(index)}<slot data-index=${index}></slot>`);
    return html`
      <div data-part="list" part="list" @toggle=${this.handleToggle} @keydown=${this.handleKeydown}>${sections}</div>
    `;
  }

  protected override updated(): void {
    this.syncSlottedItems();
    this.assignSlots();
    this.warnMissingIds();
  }

  private renderDivider(index: number): TemplateResult | typeof nothing {
    return this.divided && index > 0 ? html`<ds-divider></ds-divider>` : nothing;
  }

  private renderItem(item: AccordionItem): TemplateResult {
    return html`
      <ds-disclosure
        id=${item.id}
        summary=${item.summary}
        heading-level=${this.headingLevel}
        full-width
        ?disabled=${item.disabled === true}
        ?keep-mounted=${this.keepMounted}
        .open=${this.openIds.includes(item.id)}
      >
        <slot data-item=${item.id}></slot>
      </ds-disclosure>
    `;
  }

  private readChildren(): void {
    const next = Array.from(this.children).filter(isDisclosure);
    const current = this.slottedItems;
    if (next.length !== current.length || next.some((el, i) => el !== current[i])) {
      this.slottedItems = next;
    }
  }

  /** Assigns each slot its nodes; a slot already holding exactly those nodes is left alone. */
  private assignSlots(): void {
    for (const slot of this.renderRoot.querySelectorAll<HTMLSlotElement>('slot')) {
      const { index, item } = slot.dataset;
      let nodes: Element[] = [];
      if (index !== undefined) {
        const el = this.slottedItems[Number(index)];
        nodes = el ? [el] : [];
      } else if (item !== undefined) {
        nodes = Array.from(this.children).filter((child) => child.getAttribute('slot') === item);
      }
      const assigned = slot.assignedNodes();
      if (assigned.length !== nodes.length || assigned.some((node, i) => node !== nodes[i])) {
        slot.assign(...nodes);
      }
    }
  }

  /** Sets heading-level, keep-mounted and open on every slotted disclosure, writing only what differs. */
  private syncSlottedItems(): void {
    if (this.items) return;
    const openIds = this.openIds;
    for (const el of this.slottedItems) {
      if (el.headingLevel !== this.headingLevel) el.headingLevel = this.headingLevel;
      if (el.keepMounted !== this.keepMounted) el.keepMounted = this.keepMounted;
      const open = el.id !== '' && openIds.includes(el.id);
      if (el.open !== open) el.open = open;
    }
  }

  private itemElements(): DsDisclosure[] {
    if (this.items) {
      return Array.from(this.renderRoot.querySelectorAll<DsDisclosure>('[data-part="list"] > ds-disclosure'));
    }
    return this.slottedItems;
  }

  private readonly handleToggle = (event: Event): void => {
    const target = event.target;
    if (!(target instanceof HTMLElement) || !isDisclosure(target) || !this.itemElements().includes(target)) {
      return;
    }
    // Disclosures the accordion renders itself are internal; their toggle is replaced by change / open-change.
    if (this.items) event.stopPropagation();
    const { open, reason } = (event as CustomEvent<DisclosureToggleDetail>).detail;
    // `controlled` is the disclosure echoing an `open` the accordion just set.
    if (reason === 'controlled' || target.id === '') return;
    this.toggleSection(target.id, open, reason === 'keyboard' ? 'keyboard' : 'trigger');
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    if (event.altKey || event.ctrlKey || event.metaKey) return;
    if (!['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) return;
    const trigger = event
      .composedPath()
      .find((node): node is HTMLElement => node instanceof HTMLElement && node.dataset.part === 'trigger');
    const root = trigger?.getRootNode();
    const items = this.itemElements();
    const current = root instanceof ShadowRoot ? items.findIndex((el) => el === root.host) : -1;
    if (current === -1) return;
    const enabled = (el: DsDisclosure | undefined): el is DsDisclosure => el !== undefined && !el.disabled;
    let next: DsDisclosure | undefined;
    if (event.key === 'Home') {
      next = items.find(enabled);
    } else if (event.key === 'End') {
      next = [...items].reverse().find(enabled);
    } else {
      const step = event.key === 'ArrowDown' ? 1 : -1;
      for (let offset = 1; offset <= items.length && next === undefined; offset += 1) {
        const candidate = items[(current + step * offset + items.length * offset) % items.length];
        if (enabled(candidate)) next = candidate;
      }
    }
    if (next === undefined) return;
    event.preventDefault();
    next.focus();
  };

  /** Applies a user toggle: computes the next open set, closes the others under `exclusive`, and dispatches the events. */
  private toggleSection(id: string, open: boolean, reason: AccordionOpenChangeReason): void {
    const current = this.openIds;
    let next: string[];
    let closed: string[] = [];
    if (open) {
      // Sections `exclusive` closes are reported in item order.
      closed = this.exclusive ? this.inItemOrder(current.filter((existing) => existing !== id)) : [];
      next = this.exclusive ? [id] : current.includes(id) ? current : [...current, id];
    } else {
      next = current.filter((existing) => existing !== id);
    }
    if (this.value === undefined) {
      this.internalOpenIds = next;
      this.renderedIds = next;
    } else {
      // Controlled: the sections show the new set only once `value` changes.
      this.emittedIds = next;
    }
    this.dispatchChange(next);
    this.dispatchOpenChange(id, open, reason);
    for (const closedId of closed) {
      this.dispatchOpenChange(closedId, false, 'exclusive');
    }
  }

  /** Reports a `value` change the accordion did not itself just emit as `reason: 'controlled'`, per section. */
  private reportControlledChange(): void {
    const next = this.openIds;
    const previous = this.renderedIds;
    const emitted = this.emittedIds;
    this.renderedIds = next;
    this.emittedIds = undefined;
    if (emitted !== undefined && sameMembers(emitted, next)) return;
    for (const id of this.inItemOrder([...next, ...previous])) {
      const open = next.includes(id);
      if (open !== previous.includes(id)) this.dispatchOpenChange(id, open, 'controlled');
    }
  }

  /** The given ids sorted by section order; ids naming no section keep their relative order at the end. */
  private inItemOrder(ids: readonly string[]): string[] {
    const order = this.items ? this.items.map((item) => item.id) : this.slottedItems.map((el) => el.id);
    const rank = (id: string): number => {
      const index = order.indexOf(id);
      return index === -1 ? order.length : index;
    };
    return [...new Set(ids)].sort((a, b) => rank(a) - rank(b));
  }

  private dispatchChange(openIds: string[]): void {
    this.dispatchEvent(
      new CustomEvent<AccordionChangeDetail>('change', {
        detail: { openIds: [...openIds] },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private dispatchOpenChange(id: string, open: boolean, reason: AccordionOpenChangeReason): void {
    this.dispatchEvent(
      new CustomEvent<AccordionOpenChangeDetail>('open-change', {
        detail: { id, open, reason },
        bubbles: true,
        composed: true,
      }),
    );
  }

  /** `''` and `[]` are nothing open; a bare string is one id; under `exclusive` only the first id counts. */
  private toOpenIds(value: string | string[] | undefined): string[] {
    const ids = value === undefined || value === '' ? [] : Array.isArray(value) ? value : [value];
    return this.exclusive ? ids.slice(0, 1) : [...ids];
  }

  /** Id lists already warned about, so each distinct list warns once. */
  private readonly warnedIdLists = new Set<string>();

  private warnExclusive(value: string | string[] | undefined): void {
    if (!import.meta.env.DEV || !this.exclusive || !Array.isArray(value) || value.length < 2) return;
    const key = JSON.stringify(value);
    if (this.warnedIdLists.has(key)) return;
    this.warnedIdLists.add(key);
    console.warn(
      `ds-accordion: \`exclusive\` opens one section; opened "${value[0]}" and ignored ${value
        .slice(1)
        .map((id) => `"${id}"`)
        .join(', ')}.`,
      this,
    );
  }

  private warnedMissingId = false;

  private warnMissingIds(): void {
    if (!import.meta.env.DEV || this.warnedMissingId) return;
    const missing = this.itemElements().find((el) => el.id === '');
    if (missing) {
      this.warnedMissingId = true;
      console.warn('ds-accordion: every section needs a unique `id`; it is how `value` and the events identify it.', missing);
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as AccordionOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-accordion': DsAccordion;
  }
}
