// packages/rn/src/ActionSheet.tsx
import * as React from 'react';
import {
  AccessibilityInfo,
  Animated,
  Modal,
  PanResponder,
  Pressable,
  StyleSheet,
  Text as RNText,
  View,
  findNodeHandle,
  useWindowDimensions,
} from 'react-native';
import type { LayoutChangeEvent, TextStyle, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { FocusScope } from './FocusScope';
import { Icon } from './Icon';
import type { IconName } from './Icon';
import { Text } from './Text';
import { toEasing, toLineHeight, useReducedMotion, useTheme } from './theme';

export type ActionSheetActionTone = 'default' | 'danger';

/** One row. `danger` actions are visually distinct and rendered as a group after the others, regardless of their position in the array. */
export type ActionSheetAction = {
  id: string;
  label: string;
  icon?: IconName;
  tone?: ActionSheetActionTone;
  disabled?: boolean;
};

/** Why `onClose` fired. */
export type ActionSheetCloseReason = 'escape' | 'scrim' | 'cancel' | 'drag';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type ActionSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'itemPaddingBlock'
  | 'itemPaddingInline'
  | 'itemGap'
  | 'titleSize'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'divider'
  | 'dividerWidth'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

export interface ActionSheetProps {
  /** Controlled visibility. */
  open: boolean;
  /** What the actions apply to ("Photo.jpg"), shown muted above the list. Also the accessible name; when omitted the name is `copy.defaultLabel`. */
  title?: string;
  /** Two to about eight actions. `danger` actions are visually distinct and grouped last. */
  actions: ActionSheetAction[];
  /** Label of the explicit cancel row. Defaults to `copy.cancelLabel`. */
  cancelLabel?: string;
  /** An action was chosen; receives its `id`. The consumer performs it and closes. */
  onAction?: (id: string) => void;
  /** Dismissed without choosing: reason `escape`, `scrim`, `cancel`, or `drag`. */
  onClose?: (reason: ActionSheetCloseReason) => void;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<ActionSheetOverridableBinding, TokenRef>>;
}

const COPY = {
  cancelLabel: 'Cancel',
  defaultLabel: 'Actions',
} as const;

const DRAG_DISMISS_RATIO = 0.25; // literal-ok: fraction of sheet height past which a drag dismisses, matching BottomSheet
const DRAG_DISMISS_VELOCITY = 1.5; // literal-ok: release velocity (px/ms) past which a drag dismisses regardless of distance

/**
 * ActionSheet — "what can I do with this?" A short list of verbs for one item,
 * reached from an overflow button or a long-press, with the dangerous one grouped
 * last and an explicit Cancel because thumbs miss.
 *
 * When to use: Use for contextual actions on an item — share, rename, duplicate,
 * delete — opened from an overflow `Button` (`iconOnly`, label "More actions") or a
 * long-press. Keep it to what fits without scrolling; more than eight actions means
 * the item needs its own screen. Put destructive actions last with `tone: "danger"`.
 * Do not use it for navigation, for settings with state, for choosing a value, or to
 * confirm a decision — its danger row opens an `AlertDialog`, it does not itself
 * confirm.
 *
 * Renders a native `Modal` (`transparent`, `statusBarTranslucent`) with a full-screen
 * scrim `Pressable` and an `Animated.View` surface anchored to the bottom, sliding up
 * on open (skipped under reduced motion). The surface composes `FocusScope`
 * (`trapped`, `restoreFocus`) for the trap and focus-restore-on-close, the system
 * `Text` (`size="sm"`, `tone="muted"`) for the title, `Icon` for each row's glyph and
 * `Button` (`variant="secondary"`) for the explicit Cancel row — never restyled
 * directly. Rows are `Pressable`s with `accessibilityRole="menuitem"` and
 * `accessibilityState={{ disabled }}` — never the native `disabled` prop, which would
 * drop them from the focus order; a press guard makes disabled rows inert instead.
 * Once the enter animation finishes (or immediately under reduced motion),
 * accessibility focus moves to the first enabled action via
 * `AccessibilityInfo.setAccessibilityFocus`. A `PanResponder` on the header (the
 * title area, present whether or not `title` is set) tracks a downward drag; past
 * 25% of the measured surface height or a fast flick, it fires `onClose('drag')` and
 * continues the motion off-screen with `Animated.decay` at the release velocity
 * (instant, no decay, under reduced motion); otherwise it springs back. The gesture
 * is purely additive — the scrim, Escape (mapped from the Android back button via
 * `onRequestClose`) and the Cancel row always exist. Choosing an action does not
 * close the sheet itself: `onAction` reports the id and the consumer decides, exactly
 * like the web/Lit doc describes ("the consumer performs it and closes").
 *
 * Acknowledged native limits: there is no generic key-event API on `Pressable`, so
 * ArrowUp/ArrowDown/Home/End movement and the roving-tabindex model the web doc
 * describes have no equivalent here — each row is instead its own Tab stop, the same
 * convention `Menu` and `RadioGroup` use; Enter/Space activate a focused row through
 * the platform's own accessibility action. The wide-screen presentation ("above
 * `maxWidth`, renders as a `Menu` anchored to the trigger") is not implemented: the
 * package's `Menu` always renders its own trigger `Button` and has no way to anchor
 * to an element rendered elsewhere in the tree, so composing it here would mean
 * duplicating its positioning logic rather than reusing it. ActionSheet therefore
 * always presents as the phone sheet, on tablets too — the mirror image of the limit
 * `Menu`'s own doc comment already acknowledges. The `maxWidth` override is
 * consequently a no-op: the binding governs a breakpoint this platform does not
 * switch on.
 */
export function ActionSheet({
  open,
  title,
  actions,
  cancelLabel,
  onAction,
  onClose,
  overrides,
}: ActionSheetProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const { height: windowHeight } = useWindowDimensions();
  const resolvedCancelLabel = cancelLabel ?? COPY.cancelLabel;
  const accessibleName = title ?? COPY.defaultLabel;

  const [mounted, setMounted] = React.useState(open);
  const progress = React.useRef(new Animated.Value(open ? 1 : 0)).current;
  const dragY = React.useRef(new Animated.Value(0)).current;
  const surfaceHeightRef = React.useRef(0);
  const itemRefs = React.useRef(new Map<string, View>());

  const scrimColor = overrides?.scrim ? (resolveToken(t, overrides.scrim) as string) : t.colorOverlayScrim;
  const surfaceColor = t.colorOverlaySurface;
  const shadow = overrides?.shadow ? (resolveToken(t, overrides.shadow) as typeof t.shadowOverlay) : t.shadowOverlay;
  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusLg;
  const itemPaddingBlock = overrides?.itemPaddingBlock ? (resolveToken(t, overrides.itemPaddingBlock) as number) : t.spaceSm;
  const itemPaddingInline = overrides?.itemPaddingInline
    ? (resolveToken(t, overrides.itemPaddingInline) as number)
    : t.layoutInsetMd;
  const itemGap = overrides?.itemGap ? (resolveToken(t, overrides.itemGap) as number) : t.layoutGapNormal;
  const fontFamily = overrides?.fontFamily ? (resolveToken(t, overrides.fontFamily) as string) : t.fontFamilyBody;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t.fontSizeMd;
  const lineHeightMultiplier = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;
  const dividerColor = overrides?.divider ? (resolveToken(t, overrides.divider) as string) : t.colorBorder;
  const dividerWidth = overrides?.dividerWidth ? (resolveToken(t, overrides.dividerWidth) as number) : t.borderWidthThin;
  const layer = overrides?.layer ? (resolveToken(t, overrides.layer) as number) : t.layerSheet;
  const enterDuration = overrides?.enter ? (resolveToken(t, overrides.enter) as number) : t.motionDurationBase;
  const exitDuration = overrides?.exit ? (resolveToken(t, overrides.exit) as number) : t.motionDurationFast;

  const minTarget = t.sizeTargetComfortable;
  const itemHoverColor = t.colorBackgroundSubtle;
  const itemColor = t.colorForeground;
  const itemDangerColor = t.colorForegroundDanger;
  const focusRingColor = t.colorBorderFocus;
  const focusRingWidth = t.borderWidthFocus;

  const normalActions = actions.filter((action) => action.tone !== 'danger');
  const dangerActions = actions.filter((action) => action.tone === 'danger');

  React.useEffect(() => {
    if (open) {
      setMounted(true);
    }
  }, [open]);

  const registerItemRef = (id: string) => (node: View | null): void => {
    if (node) itemRefs.current.set(id, node);
    else itemRefs.current.delete(id);
  };

  const focusFirstEnabledAction = React.useCallback(() => {
    const target = actions.find((action) => action.disabled !== true);
    const node = target ? itemRefs.current.get(target.id) : null;
    const handle = node ? findNodeHandle(node) : null;
    if (handle !== null) {
      AccessibilityInfo.setAccessibilityFocus(handle);
    }
  }, [actions]);

  React.useEffect(() => {
    if (!mounted) {
      return undefined;
    }
    if (open) {
      dragY.setValue(0);
      if (reducedMotion) {
        progress.setValue(1);
        focusFirstEnabledAction();
        return undefined;
      }
      const animation = Animated.timing(progress, {
        toValue: 1,
        duration: enterDuration,
        easing: toEasing(t.motionEasingStandard),
        // react-native-web has no native animated module.
        useNativeDriver: false,
      });
      animation.start(({ finished }) => {
        if (finished) {
          focusFirstEnabledAction();
        }
      });
      return () => animation.stop();
    }
    if (reducedMotion) {
      progress.setValue(0);
      setMounted(false);
      return undefined;
    }
    const animation = Animated.timing(progress, {
      toValue: 0,
      duration: exitDuration,
      easing: toEasing(t.motionEasingExit),
      useNativeDriver: false,
    });
    animation.start(({ finished }) => {
      if (finished) {
        setMounted(false);
      }
    });
    return () => animation.stop();
    // Reacts to the open/closed transition and the mount gate it drives; the
    // animation's own config and the focus callback are read fresh each run rather
    // than tracked as deps.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, mounted, reducedMotion]);

  React.useEffect(() => {
    if (__DEV__ && actions.length === 0) {
      console.warn('ActionSheet: `actions` is empty; the sheet would open with nothing to choose.');
    } else if (__DEV__ && actions.length > 8) {
      console.warn('ActionSheet: more than eight actions; consider giving this item its own screen instead.');
    }
  }, [actions]);

  const handleScrimPress = (): void => {
    onClose?.('scrim');
  };

  const handleCancelPress = (): void => {
    onClose?.('cancel');
  };

  const handleRequestClose = (): void => {
    onClose?.('escape');
  };

  const handleSurfaceLayout = (event: LayoutChangeEvent): void => {
    surfaceHeightRef.current = event.nativeEvent.layout.height;
  };

  const handleActionPress = (action: ActionSheetAction): void => {
    if (action.disabled === true) {
      return;
    }
    onAction?.(action.id);
  };

  const panResponder = React.useMemo(
    () =>
      PanResponder.create({
        // False at touch-start so a tap on the title is not stolen by the responder;
        // only an actual downward drag claims it.
        onStartShouldSetPanResponder: () => false,
        onMoveShouldSetPanResponder: (_, gestureState) =>
          gestureState.dy > 4 && Math.abs(gestureState.dy) > Math.abs(gestureState.dx),
        onPanResponderMove: (_, gestureState) => {
          if (gestureState.dy > 0) {
            dragY.setValue(gestureState.dy);
          }
        },
        onPanResponderRelease: (_, gestureState) => {
          const threshold = (surfaceHeightRef.current || windowHeight * 0.5) * DRAG_DISMISS_RATIO;
          const shouldDismiss = gestureState.dy > threshold || gestureState.vy > DRAG_DISMISS_VELOCITY;
          if (shouldDismiss) {
            onClose?.('drag');
            if (reducedMotion) {
              dragY.setValue(windowHeight);
            } else {
              Animated.decay(dragY, {
                velocity: Math.max(gestureState.vy, 0.5),
                deceleration: 0.998,
                useNativeDriver: false,
              }).start();
            }
            return;
          }
          if (reducedMotion) {
            dragY.setValue(0);
            return;
          }
          Animated.timing(dragY, {
            toValue: 0,
            duration: exitDuration,
            easing: toEasing(t.motionEasingStandard),
            useNativeDriver: false,
          }).start();
        },
        onPanResponderTerminate: () => {
          if (reducedMotion) {
            dragY.setValue(0);
            return;
          }
          Animated.timing(dragY, { toValue: 0, duration: exitDuration, useNativeDriver: false }).start();
        },
      }),
    [dragY, windowHeight, onClose, reducedMotion, exitDuration, t.motionEasingStandard],
  );

  const hostStyle: ViewStyle = { flex: 1 };

  const scrimStyle: Animated.WithAnimatedObject<ViewStyle> = {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: scrimColor,
    opacity: progress,
  };

  const anchorStyle: ViewStyle = { flex: 1, justifyContent: 'flex-end', zIndex: layer };

  const entryTranslateY = progress.interpolate({ inputRange: [0, 1], outputRange: [windowHeight, 0] });

  const surfaceStyle: Animated.WithAnimatedObject<ViewStyle> = {
    width: '100%',
    maxHeight: windowHeight * 0.9, // literal-ok: proportion of viewport, matching BottomSheet's "content" sizing
    borderTopLeftRadius: radius,
    borderTopRightRadius: radius,
    ...shadow,
    backgroundColor: surfaceColor,
    overflow: 'hidden',
    transform: [{ translateY: Animated.add(entryTranslateY, dragY) }],
  };

  const headerStyle: ViewStyle = {
    paddingHorizontal: itemPaddingInline,
    paddingVertical: t.spaceSm, // not named by any binding; matches the item row's own vertical rhythm
  };

  const dividerStyle: ViewStyle = {
    borderBottomWidth: dividerWidth,
    borderBottomColor: dividerColor,
  };

  const cancelRowStyle: ViewStyle = {
    padding: itemPaddingInline,
  };

  const itemRowStyle = (focused: boolean, disabled: boolean): ViewStyle => ({
    flexDirection: 'row',
    alignItems: 'center',
    gap: itemGap,
    minHeight: minTarget,
    paddingVertical: itemPaddingBlock,
    paddingHorizontal: itemPaddingInline,
    backgroundColor: focused ? itemHoverColor : 'transparent',
    borderWidth: focusRingWidth,
    borderColor: focused ? focusRingColor : 'transparent',
    opacity: disabled ? t.opacityDisabled : 1,
  });

  const itemLabelStyle = (danger: boolean): TextStyle => ({
    flexShrink: 1,
    fontFamily,
    fontSize,
    lineHeight: toLineHeight(fontSize, lineHeightMultiplier),
    color: danger ? itemDangerColor : itemColor,
  });

  function renderAction(action: ActionSheetAction): React.JSX.Element {
    const danger = action.tone === 'danger';
    return (
      <ActionSheetItemRow
        key={action.id}
        action={action}
        registerRef={registerItemRef(action.id)}
        rowStyle={itemRowStyle}
        labelStyle={itemLabelStyle(danger)}
        iconColor={danger ? itemDangerColor : itemColor}
        onActivate={() => handleActionPress(action)}
      />
    );
  }

  return (
    <Modal visible={mounted} transparent onRequestClose={handleRequestClose} statusBarTranslucent>
      <View style={hostStyle}>
        <Animated.View style={scrimStyle} />
        <Pressable
          style={StyleSheet.absoluteFillObject}
          onPress={handleScrimPress}
          accessible={false}
          testID="ActionSheet.scrim"
        />
        <View style={anchorStyle} pointerEvents="box-none">
          <FocusScope trapped active={mounted} autoFocus="none" restoreFocus>
            <Animated.View
              style={surfaceStyle}
              onLayout={handleSurfaceLayout}
              accessibilityViewIsModal
              accessibilityRole="menu"
              accessibilityLabel={accessibleName}
              testID="ActionSheet"
            >
              <View {...panResponder.panHandlers} style={headerStyle}>
                {title !== undefined ? (
                  <Text size="sm" tone="muted" overrides={{ fontSize: overrides?.titleSize, fontFamily: overrides?.fontFamily }}>
                    {title}
                  </Text>
                ) : null}
              </View>
              <View testID="ActionSheet.list">
                {normalActions.map((action) => renderAction(action))}
                {dangerActions.length > 0 ? (
                  <>
                    <View style={dividerStyle} />
                    {dangerActions.map((action) => renderAction(action))}
                  </>
                ) : null}
              </View>
              <View style={dividerStyle} />
              <View style={cancelRowStyle}>
                <Button label={resolvedCancelLabel} variant="secondary" onPress={handleCancelPress} />
              </View>
            </Animated.View>
          </FocusScope>
        </View>
      </View>
    </Modal>
  );
}

interface ActionSheetItemRowProps {
  action: ActionSheetAction;
  registerRef: (node: View | null) => void;
  rowStyle: (focused: boolean, disabled: boolean) => ViewStyle;
  labelStyle: TextStyle;
  iconColor: string;
  onActivate: () => void;
}

/** One action row. Its own component so focus state does not re-render the whole list. */
function ActionSheetItemRow({
  action,
  registerRef,
  rowStyle,
  labelStyle,
  iconColor,
  onActivate,
}: ActionSheetItemRowProps): React.JSX.Element {
  const [focused, setFocused] = React.useState(false);
  const disabled = action.disabled === true;

  return (
    <Pressable
      ref={registerRef}
      accessibilityRole="menuitem"
      accessibilityLabel={action.label}
      accessibilityState={{ disabled }}
      // Never the native `disabled` prop: it would drop the row from the focus order.
      onPress={() => {
        if (!disabled) {
          onActivate();
        }
      }}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      style={rowStyle(focused, disabled)}
      testID="ActionSheet.item"
    >
      {action.icon !== undefined ? (
        <View accessibilityElementsHidden importantForAccessibility="no">
          <Icon name={action.icon} color={iconColor} />
        </View>
      ) : null}
      <RNText numberOfLines={1} style={labelStyle}>
        {action.label}
      </RNText>
    </Pressable>
  );
}

// packages/lit/src/ActionSheet.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import './Button.js';
import './Icon.js';
import './FocusScope.js';
import './Menu.js';
import type { IconName } from './Icon.js';
import type { TextOverridableBinding } from './Text.js';
import type { MenuActionDetail, MenuActionItem, MenuItem, MenuOpenChangeDetail } from './Menu.js';

export type ActionSheetActionTone = 'default' | 'danger';
export type ActionSheetCloseReason = 'escape' | 'scrim' | 'cancel' | 'drag';

/** A single row (anatomy: item). */
export interface ActionSheetAction {
  id: string;
  label: string;
  icon?: IconName;
  tone?: ActionSheetActionTone;
  disabled?: boolean;
}

/** Detail carried by the `action` CustomEvent. */
export interface ActionSheetActionDetail {
  id: string;
}

/** Detail carried by the `close` CustomEvent. */
export interface ActionSheetCloseDetail {
  reason: ActionSheetCloseReason;
}

/**
 * Overridable style hooks; see the `overrides` property. `surface`, `itemHover`, `itemColor`,
 * `itemDangerColor`, `titleColor`, `minTarget`, `focusRing` and `focusRingWidth` are locked and
 * excluded. `titleSize` has no host hook of its own — it is forwarded to the composed title
 * `<ds-text>`'s own `overrides` (which already owns font size), along with `fontFamily` and
 * `lineHeight` (also applied to the item rows directly). Only applies to the phone presentation;
 * above the wide breakpoint the sheet renders as `<ds-menu>` and uses Menu's own overrides contract.
 */
export type ActionSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'itemPaddingBlock'
  | 'itemPaddingInline'
  | 'itemGap'
  | 'titleSize'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'divider'
  | 'dividerWidth'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

const HOOKS: Partial<Record<ActionSheetOverridableBinding, string>> = {
  scrim: '--ds-action-sheet-scrim',
  shadow: '--ds-action-sheet-shadow',
  radius: '--ds-action-sheet-radius',
  itemPaddingBlock: '--ds-action-sheet-item-padding-block',
  itemPaddingInline: '--ds-action-sheet-item-padding-inline',
  itemGap: '--ds-action-sheet-item-gap',
  fontFamily: '--ds-action-sheet-font-family',
  fontSize: '--ds-action-sheet-font-size',
  lineHeight: '--ds-action-sheet-line-height',
  divider: '--ds-action-sheet-divider',
  dividerWidth: '--ds-action-sheet-divider-width',
  maxWidth: '--ds-action-sheet-max-width',
  layer: '--ds-action-sheet-layer',
  enter: '--ds-action-sheet-enter',
  exit: '--ds-action-sheet-exit',
};

/** copy.cancelLabel */
const COPY_CANCEL_LABEL = 'Cancel';
/** copy.defaultLabel */
const COPY_DEFAULT_LABEL = 'Actions';

/** How many `<ds-action-sheet>` instances (in their bottom-edge presentation) hold the body-scroll lock. */
let openSheetCount = 0;

function lockBodyScroll(): void {
  openSheetCount += 1;
  if (openSheetCount === 1) {
    document.documentElement.style.overflow = 'hidden';
  }
}

function unlockBodyScroll(): void {
  openSheetCount = Math.max(0, openSheetCount - 1);
  if (openSheetCount === 0) {
    document.documentElement.style.removeProperty('overflow');
  }
}

function getDeepActiveElement(): Element | null {
  let active = document.activeElement;
  while (active?.shadowRoot?.activeElement) {
    active = active.shadowRoot.activeElement;
  }
  return active;
}

function prefersReducedMotion(): boolean {
  return matchMedia('(prefers-reduced-motion: reduce)').matches;
}

function toMenuActionItem(action: ActionSheetAction): MenuActionItem {
  return { id: action.id, label: action.label, icon: action.icon, tone: action.tone, disabled: action.disabled };
}

/**
 * `<ds-action-sheet>` — ActionSheet (category: overlay, APG pattern: menu-button).
 *
 * Below `layout.maxWidth.prose` a shadow `<dialog>` opened with `showModal()` rises from the bottom
 * edge (the same mechanics as `<ds-bottom-sheet>`): a scrim, a `<ds-focus-scope trapped>`, an optional
 * muted `<ds-text>` title, a `role="menu"` list of `role="menuitem"` `<button>` rows (danger actions
 * grouped last behind a divider), a divider, and a `<ds-button variant="secondary">` Cancel row. A
 * downward drag on the surface past a distance or velocity threshold closes with reason `drag`,
 * additive to Escape, the scrim and Cancel. Above the breakpoint the same `actions` render as
 * `<ds-menu>` — non-modal, no Cancel row — positioned at the element that was focused when `open`
 * became true (Menu's own trigger has no notion of an external anchor, so it is placed at that
 * element's screen position and hidden with `opacity: 0`).
 *
 * ## When to use
 *
 * Use an ActionSheet for contextual actions on an item — share, rename, duplicate, delete — opened
 * from an overflow Button (`iconOnly`, label "More actions") or a long-press. Keep it to what fits
 * without scrolling; more than eight actions means the item needs its own screen. Put destructive
 * actions last with `tone: danger`.
 *
 * ## When not to use
 *
 * Not for navigation (Menu in a nav Landmark, or Links), for settings with state (a screen of
 * Switches), for choosing a value (Select or RadioGroup in a BottomSheet), or for confirming — an
 * ActionSheet's danger row opens an AlertDialog, it does not itself confirm. Do not put forms in it.
 *
 * @fires action - An action was chosen, with `{ id }`. The consumer performs it and closes.
 * @fires close - Dismissed without choosing, with `{ reason: 'escape' | 'scrim' | 'cancel' | 'drag' }`.
 *   The consumer sets `open` to false.
 * @csspart surface - The padded, bordered surface (anatomy: surface).
 * @csspart focus-scope - The focus-trapping wrapper (anatomy: focusScope).
 * @csspart title - The `<ds-text>` title (anatomy: title).
 * @csspart list - The `role="menu"` container (anatomy: list).
 * @csspart item - Each `role="menuitem"` row (anatomy: item).
 * @csspart item-icon - An item's leading `<ds-icon>` (anatomy: itemIcon).
 * @csspart cancel-button - The Cancel `<ds-button>` (anatomy: cancelButton).
 */
@customElement('ds-action-sheet')
export class DsActionSheet extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      --ds-action-sheet-scrim: var(--color-overlay-scrim);
      --ds-action-sheet-shadow: var(--shadow-overlay);
      --ds-action-sheet-radius: var(--radius-lg);
      --ds-action-sheet-item-padding-block: var(--space-sm);
      --ds-action-sheet-item-padding-inline: var(--layout-inset-md);
      --ds-action-sheet-item-gap: var(--layout-gap-normal);
      --ds-action-sheet-font-family: var(--font-family-body);
      --ds-action-sheet-font-size: var(--font-size-md);
      --ds-action-sheet-line-height: var(--font-line-height-normal);
      --ds-action-sheet-divider: var(--color-border);
      --ds-action-sheet-divider-width: var(--border-width-thin);
      --ds-action-sheet-max-width: var(--layout-max-width-prose);
      --ds-action-sheet-layer: var(--layer-sheet);
      --ds-action-sheet-enter: var(--motion-duration-base);
      --ds-action-sheet-exit: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    dialog {
      box-sizing: border-box;
      position: fixed;
      inset-block-end: 0;
      inset-inline: 0;
      margin: 0;
      padding: 0;
      border: 0;
      inline-size: 100%;
      max-inline-size: none;
      max-block-size: 90dvh;
      background: transparent;
      color: inherit;
      z-index: var(--ds-action-sheet-layer);
    }

    /* scrim: color.overlay.scrim */
    dialog::backdrop {
      background: var(--ds-action-sheet-scrim);
      transition: opacity var(--ds-action-sheet-enter) var(--motion-easing-standard);
    }

    @starting-style {
      dialog[open]::backdrop {
        opacity: 0;
      }
    }

    .surface {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      font-family: var(--font-family-body);
      /* surface: color.overlay.surface, locked — no override hook */
      background: var(--color-overlay-surface);
      border-start-start-radius: var(--ds-action-sheet-radius);
      border-start-end-radius: var(--ds-action-sheet-radius);
      box-shadow: var(--ds-action-sheet-shadow);
      overflow: hidden;
      padding-block-end: env(safe-area-inset-bottom);
      transform: translateY(0);
      transition: transform var(--ds-action-sheet-enter) var(--motion-easing-standard);
      touch-action: none;
    }

    .surface.closing {
      transform: translateY(100%);
      transition-duration: var(--ds-action-sheet-exit);
      transition-timing-function: var(--motion-easing-exit);
    }

    @starting-style {
      dialog[open] .surface {
        transform: translateY(100%);
      }
    }

    @media (prefers-reduced-motion: reduce) {
      dialog::backdrop,
      .surface {
        transition: none;
      }
    }

    /* handle: color.foreground.muted, locked — a decorative drag affordance; not in the schema
       anatomy (see the generation gap report), mirrored from ds-bottom-sheet's own handle. */
    .handle {
      align-self: center;
      flex: 0 0 auto;
      inline-size: var(--space-10);
      block-size: var(--space-1);
      margin-block-start: var(--layout-gap-tight);
      border-radius: var(--radius-full);
      background: var(--color-foreground-muted);
    }

    .title {
      flex: 0 0 auto;
      padding-inline: var(--ds-action-sheet-item-padding-inline);
      padding-block: var(--layout-gap-tight);
    }

    .list {
      display: flex;
      flex-direction: column;
      flex: 0 1 auto;
      overflow-y: auto;
      font-family: var(--ds-action-sheet-font-family);
      font-size: var(--ds-action-sheet-font-size);
      line-height: var(--ds-action-sheet-line-height);
    }

    .item {
      box-sizing: border-box;
      display: flex;
      align-items: center;
      gap: var(--ds-action-sheet-item-gap);
      min-block-size: var(--size-target-comfortable);
      padding-block: var(--ds-action-sheet-item-padding-block);
      padding-inline: var(--ds-action-sheet-item-padding-inline);
      border: 0;
      background: none;
      /* itemColor: color.foreground, locked */
      color: var(--color-foreground);
      font: inherit;
      text-align: start;
      cursor: pointer;
      transition: background-color var(--motion-duration-fast) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      .item {
        transition: none;
      }
    }

    /* itemHover: color.background.subtle, locked — pointer hover and keyboard focus share it */
    .item:hover,
    .item:focus {
      outline: none;
      background: var(--color-background-subtle);
    }

    /* focusRing / focusRingWidth: color.border.focus / border.width.focus, locked */
    .item:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: calc(-1 * var(--border-width-focus));
    }

    .item[aria-disabled='true'] {
      cursor: not-allowed;
      opacity: var(--opacity-disabled);
    }

    /* itemDangerColor: color.foreground.danger, locked */
    .item[data-tone='danger'] {
      color: var(--color-foreground-danger);
    }

    .item-icon {
      flex: none;
    }

    .item-label {
      flex: 1;
      min-inline-size: 0;
    }

    .divider {
      flex: 0 0 auto;
      block-size: var(--ds-action-sheet-divider-width);
      background: var(--ds-action-sheet-divider);
    }

    .cancel-button {
      flex: 0 0 auto;
      align-self: stretch;
      margin: var(--ds-action-sheet-item-padding-inline);
    }
  `;

  /** Controlled visibility. */
  @property({ type: Boolean, reflect: true }) open = false;

  /**
   * What the actions apply to ("Photo.jpg"), shown muted above the list. Also the accessible name;
   * when omitted the name is `copy.defaultLabel`. Named `heading`, not `title` — `HTMLElement`
   * already defines `title` as the tooltip attribute.
   */
  @property() heading?: string;

  /** Two to about eight actions. `danger` actions are visually distinct and grouped last. */
  @property({ attribute: false }) actions: ActionSheetAction[] = [];

  /** Label of the explicit cancel row on phones. Defaults to `copy.cancelLabel`. */
  @property({ attribute: 'cancel-label' }) cancelLabel?: string;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<ActionSheetOverridableBinding, TokenRef>>;

  /** Above `layout.maxWidth.prose` the sheet renders as `<ds-menu>` anchored to the opener instead. */
  @state() private isWide = false;

  /** Whether the exit transition is playing (kept present a beat past the `open` flip to animate out). */
  @state() private closing = false;

  /** The action currently carrying the roving tabindex and real focus (narrow presentation only). */
  @state() private activeId: string | null = null;

  @query('dialog') private readonly dialogEl!: HTMLDialogElement;
  @query('.cancel-button') private readonly cancelButtonEl!: HTMLElement;

  private openerElement: Element | null = null;
  private wideQuery: MediaQueryList | null = null;
  private dragState: { startY: number; startTime: number } | null = null;
  private anchorRect: { top: number; left: number; width: number; height: number } | null = null;
  /** Set just before dispatching `action`, so the `<ds-menu>` close that follows selection is not also reported as a dismissal. */
  private menuClosingForAction = false;

  private readonly handleWideChange = (event: MediaQueryListEvent): void => {
    this.isWide = event.matches;
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'ActionSheet');
    const breakpoint = getComputedStyle(document.documentElement).getPropertyValue('--layout-max-width-prose').trim();
    if (breakpoint) {
      this.wideQuery = matchMedia(`(min-width: ${breakpoint})`);
      this.isWide = this.wideQuery.matches;
      this.wideQuery.addEventListener('change', this.handleWideChange);
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.wideQuery?.removeEventListener('change', this.handleWideChange);
    if (!this.isWide && this.dialogEl?.open) {
      unlockBodyScroll();
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('open') && this.open && this.isWide) {
      const opener = getDeepActiveElement();
      this.anchorRect = opener instanceof HTMLElement ? opener.getBoundingClientRect() : null;
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (!this.isWide && changed.has('open')) {
      if (this.open) {
        this.handleOpen();
      } else if (changed.get('open') as boolean) {
        this.playExit();
      }
    }
    this.warnInDev();
  }

  protected override render() {
    return this.isWide ? this.renderWide() : this.renderNarrow();
  }

  private renderWide() {
    if (!this.open) {
      return nothing;
    }
    const rect = this.anchorRect;
    const anchorStyle = rect
      ? `position:fixed;top:${rect.top}px;left:${rect.left}px;width:${rect.width}px;height:${rect.height}px;opacity:0;pointer-events:none;`
      : '';
    return html`
      <ds-menu
        label=${this.accessibleLabel()}
        .items=${this.menuItems()}
        open
        trigger-icon="none"
        style=${anchorStyle}
        @action=${this.handleMenuAction}
        @open-change=${this.handleMenuOpenChange}
      ></ds-menu>
    `;
  }

  private renderNarrow() {
    const accessibleLabel = this.accessibleLabel();
    const { defaults, danger } = this.partitionedActions();

    return html`
      <dialog aria-modal="true" @cancel=${this.handleCancel} @click=${this.handleDialogClick}>
        <div
          class="surface${this.closing ? ' closing' : ''}"
          part="surface"
          @pointerdown=${this.handleSurfacePointerDown}
          @pointermove=${this.handleSurfacePointerMove}
          @pointerup=${this.handleSurfacePointerUp}
          @pointercancel=${this.handleSurfacePointerUp}
        >
          <ds-focus-scope
            part="focus-scope"
            trapped
            ?active=${this.open}
            auto-focus="none"
            ?restore-focus=${false}
            style="display: flex; flex-direction: column"
          >
            <span class="handle" aria-hidden="true"></span>
            ${this.heading
              ? html`<ds-text part="title" class="title" size="sm" tone="muted" .overrides=${this.titleOverrides()}
                  >${this.heading}</ds-text
                >`
              : nothing}
            <div class="list" part="list" role="menu" aria-label=${accessibleLabel} @keydown=${this.handleListKeydown}>
              ${defaults.map((action) => this.renderItem(action))}
              ${danger.length ? html`<div class="divider" part="divider" role="separator" aria-hidden="true"></div>` : nothing}
              ${danger.map((action) => this.renderItem(action))}
            </div>
            <div class="divider" part="divider" role="separator" aria-hidden="true"></div>
            <ds-button
              class="cancel-button"
              part="cancel-button"
              variant="secondary"
              label=${this.cancelLabel || COPY_CANCEL_LABEL}
              @press=${this.handleCancelPress}
            ></ds-button>
          </ds-focus-scope>
        </div>
      </dialog>
    `;
  }

  private renderItem(action: ActionSheetAction) {
    return html`
      <button
        type="button"
        class="item"
        part="item"
        role="menuitem"
        data-id=${action.id}
        data-tone=${ifDefined(action.tone === 'danger' ? 'danger' : undefined)}
        tabindex=${this.activeId === action.id ? 0 : -1}
        aria-disabled=${ifDefined(action.disabled ? 'true' : undefined)}
        @click=${() => this.handleItemClick(action)}
        @pointerenter=${() => this.handleItemPointerEnter(action)}
      >
        ${action.icon
          ? html`<ds-icon class="item-icon" part="item-icon" name=${action.icon} aria-hidden="true"></ds-icon>`
          : nothing}
        <span class="item-label">${action.label}</span>
      </button>
    `;
  }

  private accessibleLabel(): string {
    return this.heading || COPY_DEFAULT_LABEL;
  }

  private partitionedActions(): { defaults: ActionSheetAction[]; danger: ActionSheetAction[] } {
    const defaults = this.actions.filter((action) => action.tone !== 'danger');
    const danger = this.actions.filter((action) => action.tone === 'danger');
    return { defaults, danger };
  }

  private navigableActions(): ActionSheetAction[] {
    return this.actions.filter((action) => !action.disabled);
  }

  private menuItems(): MenuItem[] {
    const { defaults, danger } = this.partitionedActions();
    const items: MenuItem[] = defaults.map(toMenuActionItem);
    if (danger.length > 0) {
      items.push({ separator: true });
      items.push(...danger.map(toMenuActionItem));
    }
    return items;
  }

  private titleOverrides(): Partial<Record<TextOverridableBinding, TokenRef>> | undefined {
    const overrides = this.overrides;
    if (!overrides) {
      return undefined;
    }
    const result: Partial<Record<TextOverridableBinding, TokenRef>> = {};
    if (overrides.titleSize) {
      result.fontSize = overrides.titleSize;
    }
    if (overrides.fontFamily) {
      result.fontFamily = overrides.fontFamily;
    }
    if (overrides.lineHeight) {
      result.lineHeight = overrides.lineHeight;
    }
    return Object.keys(result).length ? result : undefined;
  }

  private readonly handleListKeydown = (event: KeyboardEvent): void => {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.moveFocus(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.moveFocus(-1);
        break;
      case 'Home':
        event.preventDefault();
        void this.focusAction('first');
        break;
      case 'End':
        event.preventDefault();
        void this.focusAction('last');
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        this.activateActiveAction();
        break;
      default:
        break;
    }
  };

  private readonly handleItemClick = (action: ActionSheetAction): void => {
    if (action.disabled) {
      return;
    }
    this.dispatchAction(action.id);
  };

  private readonly handleItemPointerEnter = (action: ActionSheetAction): void => {
    if (action.disabled) {
      return;
    }
    void this.focusAction(action.id);
  };

  private readonly handleCancel = (event: Event): void => {
    // The native default would close the <dialog> itself; the consumer owns `open` instead.
    event.preventDefault();
    this.dispatchClose('escape');
  };

  private readonly handleDialogClick = (event: MouseEvent): void => {
    if (event.target !== this.dialogEl) {
      return;
    }
    this.dispatchClose('scrim');
  };

  private readonly handleCancelPress = (event: Event): void => {
    // Keep the button's `press` inside the sheet; consumers listen for `close`.
    event.stopPropagation();
    this.dispatchClose('cancel');
  };

  private readonly handleMenuAction = (event: CustomEvent<MenuActionDetail>): void => {
    event.stopPropagation();
    this.menuClosingForAction = true;
    this.dispatchAction(event.detail.id);
  };

  private readonly handleMenuOpenChange = (event: CustomEvent<MenuOpenChangeDetail>): void => {
    event.stopPropagation();
    if (event.detail.open) {
      return;
    }
    if (this.menuClosingForAction) {
      this.menuClosingForAction = false;
      return;
    }
    // <ds-menu> does not distinguish Escape from an outside click; `escape` is the closest of the
    // four reasons for a non-modal, scrim-less, cancel-row-less presentation.
    this.dispatchClose('escape');
  };

  private readonly handleSurfacePointerDown = (event: PointerEvent): void => {
    if ((event.target as HTMLElement).closest('button')) {
      return;
    }
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      return;
    }
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
    this.dragState = { startY: event.clientY, startTime: event.timeStamp };
    surface.style.transition = 'none';
  };

  private readonly handleSurfacePointerMove = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!drag || !surface) {
      return;
    }
    const deltaY = Math.max(0, event.clientY - drag.startY);
    surface.style.transform = `translateY(${deltaY}px)`;
  };

  private readonly handleSurfacePointerUp = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    this.dragState = null;
    if (!drag || !surface) {
      return;
    }

    const deltaY = Math.max(0, event.clientY - drag.startY);
    const elapsed = Math.max(1, event.timeStamp - drag.startTime);
    const velocity = deltaY / elapsed;
    const sheetHeight = surface.getBoundingClientRect().height || 1;
    const pastThreshold = deltaY / sheetHeight > 0.25 || velocity > 0.5;

    surface.style.transition = prefersReducedMotion() ? 'none' : '';
    surface.style.transform = '';

    if (pastThreshold) {
      this.dispatchClose('drag');
    }
  };

  private handleOpen(): void {
    this.closing = false;
    this.openerElement = getDeepActiveElement();
    lockBodyScroll();
    this.dialogEl.showModal();
    this.applyInitialFocus();
  }

  private playExit(): void {
    const finish = (): void => {
      this.dialogEl.close();
      unlockBodyScroll();
      this.restoreFocus();
      this.closing = false;
    };
    if (prefersReducedMotion()) {
      finish();
      return;
    }
    this.closing = true;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      finish();
      return;
    }
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target !== surface || event.propertyName !== 'transform') {
        return;
      }
      surface.removeEventListener('transitionend', handleTransitionEnd);
      finish();
    };
    surface.addEventListener('transitionend', handleTransitionEnd);
  }

  private applyInitialFocus(): void {
    const first = this.navigableActions()[0];
    if (first) {
      this.activeId = first.id;
      void this.focusAction(first.id);
    } else {
      this.cancelButtonEl?.focus();
    }
  }

  private async focusAction(target: 'first' | 'last' | string): Promise<void> {
    const items = this.navigableActions();
    if (items.length === 0) {
      return;
    }
    const id = target === 'first' ? items[0].id : target === 'last' ? items[items.length - 1].id : target;
    this.activeId = id;
    await this.updateComplete;
    this.renderRoot.querySelector<HTMLElement>(`[data-id="${CSS.escape(id)}"]`)?.focus();
  }

  private moveFocus(delta: number): void {
    const items = this.navigableActions();
    if (items.length === 0) {
      return;
    }
    const currentIndex = items.findIndex((action) => action.id === this.activeId);
    let nextIndex = currentIndex + delta;
    if (nextIndex < 0) {
      nextIndex = items.length - 1;
    } else if (nextIndex >= items.length) {
      nextIndex = 0;
    }
    void this.focusAction(items[nextIndex].id);
  }

  private activateActiveAction(): void {
    const action = this.navigableActions().find((entry) => entry.id === this.activeId);
    if (action) {
      this.dispatchAction(action.id);
    }
  }

  private restoreFocus(): void {
    const opener = this.openerElement;
    this.openerElement = null;
    if (opener instanceof HTMLElement && opener.isConnected) {
      opener.focus();
    }
  }

  private dispatchAction(id: string): void {
    this.dispatchEvent(
      new CustomEvent<ActionSheetActionDetail>('action', { detail: { id }, bubbles: true, composed: true }),
    );
  }

  private dispatchClose(reason: ActionSheetCloseReason): void {
    this.dispatchEvent(
      new CustomEvent<ActionSheetCloseDetail>('close', { detail: { reason }, bubbles: true, composed: true }),
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ActionSheetOverridableBinding[]) {
      const hook = HOOKS[binding];
      if (!hook) {
        continue;
      }
      const ref = this.overrides?.[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.actions || this.actions.length === 0) {
      console.warn('<ds-action-sheet> requires at least one action in `actions`.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-action-sheet': DsActionSheet;
  }
}
