// packages/react/src/BottomSheet.tsx
import {
  useEffect,
  useId,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type MouseEvent as ReactMouseEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
  type Ref,
  type SyntheticEvent, type ReactElement,
} from 'react';
import { createPortal } from 'react-dom';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Box } from './Box';
import { Button } from './Button';
import { Dialog } from './Dialog';
import { FocusScope } from './FocusScope';
import { Heading } from './Heading';
import { Icon } from './Icon';
import { Stack } from './Stack';
import './BottomSheet.css';

export type BottomSheetHeight = 'content' | 'half' | 'full';
export type BottomSheetCloseReason = 'escape' | 'close-button' | 'scrim' | 'drag' | 'action';

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type BottomSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'handleHeight'
  | 'handleWidth'
  | 'inset'
  | 'partGap'
  | 'footerGap'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

const OVERRIDE_HOOK: Record<BottomSheetOverridableBinding, string> = {
  scrim: '--ds-bottom-sheet-scrim',
  shadow: '--ds-bottom-sheet-shadow',
  radius: '--ds-bottom-sheet-radius',
  handleHeight: '--ds-bottom-sheet-handle-height',
  handleWidth: '--ds-bottom-sheet-handle-width',
  inset: '--ds-bottom-sheet-inset',
  partGap: '--ds-bottom-sheet-part-gap',
  footerGap: '--ds-bottom-sheet-footer-gap',
  maxWidth: '--ds-bottom-sheet-max-width',
  layer: '--ds-bottom-sheet-layer',
  enter: '--ds-bottom-sheet-enter',
  exit: '--ds-bottom-sheet-exit',
};

function overridesToStyle(overrides: Partial<Record<BottomSheetOverridableBinding, TokenRef | undefined>>): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as BottomSheetOverridableBinding[]) {
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return style as CSSProperties;
}

const COPY = { closeLabel: 'Close' };

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[contenteditable]:not([contenteditable="false"])',
  '[tabindex]:not([tabindex="-1"])',
].join(',');

/* Only declared when the bundler defines it; never assumed. */
declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

/** jsdom (and older browsers) have no `matchMedia`; treat that as "no preference". */
function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function'
    ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
    : false;
}

/**
 * Above `layout.maxWidth.prose` (read from the loaded token stylesheet, never hard-coded) the sheet
 * presents as a centered Dialog instead of rising from the bottom edge.
 */
function useIsWideViewport(): boolean {
  const [isWide, setIsWide] = useState(false);

  useEffect(() => {
    if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') return undefined;
    const breakpoint = getComputedStyle(document.documentElement).getPropertyValue('--layout-max-width-prose').trim();
    if (!breakpoint) return undefined;
    const query = window.matchMedia(`(min-width: ${breakpoint})`);
    const update = () => setIsWide(query.matches);
    update();
    query.addEventListener('change', update);
    return () => query.removeEventListener('change', update);
  }, []);

  return isWide;
}

export interface BottomSheetProps
  extends Omit<ComponentPropsWithoutRef<'dialog'>, 'children' | 'title' | 'onCancel' | 'onClose' | 'open'> {
  /** Controlled visibility, as in Dialog. */
  open: boolean;
  /** The sheet's title and accessible name. May be visually hidden with `hideHeading` when the content is self-explanatory (a share sheet). */
  heading: string;
  /** Keep the heading for assistive technology but do not render it (forwarded to Dialog above the breakpoint). The accessible name is required regardless; visually hidden is fine, absent is not. */
  hideHeading?: boolean | undefined;
  /** The body. Scrolls inside the sheet when taller than the sheet's height. */
  children: ReactNode;
  /** Action row, pinned to the bottom of the sheet above the safe area. */
  footer?: ReactNode;
  /** `content` sizes to the body up to 90% of the viewport; `half` is a fixed half-height; `full` is a near-full-screen sheet with the top gutter visible so the scrim still shows. */
  height?: BottomSheetHeight | undefined;
  /** Escape, the close button, a scrim tap and the drag gesture all request close. When false, only the footer actions close it; Escape still reports. */
  dismissible?: boolean | undefined;
  /**
   * Drag the handle (or the header) downward to dismiss: release past 25% of the sheet height, or
   * faster than 1.5 px/ms, dismisses; otherwise the sheet springs back. Purely additive: the close
   * button and Escape always exist.
   */
  dragToDismiss?: boolean | undefined;
  /** Requested close with reason: `escape`, `close-button`, `scrim`, `drag`, or `action`. */
  onClose?: ((reason: BottomSheetCloseReason) => void) | undefined;
  /** The user dragged the sheet past the dismiss threshold. Fired before `onClose` with reason drag; provided so analytics can distinguish gestures. */
  onDragDismiss?: (() => void) | undefined;
  /** Portal target for the sheet's DOM node. Defaults to `document.body`. Only used below the wide-viewport breakpoint; the Dialog presentation manages its own container. */
  container?: HTMLElement | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. Only applied to the bottom-edge presentation; above the wide breakpoint the sheet renders as Dialog and uses Dialog's own overrides contract. */
  overrides?: Partial<Record<BottomSheetOverridableBinding, TokenRef | undefined>> | undefined;
}

/**
 * BottomSheet — Design Schema, category: overlay.
 *
 * When to use:
 * Use a BottomSheet on phones for a task or a set of choices that would otherwise be a Dialog:
 * filters, a form of a few fields, details of a selected item, a picker with many options. Use
 * `height: content` by default; `full` for a task that needs the whole screen but should still feel
 * dismissable; `half` for a browsable list where seeing the page behind matters (a map with
 * results). For a flat list of actions, ActionSheet is the lighter component.
 */
export const BottomSheet = function BottomSheet({
  ref,
  open,
  heading,
  hideHeading = false,
  children,
  footer,
  height = 'content',
  dismissible = true,
  dragToDismiss = true,
  onClose,
  onDragDismiss,
  container,
  overrides,
  className,
  style,
  ...rest
}: BottomSheetProps & { ref?: Ref<HTMLDialogElement> | undefined }): ReactElement | null {
  const isWide = useIsWideViewport();

  const generatedId = useId();
  const headingId = `ds-bottom-sheet${generatedId}-heading`;

  const dialogRef = useRef<HTMLDialogElement | null>(null);
  useImperativeHandle(ref, () => dialogRef.current as HTMLDialogElement, []);

  const surfaceRef = useRef<HTMLDivElement | null>(null);
  const bodyRef = useRef<HTMLElement | null>(null);
  const headingRef = useRef<HTMLHeadingElement | null>(null);
  const closeButtonRef = useRef<HTMLButtonElement | null>(null);
  const dragRef = useRef<{ startY: number; startTime: number } | null>(null);

  // Mounted while open, and while the exit transition finishes after `open` goes false.
  const [present, setPresent] = useState(open);
  // Drives the entered/exited CSS state; toggled a frame after mount so the enter transition runs.
  const [visible, setVisible] = useState(false);

  if (isDev && !heading) {
    console.warn('BottomSheet: `heading` is required and becomes the accessible name; it must not be empty.');
  }

  useEffect(() => {
    if (open) setPresent(true);
  }, [open]);

  // Mount: open the native dialog, move focus to the first control, then reveal on the next frame.
  useLayoutEffect(() => {
    if (!present || isWide) return undefined;
    const dialog = dialogRef.current;
    if (!dialog) return undefined;
    if (!dialog.open) {
      // showModal() also reflects `open`, natively; the assignment is the fallback for engines
      // (jsdom, under test) that implement the `open` IDL attribute but not showModal() itself.
      dialog.showModal?.();
      dialog.open = true;
    }

    const first = bodyRef.current?.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
    (first ?? closeButtonRef.current ?? headingRef.current ?? dialog).focus();

    if (prefersReducedMotion()) {
      setVisible(true);
      return undefined;
    }

    const frame = requestAnimationFrame(() => setVisible(true));
    return () => cancelAnimationFrame(frame);
  }, [present, isWide]);

  // Exit: hide, then unmount and close() once the transition finishes (immediately under reduced motion).
  useEffect(() => {
    if (open || !present || isWide) return undefined;
    setVisible(false);
    const dialog = dialogRef.current;
    const finish = () => {
      setPresent(false);
      dialog?.close?.();
      if (dialog) dialog.open = false;
    };
    if (prefersReducedMotion()) {
      finish();
      return undefined;
    }
    const surface = surfaceRef.current;
    const handleExited = (event: TransitionEvent) => {
      if (event.target !== surface || event.propertyName !== 'transform') return;
      finish();
    };
    surface?.addEventListener('transitionend', handleExited);
    return () => surface?.removeEventListener('transitionend', handleExited);
  }, [open, present, isWide]);

  // Body scroll lock while the sheet is present, restored on close or unmount.
  useEffect(() => {
    if (!present || isWide) return undefined;
    document.documentElement.classList.add('ds-bottom-sheet-lock-scroll');
    return () => document.documentElement.classList.remove('ds-bottom-sheet-lock-scroll');
  }, [present, isWide]);

  const requestClose = (reason: BottomSheetCloseReason) => {
    if (reason !== 'escape' && !dismissible) return;
    onClose?.(reason);
  };

  const handleCancel = (event: SyntheticEvent<HTMLDialogElement>) => {
    // The consumer owns `open`; the sheet never closes itself, even when it is not dismissible.
    event.preventDefault();
    requestClose('escape');
  };

  const handleScrimClick = (event: ReactMouseEvent<HTMLDialogElement>) => {
    if (event.target !== dialogRef.current) return;
    requestClose('scrim');
  };

  const handleCloseButtonClick = () => requestClose('close-button');

  // Drag: Pointer Events on the header (which carries the decorative handle), tracking downward
  // distance only. Released past 25% of the sheet's height or a fast flick dismisses; otherwise the
  // sheet springs back on the same transition the open/close states use.
  const handleHeaderPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!dragToDismiss) return;
    if ((event.target as HTMLElement).closest('button')) return;
    const surface = surfaceRef.current;
    if (!surface) return;
    event.currentTarget.setPointerCapture(event.pointerId);
    dragRef.current = { startY: event.clientY, startTime: event.timeStamp };
    surface.style.transition = 'none';
  };

  const handleHeaderPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    const surface = surfaceRef.current;
    if (!drag || !surface) return;
    const deltaY = Math.max(0, event.clientY - drag.startY);
    surface.style.transform = `translateY(${deltaY}px)`;
  };

  const finishDrag = (event: ReactPointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    const surface = surfaceRef.current;
    dragRef.current = null;
    if (!drag || !surface) return;

    const deltaY = Math.max(0, event.clientY - drag.startY);
    const elapsed = Math.max(1, event.timeStamp - drag.startTime);
    const velocity = deltaY / elapsed;
    const sheetHeight = surface.getBoundingClientRect().height || 1;
    const pastThreshold = deltaY / sheetHeight > 0.25 || velocity > 1.5;

    surface.style.transition = prefersReducedMotion() ? 'none' : '';
    surface.style.transform = '';

    if (pastThreshold && dismissible) {
      onDragDismiss?.();
      requestClose('drag');
    }
  };

  const overrideStyle = overrides ? overridesToStyle(overrides) : undefined;
  const bodyOverrides = overrides?.inset ? { paddingBlock: overrides.inset, paddingInline: overrides.inset } : undefined;

  if (isWide) {
    return (
      <Dialog
        {...rest}
        ref={ref}
        open={open}
        heading={heading}
        hideHeading={hideHeading}
        footer={footer}
        size="md"
        dismissible={dismissible}
        onClose={onClose}
        container={container}
        className={className}
        style={style}
      >
        {children}
      </Dialog>
    );
  }

  if (!present) return null;

  const classes = [
    'ds-bottom-sheet',
    `ds-bottom-sheet--height-${height}`,
    visible ? 'ds-bottom-sheet--visible' : null,
    className ?? null,
  ]
    .filter(Boolean)
    .join(' ');

  const mergedStyle = overrideStyle || style ? { ...overrideStyle, ...style } : undefined;

  const headingClasses = ['ds-bottom-sheet__heading', hideHeading ? 'ds-bottom-sheet__visually-hidden' : null]
    .filter(Boolean)
    .join(' ');

  const node = (
    <dialog
      {...rest}
      ref={dialogRef}
      data-ds="BottomSheet"
      className={classes}
      style={mergedStyle}
      aria-modal="true"
      aria-labelledby={headingId}
      onCancel={handleCancel}
      onClick={handleScrimClick}
    >
      <FocusScope trapped autoFocus="none" restoreFocus data-part="focusScope">
        <div className="ds-bottom-sheet__surface" ref={surfaceRef} data-part="surface">
          <div
            className="ds-bottom-sheet__header"
            data-part="header"
            onPointerDown={handleHeaderPointerDown}
            onPointerMove={handleHeaderPointerMove}
            onPointerUp={finishDrag}
            onPointerCancel={finishDrag}
          >
            <span className="ds-bottom-sheet__handle" data-part="handle" aria-hidden="true" />
            <div className="ds-bottom-sheet__heading-row">
              <Heading level={2} id={headingId} ref={headingRef} tabIndex={-1} data-part="heading" className={headingClasses}>
                {heading}
              </Heading>
              <Button
                ref={closeButtonRef}
                variant="ghost"
                size="md"
                iconOnly
                label={COPY.closeLabel}
                data-part="closeButton"
                className="ds-bottom-sheet__close"
                onClick={handleCloseButtonClick}
                leadingIcon={<Icon name="close" inline />}
              />
            </div>
          </div>
          <Box element="div" inset="lg" overrides={bodyOverrides} data-part="body" className="ds-bottom-sheet__body" ref={bodyRef}>
            {children}
          </Box>
          {footer !== undefined ? (
            <div className="ds-bottom-sheet__footer" data-part="footer">
              <Stack direction="horizontal" gap="tight" justify="end">
                {footer}
              </Stack>
            </div>
          ) : null}
        </div>
      </FocusScope>
    </dialog>
  );

  return createPortal(node, container ?? document.body);
};

// packages/lit/src/BottomSheet.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Heading.js';
import './Button.js';
import './Icon.js';
import './Box.js';
import './Stack.js';
import './FocusScope.js';
import './Dialog.js';

export type BottomSheetHeight = 'content' | 'half' | 'full';
export type BottomSheetCloseReason = 'escape' | 'close-button' | 'scrim' | 'drag' | 'action';

/** Detail carried by the `close` CustomEvent. */
export interface BottomSheetCloseDetail {
  reason: BottomSheetCloseReason;
}

/** Detail carried by the `drag-dismiss` CustomEvent (none). */
export type BottomSheetDragDismissDetail = void;

/** Overridable style hooks; see the `overrides` property. `surface`, `handle`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type BottomSheetOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'radius'
  | 'handleHeight'
  | 'handleWidth'
  | 'inset'
  | 'partGap'
  | 'footerGap'
  | 'maxWidth'
  | 'layer'
  | 'enter'
  | 'exit';

const HOOKS: Record<BottomSheetOverridableBinding, string> = {
  scrim: '--ds-bottom-sheet-scrim',
  shadow: '--ds-bottom-sheet-shadow',
  radius: '--ds-bottom-sheet-radius',
  handleHeight: '--ds-bottom-sheet-handle-height',
  handleWidth: '--ds-bottom-sheet-handle-width',
  inset: '--ds-bottom-sheet-inset',
  partGap: '--ds-bottom-sheet-part-gap',
  footerGap: '--ds-bottom-sheet-footer-gap',
  maxWidth: '--ds-bottom-sheet-max-width',
  layer: '--ds-bottom-sheet-layer',
  enter: '--ds-bottom-sheet-enter',
  exit: '--ds-bottom-sheet-exit',
};

/** copy.closeLabel */
const COPY_CLOSE_LABEL = 'Close';

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
  'ds-button',
  'ds-link',
  'ds-input',
  'ds-checkbox',
  'ds-switch',
  'ds-radio-group',
  'ds-disclosure',
].join(',');

function findFirstFocusable(root: Element): HTMLElement | null {
  if (root instanceof HTMLElement && root.matches(FOCUSABLE_SELECTOR)) {
    return root;
  }
  return root.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
}

/** How many `<ds-bottom-sheet>` instances (in their bottom-edge presentation) currently hold the body-scroll lock. */
let openSheetCount = 0;

function lockBodyScroll(): void {
  openSheetCount += 1;
  if (openSheetCount === 1) {
    document.documentElement.style.overflow = 'hidden';
  }
}

function unlockBodyScroll(): void {
  openSheetCount = Math.max(0, openSheetCount - 1);
  if (openSheetCount === 0) {
    document.documentElement.style.removeProperty('overflow');
  }
}

function getDeepActiveElement(): Element | null {
  let active = document.activeElement;
  while (active?.shadowRoot?.activeElement) {
    active = active.shadowRoot.activeElement;
  }
  return active;
}

function prefersReducedMotion(): boolean {
  return matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * `<ds-bottom-sheet>` — BottomSheet (category: overlay, APG pattern: dialog-modal).
 *
 * The phone's dialog: rises from the bottom edge behind a scrim, and above
 * the `maxWidth` breakpoint renders `<ds-dialog size="md">` instead — a
 * `matchMedia` listener on the resolved `layout.maxWidth.prose` token decides
 * which, so consumers write the screen once. Below the breakpoint a shadow
 * `<dialog>` is opened with `showModal()` for the top layer, background
 * inertness and `::backdrop` scrim; `<ds-focus-scope trapped>` wraps the
 * header, body and footer. A downward drag on the header (Pointer Events,
 * `setPointerCapture`) past a distance or velocity threshold fires
 * `drag-dismiss` then `close` with reason `drag`; it is purely additive, the
 * close button and Escape always work.
 *
 * ## When to use
 *
 * Use a BottomSheet on phones for a task or a set of choices that would
 * otherwise be a Dialog: filters, a form of a few fields, details of a
 * selected item, a picker with many options. Use `height="content"` by
 * default; `full` for a task that needs the whole screen but should still
 * feel dismissable; `half` for a browsable list where seeing the page behind
 * matters (a map with results). For a flat list of actions, ActionSheet is
 * the lighter component.
 *
 * ## When not to use
 *
 * Not as a menu (ActionSheet or Menu), a persistent panel (a bottom Landmark
 * region), or content the user must read at length (a page). Never stack
 * sheets, and never rely on the drag gesture as the only way to dismiss.
 *
 * @fires close - Requests close, with `{ reason: 'escape' | 'close-button' | 'scrim' | 'drag' | 'action' }`.
 *   The consumer sets `open` to false (or not).
 * @fires drag-dismiss - Fired before `close` (reason `drag`) when a drag gesture crosses the dismiss threshold.
 * @slot - The body. Scrolls inside the sheet when taller than the sheet's height.
 * @slot footer - Action row, pinned above the safe area.
 * @csspart surface - The padded, bordered surface (anatomy: surface).
 * @csspart focus-scope - The focus-trapping wrapper (anatomy: focusScope).
 * @csspart handle - The decorative drag handle (anatomy: handle).
 * @csspart header - The header row (anatomy: header).
 * @csspart title - The `<ds-heading>` (anatomy: title).
 * @csspart body - The body wrapper (anatomy: body).
 * @csspart footer - The footer row (anatomy: footer).
 * @csspart close-button - The close `<ds-button>` (anatomy: closeButton).
 */
@customElement('ds-bottom-sheet')
export class DsBottomSheet extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      --ds-bottom-sheet-scrim: var(--color-overlay-scrim);
      --ds-bottom-sheet-shadow: var(--shadow-overlay);
      --ds-bottom-sheet-radius: var(--radius-lg);
      --ds-bottom-sheet-handle-height: var(--space-1);
      --ds-bottom-sheet-handle-width: var(--space-10);
      --ds-bottom-sheet-inset: var(--layout-inset-lg);
      --ds-bottom-sheet-part-gap: var(--layout-gap-loose);
      --ds-bottom-sheet-footer-gap: var(--layout-gap-tight);
      --ds-bottom-sheet-max-width: var(--layout-max-width-prose);
      --ds-bottom-sheet-layer: var(--layer-sheet);
      --ds-bottom-sheet-enter: var(--motion-duration-base);
      --ds-bottom-sheet-exit: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    dialog {
      box-sizing: border-box;
      position: fixed;
      inset-block-end: 0;
      inset-inline: 0;
      margin: 0;
      padding: 0;
      border: 0;
      inline-size: 100%;
      max-inline-size: none;
      max-block-size: 90dvh;
      background: transparent;
      color: inherit;
      z-index: var(--ds-bottom-sheet-layer);
    }

    /* height: content (default) sizes to the body up to the dialog's own 90dvh max-block-size; half
       and full set an exact block-size instead, so the 90dvh cap must not also apply to them. */
    :host([height='half']) dialog {
      max-block-size: none;
      block-size: 50dvh;
    }
    :host([height='full']) dialog {
      max-block-size: none;
      block-size: calc(100dvh - var(--layout-gutter));
    }

    /* scrim: color.overlay.scrim */
    dialog::backdrop {
      background: var(--ds-bottom-sheet-scrim);
      transition: opacity var(--ds-bottom-sheet-enter) var(--motion-easing-standard);
    }

    @starting-style {
      dialog[open]::backdrop {
        opacity: 0;
      }
    }

    .surface {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      block-size: 100%;
      gap: var(--ds-bottom-sheet-part-gap);
      font-family: var(--font-family-body);
      /* surface: color.overlay.surface, locked — no override hook */
      background: var(--color-overlay-surface);
      /* radius: top corners only on phones; ds-dialog rounds all corners for the wide presentation */
      border-start-start-radius: var(--ds-bottom-sheet-radius);
      border-start-end-radius: var(--ds-bottom-sheet-radius);
      box-shadow: var(--ds-bottom-sheet-shadow);
      overflow: hidden;
      padding-block-end: env(safe-area-inset-bottom);
      transform: translateY(0);
      transition: transform var(--ds-bottom-sheet-enter) var(--motion-easing-standard);
    }

    .surface.closing {
      transform: translateY(100%);
      transition-duration: var(--ds-bottom-sheet-exit);
      transition-timing-function: var(--motion-easing-exit);
    }

    @starting-style {
      dialog[open] .surface {
        transform: translateY(100%);
      }
    }

    @media (prefers-reduced-motion: reduce) {
      dialog::backdrop,
      .surface {
        transition: none;
      }
    }

    .header {
      display: flex;
      flex-direction: column;
      gap: var(--layout-gap-tight);
      padding-inline: var(--ds-bottom-sheet-inset);
      padding-block-start: var(--layout-gap-tight);
      flex: 0 0 auto;
      touch-action: none;
    }

    /* handle: color.foreground.muted, locked — a 4×36 decorative pill, aria-hidden and not focusable */
    .handle {
      align-self: center;
      inline-size: var(--ds-bottom-sheet-handle-width);
      block-size: var(--ds-bottom-sheet-handle-height);
      border-radius: var(--radius-full);
      background: var(--color-foreground-muted);
    }

    .heading-row {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: var(--layout-gap-normal);
      min-inline-size: 0;
    }

    .title {
      min-inline-size: 0;
    }

    /* hideTitle: kept for the accessible name, removed from the visual layout. */
    .title--hidden {
      /* literal-ok: standard visually-hidden clip pattern, exempt from token-only rule */
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }

    #heading:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
      border-radius: var(--radius-sm);
    }

    .close {
      flex: none;
    }

    .body {
      flex: 1 1 auto;
      min-block-size: 0;
      overflow-y: auto;
    }
  `;

  /** Controlled visibility, as in Dialog. */
  @property({ type: Boolean, reflect: true }) open = false;

  /**
   * The sheet's title and accessible name. Named `heading`, not `title` —
   * `HTMLElement` already defines `title` as the tooltip attribute (see
   * Dialog and AlertDialog).
   */
  @property() heading!: string;

  /** Keep the title for assistive technology but do not render it. The accessible name is required regardless. */
  @property({ type: Boolean, attribute: 'hide-title' }) hideTitle = false;

  /** `content` sizes to the body up to 90% of the viewport; `half` is a fixed half-height; `full` is near-full-screen. */
  @property({ reflect: true }) height: BottomSheetHeight = 'content';

  /** Escape, the close button, a scrim tap and the drag gesture all request close. Escape still reports when false. */
  @property({ type: Boolean, reflect: true }) dismissible = true;

  /** Drag the handle (or header) downward to dismiss. Purely additive: the close button and Escape always exist. */
  @property({ type: Boolean, reflect: true }) draggable = true;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings (surface, handle, focusRing, focusRingWidth) are ignored. Only applied below the wide-viewport breakpoint; above it the sheet renders as Dialog and uses Dialog's own overrides contract. */
  @property({ attribute: false }) overrides?: Partial<Record<BottomSheetOverridableBinding, TokenRef>>;

  /** Above `layout.maxWidth.prose` the sheet renders as a centered `<ds-dialog size="md">` instead. */
  @state() private isWide = false;

  /** Whether the exit transition is playing (kept open a beat past the `open` flip so it can animate out). */
  @state() private closing = false;

  @query('dialog') private readonly dialogEl!: HTMLDialogElement;
  @query('#heading') private readonly headingEl!: HTMLElement;
  @query('.close') private readonly closeButtonEl!: HTMLElement;

  private openerElement: Element | null = null;
  private closingProgrammatically = false;
  private suppressCloseSync = false;
  private wideQuery: MediaQueryList | null = null;
  private dragState: { startY: number; startTime: number } | null = null;

  private readonly handleWideChange = (event: MediaQueryListEvent): void => {
    this.isWide = event.matches;
  };

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'BottomSheet');
    const breakpoint = getComputedStyle(document.documentElement).getPropertyValue('--layout-max-width-prose').trim();
    if (breakpoint) {
      this.wideQuery = matchMedia(`(min-width: ${breakpoint})`);
      this.isWide = this.wideQuery.matches;
      this.wideQuery.addEventListener('change', this.handleWideChange);
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.wideQuery?.removeEventListener('change', this.handleWideChange);
    if (!this.isWide && this.dialogEl?.open) {
      unlockBodyScroll();
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (!this.isWide && changed.has('open')) {
      if (this.open) {
        this.handleOpen();
      } else if (changed.get('open') as boolean) {
        if (this.suppressCloseSync) {
          this.suppressCloseSync = false;
        } else {
          this.playExit();
        }
      }
    }
    this.warnInDev();
  }

  protected override render() {
    if (this.isWide) {
      return this.renderAsDialog();
    }
    return this.renderAsSheet();
  }

  private renderAsDialog() {
    return html`
      <ds-dialog ?open=${this.open} heading=${this.heading} size="md" ?dismissible=${this.dismissible}>
        <slot></slot>
        <slot name="footer" slot="footer"></slot>
      </ds-dialog>
    `;
  }

  private renderAsSheet() {
    const hasFooter = this.querySelector('[slot="footer"]') !== null;
    const titleClasses = classMap({ title: true, 'title--hidden': this.hideTitle });

    return html`
      <dialog
        aria-modal="true"
        aria-labelledby="heading"
        @cancel=${this.handleCancel}
        @close=${this.handleNativeClose}
        @click=${this.handleDialogClick}
      >
        <div class="surface${this.closing ? ' closing' : ''}" part="surface">
          <ds-focus-scope
            part="focus-scope"
            trapped
            ?active=${this.open}
            auto-focus="none"
            ?restore-focus=${false}
            style="display: flex; flex-direction: column; gap: var(--ds-bottom-sheet-part-gap)"
          >
            <div
              class="header"
              part="header"
              @pointerdown=${this.handleHeaderPointerDown}
              @pointermove=${this.handleHeaderPointerMove}
              @pointerup=${this.handleHeaderPointerUp}
              @pointercancel=${this.handleHeaderPointerUp}
            >
              <span class="handle" part="handle" aria-hidden="true"></span>
              <div class="heading-row">
                <ds-heading id="heading" part="title" class=${titleClasses} level="2" size="lg" tabindex="-1"
                  >${this.heading}</ds-heading
                >
                <ds-button
                  class="close"
                  part="close-button"
                  variant="ghost"
                  size="md"
                  icon-only
                  label=${COPY_CLOSE_LABEL}
                  @press=${this.handleCloseButtonPress}
                >
                  <ds-icon slot="leading-icon" name="close"></ds-icon>
                </ds-button>
              </div>
            </div>
            <ds-box class="body" part="body" inset="lg" .overrides=${this.bodyOverrides()}>
              <slot></slot>
            </ds-box>
            ${hasFooter
              ? html`
                  <ds-stack part="footer" direction="horizontal" justify="end" style="gap: var(--ds-bottom-sheet-footer-gap)">
                    <slot name="footer"></slot>
                  </ds-stack>
                `
              : nothing}
          </ds-focus-scope>
        </div>
      </dialog>
    `;
  }

  private bodyOverrides() {
    const inset = this.overrides?.inset;
    return inset ? { paddingBlock: inset, paddingInline: inset } : undefined;
  }

  private readonly handleCancel = (event: Event): void => {
    // The native default would close the <dialog> itself; the consumer owns `open` instead.
    event.preventDefault();
    this.dispatchClose('escape');
  };

  private readonly handleDialogClick = (event: MouseEvent): void => {
    if (!this.dismissible || event.target !== this.dialogEl) {
      return;
    }
    this.dispatchClose('scrim');
  };

  private readonly handleCloseButtonPress = (event: Event): void => {
    // Keep the button's `press` inside the sheet; consumers listen for `close`.
    event.stopPropagation();
    if (!this.dismissible) {
      return;
    }
    this.dispatchClose('close-button');
  };

  private readonly handleNativeClose = (): void => {
    if (this.closingProgrammatically) {
      this.closingProgrammatically = false;
      return;
    }
    unlockBodyScroll();
    this.restoreFocus();
    this.suppressCloseSync = true;
    this.open = false;
    this.dispatchClose('action');
  };

  private readonly handleHeaderPointerDown = (event: PointerEvent): void => {
    if (!this.draggable) {
      return;
    }
    if ((event.target as HTMLElement).closest('.close')) {
      return;
    }
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      return;
    }
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
    this.dragState = { startY: event.clientY, startTime: event.timeStamp };
    surface.style.transition = 'none';
  };

  private readonly handleHeaderPointerMove = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!drag || !surface) {
      return;
    }
    const deltaY = Math.max(0, event.clientY - drag.startY);
    surface.style.transform = `translateY(${deltaY}px)`;
  };

  private readonly handleHeaderPointerUp = (event: PointerEvent): void => {
    const drag = this.dragState;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    this.dragState = null;
    if (!drag || !surface) {
      return;
    }

    const deltaY = Math.max(0, event.clientY - drag.startY);
    const elapsed = Math.max(1, event.timeStamp - drag.startTime);
    const velocity = deltaY / elapsed;
    const sheetHeight = surface.getBoundingClientRect().height || 1;
    const pastThreshold = deltaY / sheetHeight > 0.25 || velocity > 0.5;

    surface.style.transition = prefersReducedMotion() ? 'none' : '';
    surface.style.transform = '';

    if (pastThreshold && this.dismissible) {
      this.dispatchEvent(
        new CustomEvent<BottomSheetDragDismissDetail>('drag-dismiss', { bubbles: true, composed: true }),
      );
      this.dispatchClose('drag');
    }
  };

  private handleOpen(): void {
    this.closing = false;
    this.openerElement = getDeepActiveElement();
    lockBodyScroll();
    this.dialogEl.showModal();
    this.applyInitialFocus();
  }

  private playExit(): void {
    const finish = (): void => {
      this.closingProgrammatically = true;
      this.dialogEl.close();
      unlockBodyScroll();
      this.restoreFocus();
      this.closing = false;
    };
    if (prefersReducedMotion()) {
      finish();
      return;
    }
    this.closing = true;
    const surface = this.renderRoot.querySelector<HTMLElement>('.surface');
    if (!surface) {
      finish();
      return;
    }
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target !== surface || event.propertyName !== 'transform') {
        return;
      }
      surface.removeEventListener('transitionend', handleTransitionEnd);
      finish();
    };
    surface.addEventListener('transitionend', handleTransitionEnd);
  }

  private applyInitialFocus(): void {
    const target = this.findFirstBodyFocusable() ?? this.closeButtonEl ?? this.headingEl;
    target?.focus();
  }

  private findFirstBodyFocusable(): HTMLElement | null {
    const slot = this.renderRoot.querySelector<HTMLSlotElement>('slot:not([name])');
    if (!slot) {
      return null;
    }
    for (const element of slot.assignedElements({ flatten: true })) {
      const found = findFirstFocusable(element);
      if (found) {
        return found;
      }
    }
    return null;
  }

  private restoreFocus(): void {
    const opener = this.openerElement;
    this.openerElement = null;
    if (opener instanceof HTMLElement && opener.isConnected) {
      opener.focus();
    }
  }

  private dispatchClose(reason: BottomSheetCloseReason): void {
    this.dispatchEvent(
      new CustomEvent<BottomSheetCloseDetail>('close', { detail: { reason }, bubbles: true, composed: true }),
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as BottomSheetOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.heading) {
      console.warn('<ds-bottom-sheet> requires a `heading`, used as the accessible name.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-bottom-sheet': DsBottomSheet;
  }
}
