// packages/rn/src/Button.tsx
import * as React from 'react';
import { Animated, Easing, Platform, Pressable, Text as RNText, View } from 'react-native';
import type { Insets, LayoutChangeEvent, PressableProps, TextStyle, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { useFormContext } from './FormContext';
import { toEasing, toFontWeight, useReducedMotion, useTheme } from './theme';
import type { Tokens } from './theme';
import { trackPress } from './custom/analytics';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonType = 'button' | 'submit';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type ButtonOverridableBinding =
  | 'iconGap'
  | 'paddingInline'
  | 'paddingBlock'
  | 'radius'
  | 'fontFamily'
  | 'fontWeight'
  | 'fontSize'
  | 'inverseBackgroundHover'
  | 'inverseHoverOpacity'
  | 'disabledOpacity'
  | 'transition'
  | 'loadingSpin'
  | 'spinnerSize';

export interface ButtonProps {
  /** The button's text. Also its accessible name. */
  label: string;
  /** Visual emphasis. One primary button per view. */
  variant?: ButtonVariant | undefined;
  /** Controls padding and font size. Touch targets never drop below the minimum regardless of size. */
  size?: ButtonSize | undefined;
  /** `submit` submits the enclosing Form. Everything else is `button`. */
  type?: ButtonType | undefined;
  /**
   * Set by a parent that the button discloses (Menu, Popover, SidePanel, Disclosure):
   * reflected to `accessibilityState.expanded`. `undefined` (the default) means this
   * button does not disclose anything, so `expanded` is omitted from the state object
   * rather than sent as `false`. Consumers rarely set it directly.
   */
  expanded?: boolean | undefined;
  /** Prevents activation. The button stays in the accessibility tree and is announced as disabled. */
  disabled?: boolean | undefined;
  /** Icon before the label. Decorative — hidden from assistive technology; the label carries the meaning. */
  leadingIcon?: React.ReactNode;
  /** Icon after the label. Decorative, like `leadingIcon`. */
  trailingIcon?: React.ReactNode;
  /**
   * Hides the visible label and shows only `leadingIcon`; `trailingIcon` is not rendered
   * either. `label` is still required and becomes the accessible name. Padding becomes equal
   * on all sides: paddingInline takes the resolved paddingBlock (`space.sm`), so a
   * `paddingInline` override has no effect while `iconOnly`.
   */
  iconOnly?: boolean | undefined;
  /**
   * Shows a ring spinner in the leading icon slot (whether or not `leadingIcon` is set;
   * for `iconOnly` it replaces the sole glyph), hides `trailingIcon`, keeps the label
   * visible, and blocks repeat activation while an action is pending. `copy.loading` is
   * announced as the accessibility value beside `busy`, never as part of the name.
   */
  loading?: boolean | undefined;
  /**
   * The button sits on an inverse surface (Toast, tooltip-like panels). Only `ghost`
   * changes its fill there: its text switches to `color.inverse.link` and its pressed
   * fill to `color.inverse.foreground` at `opacity.disabled × 0.25`. Every variant's
   * focus ring switches to `color.inverse.focus`, since that ring must read against the
   * inverse surface regardless of the button's own fill.
   */
  inverse?: boolean | undefined;
  /**
   * Overrides the accessible name when it must say more than the visible label ("Sort
   * by Amount, ascending" on a header that shows "Amount"). The name must contain the
   * visible label (WCAG 2.5.3 label-in-name); starting with it is preferred. Maps to
   * `accessibilityLabel`.
   */
  accessibleName?: string | undefined;
  /**
   * Text used for this button when a Toolbar collapses it into its overflow Menu. Not
   * rendered by Button itself — read by the collapsing parent.
   */
  overflowLabel?: string | undefined;
  /** An event name sent to analytics when the button is pressed. Omit for no tracking. */
  track?: string | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<ButtonOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root `Pressable`, so a parent can measure or focus the button. */
  ref?: React.Ref<ViewInstance> | undefined;
  /** Supplementary description, forwarded verbatim to the root; Tooltip sets it when it describes the button. */
  accessibilityHint?: string | undefined;
  /** Set by a parent (Tooltip, when its content *is* the name) to replace the name the label would give. `accessibleName` still wins. */
  accessibilityLabel?: string | undefined;
  /** Fired when the button is activated by touch, keyboard, or assistive technology. */
  onPress?: (() => void) | undefined;
  /** Fired after `onPress` with the `track` name and the button's label, only when `track` is set. */
  onTrack?: ((name: string, label: string) => void) | undefined;
  /** Forwarded to the root so Tooltip can attach to the button; the button's own pressed state is kept alongside. */
  onPressOut?: PressableProps['onPressOut'];
  /** Forwarded to the root so Tooltip can open on long press. */
  onLongPress?: PressableProps['onLongPress'];
  /** Forwarded to the root (react-native-web pointer only). */
  onHoverIn?: PressableProps['onHoverIn'];
  /** Forwarded to the root (react-native-web pointer only). */
  onHoverOut?: PressableProps['onHoverOut'];
  /** Forwarded to the root; the button's own focus-ring state is kept alongside. */
  onFocus?: PressableProps['onFocus'];
  /** Forwarded to the root; the button's own focus-ring state is kept alongside. */
  onBlur?: PressableProps['onBlur'];
}

/** The component's user-facing strings, from the doc's `copy` block. */
const COPY = { loading: 'Loading' } as const;

const VARIANT_TOKENS = {
  primary: {
    background: 'colorActionPrimaryBackground',
    backgroundHover: 'colorActionPrimaryBackgroundHover',
    foreground: 'colorActionPrimaryForeground',
  },
  secondary: {
    background: 'colorActionSecondaryBackground',
    backgroundHover: 'colorActionSecondaryBackgroundHover',
    foreground: 'colorActionSecondaryForeground',
  },
  ghost: {
    background: 'colorActionGhostBackground',
    backgroundHover: 'colorActionGhostBackgroundHover',
    foreground: 'colorActionGhostForeground',
  },
  danger: {
    background: 'colorActionDangerBackground',
    backgroundHover: 'colorActionDangerBackgroundHover',
    foreground: 'colorActionDangerForeground',
  },
} as const satisfies Record<ButtonVariant, Record<'background' | 'backgroundHover' | 'foreground', keyof Tokens>>;

const PADDING_INLINE_TOKEN = {
  sm: 'spaceSm',
  md: 'spaceMd',
  lg: 'spaceLg',
} as const satisfies Record<ButtonSize, keyof Tokens>;

const FONT_SIZE_TOKEN = {
  sm: 'fontSizeSm',
  md: 'fontSizeMd',
  lg: 'fontSizeLg',
} as const satisfies Record<ButtonSize, keyof Tokens>;

/** The DOM element react-native-web renders for the root; this package has no DOM lib. */
type WebElement = { setAttribute(name: string, value: string): void; removeAttribute(name: string): void };

/** `inverseHoverOpacity` is `opacity.disabled` times this factor (the binding's `computed`). */
const INVERSE_HOVER_OPACITY_FACTOR = 0.25; // literal-ok: the doc's computed multiplier on a token

/**
 * `color` at `alpha`. The doc's inverse ghost fill is a mix of a token with the surface;
 * web and Lit write it as `color-mix`, and native has no such function, so the resolved
 * token is re-emitted with an alpha channel. Anything that is not a `#rgb`/`#rrggbb`
 * token (a named color, an already-transparent value) is returned untouched.
 */
function withAlpha(color: string, alpha: number): string {
  const hex = color.startsWith('#') ? color.slice(1) : '';
  const full = hex.length === 3 ? `${hex[0]!}${hex[0]!}${hex[1]!}${hex[1]!}${hex[2]!}${hex[2]!}` : hex;
  if (full.length !== 6 || !/^[0-9a-fA-F]{6}$/u.test(full)) {
    return color;
  }
  const channel = (at: number): number => Number.parseInt(full.slice(at, at + 2), 16);
  return `rgba(${channel(0)}, ${channel(2)}, ${channel(4)}, ${alpha})`; // literal-ok: an alpha of a resolved token, not a new color
}

/**
 * Button — lets people take an action with a single tap.
 *
 * When to use: Use a Button when the user needs to **do something**: submit, save,
 * confirm, open, add, delete. The label should be a verb or verb phrase that
 * describes the outcome ("Save changes", not "OK").
 *
 * Use the `primary` variant for the single most important action in a view. Use
 * `secondary` for the alternatives beside it, `ghost` for low-emphasis actions in
 * dense UI such as toolbars, and `danger` only for destructive, hard-to-undo actions.
 *
 * Renders a `Pressable` with `accessibilityRole="button"`, `accessibilityLabel`
 * (`accessibleName`, else a name set by a parent, else `label`) and
 * `accessibilityState={{ disabled, busy, expanded }}` (`expanded` omitted unless a
 * disclosing parent sets it), mirrored to `aria-busy`/`aria-expanded` (and, on
 * react-native-web, `aria-disabled` set on the DOM node) because react-native-web renders
 * only the aria-* forms. `disabled` is never passed to `Pressable` itself — that
 * would drop it from the tab order — so a disabled button stays focusable and is
 * announced as disabled while a press guard blocks `onPress`. There is no hover on
 * touch, so `backgroundHover` animates in for the pressed state instead (over
 * `transition`, eased with `motion.easing.standard`, skipped under reduced motion); the
 * focus ring is a border drawn in `color.border.focus` (or `color.inverse.focus` when
 * `inverse`) that is transparent, not absent, so focusing never shifts layout.
 * `loading` puts a `spinnerSize` ring spinner in the leading icon slot that rotates
 * continuously over `loadingSpin` (frozen under reduced motion), hides `trailingIcon`,
 * keeps the label visible, announces `copy.loading` as the button's accessibility
 * value, and blocks repeat activation alongside `disabled`. `inverse` changes only
 * `ghost`'s foreground and pressed fill (`inverseBackgroundHover` at
 * `inverseHoverOpacity`, an alpha of the resolved color); other variants keep their own fills.
 * `type="submit"` calls `submit()` on the nearest Form context, since there is no
 * native form. `track`, when set, calls the hand-written `trackPress(name, label)`
 * after `onPress` and before `onTrack(name, label)` fires with the same pair. When the measured
 * footprint is smaller than the comfortable target, `hitSlop` makes up the difference.
 * `accessibilityHint`, `accessibilityLabel`, `onHoverIn`, `onHoverOut`, `onFocus`,
 * `onBlur`, `onLongPress` and `onPressOut` are forwarded to the root so Tooltip can
 * attach to the button. `leadingIcon`/`trailingIcon` render in decorative wrappers
 * (`accessibilityElementsHidden`, `importantForAccessibility="no"`); there is no
 * cascade, so callers color glyphs with the variant's foreground themselves.
 */
export function Button({
  label,
  variant = 'primary',
  size = 'md',
  type = 'button',
  expanded,
  disabled = false,
  leadingIcon,
  trailingIcon,
  iconOnly = false,
  loading = false,
  inverse = false,
  accessibleName,
  track,
  overrides,
  ref,
  accessibilityHint,
  accessibilityLabel,
  onPress,
  onTrack,
  onPressOut,
  onLongPress,
  onHoverIn,
  onHoverOut,
  onFocus,
  onBlur,
}: ButtonProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const form = useFormContext();
  const reducedMotion = useReducedMotion();

  const [focused, setFocused] = React.useState(false);
  const [pressedState, setPressedState] = React.useState(false);
  const [layout, setLayout] = React.useState<{ width: number; height: number } | null>(null);

  const isDisabled = disabled || (form?.disabled ?? false);

  // The root is owned here so react-native-web can be given `aria-disabled` directly (below);
  // the caller's `ref` still receives the same Pressable.
  const rootRef = React.useRef<ViewInstance>(null);
  React.useImperativeHandle(ref, () => rootRef.current!, []);

  // react-native-web's Pressable writes `aria-disabled` from its own `disabled` prop, after any
  // `aria-disabled` passed in, and passing `disabled` would also set the native attribute on the
  // <button> it renders, dropping it from the tab order. So on web the attribute is set on the
  // DOM node itself: the button stays focusable and is still announced (and audited) as disabled.
  React.useEffect(() => {
    if (Platform.OS !== 'web') {
      return;
    }
    const node = rootRef.current as unknown as WebElement | null;
    if (node === null) {
      return;
    }
    if (isDisabled) {
      node.setAttribute('aria-disabled', 'true');
    } else {
      node.removeAttribute('aria-disabled');
    }
  }, [isDisabled]);

  const colors = VARIANT_TOKENS[variant];
  const isInverseGhost = variant === 'ghost' && inverse;

  const background = t[colors.background];
  // `backgroundHover` is locked; only the inverse ghost fill and its alpha are overridable.
  const inverseBackgroundHover = overrides?.inverseBackgroundHover
    ? (resolveToken(t, overrides.inverseBackgroundHover) as string)
    : t.colorInverseForeground;
  const inverseHoverOpacity =
    (overrides?.inverseHoverOpacity ? (resolveToken(t, overrides.inverseHoverOpacity) as number) : t.opacityDisabled) *
    INVERSE_HOVER_OPACITY_FACTOR;
  const backgroundHover = isInverseGhost
    ? withAlpha(inverseBackgroundHover, inverseHoverOpacity)
    : t[colors.backgroundHover];
  // Only `ghost` is meaningful on an inverse surface; other variants keep their own fills.
  const foreground = isInverseGhost ? t.colorInverseLink : t[colors.foreground];
  const focusRingColor = inverse ? t.colorInverseFocus : t.colorBorderFocus;

  const iconGap = overrides?.iconGap ? (resolveToken(t, overrides.iconGap) as number) : t.space2;
  const paddingBlock = overrides?.paddingBlock ? (resolveToken(t, overrides.paddingBlock) as number) : t.spaceSm;
  // `iconOnly` makes the sides equal: paddingInline takes the resolved paddingBlock, so a
  // paddingBlock override keeps them equal and a paddingInline override has no effect.
  const paddingInline = iconOnly
    ? paddingBlock
    : overrides?.paddingInline
      ? (resolveToken(t, overrides.paddingInline) as number)
      : t[PADDING_INLINE_TOKEN[size]];
  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusMd;
  const fontFamily = overrides?.fontFamily ? (resolveToken(t, overrides.fontFamily) as string) : t.fontFamilyBody;
  const fontWeight = overrides?.fontWeight ? (resolveToken(t, overrides.fontWeight) as number) : t.fontWeightMedium;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t[FONT_SIZE_TOKEN[size]];
  const disabledOpacity = overrides?.disabledOpacity
    ? (resolveToken(t, overrides.disabledOpacity) as number)
    : t.opacityDisabled;
  const transitionDuration = overrides?.transition
    ? (resolveToken(t, overrides.transition) as number)
    : t.motionDurationFast;
  const loadingSpinDuration = overrides?.loadingSpin
    ? (resolveToken(t, overrides.loadingSpin) as number)
    : t.motionDurationLoop;
  // RN has no em: the ring is `font.size.{size}` across by default, independent of a `fontSize` override.
  const spinnerSize = overrides?.spinnerSize
    ? (resolveToken(t, overrides.spinnerSize) as number)
    : t[FONT_SIZE_TOKEN[size]];
  // `spinnerStroke` is locked: border.width.focus is a focus token.
  const spinnerStroke = t.borderWidthFocus;

  // Background transitions between rest and pressed since there is no hover on touch.
  const highlight = React.useRef(new Animated.Value(0)).current;
  React.useEffect(() => {
    const toValue = pressedState && !isDisabled && !loading ? 1 : 0;
    if (reducedMotion) {
      highlight.setValue(toValue);
      return;
    }
    Animated.timing(highlight, {
      toValue,
      duration: transitionDuration,
      easing: toEasing(t.motionEasingStandard),
      // Color is not a layout property, but react-native-web has no native animated module.
      useNativeDriver: false,
    }).start();
  }, [pressedState, isDisabled, loading, reducedMotion, highlight, transitionDuration, t.motionEasingStandard]);

  const animatedBackground = highlight.interpolate({ inputRange: [0, 1], outputRange: [background, backgroundHover] });

  // The ring spins continuously while loading, and snaps to a fixed frame under
  // reduced motion rather than animating.
  const spin = React.useRef(new Animated.Value(0)).current;
  React.useEffect(() => {
    if (!loading || reducedMotion) {
      spin.setValue(0);
      return undefined;
    }
    const loopAnimation = Animated.loop(
      Animated.timing(spin, {
        toValue: 1,
        duration: loadingSpinDuration,
        easing: Easing.linear,
        useNativeDriver: Platform.OS !== 'web',
      }),
    );
    loopAnimation.start();
    return () => loopAnimation.stop();
  }, [loading, reducedMotion, spin, loadingSpinDuration]);

  // Before the first layout, assume the visual is at the minimum target so the
  // comfortable target is still reachable.
  const slop = (extent: number | undefined): number =>
    Math.max(0, Math.ceil((t.sizeTargetComfortable - (extent ?? t.sizeTargetMin)) / 2));
  const hitSlop: Insets = {
    top: slop(layout?.height),
    bottom: slop(layout?.height),
    left: slop(layout?.width),
    right: slop(layout?.width),
  };

  const handleLayout = (event: LayoutChangeEvent): void => {
    const { width, height } = event.nativeEvent.layout;
    setLayout((prev) => (prev !== null && prev.width === width && prev.height === height ? prev : { width, height }));
  };

  const handlePress = (): void => {
    if (isDisabled || loading) {
      return;
    }
    onPress?.();
    if (track !== undefined) {
      trackPress(track, label);
      onTrack?.(track, label);
    }
    if (type === 'submit') {
      form?.submit();
    }
  };

  const containerStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: t.sizeTargetMin,
    minHeight: t.sizeTargetMin,
    gap: iconGap,
    paddingHorizontal: paddingInline,
    paddingVertical: paddingBlock,
    borderRadius: radius,
    borderWidth: t.borderWidthFocus,
    borderColor: focused ? focusRingColor : 'transparent',
    opacity: isDisabled ? disabledOpacity : 1,
  };

  // A separate fill behind the content, since the border's own color is fixed
  // (transparent or the focus ring) and cannot also carry the animated background.
  const backgroundFillStyle: Animated.WithAnimatedValue<ViewStyle> = {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: radius,
    backgroundColor: animatedBackground,
  };

  const labelStyle: TextStyle = {
    fontFamily,
    fontWeight: toFontWeight(fontWeight),
    fontSize,
    color: foreground,
    textAlign: 'center',
  };

  const iconSlotStyle: ViewStyle = {
    alignItems: 'center',
    justifyContent: 'center',
  };

  // A spinnerSize ring: a circle stroked in the foreground color with one quarter
  // transparent, rotating to read as a spinner.
  const spinnerStyle: Animated.WithAnimatedValue<ViewStyle> = {
    width: spinnerSize,
    height: spinnerSize,
    borderRadius: spinnerSize / 2, // literal-ok: halves a token-derived size into a radius
    borderWidth: spinnerStroke,
    borderColor: foreground,
    borderTopColor: 'transparent',
    transform: [{ rotate: spin.interpolate({ inputRange: [0, 1], outputRange: ['0deg', '360deg'] }) }],
  };

  return (
    <Pressable
      ref={rootRef}
      testID="Button"
      accessibilityRole="button"
      accessibilityLabel={accessibleName ?? accessibilityLabel ?? label}
      accessibilityHint={accessibilityHint}
      accessibilityState={expanded === undefined ? { disabled: isDisabled, busy: loading } : { disabled: isDisabled, busy: loading, expanded }}
      // react-native-web 0.21 ignores `accessibilityState`; these aria-* mirrors are what reach
      // the DOM (native merges both). `aria-disabled` is set on the web node in an effect above.
      aria-busy={loading}
      aria-expanded={expanded}
      accessibilityValue={loading ? { text: COPY.loading } : undefined}
      hitSlop={hitSlop}
      onPress={handlePress}
      onPressIn={() => setPressedState(true)}
      onPressOut={(event) => {
        setPressedState(false);
        onPressOut?.(event);
      }}
      onLongPress={onLongPress}
      onHoverIn={onHoverIn}
      onHoverOut={onHoverOut}
      onFocus={(event) => {
        setFocused(true);
        onFocus?.(event);
      }}
      onBlur={(event) => {
        setFocused(false);
        onBlur?.(event);
      }}
      onLayout={handleLayout}
      style={containerStyle}
    >
      <Animated.View style={backgroundFillStyle} pointerEvents="none" />
      {loading ? (
        // The spinner only takes the leadingIcon position; it is not an anatomy part and carries no part name.
        <View style={iconSlotStyle} accessibilityElementsHidden importantForAccessibility="no">
          <Animated.View style={spinnerStyle} />
        </View>
      ) : leadingIcon !== undefined && leadingIcon !== null ? (
        <View testID="Button.leadingIcon" style={iconSlotStyle} accessibilityElementsHidden importantForAccessibility="no">
          {leadingIcon}
        </View>
      ) : null}
      {iconOnly ? null : (
        <RNText testID="Button.label" allowFontScaling style={labelStyle}>
          {label}
        </RNText>
      )}
      {!iconOnly && !loading && trailingIcon !== undefined && trailingIcon !== null ? (
        <View testID="Button.trailingIcon" style={iconSlotStyle} accessibilityElementsHidden importantForAccessibility="no">
          {trailingIcon}
        </View>
      ) : null}
    </Pressable>
  );
}

// packages/lit/src/Button.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { trackPress } from './custom/analytics.js';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonType = 'button' | 'submit';

/** Detail carried by the `press` CustomEvent (none). */
export type ButtonPressDetail = void;

/** Detail carried by the `track` CustomEvent. */
export interface ButtonTrackDetail {
  name: string;
  label: string;
}

/**
 * Overridable style hooks; see the `overrides` property. The accessibility-bearing
 * bindings — `background`, `backgroundHover`, `foreground`, `focusRing`,
 * `focusRingWidth`, `inverseForeground`, `inverseFocusRing`, `minTarget` and
 * `spinnerStroke` — are locked and excluded; of those, only `spinnerStroke` keeps
 * a CSS hook (`--ds-button-spinner-stroke`), the rest read their tokens directly.
 */
export type ButtonOverridableBinding =
  | 'iconGap'
  | 'paddingInline'
  | 'paddingBlock'
  | 'radius'
  | 'fontFamily'
  | 'fontWeight'
  | 'fontSize'
  | 'inverseBackgroundHover'
  | 'inverseHoverOpacity'
  | 'disabledOpacity'
  | 'transition'
  | 'loadingSpin'
  | 'spinnerSize';

const HOOKS: Record<ButtonOverridableBinding, string> = {
  iconGap: '--ds-button-icon-gap',
  paddingInline: '--ds-button-padding-inline',
  paddingBlock: '--ds-button-padding-block',
  radius: '--ds-button-radius',
  fontFamily: '--ds-button-font-family',
  fontWeight: '--ds-button-font-weight',
  fontSize: '--ds-button-font-size',
  inverseBackgroundHover: '--ds-button-inverse-background-hover',
  inverseHoverOpacity: '--ds-button-inverse-hover-opacity',
  disabledOpacity: '--ds-button-disabled-opacity',
  transition: '--ds-button-transition',
  loadingSpin: '--ds-button-loading-spin',
  spinnerSize: '--ds-button-spinner-size',
};

/** copy.loading — announced as the button's description while `loading` is true. */
const COPY_LOADING = 'Loading';

/**
 * `<ds-button>` — Button (category: action, APG pattern: button).
 *
 * Wraps a native `<button>` in a shadow root created with `delegatesFocus`, so
 * focusing the host focuses the inner button. Activation dispatches a composed,
 * bubbling `press` CustomEvent. A `type="submit"` button submits the enclosing
 * `<ds-form>` (which listens for `press`) or, only when no `ds-form` encloses it,
 * calls `requestSubmit()` on the closest native `<form>`. When `track` is set, a
 * press also calls the hand-written `trackPress` analytics module and then fires
 * a composed `track` CustomEvent with `{ name, label }`.
 *
 * `ds-button` is deliberately *not* form-associated: a form-associated custom
 * element with a reflected `disabled` attribute becomes truly disabled and
 * unfocusable, and the doc requires a disabled button to stay in the tab order.
 * The disabled state is `aria-disabled` on the inner button instead.
 *
 * ## When to use
 *
 * Use a Button when the user needs to **do something**: submit, save, confirm,
 * open, add, delete. The label should be a verb or verb phrase that describes
 * the outcome ("Save changes", not "OK").
 *
 * Use the `primary` variant for the single most important action in a view.
 * Use `secondary` for the alternatives beside it, `ghost` for low-emphasis
 * actions in dense UI such as toolbars, and `danger` only for destructive,
 * hard-to-undo actions. Navigation belongs to Link, never to Button.
 *
 * @fires press - Fired when the button is activated by pointer, keyboard
 *   (Enter/Space), or assistive technology. Not fired while `disabled` or `loading`.
 * @fires track - Fired after `press`, only when `track` is set, with `{ name, label }` in `detail`.
 * @slot leading-icon - Icon rendered before the label (anatomy: leadingIcon). Decorative.
 * @slot trailing-icon - Icon rendered after the label (anatomy: trailingIcon). Decorative.
 * @csspart container - The native `<button>` (anatomy: container).
 * @csspart label - The visible label text (anatomy: label).
 * @csspart leadingIcon - The leading-icon slot (anatomy: leadingIcon).
 * @csspart trailingIcon - The trailing-icon slot (anatomy: trailingIcon).
 */
@customElement('ds-button')
export class DsButton extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    /*
     * Hooks for the overridable bindings, plus spinnerStroke (locked, but its
     * binding keeps the hook). The other locked bindings (background,
     * backgroundHover, foreground, focusRing, focusRingWidth, inverseForeground,
     * inverseFocusRing, minTarget) have no hook: their rules read the token.
     */
    :host {
      display: inline-flex;
      vertical-align: middle;
      --ds-button-icon-gap: var(--space-2);
      --ds-button-padding-inline: var(--space-md);
      --ds-button-padding-block: var(--space-sm);
      --ds-button-radius: var(--radius-md);
      --ds-button-font-family: var(--font-family-body);
      --ds-button-font-weight: var(--font-weight-medium);
      --ds-button-font-size: var(--font-size-md);
      --ds-button-inverse-background-hover: var(--color-inverse-foreground);
      /* the base token; the rule that reads it multiplies by 0.25 */
      --ds-button-inverse-hover-opacity: var(--opacity-disabled);
      --ds-button-disabled-opacity: var(--opacity-disabled);
      --ds-button-transition: var(--motion-duration-fast);
      --ds-button-loading-spin: var(--motion-duration-loop);
      --ds-button-spinner-size: var(--font-size-md);
      --ds-button-spinner-stroke: var(--border-width-focus);
    }

    :host([hidden]) {
      display: none;
    }

    [data-part='container'] {
      position: relative;
      box-sizing: border-box;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      inline-size: 100%;
      /* minTarget: locked; the floor at every size (WCAG 2.5.8) */
      min-inline-size: var(--size-target-min);
      min-block-size: var(--size-target-min);
      margin: 0;
      padding-block: var(--ds-button-padding-block);
      padding-inline: var(--ds-button-padding-inline);
      border: 0;
      border-radius: var(--ds-button-radius);
      font-family: var(--ds-button-font-family);
      font-size: var(--ds-button-font-size);
      font-weight: var(--ds-button-font-weight);
      color: var(--color-action-primary-foreground);
      background: var(--color-action-primary-background);
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
      /* transition: only the background animates, with motion.easing.standard */
      transition: background-color var(--ds-button-transition) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='container'] {
        transition: none;
      }
    }

    /* paddingInline: space.{size}; fontSize and spinnerSize: font.size.{size} */
    :host([size='sm']) {
      --ds-button-padding-inline: var(--space-sm);
      --ds-button-font-size: var(--font-size-sm);
      --ds-button-spinner-size: var(--font-size-sm);
    }
    :host([size='md']) {
      --ds-button-padding-inline: var(--space-md);
      --ds-button-font-size: var(--font-size-md);
      --ds-button-spinner-size: var(--font-size-md);
    }
    :host([size='lg']) {
      --ds-button-padding-inline: var(--space-lg);
      --ds-button-font-size: var(--font-size-lg);
      --ds-button-spinner-size: var(--font-size-lg);
    }

    /*
     * iconOnly: equal padding on all sides. paddingInline takes the resolved
     * paddingBlock, so a paddingBlock override keeps the sides equal and a
     * paddingInline override has no effect.
     */
    :host([icon-only]) [data-part='container'] {
      padding-inline: var(--ds-button-padding-block);
    }

    /* background / foreground: color.action.{variant}.*, locked (no hook) */
    :host([variant='primary']) [data-part='container'] {
      color: var(--color-action-primary-foreground);
      background: var(--color-action-primary-background);
    }
    :host([variant='secondary']) [data-part='container'] {
      color: var(--color-action-secondary-foreground);
      background: var(--color-action-secondary-background);
    }
    :host([variant='ghost']) [data-part='container'] {
      color: var(--color-action-ghost-foreground);
      background: var(--color-action-ghost-background);
    }
    :host([variant='danger']) [data-part='container'] {
      color: var(--color-action-danger-foreground);
      background: var(--color-action-danger-background);
    }

    /*
     * backgroundHover: color.action.{variant}.backgroundHover on pointer hover and
     * pressed, locked. Suppressed by selector while the button is not accepting a
     * press -- :not([aria-disabled='true']):not([aria-busy='true']), the same
     * suppression web writes, read off the inner button's own state attributes.
     */
    :host([variant='primary'])
      [data-part='container']:not([aria-disabled='true']):not([aria-busy='true']):is(:hover, :active) {
      background: var(--color-action-primary-background-hover);
    }
    :host([variant='secondary'])
      [data-part='container']:not([aria-disabled='true']):not([aria-busy='true']):is(:hover, :active) {
      background: var(--color-action-secondary-background-hover);
    }
    :host([variant='ghost'])
      [data-part='container']:not([aria-disabled='true']):not([aria-busy='true']):is(:hover, :active) {
      background: var(--color-action-ghost-background-hover);
    }
    :host([variant='danger'])
      [data-part='container']:not([aria-disabled='true']):not([aria-busy='true']):is(:hover, :active) {
      background: var(--color-action-danger-background-hover);
    }

    /*
     * inverse: only ghost changes on an inverse surface. Its text is
     * inverseForeground, and its hover fill is inverseBackgroundHover at
     * inverseHoverOpacity (the sanctioned color-mix of tokens). Other variants
     * keep their own fills.
     */
    :host([inverse][variant='ghost']) [data-part='container'] {
      color: var(--color-inverse-link);
    }
    :host([inverse][variant='ghost'])
      [data-part='container']:not([aria-disabled='true']):not([aria-busy='true']):is(:hover, :active) {
      background: color-mix(
        in srgb,
        var(--ds-button-inverse-background-hover) calc(var(--ds-button-inverse-hover-opacity) * 0.25 * 100%),
        transparent
      );
    }

    /* focusRing / focusRingWidth: color.border.focus at border.width.focus, locked */
    [data-part='container']:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* inverseFocusRing: the ring must read against the inverse surface, for every variant */
    :host([inverse]) [data-part='container']:focus-visible {
      outline-color: var(--color-inverse-focus);
    }

    /* disabledOpacity: the whole button; colors are unchanged so the contrast math still holds */
    :host([disabled]) [data-part='container'] {
      opacity: var(--ds-button-disabled-opacity);
      cursor: not-allowed;
    }

    .content {
      display: inline-flex;
      align-items: center;
      /* iconGap: space.2 */
      gap: var(--ds-button-icon-gap);
    }

    :host([loading]) [data-part='container'] {
      cursor: progress;
    }

    /* loading: a ring spinnerSize across, spinnerStroke thick, one quarter transparent, in currentColor */
    .spinner {
      display: inline-block;
      box-sizing: border-box;
      inline-size: var(--ds-button-spinner-size);
      block-size: var(--ds-button-spinner-size);
      border: var(--ds-button-spinner-stroke) solid currentColor;
      /* the block-start quarter, so the turn reads as starting from twelve o'clock */
      border-block-start-color: transparent;
      border-radius: var(--radius-full);
      animation: ds-button-spin var(--ds-button-loading-spin) linear infinite;
    }
    @keyframes ds-button-spin {
      to {
        /* one full turn: a geometric constant, not a themed value */
        transform: rotate(360deg);
      }
    }
    @media (prefers-reduced-motion: reduce) {
      .spinner {
        animation: none;
      }
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** The button's text. Also its accessible name. */
  @property({ type: String }) accessor label = '';

  /** Visual emphasis. One primary button per view. */
  @property({ type: String, reflect: true }) accessor variant: ButtonVariant = 'primary';

  /** Controls horizontal padding and font size. Touch targets never drop below the minimum regardless of size. */
  @property({ type: String, reflect: true }) accessor size: ButtonSize = 'md';

  /** `submit` submits the enclosing Form. Everything else is `button`. */
  @property({ type: String, reflect: true }) accessor type: ButtonType = 'button';

  /**
   * Set by a parent that the button discloses (Menu, Popover, SidePanel,
   * Disclosure): rendered as `aria-expanded` on the inner button. A JS property
   * only, and tri-state — `undefined` (the default) means this button discloses
   * nothing, so no `aria-expanded` is rendered at all. A raw `aria-expanded`
   * attribute on the host does not reach the inner button.
   */
  @property({ attribute: false }) accessor expanded: boolean | undefined;

  /**
   * Prevents activation. The button stays in the tab order and is announced as
   * disabled. Inside a disabled `ds-form` the form sets this for you.
   */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /**
   * Hides the visible label and shows only `leadingIcon`; `trailingIcon` is not
   * rendered either. `label` is still required and becomes the accessible name.
   * Padding becomes equal on all sides (`space.sm`).
   */
  @property({ type: Boolean, reflect: true, attribute: 'icon-only' }) accessor iconOnly = false;

  /**
   * Shows a ring spinner in the leading icon position, hides `trailingIcon`,
   * keeps the label visible and the height unchanged, and blocks repeat
   * activation while an action is pending. Without a `leadingIcon` the spinner
   * and iconGap widen the button. `copy.loading` is the description.
   */
  @property({ type: Boolean, reflect: true }) accessor loading = false;

  /**
   * The button sits on an inverse surface (Toast, Tooltip-like panels): `ghost`
   * text and hover change, and the focus ring uses the inverse focus token for
   * every variant.
   */
  @property({ type: Boolean, reflect: true }) accessor inverse = false;

  /**
   * Overrides the accessible name when it must say more than the visible label
   * ("Sort by Amount, ascending" on a header that shows "Amount"). The name must
   * contain the visible label (WCAG 2.5.3 label-in-name). Maps to `aria-label`.
   */
  @property({ type: String, attribute: 'accessible-name' }) accessor accessibleName: string | undefined;

  /**
   * Text used for this button when a Toolbar collapses it into its overflow
   * Menu. Read by Toolbar from the host attribute; the button never renders it.
   */
  @property({ type: String, reflect: true, attribute: 'overflow-label' }) accessor overflowLabel:
    | string
    | undefined;

  /** An event name sent to analytics when the button is pressed. Omit for no tracking. */
  @property({ type: String }) accessor track: string | undefined;

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<ButtonOverridableBinding, TokenRef | undefined>>
    | undefined;

  /**
   * Mirror of the host's own `tabindex`, forwarded to the inner `<button>`.
   *
   * `delegatesFocus` makes the host focusable, but it does not make the inner
   * button share the host's tabbability: a composer that writes `tabindex="-1"`
   * on a `<ds-button>` — a roving-focus parent such as `ds-toolbar`, or one that
   * keeps the control out of the tab order because the surrounding decoration is
   * `aria-hidden` (`ds-tree-grid`'s expand chevron, `ds-number-input`'s steppers)
   * — takes the *host* out of the tab order while the shadow `<button>` stays a
   * tab stop of its own. Forwarding the attribute is the only way a composer can
   * express that, since it cannot reach into this shadow root.
   *
   * `null` (no `tabindex` on the host) forwards nothing, so an ordinary button is
   * tabbable exactly as before, and `disabled` still leaves it in the tab order.
   */
  @state() private accessor hostTabIndex: string | null = null;

  /**
   * Watches the host's `tabindex` only. The callback writes to the inner button
   * through `hostTabIndex`, never back to the host, so it cannot re-enter.
   */
  private readonly tabIndexObserver: MutationObserver = new MutationObserver(() => this.readHostTabIndex());

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Button');
    this.readHostTabIndex();
    this.tabIndexObserver.observe(this, { attributes: true, attributeFilter: ['tabindex'] });
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.tabIndexObserver.disconnect();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    return html`
      <button
        part="container"
        data-part="container"
        type=${this.type}
        tabindex=${ifDefined(this.hostTabIndex ?? undefined)}
        aria-disabled=${ifDefined(this.disabled ? 'true' : undefined)}
        aria-busy=${ifDefined(this.loading ? 'true' : undefined)}
        aria-expanded=${ifDefined(this.expanded === undefined ? undefined : String(this.expanded))}
        aria-label=${ifDefined(this.accessibleName ?? (this.iconOnly ? this.label : undefined))}
        aria-describedby=${ifDefined(this.loading ? 'loading-description' : undefined)}
        @click=${this.handleClick}
      >
        <span class="content">
          ${this.loading
            ? html`<span class="spinner" aria-hidden="true"></span>`
            : html`<slot name="leading-icon" part="leadingIcon" data-part="leadingIcon"></slot>`}
          ${this.iconOnly
            ? // iconOnly removes the label part outright — no hidden node either, since the
              // name moves to aria-label, so a part selector targeting it finds nothing.
              nothing
            : html`<span class="label" part="label" data-part="label">${this.label}</span>`}
          ${this.iconOnly || this.loading
            ? nothing
            : html`<slot name="trailing-icon" part="trailingIcon" data-part="trailingIcon"></slot>`}
        </span>
        ${this.loading
          ? html`<span id="loading-description" class="visually-hidden" aria-hidden="true">${COPY_LOADING}</span>`
          : nothing}
      </button>
    `;
  }

  private handleClick(event: MouseEvent): void {
    if (this.disabled || this.loading) {
      // aria-disabled keeps the button discoverable, so the activation has to be
      // swallowed here: no `press`, no native click leaking out, no submit.
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    this.dispatchEvent(new CustomEvent<ButtonPressDetail>('press', { bubbles: true, composed: true }));

    if (this.track) {
      // The analytics seam: a hand-written module the adopter owns, called once
      // per press, after `press` and before `track`.
      trackPress(this.track, this.label);
      this.dispatchEvent(
        new CustomEvent<ButtonTrackDetail>('track', {
          detail: { name: this.track, label: this.label },
          bubbles: true,
          composed: true,
        }),
      );
    }

    if (this.type === 'submit' && !this.closest('ds-form')) {
      // The inner <button> has no form owner (it lives in the shadow root), so a
      // native <form> is submitted explicitly. Inside a ds-form the form reacts
      // to `press` instead, so a ds-form nested in a native form submits once.
      this.closest('form')?.requestSubmit();
    }
  }

  private readHostTabIndex(): void {
    this.hostTabIndex = this.getAttribute('tabindex');
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ButtonOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-button': DsButton;
  }
}
