// packages/rn/src/Checkbox.tsx
import * as React from 'react';
import { Animated, AccessibilityInfo, Platform, Pressable, StyleSheet, View, findNodeHandle } from 'react-native';
import type { PressableStateCallbackType, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { useFieldsetContext } from './Fieldset';
import { useFormContext } from './FormContext';
import type { FormFieldHandle } from './FormContext';
import { Icon } from './Icon';
import { Text } from './Text';
import { toEasing, useReducedMotion, useTheme } from './theme';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type CheckboxOverridableBinding =
  | 'controlBackground'
  | 'controlBorderWidth'
  | 'pressedOverlay'
  | 'controlBorderInvalid'
  | 'controlSize'
  | 'controlRadius'
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

export interface CheckboxProps {
  /** Visible label. Tapping it toggles the control. Also the `accessibilityLabel`. */
  label: string;
  /** Visually hide the label (it remains the accessible name via `accessibilityLabel`): a selection column in a Table, where the row name is the label. */
  hideLabel?: boolean | undefined;
  /** Field name used by the enclosing Form when collecting values. */
  name: string;
  /** What a native HTML form submits when checked (web and Lit only). The enclosing Form ignores it and collects the boolean `checked`; checkboxes sharing a `name` are not a multi-select, so give each its own name. */
  value?: string | undefined;
  /** Controlled checked state. Omit for an uncontrolled control. */
  checked?: boolean | undefined;
  /** Initial state for an uncontrolled control. */
  defaultChecked?: boolean | undefined;
  /** Shows the mixed indicator, for a parent checkbox whose children are partly selected. Visual and announced only; the submitted value still follows `checked`. */
  indeterminate?: boolean | undefined;
  /** Cannot be toggled and is not submitted. Stays visible, readable and focusable. */
  disabled?: boolean | undefined;
  /** Must be checked to submit — for consent and agreement. Shown in the label, not only by color. */
  required?: boolean | undefined;
  /** Marks the control as failing validation. Usually set by the Form; can be set directly. */
  invalid?: boolean | undefined;
  /** Persistent helper text below the label. Also the `accessibilityHint`. */
  description?: string | undefined;
  /** The error message. Setting it marks the control invalid. Say what to do ("Accept the terms to continue"). */
  error?: string | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<CheckboxOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the checked state changes, with the new boolean. */
  onChange?: ((checked: boolean) => void) | undefined;
  /** The root view. */
  ref?: React.Ref<ViewInstance> | undefined;
}

const COPY = {
  required: (label: string): string => `${label} is required.`,
  invalid: (label: string): string => `${label} is not valid.`,
  requiredIndicator: ' (required)',
} as const;

/**
 * Checkbox — a single yes/no choice that the user makes and then submits, as
 * opposed to a Switch, which takes effect the moment it is flipped.
 *
 * When to use: Use a Checkbox for one independent option ("Remember me"), for terms
 * and consent (`required`), or several, each with its own `name`, when the user may
 * pick any number of items. Use `indeterminate` on a "select all" parent when only some
 * of its children are checked. Do not use it for a setting that applies immediately
 * (Switch) or to pick exactly one option (RadioGroup).
 *
 * There is no checkbox in core React Native. Renders a `Pressable` row with
 * `accessibilityRole="checkbox"`, `accessibilityLabel`, `accessibilityHint={description}`
 * and `accessibilityState={{ checked: indeterminate ? 'mixed' : checked, disabled }}`,
 * containing the drawn control (the `check`/`dash` `Icon`) and the label and
 * description, so the whole row — control, label or description — is the hit area and
 * never drops below the comfortable target. Space on a hardware keyboard is handled by
 * the platform once the role is set. The fill, border and indicator cross-fade over
 * `transition` with `motion.easing.standard` (skipped under reduced motion); while
 * pressed an unchecked, enabled box shows the selected fill at `pressedOverlay`.
 * Toggling an indeterminate checkbox clears the mixed state until `indeterminate`
 * changes value again. Inside a Form the control registers by `name` and submits its
 * checked state as a boolean (`value` is not used on native); the error slot shows
 * `error`, else the Form's message, else — only while `invalid` — `copy.required`
 * (required and unchecked) or `copy.invalid`, as in Input, and `validate: blur` means
 * on change. `disabledOpacity` dims the control and label, not the description or
 * error. The row has no vertical padding: it is at least `size.target.comfortable`
 * tall and centers the control and text column.
 * Inside a Fieldset the group's `disabled` applies and the legend prefixes the
 * accessibility label. Errors are announced as in Input.
 */
export function Checkbox({
  label,
  hideLabel = false,
  name,
  value = 'on',
  checked,
  defaultChecked = false,
  indeterminate = false,
  disabled = false,
  required = false,
  invalid = false,
  description,
  error,
  overrides,
  onChange,
  ref,
}: CheckboxProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const form = useFormContext();
  const fieldset = useFieldsetContext();
  const reducedMotion = useReducedMotion();
  const pressableRef = React.useRef<ViewInstance>(null);
  const [internalChecked, setInternalChecked] = React.useState<boolean>(defaultChecked);
  const [mixedCleared, setMixedCleared] = React.useState(false);
  const [focused, setFocused] = React.useState(false);

  // A new `indeterminate: true` brings the mixed state back after a toggle cleared it.
  React.useEffect(() => {
    setMixedCleared(false);
  }, [indeterminate]);

  const isChecked = checked ?? internalChecked;
  const isMixed = indeterminate && !mixedCleared;
  const isDisabled = disabled || (form?.disabled ?? false) || (fieldset?.disabled ?? false);
  const formError = form?.errors[name];
  const derivedError = invalid ? (required && !isChecked ? COPY.required(label) : COPY.invalid(label)) : undefined;
  const displayedError = error !== undefined && error !== '' ? error : (formError ?? derivedError);
  const isInvalid = invalid || displayedError !== undefined;
  const summarised = form !== null && form.errorSummary;

  const validateValue = React.useCallback(
    (candidate: boolean): string | null => {
      // Precedence: `error` prop, then `required`, then `invalid`.
      if (error !== undefined && error !== '') {
        return error;
      }
      if (required && !candidate) {
        return COPY.required(label);
      }
      if (invalid) {
        return COPY.invalid(label);
      }
      return null;
    },
    [error, required, invalid, label],
  );

  const latest = React.useRef({ isChecked, value, validateValue });
  latest.current = { isChecked, value, validateValue };
  const handle = React.useMemo<FormFieldHandle>(
    () => ({
      getValue: () => latest.current.isChecked,
      validate: () => latest.current.validateValue(latest.current.isChecked),
      focus: () => {
        const node = pressableRef.current === null ? null : findNodeHandle(pressableRef.current);
        if (node != null) {
          AccessibilityInfo.setAccessibilityFocus(node);
        }
      },
    }),
    [],
  );

  const register = form?.register;
  const unregister = form?.unregister;
  React.useEffect(() => {
    if (register === undefined || unregister === undefined || isDisabled) {
      return undefined;
    }
    register(name, handle);
    return () => unregister(name);
  }, [register, unregister, name, handle, isDisabled]);

  React.useEffect(() => {
    if (Platform.OS === 'ios' && !summarised && displayedError !== undefined) {
      AccessibilityInfo.announceForAccessibility(displayedError);
    }
  }, [displayedError, summarised]);

  const handlePress = (): void => {
    if (isDisabled) {
      return;
    }
    const next = !isChecked;
    if (checked === undefined) {
      setInternalChecked(next);
    }
    if (isMixed) {
      setMixedCleared(true);
    }
    onChange?.(next);
    if (form !== null && form.validateMode !== 'submit') {
      form.reportValidity(name, validateValue(next));
    }
  };

  const visibleLabel = required ? `${label}${COPY.requiredIndicator}` : label;
  const accessibleName = fieldset !== null ? `${fieldset.legend}, ${visibleLabel}` : visibleLabel;
  const filled = isChecked || isMixed;

  const controlBackground = overrides?.controlBackground ? (resolveToken(t, overrides.controlBackground) as string) : t.colorControlBackground;
  const controlBorderWidth = overrides?.controlBorderWidth ? (resolveToken(t, overrides.controlBorderWidth) as number) : t.borderWidthThin;
  const pressedOverlay = overrides?.pressedOverlay ? (resolveToken(t, overrides.pressedOverlay) as number) : t.opacityDisabled;
  const controlBorderInvalid = overrides?.controlBorderInvalid ? (resolveToken(t, overrides.controlBorderInvalid) as string) : t.colorBorderDanger;
  const controlSize = overrides?.controlSize ? (resolveToken(t, overrides.controlSize) as number) : t.space5;
  const controlRadius = overrides?.controlRadius ? (resolveToken(t, overrides.controlRadius) as number) : t.radiusSm;
  const gap = overrides?.gap ? (resolveToken(t, overrides.gap) as number) : t.space2;
  const partGap = overrides?.partGap ? (resolveToken(t, overrides.partGap) as number) : t.space1;
  const disabledOpacity = overrides?.disabledOpacity ? (resolveToken(t, overrides.disabledOpacity) as number) : t.opacityDisabled;
  const transitionDuration = overrides?.transition ? (resolveToken(t, overrides.transition) as number) : t.motionDurationFast;

  // Fill, border and indicator cross-fade together between unchecked and
  // checked/indeterminate; the pressed overlay is instant, not part of this.
  const fillAnim = React.useRef(new Animated.Value(filled ? 1 : 0)).current;
  React.useEffect(() => {
    const toValue = filled ? 1 : 0;
    if (reducedMotion) {
      fillAnim.setValue(toValue);
      return;
    }
    Animated.timing(fillAnim, {
      toValue,
      duration: transitionDuration,
      easing: toEasing(t.motionEasingStandard),
      useNativeDriver: false,
    }).start();
  }, [filled, reducedMotion, fillAnim, transitionDuration, t.motionEasingStandard]);

  const animatedBackground = fillAnim.interpolate({ inputRange: [0, 1], outputRange: [controlBackground, t.colorControlSelectedBackground] });
  const animatedBorderColor = fillAnim.interpolate({ inputRange: [0, 1], outputRange: [t.colorControlBorder, t.colorControlSelectedBackground] });

  const rootStyle: ViewStyle = {
    flexDirection: 'column',
    gap: partGap,
  };

  const rowStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'center',
    gap,
    minHeight: t.sizeTargetComfortable,
  };

  // Dims the control (with its indicator) and the label; description and error stay readable.
  const dimStyle: ViewStyle = { opacity: isDisabled ? disabledOpacity : 1 };

  const controlStyle: Animated.WithAnimatedValue<ViewStyle> = {
    width: controlSize,
    height: controlSize,
    borderRadius: controlRadius,
    borderWidth: focused ? t.borderWidthFocus : controlBorderWidth,
    borderColor: focused ? t.colorBorderFocus : isInvalid ? controlBorderInvalid : animatedBorderColor,
    backgroundColor: animatedBackground,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: dimStyle.opacity,
  };

  // Only an unchecked, not-mixed, enabled box shows the pressed overlay; a filled one has nothing to add.
  const overlayStyle = ({ pressed }: PressableStateCallbackType): ViewStyle => ({
    ...StyleSheet.absoluteFill,
    backgroundColor: t.colorControlSelectedBackground,
    opacity: pressed && !filled && !isDisabled ? pressedOverlay : 0,
  });

  const indicatorStyle: Animated.WithAnimatedValue<ViewStyle> = { opacity: fillAnim };

  const textColumnStyle: ViewStyle = {
    flex: 1,
    flexDirection: 'column',
    gap: partGap,
  };

  const typographyOverrides = { fontFamily: overrides?.fontFamily, lineHeight: overrides?.lineHeight };
  const helperOverrides = { ...typographyOverrides, fontSize: overrides?.helperSize };

  return (
    <View ref={ref} testID="Checkbox" style={rootStyle}>
      <Pressable
        ref={pressableRef}
        accessibilityRole="checkbox"
        accessibilityLabel={accessibleName}
        accessibilityHint={description}
        accessibilityState={{ checked: isMixed ? 'mixed' : isChecked, disabled: isDisabled }}
        onPress={handlePress}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        style={rowStyle}
      >
        {(state) => (
          <>
            <Animated.View testID="Checkbox.control" style={controlStyle} accessibilityElementsHidden importantForAccessibility="no">
              <View style={overlayStyle(state)} />
              <Animated.View testID="Checkbox.indicator" style={indicatorStyle}>
                <Icon name={isMixed ? 'dash' : 'check'} size="xs" color={t.colorControlSelectedForeground} />
              </Animated.View>
            </Animated.View>
            <View style={textColumnStyle}>
              {hideLabel ? null : (
                <View testID="Checkbox.label" style={dimStyle}>
                  <Text
                    size="md"
                    weight="regular"
                    tone="default"
                    overrides={{ ...typographyOverrides, fontSize: overrides?.labelSize, fontWeight: overrides?.labelWeight }}
                  >
                    {visibleLabel}
                  </Text>
                </View>
              )}
              {description !== undefined ? (
                <View testID="Checkbox.description">
                  <Text size="sm" tone="muted" overrides={helperOverrides}>
                    {description}
                  </Text>
                </View>
              ) : null}
            </View>
          </>
        )}
      </Pressable>
      {displayedError !== undefined ? (
        <View accessibilityLiveRegion={summarised ? 'none' : 'assertive'} testID="Checkbox.errorMessage">
          <Text size="sm" tone="danger" overrides={helperOverrides}>
            {displayedError}
          </Text>
        </View>
      ) : null}
    </View>
  );
}

// packages/lit/src/Checkbox.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { live } from 'lit/directives/live.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import type { IconOverridableBinding } from './Icon.js';
import type { TextOverridableBinding } from './Text.js';
import './Icon.js';
import './Text.js';

/** Detail carried by the `change` CustomEvent. */
export interface CheckboxChangeDetail {
  /** The new checked state. */
  checked: boolean;
}

/** copy.required */
const COPY_REQUIRED = (label: string): string => `${label} is required.`;
/** copy.invalid */
const COPY_INVALID = (label: string): string => `${label} is not valid.`;
/** copy.requiredIndicator */
const COPY_REQUIRED_INDICATOR = ' (required)';

/** indicator (locked): reaches the composed Icon only through its `color` override. */
const INDICATOR_OVERRIDES: Partial<Record<IconOverridableBinding, TokenRef | undefined>> = {
  color: 'color.control.selectedForeground',
};

/** Overridable style hooks; see the `overrides` property. `controlBorder`, `controlSelectedBackground`, `indicator`, `indicatorStroke`, `labelColor`, `descriptionText`, `errorText`, `focusRing`, `focusRingWidth` and `minTarget` are locked and excluded. */
export type CheckboxOverridableBinding =
  | 'controlBackground'
  | 'controlBorderWidth'
  | 'pressedOverlay'
  | 'controlBorderInvalid'
  | 'controlSize'
  | 'controlRadius'
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

/** Hooks on `:host`. `helperSize` has none: it reaches the description and error Texts only through their `overrides`. */
const HOOKS: Record<Exclude<CheckboxOverridableBinding, 'helperSize'>, string> = {
  controlBackground: '--ds-checkbox-control-background',
  controlBorderWidth: '--ds-checkbox-control-border-width',
  pressedOverlay: '--ds-checkbox-pressed-overlay',
  controlBorderInvalid: '--ds-checkbox-control-border-invalid',
  controlSize: '--ds-checkbox-control-size',
  controlRadius: '--ds-checkbox-control-radius',
  gap: '--ds-checkbox-gap',
  partGap: '--ds-checkbox-part-gap',
  labelSize: '--ds-checkbox-label-size',
  labelWeight: '--ds-checkbox-label-weight',
  fontFamily: '--ds-checkbox-font-family',
  lineHeight: '--ds-checkbox-line-height',
  disabledOpacity: '--ds-checkbox-disabled-opacity',
  transition: '--ds-checkbox-transition',
};

/**
 * `<ds-checkbox>` — Checkbox (category: input, APG pattern: checkbox).
 *
 * `<ds-checkbox name="updates" label="Send me product updates">`. A native
 * `<input type="checkbox">` styled with `appearance: none` lives in the shadow
 * root (with `delegatesFocus`) and is the drawn box; the check mark and mixed
 * dash are `<ds-icon name="check">` / `<ds-icon name="dash">` in an aria-hidden
 * indicator span stacked over it. The `<label for>` sits in the same root, so a
 * click on it toggles natively; a click on the description or the gap is
 * forwarded to the control. The error message sits below the row, outside the
 * hit area, indented so it lines up with the label.
 *
 * The element is form-associated via `ElementInternals`
 * (`setFormValue(checked ? value : null)`), so a native `<form>` sees it, and
 * `<ds-form>` discovers it by `data-ds-field` and collects the boolean. The inner
 * native `change` is not composed, so a composed `change` CustomEvent with
 * `{ checked }` is re-dispatched from the host. `checked` behaves like a native
 * input: the `checked` attribute is the initial state only and the property
 * tracks the live state, so it is not reflected.
 *
 * ## When to use
 *
 * Use a Checkbox for one independent option ("Remember me"), for terms and
 * consent (`required`), or several, each with its own `name`, when the user may
 * pick any number of items. Use `indeterminate` on a "select all" parent when
 * only some of its children are checked. For a setting that applies
 * immediately, use Switch instead; to pick exactly one of several, use RadioGroup.
 *
 * @fires change - Fired when the user toggles the checked state, with `{ checked }` in `detail`.
 */
@customElement('ds-checkbox')
export class DsCheckbox extends LitElement {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-checkbox-control-background: var(--color-control-background);
      --ds-checkbox-control-border-width: var(--border-width-thin);
      --ds-checkbox-pressed-overlay: var(--opacity-disabled);
      --ds-checkbox-control-border-invalid: var(--color-border-danger);
      --ds-checkbox-control-size: var(--space-5);
      --ds-checkbox-control-radius: var(--radius-sm);
      --ds-checkbox-gap: var(--space-2);
      --ds-checkbox-part-gap: var(--space-1);
      --ds-checkbox-label-size: var(--font-size-md);
      --ds-checkbox-label-weight: var(--font-weight-regular);
      --ds-checkbox-font-family: var(--font-family-body);
      --ds-checkbox-line-height: var(--font-line-height-normal);
      --ds-checkbox-disabled-opacity: var(--opacity-disabled);
      --ds-checkbox-transition: var(--motion-duration-fast);
      /* indicator, indicatorStroke, helperSize, descriptionText and errorText have no hook: the
         composed Icon and Texts realise them through their own props and overrides. */

      /* The label's first line box; the control centres on it and the row is padded around it. */
      --ds-checkbox-line-box: calc(var(--ds-checkbox-label-size) * var(--ds-checkbox-line-height));
    }

    :host([hidden]) {
      display: none;
    }

    /* partGap: between the row and the error message below it */
    .field {
      display: flex;
      flex-direction: column;
      gap: var(--ds-checkbox-part-gap);
    }

    /* minTarget: the whole row, gap included, is the hit area. The children align to the start of
       the cross axis and the padding makes a single-line row exactly minTarget tall, so a wrapping
       label or a description grows the row downwards without pulling the control off the first line. */
    .row {
      display: flex;
      align-items: flex-start;
      gap: var(--ds-checkbox-gap);
      padding-block: calc((var(--size-target-comfortable) - var(--ds-checkbox-line-box)) / 2);
      cursor: pointer;
    }

    /* The box is one label line tall and stacks the control and the indicator in one grid cell,
       which centres the control on the label's first line (and in the row when the label is hidden). */
    .box {
      display: inline-grid;
      place-items: center;
      flex: 0 0 auto;
      block-size: var(--ds-checkbox-line-box);
    }
    .box > * {
      grid-area: 1 / 1;
    }

    /* control: a native input drawn with the control tokens, never a hidden input under a fake box. */
    .control {
      box-sizing: border-box;
      inline-size: var(--ds-checkbox-control-size);
      block-size: var(--ds-checkbox-control-size);
      margin: 0;
      padding: 0;
      border-width: var(--ds-checkbox-control-border-width);
      border-style: solid;
      border-color: var(--color-control-border);
      border-radius: var(--ds-checkbox-control-radius);
      background-color: var(--ds-checkbox-control-background);
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
      transition:
        background-color var(--ds-checkbox-transition) var(--motion-easing-standard),
        border-color var(--ds-checkbox-transition) var(--motion-easing-standard);
    }

    /* Border color precedence: invalid, then selected, then rest — so these three rules stay in order. */

    /* controlSelectedBackground: checked and indeterminate fill; the border takes the same color */
    .control:checked,
    .control:indeterminate {
      border-color: var(--color-control-selected-background);
      background-color: var(--color-control-selected-background);
    }

    /* controlBorderInvalid: replaces the border color in every state; the selected fill is unchanged */
    :host([invalid]) .control {
      border-color: var(--ds-checkbox-control-border-invalid);
    }

    /* pressedOverlay: an unchecked, not-mixed, enabled box shows controlSelectedBackground at this
       opacity over controlBackground; the border is unchanged. A filled or disabled box shows none. */
    .row:not(.disabled) .control:active:not(:checked):not(:indeterminate) {
      background-color: color-mix(
        in srgb,
        var(--color-control-selected-background) calc(var(--ds-checkbox-pressed-overlay) * 100%),
        var(--ds-checkbox-control-background)
      );
    }

    /* focusRing, focusRingWidth: a separate outline, so an invalid box keeps controlBorderInvalid */
    .control:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* indicator: the Icon centred over the control; clicks fall through to the input */
    .indicator {
      display: inline-flex;
      pointer-events: none;
    }

    /* transition: fill and border only — the indicator is mounted and unmounted, never animated */
    @media (prefers-reduced-motion: reduce) {
      .control {
        transition: none;
      }
    }

    /* partGap: between label and description */
    .text {
      display: flex;
      flex-direction: column;
      gap: var(--ds-checkbox-part-gap);
      min-inline-size: 0;
    }

    /* labelColor, labelSize, labelWeight, fontFamily, lineHeight: the label's own rule */
    .label {
      font-family: var(--ds-checkbox-font-family);
      font-size: var(--ds-checkbox-label-size);
      font-weight: var(--ds-checkbox-label-weight);
      line-height: var(--ds-checkbox-line-height);
      color: var(--color-foreground);
      cursor: pointer;
    }

    /* The error sits below the row, outside the hit area, indented by controlSize + gap so it lines
       up with the label rather than the control. */
    .error {
      padding-inline-start: calc(var(--ds-checkbox-control-size) + var(--ds-checkbox-gap));
    }

    /* disabledOpacity: dims the control (with its indicator) and the label, not the description or error */
    .row.disabled,
    .row.disabled .control,
    .row.disabled .label {
      cursor: not-allowed;
    }
    .row.disabled .box,
    .row.disabled .label {
      opacity: var(--ds-checkbox-disabled-opacity);
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** Visible label. Clicking or tapping it toggles the control. */
  @property() accessor label = '';

  /** Visually hide the label (it remains the accessible name). */
  @property({ type: Boolean, attribute: 'hide-label' }) accessor hideLabel = false;

  /** Field name used by the enclosing Form when collecting values. */
  @property() accessor name = '';

  /** What a native `<form>` submits under `name` when checked. ds-form ignores it and collects the boolean. */
  @property() accessor value = 'on';

  /** Initial state when the `checked` attribute is absent. */
  @property({ type: Boolean, attribute: 'default-checked' }) accessor defaultChecked = false;

  /** Shows the mixed indicator. Visual and announced only; the submitted value still follows `checked`. */
  @property({ type: Boolean, reflect: true }) accessor indeterminate = false;

  /** Cannot be toggled and is not submitted. Stays visible, readable and focusable. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Must be checked to submit. Shown in the label, not only by color. */
  @property({ type: Boolean, reflect: true }) accessor required = false;

  /** Marks the control as failing validation. Usually set by the Form; can be set directly. */
  @property({ type: Boolean, reflect: true }) accessor invalid = false;

  /** Persistent helper text below the label. */
  @property() accessor description: string | undefined;

  /** Per-instance style overrides: `{ controlRadius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<CheckboxOverridableBinding, TokenRef | undefined>>
    | undefined;

  private checkedValue: boolean | undefined;

  /** The live checked state, like a native input: starts from the `checked` attribute, else `defaultChecked`, and follows every toggle. Not reflected. */
  get checked(): boolean {
    return this.checkedValue ?? this.defaultChecked;
  }
  @property({ type: Boolean })
  set checked(value: boolean) {
    const old = this.checked;
    this.checkedValue = value;
    this.requestUpdate('checked', old);
  }

  private errorValue: string | undefined;

  /** The error message. Setting it marks the control invalid. Say what to do. */
  get error(): string | undefined {
    return this.errorValue;
  }
  @property()
  set error(value: string | undefined) {
    const old = this.errorValue;
    this.errorValue = value;
    // Synchronous so that `checkValidity()` right after an assignment is already correct.
    this.invalid = Boolean(value);
    this.requestUpdate('error', old);
  }

  /** Disabled by an owning native form / fieldset (via `formDisabledCallback`). */
  @state() private accessor formDisabled = false;

  /** A user toggle clears the mixed indicator locally until `indeterminate` changes value again. */
  @state() private accessor mixedCleared = false;

  @query('#control') private accessor inputEl!: HTMLInputElement | null;

  private readonly internals: ElementInternals;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Checkbox');
    // A checkbox has no useful blur moment, so `validate: blur` means "on change" for it.
    this.setAttribute('data-ds-field', 'change');
  }

  /** The value `<ds-form>` collects: the checked boolean. */
  get currentValue(): boolean {
    return this.checked;
  }

  /** The owning native form, if any (from `ElementInternals`). */
  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  get validity(): ValidityState {
    this.syncInternals();
    return this.internals.validity;
  }

  /** The field's own copy, in the same order as its validity; empty when valid. */
  get validationMessage(): string {
    this.syncInternals();
    return this.internals.validationMessage;
  }

  checkValidity(): boolean {
    this.syncInternals();
    return this.internals.checkValidity();
  }

  reportValidity(): boolean {
    this.syncInternals();
    return this.internals.reportValidity();
  }

  /* Form-associated custom element callbacks (invoked by the browser). */

  formDisabledCallback(disabled: boolean): void {
    this.formDisabled = disabled;
  }

  /** Back to the initial state: the `checked` attribute, else `defaultChecked`. */
  formResetCallback(): void {
    this.checked = this.hasAttribute('checked') || this.defaultChecked;
    this.mixedCleared = false;
  }

  formStateRestoreCallback(state: File | string | FormData | null): void {
    this.checked = typeof state === 'string' && state === this.value;
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('indeterminate')) {
      this.mixedCleared = false;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    // `indeterminate` has no attribute; it is a DOM property only. Compare first: an unconditional
    // write would re-enter the update cycle.
    if (this.inputEl && this.inputEl.indeterminate !== this.showMixed) {
      this.inputEl.indeterminate = this.showMixed;
    }
    this.syncInternals();
  }

  protected override render(): TemplateResult {
    const isDisabled = this.isDisabled;
    const mixed = this.showMixed;
    const message = this.displayedError;
    const describedBy = [this.description ? 'description' : '', message ? 'error' : ''].filter(Boolean).join(' ');
    const textOverrides = this.textOverrides;
    const glyph = mixed ? 'dash' : this.checked ? 'check' : undefined;

    return html`
      <div class="field">
        <div class=${classMap({ row: true, disabled: isDisabled })} @click=${this.handleRowClick}>
          <span class="box">
            <input
              id="control"
              class="control"
              part="control"
              data-part="control"
              type="checkbox"
              name=${this.name}
              value=${this.value}
              .checked=${live(this.checked)}
              aria-checked=${ifDefined(mixed ? 'mixed' : undefined)}
              aria-describedby=${ifDefined(describedBy || undefined)}
              aria-invalid=${ifDefined(this.invalid ? 'true' : undefined)}
              aria-required=${ifDefined(this.required ? 'true' : undefined)}
              aria-disabled=${ifDefined(isDisabled ? 'true' : undefined)}
              @click=${this.handleControlClick}
              @change=${this.handleChange}
            />
            ${glyph
              ? html`<span class="indicator" part="indicator" data-part="indicator" aria-hidden="true"
                  ><ds-icon name=${glyph} size="xs" .overrides=${INDICATOR_OVERRIDES}></ds-icon
                ></span>`
              : nothing}
          </span>
          <div class="text">
            <label
              class=${classMap({ label: true, 'visually-hidden': this.hideLabel })}
              part="label"
              data-part="label"
              for="control"
              >${this.label}${this.required ? COPY_REQUIRED_INDICATOR : nothing}</label
            >
            ${this.description
              ? html`<ds-text
                  id="description"
                  part="description"
                  data-part="description"
                  element="p"
                  size="sm"
                  tone="muted"
                  .overrides=${textOverrides}
                  >${this.description}</ds-text
                >`
              : nothing}
          </div>
        </div>
        ${message
          ? html`<ds-text
              id="error"
              class="error"
              role="alert"
              part="errorMessage"
              data-part="errorMessage"
              element="p"
              size="sm"
              tone="danger"
              .overrides=${textOverrides}
              >${message}</ds-text
            >`
          : nothing}
      </div>
    `;
  }

  private get isDisabled(): boolean {
    return this.disabled || this.formDisabled;
  }

  private get showMixed(): boolean {
    return this.indeterminate && !this.mixedCleared;
  }

  /** Rendered error, as Input: `error`, then — only while invalid — copy.required when required and unchecked, else copy.invalid. */
  private get displayedError(): string {
    if (this.error) {
      return this.error;
    }
    if (!this.invalid) {
      return '';
    }
    return this.required && !this.checked ? COPY_REQUIRED(this.label) : COPY_INVALID(this.label);
  }

  /** helperSize, fontFamily and lineHeight forwarded to the description and error Text. */
  private get textOverrides(): Partial<Record<TextOverridableBinding, TokenRef | undefined>> | undefined {
    const o = this.overrides;
    if (!o) {
      return undefined;
    }
    return { fontSize: o.helperSize, fontFamily: o.fontFamily, lineHeight: o.lineHeight };
  }

  /** Clicks on the description or the gap toggle the control too. */
  private handleRowClick(event: MouseEvent): void {
    const input = this.inputEl;
    const target = event.target;
    if (!input || !(target instanceof Element) || this.isDisabled) {
      return;
    }
    // The input handles itself, and a label click is already forwarded to it natively.
    if (target === input || target.closest('label') !== null) {
      return;
    }
    input.focus();
    input.click();
  }

  /** Disabled uses aria-disabled so the control stays focusable; click and change are both guarded. */
  private handleControlClick(event: MouseEvent): void {
    if (this.isDisabled) {
      event.preventDefault();
    }
  }

  private handleChange(event: Event): void {
    event.stopPropagation();
    const input = event.currentTarget as HTMLInputElement;
    if (this.isDisabled) {
      event.preventDefault();
      input.checked = this.checked;
      return;
    }
    const next = input.checked;
    // A toggle clears the mixed indicator until `indeterminate` changes value again.
    if (this.indeterminate) {
      this.mixedCleared = true;
    }
    this.checked = next;
    this.dispatchEvent(
      new CustomEvent<CheckboxChangeDetail>('change', {
        detail: { checked: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  /** Mirror value and validity into ElementInternals, in the same order as Input. */
  private syncInternals(): void {
    // A disabled field is left out of submission and validity, as a native disabled control is.
    if (this.isDisabled) {
      this.internals.setFormValue(null);
      this.internals.setValidity({});
      return;
    }

    const anchor = this.inputEl ?? undefined;
    this.internals.setFormValue(this.checked ? this.value : null);

    if (this.error) {
      this.internals.setValidity({ customError: true }, this.error, anchor);
    } else if (this.required && !this.checked) {
      this.internals.setValidity({ valueMissing: true }, COPY_REQUIRED(this.label), anchor);
    } else if (this.invalid) {
      this.internals.setValidity({ customError: true }, COPY_INVALID(this.label), anchor);
    } else {
      this.internals.setValidity({});
    }
  }

  private applyOverrides(): void {
    for (const [binding, hook] of Object.entries(HOOKS) as [keyof typeof HOOKS, string][]) {
      const ref = this.overrides?.[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-checkbox': DsCheckbox;
  }
}
