// packages/react/src/Checkbox.tsx
import {
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
  type ChangeEvent,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type MouseEvent,
  type Ref,
  type ReactElement,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import { Text, type TextOverridableBinding } from './Text';
import { useFormContext } from './FormContext';
import './Checkbox.css';

/**
 * copy.* — used verbatim; `{label}` is replaced by the visible label. `checked`, `unchecked` and
 * `mixed` are SwiftUI-only spoken values; on web the native checked state and
 * `aria-checked="mixed"` carry the state.
 */
const COPY = {
  required: '{label} is required.',
  invalid: '{label} is not valid.',
  requiredIndicator: ' (required)',
  checked: 'Checked',
  unchecked: 'Unchecked',
  mixed: 'Mixed',
} as const;

/** The indicator binding's locked token, reaching the composed Icon only through its `color` override. */
const INDICATOR_COLOR: TokenRef = 'color.control.selectedForeground';

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type CheckboxOverridableBinding =
  | 'controlBackground'
  | 'controlBorderWidth'
  | 'pressedOverlay'
  | 'controlBorderInvalid'
  | 'controlSize'
  | 'controlRadius'
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

/**
 * helperSize has no hook: it reaches the description and error Texts only through their `fontSize`
 * override. fontFamily and lineHeight are both a hook (the label's own rule) and a forward.
 */
const OVERRIDE_HOOK: Partial<Record<CheckboxOverridableBinding, string>> = {
  controlBackground: '--ds-checkbox-control-background',
  controlBorderWidth: '--ds-checkbox-control-border-width',
  pressedOverlay: '--ds-checkbox-pressed-overlay',
  controlBorderInvalid: '--ds-checkbox-control-border-invalid',
  controlSize: '--ds-checkbox-control-size',
  controlRadius: '--ds-checkbox-control-radius',
  gap: '--ds-checkbox-gap',
  partGap: '--ds-checkbox-part-gap',
  labelSize: '--ds-checkbox-label-size',
  labelWeight: '--ds-checkbox-label-weight',
  fontFamily: '--ds-checkbox-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  lineHeight: '--ds-checkbox-line-height',
  disabledOpacity: '--ds-checkbox-disabled-opacity',
  transition: '--ds-checkbox-transition',
};

type TextOverrides = Partial<Record<TextOverridableBinding, TokenRef | undefined>>;

function resolveOverrides(overrides: Partial<Record<CheckboxOverridableBinding, TokenRef | undefined>>): {
  rootStyle: CSSProperties;
  helperOverrides: TextOverrides;
} {
  const rootStyle: Record<string, string> = {};
  const helperOverrides: TextOverrides = {};
  for (const binding of Object.keys(overrides) as CheckboxOverridableBinding[]) {
    const ref = overrides[binding];
    if (!ref) continue;
    // Description and error are Text: helperSize, fontFamily and lineHeight reach Text's own overrides.
    if (binding === 'helperSize') helperOverrides.fontSize = ref;
    if (binding === 'fontFamily') helperOverrides.fontFamily = ref;
    if (binding === 'lineHeight') helperOverrides.lineHeight = ref;
    // Locked bindings (and helperSize) have no entry in the hook table, so no hook is written.
    const hook = OVERRIDE_HOOK[binding];
    if (hook) rootStyle[hook] = cssVar(ref);
  }
  return { rootStyle: rootStyle as CSSProperties, helperOverrides };
}

export interface CheckboxProps
  extends Omit<
    ComponentPropsWithoutRef<'input'>,
    | 'type'
    | 'name'
    | 'value'
    | 'checked'
    | 'defaultChecked'
    | 'required'
    | 'disabled'
    | 'onChange'
    | 'aria-describedby'
    | 'aria-invalid'
    | 'aria-required'
    | 'aria-checked'
    | 'aria-disabled'
    | 'className'
    | 'style'
    | 'children'
  > {
  /** Visible label. Clicking or tapping it toggles the control. */
  label: string;
  /**
   * Visually hide the label (it remains the accessible name): a selection column in a Table, where
   * the row name is the label.
   */
  hideLabel?: boolean | undefined;
  /** Field name used by the enclosing Form when collecting values. */
  name: string;
  /**
   * What a native HTML <form> submits under `name` when checked (web and Lit only). The enclosing Form
   * (React, React Native, ds-form) ignores it and collects the boolean `checked`. Checkboxes sharing a
   * `name` are not a multi-select under Form; give each its own name. React Native accepts it
   * (default 'on') for API parity and does nothing with it.
   */
  value?: string | undefined;
  /** Controlled checked state. Omit for an uncontrolled control. */
  checked?: boolean | undefined;
  /** Initial state for an uncontrolled control. */
  defaultChecked?: boolean | undefined;
  /**
   * Shows the mixed indicator, for a parent checkbox whose children are partly selected. Visual and
   * announced only; the submitted value still follows `checked`. With `checked` also true, mixed wins
   * for both the glyph and the announced state — a partly selected parent is mixed, whatever its own
   * box would say — while the submitted value stays `checked`.
   */
  indeterminate?: boolean | undefined;
  /**
   * Cannot be toggled and is skipped by the Form. Stays visible, readable and focusable, which is why
   * it is `aria-disabled` and not the native attribute — with the accepted consequence that a native
   * HTML `<form>` still submits a disabled-but-checked box's `value`, since only the native attribute
   * excludes it.
   */
  disabled?: boolean | undefined;
  /** Must be checked to submit — for consent and agreement. Shown in the label, not only by color. */
  required?: boolean | undefined;
  /**
   * Marks the control as failing validation. Usually set by the Form; can be set directly. While true
   * with no `error` (and no Form message), the error slot renders copy.required (required and
   * unchecked) or copy.invalid, with role=alert, so a bare `invalid` always shows a message.
   */
  invalid?: boolean | undefined;
  /** Persistent helper text below the label. */
  description?: string | undefined;
  /**
   * The error message. Setting it marks the control invalid. Say what to do ("Accept the terms to
   * continue").
   */
  error?: string | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<CheckboxOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the checked state changes, with the new boolean. */
  onChange?: ((checked: boolean) => void) | undefined;
}

/**
 * Checkbox — Design Schema, category: input.
 *
 * When to use:
 * Use a Checkbox for one independent option ("Remember me"), for terms and consent (`required`), or several, each with its own `name`, when the user may pick any number of items. Use `indeterminate` on a "select all" parent when only some of its children are checked.
 */
export function Checkbox({
  ref,
  label,
  hideLabel = false,
  name,
  value = 'on',
  checked,
  defaultChecked = false,
  indeterminate = false,
  disabled = false,
  required = false,
  invalid = false,
  description,
  error,
  overrides,
  onChange,
  onClick,
  id: idProp,
  ...rest
}: CheckboxProps & { ref?: Ref<HTMLInputElement> | undefined }): ReactElement {
  const form = useFormContext();
  const generatedId = useId();
  const id = idProp ?? (form?.idBase ? `${form.idBase}-${name}` : `ds-checkbox${generatedId}`);
  const descriptionId = `${id}-description`;
  const errorId = `${id}-error`;

  const inputRef = useRef<HTMLInputElement | null>(null);
  const labelRef = useRef<HTMLLabelElement | null>(null);
  // The root is the wrapper div; the forwarded ref resolves to the interactive <input>, as in Input.
  useImperativeHandle(ref, () => inputRef.current as HTMLInputElement, []);

  // The input is never React-controlled: it takes `defaultChecked` and keeps its native checked
  // state. React mirrors the live state only to render the indicator, and writes the prop back onto
  // the DOM property when a controlled `checked` differs from what the browser just did.
  const isControlled = checked !== undefined;
  const [uncontrolledChecked, setUncontrolledChecked] = useState(defaultChecked);
  const isChecked = isControlled ? checked : uncontrolledChecked;
  const isDisabled = disabled || (form?.disabled ?? false);

  useEffect(() => {
    const el = inputRef.current;
    if (el && el.checked !== isChecked) el.checked = isChecked;
  }, [isChecked]);

  // A user toggle clears the mixed state locally; a new `indeterminate` prop value restores it.
  const [mixedCleared, setMixedCleared] = useState(false);
  const [lastIndeterminate, setLastIndeterminate] = useState(indeterminate);
  if (lastIndeterminate !== indeterminate) {
    setLastIndeterminate(indeterminate);
    setMixedCleared(false);
  }
  const isMixed = indeterminate && !mixedCleared;

  // `indeterminate` has no attribute; it is a DOM property, mirrored as aria-checked="mixed".
  useEffect(() => {
    const el = inputRef.current;
    if (el && el.indeterminate !== isMixed) el.indeterminate = isMixed;
  }, [isMixed]);

  // Error slot: `error`, else the Form's message, else — only while `invalid` — the copy.
  const invalidMessage = invalid
    ? (required && !isChecked ? COPY.required : COPY.invalid).replace('{label}', label)
    : undefined;
  const resolvedError = error ?? form?.errors[name] ?? invalidMessage;
  const isInvalid = invalid || resolvedError !== undefined;

  // Keep the latest props in a ref so the Form registration does not churn on every render.
  const latest = useRef({ label, required, disabled: isDisabled, invalid, error });
  latest.current = { label, required, disabled: isDisabled, invalid, error };

  useEffect(() => {
    if (!form) return undefined;
    return form.register({
      name,
      id,
      get label() {
        return latest.current.label;
      },
      // form.valueType is boolean: the checked state is collected under `name`, false when unchecked.
      getValue: () => inputRef.current?.checked ?? false,
      isDisabled: () => latest.current.disabled,
      // Validity always follows the full order, whatever `invalid` is; only the rendered message waits.
      validate: () => {
        const { label: currentLabel, required: isRequired, invalid: isInvalidProp, error: errorProp } = latest.current;
        if (errorProp !== undefined) return errorProp;
        if (isRequired && !inputRef.current?.checked) return COPY.required.replace('{label}', currentLabel);
        if (isInvalidProp) return COPY.invalid.replace('{label}', currentLabel);
        return null;
      },
      focus: () => inputRef.current?.focus(),
    });
  }, [form, name, id]);

  const describedBy = [description ? descriptionId : null, resolvedError ? errorId : null].filter(Boolean).join(' ');

  // Inside a Form, `validate: blur` means "on change" for a checkbox; after a failed submit every
  // mode re-validates on change, so a fixed field stops being flagged.
  const validateMode = form ? (form.validateMode ?? form.validate) : undefined;
  const validatesOnChange = validateMode === 'blur' || validateMode === 'change' || (form?.submitFailed ?? false);

  const handleClick = (event: MouseEvent<HTMLInputElement>) => {
    if (isDisabled) {
      // aria-disabled does not stop native toggling, so we do. The input stays focusable.
      event.preventDefault();
      return;
    }
    onClick?.(event);
  };

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (isDisabled) {
      event.preventDefault();
      return;
    }
    const input = event.target;
    const next = input.checked;
    if (!isControlled) setUncontrolledChecked(next);
    if (isMixed) setMixedCleared(true);
    onChange?.(next);
    // Controlled: after reporting the change, write the prop back so the box follows the prop. A new
    // prop value re-renders and the sync effect above writes that instead.
    if (isControlled) input.checked = isChecked;
    // There is no useful blur moment for a checkbox: `blur` mode validates on change too.
    if (form && validatesOnChange) form.validateField(name);
  };

  // The whole row is the hit area: the gap, the text column and the description forward to the
  // control. The input and the label already toggle natively, so they are left alone.
  const handleRowClick = (event: MouseEvent<HTMLDivElement>) => {
    const target = event.target as Node;
    if (inputRef.current?.contains(target) || labelRef.current?.contains(target)) return;
    if (!isDisabled) inputRef.current?.click();
  };

  const classes = ['ds-checkbox', isInvalid ? 'ds-checkbox--invalid' : null, isDisabled ? 'ds-checkbox--disabled' : null]
    .filter(Boolean)
    .join(' ');
  const labelClasses = ['ds-checkbox__label', hideLabel ? 'ds-checkbox__label--hidden' : null].filter(Boolean).join(' ');

  const { rootStyle, helperOverrides } = overrides
    ? resolveOverrides(overrides)
    : { rootStyle: undefined, helperOverrides: undefined };

  return (
    <div className={classes} data-ds="Checkbox" data-ds-field style={rootStyle}>
      <div className="ds-checkbox__row" onClick={handleRowClick}>
        {/* The box stacks the void <input> and the indicator in one cell, one label line tall. */}
        <span className="ds-checkbox__box">
          <input
            {...rest}
            ref={inputRef}
            id={id}
            type="checkbox"
            name={name}
            value={value}
            defaultChecked={isChecked}
            className="ds-checkbox__control"
            data-part="control"
            aria-describedby={describedBy || undefined}
            aria-invalid={isInvalid ? 'true' : undefined}
            aria-required={required ? 'true' : undefined}
            aria-checked={isMixed ? 'mixed' : undefined}
            aria-disabled={isDisabled ? 'true' : undefined}
            onClick={handleClick}
            onChange={handleChange}
          />
          {/* indicator: decorative, stacked over the control; the input's state is what is announced. */}
          <span className="ds-checkbox__indicator" data-part="indicator" aria-hidden="true">
            {isMixed || isChecked ? (
              <Icon name={isMixed ? 'dash' : 'check'} size="xs" overrides={{ color: INDICATOR_COLOR }} />
            ) : null}
          </span>
        </span>
        <div className="ds-checkbox__text">
          <label ref={labelRef} htmlFor={id} className={labelClasses} data-part="label">
            {label}
            {/* requiredIndicator is plain label text, not aria-hidden: it is part of the name. */}
            {required ? COPY.requiredIndicator : null}
          </label>
          {description ? (
            <Text
              element="p"
              id={descriptionId}
              data-part="description"
              size="sm"
              tone="muted"
              overrides={helperOverrides}
            >
              {description}
            </Text>
          ) : null}
        </div>
      </div>
      {/* The error sits below the row, outside the hit area, indented to line up with the label. */}
      {resolvedError ? (
        <div className="ds-checkbox__error">
          <Text
            element="p"
            id={errorId}
            role="alert"
            data-part="errorMessage"
            size="sm"
            tone="danger"
            overrides={helperOverrides}
          >
            {resolvedError}
          </Text>
        </div>
      ) : null}
    </div>
  );
}

// packages/lit/src/Checkbox.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { live } from 'lit/directives/live.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import type { IconOverridableBinding } from './Icon.js';
import type { TextOverridableBinding } from './Text.js';
import './Icon.js';
import './Text.js';

/** Detail carried by the `change` CustomEvent. */
export interface CheckboxChangeDetail {
  /** The new checked state. */
  checked: boolean;
}

/** copy.required */
const COPY_REQUIRED = (label: string): string => `${label} is required.`;
/** copy.invalid */
const COPY_INVALID = (label: string): string => `${label} is not valid.`;
/** copy.requiredIndicator */
const COPY_REQUIRED_INDICATOR = ' (required)';

/** indicator (locked): reaches the composed Icon only through its `color` override. */
const INDICATOR_OVERRIDES: Partial<Record<IconOverridableBinding, TokenRef | undefined>> = {
  color: 'color.control.selectedForeground',
};

/** Overridable style hooks; see the `overrides` property. `controlBorder`, `controlSelectedBackground`, `indicator`, `indicatorStroke`, `labelColor`, `descriptionText`, `errorText`, `focusRing`, `focusRingWidth` and `minTarget` are locked and excluded. */
export type CheckboxOverridableBinding =
  | 'controlBackground'
  | 'controlBorderWidth'
  | 'pressedOverlay'
  | 'controlBorderInvalid'
  | 'controlSize'
  | 'controlRadius'
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

/** Hooks on `:host`. `helperSize` has none: it reaches the description and error Texts only through their `overrides`. */
const HOOKS: Record<Exclude<CheckboxOverridableBinding, 'helperSize'>, string> = {
  controlBackground: '--ds-checkbox-control-background',
  controlBorderWidth: '--ds-checkbox-control-border-width',
  pressedOverlay: '--ds-checkbox-pressed-overlay',
  controlBorderInvalid: '--ds-checkbox-control-border-invalid',
  controlSize: '--ds-checkbox-control-size',
  controlRadius: '--ds-checkbox-control-radius',
  gap: '--ds-checkbox-gap',
  partGap: '--ds-checkbox-part-gap',
  labelSize: '--ds-checkbox-label-size',
  labelWeight: '--ds-checkbox-label-weight',
  fontFamily: '--ds-checkbox-font-family',
  lineHeight: '--ds-checkbox-line-height',
  disabledOpacity: '--ds-checkbox-disabled-opacity',
  transition: '--ds-checkbox-transition',
};

/**
 * `<ds-checkbox>` — Checkbox (category: input, APG pattern: checkbox).
 *
 * `<ds-checkbox name="updates" label="Send me product updates">`. A native
 * `<input type="checkbox">` styled with `appearance: none` lives in the shadow
 * root (with `delegatesFocus`) and is the drawn box; the check mark and mixed
 * dash are `<ds-icon name="check">` / `<ds-icon name="dash">` in an aria-hidden
 * indicator span stacked over it. The `<label for>` sits in the same root, so a
 * click on it toggles natively; a click on the description or the gap is
 * forwarded to the control. The error message sits below the row, outside the
 * hit area, indented so it lines up with the label.
 *
 * The element is form-associated via `ElementInternals`
 * (`setFormValue(checked ? value : null)`), so a native `<form>` sees it, and
 * `<ds-form>` discovers it by `data-ds-field` and collects the boolean. The inner
 * native `change` is not composed, so a composed `change` CustomEvent with
 * `{ checked }` is re-dispatched from the host. `checked` behaves like a native
 * input: the `checked` attribute is the initial state only and the property
 * tracks the live state, so it is not reflected.
 *
 * ## When to use
 *
 * Use a Checkbox for one independent option ("Remember me"), for terms and
 * consent (`required`), or several, each with its own `name`, when the user may
 * pick any number of items. Use `indeterminate` on a "select all" parent when
 * only some of its children are checked. For a setting that applies
 * immediately, use Switch instead; to pick exactly one of several, use RadioGroup.
 *
 * @fires change - Fired when the user toggles the checked state, with `{ checked }` in `detail`.
 */
@customElement('ds-checkbox')
export class DsCheckbox extends LitElement {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-checkbox-control-background: var(--color-control-background);
      --ds-checkbox-control-border-width: var(--border-width-thin);
      --ds-checkbox-pressed-overlay: var(--opacity-disabled);
      --ds-checkbox-control-border-invalid: var(--color-border-danger);
      --ds-checkbox-control-size: var(--space-5);
      --ds-checkbox-control-radius: var(--radius-sm);
      --ds-checkbox-gap: var(--space-2);
      --ds-checkbox-part-gap: var(--space-1);
      --ds-checkbox-label-size: var(--font-size-md);
      --ds-checkbox-label-weight: var(--font-weight-regular);
      --ds-checkbox-font-family: var(--font-family-body);
      --ds-checkbox-line-height: var(--font-line-height-normal);
      --ds-checkbox-disabled-opacity: var(--opacity-disabled);
      --ds-checkbox-transition: var(--motion-duration-fast);
      /* indicator, indicatorStroke, helperSize, descriptionText and errorText have no hook: the
         composed Icon and Texts realise them through their own props and overrides. */

      /* The label's first line box; the control centres on it and the row is padded around it. */
      --ds-checkbox-line-box: calc(var(--ds-checkbox-label-size) * var(--ds-checkbox-line-height));
    }

    :host([hidden]) {
      display: none;
    }

    /* partGap: between the row and the error message below it */
    .field {
      display: flex;
      flex-direction: column;
      gap: var(--ds-checkbox-part-gap);
    }

    /* minTarget: the whole row, gap included, is the hit area. The children align to the start of
       the cross axis and the padding makes a single-line row exactly minTarget tall, so a wrapping
       label or a description grows the row downwards without pulling the control off the first line. */
    .row {
      display: flex;
      align-items: flex-start;
      gap: var(--ds-checkbox-gap);
      padding-block: calc((var(--size-target-comfortable) - var(--ds-checkbox-line-box)) / 2);
      cursor: pointer;
    }

    /* The box is one label line tall and stacks the control and the indicator in one grid cell,
       which centres the control on the label's first line (and in the row when the label is hidden). */
    .box {
      display: inline-grid;
      place-items: center;
      flex: 0 0 auto;
      block-size: var(--ds-checkbox-line-box);
    }
    .box > * {
      grid-area: 1 / 1;
    }

    /* control: a native input drawn with the control tokens, never a hidden input under a fake box. */
    .control {
      box-sizing: border-box;
      inline-size: var(--ds-checkbox-control-size);
      block-size: var(--ds-checkbox-control-size);
      margin: 0;
      padding: 0;
      border-width: var(--ds-checkbox-control-border-width);
      border-style: solid;
      border-color: var(--color-control-border);
      border-radius: var(--ds-checkbox-control-radius);
      background-color: var(--ds-checkbox-control-background);
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
      transition:
        background-color var(--ds-checkbox-transition) var(--motion-easing-standard),
        border-color var(--ds-checkbox-transition) var(--motion-easing-standard);
    }

    /* Border color precedence: invalid, then selected, then rest — so these three rules stay in order. */

    /* controlSelectedBackground: checked and indeterminate fill; the border takes the same color */
    .control:checked,
    .control:indeterminate {
      border-color: var(--color-control-selected-background);
      background-color: var(--color-control-selected-background);
    }

    /* controlBorderInvalid: replaces the border color in every state; the selected fill is unchanged */
    :host([invalid]) .control {
      border-color: var(--ds-checkbox-control-border-invalid);
    }

    /* pressedOverlay: an unchecked, not-mixed, enabled box shows controlSelectedBackground at this
       opacity over controlBackground; the border is unchanged. A filled or disabled box shows none. */
    .row:not(.disabled) .control:active:not(:checked):not(:indeterminate) {
      background-color: color-mix(
        in srgb,
        var(--color-control-selected-background) calc(var(--ds-checkbox-pressed-overlay) * 100%),
        var(--ds-checkbox-control-background)
      );
    }

    /* focusRing, focusRingWidth: a separate outline, so an invalid box keeps controlBorderInvalid */
    .control:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* indicator: the Icon centred over the control; clicks fall through to the input */
    .indicator {
      display: inline-flex;
      pointer-events: none;
    }

    /* transition: fill and border only — the indicator is mounted and unmounted, never animated */
    @media (prefers-reduced-motion: reduce) {
      .control {
        transition: none;
      }
    }

    /* partGap: between label and description */
    .text {
      display: flex;
      flex-direction: column;
      gap: var(--ds-checkbox-part-gap);
      min-inline-size: 0;
    }

    /* labelColor, labelSize, labelWeight, fontFamily, lineHeight: the label's own rule */
    .label {
      font-family: var(--ds-checkbox-font-family);
      font-size: var(--ds-checkbox-label-size);
      font-weight: var(--ds-checkbox-label-weight);
      line-height: var(--ds-checkbox-line-height);
      color: var(--color-foreground);
      cursor: pointer;
    }

    /* The error sits below the row, outside the hit area, indented by controlSize + gap so it lines
       up with the label rather than the control. */
    .error {
      padding-inline-start: calc(var(--ds-checkbox-control-size) + var(--ds-checkbox-gap));
    }

    /* disabledOpacity: dims the control (with its indicator) and the label, not the description or error */
    .row.disabled,
    .row.disabled .control,
    .row.disabled .label {
      cursor: not-allowed;
    }
    .row.disabled .box,
    .row.disabled .label {
      opacity: var(--ds-checkbox-disabled-opacity);
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** Visible label. Clicking or tapping it toggles the control. */
  @property() accessor label = '';

  /** Visually hide the label (it remains the accessible name). */
  @property({ type: Boolean, attribute: 'hide-label' }) accessor hideLabel = false;

  /** Field name used by the enclosing Form when collecting values. */
  @property() accessor name = '';

  /** What a native `<form>` submits under `name` when checked. ds-form ignores it and collects the boolean. */
  @property() accessor value = 'on';

  /** Initial state when the `checked` attribute is absent. */
  @property({ type: Boolean, attribute: 'default-checked' }) accessor defaultChecked = false;

  /** Shows the mixed indicator. Visual and announced only; the submitted value still follows `checked`. */
  @property({ type: Boolean, reflect: true }) accessor indeterminate = false;

  /** Cannot be toggled and is not submitted. Stays visible, readable and focusable. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Must be checked to submit. Shown in the label, not only by color. */
  @property({ type: Boolean, reflect: true }) accessor required = false;

  /** Marks the control as failing validation. Usually set by the Form; can be set directly. */
  @property({ type: Boolean, reflect: true }) accessor invalid = false;

  /** Persistent helper text below the label. */
  @property() accessor description: string | undefined;

  /** Per-instance style overrides: `{ controlRadius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<CheckboxOverridableBinding, TokenRef | undefined>>
    | undefined;

  private checkedValue: boolean | undefined;

  /** The live checked state, like a native input: starts from the `checked` attribute, else `defaultChecked`, and follows every toggle. Not reflected. */
  get checked(): boolean {
    return this.checkedValue ?? this.defaultChecked;
  }
  @property({ type: Boolean })
  set checked(value: boolean) {
    const old = this.checked;
    this.checkedValue = value;
    this.requestUpdate('checked', old);
  }

  private errorValue: string | undefined;

  /** The error message. Setting it marks the control invalid. Say what to do. */
  get error(): string | undefined {
    return this.errorValue;
  }
  @property()
  set error(value: string | undefined) {
    const old = this.errorValue;
    this.errorValue = value;
    // Synchronous so that `checkValidity()` right after an assignment is already correct.
    this.invalid = Boolean(value);
    this.requestUpdate('error', old);
  }

  /** Disabled by an owning native form / fieldset (via `formDisabledCallback`). */
  @state() private accessor formDisabled = false;

  /** A user toggle clears the mixed indicator locally until `indeterminate` changes value again. */
  @state() private accessor mixedCleared = false;

  @query('#control') private accessor inputEl!: HTMLInputElement | null;

  private readonly internals: ElementInternals;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Checkbox');
    // A checkbox has no useful blur moment, so `validate: blur` means "on change" for it.
    this.setAttribute('data-ds-field', 'change');
  }

  /** The value `<ds-form>` collects: the checked boolean. */
  get currentValue(): boolean {
    return this.checked;
  }

  /** The owning native form, if any (from `ElementInternals`). */
  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  get validity(): ValidityState {
    this.syncInternals();
    return this.internals.validity;
  }

  /** The field's own copy, in the same order as its validity; empty when valid. */
  get validationMessage(): string {
    this.syncInternals();
    return this.internals.validationMessage;
  }

  checkValidity(): boolean {
    this.syncInternals();
    return this.internals.checkValidity();
  }

  reportValidity(): boolean {
    this.syncInternals();
    return this.internals.reportValidity();
  }

  /* Form-associated custom element callbacks (invoked by the browser). */

  formDisabledCallback(disabled: boolean): void {
    this.formDisabled = disabled;
  }

  /** Back to the initial state: the `checked` attribute, else `defaultChecked`. */
  formResetCallback(): void {
    this.checked = this.hasAttribute('checked') || this.defaultChecked;
    this.mixedCleared = false;
  }

  formStateRestoreCallback(state: File | string | FormData | null): void {
    this.checked = typeof state === 'string' && state === this.value;
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('indeterminate')) {
      this.mixedCleared = false;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    // `indeterminate` has no attribute; it is a DOM property only. Compare first: an unconditional
    // write would re-enter the update cycle.
    if (this.inputEl && this.inputEl.indeterminate !== this.showMixed) {
      this.inputEl.indeterminate = this.showMixed;
    }
    this.syncInternals();
  }

  protected override render(): TemplateResult {
    const isDisabled = this.isDisabled;
    const mixed = this.showMixed;
    const message = this.displayedError;
    const describedBy = [this.description ? 'description' : '', message ? 'error' : ''].filter(Boolean).join(' ');
    const textOverrides = this.textOverrides;
    const glyph = mixed ? 'dash' : this.checked ? 'check' : undefined;

    return html`
      <div class="field">
        <div class=${classMap({ row: true, disabled: isDisabled })} @click=${this.handleRowClick}>
          <span class="box">
            <input
              id="control"
              class="control"
              part="control"
              data-part="control"
              type="checkbox"
              name=${this.name}
              value=${this.value}
              .checked=${live(this.checked)}
              aria-checked=${ifDefined(mixed ? 'mixed' : undefined)}
              aria-describedby=${ifDefined(describedBy || undefined)}
              aria-invalid=${ifDefined(this.invalid ? 'true' : undefined)}
              aria-required=${ifDefined(this.required ? 'true' : undefined)}
              aria-disabled=${ifDefined(isDisabled ? 'true' : undefined)}
              @click=${this.handleControlClick}
              @change=${this.handleChange}
            />
            ${glyph
              ? html`<span class="indicator" part="indicator" data-part="indicator" aria-hidden="true"
                  ><ds-icon name=${glyph} size="xs" .overrides=${INDICATOR_OVERRIDES}></ds-icon
                ></span>`
              : nothing}
          </span>
          <div class="text">
            <label
              class=${classMap({ label: true, 'visually-hidden': this.hideLabel })}
              part="label"
              data-part="label"
              for="control"
              >${this.label}${this.required ? COPY_REQUIRED_INDICATOR : nothing}</label
            >
            ${this.description
              ? html`<ds-text
                  id="description"
                  part="description"
                  data-part="description"
                  element="p"
                  size="sm"
                  tone="muted"
                  .overrides=${textOverrides}
                  >${this.description}</ds-text
                >`
              : nothing}
          </div>
        </div>
        ${message
          ? html`<ds-text
              id="error"
              class="error"
              role="alert"
              part="errorMessage"
              data-part="errorMessage"
              element="p"
              size="sm"
              tone="danger"
              .overrides=${textOverrides}
              >${message}</ds-text
            >`
          : nothing}
      </div>
    `;
  }

  private get isDisabled(): boolean {
    return this.disabled || this.formDisabled;
  }

  private get showMixed(): boolean {
    return this.indeterminate && !this.mixedCleared;
  }

  /** Rendered error, as Input: `error`, then — only while invalid — copy.required when required and unchecked, else copy.invalid. */
  private get displayedError(): string {
    if (this.error) {
      return this.error;
    }
    if (!this.invalid) {
      return '';
    }
    return this.required && !this.checked ? COPY_REQUIRED(this.label) : COPY_INVALID(this.label);
  }

  /** helperSize, fontFamily and lineHeight forwarded to the description and error Text. */
  private get textOverrides(): Partial<Record<TextOverridableBinding, TokenRef | undefined>> | undefined {
    const o = this.overrides;
    if (!o) {
      return undefined;
    }
    return { fontSize: o.helperSize, fontFamily: o.fontFamily, lineHeight: o.lineHeight };
  }

  /** Clicks on the description or the gap toggle the control too. */
  private handleRowClick(event: MouseEvent): void {
    const input = this.inputEl;
    const target = event.target;
    if (!input || !(target instanceof Element) || this.isDisabled) {
      return;
    }
    // The input handles itself, and a label click is already forwarded to it natively.
    if (target === input || target.closest('label') !== null) {
      return;
    }
    input.focus();
    input.click();
  }

  /** Disabled uses aria-disabled so the control stays focusable; click and change are both guarded. */
  private handleControlClick(event: MouseEvent): void {
    if (this.isDisabled) {
      event.preventDefault();
    }
  }

  private handleChange(event: Event): void {
    event.stopPropagation();
    const input = event.currentTarget as HTMLInputElement;
    if (this.isDisabled) {
      event.preventDefault();
      input.checked = this.checked;
      return;
    }
    const next = input.checked;
    // A toggle clears the mixed indicator until `indeterminate` changes value again.
    if (this.indeterminate) {
      this.mixedCleared = true;
    }
    this.checked = next;
    this.dispatchEvent(
      new CustomEvent<CheckboxChangeDetail>('change', {
        detail: { checked: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  /** Mirror value and validity into ElementInternals, in the same order as Input. */
  private syncInternals(): void {
    // A disabled field is left out of submission and validity, as a native disabled control is.
    if (this.isDisabled) {
      this.internals.setFormValue(null);
      this.internals.setValidity({});
      return;
    }

    const anchor = this.inputEl ?? undefined;
    this.internals.setFormValue(this.checked ? this.value : null);

    if (this.error) {
      this.internals.setValidity({ customError: true }, this.error, anchor);
    } else if (this.required && !this.checked) {
      this.internals.setValidity({ valueMissing: true }, COPY_REQUIRED(this.label), anchor);
    } else if (this.invalid) {
      this.internals.setValidity({ customError: true }, COPY_INVALID(this.label), anchor);
    } else {
      this.internals.setValidity({});
    }
  }

  private applyOverrides(): void {
    for (const [binding, hook] of Object.entries(HOOKS) as [keyof typeof HOOKS, string][]) {
      const ref = this.overrides?.[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-checkbox': DsCheckbox;
  }
}
