// packages/rn/src/Disclosure.tsx
import * as React from 'react';
import { Animated, I18nManager, Platform, Pressable, Text as RNText, View } from 'react-native';
import type { PressableStateCallbackType, TextStyle, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import { Text } from './Text';
import { toEasing, toFontWeight, toLineHeight, useReducedMotion, useTheme } from './theme';

/** Heading level for the trigger. The schema declares the values as strings; numbers are accepted for ergonomics. */
export type DisclosureHeadingLevel = '2' | '3' | '4' | '5' | '6' | 2 | 3 | 4 | 5 | 6;

/**
 * Why the state changed. `keyboard` never fires natively — `Pressable` cannot tell a
 * hardware Enter/Space activation from a touch — so a trigger press always reports
 * `pointer`; `controlled` is a consumer-driven `open` prop change.
 */
export type DisclosureToggleReason = 'pointer' | 'keyboard' | 'controlled';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type DisclosureOverridableBinding =
  | 'triggerPaddingBlock'
  | 'triggerPaddingInline'
  | 'triggerGap'
  | 'triggerFontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight'
  | 'triggerLineHeight'
  | 'triggerRadius'
  | 'panelPaddingBlock'
  | 'panelPaddingInline'
  | 'disabledOpacity'
  | 'transition';

export interface DisclosureProps {
  /** The trigger's label. Also the trigger's accessible name. Says what will be revealed. */
  summary: string;
  /** The content of the panel. Rendered only while open (not merely hidden). A plain string is wrapped in the system `Text`. */
  children: React.ReactNode;
  /** Controlled open state. Omit for an uncontrolled disclosure. */
  open?: boolean | undefined;
  /** Initial state for an uncontrolled disclosure. */
  defaultOpen?: boolean | undefined;
  /** The trigger cannot be activated. Stays focusable and is announced as disabled; the panel keeps its current state. */
  disabled?: boolean | undefined;
  /** Keep the panel in the tree while closed (hidden, not unmounted). Required when the panel contains form fields, so the Form still collects them while the disclosure is closed. */
  keepMounted?: boolean | undefined;
  /** The trigger stretches across its container, so the whole row is the hit area (and the hover fill runs edge to edge). The icon and summary stay at the start. */
  fullWidth?: boolean | undefined;
  /**
   * When set, the summary is marked `accessibilityRole="header"` so the disclosure
   * appears in the screen reader's heading list. Native has no heading levels, so the
   * value itself changes nothing beyond that.
   */
  headingLevel?: DisclosureHeadingLevel | undefined;
  /** Fired after the state changes, with the new boolean `open` and a reason. */
  onToggle?: ((open: boolean, reason: DisclosureToggleReason) => void) | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root view. */
  ref?: React.Ref<ViewInstance> | undefined;
}

/** The part of a DOM element react-native-web hands back for a `View`; `Platform.OS === 'web'` only. */
type WebElement = { setAttribute(name: string, value: string): void; removeAttribute(name: string): void };

/** Each overridable binding's default token, the one place its path is written. */
const DEFAULT_TOKEN = {
  triggerPaddingBlock: 'space.sm',
  triggerPaddingInline: 'space.sm',
  triggerGap: 'space.2',
  triggerFontFamily: 'font.family.body',
  triggerFontSize: 'font.size.md',
  triggerFontWeight: 'font.weight.medium',
  triggerLineHeight: 'font.lineHeight.normal',
  triggerRadius: 'radius.md',
  panelPaddingBlock: 'space.sm',
  panelPaddingInline: 'space.sm',
  disabledOpacity: 'opacity.disabled',
  transition: 'motion.duration.base',
} as const satisfies Record<DisclosureOverridableBinding, TokenRef>;

/** Chevron rotation: pointing along the reading direction when closed, down when open. */
const CHEVRON_CLOSED = '0deg';
const CHEVRON_OPEN = '90deg';
/** `chevron-left` points the other way, so it turns the other way to land on the same down-pointing shape. */
const CHEVRON_OPEN_RTL = '-90deg';

/**
 * Disclosure — a button that reveals content beneath it. Deliberately plain: no
 * border, no card, no animation of the panel.
 *
 * When to use: hide secondary content that some users need and most do not —
 * optional settings, long explanations, FAQ answers. Stack several to make an
 * accordion; each is independent. Do not hide content most users need, and do not
 * use it as a fake tab set.
 *
 * Renders a `Pressable` trigger with `accessibilityRole="button"`,
 * `accessibilityLabel={summary}` and `accessibilityState={{ expanded, disabled }}`,
 * containing the chevron `Icon` and the summary text (`accessibilityRole="header"`
 * when `headingLevel` is set). The panel renders below only while open, or with
 * `display: 'none'` and hidden from accessibility while closed under `keepMounted`.
 * There is no `aria-controls` equivalent, and focus cannot be handed back to the
 * trigger when the panel closes (native has no focus-within). The chevron mirrors to
 * `chevron-left` under `I18nManager.isRTL` and rotates over `transition`, snapping
 * under reduced motion.
 */
export function Disclosure({
  summary,
  children,
  open,
  defaultOpen = false,
  disabled = false,
  keepMounted = false,
  fullWidth = false,
  headingLevel,
  onToggle,
  overrides,
  ref,
}: DisclosureProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const rtl = I18nManager.isRTL;
  const isControlled = open !== undefined;
  const [internalOpen, setInternalOpen] = React.useState<boolean>(defaultOpen);
  const [focused, setFocused] = React.useState(false);
  const [hovered, setHovered] = React.useState(false);
  const isOpen = isControlled ? open : internalOpen;
  const rotation = React.useRef(new Animated.Value(isOpen ? 1 : 0)).current;

  // react-native-web 0.21 ignores `accessibilityState`, so the disabled state would never reach the
  // DOM, and passing Pressable's own `disabled` would drop the trigger from the tab order — which
  // `accessibilityState.disabled` plus a press guard exists to avoid. So on web the attribute is set
  // on the DOM node itself: the trigger stays focusable and is still announced (and audited) as
  // disabled, which is also what keeps the dimmed trigger out of axe's contrast check, as in Button.
  const triggerRef = React.useRef<ViewInstance>(null);
  React.useEffect(() => {
    if (Platform.OS !== 'web') {
      return;
    }
    const node = triggerRef.current as unknown as WebElement | null;
    if (node === null) {
      return;
    }
    if (disabled) {
      node.setAttribute('aria-disabled', 'true');
    } else {
      node.removeAttribute('aria-disabled');
    }
  }, [disabled]);

  // Controlled: a press is reported at once (the state changes only when the consumer echoes it),
  // and the `open` change that echoes that request does not fire again; any other `open` change
  // reports 'controlled'. Uncontrolled: the press is reported after the new state has committed.
  // Only the latest request is remembered, and the next `open` change clears it. Nothing fires on mount.
  // The latest handler, so the effect below never calls one from an earlier render.
  const onToggleRef = React.useRef(onToggle);
  onToggleRef.current = onToggle;
  const previousOpenRef = React.useRef(isOpen);
  const selfEmittedRef = React.useRef<boolean | null>(null);
  const pendingPressRef = React.useRef(false);
  React.useEffect(() => {
    if (previousOpenRef.current === isOpen) return;
    previousOpenRef.current = isOpen;
    const echo = selfEmittedRef.current === isOpen;
    selfEmittedRef.current = null;
    const pressed = pendingPressRef.current;
    pendingPressRef.current = false;
    if (isControlled) {
      if (!echo) onToggleRef.current?.(isOpen, 'controlled');
    } else if (pressed) {
      onToggleRef.current?.(isOpen, 'pointer');
    }
  }, [isOpen, isControlled]);

  const tokenFor = (binding: DisclosureOverridableBinding): TokenRef =>
    overrides?.[binding] ?? DEFAULT_TOKEN[binding];
  const triggerPaddingBlock = resolveToken(t, tokenFor('triggerPaddingBlock')) as number;
  const triggerPaddingInline = resolveToken(t, tokenFor('triggerPaddingInline')) as number;
  const triggerGap = resolveToken(t, tokenFor('triggerGap')) as number;
  const triggerFontFamily = resolveToken(t, tokenFor('triggerFontFamily')) as string;
  const triggerFontSizeToken = tokenFor('triggerFontSize');
  const triggerFontSize = resolveToken(t, triggerFontSizeToken) as number;
  const triggerFontWeight = resolveToken(t, tokenFor('triggerFontWeight')) as number;
  const triggerLineHeight = resolveToken(t, tokenFor('triggerLineHeight')) as number;
  const triggerRadius = resolveToken(t, tokenFor('triggerRadius')) as number;
  const panelPaddingBlock = resolveToken(t, tokenFor('panelPaddingBlock')) as number;
  const panelPaddingInline = resolveToken(t, tokenFor('panelPaddingInline')) as number;
  const disabledOpacity = resolveToken(t, tokenFor('disabledOpacity')) as number;
  const transitionDuration = resolveToken(t, tokenFor('transition')) as number;

  // `useReducedMotion` reads `false` until the OS answers, so the first run snaps rather
  // than trusting it: nothing animates on first render.
  const animationReadyRef = React.useRef(false);
  React.useEffect(() => {
    const toValue = isOpen ? 1 : 0;
    if (reducedMotion || !animationReadyRef.current) {
      animationReadyRef.current = true;
      rotation.setValue(toValue);
      return;
    }
    Animated.timing(rotation, {
      toValue,
      duration: transitionDuration,
      easing: toEasing(t.motionEasingStandard),
      // A transform, not a layout prop; react-native-web has no native animated module.
      useNativeDriver: Platform.OS !== 'web',
    }).start();
  }, [isOpen, reducedMotion, rotation, transitionDuration, t.motionEasingStandard]);

  const handlePress = (): void => {
    if (disabled) {
      return;
    }
    const next = !isOpen;
    // `Pressable` cannot tell a hardware Enter/Space from a tap, so a press is always 'pointer'.
    if (isControlled) {
      selfEmittedRef.current = next;
      onToggle?.(next, 'pointer');
    } else {
      pendingPressRef.current = true;
      setInternalOpen(next);
    }
  };

  const triggerStyle = ({ pressed }: PressableStateCallbackType): ViewStyle => ({
    flexDirection: 'row',
    alignItems: 'center',
    // Start-aligned so the hover fill hugs the summary; `fullWidth` makes the whole row the trigger.
    alignSelf: fullWidth ? 'stretch' : 'flex-start',
    gap: triggerGap,
    minHeight: t.sizeTargetMin,
    minWidth: t.sizeTargetMin,
    paddingVertical: triggerPaddingBlock,
    paddingHorizontal: triggerPaddingInline,
    borderRadius: triggerRadius,
    backgroundColor: (pressed || hovered) && !disabled ? t.colorBackgroundSubtle : 'transparent',
    borderWidth: t.borderWidthFocus,
    borderColor: focused ? t.colorBorderFocus : 'transparent',
    opacity: disabled ? disabledOpacity : 1,
  });

  const summaryStyle: TextStyle = {
    fontFamily: triggerFontFamily,
    fontSize: triggerFontSize,
    fontWeight: toFontWeight(triggerFontWeight),
    lineHeight: toLineHeight(triggerFontSize, triggerLineHeight),
    color: t.colorForeground,
    flexShrink: 1,
  };

  const chevronStyle: Animated.WithAnimatedValue<ViewStyle> = {
    transform: [
      {
        rotate: rotation.interpolate({
          inputRange: [0, 1],
          outputRange: [CHEVRON_CLOSED, rtl ? CHEVRON_OPEN_RTL : CHEVRON_OPEN],
        }),
      },
    ],
  };

  const panelStyle: ViewStyle = {
    paddingVertical: panelPaddingBlock,
    paddingHorizontal: panelPaddingInline,
    display: isOpen ? 'flex' : 'none',
  };

  return (
    <View ref={ref} testID="Disclosure">
      <Pressable
        ref={triggerRef}
        testID="Disclosure.trigger"
        accessibilityRole="button"
        accessibilityLabel={summary}
        aria-label={summary}
        accessibilityState={{ expanded: isOpen, disabled }}
        // react-native-web 0.21 ignores `accessibilityState`; this mirror is what carries the
        // expanded state to the DOM (native merges both). `aria-disabled` is set in the effect above.
        aria-expanded={isOpen}
        onPress={handlePress}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        onHoverIn={() => setHovered(true)}
        onHoverOut={() => setHovered(false)}
        style={triggerStyle}
      >
        <Animated.View testID="Disclosure.triggerIcon" style={chevronStyle}>
          {/* The glyph tracks the trigger text through the same token as `triggerFontSize`. */}
          <Icon
            name={rtl ? 'chevron-left' : 'chevron-right'}
            color={t.colorForegroundMuted}
            overrides={{ size: triggerFontSizeToken }}
          />
        </Animated.View>
        {/*
          The schema's stopgap: a plain `Text` carrying the same trigger bindings. The package
          `Text` takes all four typography overrides but has no `accessibilityRole` prop, so it
          cannot carry the header role `headingLevel` asks for.
        */}
        <RNText accessibilityRole={headingLevel !== undefined ? 'header' : undefined} style={summaryStyle}>
          {summary}
        </RNText>
      </Pressable>
      {isOpen || keepMounted ? (
        <View
          testID="Disclosure.panel"
          style={panelStyle}
          accessibilityElementsHidden={!isOpen}
          importantForAccessibility={isOpen ? 'auto' : 'no-hide-descendants'}
        >
          {typeof children === 'string' || typeof children === 'number' ? <Text>{children}</Text> : children}
        </View>
      ) : null}
    </View>
  );
}

// packages/lit/src/Disclosure.ts
import { LitElement, css, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { html, literal, type StaticValue } from 'lit/static-html.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';

export type DisclosureHeadingLevel = '2' | '3' | '4' | '5' | '6';

/** Why the disclosure changed state. */
export type DisclosureToggleReason = 'pointer' | 'keyboard' | 'controlled';

/** Detail carried by the `toggle` CustomEvent. */
export interface DisclosureToggleDetail {
  /** The new state. */
  open: boolean;
  /** `pointer` (clicked or tapped), `keyboard` (Enter or Space), `controlled` (the consumer changed `open`). */
  reason: DisclosureToggleReason;
}

/** Overridable style hooks; see the `overrides` property. `triggerColor`, `triggerBackgroundHover`, `icon`, `panelColor`, `focusRing`, `focusRingWidth` and `minTarget` are locked and excluded. */
export type DisclosureOverridableBinding =
  | 'triggerPaddingBlock'
  | 'triggerPaddingInline'
  | 'triggerGap'
  | 'triggerFontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight'
  | 'triggerLineHeight'
  | 'triggerRadius'
  | 'panelPaddingBlock'
  | 'panelPaddingInline'
  | 'disabledOpacity'
  | 'transition';

const HOOKS: Record<DisclosureOverridableBinding, string> = {
  triggerPaddingBlock: '--ds-disclosure-trigger-padding-block',
  triggerPaddingInline: '--ds-disclosure-trigger-padding-inline',
  triggerGap: '--ds-disclosure-trigger-gap',
  triggerFontFamily: '--ds-disclosure-trigger-font-family',
  triggerFontSize: '--ds-disclosure-trigger-font-size',
  triggerFontWeight: '--ds-disclosure-trigger-font-weight',
  triggerLineHeight: '--ds-disclosure-trigger-line-height',
  triggerRadius: '--ds-disclosure-trigger-radius',
  panelPaddingBlock: '--ds-disclosure-panel-padding-block',
  panelPaddingInline: '--ds-disclosure-panel-padding-inline',
  disabledOpacity: '--ds-disclosure-disabled-opacity',
  transition: '--ds-disclosure-transition',
};

const HEADINGS: Record<DisclosureHeadingLevel, StaticValue> = {
  '2': literal`h2`,
  '3': literal`h3`,
  '4': literal`h4`,
  '5': literal`h5`,
  '6': literal`h6`,
};

function isHeadingLevel(value: unknown): value is DisclosureHeadingLevel {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(HEADINGS, value);
}

/**
 * `<ds-disclosure>` — Disclosure (category: container, APG pattern: disclosure).
 *
 * `<ds-disclosure summary="Advanced options">…</ds-disclosure>` renders a
 * native `<button aria-expanded aria-controls>` trigger in its shadow root and
 * the panel as the default `<slot>`, which exists only while open. Light-DOM
 * children that are not assigned to a slot are neither rendered nor in the
 * accessibility tree, so a closed panel is genuinely gone — the consumer's
 * nodes are never given `hidden`. With `keepMounted` the slot is always
 * rendered and its wrapper gets `hidden` while closed, which is required when
 * the panel holds form fields (a `<ds-form>` reads `currentOpen` and
 * `keepMounted` and skips fields inside a closed disclosure without it).
 *
 * Uncontrolled from `defaultOpen` unless `open` is set; a controlled element
 * shows the new state only once `open` changes. Every change dispatches a
 * composed `toggle` CustomEvent with `{ open, reason }` after the state changes.
 *
 * ## When to use
 *
 * Use a Disclosure to hide secondary content that some users need and most do
 * not: optional settings, long explanations, a list of details behind a
 * summary count. Stack several to make an accordion — each is independent.
 * Set `headingLevel` when the summaries are section titles so they appear in
 * the outline.
 *
 * @fires toggle - Fired after the state changes with `{ open, reason }` in `detail`.
 * @slot - The panel content. Rendered only while open (always, but hidden while closed, with `keep-mounted`).
 */
@customElement('ds-disclosure')
export class DsDisclosure extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-disclosure-trigger-padding-block: var(--space-sm);
      --ds-disclosure-trigger-padding-inline: var(--space-sm);
      --ds-disclosure-trigger-gap: var(--space-2);
      --ds-disclosure-trigger-font-family: var(--font-family-body);
      --ds-disclosure-trigger-font-size: var(--font-size-md);
      --ds-disclosure-trigger-font-weight: var(--font-weight-medium);
      --ds-disclosure-trigger-line-height: var(--font-line-height-normal);
      --ds-disclosure-trigger-radius: var(--radius-md);
      --ds-disclosure-panel-padding-block: var(--space-sm);
      --ds-disclosure-panel-padding-inline: var(--space-sm);
      --ds-disclosure-disabled-opacity: var(--opacity-disabled);
      --ds-disclosure-transition: var(--motion-duration-base);
      /* Locked: no overrides entry, but the hook stays themeable from page CSS. */
      --ds-disclosure-trigger-color: var(--color-foreground);
      --ds-disclosure-trigger-background-hover: var(--color-background-subtle);
      --ds-disclosure-icon: var(--color-foreground-muted);
      --ds-disclosure-panel-color: var(--color-foreground);
      --ds-disclosure-focus-ring: var(--color-border-focus);
      --ds-disclosure-focus-ring-width: var(--border-width-focus);
      --ds-disclosure-min-target: var(--size-target-min);
    }

    :host([hidden]) {
      display: none;
    }

    /* The heading has no styling of its own — the button carries it. */
    .heading {
      margin: 0;
      padding: 0;
      font: inherit;
    }

    [data-part='trigger'] {
      box-sizing: border-box;
      display: inline-flex;
      align-items: center;
      gap: var(--ds-disclosure-trigger-gap);
      min-inline-size: var(--ds-disclosure-min-target);
      min-block-size: var(--ds-disclosure-min-target);
      margin: 0;
      padding-block: var(--ds-disclosure-trigger-padding-block);
      padding-inline: var(--ds-disclosure-trigger-padding-inline);
      border: 0;
      border-radius: var(--ds-disclosure-trigger-radius);
      font-family: var(--ds-disclosure-trigger-font-family);
      font-size: var(--ds-disclosure-trigger-font-size);
      font-weight: var(--ds-disclosure-trigger-font-weight);
      line-height: var(--ds-disclosure-trigger-line-height);
      text-align: start;
      color: var(--ds-disclosure-trigger-color);
      /* At rest the trigger has no fill; no token expresses its absence. */
      background: transparent;
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
    }

    /* fullWidth: the whole row is the hit area; icon and summary stay at the start. */
    :host([full-width]) [data-part='trigger'] {
      display: flex;
      inline-size: 100%;
    }

    /* triggerBackgroundHover: pointer hover and pressed state, instant, suppressed while disabled */
    :host(:not([disabled])) [data-part='trigger']:is(:hover, :active) {
      background: var(--ds-disclosure-trigger-background-hover);
    }

    [data-part='trigger']:focus-visible {
      outline: var(--ds-disclosure-focus-ring-width) solid var(--ds-disclosure-focus-ring);
      outline-offset: var(--ds-disclosure-focus-ring-width);
    }

    :host([disabled]) [data-part='trigger'] {
      opacity: var(--ds-disclosure-disabled-opacity);
      cursor: not-allowed;
    }

    /* icon: the wrapper the Disclosure owns carries the colour and the rotation; the composed
       <ds-icon inline> is never restyled and tracks the trigger's font size through 1em. */
    [data-part='triggerIcon'] {
      display: inline-flex;
      flex: none;
      color: var(--ds-disclosure-icon);
      transition: transform var(--ds-disclosure-transition) var(--motion-easing-standard);
    }
    [aria-expanded='true'] [data-part='triggerIcon'] {
      transform: rotate(90deg);
    }
    :host(:dir(rtl)) [data-part='triggerIcon'] {
      transform: scaleX(-1);
    }
    :host(:dir(rtl)) [aria-expanded='true'] [data-part='triggerIcon'] {
      transform: scaleX(-1) rotate(90deg);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='triggerIcon'] {
        transition: none;
      }
    }

    [data-part='panel'] {
      padding-block: var(--ds-disclosure-panel-padding-block);
      padding-inline: var(--ds-disclosure-panel-padding-inline);
      color: var(--ds-disclosure-panel-color);
    }
    [data-part='panel'][hidden] {
      display: none;
    }
  `;

  /** The trigger's label. Also its accessible name. Says what will be revealed. */
  @property() accessor summary = '';

  /** Controlled open state. Omit for an uncontrolled disclosure. */
  @property({ type: Boolean, reflect: true }) accessor open: boolean | undefined;

  /** Initial state for an uncontrolled disclosure. */
  @property({ type: Boolean, attribute: 'default-open' }) accessor defaultOpen = false;

  /** The trigger cannot be activated. Stays focusable and is announced as disabled; the panel keeps its current state. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Keep the panel in the tree while closed (hidden, not unmounted). Required when the panel contains form fields. */
  @property({ type: Boolean, reflect: true, attribute: 'keep-mounted' }) accessor keepMounted = false;

  /** The trigger spans the width of its row, so the whole row is the hit area. */
  @property({ type: Boolean, reflect: true, attribute: 'full-width' }) accessor fullWidth = false;

  /** When set, the trigger is wrapped in a heading of this level so it appears in the outline. */
  @property({ attribute: 'heading-level' }) accessor headingLevel: DisclosureHeadingLevel | undefined;

  /** Per-instance style overrides: `{ triggerRadius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>> | undefined;

  /** Uncontrolled open state (seeded from `defaultOpen`). */
  @state() private accessor internalOpen = false;

  @query('[data-part=trigger]') private accessor triggerEl!: HTMLButtonElement | null;

  /** The resolved state rendered at the last update; `undefined` before the first. */
  private renderedOpen: boolean | undefined;

  /** The state the last user activation asked for, so the resulting prop change is not re-reported as `controlled`. */
  private requestedOpen: boolean | undefined;

  /**
   * Focus entered the panel and has not demonstrably moved elsewhere. Unassigning a focused node from the slot can
   * drop focus to the body without a focusout, so the flag is cleared only when focus lands somewhere known.
   */
  private focusWithinPanel = false;

  /** Set when a close happens while focus is within the panel; resolved after the render that removes it. */
  private restoreFocusPending = false;

  /** Whether the panel is currently open (controlled `open`, else the uncontrolled state). */
  get currentOpen(): boolean {
    return this.open ?? this.internalOpen;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Disclosure');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (!this.hasUpdated) {
      this.internalOpen = this.defaultOpen;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    // Closing removes (or hides) the panel: focus within it is handed to the trigger once the render lands,
    // whether the close came from the trigger or from a controlled `open` change.
    if (this.hasUpdated && this.renderedOpen === true && !this.currentOpen && this.focusWithinPanel) {
      this.focusWithinPanel = false;
      this.restoreFocusPending = true;
    }
  }

  protected override render(): TemplateResult {
    const isOpen = this.currentOpen;
    const panelExists = isOpen || this.keepMounted;
    const trigger = html`
      <button
        data-part="trigger"
        part="trigger"
        type="button"
        aria-expanded=${isOpen ? 'true' : 'false'}
        aria-controls=${ifDefined(panelExists ? 'panel' : undefined)}
        aria-disabled=${ifDefined(this.disabled ? 'true' : undefined)}
        @click=${this.handleClick}
      >
        <span data-part="triggerIcon" part="triggerIcon"
          ><ds-icon name="chevron-right" inline></ds-icon
        ></span>
        <span>${this.summary}</span>
      </button>
    `;
    const level = this.headingLevel;
    const heading = isHeadingLevel(level)
      ? html`<${HEADINGS[level]} class="heading">${trigger}</${HEADINGS[level]}>`
      : trigger;

    return html`
      ${heading}
      ${panelExists
        ? html`<div
            id="panel"
            data-part="panel"
            part="panel"
            ?hidden=${!isOpen}
            @focusin=${this.handlePanelFocusIn}
            @focusout=${this.handlePanelFocusOut}
          ><slot></slot></div>`
        : nothing}
    `;
  }

  protected override updated(changed: PropertyValues): void {
    const now = this.currentOpen;
    const previous = this.renderedOpen;
    this.renderedOpen = now;
    if (this.restoreFocusPending) {
      this.restoreFocusPending = false;
      this.restoreFocus();
    }
    if (!changed.has('open') && !changed.has('internalOpen')) return;
    const requested = this.requestedOpen;
    this.requestedOpen = undefined;
    // A consumer-driven change of `open` that no user activation asked for.
    if (previous !== undefined && previous !== now && changed.has('open') && requested !== now) {
      this.dispatchToggle(now, 'controlled');
    }
  }

  private handleClick(event: MouseEvent): void {
    if (this.disabled) {
      event.preventDefault();
      return;
    }
    const next = !this.currentOpen;
    // A keyboard activation of a native button produces a click with detail 0.
    const reason: DisclosureToggleReason = event.detail === 0 ? 'keyboard' : 'pointer';
    if (this.open === undefined) {
      this.internalOpen = next;
    } else {
      // Controlled: the new state shows only once the consumer sets `open`.
      this.requestedOpen = next;
    }
    this.dispatchToggle(next, reason);
  }

  private dispatchToggle(open: boolean, reason: DisclosureToggleReason): void {
    this.dispatchEvent(
      new CustomEvent<DisclosureToggleDetail>('toggle', {
        detail: { open, reason },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private handlePanelFocusIn(): void {
    this.focusWithinPanel = true;
  }

  private handlePanelFocusOut(event: FocusEvent): void {
    const to = event.relatedTarget;
    // Slotted panel content is the host's light DOM; the trigger lives in the shadow root, so it is not contained.
    if (to instanceof Node && (to === this || !this.contains(to))) {
      this.focusWithinPanel = false;
    }
  }

  /** Focus still inside the closed panel, or dropped to the body when the panel went away, moves to the trigger. */
  private restoreFocus(): void {
    const active = document.activeElement;
    const lost = active === null || active === document.body || (active !== this && this.contains(active));
    if (lost) this.triggerEl?.focus();
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as DisclosureOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-disclosure': DsDisclosure;
  }
}
