// packages/rn/src/Divider.tsx
import * as React from 'react';
import { View } from 'react-native';
import type { ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Text } from './Text';
import { useTheme } from './theme';
import type { Tokens } from './theme';

export type DividerOrientation = 'horizontal' | 'vertical';
export type DividerSpacing = 'none' | 'tight' | 'normal' | 'loose';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type DividerOverridableBinding = 'color' | 'thickness' | 'spacing' | 'labelSize' | 'labelGap' | 'fontFamily';

export interface DividerProps {
  /**
   * Vertical dividers sit between inline siblings (toolbar groups) and stretch to the row
   * height. They need a row (a horizontal Stack with align stretch) or a parent with a
   * definite height; otherwise a vertical divider has no height and draws nothing.
   */
  orientation?: DividerOrientation | undefined;
  /**
   * Optional text in the middle of a horizontal divider ("or", "Earlier today"). Turns the
   * divider from decorative into a labelled separator. Ignored on a vertical divider, with
   * a development warning. An empty string is no label.
   */
  label?: string | undefined;
  /**
   * Expose as a separator to assistive technology. React Native has no separator role, so
   * without a `label` this has no observable effect and warns in development.
   */
  semantic?: boolean | undefined;
  /** Space on both sides along the cross axis, from the layout rhythm, for dividers used outside a Stack that already spaces them. */
  spacing?: DividerSpacing | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<DividerOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root `View`, for measurement or accessibility focus. */
  ref?: React.Ref<ViewInstance> | undefined;
}

const SPACING_TOKEN = {
  tight: 'layoutGapTight',
  normal: 'layoutGapNormal',
  loose: 'layoutGapLoose',
} as const satisfies Record<Exclude<DividerSpacing, 'none'>, keyof Tokens>;

/**
 * Divider — a line, decorative by default. A `label` centers text between two line
 * segments and makes the line meaningful rather than furniture.
 *
 * The line is an inner `View` `border.width.thin` thick along the cross axis in
 * `color.border`, inside a root `View` that carries `spacing` as padding on that axis;
 * root and line both `alignSelf: 'stretch'` in either orientation, so a divider in a parent
 * that does not stretch its children still draws. `spacing: none` renders no space, so
 * `overrides.spacing` is a no-op there. There is no `separator` role on React Native:
 * a decorative root hides itself and its line (`accessibilityElementsHidden` +
 * `importantForAccessibility="no-hide-descendants"`); a labelled root is a row (`gap` from
 * `labelGap`) of two hidden line Views around `Text size="sm" tone="muted"`, which is read.
 * The label Text sits in a plain unflexed View carrying the `Divider.label` hook, since Text
 * takes no `testID`. `labelSize`/`fontFamily` overrides reach Text's `fontSize`/`fontFamily`.
 */
export function Divider({
  orientation = 'horizontal',
  label,
  semantic = false,
  spacing = 'none',
  overrides,
  ref,
}: DividerProps): React.JSX.Element {
  const { tokens: t } = useTheme();

  const hasLabelText = label !== undefined && label !== '';
  const labelIgnored = hasLabelText && orientation === 'vertical';
  const labelled = hasLabelText && orientation === 'horizontal';

  // Keyed on `label` and `orientation`: warns when the ignored combination appears or changes.
  React.useEffect(() => {
    if (__DEV__ && labelIgnored) {
      console.warn('Divider: `label` is ignored on a vertical divider — a vertical line has no room for centered text.');
    }
  }, [label, orientation, labelIgnored]);

  // Keyed on `semantic` and whether a label is in effect, so a semantic vertical divider
  // whose label is ignored warns here too.
  React.useEffect(() => {
    if (__DEV__ && semantic && !labelled) {
      console.warn(
        'Divider: `semantic` has no observable effect on React Native without a `label` — there is no native separator role, so the boundary is silent to assistive technology.',
      );
    }
  }, [semantic, labelled]);

  const styles = React.useMemo(() => {
    const thickness = overrides?.thickness ? (resolveToken(t, overrides.thickness) as number) : t.borderWidthThin;
    const color = overrides?.color ? (resolveToken(t, overrides.color) as string) : t.colorBorder;
    // `spacing: none` is the off state: no space and no token, so an override changes nothing.
    const space =
      spacing === 'none'
        ? undefined
        : overrides?.spacing
          ? (resolveToken(t, overrides.spacing) as number)
          : t[SPACING_TOKEN[spacing]];
    const vertical = orientation === 'vertical';
    const gap = overrides?.labelGap ? (resolveToken(t, overrides.labelGap) as number) : t.layoutGapNormal;
    const root: ViewStyle = vertical
      ? { flexDirection: 'row', alignSelf: 'stretch', paddingHorizontal: space }
      : { alignSelf: 'stretch', paddingVertical: space };
    const labelledRoot: ViewStyle = {
      alignSelf: 'stretch',
      paddingVertical: space,
      flexDirection: 'row',
      alignItems: 'center',
      gap,
    };
    const line: ViewStyle = vertical
      ? { width: thickness, alignSelf: 'stretch', backgroundColor: color }
      : { height: thickness, alignSelf: 'stretch', backgroundColor: color };
    const segment: ViewStyle = { flex: 1, height: thickness, backgroundColor: color };
    return { root, labelledRoot, line, segment };
  }, [t, orientation, spacing, overrides]);

  if (labelled) {
    return (
      <View ref={ref} style={styles.labelledRoot} testID="Divider">
        <View style={styles.segment} accessibilityElementsHidden importantForAccessibility="no" testID="Divider.line" />
        <View testID="Divider.label">
          <Text size="sm" tone="muted" overrides={{ fontSize: overrides?.labelSize, fontFamily: overrides?.fontFamily }}>
            {label}
          </Text>
        </View>
        <View style={styles.segment} accessibilityElementsHidden importantForAccessibility="no" testID="Divider.line" />
      </View>
    );
  }

  return (
    <View
      ref={ref}
      style={styles.root}
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      testID="Divider"
    >
      <View style={styles.line} testID="Divider.line" />
    </View>
  );
}

// packages/lit/src/Divider.ts
import { LitElement, css, html, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import type { TextOverridableBinding } from './Text.js';

export type DividerOrientation = 'horizontal' | 'vertical';
export type DividerSpacing = 'none' | 'tight' | 'normal' | 'loose';

/**
 * Overridable style hooks; see the `overrides` property. The accessibility-bearing `labelColor` is
 * locked and excluded. `labelSize` and `fontFamily` reach the composed label `Text` through its own
 * `overrides` (as `fontSize` and `fontFamily`) rather than a `--ds-divider-*` hook: Divider does not
 * style the Text itself, and page CSS reaches the label through Text's hooks.
 */
export type DividerOverridableBinding = 'color' | 'thickness' | 'spacing' | 'labelSize' | 'labelGap' | 'fontFamily';

/** The bindings Divider paints itself, and the host hook each one sets. */
const HOOKS: Partial<Record<DividerOverridableBinding, string>> = {
  color: '--ds-divider-color',
  thickness: '--ds-divider-thickness',
  spacing: '--ds-divider-spacing',
  labelGap: '--ds-divider-label-gap',
};

/** Divider bindings forwarded to the composed label Text's `overrides`. */
const LABEL_FORWARDS: ReadonlyArray<[DividerOverridableBinding, TextOverridableBinding]> = [
  ['labelSize', 'fontSize'],
  ['fontFamily', 'fontFamily'],
];

/**
 * `<ds-divider>` — Divider (category: layout, role: separator).
 *
 * The host is the line: it carries the thickness on the cross axis and the
 * shadow root paints it as the `line` part. `<ds-divider>` is decorative and
 * hidden from assistive technology (`aria-hidden="true"`); `<ds-divider
 * semantic>` or `<ds-divider label="or">` is exposed as `role="separator"`
 * with `aria-orientation`. A label renders in the shadow root as a
 * `<ds-text size="sm" tone="muted">` between two aria-hidden line segments and
 * names the separator through `aria-label` on the host — ids do not cross the
 * shadow root, and a separator's children are presentational.
 *
 * ## When to use
 *
 * Between items in a dense list where whitespace alone does not separate
 * them, between toolbar groups (`orientation="vertical"`), and with a `label`
 * as an "or" between alternatives or a date heading in a feed. Use `spacing`
 * when the divider stands outside a Stack.
 *
 * ## When not to use
 *
 * Not between page sections (use section spacing and headings), not under a
 * heading as decoration, and not as a heading substitute.
 */
@customElement('ds-divider')
export class DsDivider extends LitElement {
  static override styles: CSSResult = css`
    :host {
      --ds-divider-color: var(--color-border);
      --ds-divider-thickness: var(--border-width-thin);
      --ds-divider-label-gap: var(--layout-gap-normal);
      display: flex;
      box-sizing: border-box;
      block-size: var(--ds-divider-thickness);
    }

    :host([hidden]) {
      display: none;
    }

    /* The host sizes the line on the cross axis; the line part paints it along the other. */
    [data-part='line'] {
      flex: 1 1 auto;
      background-color: var(--ds-divider-color);
    }

    /* stretches in a flex/grid row (block-size stays auto so align-self: stretch applies) and fills a parent with a definite height */
    :host([orientation='vertical']) {
      display: inline-flex;
      inline-size: var(--ds-divider-thickness);
      block-size: auto;
      min-block-size: 100%;
      align-self: stretch;
    }

    /* spacing: layout.gap.{spacing}; none is the off state, so the hook (and any override of it) applies only once a value is chosen */
    :host([spacing='tight']) {
      --ds-divider-spacing: var(--layout-gap-tight);
    }
    :host([spacing='normal']) {
      --ds-divider-spacing: var(--layout-gap-normal);
    }
    :host([spacing='loose']) {
      --ds-divider-spacing: var(--layout-gap-loose);
    }
    :host([spacing]:not([spacing='none'])) {
      margin-block: var(--ds-divider-spacing);
    }
    :host([orientation='vertical'][spacing]:not([spacing='none'])) {
      margin-block: 0;
      margin-inline: var(--ds-divider-spacing);
    }

    /* labelled (horizontal only): the host is a row of line, label, line, and the lines paint */
    :host([data-labelled]) {
      align-items: center;
      block-size: auto;
      gap: var(--ds-divider-label-gap);
    }

    :host([data-labelled]) [data-part='line'] {
      flex: 1 1 0;
      block-size: var(--ds-divider-thickness);
    }
  `;

  /**
   * Vertical dividers sit between inline siblings (toolbar groups) and stretch to the row height:
   * `inline-block` with `block-size: auto; align-self: stretch; min-block-size: 100%`. They need a
   * flex or grid row (a horizontal Stack with align stretch) or a parent with a definite height; in
   * plain block flow a vertical divider has no height and draws nothing.
   */
  @property({ type: String, reflect: true }) accessor orientation: DividerOrientation = 'horizontal';

  /**
   * Optional text in the middle of a horizontal divider ("or", "Earlier
   * today"). Turns the divider from decorative into a labelled separator
   * (`semantic` is implied). Ignored on a vertical divider, with a development
   * warning: a vertical line has no room for centered text. An ignored label
   * implies nothing either — a vertical divider is semantic only when
   * `semantic` says so. An empty string is no label.
   */
  @property({ type: String }) accessor label: string | undefined;

  /**
   * Expose as a separator to assistive technology. Leave false for purely visual lines between list
   * rows; set true (or provide a label) when the divider marks a real boundary between sections
   * that a screen-reader user should hear.
   */
  @property({ type: Boolean, reflect: true }) accessor semantic = false;

  /** Space on both sides along the cross axis, from the layout rhythm, for dividers used outside a Stack. */
  @property({ type: String, reflect: true }) accessor spacing: DividerSpacing = 'none';

  /** Per-instance style overrides: `{ color: 'color.border.strong' }`. `labelColor` is locked and ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<DividerOverridableBinding, TokenRef | undefined>> | undefined;

  /** The ignored label last warned about, so the warning fires once per appearance or change. */
  private warnedLabel: string | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Divider');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('semantic') || changed.has('label') || changed.has('orientation')) {
      this.syncSemantics();
    }
    // Which bindings are in effect depends on `spacing` and on whether a label renders, so the
    // hooks are rewritten when those change too, not only when `overrides` does.
    if (
      changed.has('overrides') ||
      changed.has('spacing') ||
      changed.has('label') ||
      changed.has('orientation')
    ) {
      this.applyOverrides();
    }
    if (changed.has('label') || changed.has('orientation')) this.warnIgnoredLabel();
  }

  /** The label in effect: none on a vertical divider, and an empty string is no label. */
  private get effectiveLabel(): string | undefined {
    return this.orientation === 'vertical' ? undefined : this.label || undefined;
  }

  protected override render(): TemplateResult {
    const label = this.effectiveLabel;
    if (label === undefined) {
      return html`<span part="line" data-part="line" aria-hidden="true"></span>`;
    }
    return html`
      <span part="line" data-part="line" aria-hidden="true"></span>
      <ds-text
        part="label"
        data-part="label"
        size="sm"
        tone="muted"
        element="span"
        .overrides=${this.labelOverrides()}
      >${label}</ds-text>
      <span part="line" data-part="line" aria-hidden="true"></span>
    `;
  }

  /** `labelSize` → Text `fontSize`, `fontFamily` → Text `fontFamily`; only bindings the author overrode. */
  private labelOverrides(): Partial<Record<TextOverridableBinding, TokenRef | undefined>> | undefined {
    const forwarded: Partial<Record<TextOverridableBinding, TokenRef | undefined>> = {};
    let any = false;
    for (const [from, to] of LABEL_FORWARDS) {
      const ref = this.overrides?.[from];
      if (ref !== undefined) {
        forwarded[to] = ref;
        any = true;
      }
    }
    return any ? forwarded : undefined;
  }

  /**
   * Decorative → aria-hidden; semantic or labelled → role=separator with
   * aria-orientation (and the label as its name, since a separator's content
   * is presentational). Plain host attributes, not ElementInternals, so that
   * accessible-name readers observe them.
   */
  private syncSemantics(): void {
    const label = this.effectiveLabel;
    const semantic = this.semantic || label !== undefined;
    this.toggleAttribute('data-labelled', label !== undefined);
    if (semantic) {
      this.removeAttribute('aria-hidden');
      this.setAttribute('role', 'separator');
      this.setAttribute('aria-orientation', this.orientation);
    } else {
      this.setAttribute('aria-hidden', 'true');
      this.removeAttribute('role');
      this.removeAttribute('aria-orientation');
    }
    if (label !== undefined) this.setAttribute('aria-label', label);
    else this.removeAttribute('aria-label');
  }

  private warnIgnoredLabel(): void {
    const ignored = this.orientation === 'vertical' && this.label ? this.label : undefined;
    if (ignored !== undefined && ignored !== this.warnedLabel && import.meta.env.DEV) {
      console.warn('ds-divider: `label` is ignored on a vertical divider: a vertical line has no room for centered text.');
    }
    this.warnedLabel = ignored;
  }

  /**
   * Overrides change values, never presence: `spacing: none` renders no space and takes no hook,
   * and the label bindings apply only while a label is in effect.
   */
  private applyOverrides(): void {
    const labelled = this.effectiveLabel !== undefined;
    for (const binding of Object.keys(HOOKS) as DividerOverridableBinding[]) {
      const hook = HOOKS[binding];
      if (hook === undefined) continue;
      const inEffect = binding === 'spacing' ? this.spacing !== 'none' : binding === 'labelGap' ? labelled : true;
      const ref = inEffect ? this.overrides?.[binding] : undefined;
      if (ref === undefined) this.style.removeProperty(hook);
      else this.style.setProperty(hook, cssVar(ref));
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-divider': DsDivider;
  }
}
