// packages/react/src/Feed.tsx
import {
  forwardRef,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Button, type ButtonOverridableBinding } from './Button';
import { Card, type CardOverridableBinding } from './Card';
import { ProgressBar } from './ProgressBar';
import { Text, type TextOverridableBinding } from './Text';
import './Feed.css';

/** The schema declares the values as strings; numbers are accepted for ergonomics. */
export type FeedHeadingLevel = '2' | '3' | '4' | 2 | 3 | 4;

/** One article. `heading` names it (a Heading inside the article's Card); `timestamp` is ISO and
 * rendered relative, with the absolute time as its title; `unread` marks items not yet seen. */
export interface FeedItem {
  id: string;
  heading: string;
  timestamp: string;
  content: ReactNode;
  actions?: ReactNode;
  unread?: boolean;
}

const COPY = {
  showNew: 'Show {count} new',
  loading: 'Loading more',
  end: 'You are all caught up.',
  unread: 'unread',
  position: '{index} of {total}',
  empty: 'Nothing here yet.',
};

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type FeedOverridableBinding =
  | 'itemGap'
  | 'articleInset'
  | 'unreadBorderWidth'
  | 'timestampSize'
  | 'newItemsOffset'
  | 'loadingInset'
  | 'endMessageInset'
  | 'endMessageSize'
  | 'fontFamily';

/** Bindings owned by the root; `articleInset` forwards to each composed Card's own padding hooks,
 * and `timestampSize`/`endMessageSize`/`fontFamily` forward into the composed Text (and, for
 * `fontFamily`, the new-items Button) instances' own `overrides`, since those components already
 * own that hook. */
const ROOT_OVERRIDE_HOOK: Partial<Record<FeedOverridableBinding, string>> = {
  itemGap: '--ds-feed-item-gap',
  unreadBorderWidth: '--ds-feed-unread-border-width',
  newItemsOffset: '--ds-feed-new-items-offset',
  loadingInset: '--ds-feed-loading-inset',
  endMessageInset: '--ds-feed-end-message-inset',
};

function overridesToStyle(overrides: Partial<Record<FeedOverridableBinding, TokenRef>>): {
  rootStyle: CSSProperties;
  articleOverrides: Partial<Record<CardOverridableBinding, TokenRef>>;
  timestampOverrides: Partial<Record<TextOverridableBinding, TokenRef>>;
  endMessageOverrides: Partial<Record<TextOverridableBinding, TokenRef>>;
  newItemsButtonOverrides: Partial<Record<ButtonOverridableBinding, TokenRef>>;
} {
  const rootStyle: Record<string, string> = {};
  const articleOverrides: Partial<Record<CardOverridableBinding, TokenRef>> = {};
  const timestampOverrides: Partial<Record<TextOverridableBinding, TokenRef>> = {};
  const endMessageOverrides: Partial<Record<TextOverridableBinding, TokenRef>> = {};
  const newItemsButtonOverrides: Partial<Record<ButtonOverridableBinding, TokenRef>> = {};

  for (const binding of Object.keys(overrides) as FeedOverridableBinding[]) {
    const tokenRef = overrides[binding];
    if (!tokenRef) continue;
    const hook = ROOT_OVERRIDE_HOOK[binding];
    if (hook) {
      rootStyle[hook] = cssVar(tokenRef);
      continue;
    }
    switch (binding) {
      case 'articleInset':
        articleOverrides.paddingBlock = tokenRef;
        articleOverrides.paddingInline = tokenRef;
        break;
      case 'timestampSize':
        timestampOverrides.fontSize = tokenRef;
        break;
      case 'endMessageSize':
        endMessageOverrides.fontSize = tokenRef;
        break;
      case 'fontFamily':
        timestampOverrides.fontFamily = tokenRef;
        endMessageOverrides.fontFamily = tokenRef;
        newItemsButtonOverrides.fontFamily = tokenRef;
        break;
    }
  }

  return { rootStyle: rootStyle as CSSProperties, articleOverrides, timestampOverrides, endMessageOverrides, newItemsButtonOverrides };
}

/** Elements the Ctrl+Home/Ctrl+End feed commands can escape to. */
const FOCUSABLE = 'a[href], button, input, select, textarea, [tabindex]:not([tabindex="-1"]), [contenteditable="true"]';

/** Moves focus to the first focusable element after `root` in document order. */
function focusAfter(root: HTMLElement): void {
  const candidates = Array.from(root.ownerDocument.querySelectorAll<HTMLElement>(FOCUSABLE)).filter(
    (el) => !root.contains(el),
  );
  candidates.find((el) => (root.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0)?.focus();
}

/** Moves focus to the last focusable element before `root` in document order. */
function focusBefore(root: HTMLElement): void {
  const candidates = Array.from(root.ownerDocument.querySelectorAll<HTMLElement>(FOCUSABLE)).filter(
    (el) => !root.contains(el),
  );
  candidates.filter((el) => (root.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_PRECEDING) !== 0).pop()?.focus();
}

/** jsdom (and older browsers) have no `matchMedia`; treat that as "no preference". */
function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function'
    ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
    : false;
}

const RELATIVE_TIME = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });
const RELATIVE_DIVISIONS: { amount: number; unit: Intl.RelativeTimeFormatUnit }[] = [
  { amount: 60, unit: 'seconds' },
  { amount: 60, unit: 'minutes' },
  { amount: 24, unit: 'hours' },
  { amount: 7, unit: 'days' },
  { amount: 4.34524, unit: 'weeks' },
  { amount: 12, unit: 'months' },
  { amount: Number.POSITIVE_INFINITY, unit: 'years' },
];

/** No `copy.*` token covers relative time ("3 min ago"); this leans on the platform's own i18n
 * formatting rather than inventing English strings, matching the Lit generation's locale choice. */
function formatRelativeTime(iso: string): string {
  let duration = (new Date(iso).getTime() - Date.now()) / 1000;
  for (const division of RELATIVE_DIVISIONS) {
    if (Math.abs(duration) < division.amount) {
      return RELATIVE_TIME.format(Math.round(duration), division.unit);
    }
    duration /= division.amount;
  }
  return RELATIVE_TIME.format(Math.round(duration), 'years');
}

function formatAbsoluteTime(iso: string): string {
  return new Date(iso).toLocaleString();
}

export interface FeedProps extends Omit<ComponentPropsWithoutRef<'div'>, 'children' | 'role' | 'aria-label' | 'aria-busy'> {
  /** What the feed contains ("Activity", "Notifications"). */
  label: string;
  /** Articles, newest first. */
  items: FeedItem[];
  /** More items exist beyond the last; the feed asks for them with `onLoadMore` as the end approaches. */
  hasMore?: boolean;
  /** More items are being fetched; a loading indicator is shown after the last article and the feed is `aria-busy`. */
  loading?: boolean;
  /**
   * Number of newer items available above (from polling or a socket). The feed does not insert
   * them — that would shift what the reader is looking at — it shows a "Show {count} new" button
   * at the top which prepends and scrolls.
   */
  newItemsCount?: number;
  /** Heading level for article headings, matching the page outline. */
  headingLevel?: FeedHeadingLevel;
  /** Shown after the last item when `hasMore` is false. Defaults to `copy.end`. */
  endMessage?: string;
  /** Fired when the last rendered article is within one screen of view (or on Ctrl+End with `hasMore`). */
  onLoadMore?: () => void;
  /** Fired when the new-items button is pressed; the caller prepends the items and clears `newItemsCount`. */
  onShowNew?: () => void;
  /** Fired with an item id when it has been substantially visible for a moment (mark as read). */
  onItemVisible?: (id: string) => void;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<FeedOverridableBinding, TokenRef>>;
}

/**
 * Feed — Design Schema, category: container.
 *
 * When to use:
 * Use a Feed for a stream of similar, time-ordered items whose total is unknown or large:
 * activity, notifications, comments, posts, audit events. Each item is a Card with a heading and a
 * time. Use `newItemsCount` with `onShowNew` for live streams rather than inserting items while the
 * reader is looking; use `onItemVisible` to mark things read.
 */
export const Feed = forwardRef<HTMLDivElement, FeedProps>(function Feed(
  {
    label,
    items,
    hasMore = false,
    loading = false,
    newItemsCount,
    headingLevel = '3',
    endMessage,
    onLoadMore,
    onShowNew,
    onItemVisible,
    overrides,
    className,
    style,
    ...rest
  },
  ref,
) {
  const generatedId = useId();
  const baseId = `ds-feed${generatedId}`;

  const rootRef = useRef<HTMLDivElement | null>(null);
  useImperativeHandle(ref, () => rootRef.current as HTMLDivElement, []);

  const articleRefs = useRef(new Map<string, HTMLElement>());
  const newItemsButtonRef = useRef<HTMLButtonElement | null>(null);

  const onLoadMoreRef = useRef(onLoadMore);
  const onItemVisibleRef = useRef(onItemVisible);
  useEffect(() => {
    onLoadMoreRef.current = onLoadMore;
    onItemVisibleRef.current = onItemVisible;
  });

  // The feed never inserts new items itself: pressing "Show new" only asks the caller to prepend
  // them. Once that lands (the first item's id changes), focus moves to it.
  const pendingFocusNewRef = useRef(false);
  const lastFirstIdRef = useRef(items[0]?.id);
  useEffect(() => {
    if (pendingFocusNewRef.current && items[0] && items[0].id !== lastFirstIdRef.current) {
      pendingFocusNewRef.current = false;
      const node = articleRefs.current.get(items[0].id);
      node?.focus();
      node?.scrollIntoView({ behavior: prefersReducedMotion() ? 'auto' : 'smooth', block: 'start' });
    }
    lastFirstIdRef.current = items[0]?.id;
  }, [items]);

  // An empty feed has no last article to observe, so it asks for its first page itself.
  const firedInitialLoadRef = useRef(false);
  useEffect(() => {
    if (items.length === 0 && hasMore && !loading && !firedInitialLoadRef.current) {
      firedInitialLoadRef.current = true;
      onLoadMoreRef.current?.();
    } else if (items.length > 0) {
      firedInitialLoadRef.current = false;
    }
  }, [items, hasMore, loading]);

  // Loads more as the last article nears view.
  useEffect(() => {
    if (!hasMore || loading || items.length === 0 || typeof IntersectionObserver === 'undefined') return undefined;
    const node = articleRefs.current.get(items[items.length - 1].id);
    if (!node) return undefined;
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) onLoadMoreRef.current?.();
      },
      { rootMargin: '100% 0px' },
    );
    observer.observe(node);
    return () => observer.disconnect();
  }, [items, hasMore, loading]);

  // Marks items read once they have been at least half visible for a moment.
  useEffect(() => {
    if (typeof IntersectionObserver === 'undefined') return undefined;
    const timers = new Map<string, number>();
    const idByNode = new Map<HTMLElement, string>();
    items.forEach((item) => {
      const node = articleRefs.current.get(item.id);
      if (node) idByNode.set(node, item.id);
    });
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const id = idByNode.get(entry.target as HTMLElement);
          if (!id) return;
          const existing = timers.get(id);
          if (existing !== undefined) {
            window.clearTimeout(existing);
            timers.delete(id);
          }
          if (entry.isIntersecting) {
            timers.set(
              id,
              window.setTimeout(() => {
                timers.delete(id);
                onItemVisibleRef.current?.(id);
              }, 1000),
            );
          }
        });
      },
      { threshold: 0.5 },
    );
    idByNode.forEach((_, node) => observer.observe(node));
    return () => {
      observer.disconnect();
      timers.forEach((timer) => window.clearTimeout(timer));
    };
  }, [items]);

  const handleShowNew = () => {
    pendingFocusNewRef.current = true;
    onShowNew?.();
  };

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'PageDown' || event.key === 'PageUp') {
      const articleEl = (event.target as HTMLElement).closest<HTMLElement>('[data-ds="Card"]');
      if (!articleEl) return;
      const ids = items.map((item) => item.id);
      const currentIndex = ids.findIndex((id) => articleRefs.current.get(id) === articleEl);
      if (currentIndex === -1) return;
      event.preventDefault();
      const targetId = ids[currentIndex + (event.key === 'PageDown' ? 1 : -1)];
      if (targetId) articleRefs.current.get(targetId)?.focus();
    } else if (event.key === 'End' && event.ctrlKey) {
      event.preventDefault();
      if (hasMore) {
        onLoadMoreRef.current?.();
      } else if (rootRef.current) {
        focusAfter(rootRef.current);
      }
    } else if (event.key === 'Home' && event.ctrlKey) {
      event.preventDefault();
      if (newItemsCount) {
        newItemsButtonRef.current?.focus();
      } else if (rootRef.current) {
        focusBefore(rootRef.current);
      }
    }
  };

  const classes = ['ds-feed', className ?? null].filter(Boolean).join(' ');
  const { rootStyle, articleOverrides, timestampOverrides, endMessageOverrides, newItemsButtonOverrides } = overrides
    ? overridesToStyle(overrides)
    : {
        rootStyle: undefined,
        articleOverrides: undefined,
        timestampOverrides: undefined,
        endMessageOverrides: undefined,
        newItemsButtonOverrides: undefined,
      };
  const mergedStyle = rootStyle || style ? { ...rootStyle, ...style } : undefined;

  const total = items.length;
  const setSize = hasMore ? -1 : total;

  return (
    <div
      {...rest}
      ref={rootRef}
      data-ds="Feed"
      data-part="container"
      className={classes}
      style={mergedStyle}
      role="feed"
      aria-label={label}
      aria-busy={loading ? 'true' : undefined}
      onKeyDown={handleKeyDown}
    >
      {newItemsCount ? (
        <div className="ds-feed__new-items" data-part="newItemsButton" role="status" aria-live="polite">
          <Button
            ref={newItemsButtonRef}
            variant="secondary"
            size="sm"
            label={COPY.showNew.replace('{count}', String(newItemsCount))}
            overrides={newItemsButtonOverrides}
            onClick={handleShowNew}
          />
        </div>
      ) : null}
      {total === 0 && !loading ? (
        <Text tone="muted" className="ds-feed__empty" data-part="emptyState">
          {COPY.empty}
        </Text>
      ) : (
        items.map((item, index) => {
          const itemBaseId = `${baseId}-${item.id}`;
          const timestampId = `${itemBaseId}-time`;

          return (
            <Card
              key={item.id}
              ref={(node) => {
                if (node) articleRefs.current.set(item.id, node);
                else articleRefs.current.delete(item.id);
              }}
              data-unread={item.unread || undefined}
              heading={item.heading}
              headingLevel={headingLevel}
              footer={item.actions !== undefined ? <div data-part="articleActions">{item.actions}</div> : undefined}
              overrides={articleOverrides}
              tabIndex={-1}
              aria-describedby={timestampId}
              aria-posinset={index + 1}
              aria-setsize={setSize}
            >
              <div className="ds-feed__article-body" data-part="articleBody">
                {item.unread ? <span className="ds-feed__visually-hidden">{COPY.unread}</span> : null}
                <time
                  className="ds-feed__timestamp"
                  id={timestampId}
                  dateTime={item.timestamp}
                  title={formatAbsoluteTime(item.timestamp)}
                >
                  <Text element="span" tone="muted" size="xs" overrides={timestampOverrides}>
                    {formatRelativeTime(item.timestamp)}
                  </Text>
                </time>
                {setSize !== -1 ? (
                  <span className="ds-feed__visually-hidden">
                    {COPY.position.replace('{index}', String(index + 1)).replace('{total}', String(total))}
                  </span>
                ) : null}
                {item.content}
              </div>
            </Card>
          );
        })
      )}
      {loading ? (
        <div className="ds-feed__loading" data-part="loadingIndicator">
          <ProgressBar label={COPY.loading} hideLabel />
        </div>
      ) : total > 0 && !hasMore ? (
        <div className="ds-feed__end-message" data-part="endMessage" role="status" aria-live="polite">
          <Text tone="muted" size="sm" overrides={endMessageOverrides}>
            {endMessage ?? COPY.end}
          </Text>
        </div>
      ) : null}
    </div>
  );
});

// packages/lit/src/Feed.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Card.js';
import './Button.js';
import './ProgressBar.js';
import './Text.js';

export type FeedHeadingLevel = '2' | '3' | '4';

/**
 * One article. `content` and `actions` are anything `lit-html` can render
 * (a string, a `TemplateResult`, a `Node`) — the platform's stand-in for
 * `ReactNode`. `timestamp` is ISO 8601 and rendered relative, with the
 * absolute time as the `<time>` element's `title`.
 */
export interface FeedItem {
  id: string;
  heading: string;
  timestamp: string;
  content: unknown;
  actions?: unknown;
  unread?: boolean;
}

/** Detail carried by the `item-visible` CustomEvent. */
export interface FeedItemVisibleDetail {
  id: string;
}

/** Overridable style hooks; see the `overrides` property. `unreadBorder`, `timestampColor`, `endMessageColor`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type FeedOverridableBinding =
  | 'itemGap'
  | 'articleInset'
  | 'unreadBorderWidth'
  | 'timestampSize'
  | 'newItemsOffset'
  | 'loadingInset'
  | 'endMessageSize'
  | 'fontFamily';

const HOOKS: Record<FeedOverridableBinding, string> = {
  itemGap: '--ds-feed-item-gap',
  articleInset: '--ds-feed-article-inset',
  unreadBorderWidth: '--ds-feed-unread-border-width',
  timestampSize: '--ds-feed-timestamp-size',
  newItemsOffset: '--ds-feed-new-items-offset',
  loadingInset: '--ds-feed-loading-inset',
  endMessageSize: '--ds-feed-end-message-size',
  fontFamily: '--ds-feed-font-family',
};

/** copy.showNew */
const COPY_SHOW_NEW = (count: number): string => `Show ${count} new`;
/** copy.loading */
const COPY_LOADING = 'Loading more';
/** copy.end */
const COPY_END = 'You are all caught up.';
/** copy.unread */
const COPY_UNREAD = 'unread';
/** copy.position */
const COPY_POSITION = (index: number, total: number): string => `${index} of ${total}`;
/** copy.empty */
const COPY_EMPTY = 'Nothing here yet.';

const RELATIVE_TIME = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });
const RELATIVE_DIVISIONS: { amount: number; unit: Intl.RelativeTimeFormatUnit }[] = [
  { amount: 60, unit: 'seconds' },
  { amount: 60, unit: 'minutes' },
  { amount: 24, unit: 'hours' },
  { amount: 7, unit: 'days' },
  { amount: 4.34524, unit: 'weeks' },
  { amount: 12, unit: 'months' },
  { amount: Number.POSITIVE_INFINITY, unit: 'years' },
];

function formatRelativeTime(iso: string): string {
  let duration = (new Date(iso).getTime() - Date.now()) / 1000;
  for (const division of RELATIVE_DIVISIONS) {
    if (Math.abs(duration) < division.amount) {
      return RELATIVE_TIME.format(Math.round(duration), division.unit);
    }
    duration /= division.amount;
  }
  return RELATIVE_TIME.format(Math.round(duration), 'years');
}

function formatAbsoluteTime(iso: string): string {
  return new Date(iso).toLocaleString();
}

/** Elements the Ctrl+Home/Ctrl+End feed commands can escape to. */
const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  'audio[controls]',
  'video[controls]',
  'summary',
  '[contenteditable]:not([contenteditable="false"])',
  '[tabindex]',
].join(',');

function isFocusable(el: Element): el is HTMLElement {
  if (!(el instanceof HTMLElement)) {
    return false;
  }
  if (el.hasAttribute('inert') || el.getAttribute('aria-hidden') === 'true') {
    return false;
  }
  const tabindex = el.getAttribute('tabindex');
  if (tabindex !== null && Number(tabindex) < 0) {
    return false;
  }
  return el.matches(FOCUSABLE_SELECTOR);
}

/** Walks light DOM, slot assignments and open shadow roots in tree order. */
function collectFocusable(node: Element, results: HTMLElement[]): void {
  if (node.hasAttribute('inert') || node.getAttribute('aria-hidden') === 'true') {
    return;
  }
  if (isFocusable(node)) {
    results.push(node);
  }
  if (node instanceof HTMLSlotElement) {
    for (const assigned of node.assignedElements({ flatten: true })) {
      collectFocusable(assigned, results);
    }
    return;
  }
  const scope = node.shadowRoot ?? node;
  for (const child of Array.from(scope.children)) {
    collectFocusable(child, results);
  }
}

function findFocusableInDocument(): HTMLElement[] {
  const results: HTMLElement[] = [];
  for (const child of Array.from(document.body.children)) {
    collectFocusable(child, results);
  }
  return results;
}

/**
 * `<ds-feed>` — Feed (category: container, APG pattern: feed).
 *
 * A `role="feed"` host (set as a plain attribute, along with `aria-label` and
 * `aria-busy`, so accessible-name tooling reads them) around a shadow root of
 * `<ds-card>` articles built from `items`, newest first. Each card carries
 * `tabindex="-1"`, `aria-posinset`/`aria-setsize` and `aria-describedby`
 * (pointing at its own `<time>`) as plain attributes; `role="article"` and
 * cross-root `aria-labelledby` come from `<ds-card>` itself once `heading` is
 * set, so Feed never duplicates that. `IntersectionObserver`s drive
 * `load-more` (root margin one viewport, only while `hasMore` and not already
 * `loading`) and `item-visible` (50% visible for one second). The
 * `newItemsCount` button never inserts items itself — pressing it fires
 * `show-new` and, once the caller's next `items` update lands, focus moves to
 * the new first article. PageDown/PageUp move focus between articles;
 * Ctrl+End requests more when `hasMore` (otherwise leaves the feed forward);
 * Ctrl+Home goes to the new-items button when shown, otherwise leaves the
 * feed backward.
 *
 * ## When to use
 *
 * Use a Feed for a stream of similar, time-ordered items whose total is
 * unknown or large: activity, notifications, comments, posts, audit events.
 * Use `newItemsCount` with `show-new` for live streams rather than inserting
 * items while the reader is looking; use `item-visible` to mark things read.
 *
 * ## When not to use
 *
 * Do not use a Feed for a finite list that fits on a page, for records with
 * comparable fields (Table), or for a chat thread. Do not use it for content
 * that must be complete on load; paginate instead.
 *
 * @fires load-more - Fired when the last rendered article is within one screen of view (or on Ctrl+End with `hasMore`).
 * @fires show-new - Fired when the new-items button is pressed; the caller prepends the items and clears `newItemsCount`.
 * @fires item-visible - Fired with `{ id }` once an item has been substantially visible for a moment.
 * @csspart container - The list wrapper (anatomy: container).
 * @csspart article - Each `<ds-card>` (anatomy: article).
 * @csspart articleBody - The timestamp/content wrapper inside an article (anatomy: articleBody).
 * @csspart articleActions - The actions row inside an article (anatomy: articleActions).
 * @csspart loadingIndicator - The `<ds-progress-bar>` shown while `loading` (anatomy: loadingIndicator).
 * @csspart endMessage - The end-of-feed message (anatomy: endMessage).
 * @csspart newItemsButton - The sticky new-items `<ds-button>` (anatomy: newItemsButton).
 * @csspart emptyState - The empty-state `<ds-text>` (anatomy: emptyState).
 */
@customElement('ds-feed')
export class DsFeed extends LitElement {
  static override styles = css`
    :host {
      display: block;
      font-family: var(--ds-feed-font-family);
      --ds-feed-item-gap: var(--layout-gap-normal);
      --ds-feed-article-inset: var(--layout-inset-md);
      --ds-feed-unread-border-width: var(--border-width-focus);
      --ds-feed-timestamp-size: var(--font-size-xs);
      --ds-feed-new-items-offset: var(--space-3);
      --ds-feed-loading-inset: var(--layout-inset-md);
      --ds-feed-end-message-size: var(--font-size-sm);
      --ds-feed-font-family: var(--font-family-body);
    }

    :host([hidden]) {
      display: none;
    }

    .container {
      display: flex;
      flex-direction: column;
      gap: var(--ds-feed-item-gap);
    }

    /* newItemsOffset: space.3, above the sticky button */
    .new-items-wrap {
      display: flex;
      justify-content: center;
      position: sticky;
      inset-block-start: 0;
      padding-block-start: var(--ds-feed-new-items-offset);
    }

    /* articleInset: layout.inset.md, forwarded to each Card's own padding hooks */
    .container ds-card {
      --ds-card-padding-block: var(--ds-feed-article-inset);
      --ds-card-padding-inline: var(--ds-feed-article-inset);
    }

    /* unreadBorder: color.control.selectedBackground, locked; unreadBorderWidth overridable */
    .container ds-card[data-unread] {
      border-inline-start: var(--ds-feed-unread-border-width) solid var(--color-control-selected-background);
    }

    /* focusRing/focusRingWidth: color.border.focus / border.width.focus, locked. The article host itself is the focus target (tabindex=-1). */
    .container ds-card:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    .article-body {
      display: flex;
      flex-direction: column;
      gap: var(--space-2);
    }

    /* timestampColor: color.foreground.muted, locked; timestampSize overridable */
    .timestamp {
      display: block;
      color: var(--color-foreground-muted);
      font-size: var(--ds-feed-timestamp-size);
    }

    .visually-hidden {
      /* literal-ok: standard visually-hidden clip pattern, exempt from token-only rule */
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }

    /* loadingInset: layout.inset.md */
    .loading {
      padding-block: var(--ds-feed-loading-inset);
      padding-inline: var(--ds-feed-loading-inset);
    }

    /* endMessageColor: color.foreground.muted, locked; endMessageSize overridable */
    .end-message {
      color: var(--color-foreground-muted);
      font-size: var(--ds-feed-end-message-size);
    }
  `;

  /** What the feed contains ("Activity", "Notifications"). The feed's accessible name. */
  @property() label = '';

  /** Articles, newest first. */
  @property({ attribute: false }) items: FeedItem[] = [];

  /** More items exist beyond the last; the feed asks for them with `load-more` as the end approaches. */
  @property({ type: Boolean, reflect: true, attribute: 'has-more' }) hasMore = false;

  /** More items are being fetched; a loading indicator is shown after the last article and the feed is `aria-busy`. */
  @property({ type: Boolean, reflect: true }) loading = false;

  /** Number of newer items available above. Shows a "Show {count} new" button that prepends and scrolls; the feed never inserts them itself. */
  @property({ type: Number, reflect: true, attribute: 'new-items-count' }) newItemsCount?: number;

  /** Heading level for article headings, matching the page outline. */
  @property({ reflect: true, attribute: 'heading-level' }) headingLevel: FeedHeadingLevel = '3';

  /** Shown after the last item when `hasMore` is false. Defaults to `copy.end`. */
  @property({ attribute: 'end-message' }) endMessage?: string;

  /** Per-instance style overrides: `{ itemGap: 'layout.gap.loose' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<FeedOverridableBinding, TokenRef>>;

  @query('.new-items-button') private readonly newItemsButtonEl?: HTMLElement;

  private loadMoreObserver?: IntersectionObserver;
  private visibilityObserver?: IntersectionObserver;
  private readonly visibilityTimers = new Map<string, number>();
  private pendingShowNewFocus = false;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Feed');
    this.setAttribute('role', 'feed');
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.teardownObservers();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render() {
    const showNewItems = Boolean(this.newItemsCount && this.newItemsCount > 0);
    const isEmpty = this.items.length === 0;

    return html`
      <div class="container" part="container" @keydown=${this.handleKeydown}>
        ${showNewItems
          ? html`
              <div class="new-items-wrap">
                <ds-button
                  class="new-items-button"
                  part="newItemsButton"
                  variant="secondary"
                  size="sm"
                  label=${COPY_SHOW_NEW(this.newItemsCount ?? 0)}
                  @press=${this.handleShowNewPress}
                ></ds-button>
              </div>
            `
          : nothing}
        ${isEmpty
          ? this.loading
            ? this.renderLoading()
            : html`<ds-text part="emptyState">${COPY_EMPTY}</ds-text>`
          : html`
              ${repeat(
                this.items,
                (item) => item.id,
                (item, index) => this.renderArticle(item, index),
              )}
              ${this.loading ? this.renderLoading() : !this.hasMore ? this.renderEndMessage() : nothing}
            `}
      </div>
    `;
  }

  protected override updated(changed: PropertyValues): void {
    this.syncHostAria();
    if (changed.has('items') || changed.has('hasMore') || changed.has('loading')) {
      this.syncObservers();
    }
    if (this.pendingShowNewFocus && changed.has('items')) {
      this.pendingShowNewFocus = false;
      this.getArticles()[0]?.focus();
    }
  }

  private renderArticle(item: FeedItem, index: number) {
    const timestampId = `ts-${item.id}`;
    const setsize = this.hasMore ? -1 : this.items.length;
    return html`
      <ds-card
        part="article"
        data-item-id=${item.id}
        ?data-unread=${item.unread}
        heading=${item.heading}
        heading-level=${this.headingLevel}
        tabindex="-1"
        aria-describedby=${timestampId}
        aria-posinset=${index + 1}
        aria-setsize=${setsize}
      >
        <div class="article-body" part="articleBody">
          ${item.unread ? html`<span class="visually-hidden">${COPY_UNREAD}</span>` : nothing}
          <time class="timestamp" id=${timestampId} datetime=${item.timestamp} title=${formatAbsoluteTime(item.timestamp)}
            >${formatRelativeTime(item.timestamp)}</time
          >
          ${setsize !== -1 ? html`<span class="visually-hidden">${COPY_POSITION(index + 1, setsize)}</span>` : nothing}
          ${item.content}
        </div>
        ${item.actions !== undefined
          ? html`<div slot="footer" part="articleActions">${item.actions}</div>`
          : nothing}
      </ds-card>
    `;
  }

  private renderLoading() {
    return html`
      <div class="loading" part="loadingIndicator">
        <ds-progress-bar label=${COPY_LOADING} hide-label></ds-progress-bar>
      </div>
    `;
  }

  private renderEndMessage() {
    return html`<div class="end-message" part="endMessage">${this.endMessage ?? COPY_END}</div>`;
  }

  private getArticles(): HTMLElement[] {
    return Array.from(this.renderRoot.querySelectorAll<HTMLElement>('ds-card'));
  }

  private readonly handleShowNewPress = (): void => {
    this.pendingShowNewFocus = true;
    this.dispatchEvent(new CustomEvent<void>('show-new', { bubbles: true, composed: true }));
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'PageDown') {
      event.preventDefault();
      this.focusAdjacentArticle(1, event.composedPath());
    } else if (event.key === 'PageUp') {
      event.preventDefault();
      this.focusAdjacentArticle(-1, event.composedPath());
    } else if (event.ctrlKey && event.key === 'End') {
      event.preventDefault();
      this.handleCtrlEnd();
    } else if (event.ctrlKey && event.key === 'Home') {
      event.preventDefault();
      this.handleCtrlHome();
    }
  };

  private focusAdjacentArticle(delta: 1 | -1, path: EventTarget[]): void {
    const articles = this.getArticles();
    const current = path.find((el): el is HTMLElement => el instanceof HTMLElement && el.tagName === 'DS-CARD');
    const index = current ? articles.indexOf(current) : -1;
    if (index === -1) {
      return;
    }
    articles[index + delta]?.focus();
  }

  private handleCtrlEnd(): void {
    if (this.hasMore) {
      this.dispatchEvent(new CustomEvent<void>('load-more', { bubbles: true, composed: true }));
      return;
    }
    this.focusOutside(1);
  }

  private handleCtrlHome(): void {
    if (this.newItemsCount) {
      this.newItemsButtonEl?.focus();
      return;
    }
    this.focusOutside(-1);
  }

  /** Escapes the feed to the nearest focusable element in document order, before (`-1`) or after (`1`) the host. */
  private focusOutside(direction: 1 | -1): void {
    const candidates = findFocusableInDocument().filter((el) => !this.contains(el));
    if (direction === 1) {
      const next = candidates.find((el) => (this.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0);
      next?.focus();
    } else {
      const preceding = candidates.filter(
        (el) => (this.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_PRECEDING) !== 0,
      );
      preceding[preceding.length - 1]?.focus();
    }
  }

  private syncHostAria(): void {
    if (this.label) {
      this.setAttribute('aria-label', this.label);
    } else {
      this.removeAttribute('aria-label');
    }
    if (this.loading) {
      this.setAttribute('aria-busy', 'true');
    } else {
      this.removeAttribute('aria-busy');
    }
  }

  /** (Re)builds the load-more and visibility observers against the current articles. */
  private syncObservers(): void {
    this.teardownObservers();
    const articles = this.getArticles();
    if (articles.length === 0) {
      return;
    }

    if (this.hasMore && !this.loading) {
      this.loadMoreObserver = new IntersectionObserver(this.handleLoadMoreIntersect, { rootMargin: '100% 0px' });
      this.loadMoreObserver.observe(articles[articles.length - 1]);
    }

    this.visibilityObserver = new IntersectionObserver(this.handleVisibilityIntersect, { threshold: 0.5 });
    for (const article of articles) {
      this.visibilityObserver.observe(article);
    }
  }

  private teardownObservers(): void {
    this.loadMoreObserver?.disconnect();
    this.loadMoreObserver = undefined;
    this.visibilityObserver?.disconnect();
    this.visibilityObserver = undefined;
    for (const timer of this.visibilityTimers.values()) {
      clearTimeout(timer);
    }
    this.visibilityTimers.clear();
  }

  private readonly handleLoadMoreIntersect = (entries: IntersectionObserverEntry[]): void => {
    if (entries.some((entry) => entry.isIntersecting)) {
      this.dispatchEvent(new CustomEvent<void>('load-more', { bubbles: true, composed: true }));
    }
  };

  private readonly handleVisibilityIntersect = (entries: IntersectionObserverEntry[]): void => {
    for (const entry of entries) {
      const id = (entry.target as HTMLElement).dataset.itemId;
      if (!id) {
        continue;
      }
      const existing = this.visibilityTimers.get(id);
      if (existing !== undefined) {
        clearTimeout(existing);
        this.visibilityTimers.delete(id);
      }
      if (entry.isIntersecting) {
        const timer = window.setTimeout(() => {
          this.visibilityTimers.delete(id);
          this.dispatchEvent(
            new CustomEvent<FeedItemVisibleDetail>('item-visible', {
              detail: { id },
              bubbles: true,
              composed: true,
            }),
          );
        }, 1000);
        this.visibilityTimers.set(id, timer);
      }
    }
  };

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as FeedOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-feed': DsFeed;
  }
}
