// packages/react/src/Form.tsx
import {
  useCallback,
  useEffect,
  useId,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type FormEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import {
  FormContext,
  type FormContextValue,
  type FormFieldRegistration,
  type FormValidateMode,
} from './FormContext';
import { Link } from './Link';
import { Stack } from './Stack';
import { Text } from './Text';
import './Form.css';

export type { FormValidateMode, FormFieldValue } from './FormContext';

/**
 * Collected values keyed by field `name`: Input and RadioGroup contribute strings, Switch a boolean,
 * Checkbox its `value` when checked, NumberInput and Slider a number, multi-select Listbox, Select and
 * Combobox a string array, a range Slider or DatePicker a pair. Empty, unchecked, unselected and
 * disabled fields contribute no key.
 */
export type FormValues = Record<string, string | number | boolean | string[] | [number, number]>;
/** Error messages keyed by field `name`. */
export type FormErrors = Record<string, string>;

/**
 * copy.* — used verbatim. `summaryHeading` is selected by `Intl.PluralRules` on `count`;
 * `summaryHeadingOne` and `invalidSummary` are not rendered on web.
 */
const COPY = {
  summaryHeading: {
    one: '1 problem with this form',
    other: '{count} problems with this form',
  },
  summaryHeadingOne: '1 problem with this form',
  invalidSummary: 'This form has errors.',
} as const;

function summaryHeading(count: number, locale: string | undefined): string {
  let rules: Intl.PluralRules;
  try {
    rules = new Intl.PluralRules(locale);
  } catch {
    rules = new Intl.PluralRules();
  }
  const form = rules.select(count) === 'one' ? COPY.summaryHeading.one : COPY.summaryHeading.other;
  return form.replace('{count}', String(count));
}

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type FormOverridableBinding =
  | 'gap'
  | 'errorSummaryBorder'
  | 'errorSummaryBorderWidth'
  | 'errorSummaryRadius'
  | 'errorSummaryPadding'
  | 'errorSummaryGap';

/** CSS hooks written inline. `errorSummaryGap` is absent: it is forwarded to the summary's Stack `gap`. */
const OVERRIDE_HOOK: Record<Exclude<FormOverridableBinding, 'errorSummaryGap'>, string> = {
  gap: '--ds-form-gap',
  errorSummaryBorder: '--ds-form-error-summary-border',
  errorSummaryBorderWidth: '--ds-form-error-summary-border-width',
  errorSummaryRadius: '--ds-form-error-summary-radius',
  errorSummaryPadding: '--ds-form-error-summary-padding',
};

function overridesToStyle(
  overrides: Partial<Record<FormOverridableBinding, TokenRef | undefined>>,
): CSSProperties | undefined {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(OVERRIDE_HOOK) as (keyof typeof OVERRIDE_HOOK)[]) {
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return Object.keys(style).length > 0 ? (style as CSSProperties) : undefined;
}

export interface FormProps
  extends Omit<
    ComponentPropsWithoutRef<'form'>,
    | 'children'
    | 'name'
    | 'onSubmit'
    | 'onInvalid'
    | 'noValidate'
    | 'action'
    | 'aria-label'
    | 'aria-labelledby'
    | 'aria-disabled'
    | 'style'
    | 'className'
  > {
  /** Fields (Input etc.) and layout (Stack). The action row goes in `actions`. */
  children: ReactNode;
  /** The action row: at least one Button with `type: submit`, primary first (Form's action-order rule). Rendered after the fields with the form gap. */
  actions: ReactNode;
  /** Identifier for the form, used for analytics and as the base of generated ids. */
  name?: string | undefined;
  /** Accessible name for the form landmark, e.g. "Sign in". Required when a page has more than one form and `labelledBy` is not set. Nothing enforces this at runtime and no dev warning is emitted. */
  label?: string | undefined;
  /** Id of a visible Heading that names the form. Wins over `label` when both are set. */
  labelledBy?: string | undefined;
  /** When field-level validation runs. `submit` is the least noisy; `blur` is the usual choice for longer forms. */
  validate?: FormValidateMode | undefined;
  /** Disables every field and action inside. Use while submitting. Each field and action dims itself; the Form applies no opacity of its own and only exposes the disabled state. */
  disabled?: boolean | undefined;
  /** When submission fails validation, render a summary of errors above the fields that links to each field. Each item's text is the field's own message verbatim; a field invalid with an empty message shows its `label` instead. */
  errorSummary?: boolean | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<FormOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the form is submitted and every field is valid. Receives the collected values keyed by field name. */
  onSubmit?: ((values: FormValues) => void) | undefined;
  /** Fired when submission is blocked by validation. Receives the errors keyed by field name. */
  onInvalid?: ((errors: FormErrors) => void) | undefined;
}

/** A null, empty-string or empty-array value contributes no key to `onSubmit`. */
function isEmptyValue(value: unknown): boolean {
  return value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0);
}

function shallowEqual(a: Readonly<FormErrors>, b: Readonly<FormErrors>): boolean {
  const aKeys = Object.keys(a);
  const bKeys = Object.keys(b);
  if (aKeys.length !== bKeys.length) return false;
  return aKeys.every((key) => a[key] === b[key]);
}

/**
 * Form — Design Schema, category: container.
 *
 * When to use:
 * Use Form whenever two or more fields are submitted together, and for any single field whose
 * submission has consequences (sign-in, search with side effects). Place actions (submit, cancel)
 * at the end in a Stack. Give the form a `label` when the page contains more than one.
 */
export function Form({
  ref,
  children,
  actions,
  name,
  label,
  labelledBy,
  validate = 'submit',
  disabled = false,
  errorSummary = true,
  overrides,
  onSubmit,
  onInvalid,
  ...rest
}: FormProps & { ref?: Ref<HTMLFormElement> | undefined }): ReactElement {
  const formRef = useRef<HTMLFormElement | null>(null);
  useImperativeHandle(ref, () => formRef.current as HTMLFormElement, []);

  const generatedId = useId();
  // An unnamed form bases its ids on a generated unique id.
  const idBase = name ?? `ds-form${generatedId}`;
  const summaryId = `${idBase}-error-summary`;

  const fieldsRef = useRef(new Map<string, FormFieldRegistration>());
  // Last registration seen per name, so a summary entry keeps its label after its field unregisters.
  const knownFieldsRef = useRef(new Map<string, FormFieldRegistration>());
  const [errors, setErrors] = useState<FormErrors>({});
  // Counts failed submissions (the summary refocuses on each); a successful submission resets it.
  // After a failed submission every mode re-validates on blur and change (`submitFailed`).
  const [failedSubmissions, setFailedSubmissions] = useState(0);
  const submitFailed = failedSubmissions > 0;
  // Plural locale for the summary heading: the nearest `lang` ancestor, read when submission fails.
  const [locale, setLocale] = useState<string | undefined>(undefined);
  const summaryRef = useRef<HTMLDivElement | null>(null);

  const register = useCallback((field: FormFieldRegistration) => {
    fieldsRef.current.set(field.name, field);
    knownFieldsRef.current.set(field.name, field);
    return () => {
      if (fieldsRef.current.get(field.name) === field) fieldsRef.current.delete(field.name);
    };
  }, []);

  /**
   * Registered fields in document order, sorted by the position of each field's `data-ds-field`
   * element. Fields whose element is not found keep their registration order at the end.
   */
  const orderedFields = (): FormFieldRegistration[] => {
    const fields = [...fieldsRef.current.values()];
    const root = formRef.current;
    if (!root) return fields;
    const hosts = [...root.querySelectorAll('[data-ds-field]')];
    const position = new Map<FormFieldRegistration, number>();
    for (const field of fields) {
      const host = root.ownerDocument.getElementById(field.id)?.closest('[data-ds-field]');
      const index = host ? hosts.indexOf(host) : -1;
      position.set(field, index === -1 ? Number.POSITIVE_INFINITY : index);
    }
    return fields.sort((a, b) => {
      const pa = position.get(a)!;
      const pb = position.get(b)!;
      return pa === pb ? 0 : pa < pb ? -1 : 1;
    });
  };

  const validateField = useCallback(
    (fieldName: string) => {
      // Under `validate: submit`, nothing validates before the first failed submission.
      if (validate === 'submit' && !submitFailed) return;
      const field = fieldsRef.current.get(fieldName);
      if (!field) return;
      const message = field.isDisabled() ? null : field.validate();
      setErrors((prev) => {
        const hasPrev = Object.prototype.hasOwnProperty.call(prev, fieldName);
        if (message === null) {
          if (!hasPrev) return prev;
          const next = { ...prev };
          delete next[fieldName];
          return next;
        }
        if (hasPrev && prev[fieldName] === message) return prev;
        return { ...prev, [fieldName]: message };
      });
    },
    [validate, submitFailed],
  );

  const handleSubmit = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    if (disabled) return;

    const nextErrors: FormErrors = {};
    const values: FormValues = {};
    let firstInvalid: FormFieldRegistration | null = null;

    for (const field of orderedFields()) {
      if (field.isDisabled()) continue;
      const message = field.validate();
      if (message !== null) {
        nextErrors[field.name] = message;
        firstInvalid ??= field;
      } else {
        const fieldValue = field.getValue();
        if (fieldValue !== undefined && !isEmptyValue(fieldValue)) values[field.name] = fieldValue;
      }
    }

    setErrors((prev) => (shallowEqual(prev, nextErrors) ? prev : nextErrors));

    if (firstInvalid !== null) {
      const lang = formRef.current?.closest('[lang]')?.getAttribute('lang');
      setLocale(lang ? lang : undefined);
      setFailedSubmissions((count) => count + 1);
      onInvalid?.(nextErrors);
      if (!errorSummary) firstInvalid.focus();
      return;
    }
    setFailedSubmissions(0);
    onSubmit?.(values);
  };

  // Focus the summary once it has rendered after a failed submission.
  useEffect(() => {
    if (failedSubmissions > 0 && errorSummary) summaryRef.current?.focus();
  }, [failedSubmissions, errorSummary]);

  const contextValue = useMemo<FormContextValue>(
    () => ({
      disabled,
      validateMode: validate,
      submitFailed,
      validate,
      idBase,
      errors,
      register,
      validateField,
    }),
    [disabled, validate, submitFailed, idBase, errors, register, validateField],
  );

  const errorEntries = Object.entries(errors);
  const showSummary = errorSummary && failedSubmissions > 0 && errorEntries.length > 0;
  const summaryGap: Partial<Record<'gap', TokenRef | undefined>> | undefined = overrides?.errorSummaryGap
    ? { gap: overrides.errorSummaryGap }
    : undefined;

  return (
    <FormContext.Provider value={contextValue}>
      <form
        {...rest}
        ref={formRef}
        name={name}
        data-ds="Form"
        data-part="container"
        className="ds-form"
        style={overrides ? overridesToStyle(overrides) : undefined}
        noValidate
        aria-label={labelledBy ? undefined : label}
        aria-labelledby={labelledBy}
        onSubmit={handleSubmit}
      >
        {showSummary ? (
          <div
            ref={summaryRef}
            id={summaryId}
            data-part="errorSummary"
            className="ds-form__error-summary"
            role="alert"
            tabIndex={-1}
          >
            <Stack gap="tight" overrides={summaryGap}>
              <Text element="p" weight="semibold" tone="danger">
                {summaryHeading(errorEntries.length, locale)}
              </Text>
              <Stack element="ul" gap="tight" overrides={summaryGap}>
                {/* Stack element="ul" wraps each child in its own `li`. */}
                {errorEntries.map(([fieldName, message]) => {
                  // A field that has unregistered since the failed submit stays as plain danger Text.
                  const field = fieldsRef.current.get(fieldName);
                  const known = field ?? knownFieldsRef.current.get(fieldName);
                  // An empty message falls back to the label, then to the name when the label is empty too.
                  const text = message !== '' ? message : known?.label ? known.label : fieldName;
                  return field ? (
                    <Link
                      key={fieldName}
                      href={`#${field.id}`}
                      label={text}
                      tone="inherit"
                      onClick={() => {
                        field.focus();
                        return false;
                      }}
                    />
                  ) : (
                    <Text key={fieldName} element="span" tone="danger">
                      {text}
                    </Text>
                  );
                })}
              </Stack>
            </Stack>
          </div>
        ) : null}
        <div className="ds-form__fields" data-part="fields">
          {children}
        </div>
        <div className="ds-form__actions" data-part="actions">
          {actions}
        </div>
      </form>
    </FormContext.Provider>
  );
}

// packages/lit/src/Form.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Text.js';
import './Link.js';
import './Stack.js';

export type FormValidate = 'submit' | 'blur' | 'change';

/** Detail carried by the `submit` CustomEvent. */
export interface FormSubmitDetail {
  values: Record<string, string | number | boolean | string[] | [number, number]>;
}

/** Detail carried by the `invalid` CustomEvent. */
export interface FormInvalidDetail {
  errors: Record<string, string>;
}

/**
 * The contract a light-DOM element must implement to be collected by
 * `<ds-form>`. Form finds fields by the `data-ds-field` attribute on their host,
 * never by tag, so any element that sets it and implements this interface is
 * collected. `error` and `validationMessage` are optional: a field that never
 * validates (Switch) omits them, and Form treats absence as valid.
 * `currentValue` is `null` when the field contributes no key (empty, unchecked,
 * unselected).
 */
export interface DsFormField extends HTMLElement {
  name: string;
  label: string;
  required: boolean;
  disabled: boolean;
  error?: string | undefined;
  readonly currentValue: string | number | boolean | string[] | [number, number] | null;
  id: string;
  focus(): void;
  checkValidity(): boolean;
  readonly validationMessage?: string | undefined;
}

/** Overridable style hooks; see the `overrides` property. `errorSummaryText` and `errorSummaryBackground` are locked and excluded. */
export type FormOverridableBinding =
  | 'gap'
  | 'errorSummaryBorder'
  | 'errorSummaryBorderWidth'
  | 'errorSummaryRadius'
  | 'errorSummaryPadding'
  | 'errorSummaryGap';

/** `errorSummaryGap` has no hook: it is forwarded to the summary Stacks' `overrides.gap`. */
const HOOKS: Record<Exclude<FormOverridableBinding, 'errorSummaryGap'>, string> = {
  gap: '--ds-form-gap',
  errorSummaryBorder: '--ds-form-error-summary-border',
  errorSummaryBorderWidth: '--ds-form-error-summary-border-width',
  errorSummaryRadius: '--ds-form-error-summary-radius',
  errorSummaryPadding: '--ds-form-error-summary-padding',
};

type FieldValue = FormSubmitDetail['values'][string];

/** A null, empty-string or empty-array value contributes no key. */
function isEmptyValue(value: FieldValue | null | undefined): boolean {
  return value === null || value === undefined || value === '' || (Array.isArray(value) && value.length === 0);
}

/** copy.summaryHeading, plural by `count`. */
const COPY_SUMMARY_HEADING: Record<'one' | 'other', string> = {
  one: '1 problem with this form',
  other: '{count} problems with this form',
};

/** Every field component sets this attribute on its host; Form discovers fields by it alone. */
const FIELD_SELECTOR = '[data-ds-field]';

/** Negates a boolean attribute: `no-error-summary` present means `errorSummary` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

let formInstanceCount = 0;

type Disableable = HTMLElement & { disabled: boolean };

/**
 * `<ds-form>` — Form (category: container).
 *
 * `<ds-form name="sign-in" label="Sign in">` wraps a native `<form novalidate>`
 * in its shadow root, with a default slot for fields (Input etc. and layout
 * like Stack) and a named `actions` slot for the action row, but form
 * ownership is DOM-tree based, so the slotted fields are not owned by it.
 * Instead it collects light-DOM descendants carrying `data-ds-field` that have
 * a `name` and implement `DsFormField` (skipping any inside a closed
 * `ds-disclosure` without `keep-mounted`), submits on a composed `press` from
 * a `ds-button[type=submit]` and on Enter in any field (a `keydown` listener on
 * the host, never a CustomEvent named after a native event), and propagates
 * `disabled` to the fields it found and to every `ds-button` slotted into
 * `actions`, remembering which ones it disabled so it never re-enables one
 * already disabled on its own. The host carries `role="form"` and
 * `aria-label` / `aria-labelledby` (`labelledBy` winning over `label`) as plain
 * attributes, so the landmark lives in the light DOM tree. Dispatches composed
 * `submit` (`{ values }`) and `invalid` (`{ errors }`) CustomEvents; never
 * navigates. Never nest inside a native form or another `<ds-form>`.
 *
 * ## When to use
 *
 * Use Form whenever two or more fields are submitted together, and for any
 * single field whose submission has consequences (sign-in, search with side
 * effects). Place actions (submit, cancel) at the end in a Stack. Give the
 * form a `label` when the page contains more than one.
 *
 * @fires submit - Fired when every field is valid, with `{ values }` (keyed by each field's `name`) in `detail`.
 * @fires invalid - Fired when submission is blocked by validation, with `{ errors }` in `detail`.
 * @slot - Fields (Input etc.) and layout (Stack) (anatomy: fields).
 * @slot actions - The action row: at least one Button with `type: submit`, primary first (anatomy: actions).
 */
@customElement('ds-form')
export class DsForm extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-form-gap: var(--layout-gap-loose);
      --ds-form-error-summary-border: var(--color-border-danger);
      --ds-form-error-summary-border-width: var(--border-width-thin);
      --ds-form-error-summary-radius: var(--radius-md);
      --ds-form-error-summary-padding: var(--space-md);
    }

    :host([hidden]) {
      display: none;
    }

    [data-part='container'] {
      display: flex;
      flex-direction: column;
      gap: var(--ds-form-gap);
      margin: 0;
      padding: 0;
    }

    /* A bare single action keeps its own width instead of stretching across the column. */
    slot[name='actions'] {
      display: flex;
      align-items: flex-start;
    }

    /* errorSummaryBackground / errorSummaryText: color.background.subtle / color.foreground.danger, locked */
    [data-part='errorSummary'] {
      box-sizing: border-box;
      padding: var(--ds-form-error-summary-padding);
      border: var(--ds-form-error-summary-border-width) solid var(--ds-form-error-summary-border);
      border-radius: var(--ds-form-error-summary-radius);
      background: var(--color-background-subtle);
      color: var(--color-foreground-danger);
    }

    [data-part='errorSummary']:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }
  `;

  /** Identifier for the form, used for analytics and as the base of generated field ids. */
  @property() accessor name = '';

  /** Accessible name for the form landmark. Required when a page has more than one form and `labelledBy` is not set. */
  @property() accessor label: string | undefined;

  /** Id of a visible Heading that names the form. Wins over `label` when both are set. */
  @property() accessor labelledBy: string | undefined;

  /** When field-level validation runs. `submit` is the least noisy; `blur` is the usual choice for longer forms. */
  @property() accessor validate: FormValidate = 'submit';

  /** Disables every field and action inside. Use while submitting. The container applies no opacity of its own. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /**
   * When submission fails validation, render a summary of errors above the fields that links to each field.
   * Attribute is the negation, `no-error-summary`, because a boolean attribute cannot express `false` for a
   * prop that defaults `true`.
   */
  @property({ attribute: 'no-error-summary', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER })
  accessor errorSummary = true;

  /** Per-instance style overrides: `{ gap: 'layout.gap.normal' }`. Locked bindings (errorSummaryText, errorSummaryBackground) are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<FormOverridableBinding, TokenRef | undefined>> | undefined;

  /**
   * Field name -> message for the error summary: document order at the failed submit, with errors that
   * blur or change validation finds later appended at the end. Empty until a submission fails.
   */
  @state() private accessor errors: ReadonlyMap<string, string> = new Map();

  /** Each errored field's `label` as registered, so an entry whose field has since gone keeps its fallback text. */
  private readonly errorLabels = new Map<string, string>();

  /** Once a submission has failed, fields re-validate on blur/change even in `submit` mode; a successful one clears it. */
  private hasFailedSubmission = false;

  /** The plural locale, read at the failed submit (nearest `lang` ancestor, else the runtime default). */
  private summaryLocale: string | undefined;

  /** Fields and actions this Form disabled itself, so re-enabling never touches one already disabled by the consumer. */
  private readonly disabledByForm = new Set<Disableable>();

  /** Re-syncs disabled propagation when fields are added or removed; observes `childList` only, never the attributes it writes. */
  private readonly mutationObserver = new MutationObserver(() => {
    if (this.disabled) this.syncDisabled();
  });

  /** Focus the error summary once it exists, after the render that follows a failed submission. */
  private pendingSummaryFocus = false;

  private readonly instanceId = `ds-form-${++formInstanceCount}`;

  constructor() {
    super();
    this.addEventListener('keydown', (event) => this.handleKeydown(event));
    this.addEventListener('press', (event) => this.handlePress(event));
    this.addEventListener('change', (event) => this.handleFieldChange(event));
    this.addEventListener('focusout', (event) => this.handleFieldFocusOut(event));
  }

  private get idBase(): string {
    return this.name || this.instanceId;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Form');
    if (this.getAttribute('role') !== 'form') this.setAttribute('role', 'form');
    this.mutationObserver.observe(this, { childList: true, subtree: true });
    if (import.meta.env.DEV && this.parentElement?.closest('form, ds-form')) {
      console.warn('<ds-form> must not be nested inside a native <form> or another <ds-form>.');
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.mutationObserver.disconnect();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('label') || changed.has('labelledBy')) {
      this.syncName();
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('disabled')) {
      this.syncDisabled();
    }
    if (this.pendingSummaryFocus) {
      this.pendingSummaryFocus = false;
      this.renderRoot.querySelector<HTMLElement>('[data-part="errorSummary"]')?.focus();
    }
  }

  protected override render(): TemplateResult {
    const errorEntries = Array.from(this.errors);
    const showSummary = this.errorSummary && this.hasFailedSubmission && errorEntries.length > 0;

    return html`
      <form
        part="container"
        data-part="container"
        novalidate
        name=${ifDefined(this.name || undefined)}
        @submit=${this.handleNativeSubmit}
      >
        ${showSummary ? this.renderSummary(errorEntries) : nothing}
        <slot data-part="fields"></slot>
        <slot name="actions" data-part="actions"></slot>
      </form>
    `;
  }

  private renderSummary(errorEntries: [string, string][]): TemplateResult {
    const fieldsByName = new Map(this.queryFields().map((field) => [field.name, field] as const));
    // errorSummaryGap is forwarded to both Stacks; their `gap="tight"` is the binding's default token.
    const gapRef = this.overrides?.errorSummaryGap;
    const stackOverrides = gapRef === undefined ? undefined : { gap: gapRef };
    return html`
      <div part="errorSummary" data-part="errorSummary" role="alert" tabindex="-1">
        <ds-stack gap="tight" .overrides=${stackOverrides}>
          <ds-text element="p" weight="semibold" tone="danger">${this.summaryHeading(errorEntries.length)}</ds-text>
          <ds-stack element="ul" gap="tight" .overrides=${stackOverrides}>
            ${errorEntries.map(([name, message]) => {
              const field = fieldsByName.get(name);
              // The field's own message verbatim; its label only when the message is empty.
              const text = message || (field?.label ?? this.errorLabels.get(name)) || name;
              // A field that has since unregistered keeps its entry as plain danger Text, with no Link.
              if (field === undefined) {
                return html`<ds-text tone="danger">${text}</ds-text>`;
              }
              return html`
                <ds-link
                  tone="inherit"
                  href=${`#${field.id}`}
                  label=${text}
                  @click=${(event: MouseEvent) => this.handleSummaryLinkClick(event, name)}
                ></ds-link>
              `;
            })}
          </ds-stack>
        </ds-stack>
      </div>
    `;
  }

  private summaryHeading(count: number): string {
    const form = new Intl.PluralRules(this.summaryLocale).select(count) === 'one' ? 'one' : 'other';
    return COPY_SUMMARY_HEADING[form].replace('{count}', String(count));
  }

  /** Validate every field and, only if all pass, dispatch `submit` with the collected values. */
  submit(): void {
    if (this.disabled) {
      return;
    }
    const fields = this.queryFields();
    this.assignFieldIds(fields);

    const errors = new Map<string, string>();
    this.errorLabels.clear();
    const values: FormSubmitDetail['values'] = {};
    let firstInvalid: DsFormField | undefined;

    for (const field of fields) {
      if (field.disabled) {
        continue;
      }
      if (field.checkValidity()) {
        const value = field.currentValue;
        if (!isEmptyValue(value)) {
          values[field.name] = value as FieldValue;
        }
      } else {
        errors.set(field.name, field.validationMessage ?? '');
        this.errorLabels.set(field.name, field.label);
        firstInvalid ??= field;
      }
    }

    this.errors = errors;

    if (firstInvalid !== undefined) {
      this.hasFailedSubmission = true;
      this.summaryLocale = this.closest('[lang]')?.getAttribute('lang') || undefined;
      this.dispatchEvent(
        new CustomEvent<FormInvalidDetail>('invalid', {
          detail: { errors: Object.fromEntries(errors) },
          bubbles: true,
          composed: true,
        }),
      );
      if (this.errorSummary) {
        this.pendingSummaryFocus = true;
      } else {
        firstInvalid.focus();
      }
      return;
    }

    // A successful submission removes the summary.
    this.hasFailedSubmission = false;
    this.dispatchEvent(
      new CustomEvent<FormSubmitDetail>('submit', { detail: { values }, bubbles: true, composed: true }),
    );
  }

  private handleNativeSubmit(event: Event): void {
    // The shadow <form> owns no controls; never let it navigate.
    event.preventDefault();
  }

  private handleKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' || event.defaultPrevented || event.isComposing) {
      return;
    }
    if (this.fieldFor(event.target) === null) {
      return;
    }
    // Enter in a multi-line control inserts a line break; on a button or link it activates it.
    const origin = event.composedPath()[0];
    if (
      origin instanceof HTMLTextAreaElement ||
      origin instanceof HTMLButtonElement ||
      origin instanceof HTMLAnchorElement
    ) {
      return;
    }
    event.preventDefault();
    this.submit();
  }

  private handlePress(event: Event): void {
    const target = event.target;
    if (!(target instanceof HTMLElement) || target.tagName !== 'DS-BUTTON') {
      return;
    }
    if ((target as HTMLElement & { type?: string | undefined }).type !== 'submit') {
      return;
    }
    this.submit();
  }

  private handleFieldChange(event: Event): void {
    const field = this.fieldFor(event.target);
    if (field === null) {
      return;
    }
    const shouldValidate =
      this.validate === 'change' ||
      (this.validate === 'blur' && this.validatesOnChange(field)) ||
      this.hasFailedSubmission;
    if (shouldValidate) {
      this.validateField(field);
    }
  }

  private handleFieldFocusOut(event: FocusEvent): void {
    const field = this.fieldFor(event.target);
    if (field === null) {
      return;
    }
    const related = event.relatedTarget;
    if (related instanceof Node && (related === field || field.contains(related))) {
      // Focus moved within the same field (two radios in one group), not out of it.
      return;
    }
    const shouldValidate =
      (this.validate === 'blur' && !this.validatesOnChange(field)) || this.hasFailedSubmission;
    if (shouldValidate) {
      this.validateField(field);
    }
  }

  /** A field with no useful blur moment (Checkbox, Switch) declares `data-ds-field="change"`. */
  private validatesOnChange(field: DsFormField): boolean {
    return field.getAttribute('data-ds-field') === 'change';
  }

  private handleSummaryLinkClick(event: MouseEvent, name: string): void {
    // Moves focus to the field; never navigates or changes the URL hash.
    event.preventDefault();
    this.queryFields()
      .find((candidate) => candidate.name === name)
      ?.focus();
  }

  /**
   * Runs the field's own validation (the field shows its error). The summary only tracks it after a failed
   * submission: a fixed field drops out, a still-listed one keeps its place, a newly invalid one is appended.
   */
  private validateField(field: DsFormField): void {
    const invalid = !field.disabled && !field.checkValidity();
    if (!this.hasFailedSubmission) {
      return;
    }
    const next = new Map(this.errors);
    if (invalid) {
      next.set(field.name, field.validationMessage ?? '');
      this.errorLabels.set(field.name, field.label);
    } else {
      next.delete(field.name);
    }
    this.errors = next;
  }

  /** The collected field an event came from, or `null`. */
  private fieldFor(target: EventTarget | null): DsFormField | null {
    if (!(target instanceof Element)) {
      return null;
    }
    const el = target.closest<HTMLElement>(FIELD_SELECTOR);
    if (el === null || !this.contains(el)) {
      return null;
    }
    const field = el as DsFormField;
    return field.name && !this.isInsideClosedDisclosure(el) ? field : null;
  }

  /** Fields with a `name`, in document order, not inside a closed `ds-disclosure` without `keep-mounted`. */
  private queryFields(): DsFormField[] {
    return Array.from(this.querySelectorAll<HTMLElement>(FIELD_SELECTOR)).filter(
      (el): el is DsFormField => Boolean((el as DsFormField).name) && !this.isInsideClosedDisclosure(el),
    );
  }

  private isInsideClosedDisclosure(el: HTMLElement): boolean {
    let node = el.parentElement;
    while (node !== null && node !== this) {
      if (node.tagName === 'DS-DISCLOSURE') {
        const disclosure = node as HTMLElement & { currentOpen?: boolean | undefined; keepMounted?: boolean | undefined };
        if (!disclosure.keepMounted && !disclosure.currentOpen) {
          return true;
        }
      }
      node = node.parentElement;
    }
    return false;
  }

  /** A field missing an `id` gets `{name}-{field.name}`, so an error summary link always has somewhere to point. */
  private assignFieldIds(fields: readonly DsFormField[]): void {
    for (const field of fields) {
      if (!field.id) {
        field.id = `${this.idBase}-${field.name}`;
      }
    }
  }

  /** Every `ds-button` slotted into `actions`, including the slotted element itself. */
  private queryActionButtons(): Disableable[] {
    const buttons: Disableable[] = [];
    for (const child of Array.from(this.children)) {
      if (child.getAttribute('slot') !== 'actions') continue;
      if (child.tagName === 'DS-BUTTON') buttons.push(child as Disableable);
      buttons.push(...Array.from(child.querySelectorAll<Disableable>('ds-button')));
    }
    return buttons;
  }

  /** Disables every found field and action button, remembering which it disabled so re-enabling is exact. */
  private syncDisabled(): void {
    if (this.disabled) {
      for (const control of [...this.queryFields(), ...this.queryActionButtons()] as Disableable[]) {
        if (!control.disabled) {
          this.disabledByForm.add(control);
          control.disabled = true;
        }
      }
      return;
    }
    for (const control of this.disabledByForm) {
      if (control.disabled) control.disabled = false;
    }
    this.disabledByForm.clear();
  }

  /** Accessible name as plain host attributes, `labelledBy` winning over `label`. */
  private syncName(): void {
    if (this.labelledBy) {
      this.setAttribute('aria-labelledby', this.labelledBy);
      this.removeAttribute('aria-label');
    } else {
      this.removeAttribute('aria-labelledby');
      if (this.label) {
        this.setAttribute('aria-label', this.label);
      } else {
        this.removeAttribute('aria-label');
      }
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as (keyof typeof HOOKS)[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-form': DsForm;
  }
}
