// packages/react/src/Landmark.tsx
import {
  createElement,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import './Landmark.css';

/** Which landmark this is. */
export type LandmarkRole =
  | 'banner'
  | 'navigation'
  | 'main'
  | 'complementary'
  | 'contentinfo'
  | 'region'
  | 'search'
  | 'form';

/** Web element override. */
export type LandmarkElement = 'header' | 'nav' | 'main' | 'aside' | 'footer' | 'section' | 'form' | 'div';

export interface LandmarkProps
  extends Omit<HTMLAttributes<HTMLElement>, 'role' | 'children' | 'aria-label' | 'className' | 'style'> {
  /**
   * Which landmark this is. `banner` (site header), `navigation`, `main` (exactly one per page),
   * `complementary` (sidebar), `contentinfo` (site footer), `region` (a labelled section that
   * deserves a jump point), `search`, `form` (a labelled form that is a page-level region).
   */
  role: LandmarkRole;
  /**
   * Accessible name. Required for `region` and `form`, and whenever the page has more than one
   * landmark of the same role (two navigations: "Main" and "Footer"). Not shown visually. An empty
   * string counts as absent. `banner`, `main` and `contentinfo` never take a label: one passed to
   * them is not rendered and a development warning says so.
   */
  label?: string | undefined;
  /** The region's content. */
  children: ReactNode;
  /**
   * Web element override. By default the element is chosen from `role`; set this only when the
   * native element would be wrong, e.g. a `banner` that is not the page header.
   */
  as?: LandmarkElement | undefined;
}

declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev: boolean = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

const COPY = {
  missingLabel: 'Landmark: role "{role}" is only a landmark when it has a label.',
  labelNotTaken: 'Landmark: role "{role}" does not take a label; it was not rendered.',
} as const;

/** The element each role renders when `as` is not set. */
const DEFAULT_ELEMENT: Record<LandmarkRole, LandmarkElement> = {
  banner: 'header',
  navigation: 'nav',
  main: 'main',
  complementary: 'aside',
  contentinfo: 'footer',
  region: 'section',
  search: 'form',
  form: 'form',
};

/** The landmark role an element implies without an explicit `role`. */
const IMPLIED_ROLE: Partial<Record<LandmarkElement, LandmarkRole>> = {
  header: 'banner',
  nav: 'navigation',
  main: 'main',
  aside: 'complementary',
  footer: 'contentinfo',
  section: 'region',
  form: 'form',
};

/** Roles that never take a label. */
const UNLABELLED_ROLES: ReadonlySet<LandmarkRole> = new Set<LandmarkRole>(['banner', 'main', 'contentinfo']);

/** Roles whose duplicates must be told apart by label. */
const DISTINGUISHED_ROLES: ReadonlySet<LandmarkRole> = new Set<LandmarkRole>([
  'navigation',
  'complementary',
  'region',
  'form',
]);

/** The role a rendered Landmark carries, read back from the DOM. */
function roleOf(el: Element): string | undefined {
  return el.getAttribute('role') ?? IMPLIED_ROLE[el.tagName.toLowerCase() as LandmarkElement];
}

/** The name a rendered Landmark carries: `aria-label`, else the text `aria-labelledby` points at. */
function nameOf(el: Element, root: Document | ShadowRoot): string | null {
  const label = el.getAttribute('aria-label');
  if (label) return label;
  const ids = el.getAttribute('aria-labelledby');
  if (!ids) return null;
  const text = ids
    .split(/\s+/)
    .map((id) => root.getElementById?.(id)?.textContent?.trim() ?? '')
    .join(' ')
    .trim();
  return text || null;
}

/** Development warnings from the guidance; only the later duplicate warns, so each pair warns once. */
function warn(node: HTMLElement, role: LandmarkRole, labelDropped: boolean): void {
  if (labelDropped) console.warn(COPY.labelNotTaken.replace('{role}', role));
  const root = node.getRootNode() as Document | ShadowRoot;
  if (typeof root.querySelectorAll !== 'function') return;
  const own = nameOf(node, root);
  if ((role === 'region' || role === 'form') && own === null) {
    console.warn(COPY.missingLabel.replace('{role}', role));
  }
  if (role !== 'main' && !DISTINGUISHED_ROLES.has(role)) return;
  const earlier = Array.from(root.querySelectorAll('[data-ds="Landmark"]')).filter(
    (other) =>
      other !== node &&
      roleOf(other) === role &&
      (other.compareDocumentPosition(node) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0,
  );
  if (role === 'main') {
    if (earlier.length > 0) console.warn('Landmark: a document should contain exactly one "main" landmark.');
    return;
  }
  if (earlier.some((other) => nameOf(other, root) === own)) {
    console.warn(
      own === null
        ? `Landmark: two "${role}" landmarks in the same root both lack a label; give each a distinct label.`
        : `Landmark: two "${role}" landmarks in the same root share the label "${own}"; give each a distinct label.`,
    );
  }
}

/**
 * Landmark — Design Schema, category: layout. Renders its children inside the element and role
 * of one ARIA landmark, and nothing else: no padding, background or layout.
 *
 * When to use:
 * Wrap the page's major regions in a Landmark: one `banner` for the site header, one `main` for
 * the primary content, `navigation` for each navigation block (labelled when there is more than
 * one), `complementary` for sidebars that make sense on their own, `contentinfo` for the site
 * footer, `search` around the site search form, and `region` for any other section a user might
 * want to jump to — a "Related articles" block, a dashboard panel. Every page should have exactly
 * one `main`.
 */
export function Landmark({
  ref,
  role,
  label,
  children,
  as,
  ...rest
}: LandmarkProps & { ref?: Ref<HTMLElement> | undefined }): ReactElement {
  const nodeRef = useRef<HTMLElement>(null);
  useImperativeHandle(ref, () => nodeRef.current!, []);

  const tagName: LandmarkElement = as ?? DEFAULT_ELEMENT[role];
  // Explicit role on header/footer (they lose the landmark role inside sectioning content), when
  // `as` overrides the default element, and wherever the element does not imply the role
  // (<form role="search">).
  const explicitRole =
    tagName === 'header' ||
    tagName === 'footer' ||
    (as !== undefined && as !== DEFAULT_ELEMENT[role]) ||
    IMPLIED_ROLE[tagName] !== role;
  // An empty string counts as absent; banner, main and contentinfo never render a label.
  const hasLabel = label !== undefined && label !== '';
  const labelDropped = hasLabel && UNLABELLED_ROLES.has(role);
  const ariaLabel = hasLabel && !labelDropped ? label : undefined;
  const labelledBy = rest['aria-labelledby'];

  // Fires when the combination appears or changes, not on every render.
  useEffect(() => {
    if (!isDev || !nodeRef.current) return;
    warn(nodeRef.current, role, labelDropped);
  }, [role, ariaLabel, labelDropped, labelledBy, tagName]);

  // createElement typed on HTMLElement: JSX over a union of tags would demand a ref that fits
  // every element type at once.
  return createElement<HTMLAttributes<HTMLElement> & { 'data-ds': string }, HTMLElement>(
    tagName,
    {
      ...rest,
      ref: nodeRef,
      className: 'ds-landmark',
      'data-ds': 'Landmark',
      role: explicitRole ? role : undefined,
      'aria-label': ariaLabel,
    },
    children,
  );
}

// packages/lit/src/Landmark.ts
import { LitElement, nothing, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export type LandmarkRole =
  | 'banner'
  | 'navigation'
  | 'main'
  | 'complementary'
  | 'contentinfo'
  | 'region'
  | 'search'
  | 'form';

/** Roles that are landmarks only when they have an accessible name. */
const NAME_REQUIRED: ReadonlySet<string> = new Set(['region', 'form']);

/** Roles that never take a label: one passed to them is not rendered. */
const NO_LABEL: ReadonlySet<string> = new Set(['banner', 'main', 'contentinfo']);

/** Roles that may repeat in one root, so duplicates must be told apart by label. */
const DISTINCT_BY_LABEL: ReadonlySet<string> = new Set(['navigation', 'complementary', 'region', 'form']);

/** Implicit roles of the elements the web Landmark renders, for peers that carry no `role` attribute. */
const IMPLICIT_ROLE: Readonly<Record<string, string>> = {
  header: 'banner',
  nav: 'navigation',
  main: 'main',
  aside: 'complementary',
  footer: 'contentinfo',
  section: 'region',
  form: 'form',
};

function roleOf(el: Element): string | undefined {
  return el.getAttribute('role') ?? IMPLICIT_ROLE[el.localName];
}

/** The name the warnings count: `aria-labelledby` text, else a non-empty `aria-label`; `''` when absent. */
function nameOf(el: Element): string {
  const labelledBy = el.getAttribute('aria-labelledby');
  const root = el.getRootNode() as Document | ShadowRoot;
  if (labelledBy) {
    const text = labelledBy
      .split(/\s+/)
      .map((id) => root.getElementById(id)?.textContent?.trim() ?? '')
      .filter(Boolean)
      .join(' ');
    if (text) return text;
  }
  return el.getAttribute('aria-label')?.trim() ?? '';
}

/**
 * `<ds-landmark>` — Landmark (category: layout, APG: landmarks).
 *
 * `<ds-landmark role="navigation" label="Main">` uses **no shadow root and no
 * wrapper element**: the host itself is the landmark in the light DOM tree
 * and its children are ordinary light-DOM children. The role and accessible
 * name are plain `role` / `aria-label` attributes on the host (not
 * `ElementInternals`, which the accessible-name tooling does not read). The
 * element is a plain block; consumers lay it out like any block. There is no
 * wrapper `<nav>` or similar inside: a nested landmark of the same role would
 * be a duplicate.
 *
 * The property is `landmark` (attribute `role`) because `HTMLElement` already
 * defines `role`. `label` maps to `aria-label`; `banner`, `main` and
 * `contentinfo` never take a label, so on them neither `label` nor a
 * composite's `aria-labelledby` is rendered.
 *
 * In development it warns when no role is set, when `region` or `form` has no
 * label, when a label is passed to a role that never takes one, when `main`
 * appears twice in a root, and when two `navigation`, `complementary`,
 * `region` or `form` landmarks share a label or both lack one (only the later
 * one in document order warns). Warnings fire on mount and on a change of role
 * or label, not on every render.
 *
 * Children are ordinary light-DOM children; there is no `<slot>` and no part
 * hook — `data-ds="Landmark"` on the host is the only hook.
 */
@customElement('ds-landmark')
export class DsLandmark extends LitElement {
  /** Which landmark this is. Reflected to the host's `role` attribute; absent exposes no role. */
  @property({ type: String, reflect: true, attribute: 'role' }) accessor landmark: LandmarkRole | undefined;

  /**
   * Accessible name, rendered as `aria-label`. Required for `region` and `form`, and whenever
   * the page has more than one landmark of the same role. An empty string counts as absent.
   */
  @property({ type: String, attribute: 'aria-label' }) accessor label: string | undefined;

  /** Set while the element writes `aria-label` itself, so the write does not feed back into `label`. */
  private syncingLabel = false;

  /** A (re)connection counts as a mount for the warnings. */
  private warnPending = false;

  /** No shadow root: children stay in the light DOM and the host is the landmark. */
  protected override createRenderRoot(): HTMLElement {
    return this;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Landmark');
    // A plain block, without `display: contents` (which drops semantics in some browsers).
    if (this.style.display === '') {
      this.style.display = 'block';
    }
    this.warnPending = true;
    if (this.hasUpdated) this.requestUpdate();
  }

  override attributeChangedCallback(name: string, old: string | null, value: string | null): void {
    if (this.syncingLabel && name === 'aria-label') return;
    super.attributeChangedCallback(name, old, value);
  }

  protected override render(): typeof nothing {
    return nothing;
  }

  protected override updated(changed: PropertyValues): void {
    const refusedLabel = this.syncName();
    if (this.warnPending || changed.has('landmark') || changed.has('label')) {
      this.warnPending = false;
      this.warnInDev(refusedLabel);
    }
  }

  /**
   * Writes `aria-label` from `label`, omitting it when empty or when the role never takes a label,
   * and drops a composite's `aria-labelledby` on those roles too. Returns true when a label — from
   * either source — was passed to a role that never takes one, so it was not rendered.
   */
  private syncName(): boolean {
    const role = this.landmark;
    const refuses = role !== undefined && NO_LABEL.has(role);
    const label = this.label ? this.label : null;
    const next = refuses ? null : label;
    if (this.getAttribute('aria-label') !== next) {
      this.syncingLabel = true;
      try {
        if (next === null) this.removeAttribute('aria-label');
        else this.setAttribute('aria-label', next);
      } finally {
        this.syncingLabel = false;
      }
    }
    const droppedLabelledBy = refuses && this.hasAttribute('aria-labelledby');
    if (droppedLabelledBy) this.removeAttribute('aria-labelledby');
    return refuses && (label !== null || droppedLabelledBy);
  }

  private warnInDev(refusedLabel: boolean): void {
    if (!import.meta.env.DEV || !this.isConnected) return;
    const role = this.landmark;
    if (role === undefined) {
      console.warn('Landmark: no role is set, so no landmark is exposed.', this);
      return;
    }
    if (refusedLabel) {
      console.warn(`Landmark: role "${role}" does not take a label; it was not rendered.`, this);
    }
    const name = nameOf(this);
    if (NAME_REQUIRED.has(role) && !name) {
      console.warn(`Landmark: role "${role}" is only a landmark when it has a label.`, this);
    }
    const root = this.getRootNode() as Document | ShadowRoot;
    const earlier = Array.from(root.querySelectorAll('[data-ds="Landmark"]')).filter(
      (peer) =>
        peer !== this &&
        roleOf(peer) === role &&
        (peer.compareDocumentPosition(this) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0,
    );
    if (role === 'main' && earlier.length > 0) {
      console.warn('Landmark: role "main" appears more than once in this document.', this);
    }
    if (DISTINCT_BY_LABEL.has(role) && earlier.some((peer) => nameOf(peer) === name)) {
      console.warn(
        name
          ? `Landmark: two "${role}" landmarks share the label "${name}"; give each a distinct label.`
          : `Landmark: two "${role}" landmarks both lack a label; give each a distinct label.`,
        this,
      );
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-landmark': DsLandmark;
  }
}
