// packages/rn/src/Landmark.tsx
import * as React from 'react';
import { View } from 'react-native';
import type { AccessibilityRole, Role, ViewInstance } from 'react-native';

export type LandmarkRole =
  | 'banner'
  | 'navigation'
  | 'main'
  | 'complementary'
  | 'contentinfo'
  | 'region'
  | 'search'
  | 'form';

export interface LandmarkProps {
  /** Which landmark this is. `banner` (site header), `navigation`, `main` (exactly one per page), `complementary` (sidebar), `contentinfo` (site footer), `region` (a labelled section that deserves a jump point), `search`, `form`. */
  role: LandmarkRole;
  /** Accessible name. Required for `region` and `form`, and whenever the page has more than one landmark of the same role. Not shown visually. */
  label?: string | undefined;
  /** The region's content. */
  children: React.ReactNode;
  /** The root `View`. */
  ref?: React.Ref<ViewInstance> | undefined;
}

/** Roles whose `label` becomes the group's `accessibilityLabel` on iOS and Android. */
const LABELLED_ROLES: ReadonlySet<LandmarkRole> = new Set<LandmarkRole>(['navigation', 'region', 'form']);

/** Roles that are only landmarks when they carry a name. */
const NAME_REQUIRED_ROLES: ReadonlySet<LandmarkRole> = new Set<LandmarkRole>(['region', 'form']);

/**
 * Landmark — the page's table of contents for assistive technology. Every page
 * gets the same, correct set of regions without anyone remembering which element
 * implies which role.
 *
 * When to use: Wrap the page's major regions: one `banner`, exactly one `main`,
 * `navigation` for each navigation block (labelled when there is more than one),
 * `complementary` for sidebars, `contentinfo` for the footer, `search` around the
 * site search, and `region` for any other section a user might want to jump to. Do
 * not wrap everything, and do not use it to style a region — it has no visual
 * bindings by design.
 *
 * Renders a `View` with the `role` prop, which react-native-web turns into the
 * semantic element (`nav`, `main`, …) and iOS/Android map to the nearest
 * accessibility role or ignore. `search` is the one role missing from RN's `role`
 * union, so it is passed as the legacy `accessibilityRole="search"`, which
 * react-native-web maps to the same ARIA landmark. `label` is applied as `accessibilityLabel` only for
 * `navigation`, `region` and `form`, so the group has a name for TalkBack and
 * VoiceOver without every View announcing a role. The container is not
 * `accessible`, so its children stay individually reachable. There is no
 * jump-to-landmark on native — the value is web parity and one structure for the
 * same screen code. In development it warns when `region` or `form` has no `label`.
 */
export function Landmark({ role, label, children, ref }: LandmarkProps): React.JSX.Element {
  React.useEffect(() => {
    if (__DEV__ && NAME_REQUIRED_ROLES.has(role) && (label === undefined || label === '')) {
      console.warn(`Landmark: role "${role}" is only a landmark when it has a label.`);
    }
  }, [role, label]);

  // Every landmark role except `search` is in RN's `Role` union (RN ≥ 0.73); `search`
  // exists only in the legacy `accessibilityRole` union, which react-native-web maps
  // to the same ARIA `search` landmark.
  const nativeRole: Role | undefined = role === 'search' ? undefined : role;
  const legacyRole: AccessibilityRole | undefined = role === 'search' ? 'search' : undefined;

  return (
    <View
      ref={ref}
      testID="Landmark"
      role={nativeRole}
      accessibilityRole={legacyRole}
      accessibilityLabel={LABELLED_ROLES.has(role) ? label : undefined}
    >
      {children}
    </View>
  );
}

// packages/lit/src/Landmark.ts
import { LitElement, nothing, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export type LandmarkRole =
  | 'banner'
  | 'navigation'
  | 'main'
  | 'complementary'
  | 'contentinfo'
  | 'region'
  | 'search'
  | 'form';

/** Roles that are landmarks only when they have an accessible name. */
const NAME_REQUIRED: ReadonlySet<string> = new Set(['region', 'form']);

/** Roles that may legitimately repeat, so duplicates must be told apart by label. */
const DISTINCT_BY_LABEL: ReadonlySet<string> = new Set(['navigation', 'complementary', 'region', 'form']);

/**
 * `<ds-landmark>` — Landmark (category: layout, APG: landmarks).
 *
 * `<ds-landmark role="navigation" label="Main">` uses **no shadow root and no
 * wrapper element**: the host itself is the landmark in the light DOM tree
 * and its children are ordinary light-DOM children. The landmark role and
 * accessible name are plain `role` / `aria-label` attributes reflected
 * straight onto the host (real attributes, not `ElementInternals`, so the
 * accessible-name computation the test suite uses can see them — the same
 * attributes are what real assistive tech reads). The element is a plain
 * block; consumers lay it out like any block.
 *
 * ## When to use
 *
 * Wrap the page's major regions: one `banner`, exactly one `main`,
 * `navigation` for each navigation block (labelled when there is more than
 * one), `complementary` for sidebars, `contentinfo` for the footer, `search`
 * around the site search, and `region` for any other section a user might
 * want to jump to. Do not wrap everything; layout containers and cards are
 * not landmarks.
 *
 * @slot - The region's content (ordinary light-DOM children; there is no shadow root).
 */
@customElement('ds-landmark')
export class DsLandmark extends LitElement {
  /**
   * Which landmark this is. Exposed as the host's `role` attribute; the
   * property is named `landmark` because `HTMLElement` already defines `role`.
   */
  @property({ reflect: true, attribute: 'role' }) landmark?: LandmarkRole;

  /** Accessible name. Required for `region` and `form`, and whenever the page has more than one landmark of the same role. Reflects to `aria-label`. */
  @property({ reflect: true, attribute: 'aria-label' }) label?: string;

  /** No shadow root: children stay in the light DOM and the host is the landmark. */
  protected override createRenderRoot(): HTMLElement {
    return this;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Landmark');
    // A plain block, without `display: contents` (which drops semantics in some browsers).
    if (this.style.display === '') {
      this.style.display = 'block';
    }
    this.warnInDev();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if ((changed.has('landmark') || changed.has('label')) && this.hasUpdated) {
      this.warnInDev();
    }
  }

  protected override render() {
    return nothing;
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV || !this.isConnected) {
      return;
    }
    const role = this.landmark;
    if (role === undefined) {
      console.warn('<ds-landmark> needs a landmark role.', this);
      return;
    }
    if (NAME_REQUIRED.has(role) && !this.label) {
      console.warn(`<ds-landmark role="${role}"> is only a landmark when it has a label.`, this);
    }
    const root = this.getRootNode() as Document | ShadowRoot;
    const siblings = Array.from(root.querySelectorAll<DsLandmark>('ds-landmark')).filter(
      (candidate) => candidate !== this && candidate.landmark === role,
    );
    if (role === 'main' && siblings.length > 0) {
      console.warn('A document must have exactly one <ds-landmark role="main">.', this);
    }
    if (
      DISTINCT_BY_LABEL.has(role) &&
      siblings.some((candidate) => !candidate.label || !this.label || candidate.label === this.label)
    ) {
      console.warn(
        `Two <ds-landmark role="${role}"> elements share a label or lack one; give each a distinct label.`,
        this,
      );
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-landmark': DsLandmark;
  }
}
