// packages/react/demo-brand/src/Link.tsx
import { type ComponentPropsWithoutRef, type CSSProperties, type MouseEvent, type Ref, type ReactElement } from 'react';
import { cssVar, type TokenRef } from '@demo/tokens';
import { Icon } from './Icon';
import './Link.css';

/** `default` uses the link colors; `inherit` takes the surrounding text color. */
export type LinkTone = 'default' | 'inherit';

/** Copy strings from the schema, used verbatim. `copy.external` is the SwiftUI accessibility label and unused on web. */
const COPY = {
  externalSuffix: ' (opens in new tab)',
} as const;

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type LinkOverridableBinding = 'underlineThickness' | 'underlineOffset' | 'externalIconGap' | 'transition';

const OVERRIDE_HOOK: Record<LinkOverridableBinding, string> = {
  underlineThickness: '--demo-link-underline-thickness',
  underlineOffset: '--demo-link-underline-offset',
  externalIconGap: '--demo-link-external-icon-gap',
  transition: '--demo-link-transition',
};

function overridesToStyle(
  overrides: Partial<Record<LinkOverridableBinding, TokenRef | undefined>>,
  external: boolean,
): CSSProperties | undefined {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(OVERRIDE_HOOK) as LinkOverridableBinding[]) {
    // Overrides change values, never presence: the icon gap only applies when the icon renders.
    if (binding === 'externalIconGap' && !external) continue;
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return Object.keys(style).length > 0 ? (style as CSSProperties) : undefined;
}

export interface LinkProps
  extends Omit<
    ComponentPropsWithoutRef<'a'>,
    'href' | 'children' | 'target' | 'rel' | 'download' | 'aria-label' | 'onClick' | 'style' | 'className'
  > {
  /** The destination. A URL on web; a URL or app route on native, resolved by `onPress` when the consumer provides it. */
  href: string;
  /** The link text. Also the accessible name. Says where the link goes, not "click here". */
  label: string;
  /** Opens the destination in a new tab or the system browser and appends `copy.externalSuffix` to the accessible name, with a decorative trailing icon. */
  external?: boolean | undefined;
  /**
   * `default` uses the link colors. `inherit` takes the surrounding text color and relies on the
   * underline alone — for links inside muted or on-action text. Under `inherit` the color,
   * colorHover and colorVisited bindings are not applied: rest, hover and visited all resolve to
   * the inherited color, and the underline and the external icon follow it.
   */
  tone?: LinkTone | undefined;
  /** Downloads the resource instead of navigating, under the server's file name (a custom file name is out of scope). Web only. */
  download?: boolean | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<LinkOverridableBinding, TokenRef | undefined>> | undefined;
  /**
   * onPress — fired when the link is activated. The default navigation still happens unless the
   * consumer prevents it: call `preventDefault()` on the event or return `false`.
   */
  onClick?: ((event: MouseEvent<HTMLAnchorElement>) => void | boolean) | undefined;
}

/**
 * Link — Design Schema, category: navigation.
 *
 * When to use:
 * Use a Link for any navigation: to another page, to a screen, to an anchor within the page, to an
 * external site, or to a downloadable file. Use it inline inside body text (it renders inline by
 * default) and standalone in navigation lists. Use `external` whenever the destination leaves the
 * product, so people are warned before they lose their place.
 */
export function Link({
  ref,
  href,
  label,
  external = false,
  tone = 'default',
  download = false,
  overrides,
  onClick,
  ...rest
}: LinkProps & { ref?: Ref<HTMLAnchorElement> | undefined }): ReactElement {
  const classes = ['demo-link', `demo-link--tone-${tone}`, external ? 'demo-link--external' : null].filter(Boolean).join(' ');

  const handleClick = (event: MouseEvent<HTMLAnchorElement>): void => {
    if (onClick?.(event) === false) event.preventDefault();
  };

  return (
    <a
      {...rest}
      ref={ref}
      href={href}
      // Link's own hooks win over anything a parent passes: a parent's part goes on a wrapper it owns.
      data-ds="Link"
      data-part="anchor"
      className={classes}
      style={overrides ? overridesToStyle(overrides, external) : undefined}
      target={external ? '_blank' : undefined}
      rel={external ? 'noopener noreferrer' : undefined}
      download={download ? true : undefined}
      onClick={handleClick}
    >
      <span className="demo-link__label" data-part="label">
        {label}
      </span>
      {external ? (
        <>
          {/* Visually hidden text, not aria-label, so the accessible name still starts with the visible label. */}
          <span className="demo-link__external-suffix">{COPY.externalSuffix}</span>
          <span className="demo-link__external-icon" data-part="externalIcon">
            <Icon name="external" inline />
          </span>
        </>
      ) : null}
    </a>
  );
}

// packages/lit/src/Link.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';

export type LinkTone = 'default' | 'inherit';

/** copy.externalSuffix — appended to the accessible name of an external link. */
const EXTERNAL_SUFFIX = ' (opens in new tab)';

/** Overridable style hooks; see the `overrides` property. `color`, `colorHover`, `colorVisited`, `focusRing`, `focusRingWidth` and `focusRingRadius` are locked and excluded. */
export type LinkOverridableBinding = 'underlineThickness' | 'underlineOffset' | 'externalIconGap' | 'transition';

const HOOKS: Record<LinkOverridableBinding, string> = {
  underlineThickness: '--ds-link-underline-thickness',
  underlineOffset: '--ds-link-underline-offset',
  externalIconGap: '--ds-link-external-icon-gap',
  transition: '--ds-link-transition',
};

/**
 * `<ds-link>` — Link (category: navigation, APG pattern: link).
 *
 * Wraps a native `<a href>` in a shadow root created with `delegatesFocus`, so
 * focusing the host focuses the anchor. There is no custom event: the native
 * `click` bubbles and retargets to the host, and consumers who route
 * client-side call `preventDefault()` on it there. The host is `display: inline`
 * so a link can sit inside a `<ds-text>` paragraph.
 *
 * `href` and `label` are required but start as `''`; an empty href is the
 * consumer's authoring error (render Text instead), and Link does not warn.
 *
 * ## When to use
 *
 * Use a Link for any navigation: another page, a screen, an anchor, an
 * external site, or a downloadable file. Use `external` whenever the
 * destination leaves the product so people are warned before they lose their
 * place. Do not use a Link to trigger an action; that is a ghost Button.
 *
 * @fires click - The native anchor's click, retargeted to the host (onPress). Cancelable: `preventDefault()` skips navigation.
 */
@customElement('ds-link')
export class DsLink extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: inline;
      --ds-link-underline-thickness: var(--border-width-thin);
      --ds-link-underline-offset: var(--space-1);
      --ds-link-external-icon-gap: var(--space-1);
      --ds-link-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    [data-part='anchor'] {
      /* A link has no typography of its own: it takes the surrounding text's. */
      font: inherit;
      color: var(--color-link);
      text-decoration-line: underline;
      text-decoration-thickness: var(--ds-link-underline-thickness);
      text-underline-offset: var(--ds-link-underline-offset);
      cursor: pointer;
      transition: color var(--ds-link-transition) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='anchor'] {
        transition: none;
      }
    }

    /* colorVisited */
    [data-part='anchor']:visited {
      color: var(--color-link-visited);
    }

    /* colorHover: pointer hover only, not :active */
    [data-part='anchor']:hover {
      color: var(--color-link-hover);
    }

    /* tone=inherit: color, colorHover and colorVisited are not applied; the underline and icon follow currentColor */
    :host([tone='inherit']) [data-part='anchor'],
    :host([tone='inherit']) [data-part='anchor']:visited,
    :host([tone='inherit']) [data-part='anchor']:hover {
      color: inherit;
    }

    /* focusRing, focusRingWidth, focusRingRadius: the ring follows the inline text box */
    [data-part='anchor']:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
      border-radius: var(--radius-sm);
    }

    /* externalIconGap, on Link's own wrapper; the icon inside is 1em of the surrounding font (ds-icon inline) */
    [data-part='externalIcon'] {
      margin-inline-start: var(--ds-link-external-icon-gap);
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** The destination. A URL. */
  @property() accessor href = '';

  /** The link text. Also the accessible name. Says where the link goes, not "click here". */
  @property() accessor label = '';

  /** Opens the destination in a new tab and appends the external suffix to the accessible name, with a decorative trailing icon. */
  @property({ type: Boolean, reflect: true }) accessor external = false;

  /** `default` uses the link colors. `inherit` takes the surrounding text color and relies on the underline alone. */
  @property({ type: String, reflect: true }) accessor tone: LinkTone = 'default';

  /** Downloads the resource instead of navigating, under the server's file name. */
  @property({ type: Boolean, reflect: true }) accessor download = false;

  /** Per-instance style overrides: `{ underlineOffset: 'space.2' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<LinkOverridableBinding, TokenRef | undefined>> | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Link');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides') || changed.has('external')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    return html`<a
      part="anchor"
      data-part="anchor"
      href=${this.href}
      target=${ifDefined(this.external ? '_blank' : undefined)}
      rel=${ifDefined(this.external ? 'noopener noreferrer' : undefined)}
      ?download=${this.download}
      ><span part="label" data-part="label">${this.label}</span>${this.external
        ? html`<span class="visually-hidden">${EXTERNAL_SUFFIX}</span
            ><span part="externalIcon" data-part="externalIcon"><ds-icon name="external" inline></ds-icon></span>`
        : nothing}</a
    >`;
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as LinkOverridableBinding[]) {
      const hook = HOOKS[binding];
      // externalIconGap only applies where the externalIcon part is present.
      const ref = binding === 'externalIconGap' && !this.external ? undefined : this.overrides?.[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-link': DsLink;
  }
}
