// packages/react/src/Listbox.tsx
import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type FocusEvent,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent,
  type Ref,
  type ReactElement,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Icon, type IconName } from './Icon';
import { Text } from './Text';
import { useFormContext } from './FormContext';
import './Listbox.css';

declare const process: { env: { NODE_ENV?: string } };

/** One selectable row. */
export type ListboxOption = {
  value: string;
  label: string;
  description?: string | undefined;
  icon?: IconName | undefined;
  disabled?: boolean | undefined;
};

/** A labelled cluster of rows; groups do not nest. */
export type ListboxGroup = { group: string; options: ListboxOption[] };

/** The element type of `options`: a row or a group (Select and Combobox take the same `ListboxItem[]`). */
export type ListboxItem = ListboxOption | ListboxGroup;

/** A value, or with `multiple` an array of values. */
export type ListboxValue = string | string[];
export type ListboxMaxVisible = '5' | '8' | '12' | 'all' | 5 | 8 | 12;

/** copy.* — used verbatim; `{label}` is replaced by the `label` prop. */
const COPY = {
  empty: 'No options',
  required: '{label} is required.',
  invalid: '{label} is not valid.',
  selectedCount: '{count} selected',
  loading: 'Loading…',
} as const;

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type ListboxOverridableBinding =
  | 'border'
  | 'borderInvalid'
  | 'partGap'
  | 'borderWidth'
  | 'radius'
  | 'listPadding'
  | 'optionPaddingBlock'
  | 'optionPaddingInline'
  | 'optionGap'
  | 'optionRadius'
  | 'optionDescriptionSize'
  | 'optionSelectedWeight'
  | 'groupLabelSize'
  | 'groupLabelWeight'
  | 'groupLabelPaddingBlock'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'typeaheadReset';

const OVERRIDE_HOOK: Record<ListboxOverridableBinding, string> = {
  border: '--ds-listbox-border',
  borderInvalid: '--ds-listbox-border-invalid',
  partGap: '--ds-listbox-part-gap',
  borderWidth: '--ds-listbox-border-width',
  radius: '--ds-listbox-radius',
  listPadding: '--ds-listbox-list-padding',
  optionPaddingBlock: '--ds-listbox-option-padding-block',
  optionPaddingInline: '--ds-listbox-option-padding-inline',
  optionGap: '--ds-listbox-option-gap',
  optionRadius: '--ds-listbox-option-radius',
  optionDescriptionSize: '--ds-listbox-option-description-size',
  optionSelectedWeight: '--ds-listbox-option-selected-weight',
  groupLabelSize: '--ds-listbox-group-label-size',
  groupLabelWeight: '--ds-listbox-group-label-weight',
  groupLabelPaddingBlock: '--ds-listbox-group-label-padding-block',
  fontFamily: '--ds-listbox-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  fontSize: '--ds-listbox-font-size',
  lineHeight: '--ds-listbox-line-height',
  disabledOpacity: '--ds-listbox-disabled-opacity',
  typeaheadReset: '--ds-listbox-typeahead-reset',
};

/** Surface chrome the host popup owns while `embedded`: overrides change values, never presence. */
const EMBEDDED_NO_OP: ReadonlySet<ListboxOverridableBinding> = new Set(['border', 'borderInvalid', 'borderWidth', 'radius']);

function overridesToStyle(
  overrides: Partial<Record<ListboxOverridableBinding, TokenRef | undefined>>,
  embedded: boolean,
): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as ListboxOverridableBinding[]) {
    const ref = overrides[binding];
    // Locked bindings have no entry in the hook table, so they are ignored if passed.
    const hook = OVERRIDE_HOOK[binding];
    if (!ref || !hook || (embedded && EMBEDDED_NO_OP.has(binding))) continue;
    style[hook] = cssVar(ref);
  }
  return style as CSSProperties;
}

function isGroup(item: ListboxItem): item is ListboxGroup {
  return 'group' in item;
}

/** Rows in document order, dropping group wrappers — the unit navigation and typeahead move over. */
function flattenRows(items: ListboxItem[]): ListboxOption[] {
  const result: ListboxOption[] = [];
  for (const item of items) {
    if (isGroup(item)) result.push(...item.options);
    else result.push(item);
  }
  return result;
}

function toArray(value: ListboxValue | undefined): string[] {
  if (Array.isArray(value)) return value;
  return value === undefined ? [] : [value];
}

/** A CSS time (`120ms`, `1.2s`) in milliseconds; 0 when it cannot be read (no stylesheet loaded). */
function parseDuration(raw: string): number {
  const match = /^(-?[\d.]+)(ms|s)$/.exec(raw.trim());
  if (!match) return 0;
  const amount = Number(match[1]);
  return match[2] === 's' ? amount * 1000 : amount;
}

export interface ListboxProps
  extends Omit<
    ComponentPropsWithoutRef<'div'>,
    | 'children'
    | 'onChange'
    | 'defaultValue'
    | 'role'
    | 'tabIndex'
    | 'className'
    | 'style'
    | 'aria-label'
    | 'aria-labelledby'
    | 'aria-multiselectable'
    | 'aria-activedescendant'
    | 'aria-invalid'
    | 'aria-required'
    | 'aria-describedby'
    | 'aria-busy'
    | 'aria-disabled'
  > {
  /**
   * Accessible name of the list. When a visible Text label exists, pass its id via `labelledBy` as
   * well; on web `aria-labelledby` then wins. Always pass `label` even with `labelledBy`: it is the
   * `{label}` in `copy.required` and `copy.invalid`.
   */
  label: string;
  /** Id of a visible element that labels the list. */
  labelledBy?: string | undefined;
  /** Flat or grouped options; groups do not nest. */
  options: ListboxItem[];
  /**
   * Allow any number of selections. The value becomes an array; each option shows a check
   * indicator; selection toggles rather than moves. This is the same engine Combobox uses for
   * multi-select.
   */
  multiple?: boolean | undefined;
  /** Controlled selection: a value, or with `multiple` the exported `ListboxValue` (`string | string[]`). Omit for uncontrolled. */
  value?: ListboxValue | undefined;
  /** Initial selection (or array). */
  defaultValue?: ListboxValue | undefined;
  /**
   * Single-select only: arrow keys select as they move (the common picker feel). Set false when
   * selection has side effects, so arrows only move and Space selects.
   */
  selectionFollowsFocus?: boolean | undefined;
  /** At least one option must be selected to submit when inside a Form. */
  required?: boolean | undefined;
  /**
   * Marks the list invalid (aria-invalid, and `borderInvalid` when not `embedded`) with
   * `copy.invalid`. The list is invalid while this is true OR `error` is non-empty; clearing
   * `error` never clears an explicitly set `invalid`.
   */
  invalid?: boolean | undefined;
  /**
   * Error message rendered below the list and linked by aria-describedby; implies invalid. The
   * displayed message is `error`, then the Form's message, then while invalid `copy.required`
   * (required and nothing selected) else `copy.invalid`.
   */
  error?: string | undefined;
  /**
   * The list lives inside a popup (Select, Combobox) that owns the border, surface and radius; the
   * list draws none of its own. It keeps its own `listPadding`, and an override of `border`,
   * `borderWidth`, `surface` or `radius` is a no-op while it is set.
   */
  embedded?: boolean | undefined;
  /**
   * The option that is active when the list first receives focus (Select opens with the selected
   * option active). It wins when it names an enabled option; otherwise the first selected, else the
   * first enabled.
   */
  initialActiveValue?: string | undefined;
  /** Options are being fetched (async Combobox); the list shows `copy.loading` in place of the empty message and is aria-busy. */
  loading?: boolean | undefined;
  /**
   * The whole list is inert but readable: it stays focusable (tabindex=0, aria-disabled=true), keys,
   * hover and clicks do nothing, and `disabledOpacity` dims the list once.
   */
  disabled?: boolean | undefined;
  /**
   * Field name for Form collection. The submitted value is a string in single-select and an array
   * of strings with `multiple`; nothing selected submits no key.
   */
  name?: string | undefined;
  /** Shown when `options` is empty (a filtered Combobox with no matches). Defaults to `copy.empty`. */
  emptyMessage?: string | undefined;
  /** Height in rows before the list scrolls; `all` never scrolls. */
  maxVisible?: ListboxMaxVisible | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<ListboxOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the selection changes, with the new value (array when `multiple`). */
  onChange?: ((value: string | string[]) => void) | undefined;
  /** Fired as the focused (active) option changes, with its value; null when the list loses focus. */
  onActiveChange?: ((value: string | null) => void) | undefined;
}

/**
 * Listbox — Design Schema, category: input.
 *
 * When to use:
 * Use a standalone Listbox when the options should stay visible: a settings picker with five to twenty entries, a transfer list, the sidebar of a two-pane chooser. Use `multiple` for "pick any": tags, recipients, filters. Set `selectionFollowsFocus: false` when selecting has side effects (loading a preview), so arrow-key browsing does not trigger them. Everywhere else, use Select (short lists, form fields) or Combobox (long lists, typing to filter) — both open a Listbox.
 *
 * The root is a wrapper `div` (data-ds, data-ds-field) holding the `role="listbox"` list and the
 * error message. `id` names the list, and option ids are `${id}-option-${value}`. Keyboard and focus
 * handlers sit on the wrapper, so a host (Select) may dispatch `keydown`/`focusin` on the ref.
 */
export function Listbox({
  ref,
  label,
  labelledBy,
  options,
  multiple = false,
  value,
  defaultValue,
  selectionFollowsFocus = true,
  required = false,
  invalid = false,
  error,
  embedded = false,
  initialActiveValue,
  loading = false,
  disabled = false,
  name,
  emptyMessage,
  maxVisible = '8',
  overrides,
  onChange,
  onActiveChange,
  onBlur,
  onFocus,
  onKeyDown,
  id: idProp,
  ...rest
}: ListboxProps & { ref?: Ref<HTMLDivElement> | undefined }): ReactElement {
  const form = useFormContext();
  const generatedId = useId();
  const id = idProp ?? (form?.idBase && name ? `${form.idBase}-${name}` : `ds-listbox${generatedId}`);
  const errorId = `${id}-error`;

  const listRef = useRef<HTMLDivElement | null>(null);
  const optionRefs = useRef(new Map<string, HTMLDivElement>());
  const typeahead = useRef<{ buffer: string; timer: ReturnType<typeof setTimeout> | null }>({ buffer: '', timer: null });

  useEffect(
    () => () => {
      if (typeahead.current.timer) clearTimeout(typeahead.current.timer);
    },
    [],
  );

  useEffect(() => {
    if (process.env.NODE_ENV !== 'production' && !label) {
      console.warn('Listbox: `label` is required, even with `labelledBy` — it is the {label} in the validation copy.');
    }
  }, [label]);

  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = useState<ListboxValue | undefined>(defaultValue);
  const selected = isControlled ? value : internalValue;
  const selectedValues = toArray(selected);

  const [activeValue, setActiveValueState] = useState<string | null>(null);

  const isDisabled = disabled || (form?.disabled ?? false);
  const nothingSelected = selectedValues.length === 0;
  const formError = name ? form?.errors[name] : undefined;
  const isInvalid = invalid || (error !== undefined && error !== '');
  // Precedence: error → the Form's message → while invalid, copy.required (required, nothing selected) else copy.invalid.
  const resolvedError =
    (error !== undefined && error !== '' ? error : undefined) ??
    formError ??
    (isInvalid ? (required && nothingSelected ? COPY.required : COPY.invalid).replace('{label}', label) : undefined);
  const showsInvalid = isInvalid || resolvedError !== undefined;

  const rows = useMemo(() => flattenRows(options), [options]);
  const enabledRows = useMemo(() => rows.filter((row) => !row.disabled), [rows]);
  const maxVisibleKey = String(maxVisible) as '5' | '8' | '12' | 'all';

  const latest = useRef({ label, required, invalid, error, disabled: isDisabled, selected, multiple });
  latest.current = { label, required, invalid, error, disabled: isDisabled, selected, multiple };

  useEffect(() => {
    // Without `name` the list submits nothing (Form skips unnamed fields).
    if (!form || !name) return undefined;
    return form.register({
      name,
      id,
      get label() {
        return latest.current.label;
      },
      // form.valueType is string[]: every selected value with `multiple`, the value otherwise; no key when empty.
      getValue: () => {
        const values = toArray(latest.current.selected);
        if (values.length === 0) return undefined;
        return latest.current.multiple ? values : values[0];
      },
      isDisabled: () => latest.current.disabled,
      validate: () => {
        const { label: currentLabel, required: isRequired, invalid: isInvalidProp, error: errorProp, selected: current } =
          latest.current;
        if (errorProp !== undefined && errorProp !== '') return errorProp;
        if (isRequired && toArray(current).length === 0) return COPY.required.replace('{label}', currentLabel);
        if (isInvalidProp) return COPY.invalid.replace('{label}', currentLabel);
        return null;
      },
      focus: () => listRef.current?.focus(),
    });
  }, [form, name, id]);

  const isSelected = (optionValue: string) => selectedValues.includes(optionValue);

  const commitValue = (next: ListboxValue) => {
    if (!Array.isArray(next) && next === selected) return;
    if (!isControlled) setInternalValue(next);
    onChange?.(next);
    if (form && name && form.validate === 'change') form.validateField(name);
  };

  /** onChange receives the array in option order. */
  const inOptionOrder = (values: string[]) => rows.map((row) => row.value).filter((v) => values.includes(v));

  const setActiveValue = (next: string | null) => {
    if (next !== null) optionRefs.current.get(next)?.scrollIntoView?.({ block: 'nearest' });
    if (next === activeValue) return;
    setActiveValueState(next);
    onActiveChange?.(next);
  };

  /** Arrows, Home/End, PageUp/PageDown and typeahead all move this way: select too when selection follows focus. */
  const moveActive = (optionValue: string) => {
    setActiveValue(optionValue);
    if (!multiple && selectionFollowsFocus) commitValue(optionValue);
  };

  const toggle = (optionValue: string) => {
    commitValue(
      inOptionOrder(
        selectedValues.includes(optionValue)
          ? selectedValues.filter((v) => v !== optionValue)
          : [...selectedValues, optionValue],
      ),
    );
  };

  const selectRow = (row: ListboxOption) => {
    if (isDisabled || row.disabled) return;
    if (multiple) toggle(row.value);
    else commitValue(row.value);
  };

  /** Where focus lands first: `initialActiveValue` when enabled, else the first selected, else the first enabled. */
  const resolveInitialActive = (): string | undefined => {
    if (initialActiveValue !== undefined && enabledRows.some((row) => row.value === initialActiveValue)) {
      return initialActiveValue;
    }
    return (enabledRows.find((row) => isSelected(row.value)) ?? enabledRows[0])?.value;
  };

  const handleTypeahead = (char: string, currentIndex: number) => {
    const state = typeahead.current;
    if (state.timer) clearTimeout(state.timer);
    state.buffer += char.toLowerCase();
    // typeaheadReset is read at runtime from the list, never a number written here.
    const list = listRef.current;
    const reset = list ? parseDuration(getComputedStyle(list).getPropertyValue('--ds-listbox-typeahead-reset')) : 0;
    state.timer = setTimeout(() => {
      state.buffer = '';
    }, reset);

    const count = enabledRows.length;
    // A repeated single letter cycles; a longer prefix keeps matching the current option first.
    const startOffset = state.buffer.length > 1 || currentIndex === -1 ? 0 : 1;
    const start = currentIndex === -1 ? 0 : currentIndex;
    for (let offset = startOffset; offset < count + startOffset; offset++) {
      const candidate = enabledRows[(start + offset) % count];
      if (candidate && candidate.label.toLowerCase().startsWith(state.buffer)) {
        moveActive(candidate.value);
        return;
      }
    }
  };

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    onKeyDown?.(event);
    if (event.defaultPrevented || isDisabled || enabledRows.length === 0) return;
    const currentIndex = activeValue === null ? -1 : enabledRows.findIndex((row) => row.value === activeValue);
    const last = enabledRows.length - 1;

    switch (event.key) {
      case 'ArrowDown':
      case 'ArrowUp': {
        event.preventDefault();
        const down = event.key === 'ArrowDown';
        // Clamps at the first and last enabled option; with no active option the first press lands on an end.
        const targetIndex =
          currentIndex === -1 ? (down ? 0 : last) : Math.min(Math.max(currentIndex + (down ? 1 : -1), 0), last);
        const target = enabledRows[targetIndex]!;
        if (multiple && event.shiftKey) {
          // Add only: an already-selected option stays selected.
          setActiveValue(target.value);
          if (!selectedValues.includes(target.value)) commitValue(inOptionOrder([...selectedValues, target.value]));
        } else {
          moveActive(target.value);
        }
        break;
      }
      case 'Home':
        event.preventDefault();
        moveActive(enabledRows[0]!.value);
        break;
      case 'End':
        event.preventDefault();
        moveActive(enabledRows[last]!.value);
        break;
      case 'PageDown':
      case 'PageUp': {
        event.preventDefault();
        const down = event.key === 'PageDown';
        let targetIndex: number;
        // With no active option PageDown lands on the first enabled option and PageUp on the last.
        if (currentIndex === -1) targetIndex = down ? 0 : last;
        else if (maxVisibleKey === 'all') targetIndex = down ? last : 0;
        else targetIndex = Math.min(Math.max(currentIndex + (down ? 1 : -1) * Number(maxVisibleKey), 0), last);
        moveActive(enabledRows[targetIndex]!.value);
        break;
      }
      case ' ': {
        event.preventDefault();
        const target = currentIndex === -1 ? resolveInitialActive() : enabledRows[currentIndex]!.value;
        const row = enabledRows.find((candidate) => candidate.value === target);
        if (!row) break;
        setActiveValue(row.value);
        selectRow(row);
        break;
      }
      case 'Enter': {
        // Enter selects only in single-select; with `multiple` it is a no-op (Space toggles).
        if (multiple) break;
        const target = currentIndex === -1 ? resolveInitialActive() : enabledRows[currentIndex]!.value;
        if (target === undefined) break;
        event.preventDefault();
        setActiveValue(target);
        commitValue(target);
        break;
      }
      default: {
        if (multiple && event.ctrlKey && !event.altKey && !event.metaKey && event.key.toLowerCase() === 'a') {
          event.preventDefault();
          const all = enabledRows.map((row) => row.value);
          const allSelected = all.every((v) => selectedValues.includes(v));
          // Selected disabled options stay selected either way.
          const keep = selectedValues.filter((v) => !all.includes(v));
          commitValue(inOptionOrder(allSelected ? keep : [...keep, ...all]));
        } else if (/^[a-z]$/i.test(event.key) && !event.ctrlKey && !event.metaKey && !event.altKey) {
          handleTypeahead(event.key, currentIndex);
        }
      }
    }
  };

  const handleFocus = (event: FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    // The list itself, or a host signalling focus on the root (Select keeps DOM focus on its trigger).
    if ((event.target !== listRef.current && event.target !== event.currentTarget) || activeValue !== null) return;
    const initial = resolveInitialActive();
    if (initial !== undefined) setActiveValue(initial);
  };

  const handleBlur = (event: FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (event.target !== listRef.current) return;
    setActiveValue(null);
    if (form && name && (form.validate === 'blur' || form.validate === 'change')) form.validateField(name);
  };

  const handleRowPointerMove = (row: ListboxOption) => {
    if (isDisabled || row.disabled) return;
    setActiveValue(row.value);
  };

  const handleRowClick = (row: ListboxOption) => (event: ReactMouseEvent<HTMLDivElement>) => {
    if (isDisabled || row.disabled) {
      event.preventDefault();
      return;
    }
    setActiveValue(row.value);
    selectRow(row);
  };

  const setRowRef = (rowValue: string) => (element: HTMLDivElement | null) => {
    if (element) optionRefs.current.set(rowValue, element);
    else optionRefs.current.delete(rowValue);
  };

  const renderRow = (row: ListboxOption) => {
    const optionId = `${id}-option-${row.value}`;
    const descriptionId = row.description ? `${optionId}-description` : undefined;
    const rowSelected = isSelected(row.value);
    const rowDisabled = isDisabled || row.disabled === true;
    const classes = [
      'ds-listbox__option',
      row.value === activeValue ? 'ds-listbox__option--active' : null,
      rowSelected ? 'ds-listbox__option--selected' : null,
      row.disabled ? 'ds-listbox__option--disabled' : null,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div
        key={row.value}
        ref={setRowRef(row.value)}
        id={optionId}
        role="option"
        data-part="option"
        aria-selected={rowSelected ? 'true' : 'false'}
        aria-disabled={rowDisabled ? 'true' : undefined}
        aria-describedby={descriptionId}
        className={classes}
        onPointerMove={() => handleRowPointerMove(row)}
        onClick={handleRowClick(row)}
      >
        {multiple ? (
          // Always present with `multiple` (invisible when unselected) so labels align.
          <span className="ds-listbox__check" data-part="optionCheck" aria-hidden="true">
            <Icon name="check" size="sm" overrides={{ color: 'color.control.selectedBackground' as TokenRef }} />
          </span>
        ) : null}
        {row.icon ? (
          <span className="ds-listbox__icon" data-part="optionIcon" aria-hidden="true">
            <Icon name={row.icon} size="sm" />
          </span>
        ) : null}
        <span className="ds-listbox__text">
          <span className="ds-listbox__label" data-part="optionLabel">
            {row.label}
          </span>
          {row.description ? (
            <span id={descriptionId} className="ds-listbox__description" data-part="optionDescription">
              {row.description}
            </span>
          ) : null}
        </span>
      </div>
    );
  };

  const renderItem = (item: ListboxItem, index: number): ReactElement | null => {
    if (!isGroup(item)) return renderRow(item);
    // Empty groups are omitted.
    if (item.options.length === 0) return null;
    const groupLabelId = `${id}-group-${index}`;
    return (
      <div key={`group-${index}`} role="group" aria-labelledby={groupLabelId} data-part="group" className="ds-listbox__group">
        <div id={groupLabelId} data-part="groupLabel" className="ds-listbox__group-label">
          {item.group}
        </div>
        {item.options.map(renderRow)}
      </div>
    );
  };

  const classes = [
    'ds-listbox',
    `ds-listbox--max-visible-${maxVisibleKey}`,
    embedded ? 'ds-listbox--embedded' : null,
    isDisabled ? 'ds-listbox--disabled' : null,
    showsInvalid ? 'ds-listbox--invalid' : null,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div
      {...rest}
      ref={ref}
      data-ds="Listbox"
      data-ds-field=""
      className={classes}
      style={overrides ? overridesToStyle(overrides, embedded) : undefined}
      onKeyDown={handleKeyDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
    >
      <div
        ref={listRef}
        id={id}
        data-part="list"
        role="listbox"
        tabIndex={0}
        className="ds-listbox__list"
        aria-label={label}
        aria-labelledby={labelledBy}
        aria-multiselectable={multiple ? 'true' : undefined}
        aria-activedescendant={activeValue !== null ? `${id}-option-${activeValue}` : undefined}
        aria-invalid={showsInvalid ? 'true' : undefined}
        aria-required={required ? 'true' : undefined}
        aria-describedby={resolvedError !== undefined ? errorId : undefined}
        aria-busy={loading ? 'true' : undefined}
        aria-disabled={isDisabled ? 'true' : undefined}
      >
        {rows.length === 0 ? (
          <div className="ds-listbox__empty">
            <Text data-part="emptyState" tone="muted">
              {loading ? COPY.loading : (emptyMessage ?? COPY.empty)}
            </Text>
          </div>
        ) : (
          options.map(renderItem)
        )}
      </div>
      {resolvedError !== undefined ? (
        <Text id={errorId} data-part="errorMessage" size="sm" tone="danger">
          {resolvedError}
        </Text>
      ) : null}
    </div>
  );
}

// packages/lit/src/Listbox.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';
import './Text.js';
import type { IconName } from './Icon.js';

export type ListboxMaxVisible = '5' | '8' | '12' | 'all';

/** A single selectable entry (anatomy: option, optionLabel, optionDescription, optionIcon). */
export interface ListboxItem {
  value: string;
  label: string;
  description?: string;
  icon?: IconName;
  disabled?: boolean;
}

/** A labelled group of entries (anatomy: group, groupLabel). */
export interface ListboxGroupOption {
  group: string;
  options: ListboxOption[];
}

/** Flat or grouped entry in `options`. */
export type ListboxOption = ListboxItem | ListboxGroupOption;

/** `value`/`defaultValue` shape: a single value, or with `multiple` an array. */
export type ListboxValue = string | string[];

/** Detail carried by the `change` CustomEvent. */
export interface ListboxChangeDetail {
  value: ListboxValue;
}

/** Detail carried by the `active-change` CustomEvent. */
export interface ListboxActiveChangeDetail {
  value: string | null;
}

/** copy.empty */
const COPY_EMPTY = 'No options';
/** copy.required */
const COPY_REQUIRED = (label: string): string => `${label} is required.`;
/**
 * copy.selectedCount — not part of Listbox's own anatomy (nothing here renders a
 * count), so it is exported for composing components (a Select trigger, a
 * Combobox input) that show the selection summary elsewhere in their UI.
 */
export const LISTBOX_COPY_SELECTED_COUNT = (count: number): string => `${count} selected`;

/** How long a typed-character run is remembered for typeahead before it resets. Not a design token — an interaction timing, not a motion one. */
const TYPEAHEAD_RESET_MS = 500;

/** Overridable style hooks; see the `overrides` property. `surface`, `optionColor`, `optionDescriptionColor`, `optionActiveBackground`, `optionSelectedCheck`, `groupLabelColor`, `emptyColor`, `minTarget`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type ListboxOverridableBinding =
  | 'border'
  | 'borderWidth'
  | 'radius'
  | 'listPadding'
  | 'optionPaddingBlock'
  | 'optionPaddingInline'
  | 'optionGap'
  | 'optionRadius'
  | 'optionDescriptionSize'
  | 'optionSelectedWeight'
  | 'groupLabelSize'
  | 'groupLabelWeight'
  | 'groupLabelPaddingBlock'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'disabledOpacity';

const HOOKS: Record<ListboxOverridableBinding, string> = {
  border: '--ds-listbox-border',
  borderWidth: '--ds-listbox-border-width',
  radius: '--ds-listbox-radius',
  listPadding: '--ds-listbox-list-padding',
  optionPaddingBlock: '--ds-listbox-option-padding-block',
  optionPaddingInline: '--ds-listbox-option-padding-inline',
  optionGap: '--ds-listbox-option-gap',
  optionRadius: '--ds-listbox-option-radius',
  optionDescriptionSize: '--ds-listbox-option-description-size',
  optionSelectedWeight: '--ds-listbox-option-selected-weight',
  groupLabelSize: '--ds-listbox-group-label-size',
  groupLabelWeight: '--ds-listbox-group-label-weight',
  groupLabelPaddingBlock: '--ds-listbox-group-label-padding-block',
  fontFamily: '--ds-listbox-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-listbox-font-size',
  lineHeight: '--ds-listbox-line-height',
  disabledOpacity: '--ds-listbox-disabled-opacity',
};

let listboxInstanceCount = 0;

function isGroupOption(option: ListboxOption): option is ListboxGroupOption {
  return 'group' in option;
}

/** Depth-first list of every selectable item, groups flattened. */
function flattenOptions(options: ListboxOption[]): ListboxItem[] {
  const result: ListboxItem[] = [];
  for (const option of options) {
    if (isGroupOption(option)) {
      result.push(...flattenOptions(option.options));
    } else {
      result.push(option);
    }
  }
  return result;
}

/**
 * `<ds-listbox>` — Listbox (category: input, APG pattern: listbox).
 *
 * `<ds-listbox label="Assignees" .options=${options}>` renders one
 * `role="listbox"` `<div tabindex="0">` in its shadow root, with
 * `role="option"` children for each entry (and `role="group"` wrappers for
 * grouped entries). It is a single tab stop: arrow keys, Home/End,
 * PageUp/PageDown and typeahead move `aria-activedescendant` between the
 * option children instead of moving real DOM focus, which works because the
 * list and its options share this shadow root. `options` and `value` are
 * properties, not attributes (arrays/unions are not attribute-safe). Choosing
 * an option fires a composed `change` CustomEvent with the new value (an
 * array in option order when `multiple`); moving the active option fires
 * `active-change`. The element is form-associated: `setFormValue` receives a
 * plain string for single-select and a `FormData` with one entry per value
 * for `multiple`, the same shape a native `<select multiple>` submits.
 * `handleKey` and `activeValue` are public so a future `<ds-combobox>` can
 * forward its input's keydowns into a composed listbox and keep its own
 * `aria-activedescendant` in sync.
 *
 * ## When to use
 *
 * Use a standalone Listbox when the options should stay visible: a settings
 * picker with five to twenty entries, a transfer list. Use `multiple` for
 * "pick any". Set `selectionFollowsFocus: false` when selecting has side
 * effects, so arrow-key browsing does not trigger them.
 *
 * ## When not to use
 *
 * Not for two to seven options that fit without scrolling (RadioGroup or
 * Checkboxes), not for actions (Menu) or navigation (Links).
 *
 * @fires change - Fired when the selection changes, with `{ value }` (array when `multiple`) in `detail`.
 * @fires active-change - Fired as the active option changes, with `{ value }` in `detail`.
 * @csspart list - The `role="listbox"` container (anatomy: list).
 * @csspart group - Each grouped section (anatomy: group).
 * @csspart group-label - Each group's non-interactive heading row (anatomy: groupLabel).
 * @csspart option - Each `role="option"` row (anatomy: option).
 * @csspart option-label - An option's label (anatomy: optionLabel).
 * @csspart option-description - An option's second line (anatomy: optionDescription).
 * @csspart option-icon - An option's leading `<ds-icon>` (anatomy: optionIcon).
 * @csspart option-check - An option's selected-state `<ds-icon>`, always rendered so labels align (anatomy: optionCheck).
 * @csspart empty-state - The `<ds-text>` shown when `options` is empty (anatomy: emptyState).
 */
@customElement('ds-listbox')
export class DsListbox extends LitElement {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      --ds-listbox-border: var(--color-border-strong);
      --ds-listbox-border-width: var(--border-width-thin);
      --ds-listbox-radius: var(--radius-md);
      --ds-listbox-list-padding: var(--space-1);
      --ds-listbox-option-padding-block: var(--space-sm);
      --ds-listbox-option-padding-inline: var(--space-md);
      --ds-listbox-option-gap: var(--layout-gap-normal);
      --ds-listbox-option-radius: var(--radius-sm);
      --ds-listbox-option-description-size: var(--font-size-sm);
      --ds-listbox-option-selected-weight: var(--font-weight-medium);
      --ds-listbox-group-label-size: var(--font-size-xs);
      --ds-listbox-group-label-weight: var(--font-weight-semibold);
      --ds-listbox-group-label-padding-block: var(--space-1);
      --ds-listbox-font-family: var(--font-family-body);
      --ds-listbox-font-size: var(--font-size-md);
      --ds-listbox-line-height: var(--font-line-height-normal);
      --ds-listbox-disabled-opacity: var(--opacity-disabled);
    }

    :host([hidden]) {
      display: none;
    }

    /* surface: color.background, locked */
    .list {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      padding: var(--ds-listbox-list-padding);
      border-style: solid;
      border-width: var(--ds-listbox-border-width);
      border-color: var(--ds-listbox-border);
      border-radius: var(--ds-listbox-radius);
      background: var(--color-background);
      font-family: var(--ds-listbox-font-family);
      font-size: var(--ds-listbox-font-size);
      line-height: var(--ds-listbox-line-height);
      overflow-y: auto;
      outline: none;
      /* maxVisible: rows × one option's measured block size */
      max-block-size: calc(
        (
            var(--ds-listbox-font-size) * var(--ds-listbox-line-height) + 2 * var(--ds-listbox-option-padding-block)
          ) * var(--ds-listbox-rows, 8)
      );
    }

    .list.is-max-visible-all {
      max-block-size: none;
      overflow-y: visible;
    }

    /* focusRing / focusRingWidth: color.border.focus / border.width.focus, locked */
    .list:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: calc(-1 * var(--border-width-focus));
    }

    :host([disabled]) .list {
      cursor: not-allowed;
    }

    .group {
      display: flex;
      flex-direction: column;
    }

    /* groupLabelColor: color.foreground.muted, locked */
    .group-label {
      padding-block: var(--ds-listbox-group-label-padding-block);
      padding-inline: var(--ds-listbox-option-padding-inline);
      font-size: var(--ds-listbox-group-label-size);
      font-weight: var(--ds-listbox-group-label-weight);
      color: var(--color-foreground-muted);
    }

    /* minTarget: size.target.min, locked */
    .option {
      box-sizing: border-box;
      display: flex;
      align-items: center;
      gap: var(--ds-listbox-option-gap);
      min-block-size: var(--size-target-min);
      padding-block: var(--ds-listbox-option-padding-block);
      padding-inline: var(--ds-listbox-option-padding-inline);
      border-radius: var(--ds-listbox-option-radius);
      /* optionColor: color.foreground, locked */
      color: var(--color-foreground);
      cursor: pointer;
      user-select: none;
    }

    /* optionActiveBackground: color.background.subtle, locked — keyboard and hover share it, so active is never hover-only */
    .option.is-active {
      background: var(--color-background-subtle);
    }

    .option[aria-disabled='true'] {
      opacity: var(--ds-listbox-disabled-opacity);
      cursor: not-allowed;
    }

    /* optionSelectedWeight: selection is marked by weight and the check, never color alone */
    .option[aria-selected='true'] .option-label {
      font-weight: var(--ds-listbox-option-selected-weight);
    }

    /* optionSelectedCheck: color.control.selectedBackground, locked; always rendered (invisible when unselected) so labels align */
    .option-check {
      flex: none;
      color: var(--color-control-selected-background);
      visibility: hidden;
    }
    .option[aria-selected='true'] .option-check {
      visibility: visible;
    }

    .option-icon {
      flex: none;
    }

    .option-text {
      display: flex;
      flex-direction: column;
      min-inline-size: 0;
    }

    .option-label {
      min-inline-size: 0;
    }

    /* optionDescriptionColor: color.foreground.muted, locked */
    .option-description {
      font-size: var(--ds-listbox-option-description-size);
      color: var(--color-foreground-muted);
    }

    .empty {
      display: block;
      padding-block: var(--ds-listbox-option-padding-block);
      padding-inline: var(--ds-listbox-option-padding-inline);
    }
  `;

  /** Accessible name of the list. Ignored when `labelledBy` is set. */
  @property() label!: string;

  /** Id of a visible element (in this shadow root) that labels the list, taking priority over `label`. */
  @property() labelledBy?: string;

  /** Flat or grouped options in display order. A property, not an attribute. */
  @property({ attribute: false }) options: ListboxOption[] = [];

  /** Allow any number of selections; the value becomes an array. */
  @property({ type: Boolean, reflect: true }) multiple = false;

  /** Controlled selection: a value, or with `multiple` an array. Omit for uncontrolled. */
  @property({ attribute: false }) value?: ListboxValue;

  /** Initial selection (or array) for an uncontrolled list. */
  @property({ attribute: false }) defaultValue?: ListboxValue;

  /**
   * Single-select only: arrow keys select as they move. Boolean attributes
   * cannot express `false` while the default is `true`, so the attribute is
   * the negation — `no-selection-follows-focus` present means this is `false`.
   */
  @property({
    attribute: 'no-selection-follows-focus',
    converter: {
      fromAttribute: (value: string | null): boolean => value === null,
      toAttribute: (value: boolean): string | null => (value ? null : ''),
    },
  })
  selectionFollowsFocus = true;

  /** At least one option must be selected to submit when inside a Form. */
  @property({ type: Boolean, reflect: true }) required = false;

  /** The whole list is inert but readable. Individual options use `options[].disabled`. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  /** Field name for Form collection. Multiple values are collected as an array. */
  @property() name = '';

  /** Shown when `options` is empty. Defaults to `copy.empty`. */
  @property({ attribute: 'empty-message' }) emptyMessage?: string;

  /** Height in rows before the list scrolls; `all` never scrolls. */
  @property({ attribute: 'max-visible' }) maxVisible: ListboxMaxVisible = '8';

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<ListboxOverridableBinding, TokenRef>>;

  /** Uncontrolled selection (seeded from `defaultValue`). */
  @state() private internalValue?: ListboxValue;

  /**
   * The option currently carrying `aria-activedescendant`, public so a
   * composing `<ds-combobox>` can read it and keep its own activedescendant
   * in sync.
   */
  @state() activeValue: string | null = null;

  /** Disabled by an owning native form / fieldset (via `formDisabledCallback`). */
  @state() private formDisabled = false;

  @query('.list') private readonly listEl?: HTMLElement;

  private readonly instanceId = `ds-listbox-${++listboxInstanceCount}`;
  private typeaheadQuery = '';
  private typeaheadTimer?: ReturnType<typeof setTimeout>;

  private readonly internals: ElementInternals;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  /** Every selectable item, groups flattened, in document order. */
  private get flatItems(): ListboxItem[] {
    return flattenOptions(this.options);
  }

  private get enabledItems(): ListboxItem[] {
    return this.flatItems.filter((item) => item.disabled !== true);
  }

  private get isDisabled(): boolean {
    return this.disabled || this.formDisabled;
  }

  /** The current selection: a value, an array (`multiple`), or `null` when nothing is selected (no key in the Form). */
  get currentValue(): ListboxValue | null {
    const value = this.value ?? this.internalValue;
    if (this.multiple) {
      const list = Array.isArray(value) ? value : [];
      return list.length > 0 ? list : null;
    }
    return typeof value === 'string' && value !== '' ? value : null;
  }

  /** The owning native form, if any (from `ElementInternals`). */
  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  get validationMessage(): string {
    return this.internals.validationMessage;
  }

  private get selectedSet(): Set<string> {
    const value = this.currentValue;
    if (this.multiple) {
      return new Set(Array.isArray(value) ? value : []);
    }
    return new Set(typeof value === 'string' ? [value] : []);
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Listbox');
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    clearTimeout(this.typeaheadTimer);
  }

  checkValidity(): boolean {
    this.syncInternals();
    return this.internals.checkValidity();
  }

  reportValidity(): boolean {
    this.syncInternals();
    return this.internals.reportValidity();
  }

  formDisabledCallback(disabled: boolean): void {
    this.formDisabled = disabled;
  }

  formResetCallback(): void {
    this.value = undefined;
    this.internalValue = this.defaultValue;
  }

  formStateRestoreCallback(state: File | string | FormData | null): void {
    if (typeof state === 'string' && !this.multiple) {
      this.value = state;
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (!this.hasUpdated) {
      this.internalValue = this.defaultValue;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.syncInternals();
    this.warnInDev();
  }

  protected override render() {
    const items = this.flatItems;
    const isEmpty = items.length === 0;
    const optionIds = new Map<string, string>();
    items.forEach((item, index) => optionIds.set(item.value, `${this.instanceId}-option-${index}`));
    const activeId = this.activeValue !== null ? optionIds.get(this.activeValue) : undefined;
    const rowsStyle =
      this.maxVisible === 'all' ? {} : { '--ds-listbox-rows': this.maxVisible };

    return html`
      <div
        id="list"
        class=${classMap({ list: true, 'is-max-visible-all': this.maxVisible === 'all' })}
        style=${styleMap(rowsStyle)}
        part="list"
        role="listbox"
        tabindex=${this.isDisabled ? -1 : 0}
        aria-label=${ifDefined(this.labelledBy ? undefined : this.label)}
        aria-labelledby=${ifDefined(this.labelledBy)}
        aria-multiselectable=${ifDefined(this.multiple ? 'true' : undefined)}
        aria-required=${ifDefined(this.required ? 'true' : undefined)}
        aria-disabled=${ifDefined(this.isDisabled ? 'true' : undefined)}
        aria-activedescendant=${ifDefined(activeId)}
        @keydown=${this.handleKey}
        @focus=${this.handleListFocus}
      >
        ${isEmpty
          ? html`<ds-text class="empty" part="empty-state" tone="muted"
              >${this.emptyMessage || COPY_EMPTY}</ds-text
            >`
          : this.renderOptionList(this.options, optionIds)}
      </div>
    `;
  }

  private renderOptionList(options: ListboxOption[], optionIds: Map<string, string>) {
    let groupCounter = 0;
    const render = (opts: ListboxOption[]): unknown[] =>
      opts.map((option) => {
        if (isGroupOption(option)) {
          const labelId = `${this.instanceId}-group-${groupCounter++}`;
          return html`
            <div class="group" part="group" role="group" aria-labelledby=${labelId}>
              <div class="group-label" part="group-label" id=${labelId}>${option.group}</div>
              ${render(option.options)}
            </div>
          `;
        }
        return this.renderOption(option, optionIds.get(option.value)!);
      });
    return render(options);
  }

  private renderOption(item: ListboxItem, id: string) {
    const disabled = this.isDisabled || item.disabled === true;
    const selected = this.selectedSet.has(item.value);
    const active = this.activeValue === item.value;
    return html`
      <div
        id=${id}
        class=${classMap({ option: true, 'is-active': active })}
        part="option"
        role="option"
        data-value=${item.value}
        aria-selected=${selected ? 'true' : 'false'}
        aria-disabled=${ifDefined(disabled ? 'true' : undefined)}
        @click=${() => this.handleOptionClick(item)}
        @pointerenter=${() => this.handleOptionPointerEnter(item)}
      >
        <ds-icon class="option-check" part="option-check" name="check"></ds-icon>
        ${item.icon ? html`<ds-icon class="option-icon" part="option-icon" name=${item.icon}></ds-icon>` : nothing}
        <div class="option-text">
          <span class="option-label" part="option-label">${item.label}</span>
          ${item.description
            ? html`<span class="option-description" part="option-description">${item.description}</span>`
            : nothing}
        </div>
      </div>
    `;
  }

  /** Public so a composing `<ds-combobox>` can forward its input's keydowns here. */
  readonly handleKey = (event: KeyboardEvent): void => {
    if (this.isDisabled) {
      return;
    }
    const key = event.key;

    if (this.multiple && event.shiftKey && (key === 'ArrowDown' || key === 'ArrowUp')) {
      event.preventDefault();
      this.extendSelection(key === 'ArrowDown' ? 1 : -1);
      return;
    }
    if (this.multiple && (event.ctrlKey || event.metaKey) && key.toLowerCase() === 'a') {
      event.preventDefault();
      this.toggleSelectAll();
      return;
    }

    switch (key) {
      case 'ArrowDown':
        event.preventDefault();
        this.moveActive(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.moveActive(-1);
        break;
      case 'Home':
        event.preventDefault();
        this.setActiveEdge('first');
        break;
      case 'End':
        event.preventDefault();
        this.setActiveEdge('last');
        break;
      case ' ':
        event.preventDefault();
        this.selectActive();
        break;
      case 'Enter':
        if (!this.multiple) {
          event.preventDefault();
          this.selectActive();
        }
        break;
      case 'PageDown':
        event.preventDefault();
        this.pageActive(1);
        break;
      case 'PageUp':
        event.preventDefault();
        this.pageActive(-1);
        break;
      default:
        if (key.length === 1 && /[a-z]/i.test(key)) {
          this.handleTypeahead(key);
        }
    }
  };

  private readonly handleListFocus = (): void => {
    if (this.activeValue !== null) {
      return;
    }
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const selected = items.find((item) => this.selectedSet.has(item.value));
    this.setActive((selected ?? items[0]).value);
  };

  private handleOptionClick(item: ListboxItem): void {
    if (this.isDisabled || item.disabled) {
      return;
    }
    this.setActive(item.value);
    this.selectActive();
  }

  private handleOptionPointerEnter(item: ListboxItem): void {
    if (this.isDisabled || item.disabled) {
      return;
    }
    this.setActive(item.value);
  }

  private moveActive(delta: number): void {
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const currentIndex = this.activeValue ? items.findIndex((item) => item.value === this.activeValue) : -1;
    let nextIndex = currentIndex + delta;
    if (nextIndex < 0) {
      nextIndex = items.length - 1;
    } else if (nextIndex >= items.length) {
      nextIndex = 0;
    }
    const item = items[nextIndex];
    this.setActive(item.value);
    if (!this.multiple && this.selectionFollowsFocus) {
      this.commitValue(item.value);
    }
  }

  private setActiveEdge(edge: 'first' | 'last'): void {
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const item = edge === 'first' ? items[0] : items[items.length - 1];
    this.setActive(item.value);
  }

  private pageActive(direction: 1 | -1): void {
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const pageSize = this.maxVisible === 'all' ? items.length : Number(this.maxVisible);
    const currentIndex = this.activeValue
      ? items.findIndex((item) => item.value === this.activeValue)
      : direction === 1
        ? -1
        : items.length;
    let nextIndex = currentIndex + direction * pageSize;
    nextIndex = Math.max(0, Math.min(items.length - 1, nextIndex));
    this.setActive(items[nextIndex].value);
  }

  private extendSelection(delta: number): void {
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const currentIndex = this.activeValue ? items.findIndex((item) => item.value === this.activeValue) : -1;
    const nextIndex = Math.max(0, Math.min(items.length - 1, currentIndex + delta));
    const item = items[nextIndex];
    this.setActive(item.value);
    const set = this.selectedSet;
    set.add(item.value);
    this.commitValue(this.orderValues(set));
  }

  private toggleSelectAll(): void {
    const items = this.enabledItems;
    if (items.length === 0) {
      return;
    }
    const allSelected = items.every((item) => this.selectedSet.has(item.value));
    this.commitValue(allSelected ? [] : items.map((item) => item.value));
  }

  private handleTypeahead(char: string): void {
    clearTimeout(this.typeaheadTimer);
    this.typeaheadQuery += char.toLowerCase();
    const query = this.typeaheadQuery;
    const match = this.enabledItems.find((item) => item.label.toLowerCase().startsWith(query));
    if (match) {
      this.setActive(match.value);
    }
    this.typeaheadTimer = setTimeout(() => {
      this.typeaheadQuery = '';
    }, TYPEAHEAD_RESET_MS);
  }

  private selectActive(): void {
    if (this.activeValue === null) {
      return;
    }
    const item = this.flatItems.find((candidate) => candidate.value === this.activeValue);
    if (!item || item.disabled) {
      return;
    }
    if (this.multiple) {
      const set = this.selectedSet;
      if (set.has(item.value)) {
        set.delete(item.value);
      } else {
        set.add(item.value);
      }
      this.commitValue(this.orderValues(set));
    } else {
      this.commitValue(item.value);
    }
  }

  private orderValues(set: Set<string>): string[] {
    return this.flatItems.filter((item) => set.has(item.value)).map((item) => item.value);
  }

  private setActive(value: string | null): void {
    if (this.activeValue === value) {
      return;
    }
    this.activeValue = value;
    this.dispatchEvent(
      new CustomEvent<ListboxActiveChangeDetail>('active-change', {
        detail: { value },
        bubbles: true,
        composed: true,
      }),
    );
    void this.scrollActiveIntoView();
  }

  private async scrollActiveIntoView(): Promise<void> {
    await this.updateComplete;
    if (this.activeValue === null) {
      return;
    }
    this.renderRoot
      .querySelector(`[data-value="${CSS.escape(this.activeValue)}"]`)
      ?.scrollIntoView({ block: 'nearest' });
  }

  private commitValue(next: ListboxValue): void {
    if (this.value !== undefined) {
      this.value = next;
    } else {
      this.internalValue = next;
    }
    this.dispatchEvent(
      new CustomEvent<ListboxChangeDetail>('change', {
        detail: { value: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  /**
   * Mirrors value and validity into ElementInternals. `currentValue` can be
   * an array (`multiple`), which is outside `DsFormField`'s
   * `string | boolean | null` contract — see the generator's gap notes;
   * `<ds-form>` does not currently discover `<ds-listbox>` by tag.
   */
  private syncInternals(): void {
    const value = this.currentValue;
    if (this.multiple) {
      if (this.isDisabled || value === null) {
        this.internals.setFormValue(null);
      } else {
        const formData = new FormData();
        for (const entry of value as string[]) {
          formData.append(this.name, entry);
        }
        this.internals.setFormValue(formData);
      }
    } else {
      this.internals.setFormValue(this.isDisabled || value === null ? null : (value as string));
    }

    if (this.required && value === null) {
      this.internals.setValidity({ valueMissing: true }, COPY_REQUIRED(this.label), this.listEl);
    } else {
      this.internals.setValidity({});
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ListboxOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.label && !this.labelledBy) {
      console.warn('<ds-listbox> requires a `label` or `labelledBy`.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-listbox': DsListbox;
  }
}
