// packages/rn/src/SegmentedControl.tsx
import * as React from 'react';
import { Animated, I18nManager, Platform, Pressable, Text as RNText, View } from 'react-native';
import type { LayoutChangeEvent, PressableStateCallbackType, TextStyle, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import type { IconName } from './Icon';
import { toEasing, toFontWeight, toLineHeight, useReducedMotion, useTheme } from './theme';
import type { Tokens } from './theme';

export type SegmentedControlSize = 'sm' | 'md';

/** One option. Labels are one word; with `iconOnly` the label becomes the accessible name. */
export type SegmentedControlOption = {
  value: string;
  label: string;
  icon?: IconName | undefined;
  disabled?: boolean | undefined;
};

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type SegmentedControlOverridableBinding =
  | 'groupPadding'
  | 'groupRadius'
  | 'segmentShadow'
  | 'segmentRadius'
  | 'segmentPaddingInline'
  | 'segmentPaddingBlock'
  | 'segmentGap'
  | 'segmentSpacing'
  | 'selectedWeight'
  | 'paddingBlockSm'
  | 'fontFamily'
  | 'fontSize'
  | 'fontWeight'
  | 'lineHeight'
  | 'transition'
  | 'disabledOpacity';

export interface SegmentedControlProps {
  /** Accessible name of the control ("View mode"). Not shown; put a visible Text label beside it when the meaning is not obvious from context. */
  label: string;
  /**
   * Two to five options (guidance, not enforced: any count renders, with no warning). Labels
   * are one word; with `iconOnly` the label becomes the accessible name. The icon is an Icon
   * whose `size` is the control's `size`.
   */
  options: SegmentedControlOption[];
  /** Controlled selected value. Omit for uncontrolled. */
  value?: string | undefined;
  /**
   * Initially selected value. Defaults to the first enabled option — a segmented control
   * always has a selection. A `value` or `defaultValue` is taken as given, never corrected:
   * one naming a disabled option keeps that segment checked with the pill under it; one
   * matching no option checks nothing and draws no pill.
   */
  defaultValue?: string | undefined;
  /**
   * Show icons only (every option must have one); labels become accessibility labels. An
   * option without `icon` warns in development (once) and shows its label as text instead.
   */
  iconOnly?: boolean | undefined;
  /** Toolbar (`sm`) or standard (`md`) height. */
  size?: SegmentedControlSize | undefined;
  /** Stretch to the container width with equal segments. */
  fill?: boolean | undefined;
  /** Fired when the selection changes, with the new value. The change takes effect immediately. */
  onChange?: ((value: string) => void) | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<SegmentedControlOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root `View` (the radiogroup). */
  ref?: React.Ref<ViewInstance> | undefined;
}

const FONT_SIZE = {
  sm: 'fontSizeSm',
  md: 'fontSizeMd',
} as const satisfies Record<SegmentedControlSize, keyof Tokens>;

type SegmentLayout = { x: number; y: number; width: number; height: number };

const isWeb = Platform.OS === 'web';

/** The DOM element react-native-web renders for a `Pressable`; this package has no DOM lib. */
type WebElement = { setAttribute(name: string, value: string): void; removeAttribute(name: string): void };

/**
 * SegmentedControl — switches a mode: list or grid, day or week, metric or imperial.
 * Exactly one segment is always selected and choosing one takes effect at once; there
 * is nothing to submit, which is what separates it from a RadioGroup in a form.
 *
 * When to use: two to five short, parallel options that change what a region shows or
 * how a tool behaves, switched often with the effect seen immediately. `iconOnly` in
 * toolbars where the icons are unambiguous. Not for a value submitted later
 * (RadioGroup), views of content (Tabs), more than five options (Select), or on/off
 * (Switch).
 *
 * Renders a `View` row with `accessibilityRole="radiogroup"` and `accessibilityLabel`,
 * on `groupBackground` with `groupPadding`, holding one `Pressable` per option with
 * `accessibilityRole="radio"` and `accessibilityState={{ checked, disabled }}`; each
 * segment is its own accessibility stop on native. The pill is an `Animated.View`
 * (hidden from assistive technology) positioned from each segment's measured layout
 * and slid over `transition` with `motion.easing.standard`, snapping under reduced
 * motion. Selection is also carried by the stronger, heavier label and the checked
 * state, never by the pill alone. Every segment reaches `size.target.comfortable`
 * (touch), so `size` changes the type and padding, not the target.
 *
 * Keyboard: on react-native-web the group handles `onKeyDown` — ArrowRight/ArrowDown
 * and ArrowLeft/ArrowUp move focus AND selection to the next/previous enabled segment,
 * wrapping; Home/End to the first/last enabled one — and only the selected segment is
 * a tab stop (roving). iOS/Android deliver no key events to `View`/`Pressable`, so a
 * hardware keyboard reaches each segment as its own stop and Enter/Space press it.
 * With `iconOnly` the label is the segment's accessibility label; native has no hover
 * or focus Tooltip, so none is shown.
 */
export function SegmentedControl({
  label,
  options,
  value,
  defaultValue,
  iconOnly = false,
  size = 'md',
  fill = false,
  onChange,
  overrides,
  ref,
}: SegmentedControlProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const rtl = I18nManager.isRTL;

  const enabledOptions = options.filter((option) => option.disabled !== true);
  const firstEnabledValue = enabledOptions[0]?.value;
  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = React.useState<string | undefined>(defaultValue ?? firstEnabledValue);
  const currentValue = isControlled ? value : internalValue;

  const hasWarnedIconRef = React.useRef(false);
  React.useEffect(() => {
    if (__DEV__ && iconOnly && !hasWarnedIconRef.current) {
      const missing = options.filter((option) => option.icon === undefined).map((option) => `"${option.value}"`);
      if (missing.length > 0) {
        hasWarnedIconRef.current = true;
        // One message per instance listing every option without an icon.
        console.warn(
          `SegmentedControl: iconOnly is set but ${missing.join(', ')} ${missing.length === 1 ? 'has' : 'have'} no icon; the label is shown as text instead.`,
        );
      }
    }
  }, [iconOnly, options]);

  const groupPadding = overrides?.groupPadding ? (resolveToken(t, overrides.groupPadding) as number) : t.space1;
  const groupRadius = overrides?.groupRadius ? (resolveToken(t, overrides.groupRadius) as number) : t.radiusMd;
  const segmentShadow = overrides?.segmentShadow ? (resolveToken(t, overrides.segmentShadow) as typeof t.shadowRaised) : t.shadowRaised;
  const segmentRadius = overrides?.segmentRadius ? (resolveToken(t, overrides.segmentRadius) as number) : t.radiusSm;
  const segmentPaddingInline = overrides?.segmentPaddingInline ? (resolveToken(t, overrides.segmentPaddingInline) as number) : t.spaceMd;
  const paddingBlockMd = overrides?.segmentPaddingBlock ? (resolveToken(t, overrides.segmentPaddingBlock) as number) : t.space1;
  const paddingBlockSm = overrides?.paddingBlockSm ? (resolveToken(t, overrides.paddingBlockSm) as number) : t.space1;
  const segmentGap = overrides?.segmentGap ? (resolveToken(t, overrides.segmentGap) as number) : t.layoutGapTight;
  const segmentSpacing = overrides?.segmentSpacing ? (resolveToken(t, overrides.segmentSpacing) as number) : t.space0;
  const selectedWeight = overrides?.selectedWeight ? (resolveToken(t, overrides.selectedWeight) as number) : t.fontWeightSemibold;
  const fontFamily = overrides?.fontFamily ? (resolveToken(t, overrides.fontFamily) as string) : t.fontFamilyBody;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t[FONT_SIZE[size]];
  const fontWeight = overrides?.fontWeight ? (resolveToken(t, overrides.fontWeight) as number) : t.fontWeightMedium;
  const lineHeightMultiplier = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;
  const transitionDuration = overrides?.transition ? (resolveToken(t, overrides.transition) as number) : t.motionDurationFast;
  const disabledOpacity = overrides?.disabledOpacity ? (resolveToken(t, overrides.disabledOpacity) as number) : t.opacityDisabled;

  const segmentLayoutsRef = React.useRef(new Map<string, SegmentLayout>());
  const segmentRefs = React.useRef(new Map<string, ViewInstance>());
  const focusedValueRef = React.useRef<string | undefined>(undefined);
  const hasMeasuredRef = React.useRef(false);
  const pillX = React.useRef(new Animated.Value(0)).current;
  const pillWidth = React.useRef(new Animated.Value(0)).current;
  const pillY = React.useRef(new Animated.Value(0)).current;
  const pillHeight = React.useRef(new Animated.Value(0)).current;

  const updatePill = React.useCallback(
    (optionValue: string): void => {
      const layout = segmentLayoutsRef.current.get(optionValue);
      if (!layout) {
        return;
      }
      // Segments share one row, so only the inline position animates.
      pillY.setValue(layout.y);
      pillHeight.setValue(layout.height);
      if (reducedMotion || !hasMeasuredRef.current) {
        pillX.setValue(layout.x);
        pillWidth.setValue(layout.width);
        hasMeasuredRef.current = true;
        return;
      }
      const easing = toEasing(t.motionEasingStandard);
      Animated.parallel([
        Animated.timing(pillX, { toValue: layout.x, duration: transitionDuration, easing, useNativeDriver: false }),
        Animated.timing(pillWidth, { toValue: layout.width, duration: transitionDuration, easing, useNativeDriver: false }),
      ]).start();
    },
    [reducedMotion, transitionDuration, t.motionEasingStandard, pillX, pillWidth, pillY, pillHeight],
  );

  // A value matching no option checks nothing and draws no pill (never corrected).
  const hasSelectedOption = options.some((option) => option.value === currentValue);

  React.useEffect(() => {
    if (currentValue !== undefined && hasSelectedOption) {
      updatePill(currentValue);
    } else {
      // The pill unmounts; the next selection places it without sliding in from a stale spot.
      hasMeasuredRef.current = false;
    }
  }, [currentValue, hasSelectedOption, updatePill]);

  const handleSegmentLayout = (optionValue: string, event: LayoutChangeEvent): void => {
    const { x, y, width, height } = event.nativeEvent.layout;
    segmentLayoutsRef.current.set(optionValue, { x, y, width, height });
    if (optionValue === currentValue) {
      updatePill(optionValue);
    }
  };

  const select = (optionValue: string): void => {
    const option = options.find((candidate) => candidate.value === optionValue);
    if (!option || option.disabled === true || optionValue === currentValue) {
      return;
    }
    if (!isControlled) {
      setInternalValue(optionValue);
    }
    onChange?.(optionValue);
  };

  // The roving tab stop on web: the selected segment when it is enabled, else the first enabled one.
  const tabStopValue = enabledOptions.some((option) => option.value === currentValue) ? currentValue : firstEnabledValue;

  // react-native-web only: View has no key events on iOS/Android.
  const handleKeyDown = (event: { key?: string; nativeEvent?: { key?: string }; preventDefault?: () => void }): void => {
    const key = event.key ?? event.nativeEvent?.key;
    if (enabledOptions.length === 0 || key === undefined) {
      return;
    }
    // Arrows move from the focused segment, else from the tab stop (the first enabled segment
    // when the value names a disabled option or none).
    const fromValue = focusedValueRef.current ?? tabStopValue;
    const fromIndex = enabledOptions.findIndex((option) => option.value === fromValue);
    const nextKeys = rtl ? ['ArrowLeft', 'ArrowDown'] : ['ArrowRight', 'ArrowDown'];
    const prevKeys = rtl ? ['ArrowRight', 'ArrowUp'] : ['ArrowLeft', 'ArrowUp'];
    let targetIndex: number;
    if (nextKeys.includes(key)) {
      targetIndex = fromIndex < 0 ? 0 : (fromIndex + 1) % enabledOptions.length;
    } else if (prevKeys.includes(key)) {
      targetIndex = fromIndex <= 0 ? enabledOptions.length - 1 : fromIndex - 1;
    } else if (key === 'Home') {
      targetIndex = 0;
    } else if (key === 'End') {
      targetIndex = enabledOptions.length - 1;
    } else {
      return;
    }
    event.preventDefault?.();
    const target = enabledOptions[targetIndex]!;
    segmentRefs.current.get(target.value)?.focus();
    select(target.value);
  };

  const keyProps: Record<string, unknown> = isWeb ? { onKeyDown: handleKeyDown } : {};

  const styleTokens: SegmentStyleTokens = {
    paddingInline: segmentPaddingInline,
    paddingBlock: size === 'sm' ? paddingBlockSm : paddingBlockMd,
    gap: segmentGap,
    // minTarget: React Native is touch, so every segment reaches size.target.comfortable.
    minTarget: t.sizeTargetComfortable,
    disabledOpacity,
    focusRingColor: t.colorBorderFocus,
    focusRingWidth: t.borderWidthFocus,
    // segmentRadius: the pill's corners, which the focus ring shares.
    radius: segmentRadius,
    fontFamily,
    fontSize,
    fontWeight,
    selectedWeight,
    lineHeightMultiplier,
    color: t.colorForegroundMuted,
    selectedColor: t.colorForegroundStrong,
    // The glyph is an Icon at the control's own size, as on every other platform.
    iconSize: size,
  };

  const groupStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'stretch',
    alignSelf: fill ? 'stretch' : 'flex-start',
    position: 'relative',
    gap: segmentSpacing,
    padding: groupPadding,
    borderRadius: groupRadius,
    backgroundColor: t.colorBackgroundStrong,
  };

  const pillStyle: Animated.WithAnimatedValue<ViewStyle> = {
    position: 'absolute',
    left: 0,
    top: pillY,
    width: pillWidth,
    height: pillHeight,
    borderRadius: segmentRadius,
    backgroundColor: t.colorBackground,
    transform: [{ translateX: pillX }],
    ...segmentShadow,
  };

  return (
    <View
      ref={ref}
      {...keyProps}
      testID="SegmentedControl"
      accessibilityRole="radiogroup"
      accessibilityLabel={label}
      style={groupStyle}
    >
      {hasSelectedOption ? (
        <Animated.View
          testID="SegmentedControl.indicator"
          style={pillStyle}
          pointerEvents="none"
          accessibilityElementsHidden
          importantForAccessibility="no-hide-descendants"
        />
      ) : null}
      {options.map((option) => (
        <Segment
          key={option.value}
          option={option}
          selected={option.value === currentValue}
          tabStop={option.value === tabStopValue}
          iconOnly={iconOnly}
          fill={fill}
          styleTokens={styleTokens}
          onSelect={select}
          onMeasured={handleSegmentLayout}
          onFocusChange={(optionValue, focused) => {
            focusedValueRef.current = focused
              ? optionValue
              : focusedValueRef.current === optionValue
                ? undefined
                : focusedValueRef.current;
          }}
          registerRef={(optionValue, instance) => {
            if (instance) {
              segmentRefs.current.set(optionValue, instance);
            } else {
              segmentRefs.current.delete(optionValue);
            }
          }}
        />
      ))}
    </View>
  );
}

interface SegmentStyleTokens {
  paddingInline: number;
  paddingBlock: number;
  gap: number;
  minTarget: number;
  disabledOpacity: number;
  focusRingColor: string;
  focusRingWidth: number;
  radius: number;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  selectedWeight: number;
  lineHeightMultiplier: number;
  color: string;
  selectedColor: string;
  iconSize: SegmentedControlSize;
}

interface SegmentProps {
  option: SegmentedControlOption;
  selected: boolean;
  tabStop: boolean;
  iconOnly: boolean;
  fill: boolean;
  styleTokens: SegmentStyleTokens;
  onSelect: (value: string) => void;
  onMeasured: (value: string, event: LayoutChangeEvent) => void;
  onFocusChange: (value: string, focused: boolean) => void;
  registerRef: (value: string, instance: ViewInstance | null) => void;
}

/** One segment. Its own component so focus state does not re-render the whole group. */
function Segment({
  option,
  selected,
  tabStop,
  iconOnly,
  fill,
  styleTokens: s,
  onSelect,
  onMeasured,
  onFocusChange,
  registerRef,
}: SegmentProps): React.JSX.Element {
  const [focused, setFocused] = React.useState(false);
  const disabled = option.disabled === true;
  const foreground = selected ? s.selectedColor : s.color;
  const nodeRef = React.useRef<ViewInstance | null>(null);

  // react-native-web 0.21 ignores `accessibilityState` and `focusable`, so neither the disabled
  // state nor the roving tab stop would reach the DOM: every segment renders `tabindex="0"` and no
  // segment is announced as disabled. Both are set on the node itself here, as Tabs, Button and
  // Checkbox do — passing Pressable's own `disabled` prop instead would drop the segment out of the
  // accessibility tree, which the press guard exists to avoid. The attribute is also what keeps the
  // dimmed disabled segment out of axe's contrast check (WCAG 1.4.3 exempts inactive components,
  // and `opacity.disabled` over `color.foreground.muted` cannot reach 4.5:1).
  React.useEffect(() => {
    if (!isWeb) {
      return;
    }
    const node = nodeRef.current as unknown as WebElement | null;
    if (node === null) {
      return;
    }
    if (disabled) {
      node.setAttribute('aria-disabled', 'true');
    } else {
      node.removeAttribute('aria-disabled');
    }
    // The group is one tab stop: the selected segment, or the first enabled one. A disabled
    // segment is never a stop (it has nothing to reach), but stays in the tree and readable.
    node.setAttribute('tabindex', tabStop && !disabled ? '0' : '-1');
  }, [disabled, tabStop]);

  const rowStyle = (_state: PressableStateCallbackType): ViewStyle => ({
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: fill ? 1 : 0,
    flexShrink: fill ? 1 : 0,
    flexBasis: fill ? 0 : 'auto',
    gap: s.gap,
    minWidth: s.minTarget,
    minHeight: s.minTarget,
    paddingHorizontal: s.paddingInline,
    paddingVertical: s.paddingBlock,
    borderWidth: s.focusRingWidth,
    borderColor: focused ? s.focusRingColor : 'transparent',
    borderRadius: s.radius,
    opacity: disabled ? s.disabledOpacity : 1,
  });

  // With `iconOnly`, a segment whose option has no icon shows its label so it never renders empty.
  const showIcon = option.icon !== undefined;
  const showLabel = !iconOnly || !showIcon;

  const labelStyle: TextStyle = {
    fontFamily: s.fontFamily,
    fontSize: s.fontSize,
    fontWeight: toFontWeight(selected ? s.selectedWeight : s.fontWeight),
    lineHeight: toLineHeight(s.fontSize, s.lineHeightMultiplier),
    color: foreground,
  };

  return (
    <Pressable
      ref={(instance: ViewInstance | null) => {
        nodeRef.current = instance;
        registerRef(option.value, instance);
      }}
      testID="SegmentedControl.segment"
      accessibilityRole="radio"
      // An `iconOnly` segment carries its label as the accessible name; a segment showing its
      // label as text is named by that text, and gets no label of its own. No
      // `accessibilityHint` either: it would only repeat the name, and a press already selects.
      accessibilityLabel={showLabel ? undefined : option.label}
      accessibilityState={{ checked: selected, disabled }}
      // `role="radio"` requires `aria-checked`, and react-native-web 0.21 ignores
      // `accessibilityState`, so the checked state reaches the DOM through this mirror (native
      // merges both); `aria-disabled` and `tabindex` are set in the effect above.
      aria-checked={selected}
      // Never the native `disabled` prop: it would drop the segment from the focus order.
      onPress={() => {
        if (!disabled) {
          onSelect(option.value);
        }
      }}
      onFocus={() => {
        setFocused(true);
        onFocusChange(option.value, true);
      }}
      onBlur={() => {
        setFocused(false);
        onFocusChange(option.value, false);
      }}
      onLayout={(event) => onMeasured(option.value, event)}
      style={rowStyle}
    >
      {showIcon ? (
        <View testID="SegmentedControl.segmentIcon" accessibilityElementsHidden importantForAccessibility="no">
          <Icon name={option.icon!} size={s.iconSize} color={foreground} />
        </View>
      ) : null}
      {!showLabel ? null : (
        <RNText numberOfLines={1} style={labelStyle} testID="SegmentedControl.segmentLabel">
          {option.label}
        </RNText>
      )}
    </Pressable>
  );
}

// packages/lit/src/SegmentedControl.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';
import type { IconName, IconOverridableBinding } from './Icon.js';
import './Tooltip.js';

export type SegmentedControlSize = 'sm' | 'md';

/** Shape of each entry in `options`. */
export interface SegmentedControlOption {
  value: string;
  label: string;
  icon?: IconName | undefined;
  disabled?: boolean | undefined;
}

/** Detail carried by the `change` CustomEvent. */
export interface SegmentedControlChangeDetail {
  value: string;
}

/** Overridable style hooks; see the `overrides` property. `groupBackground`, `segmentColor`, `segmentSelectedColor`, `segmentSelectedBackground`, `minTarget`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type SegmentedControlOverridableBinding =
  | 'groupPadding'
  | 'groupRadius'
  | 'segmentShadow'
  | 'segmentRadius'
  | 'segmentPaddingInline'
  | 'segmentPaddingBlock'
  | 'segmentGap'
  | 'segmentSpacing'
  | 'selectedWeight'
  | 'paddingBlockSm'
  | 'fontFamily'
  | 'fontSize'
  | 'fontWeight'
  | 'lineHeight'
  | 'transition'
  | 'disabledOpacity';

const HOOKS: Record<SegmentedControlOverridableBinding, string> = {
  groupPadding: '--ds-segmented-control-group-padding',
  groupRadius: '--ds-segmented-control-group-radius',
  segmentShadow: '--ds-segmented-control-segment-shadow',
  segmentRadius: '--ds-segmented-control-segment-radius',
  segmentPaddingInline: '--ds-segmented-control-segment-padding-inline',
  segmentPaddingBlock: '--ds-segmented-control-segment-padding-block',
  segmentGap: '--ds-segmented-control-segment-gap',
  segmentSpacing: '--ds-segmented-control-segment-spacing',
  selectedWeight: '--ds-segmented-control-selected-weight',
  paddingBlockSm: '--ds-segmented-control-padding-block-sm',
  fontFamily: '--ds-segmented-control-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-segmented-control-font-size',
  fontWeight: '--ds-segmented-control-font-weight',
  lineHeight: '--ds-segmented-control-line-height',
  transition: '--ds-segmented-control-transition',
  disabledOpacity: '--ds-segmented-control-disabled-opacity',
};

/** The icon takes its segment's colour (segmentColor / segmentSelectedColor) through its own `overrides.color`. */
const ICON_OVERRIDES: Partial<Record<IconOverridableBinding, TokenRef>> = { color: 'color.foreground.muted' };
const SELECTED_ICON_OVERRIDES: Partial<Record<IconOverridableBinding, TokenRef>> = { color: 'color.foreground.strong' };

/** The selected segment's box inside the group, in physical pixels, as the pill is drawn. */
interface IndicatorRect {
  left: number;
  top: number;
  width: number;
  height: number;
}

/**
 * `<ds-segmented-control>` — SegmentedControl (category: input, APG pattern: radio).
 *
 * `<ds-segmented-control label="View mode" .options=${[...]} value="grid">`
 * renders a `role="radiogroup"` of native `<button role="radio">` in its
 * shadow root, one per entry of `options`. The group is one roving-tabindex
 * stop: arrow keys move real focus *and* selection together (radio
 * semantics), wrapping and skipping disabled options; Home/End do the same
 * to the first/last enabled option. The pill (anatomy: indicator) is an
 * absolutely positioned element measured from the selected segment's box and
 * slid with `transition`, instant under reduced motion. `iconOnly` wraps each
 * segment in a `<ds-tooltip no-describes>` so the option's label is both the
 * accessible name and the visible hover/focus label.
 *
 * Selecting a segment fires a composed `change` CustomEvent with `{ value }`.
 * With `value` set the element is controlled: it reports the choice and shows
 * it only once `value` changes — an arrow still moves focus and fires
 * `change`, while the checked state, the pill and the tab stop stay where
 * `value` says. Not form-associated: a segmented control has nothing to
 * submit, it only switches a mode.
 *
 * ## When to use
 *
 * Use it for two to five short, parallel options that change what a region
 * shows or how a tool behaves, where the user switches often and sees the
 * effect immediately. Use `iconOnly` in toolbars where the icons are
 * unambiguous and pair it with a visible Text label when the group's purpose
 * is not obvious.
 *
 * ## When not to use
 *
 * Not for a value that is submitted later (RadioGroup), not for more than
 * five options or long labels (use Tabs or Select), and never with no
 * selection — a segmented control always has one.
 *
 * @fires change - Fired when the user changes the selection, with `{ value }` in `detail`.
 */
@customElement('ds-segmented-control')
export class DsSegmentedControl extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: inline-flex;
      max-inline-size: 100%;
      /* Locked: not in the overrides type, but still themeable from page CSS. */
      --ds-segmented-control-group-background: var(--color-background-strong);
      --ds-segmented-control-segment-color: var(--color-foreground-muted);
      --ds-segmented-control-segment-selected-color: var(--color-foreground-strong);
      --ds-segmented-control-segment-selected-background: var(--color-background);
      --ds-segmented-control-min-target: var(--size-target-min);
      --ds-segmented-control-focus-ring: var(--color-border-focus);
      --ds-segmented-control-focus-ring-width: var(--border-width-focus);
      --ds-segmented-control-group-padding: var(--space-1);
      --ds-segmented-control-group-radius: var(--radius-md);
      --ds-segmented-control-segment-shadow: var(--shadow-raised);
      --ds-segmented-control-segment-radius: var(--radius-sm);
      --ds-segmented-control-segment-padding-inline: var(--space-md);
      --ds-segmented-control-segment-padding-block: var(--space-1);
      --ds-segmented-control-segment-gap: var(--layout-gap-tight);
      --ds-segmented-control-segment-spacing: var(--space-0);
      --ds-segmented-control-selected-weight: var(--font-weight-semibold);
      --ds-segmented-control-padding-block-sm: var(--space-1);
      --ds-segmented-control-font-family: var(--font-family-body);
      --ds-segmented-control-font-size: var(--font-size-md);
      --ds-segmented-control-font-weight: var(--font-weight-medium);
      --ds-segmented-control-line-height: var(--font-line-height-normal);
      --ds-segmented-control-transition: var(--motion-duration-fast);
      --ds-segmented-control-disabled-opacity: var(--opacity-disabled);
    }

    :host([hidden]) {
      display: none;
    }

    :host([fill]) {
      display: flex;
      inline-size: 100%;
    }

    /* fontSize: font.size.{size} */
    :host([size='sm']) {
      --ds-segmented-control-font-size: var(--font-size-sm);
    }
    :host([size='md']) {
      --ds-segmented-control-font-size: var(--font-size-md);
    }

    /* groupBackground: color.background.strong, locked. segmentSpacing is the group's gap, never a segment margin. */
    [data-part='group'] {
      position: relative;
      box-sizing: border-box;
      display: flex;
      inline-size: 100%;
      gap: var(--ds-segmented-control-segment-spacing);
      padding: var(--ds-segmented-control-group-padding);
      border-radius: var(--ds-segmented-control-group-radius);
      background: var(--ds-segmented-control-group-background);
    }

    [data-part='segment'] {
      position: relative;
      z-index: 1;
      box-sizing: border-box;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: var(--ds-segmented-control-segment-gap);
      /* minTarget: size.target.min, locked */
      min-inline-size: var(--ds-segmented-control-min-target);
      min-block-size: var(--ds-segmented-control-min-target);
      margin: 0;
      padding-inline: var(--ds-segmented-control-segment-padding-inline);
      padding-block: var(--ds-segmented-control-segment-padding-block);
      border: 0;
      border-radius: var(--ds-segmented-control-segment-radius);
      background: transparent;
      font-family: var(--ds-segmented-control-font-family);
      font-size: var(--ds-segmented-control-font-size);
      font-weight: var(--ds-segmented-control-font-weight);
      line-height: var(--ds-segmented-control-line-height);
      /* segmentColor: color.foreground.muted, locked */
      color: var(--ds-segmented-control-segment-color);
      white-space: nowrap;
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
    }

    /* ds-tooltip is display: contents, so the button stays the group's flex item */
    :host([fill]) [data-part='segment'] {
      flex: 1 1 0;
    }

    /* paddingBlockSm: vertical padding at size sm; md keeps segmentPaddingBlock. */
    :host([size='sm']) [data-part='segment'] {
      padding-block: var(--ds-segmented-control-padding-block-sm);
    }

    /* segmentSelectedColor: color.foreground.strong, locked. Selection is the text pair plus the
       checked state plus the pill — never color alone (1.4.1). */
    [data-part='segment'][aria-checked='true'] {
      color: var(--ds-segmented-control-segment-selected-color);
      font-weight: var(--ds-segmented-control-selected-weight);
    }

    /* focusRing / focusRingWidth: color.border.focus / border.width.focus, locked. Never removed. */
    [data-part='segment']:focus-visible {
      outline: var(--ds-segmented-control-focus-ring-width) solid var(--ds-segmented-control-focus-ring);
      outline-offset: calc(-1 * var(--ds-segmented-control-focus-ring-width));
    }

    [data-part='segment'][aria-disabled='true'] {
      opacity: var(--ds-segmented-control-disabled-opacity);
      cursor: default;
    }

    [data-part='segmentIcon'] {
      flex: none;
      line-height: 0;
    }

    [data-part='segmentLabel'] {
      min-inline-size: 0;
    }

    /* The raised pill under the selected segment: segmentSelectedBackground (color.background,
       locked) plus segmentShadow. Placed in JS from the selected segment's measured offset, and
       unmounted entirely when nothing is selected — see updateIndicator(). */
    [data-part='indicator'] {
      position: absolute;
      z-index: 0;
      box-sizing: border-box;
      background: var(--ds-segmented-control-segment-selected-background);
      border-radius: var(--ds-segmented-control-segment-radius);
      box-shadow: var(--ds-segmented-control-segment-shadow);
      pointer-events: none;
      transition-property: left, top, width, height;
      transition-duration: var(--ds-segmented-control-transition);
      transition-timing-function: var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='indicator'] {
        transition: none;
      }
    }
  `;

  /** Accessible name of the control ("View mode"). Not shown; put a visible Text label beside it when the meaning is not obvious from context. */
  @property() accessor label: string = '';

  /**
   * Two to five options (guidance, not enforced: any count renders, with no warning) in display
   * order. Labels are one word; with `iconOnly` the label becomes the accessible name. The icon is
   * an Icon whose `size` is the control's `size`. A property, not an attribute.
   */
  @property({ attribute: false }) accessor options: SegmentedControlOption[] = [];

  /** Controlled selected value. Omit for uncontrolled. */
  @property({ type: String, reflect: true }) accessor value: string | undefined;

  /**
   * Initially selected value. Defaults to the first enabled option — a segmented control always has
   * a selection. A `value` or `defaultValue` is taken as given, never corrected: one naming a
   * disabled option keeps that segment checked with the pill under it (arrows still skip it); one
   * matching no option checks nothing and draws no pill. In both cases the tab stop is the first
   * enabled segment. Reads the `default-value` attribute; not reflected.
   */
  @property({ attribute: 'default-value' }) accessor defaultValue: string | undefined;

  /**
   * Show icons only (every option must have one); labels become accessible names and Tooltips. An
   * option without `icon` warns in development once per instance and shows its label as text
   * instead, so it never renders empty; that segment gets no Tooltip and no `aria-label`.
   */
  @property({ type: Boolean, reflect: true, attribute: 'icon-only' }) accessor iconOnly = false;

  /** Toolbar (`sm`) or standard (`md`) height. */
  @property({ type: String, reflect: true }) accessor size: SegmentedControlSize = 'md';

  /** Stretch to the container width with equal segments. */
  @property({ type: Boolean, reflect: true }) accessor fill = false;

  /** Per-instance style overrides: `{ segmentRadius: 'radius.md' }`. Locked bindings are not in the type. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<SegmentedControlOverridableBinding, TokenRef | undefined>>
    | undefined;

  /** Uncontrolled selection, seeded from `defaultValue` (or the first enabled option). */
  @state() private accessor internalValue: string | undefined;

  @query('[data-part="group"]') private accessor groupEl!: HTMLElement | null;
  @query('[data-part="indicator"]') private accessor indicatorEl!: HTMLElement | null;

  private resizeObserver: ResizeObserver | undefined;
  private placedRect: IndicatorRect | undefined;
  private warnedLabel = false;
  private warnedIcon = false;

  /** The currently selected value, controlled or not. */
  get currentValue(): string | null {
    return this.value ?? this.internalValue ?? null;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'SegmentedControl');
    if (this.hasUpdated && this.groupEl) {
      this.observeGroup(this.groupEl);
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.resizeObserver?.disconnect();
    this.resizeObserver = undefined;
  }

  protected override firstUpdated(): void {
    if (this.groupEl) {
      this.observeGroup(this.groupEl);
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (this.internalValue === undefined && this.options.length > 0) {
      this.internalValue = this.defaultValue ?? this.firstEnabled()?.value;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.updateIndicator();
    this.warnInDev();
  }

  protected override render(): TemplateResult {
    const selected = this.currentValue;
    const tabStop = this.tabStopValue();
    // A selection matching no option draws no pill: the element is unmounted rather than hidden,
    // so the next selection mounts it in place instead of sliding it in from nowhere.
    const hasPill = selected !== null && this.options.some((option) => option.value === selected);
    return html`
      <div data-part="group" part="group" role="radiogroup" aria-label=${this.label} @keydown=${this.handleKeydown}>
        ${this.options.map((option) =>
          this.renderSegment(option, option.value === selected, option.value === tabStop),
        )}
        ${hasPill ? html`<span data-part="indicator" part="indicator" aria-hidden="true"></span>` : nothing}
      </div>
    `;
  }

  private renderSegment(option: SegmentedControlOption, selected: boolean, tabStop: boolean): TemplateResult {
    // An `iconOnly` option without an icon shows its label as text, so the segment never renders
    // empty — and then carries no Tooltip and no aria-label, since its visible text is its name.
    const iconOnly = this.iconOnly && option.icon !== undefined;
    const button = html`
      <button
        type="button"
        data-part="segment"
        part="segment"
        role="radio"
        data-value=${option.value}
        aria-checked=${selected ? 'true' : 'false'}
        aria-disabled=${ifDefined(option.disabled === true ? 'true' : undefined)}
        aria-label=${ifDefined(iconOnly ? option.label : undefined)}
        tabindex=${tabStop ? 0 : -1}
        @click=${() => this.handleSegmentClick(option)}
      >
        ${option.icon
          ? html`<ds-icon
              data-part="segmentIcon"
              part="segmentIcon"
              name=${option.icon}
              size=${this.size}
              .overrides=${selected ? SELECTED_ICON_OVERRIDES : ICON_OVERRIDES}
            ></ds-icon>`
          : nothing}
        ${iconOnly ? nothing : html`<span data-part="segmentLabel" part="segmentLabel">${option.label}</span>`}
      </button>
    `;
    return iconOnly
      ? html`<ds-tooltip data-part="tooltip" part="tooltip" content=${option.label} no-describes>${button}</ds-tooltip>`
      : button;
  }

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    if (event.defaultPrevented || event.altKey || event.ctrlKey || event.metaKey) {
      return;
    }
    const enabled = this.enabledOptions();
    if (enabled.length === 0) {
      return;
    }

    // In right-to-left writing ArrowLeft is "next" and ArrowRight "previous"; the vertical arrows
    // are unchanged. The direction is the host's computed one, read at keydown.
    const rtl = getComputedStyle(this).direction === 'rtl';
    let step: 1 | -1 | 'first' | 'last';
    switch (event.key) {
      case 'ArrowDown':
        step = 1;
        break;
      case 'ArrowUp':
        step = -1;
        break;
      case 'ArrowRight':
        step = rtl ? -1 : 1;
        break;
      case 'ArrowLeft':
        step = rtl ? 1 : -1;
        break;
      case 'Home':
        step = 'first';
        break;
      case 'End':
        step = 'last';
        break;
      default:
        return;
    }

    // Inside a toolbar the arrows do not wrap, and Home/End belong to the toolbar: leaving the key
    // unhandled lets the toolbar move focus to the neighbouring control.
    const inToolbar = this.insideToolbar();

    let target: SegmentedControlOption | undefined;
    if (step === 'first' || step === 'last') {
      if (inToolbar) return;
      target = step === 'first' ? enabled[0] : enabled[enabled.length - 1];
    } else {
      // Movement starts at the focused segment (a disabled one included), and at the tab stop only
      // when no segment has focus.
      const focused = this.focusedValue();
      const count = this.options.length;
      const origin = this.options.findIndex((option) => option.value === (focused ?? this.tabStopValue()));
      if (origin < 0) {
        target = step === 1 ? enabled[0] : enabled[enabled.length - 1];
      } else {
        let wrapped = false;
        for (let offset = 1; offset <= count; offset++) {
          const raw = origin + step * offset;
          if (raw < 0 || raw >= count) wrapped = true;
          const candidate = this.options[(raw + count * 2) % count];
          if (candidate !== undefined && candidate.disabled !== true) {
            target = candidate;
            break;
          }
        }
        // Only a move that would wrap out of a genuinely focused, enabled end segment is left to
        // the toolbar; focus on no enabled segment still moves inside the control.
        const focusedEnabled = enabled.some((option) => option.value === focused);
        if (wrapped && inToolbar && focusedEnabled) return;
      }
    }

    if (target === undefined) {
      return;
    }
    event.preventDefault();
    this.segmentElement(target.value)?.focus();
    this.select(target.value);
  };

  /**
   * Whether a `role="toolbar"` ancestor contains the group, walking `parentElement` and crossing
   * shadow roots through each root's host. Starts at the group's parent, so the group never matches
   * itself.
   */
  private insideToolbar(): boolean {
    const group = this.groupEl;
    if (!group) return false;
    let node: Element | null = group.parentElement ?? this.hostOf(group);
    while (node) {
      if (node.getAttribute('role') === 'toolbar') return true;
      node = node.parentElement ?? this.hostOf(node);
    }
    return false;
  }

  private hostOf(node: Element): Element | null {
    const root = node.getRootNode();
    return root instanceof ShadowRoot ? root.host : null;
  }

  private handleSegmentClick(option: SegmentedControlOption): void {
    if (option.disabled === true) {
      return;
    }
    this.select(option.value);
  }

  private enabledOptions(): SegmentedControlOption[] {
    return this.options.filter((option) => option.disabled !== true);
  }

  private firstEnabled(): SegmentedControlOption | undefined {
    return this.options.find((option) => option.disabled !== true);
  }

  private segmentElement(value: string): HTMLElement | null {
    return this.renderRoot.querySelector<HTMLElement>(`[data-part="segment"][data-value="${CSS.escape(value)}"]`);
  }

  /** The value of the segment that holds focus right now, or undefined when none does. */
  private focusedValue(): string | undefined {
    const active = this.shadowRoot?.activeElement;
    const segment = active?.closest<HTMLElement>('[data-part="segment"]');
    return segment?.dataset['value'];
  }

  /** One tab stop: the selected segment when it is enabled, otherwise the first enabled one. */
  private tabStopValue(): string | undefined {
    const selected = this.currentValue;
    const option = this.options.find((candidate) => candidate.value === selected);
    return option !== undefined && option.disabled !== true ? option.value : this.firstEnabled()?.value;
  }

  private select(next: string): void {
    // `change` fires only when the target differs from the current value, so moving back onto the
    // checked segment fires nothing.
    if (next === this.currentValue) {
      return;
    }
    if (this.value === undefined) {
      this.internalValue = next;
    }
    this.dispatchEvent(
      new CustomEvent<SegmentedControlChangeDetail>('change', {
        detail: { value: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private observeGroup(group: HTMLElement): void {
    this.resizeObserver?.disconnect();
    this.resizeObserver = new ResizeObserver(() => this.updateIndicator());
    this.resizeObserver.observe(group);
  }

  /**
   * Place the pill over the selected segment. Writes only when the measured box moved, so the
   * ResizeObserver that feeds it cannot drive itself.
   */
  private updateIndicator(): void {
    const indicator = this.indicatorEl;
    const selected = this.currentValue;
    const segment = selected !== null ? this.segmentElement(selected) : null;
    if (!indicator || !segment) {
      this.placedRect = undefined;
      return;
    }
    // offsetLeft/offsetTop are physical and measured against the group, which is the only
    // positioned ancestor, so the pill is placed with physical insets in either direction.
    const next: IndicatorRect = {
      left: segment.offsetLeft,
      top: segment.offsetTop,
      width: segment.offsetWidth,
      height: segment.offsetHeight,
    };
    const prev = this.placedRect;
    if (
      prev !== undefined &&
      prev.left === next.left &&
      prev.top === next.top &&
      prev.width === next.width &&
      prev.height === next.height
    ) {
      return;
    }
    this.placedRect = next;
    indicator.style.left = `${next.left}px`;
    indicator.style.top = `${next.top}px`;
    indicator.style.width = `${next.width}px`;
    indicator.style.height = `${next.height}px`;
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as SegmentedControlOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.label && !this.warnedLabel) {
      this.warnedLabel = true;
      console.warn("<ds-segmented-control> requires a `label`, the group's accessible name.", this);
    }
    // The two-to-five option count is guidance only: any count renders, with no warning.
    if (this.iconOnly && !this.warnedIcon) {
      const missing = this.options.filter((option) => option.icon === undefined);
      if (missing.length > 0) {
        this.warnedIcon = true;
        console.warn(
          `<ds-segmented-control>: \`icon-only\` needs an \`icon\` on every option; ${missing
            .map((option) => `"${option.value}"`)
            .join(', ')} show their label as text instead.`,
          this,
        );
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-segmented-control': DsSegmentedControl;
  }
}
