// packages/rn/src/SidePanel.tsx
import * as React from 'react';
import {
  AccessibilityInfo,
  Animated,
  I18nManager,
  Modal,
  PanResponder,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  View,
  findNodeHandle,
  useWindowDimensions,
} from 'react-native';
import type { LayoutChangeEvent, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Box } from './Box';
import { Button } from './Button';
import { FocusScope } from './FocusScope';
import { Heading } from './Heading';
import { Icon } from './Icon';
import { Stack } from './Stack';
import { toEasing, useReducedMotion, useTheme } from './theme';

export type SidePanelSide = 'start' | 'end';
export type SidePanelWidth = 'narrow' | 'default' | 'wide';
export type SidePanelPersistent = 'never' | 'content' | 'page';
export type SidePanelRole = 'complementary' | 'navigation';
/** Why `onOpenChange` fired. `action` and `navigation` are never emitted by SidePanel itself — they exist for a consumer whose footer action, or a followed Link inside the body, wants to report a close through the same callback (native has no client-router hook to detect a followed Link, unlike the web generator). */
export type SidePanelCloseReason = 'trigger' | 'escape' | 'close-button' | 'scrim' | 'swipe' | 'action' | 'navigation';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type SidePanelOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'border'
  | 'borderWidth'
  | 'width'
  | 'widthNarrow'
  | 'widthWide'
  | 'edgeGutter'
  | 'inset'
  | 'headerGap'
  | 'partGap'
  | 'footerGap'
  | 'layer'
  | 'enter'
  | 'exit';

export interface SidePanelProps {
  /** The Button that shows and hides the panel (usually `iconOnly` with the `menu` Icon). It is the APG disclosure button: pressing it again closes the panel. Omit to control `open` from elsewhere (a Toolbar); hidden entirely once `persistent` takes over. */
  trigger?: React.ReactNode;
  /** Controlled visibility. Omit for uncontrolled (the trigger toggles it). Ignored once `persistent` takes over — the panel is then always present. */
  open?: boolean;
  /** The panel's title and accessible name. May be visually hidden with `hideHeading`. */
  heading: string;
  /** Keep the heading for assistive technology but do not render it. The accessible name is required regardless. */
  hideHeading?: boolean;
  /** The body. Scrolls inside the panel when taller than the viewport. */
  children: React.ReactNode;
  /** Pinned to the bottom of the panel above the safe area. */
  footer?: React.ReactNode;
  /** The physical edge the panel slides from, flipped by `I18nManager.isRTL`. */
  side?: SidePanelSide;
  /** Panel width: `narrow` for a list of links, `wide` for a form or detail. Clamped to the viewport minus `edgeGutter` on narrow screens. */
  width?: SidePanelWidth;
  /** Above the chosen breakpoint the panel renders as a fixed sidebar beside the content instead of an overlay: always visible regardless of `open`, no scrim, no trap, trigger hidden. `content` switches at `layout.maxWidth.content`, `page` at `layout.maxWidth.page`. */
  persistent?: SidePanelPersistent;
  /** The landmark role the panel exposes as a persistent sidebar: `navigation` for a menu of Links, `complementary` for filters, a cart, a detail. Native has no `<aside>`/landmark equivalent for the overlay surface, so this reaches only the persistent sidebar's `role`. */
  role?: SidePanelRole;
  /** `false` (default, the disclosure pattern): focus stays on the trigger when it opens, the panel is not trapped. `true`: a modal Dialog at the edge — focus moves in and is trapped, always shows a scrim. */
  modal?: boolean;
  /** Show the scrim in non-modal mode too. Modal always has one regardless of this prop. */
  scrim?: boolean;
  /** Escape, the close button, a scrim tap and the swipe gesture all request close. When false, only the trigger and footer actions close it. */
  dismissible?: boolean;
  /** A swipe toward the edge dismisses the panel. Purely additive: the close button and (when `dismissible`) Escape always exist. Edge-swipe-to-open is not automatic — see `useSidePanelEdgeSwipe`. */
  swipeable?: boolean;
  /** Fired when the panel opens or closes, with the new state and a reason. */
  onOpenChange?: (open: boolean, reason: SidePanelCloseReason) => void;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<SidePanelOverridableBinding, TokenRef>>;
}

const COPY = {
  closeLabel: 'Close',
  openLabel: 'Open menu',
} as const;

const DRAG_DISMISS_RATIO = 0.25; // literal-ok: fraction of panel width past which a swipe dismisses, matching BottomSheet's vertical convention
const DRAG_DISMISS_VELOCITY = 1.5; // literal-ok: release velocity (px/ms) past which a swipe dismisses regardless of distance

/**
 * SidePanel — the drawer: hidden off the edge until the trigger asks for it, then
 * sliding in beside the page. Non-modal by default (the APG disclosure pattern:
 * focus stays on the trigger, the page stays live); `modal` turns it into a Dialog
 * at the edge for a panel that must be finished or dismissed. Above `persistent`'s
 * breakpoint it stops being an overlay and becomes a fixed sidebar.
 *
 * When to use: primary navigation on phones (`start` edge), filters, a cart or
 * detail panel (`end` edge), a settings drawer. Set `persistent: content` when the
 * same panel should become the permanent desktop sidebar. Do not use it for a short
 * list of actions (Menu/ActionSheet), a small task (Dialog/BottomSheet), or content
 * that is the page's point. Do not stack side panels.
 *
 * Renders a native `Modal` (`transparent`, `statusBarTranslucent`) with a full-screen
 * backdrop `Pressable` — tinted with `color.overlay.scrim` when `modal` or `scrim`,
 * transparent otherwise, though the `Modal` still intercepts every touch behind it on
 * this platform, the same native limit `Popover` documents for its own non-modal
 * mode — and an `Animated.View` surface anchored to `side` (`I18nManager.isRTL`
 * flips it), sliding in on open (skipped under reduced motion). The surface composes
 * `FocusScope` (`trapped={modal}`, `autoFocus={modal ? 'first' : 'none'}`), `Heading`
 * (level 2, hidden with `hideHeading`) for the heading, `Button` for the close control,
 * `Box` for the scrollable body and `Stack` for the footer row — never restyled
 * directly. A `PanResponder` on the surface tracks a drag toward the edge it came
 * from; past 25% of its measured width or a fast flick, it fires `onOpenChange`
 * with reason `swipe` and continues the motion off-screen with `Animated.decay` at
 * the release velocity (instant, no decay, under reduced motion); otherwise it
 * springs back. The gesture is additive — the close button always exists and is
 * gated only by `dismissible`, exactly like Escape (the Android back button via
 * `onRequestClose`), the scrim tap and the swipe: per this component's own prop
 * doc, all four are disabled when `dismissible` is false, unlike `Dialog`'s
 * "Escape always reports" precedent, which does not apply here. `width`'s tokens
 * are clamped to the viewport minus `edgeGutter` so a phone-width panel always
 * leaves a strip of scrim visible. Above the `persistent` breakpoint
 * (`useWindowDimensions` against the chosen `layout.maxWidth.*` token) the panel
 * renders instead as a plain `View` (native `role` set from the `role` prop,
 * labelled by `heading`) with a border on the edge facing the content, always
 * visible regardless of `open`, with the trigger unrendered — the mirror of the web
 * generator's fixed sidebar. Edge-swipe-to-open is not implemented inside the
 * component (it needs a gesture on the screen root, not the panel itself);
 * `useSidePanelEdgeSwipe` is exported for a consumer to wire onto their own root
 * view.
 *
 * Acknowledged native limits: `role` reaches only the persistent sidebar — the
 * overlay surface has no `<aside>`/landmark equivalent on native, so its region role
 * is not exposed while disclosed or modal; there is no page-scroll lock or `inert`
 * background — the same limit `Dialog` and `BottomSheet` document, since there is no
 * page scroll for a modal window to suppress; the modal Tab-wrap and non-modal "Tab
 * flows into the panel" behavior have no native key-event equivalent, the same limit
 * `FocusScope` itself documents; a followed `Link` inside the body cannot close the
 * panel on its own (no client router to observe), so `navigation` is never emitted
 * by this component, only reserved on the type for parity with the web/Lit docs.
 */
export function SidePanel({
  trigger,
  open,
  heading,
  hideHeading = false,
  children,
  footer,
  side = 'start',
  width = 'default',
  persistent = 'never',
  role = 'complementary',
  modal = false,
  scrim = true,
  dismissible = true,
  swipeable = true,
  onOpenChange,
  overrides,
}: SidePanelProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const { width: windowWidth } = useWindowDimensions();

  const triggerRef = React.useRef<View>(null);
  const surfaceWidthRef = React.useRef(0);

  const isControlled = open !== undefined;
  const [internalOpen, setInternalOpen] = React.useState(false);
  const isOpen = isControlled ? (open as boolean) : internalOpen;

  const [mounted, setMounted] = React.useState(isOpen);
  const progress = React.useRef(new Animated.Value(isOpen ? 1 : 0)).current;
  const dragX = React.useRef(new Animated.Value(0)).current;

  const scrimColor = overrides?.scrim ? (resolveToken(t, overrides.scrim) as string) : t.colorOverlayScrim;
  const surfaceColor = t.colorOverlaySurface;
  const shadow = overrides?.shadow ? (resolveToken(t, overrides.shadow) as typeof t.shadowOverlay) : t.shadowOverlay;
  const borderColor = overrides?.border ? (resolveToken(t, overrides.border) as string) : t.colorBorder;
  const borderWidth = overrides?.borderWidth ? (resolveToken(t, overrides.borderWidth) as number) : t.borderWidthThin;
  const widthDefault = overrides?.width ? (resolveToken(t, overrides.width) as number) : t.layoutMaxWidthProse;
  const widthNarrow = overrides?.widthNarrow ? (resolveToken(t, overrides.widthNarrow) as number) : t.space20 * 3; // literal-ok: schema-specified multiplier (space.20 × 3)
  const widthWide = overrides?.widthWide ? (resolveToken(t, overrides.widthWide) as number) : t.layoutMaxWidthContent;
  const edgeGutter = overrides?.edgeGutter ? (resolveToken(t, overrides.edgeGutter) as number) : t.space12;
  const inset = overrides?.inset ? (resolveToken(t, overrides.inset) as number) : t.layoutInsetLg;
  const headerGap = overrides?.headerGap ? (resolveToken(t, overrides.headerGap) as number) : t.layoutGapNormal;
  const partGap = overrides?.partGap ? (resolveToken(t, overrides.partGap) as number) : t.layoutGapLoose;
  const layer = overrides?.layer ? (resolveToken(t, overrides.layer) as number) : t.layerSheet;
  const enterDuration = overrides?.enter ? (resolveToken(t, overrides.enter) as number) : t.motionDurationBase;
  const exitDuration = overrides?.exit ? (resolveToken(t, overrides.exit) as number) : t.motionDurationFast;

  const persistentBreakpoint =
    persistent === 'content' ? t.layoutMaxWidthContent : persistent === 'page' ? t.layoutMaxWidthPage : null;
  const isPersistentActive = persistentBreakpoint !== null && windowWidth >= persistentBreakpoint;

  const rtl = I18nManager.isRTL;
  const isPhysicalLeft = rtl ? side === 'end' : side === 'start';
  const showScrim = modal || scrim;

  const widthToken = width === 'narrow' ? widthNarrow : width === 'wide' ? widthWide : widthDefault;
  const overlayPanelWidth = Math.min(widthToken, windowWidth - edgeGutter);

  React.useEffect(() => {
    if (isOpen) {
      setMounted(true);
    }
  }, [isOpen]);

  React.useEffect(() => {
    // The persistent sidebar has no overlay/animation lifecycle of its own.
    if (isPersistentActive || !mounted) {
      return undefined;
    }
    if (isOpen) {
      dragX.setValue(0);
      if (reducedMotion) {
        progress.setValue(1);
        return undefined;
      }
      const animation = Animated.timing(progress, {
        toValue: 1,
        duration: enterDuration,
        easing: toEasing(t.motionEasingStandard),
        // react-native-web has no native animated module.
        useNativeDriver: false,
      });
      animation.start();
      return () => animation.stop();
    }
    if (reducedMotion) {
      progress.setValue(0);
      setMounted(false);
      return undefined;
    }
    const animation = Animated.timing(progress, {
      toValue: 0,
      duration: exitDuration,
      easing: toEasing(t.motionEasingExit),
      useNativeDriver: false,
    });
    animation.start(({ finished }) => {
      if (finished) {
        setMounted(false);
      }
    });
    return () => animation.stop();
    // Reacts to the open/closed transition and the mount gate it drives; the
    // animation's own config is read fresh each run rather than tracked as a dep.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, mounted, reducedMotion, isPersistentActive]);

  React.useEffect(() => {
    if (__DEV__ && footer === undefined && !dismissible) {
      console.warn('SidePanel: with no footer and dismissible={false}, provide a way to close the panel in its body.');
    }
  }, [footer, dismissible]);

  React.useEffect(() => {
    if (__DEV__ && trigger === undefined && !isControlled) {
      console.warn(
        'SidePanel: no `trigger` and no `open` — the panel has no way to open. Pass `open` and control it from elsewhere (a Toolbar), or provide a `trigger`.',
      );
    }
  }, [trigger, isControlled]);

  const focusTrigger = React.useCallback(() => {
    const node = triggerRef.current ? findNodeHandle(triggerRef.current) : null;
    if (node !== null) {
      AccessibilityInfo.setAccessibilityFocus(node);
    }
  }, []);

  const changeOpen = (next: boolean, reason: SidePanelCloseReason): void => {
    if (!isControlled) {
      setInternalOpen(next);
    }
    onOpenChange?.(next, reason);
  };

  const requestClose = (reason: SidePanelCloseReason): void => {
    if (!isOpen) {
      return;
    }
    changeOpen(false, reason);
    focusTrigger();
  };

  const handleTriggerPress = (): void => {
    if (isOpen) {
      requestClose('trigger');
      return;
    }
    changeOpen(true, 'trigger');
  };

  const handleScrimPress = (): void => {
    if (dismissible) {
      requestClose('scrim');
    }
  };

  const handleCloseButtonPress = (): void => {
    requestClose('close-button');
  };

  const handleRequestClose = (): void => {
    if (dismissible) {
      requestClose('escape');
    }
  };

  const handleSurfaceLayout = (event: LayoutChangeEvent): void => {
    surfaceWidthRef.current = event.nativeEvent.layout.width;
  };

  const panResponder = React.useMemo(
    () =>
      PanResponder.create({
        onStartShouldSetPanResponder: () => false,
        onMoveShouldSetPanResponder: (_, gestureState) => {
          if (!swipeable || !dismissible) {
            return false;
          }
          const awayDx = isPhysicalLeft ? -gestureState.dx : gestureState.dx;
          return awayDx > 4 && Math.abs(gestureState.dx) > Math.abs(gestureState.dy);
        },
        onPanResponderMove: (_, gestureState) => {
          const awayDx = isPhysicalLeft ? -gestureState.dx : gestureState.dx;
          if (awayDx > 0) {
            dragX.setValue(gestureState.dx);
          }
        },
        onPanResponderRelease: (_, gestureState) => {
          const awayDx = isPhysicalLeft ? -gestureState.dx : gestureState.dx;
          const awayVx = isPhysicalLeft ? -gestureState.vx : gestureState.vx;
          const threshold = (surfaceWidthRef.current || overlayPanelWidth) * DRAG_DISMISS_RATIO;
          const shouldDismiss = awayDx > threshold || awayVx > DRAG_DISMISS_VELOCITY;
          if (shouldDismiss) {
            requestClose('swipe');
            if (reducedMotion) {
              dragX.setValue(isPhysicalLeft ? -windowWidth : windowWidth);
            } else {
              const decayVelocity = isPhysicalLeft ? -Math.max(awayVx, 0.5) : Math.max(awayVx, 0.5);
              Animated.decay(dragX, { velocity: decayVelocity, deceleration: 0.998, useNativeDriver: false }).start();
            }
            return;
          }
          if (reducedMotion) {
            dragX.setValue(0);
            return;
          }
          Animated.timing(dragX, {
            toValue: 0,
            duration: exitDuration,
            easing: toEasing(t.motionEasingStandard),
            useNativeDriver: false,
          }).start();
        },
        onPanResponderTerminate: () => {
          if (reducedMotion) {
            dragX.setValue(0);
            return;
          }
          Animated.timing(dragX, { toValue: 0, duration: exitDuration, useNativeDriver: false }).start();
        },
      }),
    [swipeable, dismissible, isPhysicalLeft, dragX, windowWidth, overlayPanelWidth, reducedMotion, exitDuration, t.motionEasingStandard],
  );

  const isTriggerElement = React.isValidElement(trigger);
  const triggerChild = isTriggerElement ? (trigger as React.ReactElement<Record<string, unknown>>) : null;
  const triggerChildProps = triggerChild?.props ?? {};
  const triggerHasLabel = typeof triggerChildProps.label === 'string';

  React.useEffect(() => {
    if (__DEV__ && trigger !== undefined && !isTriggerElement) {
      console.warn('SidePanel: `trigger` must be exactly one focusable element (usually a Button).');
    }
  }, [trigger, isTriggerElement]);

  const clonedTrigger =
    triggerChild !== null
      ? React.cloneElement(triggerChild, {
          onPress: (event: unknown) => {
            (triggerChildProps.onPress as ((e: unknown) => void) | undefined)?.(event);
            handleTriggerPress();
          },
          // No-op on this package's own Button, which does not forward unrecognized
          // props (see Popover's doc); kept for a trigger that does forward extra props.
          accessibilityState: { expanded: isOpen },
          ...(triggerHasLabel ? null : { accessibilityLabel: COPY.openLabel }),
        })
      : trigger;

  if (isPersistentActive) {
    const sidebarStyle: ViewStyle = {
      width: widthToken,
      height: '100%',
      backgroundColor: surfaceColor,
      gap: partGap,
      ...(isPhysicalLeft
        ? { borderRightWidth: borderWidth, borderRightColor: borderColor }
        : { borderLeftWidth: borderWidth, borderLeftColor: borderColor }),
    };
    const headerStyle: ViewStyle = {
      paddingHorizontal: inset,
      paddingTop: inset,
    };
    const bodyFlexStyle: ViewStyle = { flexShrink: 1 };
    const bodyContentStyle: ViewStyle = { flexGrow: 1 };
    const footerStyle: ViewStyle = {
      paddingHorizontal: inset,
      paddingBottom: inset,
    };

    return (
      <View style={sidebarStyle} role={role} accessibilityLabel={heading} testID="SidePanel">
        {!hideHeading ? (
          <View style={headerStyle} testID="SidePanel.header">
            <Heading level={2}>{heading}</Heading>
          </View>
        ) : null}
        <ScrollView testID="SidePanel.body" style={bodyFlexStyle} contentContainerStyle={bodyContentStyle}>
          <Box inset="lg" overrides={overrides?.inset ? { paddingBlock: overrides.inset, paddingInline: overrides.inset } : undefined}>
            {children}
          </Box>
        </ScrollView>
        {footer !== undefined ? (
          <SafeAreaView style={footerStyle} testID="SidePanel.footer">
            <Stack
              direction="horizontal"
              gap="tight"
              justify="end"
              overrides={overrides?.footerGap ? { gap: overrides.footerGap } : undefined}
            >
              {footer}
            </Stack>
          </SafeAreaView>
        ) : null}
      </View>
    );
  }

  const hostStyle: ViewStyle = { flex: 1 };

  const scrimStyle: Animated.WithAnimatedObject<ViewStyle> = {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: scrimColor,
    opacity: showScrim ? progress : 0,
  };

  const anchorStyle: ViewStyle = {
    flex: 1,
    flexDirection: 'row',
    justifyContent: isPhysicalLeft ? 'flex-start' : 'flex-end',
    zIndex: layer,
  };

  const entryTranslateX = progress.interpolate({
    inputRange: [0, 1],
    outputRange: [isPhysicalLeft ? -overlayPanelWidth : overlayPanelWidth, 0],
  });

  const surfaceStyle: Animated.WithAnimatedObject<ViewStyle> = {
    width: overlayPanelWidth,
    height: '100%',
    ...shadow,
    backgroundColor: surfaceColor,
    overflow: 'hidden',
    gap: partGap,
    transform: [{ translateX: Animated.add(entryTranslateX, dragX) }],
  };

  const headerStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: headerGap,
    paddingHorizontal: inset,
    paddingTop: inset,
  };

  const bodyFlexStyle: ViewStyle = { flexShrink: 1 };
  const bodyContentStyle: ViewStyle = { flexGrow: 1 };

  const footerStyle: ViewStyle = {
    paddingHorizontal: inset,
    paddingBottom: inset,
  };

  return (
    <View testID="SidePanel">
      {trigger !== undefined ? (
        <View ref={triggerRef} collapsable={false} testID="SidePanel.trigger">
          {clonedTrigger}
        </View>
      ) : null}
      <Modal visible={mounted} transparent onRequestClose={handleRequestClose} statusBarTranslucent>
        <View style={hostStyle}>
          <Animated.View style={scrimStyle} />
          <Pressable
            style={StyleSheet.absoluteFillObject}
            onPress={handleScrimPress}
            accessible={false}
            testID="SidePanel.scrim"
          />
          <View style={anchorStyle} pointerEvents="box-none">
            <FocusScope trapped={modal} active={mounted} autoFocus={modal ? 'first' : 'none'} restoreFocus={false}>
              <Animated.View
                {...(swipeable && dismissible ? panResponder.panHandlers : null)}
                style={surfaceStyle}
                onLayout={handleSurfaceLayout}
                accessibilityViewIsModal={modal}
                accessibilityLabel={heading}
                testID="SidePanel.surface"
              >
                <View style={headerStyle} testID="SidePanel.header">
                  {!hideHeading ? <Heading level={2}>{heading}</Heading> : null}
                  <Button
                    label={COPY.closeLabel}
                    variant="ghost"
                    size="sm"
                    iconOnly
                    disabled={!dismissible}
                    leadingIcon={<Icon name="close" color={t.colorActionGhostForeground} />}
                    onPress={handleCloseButtonPress}
                  />
                </View>
                <ScrollView
                  testID="SidePanel.body"
                  style={bodyFlexStyle}
                  contentContainerStyle={bodyContentStyle}
                  keyboardShouldPersistTaps="handled"
                >
                  <Box
                    inset="lg"
                    overrides={overrides?.inset ? { paddingBlock: overrides.inset, paddingInline: overrides.inset } : undefined}
                  >
                    {children}
                  </Box>
                </ScrollView>
                {footer !== undefined ? (
                  <SafeAreaView style={footerStyle} testID="SidePanel.footer">
                    <Stack
                      direction="horizontal"
                      gap="tight"
                      justify="end"
                      overrides={overrides?.footerGap ? { gap: overrides.footerGap } : undefined}
                    >
                      {footer}
                    </Stack>
                  </SafeAreaView>
                ) : null}
              </Animated.View>
            </FocusScope>
          </View>
        </View>
      </Modal>
    </View>
  );
}

export interface UseSidePanelEdgeSwipeOptions {
  /** Must match the SidePanel's own `side`; the hook flips it for RTL the same way. */
  side?: SidePanelSide;
  /** Turn the gesture off, e.g. while the panel is already open. */
  enabled?: boolean;
  /** Fired when an edge swipe crosses the open threshold. The consumer sets its own `open` state — this hook has no knowledge of the panel it opens. */
  onOpen: () => void;
}

/**
 * A `PanResponder` for the screen root that opens a `SidePanel` on an edge swipe —
 * additive to the trigger and never the only way in (WCAG 2.5.1). Not part of
 * `SidePanel` itself: the gesture has to start from the edge of the whole screen,
 * outside the panel's own (unmounted-when-closed) surface, so the schema asks for a
 * hook the consumer wires onto their own root view rather than an automatic behavior
 * `SidePanel` could silently opt every screen into.
 */
export function useSidePanelEdgeSwipe({ side = 'start', enabled = true, onOpen }: UseSidePanelEdgeSwipeOptions) {
  const { tokens: t } = useTheme();
  const { width: windowWidth } = useWindowDimensions();
  const rtl = I18nManager.isRTL;
  const isPhysicalLeft = rtl ? side === 'end' : side === 'start';
  // No token names the zone a swipe must start within; the comfortable target size is
  // the closest existing token to "a thumb's-width strip at the edge."
  const edgeZone = t.sizeTargetComfortable;

  const panResponder = React.useMemo(
    () =>
      PanResponder.create({
        onStartShouldSetPanResponder: (_, gestureState) => {
          if (!enabled) {
            return false;
          }
          return isPhysicalLeft ? gestureState.x0 <= edgeZone : gestureState.x0 >= windowWidth - edgeZone;
        },
        onMoveShouldSetPanResponder: (_, gestureState) => {
          if (!enabled) {
            return false;
          }
          const inwardDx = isPhysicalLeft ? gestureState.dx : -gestureState.dx;
          return inwardDx > 4 && Math.abs(gestureState.dx) > Math.abs(gestureState.dy);
        },
        onPanResponderRelease: (_, gestureState) => {
          const inwardDx = isPhysicalLeft ? gestureState.dx : -gestureState.dx;
          if (inwardDx > edgeZone / 2) {
            onOpen();
          }
        },
      }),
    [enabled, isPhysicalLeft, windowWidth, edgeZone, onOpen],
  );

  return { panHandlers: panResponder.panHandlers };
}

// packages/lit/src/SidePanel.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Heading.js';
import './Button.js';
import './Icon.js';
import './Box.js';
import './Stack.js';
import './FocusScope.js';

export type SidePanelSide = 'start' | 'end';
export type SidePanelWidth = 'narrow' | 'default' | 'wide';
export type SidePanelPersistent = 'never' | 'content' | 'page';
export type SidePanelLandmark = 'complementary' | 'navigation';
export type SidePanelOpenChangeReason =
  | 'trigger'
  | 'escape'
  | 'close-button'
  | 'scrim'
  | 'swipe'
  | 'action'
  | 'navigation';

/** Detail carried by the `open-change` CustomEvent. */
export interface SidePanelOpenChangeDetail {
  open: boolean;
  reason: SidePanelOpenChangeReason;
}

/** Overridable style hooks; see the `overrides` property. `surface`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type SidePanelOverridableBinding =
  | 'scrim'
  | 'shadow'
  | 'border'
  | 'borderWidth'
  | 'width'
  | 'widthNarrow'
  | 'widthWide'
  | 'edgeGutter'
  | 'inset'
  | 'headerGap'
  | 'partGap'
  | 'footerGap'
  | 'layer'
  | 'enter'
  | 'exit';

const HOOKS: Record<SidePanelOverridableBinding, string> = {
  scrim: '--ds-side-panel-scrim',
  shadow: '--ds-side-panel-shadow',
  border: '--ds-side-panel-border',
  borderWidth: '--ds-side-panel-border-width',
  width: '--ds-side-panel-width',
  widthNarrow: '--ds-side-panel-width-narrow',
  widthWide: '--ds-side-panel-width-wide',
  edgeGutter: '--ds-side-panel-edge-gutter',
  inset: '--ds-side-panel-inset',
  headerGap: '--ds-side-panel-header-gap',
  partGap: '--ds-side-panel-part-gap',
  footerGap: '--ds-side-panel-footer-gap',
  layer: '--ds-side-panel-layer',
  enter: '--ds-side-panel-enter',
  exit: '--ds-side-panel-exit',
};

/** copy.closeLabel */
const COPY_CLOSE_LABEL = 'Close';

/** Negates a boolean attribute: `no-dismiss` present means `dismissible` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
  'ds-button',
  'ds-link',
  'ds-input',
  'ds-checkbox',
  'ds-switch',
  'ds-radio-group',
  'ds-disclosure',
].join(',');

function findFirstFocusable(root: Element): HTMLElement | null {
  if (root instanceof HTMLElement && root.matches(FOCUSABLE_SELECTOR)) {
    return root;
  }
  return root.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
}

/** How many modal `<ds-side-panel>` instances currently hold the body-scroll lock. */
let openModalCount = 0;

function lockBodyScroll(): void {
  openModalCount += 1;
  if (openModalCount === 1) {
    document.documentElement.style.overflow = 'hidden';
  }
}

function unlockBodyScroll(): void {
  openModalCount = Math.max(0, openModalCount - 1);
  if (openModalCount === 0) {
    document.documentElement.style.removeProperty('overflow');
  }
}

function prefersReducedMotion(): boolean {
  return matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * `<ds-side-panel>` — SidePanel (category: overlay, APG pattern: disclosure).
 *
 * `<ds-side-panel heading="Menu" persistent="content"><ds-button slot="trigger"
 * icon-only label="Menu"></ds-button><ds-list>…</ds-list></ds-side-panel>`. The
 * `trigger` slot holds the APG disclosure button; clicking it toggles the
 * panel and sets `aria-expanded` directly on it (`aria-controls` is never set
 * — it cannot address an id inside the shadow root). A shadow `<dialog>`
 * backs both overlay modes: non-modal (default) opens it with `.show()` —
 * no backdrop, no trap, focus stays on the trigger, Tab flows trigger → panel
 * → page because the panel sits right after the trigger slot in the
 * flattened tree; modal opens it with `.showModal()` — native top layer,
 * inert background, focus moved in and trapped by `<ds-focus-scope trapped>`.
 * Above the `persistent` breakpoint (a `matchMedia` listener on the resolved
 * `layout.maxWidth.{content,page}` token) the host switches to `display:
 * block` in the parent grid, the trigger is hidden, and the same header/body/
 * footer render inside a plain `<aside role={landmark}>` — no dialog, no
 * scrim, no trap, part of the page's tab order.
 *
 * ## When to use
 *
 * Use a SidePanel for phone navigation (a List or Tree of Links from the
 * `start` edge), for filters beside a results page, for a cart or detail
 * panel from the `end` edge, for a settings drawer. Set `persistent="content"`
 * when the same panel should become the permanent sidebar on desktop; leave
 * it `"never"` for panels that are always a temporary overlay.
 *
 * ## When not to use
 *
 * Not for a short list of actions (Menu, ActionSheet), a task with a few
 * fields (Dialog, BottomSheet), or content that is the page's point. Never
 * open one on hover, never stack side panels, and use `modal` only when the
 * page must not be used until the panel is done — a navigation drawer is not
 * that.
 *
 * @fires open-change - Fired when the panel opens or closes, with `{ open,
 *   reason }` in `detail`; `reason` is `trigger`, `escape`, `close-button`,
 *   `scrim`, `swipe`, `action` or `navigation`.
 * @slot trigger - The APG disclosure button that shows and hides the panel. Omit to control `open` from elsewhere.
 * @slot - The body: a List, Tree or Form. Scrolls inside the panel when taller than the viewport (anatomy: body).
 * @slot footer - Pinned above the safe area (anatomy: footer).
 * @csspart scrim - The non-modal backdrop, shown when `scrim` is set (anatomy: scrim).
 * @csspart surface - The padded surface: the `<dialog>` in overlay mode, the `<aside>` in persistent mode (anatomy: surface).
 * @csspart focus-scope - The focus-trapping wrapper (anatomy: focusScope).
 * @csspart header - The header row (anatomy: header).
 * @csspart heading - The `<ds-heading>` (anatomy: heading).
 * @csspart body - The `<ds-box>` wrapping the default slot (anatomy: body).
 * @csspart footer - The footer row (anatomy: footer).
 * @csspart close-button - The close `<ds-button>` (anatomy: closeButton).
 */
@customElement('ds-side-panel')
export class DsSidePanel extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      --ds-side-panel-scrim: var(--color-overlay-scrim);
      --ds-side-panel-shadow: var(--shadow-overlay);
      --ds-side-panel-border: var(--color-border);
      --ds-side-panel-border-width: var(--border-width-thin);
      --ds-side-panel-width: var(--layout-max-width-prose);
      --ds-side-panel-width-narrow: calc(var(--space-20) * 3);
      --ds-side-panel-width-wide: var(--layout-max-width-content);
      --ds-side-panel-edge-gutter: var(--space-12);
      --ds-side-panel-inset: var(--layout-inset-lg);
      --ds-side-panel-header-gap: var(--layout-gap-normal);
      --ds-side-panel-part-gap: var(--layout-gap-loose);
      --ds-side-panel-footer-gap: var(--layout-gap-tight);
      --ds-side-panel-layer: var(--layer-sheet);
      --ds-side-panel-enter: var(--motion-duration-base);
      --ds-side-panel-exit: var(--motion-duration-fast);
      --ds-side-panel-active-width: var(--ds-side-panel-width);
    }

    :host([width='narrow']) {
      --ds-side-panel-active-width: var(--ds-side-panel-width-narrow);
    }
    :host([width='wide']) {
      --ds-side-panel-active-width: var(--ds-side-panel-width-wide);
    }

    :host([hidden]) {
      display: none;
    }

    /* persistent: above the breakpoint the host itself lays out as a sidebar in the parent grid. */
    :host(.persistent) {
      display: block;
      inline-size: var(--ds-side-panel-active-width);
      block-size: 100%;
    }

    ::slotted([slot='trigger']) {
      display: inline-flex;
    }
    :host(.persistent) ::slotted([slot='trigger']) {
      display: none;
    }

    .scrim {
      position: fixed;
      inset: 0;
      margin: 0;
      padding: 0;
      border: 0;
      background: var(--ds-side-panel-scrim);
      z-index: calc(var(--ds-side-panel-layer) - 1);
    }
    .scrim[hidden] {
      display: none;
    }

    .surface {
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      gap: var(--ds-side-panel-part-gap);
      font-family: var(--font-family-body);
      color: var(--color-foreground);
      /* surface: color.overlay.surface, locked — no override hook */
      background: var(--color-overlay-surface);
    }

    dialog.surface {
      margin: 0;
      padding: 0;
      border: 0;
      max-inline-size: none;
      position: fixed;
      inset-block: 0;
      inset-inline: auto;
      block-size: 100dvh;
      inline-size: min(var(--ds-side-panel-active-width), calc(100vw - var(--ds-side-panel-edge-gutter)));
      box-shadow: var(--ds-side-panel-shadow);
      z-index: var(--ds-side-panel-layer);
      color: inherit;
    }

    :host([side='start']) dialog.surface {
      inset-inline-start: 0;
      transition: inset-inline-start var(--ds-side-panel-enter) var(--motion-easing-standard);
    }
    :host([side='end']) dialog.surface {
      inset-inline-end: 0;
      transition: inset-inline-end var(--ds-side-panel-enter) var(--motion-easing-standard);
    }

    :host([side='start']) dialog.surface.closing {
      inset-inline-start: calc(-1 * var(--ds-side-panel-active-width));
      transition-duration: var(--ds-side-panel-exit);
      transition-timing-function: var(--motion-easing-exit);
    }
    :host([side='end']) dialog.surface.closing {
      inset-inline-end: calc(-1 * var(--ds-side-panel-active-width));
      transition-duration: var(--ds-side-panel-exit);
      transition-timing-function: var(--motion-easing-exit);
    }

    @starting-style {
      :host([side='start']) dialog.surface[open] {
        inset-inline-start: calc(-1 * var(--ds-side-panel-active-width));
      }
      :host([side='end']) dialog.surface[open] {
        inset-inline-end: calc(-1 * var(--ds-side-panel-active-width));
      }
    }

    dialog.surface::backdrop {
      background: var(--ds-side-panel-scrim);
      transition: opacity var(--ds-side-panel-enter) var(--motion-easing-standard);
    }
    @starting-style {
      dialog.surface[open]::backdrop {
        opacity: 0;
      }
    }

    @media (prefers-reduced-motion: reduce) {
      dialog.surface,
      dialog.surface::backdrop {
        transition: none;
      }
    }

    aside.surface {
      inline-size: 100%;
      block-size: 100%;
    }
    :host(.persistent[side='start']) aside.surface {
      border-inline-end: var(--ds-side-panel-border-width) solid var(--ds-side-panel-border);
    }
    :host(.persistent[side='end']) aside.surface {
      border-inline-start: var(--ds-side-panel-border-width) solid var(--ds-side-panel-border);
    }

    .header {
      display: flex;
      flex-direction: column;
      padding-inline: var(--ds-side-panel-inset);
      padding-block-start: var(--ds-side-panel-inset);
      flex: 0 0 auto;
    }

    .heading-row {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: var(--ds-side-panel-header-gap);
      min-inline-size: 0;
    }

    .heading {
      min-inline-size: 0;
    }

    /* hideHeading: kept for the accessible name, removed from the visual layout. */
    .heading--hidden {
      /* literal-ok: standard visually-hidden clip pattern, exempt from token-only rule */
      position: absolute;
      width: 1px;
      height: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }

    #heading:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
      border-radius: var(--radius-sm);
    }

    .close {
      flex: none;
    }

    .body {
      flex: 1 1 auto;
      min-block-size: 0;
      overflow-y: auto;
    }

    .footer-row {
      padding-block-end: env(safe-area-inset-bottom);
    }
  `;

  /** Controlled visibility. Omit for uncontrolled (the trigger toggles it). */
  @property({ type: Boolean, reflect: true }) accessor open: boolean | undefined;

  /**
   * The panel's title and accessible name. Named `heading`, not `title` —
   * `HTMLElement` already defines `title` as the tooltip attribute (see
   * Dialog and BottomSheet).
   */
  @property() accessor heading!: string;

  /** Keep the title for assistive technology but do not render it. The accessible name is required regardless. */
  @property({ type: Boolean, attribute: 'hide-heading' }) accessor hideHeading = false;

  /** The edge the panel slides from; `start`/`end` follow the writing direction. */
  @property({ reflect: true }) accessor side: SidePanelSide = 'start';

  /** Panel width on wide screens. On phones the panel is the viewport width minus `edgeGutter`. */
  @property({ reflect: true }) accessor width: SidePanelWidth = 'default';

  /** Above this layout width the panel becomes a fixed sidebar: always visible, no scrim, no trap, no trigger. */
  @property({ reflect: true }) accessor persistent: SidePanelPersistent = 'never';

  /**
   * The landmark role the panel exposes, in persistent mode and as the shadow
   * region's role when open. Named `landmark`, not `role` — `Element` already
   * defines `role` via ARIA reflection.
   */
  @property({ attribute: 'landmark' }) accessor landmark: SidePanelLandmark = 'complementary';

  /** `false` (default, the disclosure pattern): no trap, focus stays on the trigger. `true`: a modal Dialog at the edge. */
  @property({ type: Boolean }) accessor modal = false;

  /**
   * Show the scrim in non-modal mode too (modal always has one). Attribute
   * is the negation, `no-scrim`, because a boolean attribute cannot express
   * `false` for a prop that defaults `true`.
   */
  @property({ attribute: 'no-scrim', converter: NEGATED_BOOLEAN_CONVERTER }) accessor scrim = true;

  /**
   * Escape, the close button, a scrim tap / outside click, and the swipe
   * gesture all request close. When false, only the trigger and footer
   * actions close it. Attribute is the negation, `no-dismiss`.
   */
  @property({ attribute: 'no-dismiss', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER })
  accessor dismissible = true;

  /**
   * On touch, a swipe toward the edge dismisses (native only — not wired up
   * on the web platform). Attribute is the negation, `no-swipe`.
   */
  @property({ attribute: 'no-swipe', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER })
  accessor swipeable = true;

  /** Per-instance style overrides: `{ inset: 'layout.inset.md' }`. Locked bindings (surface, focusRing, focusRingWidth) are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<SidePanelOverridableBinding, TokenRef | undefined>> | undefined;

  /** Uncontrolled open state, used when `open` is omitted. */
  @state() private accessor internalOpen = false;

  /** Whether the persistent breakpoint currently matches. */
  @state() private accessor isPersistent = false;

  /** Whether the exit transition is playing. */
  @state() private accessor closing = false;

  /** Whether the default slot currently has assigned content, for the dev warning. */
  @state() private accessor hasBodyContent = false;

  @query('dialog') private accessor dialogEl!: HTMLDialogElement | null;
  @query('#heading') private accessor headingEl!: HTMLElement | null;
  @query('.close') private accessor closeButtonEl!: HTMLElement | null;

  private triggerEl: HTMLElement | null = null;
  private persistentQuery: MediaQueryList | null = null;
  private wasLogicalOpen = false;
  private wasOverlayOpen = false;
  private pendingReason: SidePanelOpenChangeReason = 'trigger';
  private focusTriggerOnClose = false;
  private closingProgrammatically = false;

  /** Whether the panel is currently open, controlled or not. */
  get currentOpen(): boolean {
    return this.open ?? this.internalOpen;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'SidePanel');
    this.setupPersistentQuery();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.persistentQuery?.removeEventListener('change', this.handlePersistentChange);
    this.removeOutsideListener();
    if (this.modal && this.wasOverlayOpen) {
      unlockBodyScroll();
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('persistent')) {
      this.setupPersistentQuery();
    }
    // Crossing into the persistent breakpoint while open: the render below is
    // about to swap the <dialog> for an <aside>, so clean up now while the
    // dialog element from the previous render is still queryable.
    if (changed.has('isPersistent') && this.isPersistent && this.wasOverlayOpen) {
      this.wasOverlayOpen = false;
      this.finishOverlayClose();
    }
  }

  protected override updated(): void {
    const isOpen = this.currentOpen;
    if (isOpen !== this.wasLogicalOpen) {
      this.wasLogicalOpen = isOpen;
      this.updateTriggerExpanded();
      this.dispatchOpenChange(isOpen);
    }
    const showOverlay = isOpen && !this.isPersistent;
    if (showOverlay !== this.wasOverlayOpen) {
      this.wasOverlayOpen = showOverlay;
      if (showOverlay) {
        this.openOverlay();
      } else {
        this.playExitAnimation();
      }
    }
    this.classList.toggle('persistent', this.isPersistent);
    this.warnInDev();
  }

  protected override render(): TemplateResult {
    const isOpen = this.currentOpen;
    const isPersistent = this.isPersistent;
    const hasFooter = this.querySelector('[slot="footer"]') !== null;
    const headingClasses = classMap({ heading: true, 'heading--hidden': this.hideHeading });

    const content = html`
      <ds-focus-scope
        part="focus-scope"
        .trapped=${this.modal && !isPersistent}
        .active=${isOpen || isPersistent}
        auto-focus="none"
        .restoreFocus=${false}
        style="display: flex; flex-direction: column; gap: var(--ds-side-panel-part-gap); min-block-size: 0; flex: 1 1 auto"
      >
        <div class="header" part="header">
          <div class="heading-row">
            <ds-heading id="heading" part="heading" class=${headingClasses} level="2" size="lg" tabindex="-1"
              >${this.heading}</ds-heading
            >
            ${!isPersistent
              ? html`
                  <ds-button
                    class="close"
                    part="close-button"
                    variant="ghost"
                    size="md"
                    icon-only
                    label=${COPY_CLOSE_LABEL}
                    @press=${this.handleCloseButtonPress}
                  >
                    <ds-icon slot="leading-icon" name="close"></ds-icon>
                  </ds-button>
                `
              : nothing}
          </div>
        </div>
        <ds-box class="body" part="body" inset="lg" .overrides=${this.bodyOverrides()} @click=${this.handleBodyClick}>
          <slot @slotchange=${this.handleBodySlotChange}></slot>
        </ds-box>
        ${hasFooter
          ? html`
              <ds-stack class="footer-row" part="footer" direction="horizontal" justify="end" style="gap: var(--ds-side-panel-footer-gap)">
                <slot name="footer"></slot>
              </ds-stack>
            `
          : nothing}
      </ds-focus-scope>
    `;

    return html`
      <slot name="trigger" @slotchange=${this.handleTriggerSlotChange}></slot>
      ${!this.modal && !isPersistent
        ? html`
            <div
              class="scrim"
              part="scrim"
              aria-hidden="true"
              ?hidden=${!(this.scrim && isOpen)}
              @pointerdown=${this.handleScrimPointerDown}
            ></div>
          `
        : nothing}
      ${isPersistent
        ? html`<aside class="surface" part="surface" role=${this.landmark} aria-labelledby="heading">${content}</aside>`
        : html`
            <dialog
              class="surface${this.closing ? ' closing' : ''}"
              part="surface"
              role=${this.modal ? nothing : this.landmark}
              aria-modal=${this.modal ? 'true' : nothing}
              aria-labelledby="heading"
              @cancel=${this.handleCancel}
              @close=${this.handleNativeClose}
              @click=${this.handleDialogClick}
              @keydown=${this.handlePanelKeydown}
            >
              ${content}
            </dialog>
          `}
    `;
  }

  private bodyOverrides() {
    const inset = this.overrides?.inset;
    return inset ? { paddingBlock: inset, paddingInline: inset } : undefined;
  }

  private readonly handleTriggerSlotChange = (event: Event): void => {
    const slot = event.target as HTMLSlotElement;
    const next = (slot.assignedElements({ flatten: true })[0] as HTMLElement | undefined) ?? null;
    if (next === this.triggerEl) {
      return;
    }
    this.detachTrigger();
    this.triggerEl = next;
    this.attachTrigger();
  };

  private attachTrigger(): void {
    const trigger = this.triggerEl;
    if (!trigger) {
      return;
    }
    trigger.addEventListener('click', this.handleTriggerClick);
    this.updateTriggerExpanded();
    this.warnInDev();
  }

  private detachTrigger(): void {
    const trigger = this.triggerEl;
    if (!trigger) {
      return;
    }
    trigger.removeEventListener('click', this.handleTriggerClick);
    trigger.removeAttribute('aria-expanded');
  }

  private updateTriggerExpanded(): void {
    this.triggerEl?.setAttribute('aria-expanded', this.currentOpen ? 'true' : 'false');
  }

  private readonly handleTriggerClick = (): void => {
    this.requestOpenChange(!this.currentOpen, 'trigger', false);
  };

  private readonly handleBodySlotChange = (event: Event): void => {
    const slot = event.target as HTMLSlotElement;
    this.hasBodyContent = slot.assignedNodes({ flatten: true }).length > 0;
    this.warnInDev();
  };

  private readonly handleBodyClick = (event: Event): void => {
    if (this.isPersistent) {
      return;
    }
    const link = event
      .composedPath()
      .find((target): target is HTMLElement => target instanceof HTMLElement && (target.tagName === 'A' || target.tagName === 'DS-LINK'));
    if (link) {
      this.requestOpenChange(false, 'navigation', true);
    }
  };

  private readonly handleCloseButtonPress = (event: Event): void => {
    // Keep the button's `press` inside the panel; consumers listen for `open-change`.
    event.stopPropagation();
    if (!this.dismissible) {
      return;
    }
    this.requestOpenChange(false, 'close-button', true);
  };

  private readonly handleCancel = (event: Event): void => {
    // The native default would close the <dialog> itself; the consumer owns `open` instead.
    event.preventDefault();
    if (!this.dismissible) {
      return;
    }
    this.requestOpenChange(false, 'escape', true);
  };

  private readonly handlePanelKeydown = (event: KeyboardEvent): void => {
    // A modal <dialog> already emits `cancel` for Escape; only handle it here for the non-modal (`.show()`) case.
    if (event.key !== 'Escape' || this.modal || !this.dismissible) {
      return;
    }
    event.preventDefault();
    this.requestOpenChange(false, 'escape', true);
  };

  private readonly handleDialogClick = (event: MouseEvent): void => {
    // Modal only: a click on the ::backdrop lands with the <dialog> itself as the target.
    if (!this.modal || !this.dismissible || event.target !== this.dialogEl) {
      return;
    }
    this.requestOpenChange(false, 'scrim', true);
  };

  private readonly handleScrimPointerDown = (): void => {
    if (!this.dismissible) {
      return;
    }
    this.requestOpenChange(false, 'scrim', true);
  };

  private readonly handleOutsidePointerDown = (event: PointerEvent): void => {
    if (event.composedPath().includes(this)) {
      return;
    }
    if (!this.dismissible) {
      return;
    }
    this.requestOpenChange(false, 'scrim', false);
  };

  private readonly handleNativeClose = (): void => {
    if (this.closingProgrammatically) {
      this.closingProgrammatically = false;
      return;
    }
    // Something else (a form with method="dialog", a direct .close() call) closed the dialog.
    this.requestOpenChange(false, 'action', false);
  };

  private requestOpenChange(next: boolean, reason: SidePanelOpenChangeReason, focusTriggerOnClose: boolean): void {
    this.pendingReason = reason;
    this.focusTriggerOnClose = focusTriggerOnClose;
    if (this.open !== undefined) {
      this.open = next;
    } else {
      this.internalOpen = next;
    }
  }

  private openOverlay(): void {
    this.closing = false;
    if (this.modal) {
      lockBodyScroll();
      this.dialogEl?.showModal();
      this.applyInitialFocus();
    } else {
      this.dialogEl?.show();
      this.addOutsideListener();
    }
  }

  private playExitAnimation(): void {
    if (prefersReducedMotion()) {
      this.finishOverlayClose();
      return;
    }
    this.closing = true;
    const dialog = this.dialogEl;
    if (!dialog) {
      this.finishOverlayClose();
      return;
    }
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target !== dialog || (event.propertyName !== 'inset-inline-start' && event.propertyName !== 'inset-inline-end')) {
        return;
      }
      dialog.removeEventListener('transitionend', handleTransitionEnd);
      this.finishOverlayClose();
    };
    dialog.addEventListener('transitionend', handleTransitionEnd);
  }

  private finishOverlayClose(): void {
    this.closing = false;
    this.removeOutsideListener();
    const dialog = this.dialogEl;
    if (dialog?.open) {
      this.closingProgrammatically = true;
      dialog.close();
    }
    if (this.modal) {
      unlockBodyScroll();
    }
    if (this.focusTriggerOnClose) {
      this.focusTriggerOnClose = false;
      this.triggerEl?.focus();
    }
  }

  private applyInitialFocus(): void {
    const target = this.findFirstBodyFocusable() ?? this.closeButtonEl ?? this.headingEl;
    target?.focus();
  }

  private findFirstBodyFocusable(): HTMLElement | null {
    const slot = this.renderRoot.querySelector<HTMLSlotElement>('slot:not([name])');
    if (!slot) {
      return null;
    }
    for (const element of slot.assignedElements({ flatten: true })) {
      const found = findFirstFocusable(element);
      if (found) {
        return found;
      }
    }
    return null;
  }

  private addOutsideListener(): void {
    document.addEventListener('pointerdown', this.handleOutsidePointerDown, true);
  }

  private removeOutsideListener(): void {
    document.removeEventListener('pointerdown', this.handleOutsidePointerDown, true);
  }

  private setupPersistentQuery(): void {
    this.persistentQuery?.removeEventListener('change', this.handlePersistentChange);
    this.persistentQuery = null;
    if (this.persistent === 'never') {
      this.isPersistent = false;
      return;
    }
    const tokenVar = this.persistent === 'page' ? '--layout-max-width-page' : '--layout-max-width-content';
    const breakpoint = getComputedStyle(document.documentElement).getPropertyValue(tokenVar).trim();
    if (!breakpoint) {
      this.isPersistent = false;
      return;
    }
    this.persistentQuery = matchMedia(`(min-width: ${breakpoint})`);
    this.isPersistent = this.persistentQuery.matches;
    this.persistentQuery.addEventListener('change', this.handlePersistentChange);
  }

  private readonly handlePersistentChange = (event: MediaQueryListEvent): void => {
    this.isPersistent = event.matches;
  };

  private dispatchOpenChange(open: boolean): void {
    this.dispatchEvent(
      new CustomEvent<SidePanelOpenChangeDetail>('open-change', {
        detail: { open, reason: this.pendingReason },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as SidePanelOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.heading) {
      console.warn('<ds-side-panel> requires a `heading`, used as the accessible name.', this);
    }
    if (!this.triggerEl && this.open === undefined) {
      console.warn(
        '<ds-side-panel> has no `trigger` slot and no controlled `open`; it can never be shown.',
        this,
      );
    }
    if (!this.hasBodyContent) {
      console.warn('<ds-side-panel> requires content in its default slot.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-side-panel': DsSidePanel;
  }
}
