// packages/rn/src/Splitter.tsx
import * as React from 'react';
import { Animated, PanResponder, View } from 'react-native';
import type { AccessibilityActionEvent, LayoutChangeEvent, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { Icon } from './Icon';
import type { IconName } from './Icon';
import { Text } from './Text';
import { toEasing, useReducedMotion, useTheme } from './theme';

export type SplitterOrientation = 'horizontal' | 'vertical';
export type SplitterStackBelow = 'prose' | 'content' | 'never';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type SplitterOverridableBinding =
  | 'separatorSize'
  | 'separatorColor'
  | 'handleSize'
  | 'gripLength'
  | 'gripRadius'
  | 'collapseButtonOffset'
  | 'transition';

export interface SplitterProps {
  /** What the divider resizes ("Sidebar width", "Preview height"). The separator's accessible name. */
  label: string;
  /** `horizontal` places panes side by side (the separator is vertical); `vertical` stacks them. A vertical splitter needs a parent with a definite height. */
  orientation?: SplitterOrientation | undefined;
  /** The first pane (start or top). Its size is what the separator controls and reports. A string or number is wrapped in `Text`. */
  primary: React.ReactNode;
  /** The second pane, which takes the remaining space. A string or number is wrapped in `Text`, as `primary`. */
  secondary: React.ReactNode;
  /** Controlled size of the primary pane as a percentage of the container (0–100). */
  size?: number | undefined;
  /** Initial primary size, percent. */
  defaultSize?: number | undefined;
  /** Smallest primary size, percent. With `collapsible`, a step that would cross it clamps here first and the next shrink step collapses; otherwise it is the hard floor. */
  minSize?: number | undefined;
  /** Largest primary size, percent. */
  maxSize?: number | undefined;
  /** Increment of the increment/decrement accessibility actions, percent. */
  step?: number | undefined;
  /** The primary pane can collapse to nothing: drag past the minimum, the separator's activate action, or the collapse button. Activating again restores the last size. */
  collapsible?: boolean | undefined;
  /** Controlled collapsed state. Ignored unless `collapsible`. */
  collapsed?: boolean | undefined;
  /** Initial collapsed state when uncontrolled. */
  defaultCollapsed?: boolean | undefined;
  /** When set, the size and collapsed state are remembered under this key in a module-level memory map: survives remounts, not a restart. */
  persistKey?: string | undefined;
  /** Below this width of the splitter's own box a horizontal splitter stacks its panes and the separator is not rendered. A vertical splitter never stacks. */
  stackBelow?: SplitterStackBelow | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<SplitterOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root view. */
  ref?: React.Ref<ViewInstance> | undefined;
  /** Fired continuously while dragging and on each step action, with the primary size in percent (unrounded). */
  onSizeChange?: ((size: number) => void) | undefined;
  /** Fired with the final size once when a drag ends and after each step action that changed the size. */
  onSizeChangeEnd?: ((size: number) => void) | undefined;
  /** Fired when the primary pane collapses or restores. */
  onCollapseChange?: ((collapsed: boolean) => void) | undefined;
}

const COPY = {
  collapse: (label: string): string => `Collapse ${label}`,
  expand: (label: string): string => `Expand ${label}`,
  setMinimum: (label: string): string => `Minimum ${label}`,
  setMaximum: (label: string): string => `Maximum ${label}`,
  sizeText: (percent: number): string => `${percent}%`,
} as const;

const STACK_BELOW = {
  prose: 'layoutMaxWidthProse',
  content: 'layoutMaxWidthContent',
} as const;

/** Per-`persistKey` memory. No storage dependency is permitted in this package, so it
 * survives a remount but not an app restart. */
const persisted = new Map<string, { size: number; collapsed: boolean }>();

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function renderPane(content: React.ReactNode): React.ReactNode {
  return typeof content === 'string' || typeof content === 'number' ? <Text>{content}</Text> : content;
}

/**
 * Splitter — a separator that moves the boundary between two panes, reporting how much
 * of the container the primary pane holds.
 *
 * When to use: two regions compete for space and the right split depends on the task
 * (a navigation tree beside content, a list beside a detail view). Set sensible
 * `minSize`/`maxSize`, use `persistKey` so the choice sticks, and `collapsible` for
 * sidebars. Not for phone-only screens (it stacks below `stackBelow`) or static layout.
 *
 * A `View` row (or column): the primary pane at `flexBasis` percent, the separator
 * `View` carrying a `PanResponder` (as Slider's thumb — `panHandlers` on a `Pressable`
 * fight its own responder) with `accessibilityRole="adjustable"`, `accessibilityValue`
 * and `accessibilityActions` — increment/decrement by `step`, setMinimum/setMaximum
 * (Home/End) and, when `collapsible`, activate (Enter) — the gesture alternative; then
 * the secondary pane at `flex: 1`. The collapse `Button` (ghost, sm, iconOnly) is a
 * positioned sibling of the separator, placed from its measured position rather than a
 * child, because Android drops touches outside a parent's bounds. While collapsed the
 * pane is hidden from assistive tech and touch, and drag and the step actions do
 * nothing; only activate or the button restores. Collapse and restore animate over
 * `transition` (skipped under reduced motion); dragging and step actions resize
 * instantly and the separator colour switches instantly.
 *
 * Known platform limits: a `View` has no typed key handler, so hardware arrows, Home,
 * End and Enter do nothing (including on react-native-web) — the accessibility actions
 * and the collapse Button are the keyboard and screen-reader route; the separator is a
 * plain `View`, so it shows no keyboard focus ring (the Button has full focus
 * treatment); and F6 pane cycling has no native equivalent.
 */
export function Splitter({
  label,
  orientation = 'horizontal',
  primary,
  secondary,
  size,
  defaultSize = 30,
  minSize = 10,
  maxSize = 90,
  step = 2,
  collapsible = false,
  collapsed,
  defaultCollapsed = false,
  persistKey,
  stackBelow = 'prose',
  overrides,
  ref,
  onSizeChange,
  onSizeChangeEnd,
  onCollapseChange,
}: SplitterProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const horizontal = orientation === 'horizontal';

  const [internalSize, setInternalSize] = React.useState<number>(() => {
    const stored = persistKey !== undefined ? persisted.get(persistKey) : undefined;
    return stored?.size ?? defaultSize;
  });
  const [internalCollapsed, setInternalCollapsed] = React.useState<boolean>(() => {
    const stored = persistKey !== undefined ? persisted.get(persistKey) : undefined;
    return stored?.collapsed ?? defaultCollapsed;
  });
  const [dragging, setDragging] = React.useState(false);
  const [containerWidth, setContainerWidth] = React.useState<number | null>(null);
  const [separatorOffset, setSeparatorOffset] = React.useState(0);
  const [buttonExtent, setButtonExtent] = React.useState(0);

  const isCollapsed = collapsible && (collapsed ?? internalCollapsed);
  const baseSize = clamp(size ?? internalSize, minSize, maxSize);
  const effectiveSize = isCollapsed ? 0 : baseSize;

  React.useEffect(() => {
    if (__DEV__ && minSize >= maxSize) {
      console.warn(`Splitter: minSize (${minSize}) must be less than maxSize (${maxSize}).`);
    }
  }, [minSize, maxSize]);

  const persist = (nextSize: number, nextCollapsed: boolean): void => {
    if (persistKey !== undefined) {
      persisted.set(persistKey, { size: nextSize, collapsed: nextCollapsed });
    }
  };

  const applySize = (raw: number, commit: boolean): void => {
    const next = clamp(raw, minSize, maxSize);
    if (size === undefined) {
      setInternalSize(next);
    }
    persist(next, false);
    onSizeChange?.(next);
    if (commit) {
      onSizeChangeEnd?.(next);
    }
  };

  /** A step action is a complete interaction: it reports the change and the commit, and
   * a step already at a bound (setMaximum at `maxSize`) reports nothing. */
  const stepTo = (raw: number): void => {
    const next = clamp(raw, minSize, maxSize);
    if (next === baseSize) {
      return;
    }
    applySize(next, true);
  };

  const setCollapsedState = (next: boolean): void => {
    if (collapsed === undefined) {
      setInternalCollapsed(next);
    }
    // A collapsed pane keeps its size for restoring.
    persist(baseSize, next);
    onCollapseChange?.(next);
  };

  const toggleCollapse = (): void => {
    if (collapsible) {
      setCollapsedState(!isCollapsed);
    }
  };

  const handleSeparatorAction = (event: AccessibilityActionEvent): void => {
    const name = event.nativeEvent.actionName;
    if (name === 'activate') {
      toggleCollapse();
      return;
    }
    if (isCollapsed) {
      // While collapsed only activate or the collapse button does anything.
      return;
    }
    if (name === 'increment') {
      stepTo(baseSize + step);
    } else if (name === 'decrement') {
      if (collapsible && baseSize <= minSize) {
        // At the minimum the next shrink step collapses; crossing it from above clamps first.
        setCollapsedState(true);
      } else {
        stepTo(baseSize - step);
      }
    } else if (name === 'setMinimum') {
      // Home sets `minSize` and never collapses.
      stepTo(minSize);
    } else if (name === 'setMaximum') {
      stepTo(maxSize);
    }
  };

  // The PanResponder is created once; it reads the current render through these refs.
  const latest = React.useRef({
    baseSize,
    isCollapsed,
    horizontal,
    collapsible,
    minSize,
    maxSize,
    applySize,
    setCollapsedState,
    onSizeChangeEnd,
  });
  latest.current = {
    baseSize,
    isCollapsed,
    horizontal,
    collapsible,
    minSize,
    maxSize,
    applySize,
    setCollapsedState,
    onSizeChangeEnd,
  };
  const containerExtentRef = React.useRef(0);
  const dragRef = React.useRef({ active: false, moved: false, start: 0, last: 0 });

  /** A gesture that never moved the separator is not a drag and commits nothing; one the
   * platform cancels counts as a release, so both paths end here. */
  const endDrag = (): void => {
    const drag = dragRef.current;
    if (drag.moved) {
      // A drag commits once, carrying the last expanded size even when the gesture
      // collapsed the pane.
      latest.current.onSizeChangeEnd?.(clamp(drag.last, latest.current.minSize, latest.current.maxSize));
    }
    drag.active = false;
    drag.moved = false;
    setDragging(false);
  };

  const panResponder = React.useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => !latest.current.isCollapsed,
      onMoveShouldSetPanResponder: () => !latest.current.isCollapsed,
      onPanResponderGrant: () => {
        dragRef.current = {
          active: true,
          moved: false,
          start: latest.current.baseSize,
          last: latest.current.baseSize,
        };
        setDragging(true);
      },
      onPanResponderMove: (_event, gesture) => {
        const drag = dragRef.current;
        const extent = containerExtentRef.current;
        if (!drag.active || extent <= 0) {
          return;
        }
        const delta = latest.current.horizontal ? gesture.dx : gesture.dy;
        if (delta === 0 && !drag.moved) {
          // Still a press, not yet a drag: a stray tap on the separator stays silent.
          return;
        }
        drag.moved = true;
        const raw = drag.start + (delta / extent) * 100;
        if (latest.current.collapsible && raw < latest.current.minSize) {
          // Strictly past the minimum: collapse, and the rest of this gesture is ignored.
          // `last` keeps the last expanded size, which the release event carries.
          drag.active = false;
          setDragging(false);
          latest.current.setCollapsedState(true);
          return;
        }
        drag.last = raw;
        latest.current.applySize(raw, false);
      },
      onPanResponderRelease: endDrag,
      onPanResponderTerminate: endDrag,
    }),
  ).current;

  // Style bindings.
  const separatorSize = overrides?.separatorSize ? (resolveToken(t, overrides.separatorSize) as number) : t.space1;
  const separatorColor = overrides?.separatorColor ? (resolveToken(t, overrides.separatorColor) as string) : t.colorBorder;
  const handleSize = overrides?.handleSize ? (resolveToken(t, overrides.handleSize) as number) : t.space3;
  const gripLength = overrides?.gripLength ? (resolveToken(t, overrides.gripLength) as number) : t.space6;
  const gripRadius = overrides?.gripRadius ? (resolveToken(t, overrides.gripRadius) as number) : t.radiusFull;
  const collapseButtonOffset = overrides?.collapseButtonOffset
    ? (resolveToken(t, overrides.collapseButtonOffset) as number)
    : t.space2;
  const transitionDuration = overrides?.transition ? (resolveToken(t, overrides.transition) as number) : t.motionDurationFast;
  // Locked. `separatorHover` is unused on native; `focusRing`/`focusRingWidth` cannot be
  // drawn on the separator (a plain View has no focus events) — the collapse Button has them.
  const separatorActive = t.colorControlSelectedBackground;
  const grip = t.colorBorderStrong;
  const paneMinTarget = t.sizeTargetComfortable;
  const minTarget = t.sizeTargetMin;

  // Collapse and restore animate; a size change from dragging or a step is immediate.
  const sizeAnim = React.useRef(new Animated.Value(effectiveSize)).current;
  const previousCollapsed = React.useRef(isCollapsed);
  React.useEffect(() => {
    const toggled = previousCollapsed.current !== isCollapsed;
    previousCollapsed.current = isCollapsed;
    if (!toggled || reducedMotion) {
      sizeAnim.setValue(effectiveSize);
      return undefined;
    }
    const animation = Animated.timing(sizeAnim, {
      toValue: effectiveSize,
      duration: transitionDuration,
      easing: toEasing(t.motionEasingStandard),
      useNativeDriver: false,
    });
    animation.start();
    return () => animation.stop();
  }, [effectiveSize, isCollapsed, reducedMotion, sizeAnim, transitionDuration, t.motionEasingStandard]);

  const stackThreshold = stackBelow === 'never' ? null : t[STACK_BELOW[stackBelow]];
  // Unmeasured (first frame, test renderer) renders side by side.
  const stacked = horizontal && stackThreshold !== null && containerWidth !== null && containerWidth < stackThreshold;

  const handleContainerLayout = (event: LayoutChangeEvent): void => {
    const { width, height } = event.nativeEvent.layout;
    containerExtentRef.current = horizontal ? width : height;
    setContainerWidth(width);
  };

  const handleSeparatorLayout = (event: LayoutChangeEvent): void => {
    const { x, y } = event.nativeEvent.layout;
    setSeparatorOffset(horizontal ? x : y);
  };

  const handleButtonLayout = (event: LayoutChangeEvent): void => {
    const { width, height } = event.nativeEvent.layout;
    setButtonExtent(horizontal ? width : height);
  };

  const containerStyle: ViewStyle = { flex: 1, flexDirection: horizontal && !stacked ? 'row' : 'column' };

  const primaryPaneStyle: Animated.WithAnimatedValue<ViewStyle> = stacked
    ? {}
    : {
        flexBasis: sizeAnim.interpolate({ inputRange: [0, 100], outputRange: ['0%', '100%'] }),
        flexGrow: 0,
        flexShrink: isCollapsed ? 1 : 0,
        // The pane floor is dropped while collapsed so collapse reaches zero.
        minWidth: horizontal && !isCollapsed ? paneMinTarget : 0,
        minHeight: !horizontal && !isCollapsed ? paneMinTarget : 0,
        overflow: 'hidden',
      };

  const secondaryPaneStyle: ViewStyle = stacked
    ? {}
    : {
        flex: 1,
        minWidth: horizontal ? paneMinTarget : 0,
        minHeight: horizontal ? 0 : paneMinTarget,
      };

  const hitArea = Math.max(handleSize, minTarget);
  const hitExtra = Math.max(0, Math.ceil((hitArea - separatorSize) / 2));

  const separatorStyle: ViewStyle = {
    width: horizontal ? separatorSize : '100%',
    height: horizontal ? '100%' : separatorSize,
    backgroundColor: dragging ? separatorActive : separatorColor,
    zIndex: 1,
  };

  // The grab area overlaps both panes; on native `hitSlop` carries it, and on
  // react-native-web (which ignores `hitSlop`) the overflowing child View does.
  const handleStyle: ViewStyle = horizontal
    ? { position: 'absolute', top: 0, bottom: 0, left: -hitExtra, right: -hitExtra }
    : { position: 'absolute', left: 0, right: 0, top: -hitExtra, bottom: -hitExtra };

  const gripStyle: ViewStyle = {
    position: 'absolute',
    width: horizontal ? separatorSize : gripLength,
    height: horizontal ? gripLength : separatorSize,
    left: horizontal ? 0 : '50%',
    top: horizontal ? '50%' : 0,
    transform: horizontal ? [{ translateY: -gripLength / 2 }] : [{ translateX: -gripLength / 2 }],
    borderRadius: gripRadius,
    backgroundColor: grip,
  };

  // Centred across the separator; while collapsed the primary pane has no size, so the
  // button aligns to the secondary pane's start edge instead of hanging outside.
  const buttonCross = isCollapsed
    ? separatorOffset + separatorSize
    : separatorOffset + separatorSize / 2 - buttonExtent / 2;
  const collapseButtonStyle: ViewStyle = horizontal
    ? { position: 'absolute', top: collapseButtonOffset, left: buttonCross, zIndex: 1 }
    : { position: 'absolute', left: collapseButtonOffset, top: buttonCross, zIndex: 1 };

  const collapseIcon: IconName = horizontal
    ? isCollapsed
      ? 'chevron-right'
      : 'chevron-left'
    : isCollapsed
      ? 'chevron-down'
      : 'chevron-up';
  const toggleLabel = isCollapsed ? COPY.expand(label) : COPY.collapse(label);

  // increment/decrement are named by the system; the rest carry their own copy.
  const separatorActions = [
    { name: 'increment' },
    { name: 'decrement' },
    { name: 'setMinimum', label: COPY.setMinimum(label) },
    { name: 'setMaximum', label: COPY.setMaximum(label) },
    ...(collapsible ? [{ name: 'activate', label: toggleLabel }] : []),
  ];

  // Only the reported value rounds; the size events carry the unrounded number. The
  // minimum is 0 while collapsed so the reported value stays in range, while the
  // maximum stays `maxSize`.
  const reportedSize = Math.round(effectiveSize);
  const reportedMin = isCollapsed ? 0 : minSize;

  return (
    <View ref={ref} testID="Splitter" style={containerStyle} onLayout={handleContainerLayout}>
      <Animated.View
        testID="Splitter.primaryPane"
        style={primaryPaneStyle}
        accessibilityElementsHidden={isCollapsed && !stacked}
        importantForAccessibility={isCollapsed && !stacked ? 'no-hide-descendants' : 'auto'}
        pointerEvents={isCollapsed && !stacked ? 'none' : 'auto'}
      >
        {renderPane(primary)}
      </Animated.View>
      {stacked ? null : (
        <View
          testID="Splitter.separator"
          accessible
          focusable
          accessibilityRole="adjustable"
          accessibilityLabel={label}
          accessibilityValue={{
            min: reportedMin,
            max: maxSize,
            now: reportedSize,
            text: COPY.sizeText(reportedSize),
          }}
          // The aria-* aliases carry the same value. React Native merges them into
          // `accessibilityValue`; react-native-web has no such prop and forwards only these,
          // and role="slider" (its mapping of `adjustable`) requires aria-valuenow.
          aria-valuemin={reportedMin}
          aria-valuemax={maxSize}
          aria-valuenow={reportedSize}
          aria-valuetext={COPY.sizeText(reportedSize)}
          accessibilityActions={separatorActions}
          onAccessibilityAction={handleSeparatorAction}
          hitSlop={horizontal ? { left: hitExtra, right: hitExtra } : { top: hitExtra, bottom: hitExtra }}
          onLayout={handleSeparatorLayout}
          style={separatorStyle}
          {...panResponder.panHandlers}
        >
          <View testID="Splitter.handle" style={handleStyle} />
          <View pointerEvents="none" accessibilityElementsHidden importantForAccessibility="no" style={gripStyle} />
        </View>
      )}
      {stacked || !collapsible ? null : (
        <View testID="Splitter.collapseButton" style={collapseButtonStyle} onLayout={handleButtonLayout}>
          <Button
            label={toggleLabel}
            variant="ghost"
            size="sm"
            iconOnly
            // The Button discloses the primary pane, as `aria-expanded={!collapsed}` on web.
            expanded={!isCollapsed}
            leadingIcon={<Icon name={collapseIcon} color={t.colorActionGhostForeground} />}
            onPress={toggleCollapse}
          />
        </View>
      )}
      <View testID="Splitter.secondaryPane" style={secondaryPaneStyle}>
        {renderPane(secondary)}
      </View>
    </View>
  );
}

// packages/lit/src/Splitter.ts
import { LitElement, css, html, nothing, unsafeCSS, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { classMap } from 'lit/directives/class-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Button.js';
import './Icon.js';
import type { IconName } from './Icon.js';

export type SplitterOrientation = 'horizontal' | 'vertical';
export type SplitterStackBelow = 'prose' | 'content' | 'never';

/** Detail carried by the `size-change` and `size-change-end` CustomEvents. */
export interface SplitterSizeChangeDetail {
  size: number;
}

/** Detail carried by the `collapse-change` CustomEvent. */
export interface SplitterCollapseChangeDetail {
  collapsed: boolean;
}

/** copy.collapse */
const COPY_COLLAPSE = (label: string): string => `Collapse ${label}`;
/** copy.expand */
const COPY_EXPAND = (label: string): string => `Expand ${label}`;
/** copy.sizeText */
const COPY_SIZE_TEXT = (percent: number): string => `${percent}%`;

/** layout.maxWidth.prose / layout.maxWidth.content: `@container` conditions cannot read custom properties, so the
    built breakpoints are duplicated here as literals, and again in JS to drive the ARIA/interactivity switch a
    container query alone cannot express. literal-ok: breakpoint from layout.maxWidth.* */
const PROSE_BREAKPOINT_PX = 572;
const CONTENT_BREAKPOINT_PX = 960;

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
].join(',');

/** First focusable element among `elements` or their descendants, in order. */
function firstFocusable(elements: Element[]): HTMLElement | null {
  for (const el of elements) {
    if (!(el instanceof HTMLElement)) {
      continue;
    }
    if (el.matches(FOCUSABLE_SELECTOR)) {
      return el;
    }
    const nested = el.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
    if (nested) {
      return nested;
    }
  }
  return null;
}

let idCounter = 0;
function nextSplitterId(): string {
  idCounter += 1;
  return `ds-splitter-${idCounter}`;
}

/** Overridable style hooks; see the `overrides` property. `separatorHover`, `separatorActive`, `grip`, `minTarget`,
    `focusRing` and `focusRingWidth` are locked and excluded. */
export type SplitterOverridableBinding =
  | 'separatorSize'
  | 'separatorColor'
  | 'handleSize'
  | 'gripLength'
  | 'collapseButtonOffset'
  | 'paneMinTarget'
  | 'transition';

const HOOKS: Record<SplitterOverridableBinding, string> = {
  separatorSize: '--ds-splitter-separator-size',
  separatorColor: '--ds-splitter-separator-color',
  handleSize: '--ds-splitter-handle-size',
  gripLength: '--ds-splitter-grip-length',
  collapseButtonOffset: '--ds-splitter-collapse-button-offset',
  paneMinTarget: '--ds-splitter-pane-min-target',
  transition: '--ds-splitter-transition',
};

/**
 * `<ds-splitter>` — Splitter (category: layout, APG pattern: windowsplitter).
 *
 * `<ds-splitter label="Sidebar width" collapsible persist-key="app-sidebar">` renders
 * a CSS grid of a primary pane (`slot="primary"`), a `role="separator"` divider and
 * a secondary pane (`slot="secondary"`) in its shadow root; the primary pane's size
 * is a host custom property in percent. Pointer Events with `setPointerCapture` on
 * the separator drive dragging; the full keyboard table (arrows, Home/End, Enter,
 * F6) is implemented on it. Dispatches composed `size-change` (continuously),
 * `size-change-end` (once, at drag end) and `collapse-change` CustomEvents. Below
 * `stackBelow` a horizontal splitter's `@container` query stacks the panes and a
 * `ResizeObserver` on the host retires the separator's `role`/`tabindex` to match.
 *
 * ## When to use
 *
 * Use a Splitter when two regions compete for space and the right split depends on
 * the task: a navigation tree beside content, a list beside a detail view. Make the
 * primary pane the one whose size matters, set sensible `minSize`/`maxSize`, and use
 * `persistKey` so the choice sticks. Use `collapsible` for sidebars.
 *
 * @fires size-change - Fired continuously while dragging and on each key press, with `{ size }` (percent) in `detail`.
 * @fires size-change-end - Fired once when a drag ends, with `{ size }` in `detail`.
 * @fires collapse-change - Fired when the primary pane collapses or restores, with `{ collapsed }` in `detail`.
 * @slot primary - The first pane, start or top (anatomy: primaryPane).
 * @slot secondary - The second pane, which takes the remaining space (anatomy: secondaryPane).
 * @csspart container - The grid of primary pane, separator and secondary pane (anatomy: container).
 * @csspart primaryPane - The primary pane wrapper (anatomy: primaryPane).
 * @csspart secondaryPane - The secondary pane wrapper (anatomy: secondaryPane).
 * @csspart separator - The `role="separator"` divider (anatomy: separator).
 * @csspart handle - The pointer grab area, wider than the visible line (anatomy: handle).
 * @csspart collapseButton - The composed `<ds-button>` that collapses/restores the primary pane (anatomy: collapseButton).
 */
@customElement('ds-splitter')
export class DsSplitter extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      container-type: inline-size;
      /* Internal state channel (not an override hook): the primary pane's live size, in percent. */
      --ds-splitter-primary-size: 30%;
      --ds-splitter-separator-size: var(--space-1);
      --ds-splitter-separator-color: var(--color-border);
      --ds-splitter-handle-size: var(--space-3);
      --ds-splitter-grip-length: var(--space-6);
      --ds-splitter-collapse-button-offset: var(--space-2);
      --ds-splitter-pane-min-target: var(--size-target-comfortable);
      --ds-splitter-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    .container {
      display: grid;
      block-size: 100%;
      inline-size: 100%;
      grid-template-columns: var(--ds-splitter-primary-size) var(--ds-splitter-separator-size) 1fr;
      grid-template-rows: 1fr;
    }

    :host([orientation='vertical']) .container {
      grid-template-columns: 1fr;
      grid-template-rows: var(--ds-splitter-primary-size) var(--ds-splitter-separator-size) 1fr;
    }

    .pane {
      overflow: auto;
    }

    :host([orientation='horizontal']) .pane {
      min-inline-size: var(--ds-splitter-pane-min-target);
      min-block-size: 0;
    }

    :host([orientation='vertical']) .pane {
      min-block-size: var(--ds-splitter-pane-min-target);
      min-inline-size: 0;
    }

    /* A collapsed primary pane genuinely reaches zero; the pane-min-target floor does not apply to it. */
    .primary-pane.is-collapsed {
      min-inline-size: 0;
      min-block-size: 0;
      overflow: hidden;
    }

    .separator {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      background: var(--ds-splitter-separator-color);
      transition: background var(--ds-splitter-transition) var(--motion-easing-standard);
      touch-action: none;
    }

    @media (prefers-reduced-motion: reduce) {
      .separator {
        transition: none;
      }
    }

    :host([orientation='horizontal']) .separator {
      cursor: col-resize;
      inline-size: var(--ds-splitter-separator-size);
      block-size: 100%;
    }

    :host([orientation='vertical']) .separator {
      cursor: row-resize;
      block-size: var(--ds-splitter-separator-size);
      inline-size: 100%;
    }

    /* separatorHover: color.border.strong, locked */
    .separator:hover {
      background: var(--color-border-strong);
    }

    /* separatorActive: color.control.selectedBackground, locked; while dragging or focused */
    .separator.is-active,
    .separator:focus-visible {
      background: var(--color-control-selected-background);
    }

    /* focusRing / focusRingWidth: color.border.focus / border.width.focus, both locked */
    .separator:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* handleSize: pointer grab area, centered on the separator, overlapping both panes.
       minTarget: size.target.min hit-area floor, locked. */
    .handle {
      position: absolute;
      pointer-events: none;
    }

    :host([orientation='horizontal']) .handle {
      inset-block: 0;
      inset-inline-start: 50%;
      inline-size: max(var(--ds-splitter-handle-size), var(--size-target-min));
      transform: translateX(-50%);
    }

    :host([orientation='vertical']) .handle {
      inset-inline: 0;
      inset-block-start: 50%;
      block-size: max(var(--ds-splitter-handle-size), var(--size-target-min));
      transform: translateY(-50%);
    }

    /* grip: color.border.strong, locked */
    .grip {
      position: absolute;
      inset-block-start: 50%;
      inset-inline-start: 50%;
      transform: translate(-50%, -50%);
      background: var(--color-border-strong);
      border-radius: var(--radius-full);
    }

    :host([orientation='horizontal']) .grip {
      inline-size: var(--ds-splitter-separator-size);
      block-size: var(--ds-splitter-grip-length);
    }

    :host([orientation='vertical']) .grip {
      block-size: var(--ds-splitter-separator-size);
      inline-size: var(--ds-splitter-grip-length);
    }

    .collapse-button {
      position: absolute;
      pointer-events: auto;
    }

    :host([orientation='horizontal']) .collapse-button {
      inset-inline-start: 50%;
      inset-block-start: var(--ds-splitter-collapse-button-offset);
      transform: translateX(-50%);
    }

    :host([orientation='vertical']) .collapse-button {
      inset-block-start: 50%;
      inset-inline-start: var(--ds-splitter-collapse-button-offset);
      transform: translateY(-50%);
    }

    @container (max-width: ${unsafeCSS(CONTENT_BREAKPOINT_PX)}px) {
      :host([orientation='horizontal'][stack-below='content']) .container {
        grid-template-columns: 1fr;
        grid-template-rows: auto var(--ds-splitter-separator-size) auto;
      }
      :host([orientation='horizontal'][stack-below='content']) .separator {
        cursor: default;
        inline-size: 100%;
        block-size: var(--ds-splitter-separator-size);
      }
      :host([orientation='horizontal'][stack-below='content']) .handle,
      :host([orientation='horizontal'][stack-below='content']) .collapse-button {
        display: none;
      }
      :host([orientation='horizontal'][stack-below='content']) .pane {
        min-inline-size: 0;
      }
    }

    @container (max-width: ${unsafeCSS(PROSE_BREAKPOINT_PX)}px) {
      :host([orientation='horizontal'][stack-below='prose']) .container {
        grid-template-columns: 1fr;
        grid-template-rows: auto var(--ds-splitter-separator-size) auto;
      }
      :host([orientation='horizontal'][stack-below='prose']) .separator {
        cursor: default;
        inline-size: 100%;
        block-size: var(--ds-splitter-separator-size);
      }
      :host([orientation='horizontal'][stack-below='prose']) .handle,
      :host([orientation='horizontal'][stack-below='prose']) .collapse-button {
        display: none;
      }
      :host([orientation='horizontal'][stack-below='prose']) .pane {
        min-inline-size: 0;
      }
    }
  `;

  /** What the divider resizes ("Sidebar width", "Preview height"). The separator's accessible name. */
  @property() label = '';

  /** `horizontal` places panes side by side (the separator is vertical); `vertical` stacks them. */
  @property({ reflect: true }) orientation: SplitterOrientation = 'horizontal';

  /** Controlled size of the primary pane, percent (0-100). Omit for an uncontrolled splitter. */
  @property({ type: Number }) size?: number;

  /** Initial primary size, percent, for an uncontrolled splitter. */
  @property({ type: Number, attribute: 'default-size' }) defaultSize = 30;

  /** Smallest primary size, percent. Below this the pane collapses instead, when `collapsible`. */
  @property({ type: Number, attribute: 'min-size' }) minSize = 10;

  /** Largest primary size, percent. */
  @property({ type: Number, attribute: 'max-size' }) maxSize = 90;

  /** Arrow-key increment, percent. */
  @property({ type: Number }) step = 2;

  /** The primary pane can collapse to nothing: drag past `minSize`, press Enter on the separator, or use the
      collapse button. Enter again (or the button) restores the last size. */
  @property({ type: Boolean, reflect: true }) collapsible = false;

  /** Collapsed state. Two-way: set initially to start collapsed, or read/set at any time; the component keeps it
      current as the user drags, presses Enter, or uses the collapse button. */
  @property({ type: Boolean, reflect: true }) collapsed = false;

  /** When set, the size and collapsed state are remembered in `localStorage` under this key across mounts. */
  @property({ attribute: 'persist-key' }) persistKey?: string;

  /** Below this layout width a horizontal splitter stacks its panes and the separator becomes inert. */
  @property({ reflect: true, attribute: 'stack-below' }) stackBelow: SplitterStackBelow = 'prose';

  /** Per-instance style overrides: `{ separatorSize: 'space.2' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<SplitterOverridableBinding, TokenRef>>;

  /** Uncontrolled size (seeded from `defaultSize`, or restored via `persistKey`, when nothing else is set). */
  @state() private internalSize?: number;

  /** Active while the pointer is dragging the separator (drives `separatorActive`). */
  @state() private dragging = false;

  /** `true` below `stackBelow`, on a horizontal splitter: the separator loses its `tabindex` and `role`. */
  @state() private stacked = false;

  private readonly instanceId = nextSplitterId();

  private resizeObserver?: ResizeObserver;

  @query('.container') private readonly containerEl!: HTMLDivElement;
  @query('.separator') private readonly separatorEl!: HTMLDivElement;
  @query('.primary-pane') private readonly primaryPaneEl!: HTMLDivElement;
  @query('.secondary-pane') private readonly secondaryPaneEl!: HTMLDivElement;
  @query('slot[name="primary"]') private readonly primarySlotEl?: HTMLSlotElement;
  @query('slot[name="secondary"]') private readonly secondarySlotEl?: HTMLSlotElement;

  /** The current primary size (percent), resolved from `size`, `internalSize`, then `defaultSize`, clamped. */
  private get currentSize(): number {
    const raw = this.size ?? this.internalSize ?? this.defaultSize;
    return this.clamp(raw);
  }

  /** The displayed/reported size: 0 while collapsed, else `currentSize`. */
  private get effectiveSize(): number {
    return this.collapsed ? 0 : this.currentSize;
  }

  private get primaryPaneId(): string {
    return `${this.instanceId}-primary`;
  }

  private clamp(value: number): number {
    return Math.min(this.maxSize, Math.max(this.minSize, value));
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Splitter');
    this.addEventListener('keydown', this.handleHostKeydown);
    this.loadPersisted();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('keydown', this.handleHostKeydown);
    this.resizeObserver?.disconnect();
  }

  protected override firstUpdated(): void {
    this.resizeObserver = new ResizeObserver(() => this.updateStacked());
    this.resizeObserver.observe(this);
    this.updateStacked();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('orientation') || changed.has('stackBelow')) {
      this.updateStacked();
    }
    this.style.setProperty('--ds-splitter-primary-size', `${this.effectiveSize}%`);
    this.warnInDev(changed);
  }

  protected override render() {
    const horizontal = this.orientation === 'horizontal';
    const size = this.effectiveSize;
    const collapseLabel = this.collapsed ? COPY_EXPAND(this.label) : COPY_COLLAPSE(this.label);
    const chevronName: IconName = horizontal
      ? this.collapsed
        ? 'chevron-right'
        : 'chevron-left'
      : this.collapsed
        ? 'chevron-down'
        : 'chevron-up';

    return html`
      <div class="container" part="container">
        <div
          class=${classMap({ pane: true, 'primary-pane': true, 'is-collapsed': this.collapsed })}
          part="primaryPane"
          id=${this.primaryPaneId}
          tabindex="-1"
          ?inert=${this.collapsed}
        >
          <slot name="primary"></slot>
        </div>
        <div
          class=${classMap({ separator: true, 'is-active': this.dragging })}
          part="separator"
          role=${this.stacked ? 'presentation' : 'separator'}
          tabindex=${ifDefined(this.stacked ? undefined : 0)}
          aria-orientation=${ifDefined(this.stacked ? undefined : horizontal ? 'vertical' : 'horizontal')}
          aria-valuenow=${ifDefined(this.stacked ? undefined : Math.round(size))}
          aria-valuemin=${ifDefined(this.stacked ? undefined : this.minSize)}
          aria-valuemax=${ifDefined(this.stacked ? undefined : this.maxSize)}
          aria-valuetext=${ifDefined(this.stacked ? undefined : COPY_SIZE_TEXT(Math.round(size)))}
          aria-label=${ifDefined(this.stacked ? undefined : this.label)}
          aria-controls=${ifDefined(this.stacked ? undefined : this.primaryPaneId)}
          @pointerdown=${this.handleSeparatorPointerDown}
          @pointermove=${this.handleSeparatorPointerMove}
          @pointerup=${this.handleSeparatorPointerUp}
          @pointercancel=${this.handleSeparatorPointerUp}
          @keydown=${this.handleSeparatorKeydown}
        >
          <div class="handle" part="handle">
            <div class="grip" aria-hidden="true"></div>
          </div>
          ${this.collapsible
            ? html`<ds-button
                class="collapse-button"
                part="collapseButton"
                variant="ghost"
                size="sm"
                icon-only
                label=${collapseLabel}
                @press=${this.handleCollapseButtonPress}
              >
                <ds-icon slot="leading-icon" name=${chevronName}></ds-icon>
              </ds-button>`
            : nothing}
        </div>
        <div class="pane secondary-pane" part="secondaryPane" tabindex="-1">
          <slot name="secondary"></slot>
        </div>
      </div>
    `;
  }

  private readonly handleSeparatorPointerDown = (event: PointerEvent): void => {
    if (this.stacked) {
      return;
    }
    if ((event.target as HTMLElement).closest('.collapse-button')) {
      return;
    }
    event.preventDefault();
    this.dragging = true;
    this.separatorEl.setPointerCapture(event.pointerId);
    this.updateFromPointer(event);
  };

  private readonly handleSeparatorPointerMove = (event: PointerEvent): void => {
    if (!this.dragging) {
      return;
    }
    this.updateFromPointer(event);
  };

  private readonly handleSeparatorPointerUp = (event: PointerEvent): void => {
    if (!this.dragging) {
      return;
    }
    if (this.separatorEl.hasPointerCapture(event.pointerId)) {
      this.separatorEl.releasePointerCapture(event.pointerId);
    }
    this.dragging = false;
    this.dispatchSizeChangeEnd();
    this.persist();
  };

  private updateFromPointer(event: PointerEvent): void {
    const rect = this.containerEl.getBoundingClientRect();
    const ratio =
      this.orientation === 'horizontal'
        ? rect.width === 0
          ? 0
          : (event.clientX - rect.left) / rect.width
        : rect.height === 0
          ? 0
          : (event.clientY - rect.top) / rect.height;
    const raw = Math.min(100, Math.max(0, ratio * 100));
    if (this.collapsible && raw < this.minSize) {
      this.commitSize(this.minSize);
      this.setCollapsed(true);
    } else {
      this.setCollapsed(false);
      this.commitSize(this.clamp(raw));
    }
    this.dispatchSizeChange();
  }

  private handleSeparatorKeydown(event: KeyboardEvent): void {
    if (this.stacked) {
      return;
    }
    const horizontal = this.orientation === 'horizontal';
    const growKey = horizontal ? 'ArrowRight' : 'ArrowDown';
    const shrinkKey = horizontal ? 'ArrowLeft' : 'ArrowUp';
    switch (event.key) {
      case growKey:
        event.preventDefault();
        this.adjustSize(this.step);
        break;
      case shrinkKey:
        event.preventDefault();
        this.adjustSize(-this.step);
        break;
      case 'Home':
        event.preventDefault();
        this.setCollapsed(false);
        this.commitSize(this.minSize);
        this.dispatchSizeChange();
        this.persist();
        break;
      case 'End':
        event.preventDefault();
        this.setCollapsed(false);
        this.commitSize(this.maxSize);
        this.dispatchSizeChange();
        this.persist();
        break;
      case 'Enter':
        if (this.collapsible) {
          event.preventDefault();
          this.toggleCollapsed();
        }
        break;
      default:
        break;
    }
  }

  private readonly handleHostKeydown = (event: KeyboardEvent): void => {
    if (event.key !== 'F6' || this.stacked) {
      return;
    }
    event.preventDefault();
    this.cycleFocus();
  };

  private handleCollapseButtonPress(event: Event): void {
    event.stopPropagation();
    this.toggleCollapsed();
  }

  private adjustSize(delta: number): void {
    const base = this.collapsed ? 0 : this.currentSize;
    this.setCollapsed(false);
    this.commitSize(this.clamp(base + delta));
    this.dispatchSizeChange();
    this.persist();
  }

  private toggleCollapsed(): void {
    this.setCollapsed(!this.collapsed);
    this.persist();
  }

  private commitSize(next: number): void {
    if (this.size !== undefined) {
      this.size = next;
    } else {
      this.internalSize = next;
    }
  }

  private setCollapsed(next: boolean): void {
    if (this.collapsed === next) {
      return;
    }
    this.collapsed = next;
    this.dispatchEvent(
      new CustomEvent<SplitterCollapseChangeDetail>('collapse-change', {
        detail: { collapsed: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private dispatchSizeChange(): void {
    this.dispatchEvent(
      new CustomEvent<SplitterSizeChangeDetail>('size-change', {
        detail: { size: this.effectiveSize },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private dispatchSizeChangeEnd(): void {
    this.dispatchEvent(
      new CustomEvent<SplitterSizeChangeDetail>('size-change-end', {
        detail: { size: this.effectiveSize },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private zoneIndexOf(active: Element | null): number {
    if (!active) {
      return -1;
    }
    if (active === this.separatorEl) {
      return 1;
    }
    const primaryEls = this.primarySlotEl?.assignedElements({ flatten: true }) ?? [];
    if (primaryEls.some((el) => el === active || el.contains(active))) {
      return 0;
    }
    const secondaryEls = this.secondarySlotEl?.assignedElements({ flatten: true }) ?? [];
    if (secondaryEls.some((el) => el === active || el.contains(active))) {
      return 2;
    }
    return -1;
  }

  private focusZone(index: number): void {
    if (index === 1) {
      this.separatorEl?.focus();
      return;
    }
    const slotEl = index === 0 ? this.primarySlotEl : this.secondarySlotEl;
    const paneEl = index === 0 ? this.primaryPaneEl : this.secondaryPaneEl;
    const assigned = slotEl?.assignedElements({ flatten: true }) ?? [];
    const target = firstFocusable(assigned);
    (target ?? paneEl)?.focus();
  }

  /** F6: cycles focus through primary content, the separator, and secondary content (APG convenience). */
  private cycleFocus(): void {
    const active = (this.shadowRoot?.activeElement as Element | null) ?? document.activeElement;
    const current = this.zoneIndexOf(active);
    this.focusZone((current + 1) % 3);
  }

  private updateStacked(): void {
    if (this.orientation !== 'horizontal' || this.stackBelow === 'never') {
      this.stacked = false;
      return;
    }
    const breakpoint = this.stackBelow === 'prose' ? PROSE_BREAKPOINT_PX : CONTENT_BREAKPOINT_PX;
    this.stacked = this.getBoundingClientRect().width < breakpoint;
  }

  private get storageKey(): string {
    return `ds-splitter:${this.persistKey}`;
  }

  private loadPersisted(): void {
    if (!this.persistKey) {
      return;
    }
    try {
      const raw = localStorage.getItem(this.storageKey);
      if (!raw) {
        return;
      }
      const parsed = JSON.parse(raw) as { size?: number; collapsed?: boolean };
      if (this.size === undefined && typeof parsed.size === 'number') {
        this.internalSize = parsed.size;
      }
      if (typeof parsed.collapsed === 'boolean') {
        this.collapsed = parsed.collapsed;
      }
    } catch {
      /* localStorage unavailable (SSR, privacy mode); the splitter just keeps its default. */
    }
  }

  private persist(): void {
    if (!this.persistKey) {
      return;
    }
    try {
      localStorage.setItem(this.storageKey, JSON.stringify({ size: this.currentSize, collapsed: this.collapsed }));
    } catch {
      /* localStorage unavailable (SSR, privacy mode); ignore. */
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as SplitterOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(changed: PropertyValues): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if ((changed.has('minSize') || changed.has('maxSize')) && !(this.maxSize > this.minSize)) {
      console.warn(`<ds-splitter> needs maxSize (${this.maxSize}) greater than minSize (${this.minSize}).`, this);
    }
    if (changed.has('defaultSize') && (this.defaultSize < this.minSize || this.defaultSize > this.maxSize)) {
      console.warn(`<ds-splitter> defaultSize (${this.defaultSize}) is outside minSize/maxSize.`, this);
    }
    if (changed.has('collapsed') && this.collapsed && !this.collapsible) {
      console.warn('<ds-splitter collapsed> has no effect without `collapsible`.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-splitter': DsSplitter;
  }
}
