// packages/react/src/Splitter.tsx
import {
  forwardRef,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { Icon } from './Icon';
import './Splitter.css';

export type SplitterOrientation = 'horizontal' | 'vertical';
export type SplitterStackBelow = 'prose' | 'content' | 'never';

/** copy.* — used verbatim; `{label}`/`{percent}` are replaced. */
const COPY = {
  collapse: 'Collapse {label}',
  expand: 'Expand {label}',
  sizeText: '{percent}%',
};

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type SplitterOverridableBinding =
  | 'separatorSize'
  | 'separatorColor'
  | 'handleSize'
  | 'gripLength'
  | 'collapseButtonOffset'
  | 'paneMinTarget'
  | 'transition';

const OVERRIDE_HOOK: Record<SplitterOverridableBinding, string> = {
  separatorSize: '--ds-splitter-separator-size',
  separatorColor: '--ds-splitter-separator-color',
  handleSize: '--ds-splitter-handle-size',
  gripLength: '--ds-splitter-grip-length',
  collapseButtonOffset: '--ds-splitter-collapse-button-offset',
  paneMinTarget: '--ds-splitter-pane-min-target',
  transition: '--ds-splitter-transition',
};

function overridesToStyle(overrides: Partial<Record<SplitterOverridableBinding, TokenRef>>): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as SplitterOverridableBinding[]) {
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return style as CSSProperties;
}

/* Only declared when the bundler defines it; never assumed. */
declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[contenteditable]:not([contenteditable="false"])',
  '[tabindex]:not([tabindex="-1"])',
].join(',');

const BREAKPOINT_VAR: Record<Exclude<SplitterStackBelow, 'never'>, string> = {
  prose: '--layout-max-width-prose',
  content: '--layout-max-width-content',
};

function readPersisted(key: string | undefined): { size?: number; collapsed?: boolean } | null {
  if (!key || typeof window === 'undefined') return null;
  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as { size?: number; collapsed?: boolean }) : null;
  } catch {
    return null;
  }
}

function writePersisted(key: string | undefined, value: { size: number; collapsed: boolean }): void {
  if (!key || typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* storage unavailable (private mode, quota) — the size just does not stick */
  }
}

export interface SplitterProps extends Omit<ComponentPropsWithoutRef<'div'>, 'children'> {
  /** What the divider resizes ("Sidebar width", "Preview height"). The separator's accessible name. */
  label: string;
  /** `horizontal` places panes side by side (the separator is vertical); `vertical` stacks them. */
  orientation?: SplitterOrientation;
  /** The first pane (start or top). Its size is what the separator controls and reports. */
  primary: ReactNode;
  /** The second pane, which takes the remaining space. */
  secondary: ReactNode;
  /** Controlled size of the primary pane as a percentage of the container (0–100). */
  size?: number;
  /** Initial primary size, percent. */
  defaultSize?: number;
  /** Smallest primary size, percent. Below this the pane collapses instead, when `collapsible`. */
  minSize?: number;
  /** Largest primary size, percent. */
  maxSize?: number;
  /** Arrow-key increment, percent. */
  step?: number;
  /**
   * The primary pane can collapse to nothing: drag past the minimum, press Enter on the
   * separator, or use the collapse button. Enter again restores the last size.
   */
  collapsible?: boolean;
  /** Controlled collapsed state. */
  collapsed?: boolean;
  /** When set, the size is remembered per user under this key (localStorage) so a sidebar stays where it was left. */
  persistKey?: string;
  /**
   * Below this layout width a horizontal splitter stacks its panes and the separator becomes
   * inert (a phone has no room for two panes side by side).
   */
  stackBelow?: SplitterStackBelow;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<SplitterOverridableBinding, TokenRef>>;
  /** Fired continuously while dragging and on each key press, with the primary size in percent. */
  onSizeChange?: (size: number) => void;
  /** Fired once when a drag ends, with the final size. */
  onSizeChangeEnd?: (size: number) => void;
  /** Fired when the primary pane collapses or restores. */
  onCollapseChange?: (collapsed: boolean) => void;
}

/**
 * Splitter — Design Schema, category: layout.
 *
 * When to use:
 * Use a Splitter when two regions compete for space and the right split depends on the task: a
 * navigation tree beside content, a list beside a detail view, a code editor beside its output, a
 * map beside results. Make the primary pane the one whose size matters (the sidebar), set
 * sensible `minSize`/`maxSize`, and use `persistKey` so the choice sticks. Use `collapsible` for
 * sidebars.
 */
export const Splitter = forwardRef<HTMLDivElement, SplitterProps>(function Splitter(
  {
    label,
    orientation = 'horizontal',
    primary,
    secondary,
    size,
    defaultSize = 30,
    minSize = 10,
    maxSize = 90,
    step = 2,
    collapsible = false,
    collapsed,
    persistKey,
    stackBelow = 'prose',
    overrides,
    onSizeChange,
    onSizeChangeEnd,
    onCollapseChange,
    id: idProp,
    className,
    style,
    onKeyDown,
    ...rest
  },
  ref,
) {
  const generatedId = useId();
  const id = idProp ?? `ds-splitter${generatedId}`;
  const primaryId = `${id}-primary`;
  const secondaryId = `${id}-secondary`;

  const containerRef = useRef<HTMLDivElement | null>(null);
  const primaryRef = useRef<HTMLDivElement | null>(null);
  const separatorRef = useRef<HTMLDivElement | null>(null);
  const secondaryRef = useRef<HTMLDivElement | null>(null);

  if (isDev && !label) {
    console.warn('Splitter: `label` is required and becomes the separator’s accessible name.');
  }

  const isControlled = size !== undefined;
  const [internalSize, setInternalSize] = useState<number>(() => readPersisted(persistKey)?.size ?? defaultSize);
  const current = isControlled ? (size as number) : internalSize;
  const latestSizeRef = useRef(current);
  latestSizeRef.current = current;

  const isCollapsedControlled = collapsed !== undefined;
  const [internalCollapsed, setInternalCollapsed] = useState<boolean>(() => readPersisted(persistKey)?.collapsed ?? false);
  const collapsedState = isCollapsedControlled ? (collapsed as boolean) : internalCollapsed;
  const lastSizeRef = useRef(current);

  // The size stacking checks against the splitter's own inline size, not the viewport — this is a
  // real container query, not a page-layout breakpoint (see SidePanel's `persistent`).
  const [isStacked, setIsStacked] = useState(false);
  useEffect(() => {
    if (orientation !== 'horizontal' || stackBelow === 'never') {
      setIsStacked(false);
      return undefined;
    }
    const el = containerRef.current;
    if (!el || typeof ResizeObserver === 'undefined') return undefined;
    // literal-ok: breakpoint value read from the token custom property at runtime, not a literal.
    const raw = getComputedStyle(document.documentElement).getPropertyValue(BREAKPOINT_VAR[stackBelow]).trim();
    const breakpoint = parseFloat(raw) || 0;
    const observer = new ResizeObserver((entries) => {
      const width = entries[0]?.contentRect.width ?? el.getBoundingClientRect().width;
      setIsStacked(width < breakpoint);
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, [orientation, stackBelow]);

  const effectiveCollapsed = collapsedState && !isStacked;

  useLayoutEffect(() => {
    const node = primaryRef.current;
    if (node) node.inert = effectiveCollapsed;
  }, [effectiveCollapsed]);

  useEffect(() => {
    writePersisted(persistKey, { size: current, collapsed: collapsedState });
  }, [persistKey, current, collapsedState]);

  function clamp(value: number): number {
    return Math.min(Math.max(value, minSize), maxSize);
  }

  function commitSize(next: number): void {
    const clamped = clamp(next);
    if (!isControlled) setInternalSize(clamped);
    latestSizeRef.current = clamped;
    onSizeChange?.(clamped);
  }

  function setCollapsed(next: boolean): void {
    if (!isCollapsedControlled) setInternalCollapsed(next);
    onCollapseChange?.(next);
  }

  function collapse(): void {
    if (collapsedState) return;
    lastSizeRef.current = current;
    setCollapsed(true);
  }

  function restore(): void {
    if (!collapsedState) return;
    setCollapsed(false);
    commitSize(lastSizeRef.current);
  }

  function toggleCollapse(): void {
    if (collapsedState) restore();
    else collapse();
  }

  function percentFromPoint(clientX: number, clientY: number): number {
    const el = containerRef.current;
    if (!el) return current;
    const rect = el.getBoundingClientRect();
    if (orientation === 'horizontal') {
      const rtl = getComputedStyle(el).direction === 'rtl';
      const ratio = rect.width === 0 ? 0 : (clientX - rect.left) / rect.width;
      return Math.min(Math.max(rtl ? 1 - ratio : ratio, 0), 1) * 100;
    }
    const ratio = rect.height === 0 ? 0 : (clientY - rect.top) / rect.height;
    return Math.min(Math.max(ratio, 0), 1) * 100;
  }

  const draggingRef = useRef(false);
  const [isDragging, setIsDragging] = useState(false);

  const handleSeparatorPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (isStacked || event.button !== 0) return;
    if ((event.target as HTMLElement).closest('button')) return;
    event.preventDefault();
    draggingRef.current = true;
    setIsDragging(true);
    event.currentTarget.setPointerCapture(event.pointerId);
  };

  const endDrag = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!draggingRef.current) return;
    draggingRef.current = false;
    setIsDragging(false);
    if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId);
    onSizeChangeEnd?.(latestSizeRef.current);
  };

  const handleSeparatorPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!draggingRef.current || effectiveCollapsed) return;
    const raw = percentFromPoint(event.clientX, event.clientY);
    if (collapsible && raw < minSize) {
      draggingRef.current = false;
      setIsDragging(false);
      if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId);
      collapse();
      return;
    }
    commitSize(raw);
  };

  const handleSeparatorPointerUp = (event: ReactPointerEvent<HTMLDivElement>) => endDrag(event);
  const handleSeparatorPointerCancel = (event: ReactPointerEvent<HTMLDivElement>) => endDrag(event);

  const keyChangedRef = useRef(false);

  const handleSeparatorKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (isStacked || event.target !== event.currentTarget) return;
    if (effectiveCollapsed) {
      if (event.key === 'Enter' && collapsible) {
        event.preventDefault();
        restore();
      }
      return;
    }
    const growKey = orientation === 'horizontal' ? 'ArrowRight' : 'ArrowDown';
    const shrinkKey = orientation === 'horizontal' ? 'ArrowLeft' : 'ArrowUp';
    switch (event.key) {
      case growKey:
        event.preventDefault();
        commitSize(current + step);
        keyChangedRef.current = true;
        break;
      case shrinkKey:
        event.preventDefault();
        commitSize(current - step);
        keyChangedRef.current = true;
        break;
      case 'Home':
        event.preventDefault();
        commitSize(minSize);
        keyChangedRef.current = true;
        break;
      case 'End':
        event.preventDefault();
        commitSize(maxSize);
        keyChangedRef.current = true;
        break;
      case 'Enter':
        if (collapsible) {
          event.preventDefault();
          collapse();
        }
        break;
      default:
        break;
    }
  };

  const handleSeparatorKeyUp = () => {
    if (keyChangedRef.current) {
      keyChangedRef.current = false;
      onSizeChangeEnd?.(latestSizeRef.current);
    }
  };

  // F6: the APG convenience for cycling focus between the two panes and the separator, regardless
  // of which of the three currently holds focus.
  const handleContainerKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    onKeyDown?.(event);
    if (event.key !== 'F6' || isStacked) return;
    const active = document.activeElement;
    const regions = [primaryRef, separatorRef, secondaryRef];
    const activeIndex = regions.findIndex((r) => r.current === active || (r.current?.contains(active) ?? false));
    const nextRegion = regions[activeIndex === -1 ? 0 : (activeIndex + 1) % regions.length].current;
    if (!nextRegion) return;
    event.preventDefault();
    const focusable = nextRegion.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
    (focusable ?? nextRegion).focus();
  };

  const handleCollapseButtonClick = () => toggleCollapse();

  const setContainerRef = (node: HTMLDivElement | null) => {
    containerRef.current = node;
    if (typeof ref === 'function') ref(node);
    else if (ref) (ref as { current: HTMLDivElement | null }).current = node;
  };

  const displayedPercent = effectiveCollapsed ? 0 : Math.round(current);
  const valueText = COPY.sizeText.replace('{percent}', String(displayedPercent));

  const overrideStyle = overrides ? overridesToStyle(overrides) : undefined;
  const rootStyle: CSSProperties = {
    ...overrideStyle,
    ...style,
    '--ds-splitter-primary-size': `${effectiveCollapsed ? 0 : current}%`,
  } as CSSProperties;

  const classes = [
    'ds-splitter',
    `ds-splitter--${orientation}`,
    isStacked ? 'ds-splitter--stacked' : null,
    effectiveCollapsed ? 'ds-splitter--collapsed' : null,
    isDragging ? 'ds-splitter--dragging' : null,
    className ?? null,
  ]
    .filter(Boolean)
    .join(' ');

  const collapseIcon =
    orientation === 'horizontal'
      ? effectiveCollapsed
        ? 'chevron-right'
        : 'chevron-left'
      : effectiveCollapsed
        ? 'chevron-down'
        : 'chevron-up';

  return (
    <div
      {...rest}
      ref={setContainerRef}
      id={id}
      data-ds="Splitter"
      data-part="container"
      className={classes}
      style={rootStyle}
      onKeyDown={handleContainerKeyDown}
    >
      <div
        ref={primaryRef}
        id={primaryId}
        data-part="primaryPane"
        className="ds-splitter__primary-pane"
        tabIndex={-1}
      >
        {primary}
      </div>
      <div
        ref={separatorRef}
        data-part="separator"
        className="ds-splitter__separator"
        role={isStacked ? 'presentation' : 'separator'}
        tabIndex={isStacked ? undefined : 0}
        aria-orientation={isStacked ? undefined : orientation === 'horizontal' ? 'vertical' : 'horizontal'}
        aria-label={isStacked ? undefined : label}
        aria-controls={isStacked ? undefined : primaryId}
        aria-valuenow={isStacked ? undefined : displayedPercent}
        aria-valuemin={isStacked ? undefined : minSize}
        aria-valuemax={isStacked ? undefined : maxSize}
        aria-valuetext={isStacked ? undefined : valueText}
        onPointerDown={handleSeparatorPointerDown}
        onPointerMove={handleSeparatorPointerMove}
        onPointerUp={handleSeparatorPointerUp}
        onPointerCancel={handleSeparatorPointerCancel}
        onKeyDown={handleSeparatorKeyDown}
        onKeyUp={handleSeparatorKeyUp}
      >
        {collapsible && !isStacked ? (
          <Button
            variant="ghost"
            size="sm"
            iconOnly
            data-part="collapseButton"
            className="ds-splitter__collapse-button"
            label={(effectiveCollapsed ? COPY.expand : COPY.collapse).replace('{label}', label)}
            leadingIcon={<Icon name={collapseIcon} inline />}
            onClick={handleCollapseButtonClick}
          />
        ) : null}
      </div>
      <div ref={secondaryRef} id={secondaryId} data-part="secondaryPane" className="ds-splitter__secondary-pane" tabIndex={-1}>
        {secondary}
      </div>
    </div>
  );
});

// packages/lit/src/Splitter.ts
import { LitElement, css, html, nothing, unsafeCSS, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { classMap } from 'lit/directives/class-map.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Button.js';
import './Icon.js';
import type { IconName } from './Icon.js';

export type SplitterOrientation = 'horizontal' | 'vertical';
export type SplitterStackBelow = 'prose' | 'content' | 'never';

/** Detail carried by the `size-change` and `size-change-end` CustomEvents. */
export interface SplitterSizeChangeDetail {
  size: number;
}

/** Detail carried by the `collapse-change` CustomEvent. */
export interface SplitterCollapseChangeDetail {
  collapsed: boolean;
}

/** copy.collapse */
const COPY_COLLAPSE = (label: string): string => `Collapse ${label}`;
/** copy.expand */
const COPY_EXPAND = (label: string): string => `Expand ${label}`;
/** copy.sizeText */
const COPY_SIZE_TEXT = (percent: number): string => `${percent}%`;

/** layout.maxWidth.prose / layout.maxWidth.content: `@container` conditions cannot read custom properties, so the
    built breakpoints are duplicated here as literals, and again in JS to drive the ARIA/interactivity switch a
    container query alone cannot express. literal-ok: breakpoint from layout.maxWidth.* */
const PROSE_BREAKPOINT_PX = 572;
const CONTENT_BREAKPOINT_PX = 960;

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
].join(',');

/** First focusable element among `elements` or their descendants, in order. */
function firstFocusable(elements: Element[]): HTMLElement | null {
  for (const el of elements) {
    if (!(el instanceof HTMLElement)) {
      continue;
    }
    if (el.matches(FOCUSABLE_SELECTOR)) {
      return el;
    }
    const nested = el.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
    if (nested) {
      return nested;
    }
  }
  return null;
}

let idCounter = 0;
function nextSplitterId(): string {
  idCounter += 1;
  return `ds-splitter-${idCounter}`;
}

/** Overridable style hooks; see the `overrides` property. `separatorHover`, `separatorActive`, `grip`, `minTarget`,
    `focusRing` and `focusRingWidth` are locked and excluded. */
export type SplitterOverridableBinding =
  | 'separatorSize'
  | 'separatorColor'
  | 'handleSize'
  | 'gripLength'
  | 'collapseButtonOffset'
  | 'paneMinTarget'
  | 'transition';

const HOOKS: Record<SplitterOverridableBinding, string> = {
  separatorSize: '--ds-splitter-separator-size',
  separatorColor: '--ds-splitter-separator-color',
  handleSize: '--ds-splitter-handle-size',
  gripLength: '--ds-splitter-grip-length',
  collapseButtonOffset: '--ds-splitter-collapse-button-offset',
  paneMinTarget: '--ds-splitter-pane-min-target',
  transition: '--ds-splitter-transition',
};

/**
 * `<ds-splitter>` — Splitter (category: layout, APG pattern: windowsplitter).
 *
 * `<ds-splitter label="Sidebar width" collapsible persist-key="app-sidebar">` renders
 * a CSS grid of a primary pane (`slot="primary"`), a `role="separator"` divider and
 * a secondary pane (`slot="secondary"`) in its shadow root; the primary pane's size
 * is a host custom property in percent. Pointer Events with `setPointerCapture` on
 * the separator drive dragging; the full keyboard table (arrows, Home/End, Enter,
 * F6) is implemented on it. Dispatches composed `size-change` (continuously),
 * `size-change-end` (once, at drag end) and `collapse-change` CustomEvents. Below
 * `stackBelow` a horizontal splitter's `@container` query stacks the panes and a
 * `ResizeObserver` on the host retires the separator's `role`/`tabindex` to match.
 *
 * ## When to use
 *
 * Use a Splitter when two regions compete for space and the right split depends on
 * the task: a navigation tree beside content, a list beside a detail view. Make the
 * primary pane the one whose size matters, set sensible `minSize`/`maxSize`, and use
 * `persistKey` so the choice sticks. Use `collapsible` for sidebars.
 *
 * @fires size-change - Fired continuously while dragging and on each key press, with `{ size }` (percent) in `detail`.
 * @fires size-change-end - Fired once when a drag ends, with `{ size }` in `detail`.
 * @fires collapse-change - Fired when the primary pane collapses or restores, with `{ collapsed }` in `detail`.
 * @slot primary - The first pane, start or top (anatomy: primaryPane).
 * @slot secondary - The second pane, which takes the remaining space (anatomy: secondaryPane).
 * @csspart container - The grid of primary pane, separator and secondary pane (anatomy: container).
 * @csspart primaryPane - The primary pane wrapper (anatomy: primaryPane).
 * @csspart secondaryPane - The secondary pane wrapper (anatomy: secondaryPane).
 * @csspart separator - The `role="separator"` divider (anatomy: separator).
 * @csspart handle - The pointer grab area, wider than the visible line (anatomy: handle).
 * @csspart collapseButton - The composed `<ds-button>` that collapses/restores the primary pane (anatomy: collapseButton).
 */
@customElement('ds-splitter')
export class DsSplitter extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = css`
    :host {
      display: block;
      container-type: inline-size;
      /* Internal state channel (not an override hook): the primary pane's live size, in percent. */
      --ds-splitter-primary-size: 30%;
      --ds-splitter-separator-size: var(--space-1);
      --ds-splitter-separator-color: var(--color-border);
      --ds-splitter-handle-size: var(--space-3);
      --ds-splitter-grip-length: var(--space-6);
      --ds-splitter-collapse-button-offset: var(--space-2);
      --ds-splitter-pane-min-target: var(--size-target-comfortable);
      --ds-splitter-transition: var(--motion-duration-fast);
    }

    :host([hidden]) {
      display: none;
    }

    .container {
      display: grid;
      block-size: 100%;
      inline-size: 100%;
      grid-template-columns: var(--ds-splitter-primary-size) var(--ds-splitter-separator-size) 1fr;
      grid-template-rows: 1fr;
    }

    :host([orientation='vertical']) .container {
      grid-template-columns: 1fr;
      grid-template-rows: var(--ds-splitter-primary-size) var(--ds-splitter-separator-size) 1fr;
    }

    .pane {
      overflow: auto;
    }

    :host([orientation='horizontal']) .pane {
      min-inline-size: var(--ds-splitter-pane-min-target);
      min-block-size: 0;
    }

    :host([orientation='vertical']) .pane {
      min-block-size: var(--ds-splitter-pane-min-target);
      min-inline-size: 0;
    }

    /* A collapsed primary pane genuinely reaches zero; the pane-min-target floor does not apply to it. */
    .primary-pane.is-collapsed {
      min-inline-size: 0;
      min-block-size: 0;
      overflow: hidden;
    }

    .separator {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      background: var(--ds-splitter-separator-color);
      transition: background var(--ds-splitter-transition) var(--motion-easing-standard);
      touch-action: none;
    }

    @media (prefers-reduced-motion: reduce) {
      .separator {
        transition: none;
      }
    }

    :host([orientation='horizontal']) .separator {
      cursor: col-resize;
      inline-size: var(--ds-splitter-separator-size);
      block-size: 100%;
    }

    :host([orientation='vertical']) .separator {
      cursor: row-resize;
      block-size: var(--ds-splitter-separator-size);
      inline-size: 100%;
    }

    /* separatorHover: color.border.strong, locked */
    .separator:hover {
      background: var(--color-border-strong);
    }

    /* separatorActive: color.control.selectedBackground, locked; while dragging or focused */
    .separator.is-active,
    .separator:focus-visible {
      background: var(--color-control-selected-background);
    }

    /* focusRing / focusRingWidth: color.border.focus / border.width.focus, both locked */
    .separator:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* handleSize: pointer grab area, centered on the separator, overlapping both panes.
       minTarget: size.target.min hit-area floor, locked. */
    .handle {
      position: absolute;
      pointer-events: none;
    }

    :host([orientation='horizontal']) .handle {
      inset-block: 0;
      inset-inline-start: 50%;
      inline-size: max(var(--ds-splitter-handle-size), var(--size-target-min));
      transform: translateX(-50%);
    }

    :host([orientation='vertical']) .handle {
      inset-inline: 0;
      inset-block-start: 50%;
      block-size: max(var(--ds-splitter-handle-size), var(--size-target-min));
      transform: translateY(-50%);
    }

    /* grip: color.border.strong, locked */
    .grip {
      position: absolute;
      inset-block-start: 50%;
      inset-inline-start: 50%;
      transform: translate(-50%, -50%);
      background: var(--color-border-strong);
      border-radius: var(--radius-full);
    }

    :host([orientation='horizontal']) .grip {
      inline-size: var(--ds-splitter-separator-size);
      block-size: var(--ds-splitter-grip-length);
    }

    :host([orientation='vertical']) .grip {
      block-size: var(--ds-splitter-separator-size);
      inline-size: var(--ds-splitter-grip-length);
    }

    .collapse-button {
      position: absolute;
      pointer-events: auto;
    }

    :host([orientation='horizontal']) .collapse-button {
      inset-inline-start: 50%;
      inset-block-start: var(--ds-splitter-collapse-button-offset);
      transform: translateX(-50%);
    }

    :host([orientation='vertical']) .collapse-button {
      inset-block-start: 50%;
      inset-inline-start: var(--ds-splitter-collapse-button-offset);
      transform: translateY(-50%);
    }

    @container (max-width: ${unsafeCSS(CONTENT_BREAKPOINT_PX)}px) {
      :host([orientation='horizontal'][stack-below='content']) .container {
        grid-template-columns: 1fr;
        grid-template-rows: auto var(--ds-splitter-separator-size) auto;
      }
      :host([orientation='horizontal'][stack-below='content']) .separator {
        cursor: default;
        inline-size: 100%;
        block-size: var(--ds-splitter-separator-size);
      }
      :host([orientation='horizontal'][stack-below='content']) .handle,
      :host([orientation='horizontal'][stack-below='content']) .collapse-button {
        display: none;
      }
      :host([orientation='horizontal'][stack-below='content']) .pane {
        min-inline-size: 0;
      }
    }

    @container (max-width: ${unsafeCSS(PROSE_BREAKPOINT_PX)}px) {
      :host([orientation='horizontal'][stack-below='prose']) .container {
        grid-template-columns: 1fr;
        grid-template-rows: auto var(--ds-splitter-separator-size) auto;
      }
      :host([orientation='horizontal'][stack-below='prose']) .separator {
        cursor: default;
        inline-size: 100%;
        block-size: var(--ds-splitter-separator-size);
      }
      :host([orientation='horizontal'][stack-below='prose']) .handle,
      :host([orientation='horizontal'][stack-below='prose']) .collapse-button {
        display: none;
      }
      :host([orientation='horizontal'][stack-below='prose']) .pane {
        min-inline-size: 0;
      }
    }
  `;

  /** What the divider resizes ("Sidebar width", "Preview height"). The separator's accessible name. */
  @property() label = '';

  /** `horizontal` places panes side by side (the separator is vertical); `vertical` stacks them. */
  @property({ reflect: true }) orientation: SplitterOrientation = 'horizontal';

  /** Controlled size of the primary pane, percent (0-100). Omit for an uncontrolled splitter. */
  @property({ type: Number }) size?: number;

  /** Initial primary size, percent, for an uncontrolled splitter. */
  @property({ type: Number, attribute: 'default-size' }) defaultSize = 30;

  /** Smallest primary size, percent. Below this the pane collapses instead, when `collapsible`. */
  @property({ type: Number, attribute: 'min-size' }) minSize = 10;

  /** Largest primary size, percent. */
  @property({ type: Number, attribute: 'max-size' }) maxSize = 90;

  /** Arrow-key increment, percent. */
  @property({ type: Number }) step = 2;

  /** The primary pane can collapse to nothing: drag past `minSize`, press Enter on the separator, or use the
      collapse button. Enter again (or the button) restores the last size. */
  @property({ type: Boolean, reflect: true }) collapsible = false;

  /** Collapsed state. Two-way: set initially to start collapsed, or read/set at any time; the component keeps it
      current as the user drags, presses Enter, or uses the collapse button. */
  @property({ type: Boolean, reflect: true }) collapsed = false;

  /** When set, the size and collapsed state are remembered in `localStorage` under this key across mounts. */
  @property({ attribute: 'persist-key' }) persistKey?: string;

  /** Below this layout width a horizontal splitter stacks its panes and the separator becomes inert. */
  @property({ reflect: true, attribute: 'stack-below' }) stackBelow: SplitterStackBelow = 'prose';

  /** Per-instance style overrides: `{ separatorSize: 'space.2' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<SplitterOverridableBinding, TokenRef>>;

  /** Uncontrolled size (seeded from `defaultSize`, or restored via `persistKey`, when nothing else is set). */
  @state() private internalSize?: number;

  /** Active while the pointer is dragging the separator (drives `separatorActive`). */
  @state() private dragging = false;

  /** `true` below `stackBelow`, on a horizontal splitter: the separator loses its `tabindex` and `role`. */
  @state() private stacked = false;

  private readonly instanceId = nextSplitterId();

  private resizeObserver?: ResizeObserver;

  @query('.container') private readonly containerEl!: HTMLDivElement;
  @query('.separator') private readonly separatorEl!: HTMLDivElement;
  @query('.primary-pane') private readonly primaryPaneEl!: HTMLDivElement;
  @query('.secondary-pane') private readonly secondaryPaneEl!: HTMLDivElement;
  @query('slot[name="primary"]') private readonly primarySlotEl?: HTMLSlotElement;
  @query('slot[name="secondary"]') private readonly secondarySlotEl?: HTMLSlotElement;

  /** The current primary size (percent), resolved from `size`, `internalSize`, then `defaultSize`, clamped. */
  private get currentSize(): number {
    const raw = this.size ?? this.internalSize ?? this.defaultSize;
    return this.clamp(raw);
  }

  /** The displayed/reported size: 0 while collapsed, else `currentSize`. */
  private get effectiveSize(): number {
    return this.collapsed ? 0 : this.currentSize;
  }

  private get primaryPaneId(): string {
    return `${this.instanceId}-primary`;
  }

  private clamp(value: number): number {
    return Math.min(this.maxSize, Math.max(this.minSize, value));
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Splitter');
    this.addEventListener('keydown', this.handleHostKeydown);
    this.loadPersisted();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('keydown', this.handleHostKeydown);
    this.resizeObserver?.disconnect();
  }

  protected override firstUpdated(): void {
    this.resizeObserver = new ResizeObserver(() => this.updateStacked());
    this.resizeObserver.observe(this);
    this.updateStacked();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    if (changed.has('orientation') || changed.has('stackBelow')) {
      this.updateStacked();
    }
    this.style.setProperty('--ds-splitter-primary-size', `${this.effectiveSize}%`);
    this.warnInDev(changed);
  }

  protected override render() {
    const horizontal = this.orientation === 'horizontal';
    const size = this.effectiveSize;
    const collapseLabel = this.collapsed ? COPY_EXPAND(this.label) : COPY_COLLAPSE(this.label);
    const chevronName: IconName = horizontal
      ? this.collapsed
        ? 'chevron-right'
        : 'chevron-left'
      : this.collapsed
        ? 'chevron-down'
        : 'chevron-up';

    return html`
      <div class="container" part="container">
        <div
          class=${classMap({ pane: true, 'primary-pane': true, 'is-collapsed': this.collapsed })}
          part="primaryPane"
          id=${this.primaryPaneId}
          tabindex="-1"
          ?inert=${this.collapsed}
        >
          <slot name="primary"></slot>
        </div>
        <div
          class=${classMap({ separator: true, 'is-active': this.dragging })}
          part="separator"
          role=${this.stacked ? 'presentation' : 'separator'}
          tabindex=${ifDefined(this.stacked ? undefined : 0)}
          aria-orientation=${ifDefined(this.stacked ? undefined : horizontal ? 'vertical' : 'horizontal')}
          aria-valuenow=${ifDefined(this.stacked ? undefined : Math.round(size))}
          aria-valuemin=${ifDefined(this.stacked ? undefined : this.minSize)}
          aria-valuemax=${ifDefined(this.stacked ? undefined : this.maxSize)}
          aria-valuetext=${ifDefined(this.stacked ? undefined : COPY_SIZE_TEXT(Math.round(size)))}
          aria-label=${ifDefined(this.stacked ? undefined : this.label)}
          aria-controls=${ifDefined(this.stacked ? undefined : this.primaryPaneId)}
          @pointerdown=${this.handleSeparatorPointerDown}
          @pointermove=${this.handleSeparatorPointerMove}
          @pointerup=${this.handleSeparatorPointerUp}
          @pointercancel=${this.handleSeparatorPointerUp}
          @keydown=${this.handleSeparatorKeydown}
        >
          <div class="handle" part="handle">
            <div class="grip" aria-hidden="true"></div>
          </div>
          ${this.collapsible
            ? html`<ds-button
                class="collapse-button"
                part="collapseButton"
                variant="ghost"
                size="sm"
                icon-only
                label=${collapseLabel}
                @press=${this.handleCollapseButtonPress}
              >
                <ds-icon slot="leading-icon" name=${chevronName}></ds-icon>
              </ds-button>`
            : nothing}
        </div>
        <div class="pane secondary-pane" part="secondaryPane" tabindex="-1">
          <slot name="secondary"></slot>
        </div>
      </div>
    `;
  }

  private readonly handleSeparatorPointerDown = (event: PointerEvent): void => {
    if (this.stacked) {
      return;
    }
    if ((event.target as HTMLElement).closest('.collapse-button')) {
      return;
    }
    event.preventDefault();
    this.dragging = true;
    this.separatorEl.setPointerCapture(event.pointerId);
    this.updateFromPointer(event);
  };

  private readonly handleSeparatorPointerMove = (event: PointerEvent): void => {
    if (!this.dragging) {
      return;
    }
    this.updateFromPointer(event);
  };

  private readonly handleSeparatorPointerUp = (event: PointerEvent): void => {
    if (!this.dragging) {
      return;
    }
    if (this.separatorEl.hasPointerCapture(event.pointerId)) {
      this.separatorEl.releasePointerCapture(event.pointerId);
    }
    this.dragging = false;
    this.dispatchSizeChangeEnd();
    this.persist();
  };

  private updateFromPointer(event: PointerEvent): void {
    const rect = this.containerEl.getBoundingClientRect();
    const ratio =
      this.orientation === 'horizontal'
        ? rect.width === 0
          ? 0
          : (event.clientX - rect.left) / rect.width
        : rect.height === 0
          ? 0
          : (event.clientY - rect.top) / rect.height;
    const raw = Math.min(100, Math.max(0, ratio * 100));
    if (this.collapsible && raw < this.minSize) {
      this.commitSize(this.minSize);
      this.setCollapsed(true);
    } else {
      this.setCollapsed(false);
      this.commitSize(this.clamp(raw));
    }
    this.dispatchSizeChange();
  }

  private handleSeparatorKeydown(event: KeyboardEvent): void {
    if (this.stacked) {
      return;
    }
    const horizontal = this.orientation === 'horizontal';
    const growKey = horizontal ? 'ArrowRight' : 'ArrowDown';
    const shrinkKey = horizontal ? 'ArrowLeft' : 'ArrowUp';
    switch (event.key) {
      case growKey:
        event.preventDefault();
        this.adjustSize(this.step);
        break;
      case shrinkKey:
        event.preventDefault();
        this.adjustSize(-this.step);
        break;
      case 'Home':
        event.preventDefault();
        this.setCollapsed(false);
        this.commitSize(this.minSize);
        this.dispatchSizeChange();
        this.persist();
        break;
      case 'End':
        event.preventDefault();
        this.setCollapsed(false);
        this.commitSize(this.maxSize);
        this.dispatchSizeChange();
        this.persist();
        break;
      case 'Enter':
        if (this.collapsible) {
          event.preventDefault();
          this.toggleCollapsed();
        }
        break;
      default:
        break;
    }
  }

  private readonly handleHostKeydown = (event: KeyboardEvent): void => {
    if (event.key !== 'F6' || this.stacked) {
      return;
    }
    event.preventDefault();
    this.cycleFocus();
  };

  private handleCollapseButtonPress(event: Event): void {
    event.stopPropagation();
    this.toggleCollapsed();
  }

  private adjustSize(delta: number): void {
    const base = this.collapsed ? 0 : this.currentSize;
    this.setCollapsed(false);
    this.commitSize(this.clamp(base + delta));
    this.dispatchSizeChange();
    this.persist();
  }

  private toggleCollapsed(): void {
    this.setCollapsed(!this.collapsed);
    this.persist();
  }

  private commitSize(next: number): void {
    if (this.size !== undefined) {
      this.size = next;
    } else {
      this.internalSize = next;
    }
  }

  private setCollapsed(next: boolean): void {
    if (this.collapsed === next) {
      return;
    }
    this.collapsed = next;
    this.dispatchEvent(
      new CustomEvent<SplitterCollapseChangeDetail>('collapse-change', {
        detail: { collapsed: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private dispatchSizeChange(): void {
    this.dispatchEvent(
      new CustomEvent<SplitterSizeChangeDetail>('size-change', {
        detail: { size: this.effectiveSize },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private dispatchSizeChangeEnd(): void {
    this.dispatchEvent(
      new CustomEvent<SplitterSizeChangeDetail>('size-change-end', {
        detail: { size: this.effectiveSize },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private zoneIndexOf(active: Element | null): number {
    if (!active) {
      return -1;
    }
    if (active === this.separatorEl) {
      return 1;
    }
    const primaryEls = this.primarySlotEl?.assignedElements({ flatten: true }) ?? [];
    if (primaryEls.some((el) => el === active || el.contains(active))) {
      return 0;
    }
    const secondaryEls = this.secondarySlotEl?.assignedElements({ flatten: true }) ?? [];
    if (secondaryEls.some((el) => el === active || el.contains(active))) {
      return 2;
    }
    return -1;
  }

  private focusZone(index: number): void {
    if (index === 1) {
      this.separatorEl?.focus();
      return;
    }
    const slotEl = index === 0 ? this.primarySlotEl : this.secondarySlotEl;
    const paneEl = index === 0 ? this.primaryPaneEl : this.secondaryPaneEl;
    const assigned = slotEl?.assignedElements({ flatten: true }) ?? [];
    const target = firstFocusable(assigned);
    (target ?? paneEl)?.focus();
  }

  /** F6: cycles focus through primary content, the separator, and secondary content (APG convenience). */
  private cycleFocus(): void {
    const active = (this.shadowRoot?.activeElement as Element | null) ?? document.activeElement;
    const current = this.zoneIndexOf(active);
    this.focusZone((current + 1) % 3);
  }

  private updateStacked(): void {
    if (this.orientation !== 'horizontal' || this.stackBelow === 'never') {
      this.stacked = false;
      return;
    }
    const breakpoint = this.stackBelow === 'prose' ? PROSE_BREAKPOINT_PX : CONTENT_BREAKPOINT_PX;
    this.stacked = this.getBoundingClientRect().width < breakpoint;
  }

  private get storageKey(): string {
    return `ds-splitter:${this.persistKey}`;
  }

  private loadPersisted(): void {
    if (!this.persistKey) {
      return;
    }
    try {
      const raw = localStorage.getItem(this.storageKey);
      if (!raw) {
        return;
      }
      const parsed = JSON.parse(raw) as { size?: number; collapsed?: boolean };
      if (this.size === undefined && typeof parsed.size === 'number') {
        this.internalSize = parsed.size;
      }
      if (typeof parsed.collapsed === 'boolean') {
        this.collapsed = parsed.collapsed;
      }
    } catch {
      /* localStorage unavailable (SSR, privacy mode); the splitter just keeps its default. */
    }
  }

  private persist(): void {
    if (!this.persistKey) {
      return;
    }
    try {
      localStorage.setItem(this.storageKey, JSON.stringify({ size: this.currentSize, collapsed: this.collapsed }));
    } catch {
      /* localStorage unavailable (SSR, privacy mode); ignore. */
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as SplitterOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(changed: PropertyValues): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if ((changed.has('minSize') || changed.has('maxSize')) && !(this.maxSize > this.minSize)) {
      console.warn(`<ds-splitter> needs maxSize (${this.maxSize}) greater than minSize (${this.minSize}).`, this);
    }
    if (changed.has('defaultSize') && (this.defaultSize < this.minSize || this.defaultSize > this.maxSize)) {
      console.warn(`<ds-splitter> defaultSize (${this.defaultSize}) is outside minSize/maxSize.`, this);
    }
    if (changed.has('collapsed') && this.collapsed && !this.collapsible) {
      console.warn('<ds-splitter collapsed> has no effect without `collapsible`.', this);
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-splitter': DsSplitter;
  }
}
