// packages/rn/src/Switch.tsx
import * as React from 'react';
import { AccessibilityInfo, Platform, Pressable, Switch as RNSwitch, View, findNodeHandle } from 'react-native';
import type { SwitchInstance, ViewInstance, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { useFieldsetContext } from './Fieldset';
import { useFormContext } from './FormContext';
import type { FormFieldHandle } from './FormContext';
import { Text } from './Text';
import { toLineHeight, useTheme } from './theme';

export type SwitchLabelPosition = 'start' | 'end';

/** The DOM element react-native-web renders for the row; this package has no DOM lib. */
type WebElement = { setAttribute(name: string, value: string): void; removeAttribute(name: string): void };

/**
 * The style bindings a caller may replace with a different token; see the component's
 * overrides contract. `trackWidth`, `trackHeight`, `thumbSize`, `thumbInset`, `radius`
 * and `transition` are drawn and animated by the native `Switch` on React Native and are
 * excluded here, since an override on them would be a silent no-op.
 */
export type SwitchOverridableBinding =
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity';

export interface SwitchProps {
  /** Visible label naming the thing being turned on or off. Also the accessible name. */
  label: string;
  /** Optional field name. When inside a Form the state is collected as a boolean; most switches are not in forms. A Switch never validates. */
  name?: string | undefined;
  /** Controlled state. Omit for an uncontrolled control. */
  checked?: boolean | undefined;
  /** Initial state for an uncontrolled control. */
  defaultChecked?: boolean | undefined;
  /** Cannot be toggled. Stays visible and readable; the native Switch is not focusable while disabled (platform limit). */
  disabled?: boolean | undefined;
  /** Persistent helper text below the label explaining the effect. Also the `accessibilityHint`. */
  description?: string | undefined;
  /** Where the label sits relative to the track. `start` (label, then switch at the row end) is the settings-list convention; `end` matches Checkbox. */
  labelPosition?: SwitchLabelPosition | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<SwitchOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the state changes, with the new boolean (`events.onChange`). The change is already in effect; there is nothing to submit. */
  onValueChange?: ((checked: boolean) => void) | undefined;
  /** The root view (the row). */
  ref?: React.Ref<ViewInstance> | undefined;
}

/**
 * Switch — a light switch: flip it and the thing happens. That immediacy separates
 * it from a Checkbox, which records a choice to be submitted later.
 *
 * When to use: Use a Switch for a binary setting that applies as soon as it changes
 * and can be undone by flipping it back: notifications, dark mode, "show archived".
 * Use it in settings lists with `labelPosition: start` so the switches sit at the
 * row end. If a form of switches must have a Save button, they are checkboxes.
 *
 * Uses the native `Switch` with `accessibilityRole="switch"` (native only — on
 * react-native-web the rendered `<input type="checkbox" role="switch">` already carries
 * the role, and a second one on its container would have no state and a focusable
 * descendant), `accessibilityLabel`, `accessibilityHint={description}`,
 * `accessibilityState={{ checked, disabled }}`,
 * `trackColor={{ false: trackOff, true: trackOn }}`, `thumbColor` and
 * `ios_backgroundColor={trackOff}`. The row is a `Pressable` with `accessible={false}`
 * and `tabIndex={-1}` that toggles the value, so label and description are part of the
 * target while the Switch stays the single focusable element; the row is at least the comfortable
 * target tall with no padding, and centres its content in that height, so a one-line
 * row sits in the middle while a wrapping label or a description grows it downwards
 * with the track still on the label's first line. Track and thumb sizes, radius, thumb travel, its animation (and reduced
 * motion) and the focus indicator are the OS values. With `name` inside a Form the
 * switch registers and contributes a boolean; it has no error state by design. Inside
 * a Fieldset the group's `disabled` applies and the legend prefixes the label.
 */
export function Switch({
  label,
  name,
  checked,
  defaultChecked = false,
  disabled = false,
  description,
  labelPosition = 'start',
  overrides,
  onValueChange,
  ref,
}: SwitchProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const form = useFormContext();
  const fieldset = useFieldsetContext();
  const switchRef = React.useRef<SwitchInstance>(null);
  const [internalChecked, setInternalChecked] = React.useState<boolean>(defaultChecked);

  // The root is owned here so react-native-web can be given `aria-disabled` directly (below);
  // the caller's `ref` still receives the same Pressable.
  const rootRef = React.useRef<ViewInstance>(null);
  React.useImperativeHandle(ref, () => rootRef.current!, []);

  const isChecked = checked ?? internalChecked;
  const isDisabled = disabled || (form?.disabled ?? false) || (fieldset?.disabled ?? false);
  const accessibleName = fieldset !== null ? `${fieldset.legend}, ${label}` : label;

  const latest = React.useRef({ isChecked, isDisabled, label });
  latest.current = { isChecked, isDisabled, label };
  // A disabled switch stays registered and reports `isDisabled()`, which the Form uses to
  // leave it out of the values (the disabled-field rule, as for Checkbox); it never validates.
  const handle = React.useMemo<FormFieldHandle>(
    () => ({
      get label() {
        return latest.current.label;
      },
      getValue: () => latest.current.isChecked,
      isDisabled: () => latest.current.isDisabled,
      validate: () => null,
      focus: () => {
        const node = switchRef.current === null ? null : findNodeHandle(switchRef.current);
        if (node != null) {
          AccessibilityInfo.setAccessibilityFocus(node);
        }
      },
    }),
    [],
  );

  const register = form?.register;
  const unregister = form?.unregister;
  React.useEffect(() => {
    // Without `name` the switch contributes no key and does not register.
    if (register === undefined || unregister === undefined || name === undefined) {
      return undefined;
    }
    register(name, handle);
    return () => unregister(name);
  }, [register, unregister, name, handle]);
  // The Form re-reads `isDisabled()` on registration, which keeps the field's place in the
  // order, so registering again is how a change of disabled state reaches it (as in Input).
  const registeredDisabled = React.useRef(isDisabled);
  React.useEffect(() => {
    if (registeredDisabled.current === isDisabled) {
      return;
    }
    registeredDisabled.current = isDisabled;
    if (name !== undefined) {
      register?.(name, handle);
    }
  }, [register, name, handle, isDisabled]);

  // The row is dimmed as a whole (disabledOpacity covers track, label and description), so on
  // react-native-web its text would fail axe's contrast check while reading as enabled. The row
  // Pressable cannot take `disabled` — only the native Switch does — and react-native-web's
  // Pressable overwrites any `aria-disabled` passed in with its own `disabled` prop, so the
  // attribute is set on the DOM node itself, as in Button and Checkbox: the row is announced
  // disabled and its dimmed text is audited as part of a disabled control rather than as body copy.
  React.useEffect(() => {
    if (Platform.OS !== 'web') {
      return;
    }
    const node = rootRef.current as unknown as WebElement | null;
    if (node === null) {
      return;
    }
    if (isDisabled) {
      node.setAttribute('aria-disabled', 'true');
    } else {
      node.removeAttribute('aria-disabled');
    }
  }, [isDisabled]);

  const setValue = (next: boolean): void => {
    if (isDisabled || next === isChecked) {
      return;
    }
    if (checked === undefined) {
      setInternalChecked(next);
    }
    onValueChange?.(next);
  };

  const gap = overrides?.gap ? (resolveToken(t, overrides.gap) as number) : t.space3;
  const partGap = overrides?.partGap ? (resolveToken(t, overrides.partGap) as number) : t.space1;
  const disabledOpacity = overrides?.disabledOpacity ? (resolveToken(t, overrides.disabledOpacity) as number) : t.opacityDisabled;
  const labelSize = overrides?.labelSize ? (resolveToken(t, overrides.labelSize) as number) : t.fontSizeMd;
  const lineHeight = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;

  // The row has no padding: it is at least minTarget tall and centres its content box
  // in that height, so a single line is vertically centred in the comfortable target
  // while a description or a wrapping label grows the row downwards from there.
  // The opacity dims the track (with its thumb), the label and the description together.
  const rowStyle: ViewStyle = {
    justifyContent: 'center',
    minHeight: t.sizeTargetComfortable,
    opacity: isDisabled ? disabledOpacity : 1,
  };

  // Track slot and text column, aligned to the top of the content box.
  const contentStyle: ViewStyle = {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap,
  };

  // The track sits in a slot one label line tall and is centred in it, so a wrapping
  // label or a description never pulls it off that line. The native Switch is taller
  // than the slot (about 31pt on iOS) and spills evenly above and below it; the row's
  // minHeight still contains it.
  const trackSlotStyle: ViewStyle = {
    height: toLineHeight(labelSize, lineHeight),
    justifyContent: 'center',
  };

  const textColumnStyle: ViewStyle = {
    flex: 1,
    flexDirection: 'column',
    gap: partGap,
  };

  // react-native-web colours a checked thumb from its own `activeThumbColor` (a teal default)
  // and uses `thumbColor` only while off, so the thumb binding is given to both there.
  const isWeb = Platform.OS === 'web';
  const webThumbProps: object = isWeb ? { activeThumbColor: t.colorControlSelectedForeground } : {};

  const typographyOverrides = { fontFamily: overrides?.fontFamily, lineHeight: overrides?.lineHeight };
  const helperOverrides = { ...typographyOverrides, fontSize: overrides?.helperSize };

  const labelColumn = (
    <View style={textColumnStyle}>
      <View testID="Switch.label">
        <Text
          size="md"
          weight="regular"
          tone="default"
          overrides={{ ...typographyOverrides, fontSize: overrides?.labelSize, fontWeight: overrides?.labelWeight }}
        >
          {label}
        </Text>
      </View>
      {description !== undefined ? (
        <View testID="Switch.description">
          <Text size="sm" tone="muted" overrides={helperOverrides}>
            {description}
          </Text>
        </View>
      ) : null}
    </View>
  );

  return (
    <Pressable
      ref={rootRef}
      testID="Switch"
      accessible={false}
      // The Switch is the single focusable element: react-native-web's Pressable makes its row a
      // tab stop (tabIndex 0) unless one is given, which would put an unnamed, roleless stop in
      // front of the control. `focusable` cannot do this — Pressable always passes its own tabIndex.
      tabIndex={-1}
      onPress={() => setValue(!isChecked)}
      style={rowStyle}
    >
      <View style={contentStyle}>
        {labelPosition === 'start' ? labelColumn : null}
        <View style={trackSlotStyle}>
          <RNSwitch
            ref={switchRef}
            testID="Switch.track"
            // react-native-web's Switch is a container View holding the real
            // `<input type="checkbox" role="switch">`, and spreads the accessibility props onto
            // that container: `accessibilityRole` would put a second role="switch" on it, with no
            // aria-checked of its own (aria-required-attr) and the input focusable inside it
            // (nested-interactive). The input already carries the role, the name and the state, so
            // the role is set on native only, where it is what makes the Switch announce as one.
            accessibilityRole={Platform.OS === 'web' ? undefined : 'switch'}
            accessibilityLabel={accessibleName}
            accessibilityHint={description}
            accessibilityState={{ checked: isChecked, disabled: isDisabled }}
            // The aria-* mirrors, native only for the same reason as the role: on the web
            // container they would be a stateless duplicate of what the input already says.
            aria-label={Platform.OS === 'web' ? undefined : accessibleName}
            aria-checked={Platform.OS === 'web' ? undefined : isChecked}
            aria-disabled={Platform.OS === 'web' ? undefined : isDisabled}
            {...webThumbProps}
            value={isChecked}
            disabled={isDisabled}
            trackColor={{ false: t.colorControlTrackOff, true: t.colorControlSelectedBackground }}
            thumbColor={t.colorControlSelectedForeground}
            ios_backgroundColor={t.colorControlTrackOff}
            onValueChange={setValue}
          />
        </View>
        {labelPosition === 'end' ? labelColumn : null}
      </View>
    </Pressable>
  );
}

// packages/lit/src/Switch.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { live } from 'lit/directives/live.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import type { TextOverridableBinding } from './Text.js';
import './Text.js';

/** Where the label sits relative to the track. */
export type SwitchLabelPosition = 'start' | 'end';

/** Detail carried by the `change` CustomEvent. */
export interface SwitchChangeDetail {
  /** The new state. */
  checked: boolean;
}

/** Overridable style hooks; see the `overrides` property. `trackOff`, `trackOn`, `thumb`, `labelColor`, `descriptionText`, `focusRing`, `focusRingWidth` and `minTarget` are locked and excluded. */
export type SwitchOverridableBinding =
  | 'trackWidth'
  | 'trackHeight'
  | 'thumbSize'
  | 'thumbInset'
  | 'radius'
  | 'gap'
  | 'partGap'
  | 'labelSize'
  | 'labelWeight'
  | 'helperSize'
  | 'fontFamily'
  | 'lineHeight'
  | 'disabledOpacity'
  | 'transition';

/** Hooks on `:host`. `helperSize` has none: it reaches the description Text only through its `overrides`. */
const HOOKS: Record<Exclude<SwitchOverridableBinding, 'helperSize'>, string> = {
  trackWidth: '--ds-switch-track-width',
  trackHeight: '--ds-switch-track-height',
  thumbSize: '--ds-switch-thumb-size',
  thumbInset: '--ds-switch-thumb-inset',
  radius: '--ds-switch-radius',
  gap: '--ds-switch-gap',
  partGap: '--ds-switch-part-gap',
  labelSize: '--ds-switch-label-size',
  labelWeight: '--ds-switch-label-weight',
  fontFamily: '--ds-switch-font-family',
  lineHeight: '--ds-switch-line-height',
  disabledOpacity: '--ds-switch-disabled-opacity',
  transition: '--ds-switch-transition',
};

/**
 * `<ds-switch>` — Switch (category: input, APG pattern: switch).
 *
 * `<ds-switch label="Email notifications">`. A native
 * `<input type="checkbox" role="switch">` styled with `appearance: none` is the
 * track (in a shadow root with `delegatesFocus`), which keeps label
 * association, Space toggling and form participation for free; the thumb is a
 * Switch-owned `aria-hidden` span stacked over it in a track wrapper (not the
 * input's `::before`, which Firefox does not draw on an `appearance: none`
 * input), and both key off the input's `aria-checked`, never `:checked`. The
 * `<label for>` sits in the same root, so a click on it toggles natively; a
 * click on the description or the row's gap is forwarded to the control, so
 * the whole row toggles.
 *
 * The element is form-associated like `ds-checkbox`: the native form value is
 * `"on"` while checked and `null` otherwise (and `null` while disabled or
 * form-disabled), while `<ds-form>` discovers it by `data-ds-field="change"`
 * and collects `currentValue` as a boolean. A switch never validates. The
 * inner native `change` is not composed, so a composed `change` CustomEvent
 * with `{ checked }` is re-dispatched from the host. `checked` behaves like a
 * native input: the attribute is the initial state only and the property is
 * the live state, so it is not reflected and there is no controlled mode.
 *
 * ## When to use
 *
 * Use a Switch for a binary setting that applies as soon as it changes and can
 * be undone by flipping it back: notifications, dark mode, "show archived".
 * Use it in settings lists with `labelPosition: start` so labels line up and
 * switches sit at the row end. A choice that is only applied on Save is a
 * Checkbox.
 *
 * @fires change - Fired when the user changes the state, with `{ checked }` in `detail`. The change is already in effect.
 */
@customElement('ds-switch')
export class DsSwitch extends LitElement {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-switch-track-width: var(--space-10);
      --ds-switch-track-height: var(--space-6);
      --ds-switch-thumb-size: var(--space-5);
      --ds-switch-thumb-inset: var(--space-1);
      --ds-switch-radius: var(--radius-full);
      --ds-switch-gap: var(--space-3);
      --ds-switch-part-gap: var(--space-1);
      --ds-switch-label-size: var(--font-size-md);
      --ds-switch-label-weight: var(--font-weight-regular);
      --ds-switch-font-family: var(--font-family-body);
      --ds-switch-line-height: var(--font-line-height-normal);
      --ds-switch-disabled-opacity: var(--opacity-disabled);
      --ds-switch-transition: var(--motion-duration-fast);
      /* Locked: absent from the overrides type, but the hooks stay so page CSS can re-theme them. */
      --ds-switch-track-off: var(--color-control-track-off);
      --ds-switch-track-on: var(--color-control-selected-background);
      --ds-switch-thumb: var(--color-control-selected-foreground);
      --ds-switch-label-color: var(--color-foreground);
      --ds-switch-focus-ring: var(--color-border-focus);
      --ds-switch-focus-ring-width: var(--border-width-focus);
      --ds-switch-min-target: var(--size-target-comfortable);
      /* helperSize and descriptionText have no hook: they reach the composed Text only through its
         tone prop and its own overrides. */

      /* The label's first line box, which the track slot is tall, and the thumb's travel. */
      --ds-switch-line-box: calc(var(--ds-switch-label-size) * var(--ds-switch-line-height));
      --ds-switch-thumb-travel: calc(
        var(--ds-switch-track-width) - var(--ds-switch-thumb-size) - 2 * var(--ds-switch-thumb-inset)
      );
    }

    :host([hidden]) {
      display: none;
    }

    /* minTarget: a full-width row with no padding; the whole row, gap included, toggles. The content
       box is centred on the cross axis, so a one-line row sits in the middle of minTarget. */
    .root {
      display: flex;
      flex-direction: column;
      justify-content: center;
      inline-size: 100%;
      min-block-size: var(--ds-switch-min-target);
      cursor: pointer;
    }

    /* The content box: the track slot aligns with the top of the text column, so a wrapping label or
       a description grows the row downwards without pulling the track off the first line. */
    .row {
      display: flex;
      align-items: flex-start;
      gap: var(--ds-switch-gap);
    }

    /* labelPosition changes the order of the row only: start puts the label first and pushes the
       track to the row end; end puts the track first, as on Checkbox. */
    .text {
      order: 0;
    }
    .slot {
      order: 1;
    }
    :host([label-position='start']) .row {
      justify-content: space-between;
    }
    :host([label-position='end']) .text {
      order: 1;
    }
    :host([label-position='end']) .slot {
      order: 0;
    }

    /* partGap: the text column, label then description. */
    .text {
      display: flex;
      flex-direction: column;
      gap: var(--ds-switch-part-gap);
      min-inline-size: 0;
    }

    /* labelColor, labelSize, labelWeight, fontFamily, lineHeight: the label's own rule */
    .label {
      font-family: var(--ds-switch-font-family);
      font-size: var(--ds-switch-label-size);
      font-weight: var(--ds-switch-label-weight);
      line-height: var(--ds-switch-line-height);
      color: var(--ds-switch-label-color);
      cursor: pointer;
    }

    /* One label line tall: the track centres on the label's first line. */
    .slot {
      display: flex;
      flex: 0 0 auto;
      align-items: center;
      block-size: var(--ds-switch-line-box);
    }

    /* The track wrapper stacks the Switch-owned thumb span over the input. */
    .track-wrap {
      position: relative;
      display: inline-flex;
      flex: 0 0 auto;
    }

    /* track: a native input sized trackWidth × trackHeight, drawn with the control tokens. */
    .control {
      box-sizing: border-box;
      flex: 0 0 auto;
      inline-size: var(--ds-switch-track-width);
      block-size: var(--ds-switch-track-height);
      margin: 0;
      padding: 0;
      border: 0;
      border-radius: var(--ds-switch-radius);
      background-color: var(--ds-switch-track-off);
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
      transition: background-color var(--ds-switch-transition) var(--motion-easing-standard);
    }

    /* trackOn: keyed off the component state, not :checked, so the look always follows checked. */
    .control[aria-checked='true'] {
      background-color: var(--ds-switch-track-on);
    }

    /* focusRing, focusRingWidth: drawn around the track, offset by focusRingWidth like every other
       control. Never removed. */
    .control:focus-visible {
      outline: var(--ds-switch-focus-ring-width) solid var(--ds-switch-focus-ring);
      outline-offset: var(--ds-switch-focus-ring-width);
    }

    /* thumb: a real span, not a ::before, which Firefox does not draw on an appearance: none input.
       It is inset evenly on the short axis and click-through, so presses reach the input underneath. */
    .thumb {
      position: absolute;
      inset-block-start: calc((var(--ds-switch-track-height) - var(--ds-switch-thumb-size)) / 2);
      inset-inline-start: var(--ds-switch-thumb-inset);
      inline-size: var(--ds-switch-thumb-size);
      block-size: var(--ds-switch-thumb-size);
      border-radius: var(--ds-switch-radius);
      background-color: var(--ds-switch-thumb);
      pointer-events: none;
      transition: transform var(--ds-switch-transition) var(--motion-easing-standard);
    }

    /* Travels trackWidth − thumbSize − 2 × thumbInset when on. */
    .control[aria-checked='true'] ~ .thumb {
      transform: translateX(var(--ds-switch-thumb-travel));
    }

    /* RTL: the thumb travels toward the inline end, which is leftward. :dir(rtl) rather than an
       ancestor [dir='rtl'] selector, which misses an inherited direction. */
    :host(:dir(rtl)) .control[aria-checked='true'] ~ .thumb {
      transform: translateX(calc(-1 * var(--ds-switch-thumb-travel)));
    }

    /* transition: under reduced motion the thumb jumps and the track colour changes instantly. */
    @media (prefers-reduced-motion: reduce) {
      .control,
      .thumb {
        transition: none;
      }
    }

    /* disabledOpacity: the track (with its thumb), the label and the description dim — on the slot
       and on the text column, never on the composed description Text itself. The switch stays
       visible, readable and focusable. */
    .root.disabled,
    .root.disabled .control,
    .root.disabled .label {
      cursor: not-allowed;
    }
    .root.disabled .slot,
    .root.disabled .text {
      opacity: var(--ds-switch-disabled-opacity);
    }
  `;

  /** Visible label naming the thing being turned on or off. Also the accessible name. */
  @property() accessor label = '';

  /** Optional field name. When inside a Form the state is collected as a boolean; most switches are not in forms. Reflected so a name set as a property is still submitted by a native `<form>`. */
  @property({ reflect: true }) accessor name = '';

  /** Initial state when neither the `checked` attribute nor property is set. */
  @property({ type: Boolean, attribute: 'default-checked' }) accessor defaultChecked = false;

  /** Cannot be toggled. Stays visible, readable and focusable, and contributes no key to the Form's values. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Persistent helper text below the label explaining the effect. */
  @property() accessor description: string | undefined;

  /** Where the label sits relative to the track. `start` is the settings-list convention; `end` matches Checkbox. */
  @property({ reflect: true, attribute: 'label-position' }) accessor labelPosition: SwitchLabelPosition = 'start';

  /** Per-instance style overrides: `{ trackWidth: 'space.12' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<SwitchOverridableBinding, TokenRef | undefined>>
    | undefined;

  private checkedValue: boolean | undefined;

  /** The live state, like a native input: starts from the `checked` attribute, else `defaultChecked`, and follows every toggle. Not reflected; there is no controlled mode. */
  get checked(): boolean {
    return this.checkedValue ?? this.defaultChecked;
  }
  @property({ type: Boolean })
  set checked(value: boolean) {
    const old = this.checked;
    this.checkedValue = value;
    this.requestUpdate('checked', old);
  }

  /** A switch has no required state: it never validates and never appears in an error summary. Setting it is ignored. */
  get required(): boolean {
    return false;
  }
  set required(_value: boolean) {
    // Deliberately ignored: a no-op rather than a missing setter, which would throw in strict mode.
  }

  /** Disabled by an owning native form / fieldset (via `formDisabledCallback`). */
  @state() private accessor formDisabled = false;

  @query('#control') private accessor inputEl!: HTMLInputElement | null;

  private readonly internals: ElementInternals;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Switch');
    // A switch has no useful blur moment, so ds-form validates it on change (it never fails).
    this.setAttribute('data-ds-field', 'change');
  }

  /** The value `<ds-form>` collects: the state as a boolean. */
  get currentValue(): boolean {
    return this.checked;
  }

  /** The owning native form, if any (from `ElementInternals`). */
  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  /** Always empty: a switch has no error state by design. */
  get validationMessage(): string {
    return '';
  }

  /** Always valid: a switch has no error state by design. */
  checkValidity(): boolean {
    return true;
  }

  /** Always valid: a switch has no error state by design. */
  reportValidity(): boolean {
    return true;
  }

  /* Form-associated custom element callbacks (invoked by the browser). */

  formDisabledCallback(disabled: boolean): void {
    this.formDisabled = disabled;
  }

  /** Back to the initial state: the `checked` attribute, else `defaultChecked`. */
  formResetCallback(): void {
    const old = this.checked;
    this.checkedValue = this.hasAttribute('checked') ? true : undefined;
    this.requestUpdate('checked', old);
  }

  formStateRestoreCallback(state: File | string | FormData | null): void {
    this.checked = state === 'on';
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    // Native semantics: "on" or null, and null while disabled or form-disabled, so neither a native
    // <form> nor ds-form collects a disabled switch.
    this.internals.setFormValue(this.checked && !this.isDisabled ? 'on' : null);
  }

  protected override render(): TemplateResult {
    const isDisabled = this.isDisabled;
    return html`
      <div class=${classMap({ root: true, disabled: isDisabled })} @click=${this.handleRowClick}>
        <!-- The row centres this content box in minTarget; inside it the track stays on the first line. -->
        <div class="row">
          <div class="text">
            <label class="label" part="label" data-part="label" for="control">${this.label}</label>
            ${this.description
              ? html`<ds-text
                  id="description"
                  part="description"
                  data-part="description"
                  element="p"
                  size="sm"
                  tone="muted"
                  .overrides=${this.textOverrides}
                  >${this.description}</ds-text
                >`
              : nothing}
          </div>
          <span class="slot">
            <span class="track-wrap">
              <input
                id="control"
                class="control"
                part="track"
                data-part="track"
                type="checkbox"
                role="switch"
                .checked=${live(this.checked)}
                aria-checked=${this.checked ? 'true' : 'false'}
                aria-describedby=${ifDefined(this.description ? 'description' : undefined)}
                aria-disabled=${ifDefined(isDisabled ? 'true' : undefined)}
                @click=${this.handleControlClick}
                @change=${this.handleChange}
              />
              <span class="thumb" part="thumb" data-part="thumb" aria-hidden="true"></span>
            </span>
          </span>
        </div>
      </div>
    `;
  }

  private get isDisabled(): boolean {
    return this.disabled || this.formDisabled;
  }

  /** helperSize, fontFamily and lineHeight forwarded to the description Text. */
  private get textOverrides(): Partial<Record<TextOverridableBinding, TokenRef | undefined>> | undefined {
    const o = this.overrides;
    if (!o) {
      return undefined;
    }
    return { fontSize: o.helperSize, fontFamily: o.fontFamily, lineHeight: o.lineHeight };
  }

  /** Clicks on the description, the text column or the row's gap toggle the switch too. */
  private handleRowClick(event: MouseEvent): void {
    const input = this.inputEl;
    const target = event.target;
    if (!input || !(target instanceof Element)) {
      return;
    }
    // The input handles itself, and a label click is already forwarded to it natively.
    if (target === input || target.closest('label') !== null || this.isDisabled) {
      return;
    }
    input.focus();
    input.click();
  }

  /** Disabled uses aria-disabled so the switch stays focusable; click and change are both guarded. */
  private handleControlClick(event: MouseEvent): void {
    if (this.isDisabled) {
      event.preventDefault();
    }
  }

  private handleChange(event: Event): void {
    // The native change does not cross the shadow boundary; the host re-dispatches a composed one.
    event.stopPropagation();
    const input = event.currentTarget as HTMLInputElement;
    if (this.isDisabled) {
      event.preventDefault();
      input.checked = this.checked;
      return;
    }
    // Every native toggle flips the value, so there is no next-equals-checked case to guard here.
    const next = input.checked;
    this.checked = next;
    this.dispatchEvent(
      new CustomEvent<SwitchChangeDetail>('change', {
        detail: { checked: next },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private applyOverrides(): void {
    for (const [binding, hook] of Object.entries(HOOKS) as [keyof typeof HOOKS, string][]) {
      const ref = this.overrides?.[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-switch': DsSwitch;
  }
}
