// packages/rn/src/Tabs.tsx
import * as React from 'react';
import { Animated, I18nManager, Platform, Pressable, ScrollView, Text as RNText, View } from 'react-native';
import type {
  LayoutChangeEvent,
  PressableStateCallbackType,
  ScrollEvent,
  ScrollViewInstance,
  TextStyle,
  ViewInstance,
  ViewStyle,
} from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import type { IconName } from './Icon';
import { toEasing, toFontWeight, toLineHeight, useReducedMotion, useTheme } from './theme';

export type TabsActivation = 'automatic' | 'manual';
export type TabsOrientation = 'horizontal' | 'vertical';
export type TabsFit = 'start' | 'fill';

/**
 * One tab. `badge` is a short count or status shown after the label ("3", "New"). The icon is
 * an Icon at `size: md` in the tab's current foreground color.
 */
export type TabsItem = {
  id: string;
  label: string;
  icon?: IconName | undefined;
  disabled?: boolean | undefined;
  badge?: string | undefined;
};

/** @deprecated Use `TabsItem`. */
export type TabsTab = TabsItem;

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type TabsOverridableBinding =
  | 'tabPaddingBlock'
  | 'tabPaddingInline'
  | 'tabGap'
  | 'listGap'
  | 'listBorder'
  | 'listBorderWidth'
  | 'panelGap'
  | 'badgeWeight'
  | 'badgeSize'
  | 'fontFamily'
  | 'fontSize'
  | 'fontWeight'
  | 'lineHeight'
  | 'radius'
  | 'transition'
  | 'disabledOpacity';

export interface TabsProps {
  /** The tabs in order. `badge` is a short count or status shown after the label ("3", "New"). */
  tabs: TabsItem[];
  /** One `TabPanel` per tab, in the same order, each with a matching `id`. Only the selected panel is rendered unless `keepMounted`. */
  children: React.ReactNode;
  /** Accessible name of the tab list ("Account sections"). Not shown visually. */
  label: string;
  /** Controlled selected tab id. Omit for uncontrolled. */
  value?: string | undefined;
  /** Initially selected tab id. Defaults to the first enabled tab. */
  defaultValue?: string | undefined;
  /**
   * `automatic` selects a tab as arrow keys move to it (fine when panels are cheap);
   * `manual` moves focus only and selects on Enter/Space (use when a panel loads data).
   * Arrow keys reach a tab list only through react-native-web or a hardware keyboard;
   * a touch always selects the touched tab.
   */
  activation?: TabsActivation | undefined;
  /** Vertical tab lists sit beside their panels and use Up/Down arrows. */
  orientation?: TabsOrientation | undefined;
  /** `start` packs tabs at the start; `fill` stretches them across the width (phones, two to four tabs). */
  fit?: TabsFit | undefined;
  /** Keep unselected panels in the tree (hidden) so their state survives switching. */
  keepMounted?: boolean | undefined;
  /** Fired when the selected tab changes, with the new id. */
  onChange?: ((value: string) => void) | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<TabsOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root `View`. */
  ref?: React.Ref<ViewInstance> | undefined;
}

export interface TabPanelProps {
  /** Must match a `tabs[].id`. */
  id: string;
  children?: React.ReactNode | undefined;
}

const COPY = {
  position: (index: number, total: number): string =>
    '{index} of {total}'.replace('{index}', String(index)).replace('{total}', String(total)),
} as const;

/** Wraps one tab's content. Rendered by `Tabs`, never directly. */
export function TabPanel({ children }: TabPanelProps): React.JSX.Element {
  // eslint-disable-next-line react/jsx-no-useless-fragment
  return <>{children}</>;
}

type TabLayout = { x: number; y: number; width: number; height: number };

function collectPanels(children: React.ReactNode): Map<string, React.ReactNode> {
  const panels = new Map<string, React.ReactNode>();
  React.Children.forEach(children, (child) => {
    if (React.isValidElement(child) && child.type === TabPanel) {
      const props = child.props as TabPanelProps;
      panels.set(props.id, props.children);
    }
  });
  return panels;
}

const isWeb = Platform.OS === 'web';

/** The DOM element react-native-web renders for a `Pressable`; this package has no DOM lib. */
type WebElement = { setAttribute(name: string, value: string): void; removeAttribute(name: string): void };

/** The computed writing direction of a react-native-web DOM node, or `undefined` off the web. */
function readDirection(node: unknown): boolean | undefined {
  const getComputedStyle = (globalThis as { getComputedStyle?: (element: unknown) => { direction?: string } })
    .getComputedStyle;
  if (!isWeb || node == null || getComputedStyle === undefined) {
    return undefined;
  }
  const direction = getComputedStyle(node).direction;
  return direction === undefined || direction === '' ? undefined : direction === 'rtl';
}

/**
 * Tabs — one region of a screen showing one of several equal-standing views.
 *
 * When to use: two to about seven alternative views of one region — the sections of a
 * settings page, "Overview / Activity / Files" on a record. `manual` activation when a
 * panel is expensive to show, `vertical` when there are many tabs and horizontal room is
 * short, `fill` on phones for two to four tabs. Not for navigation between pages (a nav
 * Landmark of Links), not for a sequence (Stepper), not for panels the user must compare.
 *
 * Renders a `ScrollView` (fit `start`, and every vertical list: overflowing tabs scroll, the
 * selected tab kept in view) or a row `View` whose tabs share the width (horizontal fit `fill`) of `Pressable`s
 * with `accessibilityRole="tab"`, `accessibilityState={{ selected, disabled }}` and
 * `accessibilityValue` from `copy.position`; the list carries `accessibilityRole="tablist"`
 * and `accessibilityLabel={label}`. The indicator is an `Animated.View` positioned from
 * each tab's measured layout and moved over `transition` with `motion.easing.standard`,
 * snapping under reduced motion. Panels are `View`s; only the selected one renders
 * unless `keepMounted`, when the rest stay mounted with `display: 'none'` and hidden
 * from assistive technology.
 *
 * Keyboard: on react-native-web the list handles `onKeyDown` — arrows along the
 * orientation move focus between enabled tabs and wrap (selecting under `automatic`),
 * Home/End jump, Enter/Space press the focused tab, and only the selected tab is a tab
 * stop (roving). On iOS/Android there is no key event on `View`/`Pressable`, so every
 * tab is its own accessibility stop, as on native, and a press always selects.
 */
export function Tabs({
  tabs,
  children,
  label,
  value,
  defaultValue,
  activation = 'automatic',
  orientation = 'horizontal',
  fit = 'start',
  keepMounted = false,
  onChange,
  overrides,
  ref,
}: TabsProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();
  const isHorizontal = orientation === 'horizontal';
  // `fill` is horizontal only: vertical tabs always span the list's inline size.
  const fill = fit === 'fill' && isHorizontal;
  const rtl = I18nManager.isRTL;

  const firstEnabledId = tabs.find((tab) => tab.disabled !== true)?.id;
  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = React.useState<string | undefined>(defaultValue ?? firstEnabledId);
  const currentValue = isControlled ? value : internalValue;

  const panelsById = React.useMemo(() => collectPanels(children), [children]);

  React.useEffect(() => {
    if (__DEV__) {
      tabs.forEach((tab) => {
        if (!panelsById.has(tab.id)) {
          console.warn(`Tabs: no TabPanel with id "${tab.id}" matching tabs[].id.`);
        }
      });
      panelsById.forEach((_panel, id) => {
        if (!tabs.some((tab) => tab.id === id)) {
          console.warn(`Tabs: TabPanel id "${id}" has no matching entry in tabs[]; it is not rendered.`);
        }
      });
    }
  }, [tabs, panelsById]);

  const tabPaddingBlock = overrides?.tabPaddingBlock ? (resolveToken(t, overrides.tabPaddingBlock) as number) : t.spaceSm;
  const tabPaddingInline = overrides?.tabPaddingInline ? (resolveToken(t, overrides.tabPaddingInline) as number) : t.spaceMd;
  const tabGap = overrides?.tabGap ? (resolveToken(t, overrides.tabGap) as number) : t.layoutGapTight;
  const listGap = overrides?.listGap ? (resolveToken(t, overrides.listGap) as number) : t.layoutGapNone;
  const listBorderColor = overrides?.listBorder ? (resolveToken(t, overrides.listBorder) as string) : t.colorBorder;
  const listBorderWidth = overrides?.listBorderWidth ? (resolveToken(t, overrides.listBorderWidth) as number) : t.borderWidthThin;
  const panelGap = overrides?.panelGap ? (resolveToken(t, overrides.panelGap) as number) : t.layoutGapLoose;
  // Lighter than the label's `fontWeight` so the count reads as secondary.
  const badgeWeight = overrides?.badgeWeight ? (resolveToken(t, overrides.badgeWeight) as number) : t.fontWeightRegular;
  const badgeSize = overrides?.badgeSize ? (resolveToken(t, overrides.badgeSize) as number) : t.fontSizeXs;
  const fontFamily = overrides?.fontFamily ? (resolveToken(t, overrides.fontFamily) as string) : t.fontFamilyBody;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t.fontSizeMd;
  const fontWeight = overrides?.fontWeight ? (resolveToken(t, overrides.fontWeight) as number) : t.fontWeightMedium;
  const lineHeightMultiplier = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;
  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusSm;
  const transitionDuration = overrides?.transition ? (resolveToken(t, overrides.transition) as number) : t.motionDurationFast;
  const disabledOpacity = overrides?.disabledOpacity ? (resolveToken(t, overrides.disabledOpacity) as number) : t.opacityDisabled;

  // Locked bindings: never read from overrides.
  const indicatorColor = t.colorControlSelectedBackground;
  const indicatorThickness = t.borderWidthFocus;

  const tabLayoutsRef = React.useRef(new Map<string, TabLayout>());
  const tabRefs = React.useRef(new Map<string, ViewInstance>());
  const hasMeasuredIndicatorRef = React.useRef(false);
  const indicatorOffset = React.useRef(new Animated.Value(0)).current;
  const indicatorExtent = React.useRef(new Animated.Value(0)).current;
  const scrollRef = React.useRef<ScrollViewInstance>(null);
  const scrollOffsetRef = React.useRef(0);
  const viewportSizeRef = React.useRef(0);
  const listWidthRef = React.useRef(0);
  const focusedIdRef = React.useRef<string | undefined>(undefined);
  const [focusedId, setFocusedId] = React.useState<string | undefined>(undefined);

  // Animates only when the selection moves between tabs (`animate`); the first measured placement
  // and every resize remeasure snap. A selection matching no tab collapses the bar to zero size.
  const updateIndicator = React.useCallback(
    (id: string | undefined, animate: boolean): void => {
      if (id === undefined || !tabs.some((tab) => tab.id === id)) {
        indicatorOffset.stopAnimation();
        indicatorExtent.stopAnimation();
        indicatorOffset.setValue(0);
        indicatorExtent.setValue(0);
        // The next placement is a first appearance, not a move between tabs: it snaps.
        hasMeasuredIndicatorRef.current = false;
        return;
      }
      const layout = tabLayoutsRef.current.get(id);
      if (!layout) {
        return;
      }
      // Measured from the list's inline-start edge. Yoga's layout `x` is physical, so under
      // I18nManager.isRTL it is read from the right; the bar is then placed with logical `start`.
      const offset = isHorizontal ? (rtl ? listWidthRef.current - layout.x - layout.width : layout.x) : layout.y;
      const extent = isHorizontal ? layout.width : layout.height;
      if (!animate || reducedMotion || !hasMeasuredIndicatorRef.current) {
        indicatorOffset.stopAnimation();
        indicatorExtent.stopAnimation();
        indicatorOffset.setValue(offset);
        indicatorExtent.setValue(extent);
        hasMeasuredIndicatorRef.current = true;
        return;
      }
      const easing = toEasing(t.motionEasingStandard);
      Animated.parallel([
        Animated.timing(indicatorOffset, { toValue: offset, duration: transitionDuration, easing, useNativeDriver: false }),
        Animated.timing(indicatorExtent, { toValue: extent, duration: transitionDuration, easing, useNativeDriver: false }),
      ]).start();
    },
    [tabs, isHorizontal, rtl, reducedMotion, transitionDuration, t.motionEasingStandard, indicatorOffset, indicatorExtent],
  );

  const scrollSelectedIntoView = React.useCallback(
    (id: string): void => {
      if (fill) {
        return;
      }
      const layout = tabLayoutsRef.current.get(id);
      const scrollView = scrollRef.current;
      if (!layout || !scrollView) {
        return;
      }
      const start = isHorizontal ? layout.x : layout.y;
      const end = start + (isHorizontal ? layout.width : layout.height);
      const viewStart = scrollOffsetRef.current;
      const viewEnd = viewStart + viewportSizeRef.current;
      let target: number | null = null;
      if (start < viewStart) {
        target = start;
      } else if (end > viewEnd) {
        target = end - viewportSizeRef.current;
      }
      if (target !== null) {
        const animated = !reducedMotion;
        scrollView.scrollTo(isHorizontal ? { x: Math.max(0, target), animated } : { y: Math.max(0, target), animated });
      }
    },
    [fill, isHorizontal, reducedMotion],
  );

  const previousValueRef = React.useRef(currentValue);
  React.useEffect(() => {
    const moved = previousValueRef.current !== currentValue;
    previousValueRef.current = currentValue;
    updateIndicator(currentValue, moved);
    if (currentValue !== undefined) {
      scrollSelectedIntoView(currentValue);
    }
  }, [currentValue, updateIndicator, scrollSelectedIntoView]);

  const handleTabLayout = (id: string, event: LayoutChangeEvent): void => {
    const { x, y, width, height } = event.nativeEvent.layout;
    const firstMeasure = !tabLayoutsRef.current.has(id);
    tabLayoutsRef.current.set(id, { x, y, width, height });
    if (id === currentValue) {
      // A remeasure (first appearance or resize) snaps; only a selection change animates.
      updateIndicator(id, false);
      if (firstMeasure) {
        scrollSelectedIntoView(id);
      }
    }
  };

  const handleScroll = (event: ScrollEvent): void => {
    const { x, y } = event.nativeEvent.contentOffset;
    scrollOffsetRef.current = isHorizontal ? x : y;
  };

  const handleViewportLayout = (event: LayoutChangeEvent): void => {
    const { width, height } = event.nativeEvent.layout;
    viewportSizeRef.current = isHorizontal ? width : height;
  };

  // The list's own width, for the RTL indicator offset; a resize remeasure snaps.
  const handleListLayout = (event: LayoutChangeEvent): void => {
    const { width } = event.nativeEvent.layout;
    if (width === listWidthRef.current) {
      return;
    }
    listWidthRef.current = width;
    if (rtl && isHorizontal) {
      updateIndicator(currentValue, false);
    }
  };

  const selectTab = (id: string): void => {
    const tab = tabs.find((candidate) => candidate.id === id);
    if (!tab || tab.disabled === true || id === currentValue) {
      return;
    }
    if (!isControlled) {
      setInternalValue(id);
    }
    onChange?.(id);
  };

  // react-native-web only: View has no key events on iOS/Android.
  const handleKeyDown = (event: {
    key?: string;
    nativeEvent?: { key?: string };
    currentTarget?: unknown;
    preventDefault?: () => void;
  }): void => {
    const key = event.key ?? event.nativeEvent?.key;
    const enabled = tabs.filter((tab) => tab.disabled !== true);
    if (enabled.length === 0 || key === undefined) {
      return;
    }
    const fromId = focusedIdRef.current ?? currentValue;
    const fromIndex = enabled.findIndex((tab) => tab.id === fromId);
    // Direction is read at keydown: the list's computed `direction` on web, I18nManager elsewhere.
    const isRtl = readDirection(event.currentTarget) ?? rtl;
    const nextKey = isHorizontal ? (isRtl ? 'ArrowLeft' : 'ArrowRight') : 'ArrowDown';
    const prevKey = isHorizontal ? (isRtl ? 'ArrowRight' : 'ArrowLeft') : 'ArrowUp';
    let targetIndex: number;
    if (key === nextKey) {
      targetIndex = fromIndex < 0 ? 0 : (fromIndex + 1) % enabled.length;
    } else if (key === prevKey) {
      targetIndex = fromIndex <= 0 ? enabled.length - 1 : fromIndex - 1;
    } else if (key === 'Home') {
      targetIndex = 0;
    } else if (key === 'End') {
      targetIndex = enabled.length - 1;
    } else {
      return;
    }
    event.preventDefault?.();
    const target = enabled[targetIndex]!;
    tabRefs.current.get(target.id)?.focus();
    if (activation === 'automatic') {
      selectTab(target.id);
    }
  };

  const keyProps: Record<string, unknown> = isWeb ? { onKeyDown: handleKeyDown } : {};

  const styleTokens: TabButtonStyleTokens = {
    paddingBlock: tabPaddingBlock,
    paddingInline: tabPaddingInline,
    gap: tabGap,
    minTarget: t.sizeTargetComfortable,
    radius,
    hoverBackground: t.colorBackgroundSubtle,
    disabledOpacity,
    focusRingColor: t.colorBorderFocus,
    focusRingWidth: t.borderWidthFocus,
    fontFamily,
    fontSize,
    fontWeight,
    lineHeightMultiplier,
    color: t.colorForegroundMuted,
    selectedColor: t.colorForegroundStrong,
    badgeColor: t.colorForegroundMuted,
    badgeWeight,
    badgeSize,
  };

  // The roving tab stop on web: while focus is inside the list it follows the focused tab (however
  // focus arrived); otherwise the selected tab, or the first enabled one when the selection is
  // disabled or matches nothing. Under `manual`, leaving the list forgets unselected arrow moves.
  const isEnabledId = (id: string | undefined): boolean => tabs.some((tab) => tab.id === id && tab.disabled !== true);
  const tabStopId = isEnabledId(focusedId) ? focusedId : isEnabledId(currentValue) ? currentValue : firstEnabledId;

  const tabButtons = tabs.map((tab, index) => (
    <TabButton
      key={tab.id}
      tab={tab}
      position={COPY.position(index + 1, tabs.length)}
      selected={tab.id === currentValue}
      tabStop={tab.id === tabStopId}
      fill={fill}
      horizontal={isHorizontal}
      styleTokens={styleTokens}
      onSelect={selectTab}
      onMeasured={handleTabLayout}
      onFocusChange={(id, focused) => {
        focusedIdRef.current = focused ? id : focusedIdRef.current === id ? undefined : focusedIdRef.current;
        setFocusedId(focusedIdRef.current);
      }}
      registerRef={(id, instance) => {
        if (instance) {
          tabRefs.current.set(id, instance);
        } else {
          tabRefs.current.delete(id);
        }
      }}
    />
  ));

  const listContentStyle: ViewStyle = {
    flexDirection: isHorizontal ? 'row' : 'column',
    alignItems: 'stretch',
    flexGrow: fill ? 1 : 0,
    gap: listGap,
    position: 'relative',
    // Logical edges: physical left/right are swapped under RTL by doLeftAndRightSwapInRTL, so a
    // branch on isRTL here would swap twice. The vertical rule sits at the inline end, by the panels.
    borderBottomWidth: isHorizontal ? listBorderWidth : 0,
    borderEndWidth: isHorizontal ? 0 : listBorderWidth,
    borderColor: listBorderColor,
  };

  // Inside the list at inset 0 of the bordered edge, against the border rather than over it.
  const indicatorStyle: Animated.WithAnimatedValue<ViewStyle> = isHorizontal
    ? {
        position: 'absolute',
        bottom: 0,
        start: indicatorOffset,
        height: indicatorThickness,
        width: indicatorExtent,
        backgroundColor: indicatorColor,
      }
    : {
        position: 'absolute',
        top: indicatorOffset,
        end: 0,
        width: indicatorThickness,
        height: indicatorExtent,
        backgroundColor: indicatorColor,
      };

  const indicator = (
    <Animated.View
      style={indicatorStyle}
      testID="Tabs.indicator"
      pointerEvents="none"
      aria-hidden
      accessibilityElementsHidden
      importantForAccessibility="no"
    />
  );

  const list = !fill ? (
      <ScrollView
        ref={scrollRef}
        horizontal={isHorizontal}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        onScroll={handleScroll}
        scrollEventThrottle={16} // literal-ok: one frame at 60 Hz, not a size
        onLayout={handleViewportLayout}
        style={{ flexGrow: 0 }}
      >
        <View
          {...keyProps}
          onLayout={handleListLayout}
          role="tablist"
          accessibilityRole="tablist"
          accessibilityLabel={label}
          aria-label={label}
          testID="Tabs.tablist"
          style={listContentStyle}
        >
          {tabButtons}
          {indicator}
        </View>
      </ScrollView>
    ) : (
      <View
        onLayout={(event) => {
          handleViewportLayout(event);
          handleListLayout(event);
        }}
        {...keyProps}
        role="tablist"
        accessibilityRole="tablist"
        accessibilityLabel={label}
        aria-label={label}
        testID="Tabs.tablist"
        style={listContentStyle}
      >
        {tabButtons}
        {indicator}
      </View>
    );

  return (
    <View ref={ref} testID="Tabs" style={{ flexDirection: isHorizontal ? 'column' : 'row', gap: panelGap }}>
      {list}
      <View style={{ flex: 1 }}>
        {tabs.map((tab) => {
          const selected = tab.id === currentValue;
          if ((!selected && !keepMounted) || !panelsById.has(tab.id)) {
            return null;
          }
          return (
            <View
              key={tab.id}
              testID="Tabs.panel"
              role="tabpanel"
              accessibilityLabel={tab.label}
              aria-label={tab.label}
              style={{ display: selected ? 'flex' : 'none' }}
              accessibilityElementsHidden={!selected}
              importantForAccessibility={selected ? 'auto' : 'no-hide-descendants'}
            >
              {panelsById.get(tab.id)}
            </View>
          );
        })}
      </View>
    </View>
  );
}

interface TabButtonStyleTokens {
  paddingBlock: number;
  paddingInline: number;
  gap: number;
  minTarget: number;
  radius: number;
  hoverBackground: string;
  disabledOpacity: number;
  focusRingColor: string;
  focusRingWidth: number;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  lineHeightMultiplier: number;
  color: string;
  selectedColor: string;
  badgeColor: string;
  badgeWeight: number;
  badgeSize: number;
}

interface TabButtonProps {
  tab: TabsItem;
  position: string;
  selected: boolean;
  tabStop: boolean;
  fill: boolean;
  horizontal: boolean;
  styleTokens: TabButtonStyleTokens;
  onSelect: (id: string) => void;
  onMeasured: (id: string, event: LayoutChangeEvent) => void;
  onFocusChange: (id: string, focused: boolean) => void;
  registerRef: (id: string, instance: ViewInstance | null) => void;
}

/** One tab. Its own component so focus/hover state does not re-render the whole list. */
function TabButton({
  tab,
  position,
  selected,
  tabStop,
  fill,
  horizontal,
  styleTokens: s,
  onSelect,
  onMeasured,
  onFocusChange,
  registerRef,
}: TabButtonProps): React.JSX.Element {
  const [focused, setFocused] = React.useState(false);
  const [hovered, setHovered] = React.useState(false);
  const disabled = tab.disabled === true;
  const foreground = selected ? s.selectedColor : s.color;
  const nodeRef = React.useRef<ViewInstance | null>(null);

  // react-native-web 0.21 ignores `accessibilityState` and `focusable`, so neither the disabled
  // state nor the roving tab stop would reach the DOM: every tab renders `tabindex="0"` and no
  // tab is announced as disabled. Both are set on the node itself here, as Button, Checkbox and
  // Disclosure do for `aria-disabled` — passing Pressable's own `disabled` prop instead would drop
  // the tab out of the accessibility tree, which the press guard exists to avoid. The attribute is
  // also what keeps the dimmed disabled tab out of axe's contrast check (WCAG 1.4.3 exempts
  // inactive components, and `opacity.disabled` over `color.foreground.muted` cannot reach 4.5:1).
  React.useEffect(() => {
    if (!isWeb) {
      return;
    }
    const node = nodeRef.current as unknown as WebElement | null;
    if (node === null) {
      return;
    }
    if (disabled) {
      node.setAttribute('aria-disabled', 'true');
    } else {
      node.removeAttribute('aria-disabled');
    }
    // The list is one tab stop: the selected tab, or the first enabled one. A disabled tab is
    // never a stop (it has nothing to reach), but stays in the tree and readable.
    node.setAttribute('tabindex', tabStop && !disabled ? '0' : '-1');
  }, [disabled, tabStop]);

  const rowStyle = ({ pressed }: PressableStateCallbackType): ViewStyle => ({
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: fill ? 1 : 0,
    flexShrink: fill ? 1 : 0,
    flexBasis: fill ? 0 : 'auto',
    justifyContent: fill && horizontal ? 'center' : 'flex-start',
    gap: s.gap,
    minHeight: s.minTarget,
    minWidth: s.minTarget,
    paddingVertical: s.paddingBlock,
    paddingHorizontal: s.paddingInline,
    borderRadius: s.radius,
    backgroundColor: (hovered || pressed) && !disabled ? s.hoverBackground : 'transparent',
    borderWidth: s.focusRingWidth,
    borderColor: focused ? s.focusRingColor : 'transparent',
    opacity: disabled ? s.disabledOpacity : 1,
  });

  const labelStyle: TextStyle = {
    fontFamily: s.fontFamily,
    fontSize: s.fontSize,
    fontWeight: toFontWeight(s.fontWeight),
    lineHeight: toLineHeight(s.fontSize, s.lineHeightMultiplier),
    color: foreground,
  };

  const badgeStyle: TextStyle = {
    fontFamily: s.fontFamily,
    fontSize: s.badgeSize,
    fontWeight: toFontWeight(s.badgeWeight),
    lineHeight: toLineHeight(s.badgeSize, s.lineHeightMultiplier),
    color: s.badgeColor,
  };

  // The badge is part of the name: label, a plain space, badge ("Inbox 3").
  const accessibleName = tab.badge !== undefined ? `${tab.label} ${tab.badge}` : tab.label;

  return (
    <Pressable
      ref={(instance: ViewInstance | null) => {
        nodeRef.current = instance;
        registerRef(tab.id, instance);
      }}
      role="tab"
      accessibilityRole="tab"
      accessibilityLabel={accessibleName}
      aria-label={accessibleName}
      accessibilityState={{ selected, disabled }}
      // react-native-web 0.21 ignores `accessibilityState`, so selection reaches the DOM through
      // this mirror (native merges both); `aria-disabled` and `tabindex` are set in the effect above.
      aria-selected={selected}
      aria-disabled={disabled}
      accessibilityValue={{ text: position }}
      // Never the native `disabled` prop: it would drop the tab from the accessibility order.
      onPress={() => {
        if (!disabled) {
          onSelect(tab.id);
        }
      }}
      onFocus={() => {
        setFocused(true);
        onFocusChange(tab.id, true);
      }}
      onBlur={() => {
        setFocused(false);
        onFocusChange(tab.id, false);
      }}
      onHoverIn={() => setHovered(true)}
      onHoverOut={() => setHovered(false)}
      onLayout={(event) => onMeasured(tab.id, event)}
      style={rowStyle}
      testID="Tabs.tab"
    >
      {tab.icon !== undefined ? (
        <View testID="Tabs.tabIcon" aria-hidden accessibilityElementsHidden importantForAccessibility="no">
          <Icon name={tab.icon} size="md" color={foreground} />
        </View>
      ) : null}
      <RNText numberOfLines={1} style={labelStyle} testID="Tabs.tabLabel">
        {tab.label}
      </RNText>
      {tab.badge !== undefined ? (
        <RNText testID="Tabs.tabBadge" style={badgeStyle} aria-hidden accessibilityElementsHidden importantForAccessibility="no">
          {tab.badge}
        </RNText>
      ) : null}
    </Pressable>
  );
}

// packages/lit/src/Tabs.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';
import type { IconName } from './Icon.js';

export type TabsActivation = 'automatic' | 'manual';
export type TabsOrientation = 'horizontal' | 'vertical';
export type TabsFit = 'start' | 'fill';

/** Shape of each entry in `tabs`. */
export interface TabsItem {
  id: string;
  label: string;
  icon?: IconName | undefined;
  disabled?: boolean | undefined;
  badge?: string | undefined;
}

/** @deprecated Use `TabsItem`. */
export type TabsTab = TabsItem;

/** Detail carried by the `change` CustomEvent. */
export interface TabsChangeDetail {
  value: string;
}

/** Overridable style hooks; see the `overrides` property. Locked bindings (`tabColor`, `tabSelectedColor`, `tabHoverBackground`, `indicator`, `indicatorThickness`, `badgeColor`, `minTarget`, `focusRing`, `focusRingWidth`) are excluded. */
export type TabsOverridableBinding =
  | 'tabPaddingBlock'
  | 'tabPaddingInline'
  | 'tabGap'
  | 'listGap'
  | 'listBorder'
  | 'listBorderWidth'
  | 'panelGap'
  | 'badgeWeight'
  | 'badgeSize'
  | 'fontFamily'
  | 'fontSize'
  | 'fontWeight'
  | 'lineHeight'
  | 'radius'
  | 'transition'
  | 'disabledOpacity';

const HOOKS: Record<TabsOverridableBinding, string> = {
  tabPaddingBlock: '--ds-tabs-tab-padding-block',
  tabPaddingInline: '--ds-tabs-tab-padding-inline',
  tabGap: '--ds-tabs-tab-gap',
  listGap: '--ds-tabs-list-gap',
  listBorder: '--ds-tabs-list-border',
  listBorderWidth: '--ds-tabs-list-border-width',
  panelGap: '--ds-tabs-panel-gap',
  badgeWeight: '--ds-tabs-badge-weight',
  badgeSize: '--ds-tabs-badge-size',
  fontFamily: '--ds-tabs-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-tabs-font-size',
  fontWeight: '--ds-tabs-font-weight',
  lineHeight: '--ds-tabs-line-height',
  radius: '--ds-tabs-radius',
  transition: '--ds-tabs-transition',
  disabledOpacity: '--ds-tabs-disabled-opacity',
};

type ControlsElement = HTMLElement & { ariaControlsElements?: readonly Element[] | null };

/**
 * `<ds-tab-panel>` — the light-DOM wrapper for one Tabs panel (anatomy: panel).
 *
 * `<ds-tabs>` manages its `hidden`, `role`, `tabindex` and `aria-label`
 * attributes; consumers only set `id` (matching a `tabs[].id`) and put content
 * inside. The panel is named with `aria-label` (the tab's label) rather than
 * `aria-labelledby`, because the tab lives in `<ds-tabs>`'s shadow root and a
 * reference cannot point into a descendant shadow tree.
 */
@customElement('ds-tab-panel')
export class DsTabPanel extends HTMLElement {
  // A plain element: no props besides `id`, no shadow root, no styles of its own.
  // Its layout and focus ring come from `<ds-tabs>` through `::slotted`.
  connectedCallback(): void {
    setAttr(this, 'data-ds', 'TabPanel');
    setAttr(this, 'data-part', 'panel');
  }
}

/**
 * `<ds-tabs>` — Tabs (category: navigation, APG pattern: tabs).
 *
 * `<ds-tabs label="Project sections" .tabs=${tabs}>` renders a `role="tablist"`
 * of native `<button role="tab">` in its shadow root. Panels are light-DOM
 * `<ds-tab-panel id>` children; `<ds-tabs>` stamps `role`, `tabindex` and
 * `aria-label` onto them and toggles `hidden` on the unselected ones. Panels
 * are never moved, detached or re-appended, so on Lit an unselected panel is
 * always kept in the tree (hidden) and `keepMounted` changes nothing further.
 *
 * The list is one roving-tabindex stop: arrow keys along `orientation` move
 * focus between enabled tabs and wrap, Home/End jump, `automatic` activation
 * selects as focus moves and `manual` selects on Enter/Space (a native button
 * click). Disabled tabs are `aria-disabled`, skipped and never selected.
 *
 * ## When to use
 *
 * Two to about seven views of equal standing that the user switches between
 * often. `manual` when a panel is expensive, `vertical` when horizontal room is
 * short, `fill` on phones for two to four tabs.
 *
 * ## When not to use
 *
 * Not for navigation between pages (a nav landmark of Links), not for a
 * sequence, and not when several panels must be visible at once.
 *
 * @fires change - The selected tab changed by user action; `detail: { value }`.
 * @slot - `<ds-tab-panel>` elements, one per tab, in the same order.
 */
@customElement('ds-tabs')
export class DsTabs extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      --ds-tabs-tab-color: var(--color-foreground-muted);
      --ds-tabs-tab-selected-color: var(--color-foreground-strong);
      --ds-tabs-tab-hover-background: var(--color-background-subtle);
      --ds-tabs-tab-padding-block: var(--space-sm);
      --ds-tabs-tab-padding-inline: var(--space-md);
      --ds-tabs-tab-gap: var(--layout-gap-tight);
      --ds-tabs-list-gap: var(--layout-gap-none);
      --ds-tabs-indicator: var(--color-control-selected-background);
      --ds-tabs-indicator-thickness: var(--border-width-focus);
      --ds-tabs-list-border: var(--color-border);
      --ds-tabs-list-border-width: var(--border-width-thin);
      --ds-tabs-panel-gap: var(--layout-gap-loose);
      --ds-tabs-badge-color: var(--color-foreground-muted);
      --ds-tabs-badge-weight: var(--font-weight-regular);
      --ds-tabs-badge-size: var(--font-size-xs);
      --ds-tabs-font-family: var(--font-family-body);
      --ds-tabs-font-size: var(--font-size-md);
      --ds-tabs-font-weight: var(--font-weight-medium);
      --ds-tabs-line-height: var(--font-line-height-normal);
      --ds-tabs-radius: var(--radius-sm);
      --ds-tabs-min-target: var(--size-target-comfortable);
      --ds-tabs-focus-ring: var(--color-border-focus);
      --ds-tabs-focus-ring-width: var(--border-width-focus);
      --ds-tabs-transition: var(--motion-duration-fast);
      --ds-tabs-disabled-opacity: var(--opacity-disabled);

      display: flex;
      flex-direction: column;
      /* panelGap: between the tab list and the panel */
      gap: var(--ds-tabs-panel-gap);
    }

    :host([hidden]) {
      display: none;
    }

    :host([orientation='vertical']) {
      flex-direction: row;
      align-items: flex-start;
    }

    [data-part='tablist'] {
      position: relative;
      box-sizing: border-box;
      display: flex;
      flex-direction: row;
      flex: none;
      gap: var(--ds-tabs-list-gap);
      border-block-end: var(--ds-tabs-list-border-width) solid var(--ds-tabs-list-border);
      overflow-x: auto;
      overflow-y: hidden;
      scrollbar-width: none;
    }

    :host([orientation='vertical']) [data-part='tablist'] {
      flex-direction: column;
      border-block-end: none;
      border-inline-end: var(--ds-tabs-list-border-width) solid var(--ds-tabs-list-border);
      overflow-x: hidden;
      overflow-y: auto;
    }

    [data-part='tab'] {
      position: relative;
      box-sizing: border-box;
      display: inline-flex;
      flex: none;
      align-items: center;
      justify-content: flex-start;
      gap: var(--ds-tabs-tab-gap);
      min-block-size: var(--ds-tabs-min-target);
      min-inline-size: var(--ds-tabs-min-target);
      margin: 0;
      padding-block: var(--ds-tabs-tab-padding-block);
      padding-inline: var(--ds-tabs-tab-padding-inline);
      border: 0;
      border-radius: var(--ds-tabs-radius);
      background: transparent;
      font-family: var(--ds-tabs-font-family);
      font-size: var(--ds-tabs-font-size);
      font-weight: var(--ds-tabs-font-weight);
      line-height: var(--ds-tabs-line-height);
      color: var(--ds-tabs-tab-color);
      white-space: nowrap;
      cursor: pointer;
    }

    /* fill is horizontal only: vertical tabs always span the list's inline size.
       A fill list does not scroll; tabs that overflow it are squeezed. */
    :host([fit='fill']:not([orientation='vertical'])) [data-part='tablist'] {
      overflow: hidden;
    }

    :host([fit='fill']:not([orientation='vertical'])) [data-part='tab'] {
      flex: 1 1 0%;
      justify-content: center;
    }

    [data-part='tab']:hover:not([aria-disabled='true']) {
      background: var(--ds-tabs-tab-hover-background);
    }

    /* Selection is also carried by aria-selected and the indicator, not color alone. */
    [data-part='tab'][aria-selected='true'] {
      color: var(--ds-tabs-tab-selected-color);
    }

    [data-part='tab']:focus-visible {
      outline: var(--ds-tabs-focus-ring-width) solid var(--ds-tabs-focus-ring);
      outline-offset: calc(-1 * var(--ds-tabs-focus-ring-width));
    }

    [data-part='tab'][aria-disabled='true'] {
      opacity: var(--ds-tabs-disabled-opacity);
      cursor: not-allowed;
    }

    [data-part='tabIcon'] {
      flex: none;
    }

    [data-part='tabLabel'] {
      min-inline-size: 0;
    }

    /* The badge is lighter than the label, so the count reads as secondary; its
       line height is the label's multiplier applied to the badge's own size. */
    [data-part='tabBadge'] {
      flex: none;
      font-size: var(--ds-tabs-badge-size);
      font-weight: var(--ds-tabs-badge-weight);
      line-height: var(--ds-tabs-line-height);
      color: var(--ds-tabs-badge-color);
    }

    [data-part='indicator'] {
      position: absolute;
      background: var(--ds-tabs-indicator);
      pointer-events: none;
    }

    /* Only a move between tabs animates; first placement, a newly appearing
       selected tab and a resize remeasure snap (data-animate is absent). */
    [data-part='indicator'][data-animate] {
      transition:
        transform var(--ds-tabs-transition) var(--motion-easing-standard),
        inline-size var(--ds-tabs-transition) var(--motion-easing-standard),
        block-size var(--ds-tabs-transition) var(--motion-easing-standard);
    }

    /* Horizontal: an underline flush against the list border at the bottom edge.
       Anchored physically (left, not inset-inline-start) because it is moved by
       translateX(offsetLeft), and offsetLeft measures from that same physical
       edge in both directions; a logical anchor would flip one and not the
       other in RTL. */
    :host(:not([orientation='vertical'])) [data-part='indicator'] {
      inset-block-end: 0;
      left: 0;
      block-size: var(--ds-tabs-indicator-thickness);
    }

    /* Vertical: a side bar flush against the inline-end edge, next to the panels. */
    :host([orientation='vertical']) [data-part='indicator'] {
      inset-block-start: 0;
      inset-inline-end: 0;
      inline-size: var(--ds-tabs-indicator-thickness);
    }

    ::slotted(*) {
      flex: 1 1 auto;
      min-inline-size: 0;
    }

    /* The panel has no binding of its own: its ring draws from the tab's hooks. */
    ::slotted([data-part='panel']:focus-visible) {
      outline: var(--ds-tabs-focus-ring-width) solid var(--ds-tabs-focus-ring);
      outline-offset: calc(-1 * var(--ds-tabs-focus-ring-width));
      border-radius: var(--ds-tabs-radius);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='indicator'][data-animate] {
        transition: none;
      }
    }
  `;

  /** The tabs in order. A property, not an attribute. */
  @property({ attribute: false }) accessor tabs: TabsItem[] = [];

  /** Accessible name of the tab list ("Account sections"). Not shown visually. */
  @property() accessor label: string = '';

  /** Controlled selected tab id. Omit for uncontrolled. */
  @property({ type: String, reflect: true }) accessor value: string | undefined;

  /** Initially selected tab id. Defaults to the first enabled tab. */
  @property({ attribute: 'default-value' }) accessor defaultValue: string | undefined;

  /** `automatic` selects a tab as arrow keys move to it; `manual` moves focus only and selects on Enter/Space. */
  @property({ type: String, reflect: true }) accessor activation: TabsActivation = 'automatic';

  /** Vertical tab lists sit beside their panels and use Up/Down arrows. */
  @property({ type: String, reflect: true }) accessor orientation: TabsOrientation = 'horizontal';

  /** `start` packs tabs at the start; `fill` stretches them across the width. Horizontal only: vertical tabs always span the list's inline size. */
  @property({ type: String, reflect: true }) accessor fit: TabsFit = 'start';

  /**
   * Keep unselected panels in the tree (hidden). On Lit panels are the
   * consumer's light-DOM children and are only ever hidden, never detached, so
   * both values keep them in the tree.
   */
  @property({ type: Boolean, attribute: 'keep-mounted' }) accessor keepMounted = false;

  /** Per-instance style overrides: `{ radius: 'radius.md' }`. Locked bindings are not accepted. */
  @property({ attribute: false }) accessor overrides: Partial<Record<TabsOverridableBinding, TokenRef | undefined>> | undefined;

  /** Uncontrolled selection, seeded from `defaultValue` (or the first enabled tab). */
  @state() private accessor internalValue: string | undefined;

  /** The tab carrying the roving tabindex. */
  @state() private accessor focusedId: string | null = null;

  @query('[data-part=tablist]') private accessor tablistEl!: HTMLElement | null;
  @query('[data-part=indicator]') private accessor indicatorEl!: HTMLElement | null;

  private resizeObserver: ResizeObserver | undefined;
  private lastScrolledId: string | null = null;
  /** The tab the indicator last sat under; `null` when it was at zero size (or never placed). */
  private indicatorId: string | null = null;
  private readonly warned = new Set<string>();

  /** The selected tab id, controlled or not. */
  get currentValue(): string | null {
    return this.value ?? this.internalValue ?? null;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Tabs');
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.resizeObserver?.disconnect();
    this.resizeObserver = undefined;
  }

  protected override firstUpdated(): void {
    if (this.tablistEl && typeof ResizeObserver !== 'undefined') {
      // A resize remeasure never animates.
      this.resizeObserver = new ResizeObserver(() => this.updateIndicator(false));
      this.resizeObserver.observe(this.tablistEl);
    }
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (this.internalValue === undefined && (changed.has('tabs') || changed.has('defaultValue'))) {
      this.internalValue = this.defaultValue ?? this.tabs.find((tab) => tab.disabled !== true)?.id;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.syncPanels();
    this.updateIndicator(true);
    this.scrollSelectedIntoView();
    this.warnInDev();
  }

  protected override render(): TemplateResult {
    const selected = this.currentValue;
    const rovingId = this.rovingId();
    return html`
      <div
        data-part="tablist"
        part="tablist"
        role="tablist"
        aria-label=${this.label}
        aria-orientation=${this.orientation}
        @keydown=${this.handleKeydown}
        @focusin=${this.handleFocusIn}
        @focusout=${this.handleFocusOut}
      >
        ${this.tabs.map((tab, index) => this.renderTab(tab, index, tab.id === selected, tab.id === rovingId))}
        <span data-part="indicator" part="indicator" aria-hidden="true"></span>
      </div>
      <slot @slotchange=${this.handleSlotChange}></slot>
    `;
  }

  private renderTab(tab: TabsItem, index: number, selected: boolean, roving: boolean): TemplateResult {
    const disabled = tab.disabled === true;
    const hasBadge = tab.badge !== undefined && tab.badge !== '';
    return html`
      <button
        type="button"
        data-part="tab"
        part="tab"
        role="tab"
        id="tab-${index}"
        data-id=${tab.id}
        aria-selected=${selected ? 'true' : 'false'}
        aria-disabled=${disabled ? 'true' : nothing}
        aria-labelledby=${hasBadge ? `tab-${index}-label tab-${index}-badge` : nothing}
        tabindex=${roving ? 0 : -1}
        @click=${() => this.handleTabClick(tab)}
      >
        ${tab.icon
          ? html`<ds-icon data-part="tabIcon" part="tabIcon" name=${tab.icon} size="md"></ds-icon>`
          : nothing}
        <span data-part="tabLabel" part="tabLabel" id="tab-${index}-label">${tab.label}</span>
        ${hasBadge
          ? html`<span data-part="tabBadge" part="tabBadge" id="tab-${index}-badge">${tab.badge}</span>`
          : nothing}
      </button>
    `;
  }

  /** The tab that is the list's single tab stop: the focused one, else the selected one, else the first enabled. */
  private rovingId(): string | null {
    const enabled = this.enabledTabs();
    const candidates = [this.focusedId, this.currentValue];
    for (const id of candidates) {
      if (id !== null && enabled.some((tab) => tab.id === id)) {
        return id;
      }
    }
    return enabled[0]?.id ?? null;
  }

  private readonly handleTabClick = (tab: TabsItem): void => {
    if (tab.disabled === true) {
      return;
    }
    this.focusedId = tab.id;
    this.selectTab(tab.id);
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    const vertical = this.orientation === 'vertical';
    // Only the orientation's own axis moves between tabs. In a right-to-left
    // layout ArrowLeft and ArrowRight swap, as in SegmentedControl; Up/Down,
    // Home and End do not.
    const rtl = getComputedStyle(this).direction === 'rtl';
    const nextKey = vertical ? 'ArrowDown' : rtl ? 'ArrowLeft' : 'ArrowRight';
    const prevKey = vertical ? 'ArrowUp' : rtl ? 'ArrowRight' : 'ArrowLeft';
    if (event.key === nextKey) {
      event.preventDefault();
      this.moveFocus(1);
    } else if (event.key === prevKey) {
      event.preventDefault();
      this.moveFocus(-1);
    } else if (event.key === 'Home') {
      event.preventDefault();
      this.focusEdge('first');
    } else if (event.key === 'End') {
      event.preventDefault();
      this.focusEdge('last');
    } else if ((event.key === 'Enter' || event.key === ' ') && this.activation === 'manual') {
      // Under automatic the focused tab is already selected and the native
      // button click takes the same path; only manual needs its own handler.
      const id = (event.target as HTMLElement | null)?.closest<HTMLElement>('[data-part=tab]')?.dataset['id'];
      const tab = this.tabs.find((candidate) => candidate.id === id);
      if (tab) {
        event.preventDefault();
        this.handleTabClick(tab);
      }
    }
  };

  /**
   * The roving stop follows the tab that actually has focus, however it got it —
   * Tab into the list, a click, or a programmatic `focus()` — so the next arrow
   * key moves from there rather than from the selected tab.
   */
  private readonly handleFocusIn = (event: FocusEvent): void => {
    const id = (event.target as HTMLElement | null)?.closest<HTMLElement>('[data-part=tab]')?.dataset['id'];
    if (id !== undefined && id !== this.focusedId) {
      this.focusedId = id;
    }
  };

  /** Leaving the list returns the tab stop to the selected tab. */
  private readonly handleFocusOut = (event: FocusEvent): void => {
    const next = event.relatedTarget as Node | null;
    if (next && this.tablistEl?.contains(next)) {
      return;
    }
    this.focusedId = null;
  };

  private handleSlotChange(): void {
    this.syncPanels();
    this.warnInDev();
  }

  private enabledTabs(): TabsItem[] {
    return this.tabs.filter((tab) => tab.disabled !== true);
  }

  private moveFocus(delta: number): void {
    const items = this.enabledTabs();
    if (items.length === 0) {
      return;
    }
    const currentIndex = items.findIndex((tab) => tab.id === this.rovingId());
    const nextIndex = (currentIndex + delta + items.length) % items.length;
    this.focusTab(items[nextIndex]!.id);
  }

  private focusEdge(edge: 'first' | 'last'): void {
    const items = this.enabledTabs();
    const target = edge === 'first' ? items[0] : items[items.length - 1];
    if (target) {
      this.focusTab(target.id);
    }
  }

  private focusTab(id: string): void {
    this.focusedId = id;
    if (this.activation === 'automatic') {
      this.selectTab(id);
    }
    void this.updateComplete.then(() => {
      this.tabElement(id)?.focus();
    });
  }

  /** Reports a user selection. Uncontrolled selection updates at once; controlled waits for `value` to change. */
  private selectTab(id: string): void {
    if (id === this.currentValue) {
      return;
    }
    if (this.value === undefined) {
      this.internalValue = id;
    }
    this.dispatchEvent(
      new CustomEvent<TabsChangeDetail>('change', { detail: { value: id }, bubbles: true, composed: true }),
    );
  }

  private tabElement(id: string): HTMLElement | null {
    return this.renderRoot.querySelector<HTMLElement>(`[data-part=tab][data-id="${CSS.escape(id)}"]`);
  }

  private panels(): HTMLElement[] {
    return Array.from(this.querySelectorAll<HTMLElement>(':scope > ds-tab-panel'));
  }

  /**
   * Labels each slotted panel, toggles `hidden` on the unselected ones and points
   * each tab's aria-controls at its panel. Never moves, detaches or re-appends a
   * panel, and writes an attribute only when its value differs.
   */
  private syncPanels(): void {
    const selected = this.currentValue;
    const panels = this.panels();
    for (const panel of panels) {
      const tab = this.tabs.find((candidate) => candidate.id === panel.id);
      if (!tab) {
        // A panel without a matching tab is not rendered (forced hidden); see warnInDev.
        if (!panel.hidden) panel.hidden = true;
        continue;
      }
      setAttr(panel, 'role', 'tabpanel');
      setAttr(panel, 'tabindex', '0');
      setAttr(panel, 'aria-label', tab.label);
      const hide = tab.id !== selected;
      if (panel.hidden !== hide) panel.hidden = hide;
    }
    for (const button of this.renderRoot.querySelectorAll<ControlsElement>('[data-part=tab]')) {
      if (!('ariaControlsElements' in button)) break;
      const panel = panels.find((candidate) => candidate.id === button.dataset['id']);
      const current = button.ariaControlsElements ?? null;
      if (panel ? current?.[0] !== panel : current !== null) {
        button.ariaControlsElements = panel ? [panel] : null;
      }
    }
  }

  /**
   * Places the indicator under the selected tab. It snaps on first placement,
   * when the selected tab first appears and on every resize remeasure
   * (`mayAnimate` false); only a move between two tabs sets `data-animate`.
   * With a selection that matches no tab it collapses to zero size.
   */
  private updateIndicator(mayAnimate: boolean): void {
    const indicator = this.indicatorEl;
    if (!indicator) {
      return;
    }
    const selected = this.currentValue;
    const tabEl = selected !== null ? this.tabElement(selected) : null;
    const vertical = this.orientation === 'vertical';
    if (!tabEl || selected === null) {
      indicator.removeAttribute('data-animate');
      indicator.style.transform = '';
      indicator.style.inlineSize = vertical ? '' : '0';
      indicator.style.blockSize = vertical ? '0' : '';
      this.indicatorId = null;
      return;
    }
    const animate = mayAnimate && this.indicatorId !== null && this.indicatorId !== selected;
    if (animate) {
      indicator.setAttribute('data-animate', '');
    } else if (this.indicatorId !== selected || !mayAnimate) {
      indicator.removeAttribute('data-animate');
    }
    this.indicatorId = selected;
    // Anchored at the list's physical left and moved by offsetLeft/offsetTop,
    // which measure from that same edge, so one measurement serves LTR and RTL.
    if (vertical) {
      indicator.style.transform = `translateY(${tabEl.offsetTop}px)`;
      indicator.style.blockSize = `${tabEl.offsetHeight}px`;
      indicator.style.inlineSize = '';
    } else {
      indicator.style.transform = `translateX(${tabEl.offsetLeft}px)`;
      indicator.style.inlineSize = `${tabEl.offsetWidth}px`;
      indicator.style.blockSize = '';
    }
  }

  /**
   * Keeps the selected tab visible when the list overflows, scrolling the list
   * only (never the page, so no scrollIntoView). Measured from the tab's box
   * within the list's client box, not from scrollLeft, so it holds in RTL
   * where scrollLeft is negative. A `fill` list does not scroll.
   */
  private scrollSelectedIntoView(): void {
    const selected = this.currentValue;
    const list = this.tablistEl;
    if (selected === null || selected === this.lastScrolledId || !list) {
      return;
    }
    const tabEl = this.tabElement(selected);
    if (!tabEl) {
      return;
    }
    this.lastScrolledId = selected;
    const vertical = this.orientation === 'vertical';
    if (this.fit === 'fill' && !vertical) {
      return;
    }
    const listBox = list.getBoundingClientRect();
    const tabBox = tabEl.getBoundingClientRect();
    const start = vertical ? tabBox.top - listBox.top - list.clientTop : tabBox.left - listBox.left - list.clientLeft;
    const size = vertical ? tabBox.height : tabBox.width;
    const client = vertical ? list.clientHeight : list.clientWidth;
    let delta = 0;
    if (start < 0) delta = start;
    else if (start + size > client) delta = start + size - client;
    if (delta === 0) {
      return;
    }
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const behavior: ScrollBehavior = reduced ? 'auto' : 'smooth';
    list.scrollBy(vertical ? { top: delta, behavior } : { left: delta, behavior });
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as TabsOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    const warn = (message: string): void => {
      if (this.warned.has(message)) return;
      this.warned.add(message);
      console.warn(message, this);
    };
    if (!this.label) {
      warn("<ds-tabs> requires a `label`, the tab list's accessible name.");
    }
    const panelIds = new Set(this.panels().map((panel) => panel.id));
    for (const tab of this.tabs) {
      if (!panelIds.has(tab.id)) {
        warn(`<ds-tabs> tab "${tab.id}" has no matching <ds-tab-panel id="${tab.id}">.`);
      }
    }
    const tabIds = new Set(this.tabs.map((tab) => tab.id));
    for (const id of panelIds) {
      if (!tabIds.has(id)) {
        warn(`<ds-tabs> has a <ds-tab-panel id="${id}"> with no matching entry in \`tabs\`; it stays hidden.`);
      }
    }
  }
}

function setAttr(el: Element, name: string, value: string): void {
  if (el.getAttribute(name) !== value) {
    el.setAttribute(name, value);
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-tabs': DsTabs;
    'ds-tab-panel': DsTabPanel;
  }
}
