// packages/rn/src/Toast.tsx
import * as React from 'react';
import { AccessibilityInfo, Animated, AppState, Platform, View } from 'react-native';
import type { AppStateStatus, ViewStyle } from 'react-native';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { Icon } from './Icon';
import type { IconName } from './Icon';
import { Text, TextForegroundContext } from './Text';
import type { TextOverridableBinding } from './Text';
import { toEasing, toLineHeight, useReducedMotion, useTheme } from './theme';

export type ToastTone = 'neutral' | 'success' | 'warning' | 'danger';
export type ToastDuration = 'short' | 'long' | 'persistent';
/**
 * Why the toast left the screen. `escape` belongs to the web keyboard model and is
 * never reported on native (there is no Escape to press inside a toast); it stays in
 * the union so handlers are shared across platforms.
 */
export type ToastDismissReason = 'timeout' | 'dismiss-button' | 'escape' | 'action' | 'replaced' | 'programmatic';

/**
 * The style bindings a caller may replace with a different token; see the
 * component's overrides contract. `stackGap`, `regionInset` and `layer` govern the
 * region a `ToastProvider` renders (there is one region, not one per toast) and are
 * no-ops when passed to a standalone `Toast`; every other key is in effect on the
 * toast itself.
 */
export type ToastOverridableBinding =
  | 'radius'
  | 'shadow'
  | 'paddingBlock'
  | 'paddingInline'
  | 'gap'
  | 'stackGap'
  | 'regionInset'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'layer'
  | 'enter'
  | 'enterOffset'
  | 'exit';

export interface ToastProps {
  /** One sentence saying what happened ("Message sent", "3 files deleted"). */
  message: string;
  /** Sets the leading icon; `neutral` has none. Toasts do not use tinted backgrounds — the icon and message carry the tone. */
  tone?: ToastTone | undefined;
  /** Label for a single action button ("Undo", "View"). When present the toast stays until dismissed and pauses while touched. */
  actionLabel?: string | undefined;
  /**
   * `short` ≈ 5s, `long` ≈ 10s (`motion.duration.loop` × 6 / × 12, so themes without motion
   * still get sensible times), `persistent` until dismissed. When `actionLabel` is set or `tone` is
   * `danger` the toast is persistent regardless of this prop (a dev warning notes the override only
   * when `duration` was passed explicitly as `short` or `long`). If `motion.duration.loop` is 0,
   * both durations are persistent.
   */
  duration?: ToastDuration | undefined;
  /** Shows a dismiss button. Persistent toasts are always dismissible regardless of this prop. */
  dismissible?: boolean | undefined;
  /** Stable identity; a `ToastProvider` showing a toast with the same toastId replaces the previous one instead of stacking. Unused by a standalone `Toast`. */
  toastId?: string | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<ToastOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the action button is activated, before `onDismiss('action')`. The toast then dismisses. */
  onAction?: (() => void) | undefined;
  /** Fired once the toast has left the screen, with the reason it left. */
  onDismiss?: ((reason: ToastDismissReason) => void) | undefined;
}

const COPY = {
  dismissLabel: 'Dismiss',
  regionLabel: 'Notifications',
} as const;

/** `icon`: Icon `name={tone}` with `color.inverse.status.{tone}` forwarded to Icon's `overrides.color`; `neutral` renders no icon. */
const TONE_ICON = {
  neutral: null,
  success: { name: 'success', color: 'color.inverse.status.success' },
  warning: { name: 'warning', color: 'color.inverse.status.warning' },
  danger: { name: 'danger', color: 'color.inverse.status.danger' },
} as const satisfies Record<ToastTone, { name: IconName; color: TokenRef } | null>;

/** constants.shortDuration / longDuration: `motion.duration.loop` × multiplier, in ms. */
const DURATION_MULTIPLIER = { short: 6, long: 12 } as const satisfies Record<'short' | 'long', number>;

/**
 * Typography belongs to the composed Text, so `fontFamily`, `fontSize` and `lineHeight` are
 * forward-only: the toast never styles them itself, and the value — an override or this
 * default — is always passed to Text's `overrides` under the same name.
 */
type ToastTextBinding = ToastOverridableBinding & TextOverridableBinding;

const TEXT_DEFAULT: Record<ToastTextBinding, TokenRef> = {
  fontFamily: 'font.family.body', // literal-ok: a TokenRef forwarded to Text, not a font stack
  fontSize: 'font.size.md',
  lineHeight: 'font.lineHeight.normal',
};

type PauseSource = 'touch' | 'hidden';

/**
 * Set by a `ToastProvider` when `dismiss()` asks a shown toast to leave, so it runs its
 * exit transition before reporting. `null` outside a provider and while the toast stays.
 */
const ToastExitContext: React.Context<ToastDismissReason | null> = React.createContext<ToastDismissReason | null>(null);

/**
 * Toast — says "done" and gets out of the way. Confirms an action just taken,
 * offers one chance to undo it, and leaves without being asked.
 *
 * When to use: confirm a completed action the user did not have to watch (sent,
 * saved, deleted, copied), offer Undo for a reversible action, or report a
 * background result. Match `tone` to the outcome. Never toast an error that needs
 * fixing (use Alert) or anything requiring more than one action. Show toasts through
 * `ToastProvider` + `useToast()` / `toast()`; a notification is an event, not a place
 * in the tree.
 *
 * Renders a `View` carrying the tone's icon (`neutral` has none), the message, an
 * optional action `Button` and a dismiss `Button` — both `ghost` + `inverse`, so they
 * read against `color.inverse.surface` without Toast restyling them.
 * React Native has no `status` role: `danger` gets `accessibilityRole="alert"` and
 * `accessibilityLiveRegion="assertive"`, every other tone no role and `polite`
 * (Android). iOS ignores live regions, so the message is announced once on mount
 * (queued for polite tones, interrupting for `danger`).
 *
 * The toast rises and fades in over `enter` and fades out over `exit` before
 * `onDismiss` fires; both are instant under reduced motion. A timer dismisses it after
 * the effective duration unless that is `persistent` — which it always is once
 * `actionLabel` is set or `tone` is `danger` (a `__DEV__` warning flags the mismatch).
 * The timer pauses while the toast is touched and while the app is not in the
 * foreground.
 *
 * Acknowledged native limits: F6 and Escape have no native equivalent, so toasts are
 * reached by swiping through the accessibility order and left through the dismiss
 * button, which is always shown for persistent toasts.
 */
export function Toast({
  message,
  tone = 'neutral',
  actionLabel,
  duration: durationProp,
  dismissible = true,
  overrides,
  onAction,
  onDismiss,
}: ToastProps): React.JSX.Element {
  const duration: ToastDuration = durationProp ?? 'short';
  const { tokens: t } = useTheme();
  const reducedMotion = useReducedMotion();

  const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusMd;
  const shadow = overrides?.shadow ? (resolveToken(t, overrides.shadow) as typeof t.shadowOverlay) : t.shadowOverlay;
  const paddingBlock = overrides?.paddingBlock ? (resolveToken(t, overrides.paddingBlock) as number) : t.spaceSm;
  const paddingInline = overrides?.paddingInline ? (resolveToken(t, overrides.paddingInline) as number) : t.spaceMd;
  const gap = overrides?.gap ? (resolveToken(t, overrides.gap) as number) : t.layoutGapNormal;
  const maxWidth = overrides?.maxWidth ? (resolveToken(t, overrides.maxWidth) as number) : t.layoutMaxWidthProse;
  const fontSize = overrides?.fontSize ? (resolveToken(t, overrides.fontSize) as number) : t.fontSizeMd;
  const lineHeightMultiplier = overrides?.lineHeight ? (resolveToken(t, overrides.lineHeight) as number) : t.fontLineHeightNormal;
  const enterDuration = overrides?.enter ? (resolveToken(t, overrides.enter) as number) : t.motionDurationBase;
  const enterOffset = overrides?.enterOffset ? (resolveToken(t, overrides.enterOffset) as number) : t.space2;
  const exitDuration = overrides?.exit ? (resolveToken(t, overrides.exit) as number) : t.motionDurationFast;

  // An action or danger tone forces the toast to stay until dismissed, regardless of `duration`;
  // so does a theme whose `motion.duration.loop` is 0 (no timed durations can be computed).
  const forcedPersistent = actionLabel !== undefined || tone === 'danger';
  const loopResolved = t.motionDurationLoop > 0;
  const effectiveDuration: ToastDuration = forcedPersistent || !loopResolved ? 'persistent' : duration;
  const isDismissible = effectiveDuration === 'persistent' ? true : dismissible;
  const icon = TONE_ICON[tone];
  const lineHeight = toLineHeight(fontSize, lineHeightMultiplier);

  const [dismissReason, setDismissReason] = React.useState<ToastDismissReason | null>(null);
  const dismissedRef = React.useRef(false);
  const requestDismiss = React.useCallback((reason: ToastDismissReason) => {
    if (dismissedRef.current) {
      return;
    }
    dismissedRef.current = true;
    setDismissReason(reason);
  }, []);

  React.useEffect(() => {
    // Only an explicit `short` or `long` warns; the default never does. It fires again
    // whenever a change to `duration`, `actionLabel` or `tone` enters that case.
    if (__DEV__ && forcedPersistent && (durationProp === 'short' || durationProp === 'long')) {
      console.warn(
        `Toast: \`duration: ${durationProp}\` is ignored — a toast with an action or \`tone: danger\` is persistent until dismissed.`,
      );
    }
  }, [forcedPersistent, durationProp]);

  React.useEffect(() => {
    if (Platform.OS === 'ios' && message !== '') {
      if (tone === 'danger') {
        AccessibilityInfo.announceForAccessibility(message);
      } else {
        AccessibilityInfo.announceForAccessibilityWithOptions(message, { queue: true });
      }
    }
    // Announces once, when the toast is shown.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // The auto-dismiss timer. Read once at mount from the resolved `motion.duration.loop`.
  const totalDurationRef = React.useRef<number | null>(
    effectiveDuration === 'persistent' ? null : t.motionDurationLoop * DURATION_MULTIPLIER[effectiveDuration],
  );

  // `dismiss(toastId?)` on the provider: leave through the exit transition like any other reason.
  const exitSignal = React.useContext(ToastExitContext);
  React.useEffect(() => {
    if (exitSignal !== null) {
      requestDismiss(exitSignal);
    }
  }, [exitSignal, requestDismiss]);
  const remainingRef = React.useRef(totalDurationRef.current ?? 0);
  const timerStartRef = React.useRef(0);
  const timerRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  const pausedRef = React.useRef<Set<PauseSource>>(new Set());

  const stopTimer = React.useCallback(() => {
    if (timerRef.current !== null) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
      remainingRef.current = Math.max(0, remainingRef.current - (Date.now() - timerStartRef.current));
    }
  }, []);

  const runTimer = React.useCallback(() => {
    if (totalDurationRef.current === null || dismissedRef.current || timerRef.current !== null || pausedRef.current.size > 0) {
      return;
    }
    timerStartRef.current = Date.now();
    timerRef.current = setTimeout(() => {
      timerRef.current = null;
      requestDismiss('timeout');
    }, remainingRef.current);
  }, [requestDismiss]);

  const pause = React.useCallback(
    (source: PauseSource) => {
      pausedRef.current.add(source);
      stopTimer();
    },
    [stopTimer],
  );

  const resume = React.useCallback(
    (source: PauseSource) => {
      pausedRef.current.delete(source);
      runTimer();
    },
    [runTimer],
  );

  React.useEffect(() => {
    if (AppState.currentState !== 'active' && AppState.currentState != null) {
      pausedRef.current.add('hidden');
    }
    runTimer();
    const subscription = AppState.addEventListener('change', (state: AppStateStatus) => {
      if (state === 'active') {
        resume('hidden');
      } else {
        pause('hidden');
      }
    });
    return () => {
      subscription.remove();
      if (timerRef.current !== null) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
    };
  }, [runTimer, pause, resume]);

  // Rises and fades in on mount, instant under reduced motion.
  const progress = React.useRef(new Animated.Value(0)).current;
  React.useEffect(() => {
    if (reducedMotion) {
      progress.setValue(1);
      return undefined;
    }
    const animation = Animated.timing(progress, {
      toValue: 1,
      duration: enterDuration,
      easing: toEasing(t.motionEasingStandard),
      // react-native-web has no native animated module.
      useNativeDriver: false,
    });
    animation.start();
    return () => animation.stop();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fades out before leaving, so `onDismiss` (after-change) fires once the toast is gone.
  React.useEffect(() => {
    if (dismissReason === null) {
      return undefined;
    }
    stopTimer();
    // Immediate under reduced motion or when the exit time does not resolve to a positive duration.
    if (reducedMotion || !(exitDuration > 0)) {
      onDismiss?.(dismissReason);
      return undefined;
    }
    const animation = Animated.timing(progress, {
      toValue: 0,
      duration: exitDuration,
      easing: toEasing(t.motionEasingStandard),
      useNativeDriver: false,
    });
    animation.start(({ finished }) => {
      if (finished) {
        onDismiss?.(dismissReason);
      }
    });
    return () => animation.stop();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dismissReason]);

  const handleAction = (): void => {
    if (dismissedRef.current) {
      return;
    }
    onAction?.();
    requestDismiss('action');
  };

  const toastStyle: Animated.WithAnimatedValue<ViewStyle> = {
    flexDirection: 'row',
    alignItems: 'center',
    // No `alignSelf`: the region centers its toasts at every width (`alignItems: 'center'`),
    // and a standalone toast takes the cross-axis alignment of whatever holds it.
    gap,
    maxWidth,
    paddingVertical: paddingBlock,
    paddingHorizontal: paddingInline,
    borderRadius: radius,
    backgroundColor: t.colorInverseSurface,
    opacity: progress,
    transform: [{ translateY: progress.interpolate({ inputRange: [0, 1], outputRange: [enterOffset, 0] }) }],
    ...shadow,
  };

  const iconCellStyle: ViewStyle = {
    height: lineHeight,
    justifyContent: 'center',
  };

  const messageStyle: ViewStyle = {
    flexShrink: 1,
    flexGrow: 1,
  };

  // Typography is forward-only: the value, an override or the binding's own token, is
  // always passed to the composed Text rather than drawn on the toast.
  const textOverrides = React.useMemo<Partial<Record<TextOverridableBinding, TokenRef | undefined>>>(() => {
    const next: Partial<Record<TextOverridableBinding, TokenRef | undefined>> = {};
    for (const binding of Object.keys(TEXT_DEFAULT) as ToastTextBinding[]) {
      next[binding] = overrides?.[binding] ?? TEXT_DEFAULT[binding];
    }
    return next;
  }, [overrides]);

  return (
    <Animated.View
      testID="Toast"
      style={toastStyle}
      accessibilityRole={tone === 'danger' ? 'alert' : undefined}
      accessibilityLiveRegion={tone === 'danger' ? 'assertive' : 'polite'}
      accessibilityLabel={message}
      onTouchStart={() => pause('touch')}
      onTouchEnd={() => resume('touch')}
      onTouchCancel={() => resume('touch')}
    >
      {icon !== null ? (
        <View testID="Toast.icon" style={iconCellStyle} accessibilityElementsHidden importantForAccessibility="no">
          <Icon name={icon.name} overrides={{ color: icon.color }} />
        </View>
      ) : null}
      <View testID="Toast.message" style={messageStyle}>
        {/* text: color.inverse.foreground, locked. Text's own `color` binding is locked, so the
            inverse surface provides its foreground to the subtree instead. */}
        <TextForegroundContext.Provider value={t.colorInverseForeground}>
          {/* React Native Text has no `element`, so the message part takes only `size: md`. */}
          <Text size="md" overrides={textOverrides}>
            {message}
          </Text>
        </TextForegroundContext.Provider>
      </View>
      {actionLabel !== undefined ? (
        <View testID="Toast.actionButton">
          <Button label={actionLabel} variant="ghost" size="sm" inverse onPress={handleAction} />
        </View>
      ) : null}
      {isDismissible ? (
        /* dismissColor: native has no currentColor, so the glyph takes color.inverse.link
           through Icon's own `overrides`, the sanctioned way to color a composed child. */
        <View testID="Toast.dismissButton">
          <Button
            label={COPY.dismissLabel}
            variant="ghost"
            size="sm"
            iconOnly
            inverse
            leadingIcon={<Icon name="close" overrides={{ color: 'color.inverse.link' }} />}
            onPress={() => requestDismiss('dismiss-button')}
          />
        </View>
      ) : null}
    </Animated.View>
  );
}

/** Options for the imperative `toast()` call; the same shape as `ToastProps`. */
export type ToastOptions = ToastProps;

/** What `toast()` resolves to once the toast has left the screen. */
export interface ToastResult {
  reason: ToastDismissReason;
}

export interface ToastContextValue {
  /**
   * Shows a toast and resolves with `{ reason }` when it leaves. Showing a toast with a
   * `toastId` already on screen replaces it; the replaced toast leaves immediately with
   * reason `replaced`, as does the oldest one when a fourth is shown.
   */
  toast: (options: ToastOptions) => Promise<ToastResult>;
  /**
   * Dismisses the toast with this `toastId`, or every shown toast when called with no id,
   * with reason `programmatic`. Each leaves through its exit transition.
   */
  dismiss: (toastId?: string | undefined) => void;
}

export interface ToastProviderProps {
  children?: React.ReactNode;
  /** Region-level overrides (`stackGap`, `regionInset`, `layer`). Bindings for the toasts themselves belong on each `toast()` call's own `overrides`. */
  overrides?: Partial<Record<ToastOverridableBinding, TokenRef | undefined>> | undefined;
}

/** One shown toast, tracked by a `ToastProvider`. */
interface ToastEntry {
  id: string;
  options: ToastOptions;
  resolve: (result: ToastResult) => void;
  /** Set when `dismiss()` asked this toast to leave; it reports once its exit transition ends. */
  exiting: ToastDismissReason | null;
}

const ToastContext: React.Context<ToastContextValue | null> = React.createContext<ToastContextValue | null>(null);

/** The mounted `ToastProvider`'s dispatcher, so the module-level `toast()` works outside React. */
let activeDispatch: ToastContextValue | null = null;

const MAX_TOASTS = 3; // literal-ok: the doc's stack limit ("Up to three toasts stack"), not a design token

/**
 * ToastProvider — mounted once at the app root. Renders the notification region (an
 * absolutely positioned `View` at `layer.toast` z-index, `regionInset` above the
 * bottom edge, centered, up to three toasts stacked newest-at-the-bottom) and exposes
 * `useToast()` / the module-level `toast()` so any code can show one.
 */
export function ToastProvider({ children, overrides }: ToastProviderProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const [entries, setEntries] = React.useState<ToastEntry[]>([]);
  const entriesRef = React.useRef<ToastEntry[]>([]);
  const counterRef = React.useRef(0);

  const commit = React.useCallback((next: ToastEntry[]) => {
    entriesRef.current = next;
    setEntries(next);
  }, []);

  /** Removes an entry and reports `reason` to its caller; a no-op when it is already gone. */
  const settle = React.useCallback(
    (id: string, reason: ToastDismissReason) => {
      const entry = entriesRef.current.find((candidate) => candidate.id === id);
      if (entry === undefined) {
        return;
      }
      commit(entriesRef.current.filter((candidate) => candidate.id !== id));
      entry.options.onDismiss?.(reason);
      entry.resolve({ reason });
    },
    [commit],
  );

  const toast = React.useCallback(
    (options: ToastOptions): Promise<ToastResult> =>
      new Promise<ToastResult>((resolve) => {
        counterRef.current += 1;
        const id = options.toastId ?? `toast-${counterRef.current}`;
        settle(id, 'replaced');
        const next: ToastEntry[] = [...entriesRef.current, { id, options, resolve, exiting: null }];
        // A toast already playing its exit transition does not count toward the three, so the
        // oldest one still staying is the one evicted. Only one can exceed at a time.
        const staying = next.filter((candidate) => candidate.exiting === null);
        const evicted = staying.length > MAX_TOASTS ? staying[0] : undefined;
        commit(evicted === undefined ? next : next.filter((candidate) => candidate !== evicted));
        if (evicted !== undefined) {
          // `replaced`: it leaves immediately, without its exit transition.
          evicted.options.onDismiss?.('replaced');
          evicted.resolve({ reason: 'replaced' });
        }
      }),
    [commit, settle],
  );

  const dismiss = React.useCallback(
    (toastId?: string | undefined) => {
      commit(
        entriesRef.current.map((entry) =>
          (toastId === undefined || entry.id === toastId) && entry.exiting === null ? { ...entry, exiting: 'programmatic' } : entry,
        ),
      );
    },
    [commit],
  );

  const value = React.useMemo<ToastContextValue>(() => ({ toast, dismiss }), [toast, dismiss]);

  React.useEffect(() => {
    activeDispatch = value;
    return () => {
      if (activeDispatch === value) {
        activeDispatch = null;
      }
    };
  }, [value]);

  const regionInset = overrides?.regionInset ? (resolveToken(t, overrides.regionInset) as number) : t.layoutGutter;
  const stackGap = overrides?.stackGap ? (resolveToken(t, overrides.stackGap) as number) : t.layoutGapTight;
  const layer = overrides?.layer ? (resolveToken(t, overrides.layer) as number) : t.layerToast;

  const regionStyle: ViewStyle = {
    position: 'absolute',
    left: regionInset,
    right: regionInset,
    bottom: regionInset,
    alignItems: 'center',
    gap: stackGap,
    zIndex: layer,
  };

  return (
    <ToastContext.Provider value={value}>
      {children}
      {/* `role="region"` carries the name: the region exists before any toast, and an
          `accessibilityLabel` on a View with no role is an `aria-label` on a bare <div>
          under react-native-web (axe `aria-prohibited-attr`). It is also the role the web
          and Lit regions use, so the three platforms announce the same landmark. */}
      <View testID="Toast.region" style={regionStyle} pointerEvents="box-none" role="region" accessibilityLabel={COPY.regionLabel}>
        {entries.map((entry) => (
          <ToastExitContext.Provider key={entry.id} value={entry.exiting}>
            <Toast {...entry.options} onDismiss={(reason) => settle(entry.id, reason)} />
          </ToastExitContext.Provider>
        ))}
      </View>
    </ToastContext.Provider>
  );
}

/** Returns `{ toast, dismiss }` bound to the nearest `ToastProvider`. Warns and no-ops without one. */
export function useToast(): ToastContextValue {
  const context = React.useContext(ToastContext);
  if (context === null) {
    if (__DEV__) {
      console.warn('useToast: no ToastProvider is mounted. Wrap the app root in <ToastProvider>.');
    }
    return { toast: () => new Promise<ToastResult>(() => undefined), dismiss: () => undefined };
  }
  return context;
}

/** Shows a toast from anywhere, not just from inside a component. Requires a `ToastProvider` at the app root; warns and never resolves otherwise. */
export function toast(options: ToastOptions): Promise<ToastResult> {
  if (activeDispatch === null) {
    if (__DEV__) {
      console.warn('toast(): no ToastProvider is mounted. Wrap the app root in <ToastProvider>.');
    }
    return new Promise<ToastResult>(() => undefined);
  }
  return activeDispatch.toast(options);
}

// packages/lit/src/Toast.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';
import './Text.js';
import './Button.js';
import type { TextOverridableBinding } from './Text.js';

export type ToastTone = 'neutral' | 'success' | 'warning' | 'danger';
export type ToastDuration = 'short' | 'long' | 'persistent';
export type ToastDismissReason = 'timeout' | 'dismiss-button' | 'action' | 'replaced';

/** Detail carried by the `action` CustomEvent (none). */
export type ToastActionDetail = void;

/** Detail carried by the `dismiss` CustomEvent. */
export interface ToastDismissDetail {
  reason: ToastDismissReason;
}

/** copy.dismissLabel */
const COPY_DISMISS_LABEL = 'Dismiss';
/** copy.regionLabel */
const COPY_REGION_LABEL = 'Notifications';

/** Negates a boolean attribute: `no-dismiss` present means `dismissible` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

/** `duration: short` multiplies motion.duration.loop by this to get ~5s. */
const SHORT_MULTIPLIER = 6;
/** `duration: long` multiplies motion.duration.loop by this to get ~10s. */
const LONG_MULTIPLIER = 12;

/**
 * Safety margin, in ms, added on top of the read `--ds-toast-exit` duration
 * before forcing removal if `transitionend` never fires. Not a design token —
 * a defensive timing, not a motion one.
 */
const EXIT_FALLBACK_BUFFER_MS = 50;

/** At most this many toasts stack; showing another evicts the oldest. */
const MAX_TOASTS = 3;

/** Overridable style hooks; see the `overrides` property. `surface`, `text`, `icon`, `actionColor`, `dismissColor`, `focusRingInverse`, `minTarget`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type ToastOverridableBinding =
  | 'radius'
  | 'shadow'
  | 'paddingBlock'
  | 'paddingInline'
  | 'gap'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'enter'
  | 'exit';

const HOOKS: Record<ToastOverridableBinding, string> = {
  radius: '--ds-toast-radius',
  shadow: '--ds-toast-shadow',
  paddingBlock: '--ds-toast-padding-block',
  paddingInline: '--ds-toast-padding-inline',
  gap: '--ds-toast-gap',
  maxWidth: '--ds-toast-max-width',
  fontFamily: '--ds-toast-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-toast-font-size',
  lineHeight: '--ds-toast-line-height',
  enter: '--ds-toast-enter',
  exit: '--ds-toast-exit',
};

/** Overridable style hooks for `<ds-toast-region>`; see its `overrides` property. `layer` sets the region's stacking context. */
export type ToastRegionOverridableBinding = 'stackGap' | 'regionInset' | 'layer';

const REGION_HOOKS: Record<ToastRegionOverridableBinding, string> = {
  stackGap: '--ds-toast-region-stack-gap',
  regionInset: '--ds-toast-region-inset',
  layer: '--ds-toast-region-layer',
};

function prefersReducedMotion(): boolean {
  return typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/** Reads a `--motion-duration-*`-shaped custom property off `el` and returns it in ms. */
function readDurationMs(el: HTMLElement, varName: string): number {
  const raw = getComputedStyle(el).getPropertyValue(varName).trim();
  if (raw.endsWith('ms')) {
    return parseFloat(raw);
  }
  if (raw.endsWith('s')) {
    return parseFloat(raw) * 1000;
  }
  return 0;
}

/**
 * `<ds-toast>` — Toast (category: feedback, APG pattern: alert).
 *
 * One notification. Never created directly by consumers — the `toast()`
 * function below appends it to a lazily-created `<ds-toast-region>` in
 * `document.body`. The host takes `role="status"` (`"alert"` for `tone:
 * "danger"`) and its accessible name through `ElementInternals`, set to
 * `message`, so the live region and its name live in the light DOM tree.
 * Inside the shadow root: the tone icon (`neutral` has none), the message as
 * `<ds-text>`, an inverse-ghost `<ds-button>` for the action, and an
 * inverse-ghost icon-only `<ds-button>` for dismiss. A timer dismisses the
 * toast after `duration`, pausing while hovered, focused, or the page is
 * hidden; persistent toasts have no timer. Escape and the dismiss button both
 * dismiss with a short exit transition (instant under reduced motion), after
 * which the element removes itself.
 *
 * ## When to use
 *
 * Use a Toast to confirm a completed action that the user did not have to
 * watch, to offer Undo for a reversible action, or to report a background
 * result. Match `tone` to the outcome; use `duration: "persistent"` whenever
 * there is an action, and for `danger`, so nobody misses the one they needed.
 *
 * ## When not to use
 *
 * Not for errors that need fixing (an Alert next to the problem), not for
 * anything the user must read (Alert or Dialog), and not for more than one
 * action.
 *
 * @fires action - The action button was activated. Followed by `dismiss` with `reason: 'action'`.
 * @fires dismiss - The toast left the screen, with `{ reason }` (`timeout`, `dismiss-button`, `action`, or `replaced`).
 * @csspart toast - The container (anatomy: toast).
 * @csspart icon - The tone icon (anatomy: icon).
 * @csspart message - The `<ds-text>` (anatomy: message).
 * @csspart action-button - The action `<ds-button>` (anatomy: actionButton).
 * @csspart dismiss-button - The dismiss `<ds-button>` (anatomy: dismissButton).
 */
@customElement('ds-toast')
export class DsToast extends LitElement {
  static override styles = css`
    :host {
      display: block;
      box-sizing: border-box;
      --ds-toast-radius: var(--radius-md);
      --ds-toast-shadow: var(--shadow-overlay);
      --ds-toast-padding-block: var(--space-sm);
      --ds-toast-padding-inline: var(--space-md);
      --ds-toast-gap: var(--layout-gap-normal);
      --ds-toast-max-width: var(--layout-max-width-prose);
      --ds-toast-font-family: var(--font-family-body);
      --ds-toast-font-size: var(--font-size-md);
      --ds-toast-line-height: var(--font-line-height-normal);
      --ds-toast-enter: var(--motion-duration-base);
      --ds-toast-exit: var(--motion-duration-fast);
      max-inline-size: var(--ds-toast-max-width);
    }

    :host([hidden]) {
      display: none;
    }

    .container {
      box-sizing: border-box;
      display: flex;
      align-items: center;
      gap: var(--ds-toast-gap);
      padding-block: var(--ds-toast-padding-block);
      padding-inline: var(--ds-toast-padding-inline);
      border-radius: var(--ds-toast-radius);
      box-shadow: var(--ds-toast-shadow);
      /* surface: color.inverse.surface, locked — inverted like Tooltip, so it floats above any page surface */
      background: var(--color-inverse-surface);
      opacity: 1;
      transform: translateY(0);
      transition:
        opacity var(--ds-toast-enter) var(--motion-easing-standard),
        transform var(--ds-toast-enter) var(--motion-easing-standard);
    }

    @starting-style {
      .container {
        opacity: 0;
        transform: translateY(var(--space-2));
      }
    }

    /* exit: motion.duration.fast, replacing the enter duration while leaving */
    .container.closing {
      opacity: 0;
      transform: translateY(var(--space-2));
      transition-duration: var(--ds-toast-exit);
    }

    @media (prefers-reduced-motion: reduce) {
      .container {
        transition: none;
      }
    }

    .icon {
      flex: none;
    }

    /* icon: color.inverse.status.{tone}, locked — neutral renders no icon */
    :host([tone='success']) .icon {
      color: var(--color-inverse-status-success);
    }
    :host([tone='warning']) .icon {
      color: var(--color-inverse-status-warning);
    }
    :host([tone='danger']) .icon {
      color: var(--color-inverse-status-danger);
    }

    .message {
      flex: 1 1 auto;
      min-inline-size: 0;
    }

    .action,
    .dismiss {
      flex: none;
    }
  `;

  /** One sentence, past tense, saying what happened ("Message sent", "3 files deleted"). Also the toast's accessible name. */
  @property() message!: string;

  /** Sets the leading icon; `neutral` has none. Toasts never use tinted backgrounds — the icon and message carry the tone. */
  @property({ reflect: true }) tone: ToastTone = 'neutral';

  /** Label for a single action button ("Undo", "View"). Recommended as `persistent` so there is time to use it. */
  @property({ attribute: 'action-label' }) actionLabel?: string;

  /** `short` ≈ 5s, `long` ≈ 10s (motion.duration.loop × 6 / × 12), `persistent` until dismissed. */
  @property({ reflect: true }) duration: ToastDuration = 'short';

  /** Stable identity; showing a toast with the same `toastId` replaces this one instead of stacking. Named `toastId` (attribute `toast-id`) so it does not collide with the DOM `id`. */
  @property({ attribute: 'toast-id' }) toastId?: string;

  /** Shows a dismiss button. Persistent toasts are always dismissible regardless of this value. Exposed as the negated `no-dismiss` attribute (a boolean attribute cannot express `false` for a prop that defaults `true`). */
  @property({ attribute: 'no-dismiss', converter: NEGATED_BOOLEAN_CONVERTER }) dismissible = true;

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<ToastOverridableBinding, TokenRef>>;

  @query('.container') private readonly containerEl!: HTMLElement;

  @state() private closing = false;

  private readonly internals: ElementInternals;
  private dismissed = false;
  private timerId?: ReturnType<typeof setTimeout>;
  private remainingMs: number | null = null;
  private timerStartedAt = 0;
  private pointerOver = false;
  private focused = false;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  private get showDismiss(): boolean {
    return this.dismissible || this.duration === 'persistent';
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Toast');
    this.addEventListener('pointerenter', this.handlePointerEnter);
    this.addEventListener('pointerleave', this.handlePointerLeave);
    this.addEventListener('focusin', this.handleFocusIn);
    this.addEventListener('focusout', this.handleFocusOut);
    this.addEventListener('keydown', this.handleKeydown);
    document.addEventListener('visibilitychange', this.handleVisibilityChange);
    this.startTimer();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.clearTimer();
    this.removeEventListener('pointerenter', this.handlePointerEnter);
    this.removeEventListener('pointerleave', this.handlePointerLeave);
    this.removeEventListener('focusin', this.handleFocusIn);
    this.removeEventListener('focusout', this.handleFocusOut);
    this.removeEventListener('keydown', this.handleKeydown);
    document.removeEventListener('visibilitychange', this.handleVisibilityChange);
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('tone')) {
      // role="status" implies aria-live="polite"; role="alert" implies assertive.
      this.internals.role = this.tone === 'danger' ? 'alert' : 'status';
    }
    if (changed.has('message')) {
      // A literal attribute, not `internals.ariaLabel`: ARIAMixin values set through
      // ElementInternals aren't visible to the accessible-name computation the test
      // suite uses (only real attributes are), though real assistive tech reads either.
      if (this.message) {
        this.setAttribute('aria-label', this.message);
      } else {
        this.removeAttribute('aria-label');
      }
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.warnInDev();
  }

  protected override render() {
    const textOverrides: Partial<Record<TextOverridableBinding, TokenRef>> = {
      color: 'color.inverse.foreground',
    };
    if (this.overrides?.fontFamily) {
      textOverrides.fontFamily = this.overrides.fontFamily;
    }
    if (this.overrides?.fontSize) {
      textOverrides.fontSize = this.overrides.fontSize;
    }
    if (this.overrides?.lineHeight) {
      textOverrides.lineHeight = this.overrides.lineHeight;
    }

    return html`
      <div class="container${this.closing ? ' closing' : ''}" part="toast">
        ${this.tone === 'neutral'
          ? nothing
          : html`<ds-icon class="icon" part="icon" name=${this.tone}></ds-icon>`}
        <ds-text class="message" part="message" element="span" size="md" .overrides=${textOverrides}
          >${this.message}</ds-text
        >
        ${this.actionLabel
          ? html`
              <ds-button
                class="action"
                part="action-button"
                variant="ghost"
                inverse
                size="sm"
                label=${this.actionLabel}
                @press=${this.handleActionPress}
              ></ds-button>
            `
          : nothing}
        ${this.showDismiss
          ? html`
              <ds-button
                class="dismiss"
                part="dismiss-button"
                variant="ghost"
                inverse
                size="sm"
                icon-only
                label=${COPY_DISMISS_LABEL}
                @press=${this.handleDismissPress}
              >
                <ds-icon slot="leading-icon" name="close" inline></ds-icon>
              </ds-button>
            `
          : nothing}
      </div>
    `;
  }

  private readonly handleActionPress = (event: Event): void => {
    // Keep the button's `press` inside the toast; consumers listen for `action`/`dismiss`.
    event.stopPropagation();
    this.dispatchEvent(new CustomEvent<ToastActionDetail>('action', { bubbles: true, composed: true }));
    this.requestDismiss('action');
  };

  private readonly handleDismissPress = (event: Event): void => {
    event.stopPropagation();
    this.requestDismiss('dismiss-button');
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      event.stopPropagation();
      // No 'escape' reason exists on ToastDismissReason; treated as an explicit manual dismissal.
      this.requestDismiss('dismiss-button');
    }
  };

  private readonly handlePointerEnter = (): void => {
    this.pointerOver = true;
    this.pauseTimer();
  };

  private readonly handlePointerLeave = (): void => {
    this.pointerOver = false;
    this.maybeResumeTimer();
  };

  private readonly handleFocusIn = (): void => {
    this.focused = true;
    this.pauseTimer();
  };

  private readonly handleFocusOut = (): void => {
    this.focused = false;
    this.maybeResumeTimer();
  };

  private readonly handleVisibilityChange = (): void => {
    if (document.hidden) {
      this.pauseTimer();
    } else {
      this.maybeResumeTimer();
    }
  };

  /** Dispatches `dismiss` and plays the exit transition; called for every dismissal path, including eviction by `toast()`. */
  public requestDismiss(reason: ToastDismissReason): void {
    if (this.dismissed) {
      return;
    }
    this.dismissed = true;
    this.clearTimer();
    this.dispatchEvent(
      new CustomEvent<ToastDismissDetail>('dismiss', { detail: { reason }, bubbles: true, composed: true }),
    );
    this.playExit();
  }

  private computeDurationMs(): number | null {
    if (this.duration === 'persistent') {
      return null;
    }
    const loop = readDurationMs(this, '--motion-duration-loop');
    return loop * (this.duration === 'long' ? LONG_MULTIPLIER : SHORT_MULTIPLIER);
  }

  private startTimer(): void {
    const ms = this.computeDurationMs();
    if (ms === null) {
      return;
    }
    this.remainingMs = ms;
    this.scheduleTimer();
  }

  private scheduleTimer(): void {
    if (this.remainingMs === null) {
      return;
    }
    this.timerStartedAt = Date.now();
    this.timerId = setTimeout(() => this.requestDismiss('timeout'), Math.max(0, this.remainingMs));
  }

  private pauseTimer(): void {
    if (this.timerId === undefined || this.remainingMs === null) {
      return;
    }
    clearTimeout(this.timerId);
    this.timerId = undefined;
    this.remainingMs -= Date.now() - this.timerStartedAt;
  }

  private maybeResumeTimer(): void {
    if (this.dismissed || this.timerId !== undefined || this.remainingMs === null) {
      return;
    }
    if (this.pointerOver || this.focused || document.hidden) {
      return;
    }
    this.scheduleTimer();
  }

  private clearTimer(): void {
    clearTimeout(this.timerId);
    this.timerId = undefined;
  }

  /** Plays the exit transition (instant under reduced motion), then removes the element from the DOM. */
  private playExit(): void {
    const finish = (): void => {
      const region = this.closest('ds-toast-region');
      if (this.contains(document.activeElement) && region instanceof DsToastRegion) {
        region.restoreFocus();
      }
      this.remove();
    };

    if (prefersReducedMotion()) {
      finish();
      return;
    }

    this.closing = true;
    const container = this.containerEl;
    if (!container) {
      finish();
      return;
    }

    let settled = false;
    const settle = (): void => {
      if (settled) {
        return;
      }
      settled = true;
      container.removeEventListener('transitionend', handleTransitionEnd);
      finish();
    };
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target === container && event.propertyName === 'opacity') {
        settle();
      }
    };
    container.addEventListener('transitionend', handleTransitionEnd);
    const exitMs = readDurationMs(this, '--ds-toast-exit');
    setTimeout(settle, exitMs + EXIT_FALLBACK_BUFFER_MS);
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ToastOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.message) {
      console.warn('<ds-toast> requires a `message`.', this);
    }
    if (this.actionLabel && this.duration !== 'persistent') {
      console.warn('<ds-toast> with an `action-label` should be `duration="persistent"` (WCAG 2.2.1).', this);
    }
    if (this.tone === 'danger' && this.duration !== 'persistent') {
      console.warn('<ds-toast tone="danger"> should be `duration="persistent"`.', this);
    }
  }
}

/**
 * `<ds-toast-region>` — the live region that holds `<ds-toast>` children (anatomy: region).
 *
 * Auto-created in `document.body` by `toast()`; not meant to be authored
 * directly. Takes `role="region"` and `aria-label` through `ElementInternals`
 * and `aria-live="polite"` as an attribute (an ARIAMixin property does not
 * exist for it), fixed at `regionInset` from the viewport edge — bottom-start
 * on wide screens, bottom-center on phones — stacking `<ds-toast>` children
 * with `stackGap` between them, newest at the bottom. A document-level `F6`
 * handler moves focus into the first toast's action or dismiss button, and
 * back out again on a second press.
 */
@customElement('ds-toast-region')
export class DsToastRegion extends LitElement {
  static override styles = css`
    :host {
      position: fixed;
      inset-inline: var(--ds-toast-region-inset);
      inset-block-end: var(--ds-toast-region-inset);
      z-index: var(--ds-toast-region-layer);
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: var(--ds-toast-region-stack-gap);
      pointer-events: none;
      --ds-toast-region-stack-gap: var(--layout-gap-tight);
      --ds-toast-region-inset: var(--layout-gutter);
      --ds-toast-region-layer: var(--layer-toast);
    }

    :host([hidden]) {
      display: none;
    }

    ::slotted(ds-toast) {
      pointer-events: auto;
    }

    /* Bottom-start (not centered) once there is room beside the toast's own max width. */
    @media (min-width: 572px) { /* literal-ok: breakpoint from layout.maxWidth.prose */
      :host {
        align-items: flex-start;
        inset-inline-end: auto;
      }
    }
  `;

  /** Per-instance style overrides: `{ regionInset: 'layout.gutter.wide' }`. */
  @property({ attribute: false }) overrides?: Partial<Record<ToastRegionOverridableBinding, TokenRef>>;

  private readonly internals: ElementInternals;

  /** What had focus before `F6` moved it into the region, restored on the next `F6` or on dismissal. */
  private previouslyFocused: HTMLElement | null = null;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'ToastRegion');
    this.setAttribute('aria-live', 'polite');
    this.internals.role = 'region';
    this.internals.ariaLabel = COPY_REGION_LABEL;
    document.addEventListener('keydown', this.handleDocumentKeydown);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener('keydown', this.handleDocumentKeydown);
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render() {
    return html`<slot></slot>`;
  }

  /** Sends focus back to whatever had it before `F6` moved focus in here. Called on the second `F6` and on dismissal. */
  public restoreFocus(): void {
    const target = this.previouslyFocused;
    this.previouslyFocused = null;
    target?.focus();
  }

  private readonly handleDocumentKeydown = (event: KeyboardEvent): void => {
    if (event.key !== 'F6' || this.childElementCount === 0) {
      return;
    }
    if (this.contains(document.activeElement)) {
      event.preventDefault();
      this.restoreFocus();
      return;
    }
    const first = this.firstElementChild as HTMLElement | null;
    const target = first?.shadowRoot?.querySelector<HTMLElement>('.action, .dismiss') ?? first ?? undefined;
    if (target) {
      event.preventDefault();
      this.previouslyFocused = document.activeElement as HTMLElement | null;
      target.focus();
    }
  };

  private applyOverrides(): void {
    for (const binding of Object.keys(REGION_HOOKS) as ToastRegionOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = REGION_HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

/** Options for `toast()`. */
export interface ToastOptions {
  message: string;
  tone?: ToastTone;
  actionLabel?: string;
  duration?: ToastDuration;
  dismissible?: boolean;
  /** Stable identity; showing a toast with the same toastId replaces the previous one instead of stacking. */
  toastId?: string;
}

/** Resolution of the promise `toast()` returns, once the toast leaves the screen. */
export interface ToastResult {
  reason: ToastDismissReason;
}

let regionEl: DsToastRegion | null = null;

function ensureRegion(): DsToastRegion {
  if (regionEl === null || !regionEl.isConnected) {
    regionEl = document.createElement('ds-toast-region') as DsToastRegion;
    document.body.appendChild(regionEl);
  }
  return regionEl;
}

/**
 * Shows a toast, since a notification is an event, not a place in the tree.
 * Returns a promise that resolves once the toast leaves the screen (see
 * `ToastResult.reason`). Showing a toast with the same `toastId` as one
 * already visible replaces it (`reason: 'replaced'` for the old one) instead
 * of stacking; more than `MAX_TOASTS` visible evicts the oldest the same way.
 */
export function toast(options: ToastOptions): Promise<ToastResult> {
  const region = ensureRegion();

  const current = Array.from(region.querySelectorAll('ds-toast')) as DsToast[];

  if (options.toastId !== undefined) {
    const existing = current.find((el) => el.toastId === options.toastId);
    existing?.requestDismiss('replaced');
  }

  if (current.length >= MAX_TOASTS) {
    current[0]?.requestDismiss('replaced');
  }

  const el = document.createElement('ds-toast') as DsToast;
  el.toastId = options.toastId;
  el.message = options.message;
  el.tone = options.tone ?? 'neutral';
  el.duration = options.duration ?? 'short';
  if (options.actionLabel !== undefined) {
    el.actionLabel = options.actionLabel;
  }
  if (options.dismissible !== undefined) {
    el.dismissible = options.dismissible;
  }

  region.appendChild(el);

  return new Promise<ToastResult>((resolve) => {
    el.addEventListener(
      'dismiss',
      (event) => resolve({ reason: (event as CustomEvent<ToastDismissDetail>).detail.reason }),
      { once: true },
    );
  });
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-toast': DsToast;
    'ds-toast-region': DsToastRegion;
  }
}
