// packages/rn/src/Toolbar.tsx
import * as React from 'react';
import { ScrollView, View } from 'react-native';
import type { ViewInstance, ViewStyle } from 'react-native';
import Svg, { Defs, LinearGradient, Rect, Stop } from 'react-native-svg';
import { resolveToken } from '@design-schema/tokens';
import type { TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { Divider } from './Divider';
import { Search } from './Search';
import { SegmentedControl } from './SegmentedControl';
import { Select } from './Select';
import { useTheme } from './theme';

export type ToolbarOrientation = 'horizontal' | 'vertical';
export type ToolbarOverflow = 'wrap' | 'menu' | 'scroll';
export type ToolbarSize = 'sm' | 'md';
export type ToolbarDensity = 'compact' | 'comfortable';

/** The style bindings a caller may replace with a different token; see the component's overrides contract. */
export type ToolbarOverridableBinding =
  | 'border'
  | 'borderWidth'
  | 'radius'
  | 'paddingInline'
  | 'paddingBlock'
  | 'itemGap'
  | 'groupGap'
  | 'separatorLength'
  | 'fadeWidth';

export interface ToolbarProps {
  /** What the toolbar controls ("Formatting", "Table actions"). Not visible; read by assistive technology. */
  label: string;
  /**
   * Controls in order: Buttons (usually `ghost` or `secondary`, `iconOnly` for glyph tools),
   * SegmentedControl, Select, Switch. Group related controls with `ToolbarGroup`; a Divider is
   * drawn between two adjacent groups only (a bare control next to a group gets `itemGap`, no
   * Divider), and only between top-level groups — a group nested inside a group takes no
   * separator and no `size` pass. Consumers never place Dividers themselves.
   */
  children: React.ReactNode;
  /** Vertical toolbars sit beside a canvas; the controls stack along the column. */
  orientation?: ToolbarOrientation | undefined;
  /**
   * What happens when controls do not fit: `wrap` onto more rows, or `scroll` with the edges
   * faded. `menu` (the default) renders as `scroll` on React Native — children are opaque and
   * nothing measures them; an explicitly passed `menu` warns once in development.
   */
  overflow?: ToolbarOverflow | undefined;
  /**
   * Default for child Buttons, SegmentedControls, Selects and Searches (recognised by component
   * identity) that do not set their own; applied to direct children and to each ToolbarGroup's
   * children. A child's own `size` wins.
   */
  size?: ToolbarSize | undefined;
  /** Gap between controls: tight or normal rhythm. */
  density?: ToolbarDensity | undefined;
  /** Replace individual style bindings with a different token from the theme. The only per-instance styling surface — there is no `style` prop. */
  overrides?: Partial<Record<ToolbarOverridableBinding, TokenRef | undefined>> | undefined;
  /** The root `View`, for measurement or accessibility focus. */
  ref?: React.Ref<ViewInstance> | undefined;
}

export interface ToolbarGroupProps {
  /** The group's accessible name. */
  label?: string | undefined;
  /** The group's controls, in order. */
  children: React.ReactNode;
  /** The group's `View`. */
  ref?: React.Ref<ViewInstance> | undefined;
}

const ITEM_GAP = {
  compact: 'layoutGapTight',
  comfortable: 'layoutGapNormal',
} as const;

/**
 * Components that take a toolbar `size`, recognised by identity — never by probing for a prop —
 * mapped to the toolbar sizes each one actually accepts. Search has no `sm`, so a `sm` toolbar
 * leaves every Search at its own default.
 */
const SIZED_COMPONENTS: ReadonlyMap<unknown, ReadonlySet<ToolbarSize>> = new Map<unknown, ReadonlySet<ToolbarSize>>([
  [Button, new Set<ToolbarSize>(['sm', 'md'])],
  [SegmentedControl, new Set<ToolbarSize>(['sm', 'md'])],
  [Select, new Set<ToolbarSize>(['sm', 'md'])],
  [Search, new Set<ToolbarSize>(['md'])],
]);

let warnedMenu = false;

interface ToolbarLayout {
  group: ViewStyle;
}

const ToolbarLayoutContext: React.Context<ToolbarLayout | null> = React.createContext<ToolbarLayout | null>(null);

/** Children with fragments expanded, so a fragment of controls counts as its controls. */
function flattenChildren(children: React.ReactNode, prefix = ''): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  React.Children.toArray(children).forEach((child) => {
    if (React.isValidElement<{ children?: React.ReactNode }>(child) && child.type === React.Fragment) {
      out.push(...flattenChildren(child.props.children, `${prefix}${String(child.key)}`));
    } else if (React.isValidElement(child)) {
      out.push(prefix === '' ? child : React.cloneElement(child, { key: `${prefix}${String(child.key)}` }));
    } else {
      out.push(child);
    }
  });
  return out;
}

/** Applies the toolbar's `size` to a sized package control that did not set its own. */
function withSize(node: React.ReactNode, size: ToolbarSize): React.ReactNode {
  if (!React.isValidElement<{ size?: unknown }>(node)) return node;
  if (!SIZED_COMPONENTS.get(node.type)?.has(size) || node.props.size !== undefined) return node;
  return React.cloneElement(node, { size });
}

function isGroup(node: React.ReactNode): node is React.ReactElement<ToolbarGroupProps> {
  return React.isValidElement(node) && node.type === ToolbarGroup;
}

/**
 * ToolbarGroup — related controls inside a Toolbar. A `View` with `role="group"` and
 * `accessibilityLabel` from `label`, laid out along the toolbar axis with `itemGap` between its
 * controls. The Toolbar draws a Divider between two adjacent groups.
 */
export function ToolbarGroup({ label, children, ref }: ToolbarGroupProps): React.JSX.Element {
  const layout = React.useContext(ToolbarLayoutContext);
  const outside = layout === null;
  React.useEffect(() => {
    if (__DEV__ && outside) {
      console.warn('ToolbarGroup: render it inside a Toolbar; outside one it has no orientation, wrapping or gap.');
    }
  }, [outside]);
  return (
    <View
      ref={ref}
      role="group"
      accessibilityLabel={label}
      aria-label={label}
      style={layout?.group}
      testID="Toolbar.group"
    >
      {children}
    </View>
  );
}

/**
 * Toolbar — keeps a set of related controls together: one labelled `toolbar` container
 * whose controls keep their own roles and names.
 *
 * When to use: controls that act on the same thing and are used together (text formatting,
 * a table's row actions, a filter–sort–export row). Not for page navigation, a form's
 * submit row, a single control, or as a generic horizontal Stack.
 *
 * Renders a `View` with `accessibilityRole="toolbar"` and `accessibilityLabel` carrying
 * `background` (locked), `border`, `borderWidth`, `radius` and `paddingInline`/`paddingBlock`.
 * Direct children (fragments expanded) and `ToolbarGroup`s are laid out along the axis with
 * `itemGap` (by `density`). Between two adjacent groups the Toolbar renders a
 * `Toolbar.separator` wrapper `separatorLength` long across the axis, padded along it by
 * `groupGap − itemGap` (clamped at 0), holding a `Divider` across the axis with `spacing: none`
 * that stretches to fill it. Sized children (Button, SegmentedControl, Select, Search) without
 * their own `size` receive the toolbar's.
 *
 * `overflow: wrap` wraps rows (columns when vertical). `scroll` — and `menu`, which has no
 * native measurement — puts the controls in a `ScrollView` along the toolbar axis with a
 * react-native-svg gradient `fadeWidth` long from `background` to transparent over each edge
 * that has content hidden past it, re-checked on scroll, layout and content size changes.
 *
 * Acknowledged native limits: no roving focus and no arrow/Home/End handling (Pressable has
 * no key events, react-native-web included) — every control is its own accessibility stop,
 * reached by swipe or by Tab with a hardware keyboard; Enter/Space activation is the control's
 * own. `focusRing`/`focusRingWidth` are applied nowhere: each composed control draws its own
 * ring. The `overflowButton`/`overflowMenu` parts have no element on this platform.
 */
export function Toolbar({
  label,
  children,
  orientation = 'horizontal',
  overflow,
  size = 'md',
  density = 'comfortable',
  overrides,
  ref,
}: ToolbarProps): React.JSX.Element {
  const { tokens: t } = useTheme();
  const vertical = orientation === 'vertical';
  // The schema default is `menu`; neither it nor `scroll` can measure here, so both scroll.
  const mode: 'wrap' | 'scroll' = overflow === 'wrap' ? 'wrap' : 'scroll';

  React.useEffect(() => {
    if (__DEV__ && overflow === 'menu' && !warnedMenu) {
      warnedMenu = true;
      console.warn(
        'Toolbar: `overflow="menu"` renders as `overflow="scroll"` on React Native — children are opaque, so nothing can measure them and move trailing controls into a "More" Menu.',
      );
    }
  }, [overflow]);

  const styles = React.useMemo(() => {
    const border = overrides?.border ? (resolveToken(t, overrides.border) as string) : t.colorBorder;
    const borderWidth = overrides?.borderWidth ? (resolveToken(t, overrides.borderWidth) as number) : t.borderWidthThin;
    const radius = overrides?.radius ? (resolveToken(t, overrides.radius) as number) : t.radiusMd;
    const paddingInline = overrides?.paddingInline ? (resolveToken(t, overrides.paddingInline) as number) : t.space2;
    const paddingBlock = overrides?.paddingBlock ? (resolveToken(t, overrides.paddingBlock) as number) : t.space1;
    const itemGap = overrides?.itemGap ? (resolveToken(t, overrides.itemGap) as number) : t[ITEM_GAP[density]];
    const groupGap = overrides?.groupGap ? (resolveToken(t, overrides.groupGap) as number) : t.layoutGapNormal;
    const separatorLength = overrides?.separatorLength
      ? (resolveToken(t, overrides.separatorLength) as number)
      : t.space5;
    const fadeWidth = overrides?.fadeWidth ? (resolveToken(t, overrides.fadeWidth) as number) : t.space6;
    // groupGap replaces itemGap either side of a separator: the row keeps itemGap, the separator pads the rest.
    const separatorPad = Math.max(0, groupGap - itemGap);

    const wrap = mode === 'wrap' ? 'wrap' : 'nowrap';
    const root: ViewStyle = {
      backgroundColor: t.colorBackgroundSubtle,
      borderColor: border,
      borderWidth,
      borderRadius: radius,
      paddingHorizontal: paddingInline,
      paddingVertical: paddingBlock,
    };
    const row: ViewStyle = {
      flexDirection: vertical ? 'column' : 'row',
      alignItems: vertical ? 'stretch' : 'center',
      flexWrap: wrap,
      gap: itemGap,
    };
    const group: ViewStyle = {
      flexDirection: vertical ? 'column' : 'row',
      alignItems: vertical ? 'stretch' : 'center',
      flexWrap: wrap,
      flexShrink: mode === 'wrap' ? 1 : 0,
      gap: itemGap,
    };
    // A row box lets a vertical Divider stretch to the height; a column box lets a horizontal one stretch to the width.
    const separator: ViewStyle = vertical
      ? { width: separatorLength, paddingVertical: separatorPad, alignSelf: 'center' }
      : { height: separatorLength, paddingHorizontal: separatorPad, flexDirection: 'row', alignSelf: 'center' };
    return { root, row, group, separator, fadeWidth };
  }, [t, overrides, density, vertical, mode]);

  const layout = React.useMemo<ToolbarLayout>(() => ({ group: styles.group }), [styles.group]);

  const content: React.ReactNode[] = [];
  let previousWasGroup = false;
  flattenChildren(children).forEach((node, index) => {
    if (isGroup(node)) {
      if (previousWasGroup) {
        content.push(
          <View key={`separator-${index}`} style={styles.separator} testID="Toolbar.separator">
            <Divider orientation={vertical ? 'horizontal' : 'vertical'} spacing="none" />
          </View>,
        );
      }
      content.push(
        React.cloneElement(node, {
          children: flattenChildren(node.props.children).map((child) => withSize(child, size)),
        }),
      );
      previousWasGroup = true;
    } else {
      content.push(withSize(node, size));
      previousWasGroup = false;
    }
  });

  // Which edges have content scrolled past them, so a fade only covers hidden content.
  const [edges, setEdges] = React.useState({ start: false, end: false });
  const metrics = React.useRef({ offset: 0, viewport: 0, content: 0 });
  const updateEdges = (): void => {
    const { offset, viewport, content: length } = metrics.current;
    const start = offset > 1;
    const end = offset + viewport < length - 1;
    setEdges((prev) => (prev.start === start && prev.end === end ? prev : { start, end }));
  };

  return (
    <View
      ref={ref}
      testID="Toolbar"
      accessibilityRole="toolbar"
      accessibilityLabel={label}
      aria-label={label}
      style={styles.root}
    >
      <ToolbarLayoutContext.Provider value={layout}>
        {mode === 'wrap' ? (
          <View style={styles.row} testID="Toolbar.container">
            {content}
          </View>
        ) : (
          <View>
            <ScrollView
              testID="Toolbar.container"
              horizontal={!vertical}
              showsHorizontalScrollIndicator={false}
              showsVerticalScrollIndicator={false}
              contentContainerStyle={styles.row}
              scrollEventThrottle={16} // literal-ok: one frame between fade updates
              onLayout={(event) => {
                const { width, height } = event.nativeEvent.layout;
                metrics.current.viewport = vertical ? height : width;
                updateEdges();
              }}
              onContentSizeChange={(width, height) => {
                metrics.current.content = vertical ? height : width;
                updateEdges();
              }}
              onScroll={(event) => {
                const { contentOffset } = event.nativeEvent;
                metrics.current.offset = vertical ? contentOffset.y : contentOffset.x;
                updateEdges();
              }}
            >
              {content}
            </ScrollView>
            {edges.start ? (
              <ToolbarFade edge="start" vertical={vertical} length={styles.fadeWidth} color={t.colorBackgroundSubtle} />
            ) : null}
            {edges.end ? (
              <ToolbarFade edge="end" vertical={vertical} length={styles.fadeWidth} color={t.colorBackgroundSubtle} />
            ) : null}
          </View>
        )}
      </ToolbarLayoutContext.Provider>
    </View>
  );
}

interface ToolbarFadeProps {
  edge: 'start' | 'end';
  vertical: boolean;
  length: number;
  color: string;
}

/** One edge fade over the scrolling row, opaque `background` at the edge to transparent inward. */
function ToolbarFade({ edge, vertical, length, color }: ToolbarFadeProps): React.JSX.Element {
  // useId's colons are not valid in an SVG `url(#…)` reference on react-native-web.
  const gradientId = `toolbar-fade-${React.useId().replace(/[^a-zA-Z0-9_-]/g, '')}`;
  const position: ViewStyle = vertical
    ? { position: 'absolute', left: 0, right: 0, height: length, ...(edge === 'start' ? { top: 0 } : { bottom: 0 }) }
    : { position: 'absolute', top: 0, bottom: 0, width: length, ...(edge === 'start' ? { left: 0 } : { right: 0 }) };
  const from = edge === 'start' ? '0%' : '100%';
  const to = edge === 'start' ? '100%' : '0%';

  return (
    <View style={position} pointerEvents="none" accessibilityElementsHidden importantForAccessibility="no">
      <Svg width="100%" height="100%">
        <Defs>
          <LinearGradient
            id={gradientId}
            x1={vertical ? '0%' : from}
            y1={vertical ? from : '0%'}
            x2={vertical ? '0%' : to}
            y2={vertical ? to : '0%'}
          >
            <Stop offset="0" stopColor={color} stopOpacity={1} />
            <Stop offset="1" stopColor={color} stopOpacity={0} />
          </LinearGradient>
        </Defs>
        <Rect width="100%" height="100%" fill={`url(#${gradientId})`} />
      </Svg>
    </View>
  );
}

// packages/lit/src/Toolbar.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Divider.js';
import './Menu.js';
import type { DsDivider } from './Divider.js';
import type { MenuActionDetail, MenuActionItem, MenuItem } from './Menu.js';

export type ToolbarOrientation = 'horizontal' | 'vertical';
export type ToolbarOverflow = 'wrap' | 'menu' | 'scroll';
export type ToolbarSize = 'sm' | 'md';
export type ToolbarDensity = 'compact' | 'comfortable';

/** Overridable style hooks; see the `overrides` property. `background`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type ToolbarOverridableBinding =
  | 'border'
  | 'borderWidth'
  | 'radius'
  | 'paddingInline'
  | 'paddingBlock'
  | 'itemGap'
  | 'groupGap'
  | 'separatorLength'
  | 'fadeWidth';

const HOOKS: Record<ToolbarOverridableBinding, string> = {
  border: '--ds-toolbar-border',
  borderWidth: '--ds-toolbar-border-width',
  radius: '--ds-toolbar-radius',
  paddingInline: '--ds-toolbar-padding-inline',
  paddingBlock: '--ds-toolbar-padding-block',
  itemGap: '--ds-toolbar-item-gap',
  groupGap: '--ds-toolbar-group-gap',
  separatorLength: '--ds-toolbar-separator-length',
  fadeWidth: '--ds-toolbar-fade-width',
};

/** copy.more */
const COPY_MORE = 'More';

/** Marks a light-DOM entry this toolbar hid into the overflow menu (a consumer's own `hidden` is left alone). */
const COLLAPSED = 'data-ds-toolbar-collapsed';
/** Marks a `<ds-divider>` this toolbar inserted between two groups. */
const SEPARATOR = 'data-ds-toolbar-separator';
/** Marks a control whose `size` came from the toolbar rather than its own markup. */
const SIZED = 'data-ds-toolbar-size';

const NATIVE_FOCUSABLE = 'button, select, input, textarea, a[href], [tabindex]';

/**
 * `<ds-toolbar-group>` — related controls inside a `<ds-toolbar>` (anatomy: group).
 *
 * A light-DOM `role="group"` wrapper named by `label`. `<ds-toolbar>` descends
 * into it for its roving tabindex, draws a `<ds-divider>` between adjacent
 * groups, and collapses it into the overflow Menu as one Menu group.
 *
 * @slot - The group's controls.
 */
@customElement('ds-toolbar-group')
export class DsToolbarGroup extends LitElement {
  static override styles: CSSResult = css`
    :host {
      display: flex;
      align-items: center;
      gap: var(--ds-toolbar-item-gap, var(--layout-gap-normal));
    }

    :host([hidden]) {
      display: none;
    }

    :host([data-vertical]) {
      flex-direction: column;
      align-items: stretch;
    }
  `;

  /** The group's accessible name ("Text style", "Alignment"); also the Menu group heading when it collapses. */
  @property() accessor label: string | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'ToolbarGroup');
    this.setAttribute('data-part', 'group');
    this.setAttribute('role', 'group');
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('label')) {
      if (this.label) this.setAttribute('aria-label', this.label);
      else this.removeAttribute('aria-label');
    }
  }

  protected override render(): TemplateResult {
    return html`<slot></slot>`;
  }
}

/**
 * `<ds-toolbar>` — Toolbar (category: navigation, APG pattern: toolbar).
 *
 * `<ds-toolbar label="Formatting">` holds slotted light-DOM controls, bare or
 * inside `<ds-toolbar-group>`, and makes them one tab stop with a roving
 * tabindex: Tab enters on the last-focused control (initially the first),
 * arrows along `orientation` move between enabled controls without wrapping,
 * Home/End jump to the ends. A control that handles an arrow itself
 * (`defaultPrevented`, as SegmentedControl does) keeps it. A `<ds-divider>` is
 * inserted between adjacent groups.
 *
 * `overflow="menu"` (horizontal only; a vertical toolbar scrolls instead)
 * measures the entries when the host resizes and hides whole trailing entries
 * of Buttons — a group collapses as a group — into a "More" `<ds-menu>`, whose
 * items are named by each control's `overflow-label` and call `click()` on the
 * original element. SegmentedControl, Select and Switch never collapse.
 * `wrap` and `scroll` are CSS only.
 *
 * `role`, `aria-label` and `aria-orientation` are plain host attributes so
 * accessible-name computation in tests reads them.
 *
 * @slot - Controls in order, or `<ds-toolbar-group>` wrappers around related ones.
 */
@customElement('ds-toolbar')
export class DsToolbar extends LitElement {
  static override styles: CSSResult = css`
    :host {
      --ds-toolbar-background: var(--color-background-subtle);
      --ds-toolbar-border: var(--color-border);
      --ds-toolbar-border-width: var(--border-width-thin);
      --ds-toolbar-radius: var(--radius-md);
      --ds-toolbar-padding-inline: var(--space-2);
      --ds-toolbar-padding-block: var(--space-1);
      --ds-toolbar-item-gap: var(--layout-gap-normal);
      --ds-toolbar-group-gap: var(--layout-gap-normal);
      --ds-toolbar-separator-length: var(--space-5);
      --ds-toolbar-fade-width: var(--space-6);
      /* Locked, and applied nowhere by the toolbar: every focusable thing in it is a composed child drawing its own ring. */
      --ds-toolbar-focus-ring: var(--color-border-focus);
      --ds-toolbar-focus-ring-width: var(--border-width-focus);
      display: flex;
      position: relative;
      box-sizing: border-box;
      align-items: center;
      gap: var(--ds-toolbar-item-gap);
      padding-inline: var(--ds-toolbar-padding-inline);
      padding-block: var(--ds-toolbar-padding-block);
      border: var(--ds-toolbar-border-width) solid var(--ds-toolbar-border);
      border-radius: var(--ds-toolbar-radius);
      background: var(--ds-toolbar-background);
    }

    :host([hidden]) {
      display: none;
    }

    /* itemGap by density */
    :host([density='compact']) {
      --ds-toolbar-item-gap: var(--layout-gap-tight);
    }

    :host([orientation='vertical']) {
      flex-direction: column;
      align-items: stretch;
    }

    [data-part='container'] {
      display: flex;
      flex: 1 1 auto;
      align-items: center;
      gap: var(--ds-toolbar-item-gap);
      min-inline-size: 0;
      min-block-size: 0;
    }

    :host([orientation='vertical']) [data-part='container'] {
      flex-direction: column;
      align-items: stretch;
    }

    :host([overflow='wrap']) [data-part='container'] {
      flex-wrap: wrap;
    }

    :host([overflow='scroll']) [data-part='container'] {
      overflow-x: auto;
      overflow-y: hidden;
      scrollbar-width: none;
      mask-image: linear-gradient(to right, transparent, black var(--ds-toolbar-fade-width), black calc(100% - var(--ds-toolbar-fade-width)), transparent); /* literal-ok: mask alpha stops, not a color */
    }

    /* a vertical toolbar treats overflow menu as scroll */
    :host([orientation='vertical'][overflow='scroll']) [data-part='container'],
    :host([orientation='vertical'][overflow='menu']) [data-part='container'] {
      overflow-x: hidden;
      overflow-y: auto;
      scrollbar-width: none;
      mask-image: linear-gradient(to bottom, transparent, black var(--ds-toolbar-fade-width), black calc(100% - var(--ds-toolbar-fade-width)), transparent); /* literal-ok: mask alpha stops, not a color */
    }

    [data-part='container']::-webkit-scrollbar {
      display: none;
    }

    [data-part='overflowMenu'] {
      flex: none;
    }

    [data-part='overflowMenu'][hidden] {
      display: none;
    }

    /* Measures size.target.min, the width budget reserved for the More trigger before it is rendered. */
    .target-probe {
      position: absolute;
      visibility: hidden;
      pointer-events: none;
      inline-size: var(--size-target-min);
      block-size: var(--size-target-min);
    }
  `;

  /** What the toolbar controls ("Formatting", "Table actions"). Not visible; the toolbar's accessible name. */
  @property() accessor label: string = '';

  /** Vertical toolbars sit beside a canvas; arrow keys swap axes. */
  @property({ type: String, reflect: true }) accessor orientation: ToolbarOrientation = 'horizontal';

  /** What happens when controls do not fit: wrap onto more rows, collapse trailing Buttons into a "More" Menu, or scroll with faded edges. */
  @property({ type: String, reflect: true }) accessor overflow: ToolbarOverflow = 'menu';

  /** Default `size` for child controls that have one and do not set their own. */
  @property({ type: String, reflect: true }) accessor size: ToolbarSize = 'md';

  /** Gap between controls: tight or normal rhythm. */
  @property({ type: String, reflect: true }) accessor density: ToolbarDensity = 'comfortable';

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are not in the type. */
  @property({ attribute: false }) accessor overrides: Partial<Record<ToolbarOverridableBinding, TokenRef | undefined>> | undefined;

  /** The overflow Menu's items, built from the collapsed controls. */
  @state() private accessor overflowItems: MenuItem[] = [];

  @query('[data-part="overflowMenu"]') private accessor overflowMenuEl!: HTMLElement | null;
  @query('.target-probe') private accessor probeEl!: HTMLElement | null;

  /** The control carrying tabindex 0: the last one focused, initially the first. */
  private focusedControl: HTMLElement | null = null;

  /** Overflow item id → the original control it clicks. */
  private overflowTargets = new Map<string, HTMLElement>();

  private recalcFrame = 0;
  private resizeObserver: ResizeObserver | undefined;

  /** Watches the whole light-DOM subtree: a control added inside an existing group is assigned to the group's slot, so
      the toolbar's own `slotchange` would not see it. `childList` only, so the toolbar's attribute writes never re-enter. */
  private readonly mutationObserver: MutationObserver = new MutationObserver(() => this.handleChildrenChanged());

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Toolbar');
    this.setAttribute('role', 'toolbar');
    this.addEventListener('keydown', this.handleKeydown);
    this.addEventListener('focusin', this.handleFocusIn);
    this.mutationObserver.observe(this, { childList: true, subtree: true });
    this.resizeObserver = new ResizeObserver(() => this.scheduleRecalc());
    this.resizeObserver.observe(this);
    if (this.hasUpdated) this.handleChildrenChanged();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener('keydown', this.handleKeydown);
    this.removeEventListener('focusin', this.handleFocusIn);
    this.mutationObserver.disconnect();
    this.resizeObserver?.disconnect();
    this.resizeObserver = undefined;
    if (this.recalcFrame) cancelAnimationFrame(this.recalcFrame);
    this.recalcFrame = 0;
  }

  protected override firstUpdated(): void {
    this.handleChildrenChanged();
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) this.applyOverrides();
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('label')) {
      if (this.label) this.setAttribute('aria-label', this.label);
      else this.removeAttribute('aria-label');
      if (import.meta.env.DEV && !this.label) {
        console.warn("<ds-toolbar> requires a `label`, the toolbar's accessible name.", this);
      }
    }
    if (changed.has('orientation')) {
      this.setAttribute('aria-orientation', this.orientation);
      this.syncLayout();
    }
    if (changed.has('size')) this.applyDefaultSizes();
    if (changed.has('orientation') || changed.has('overflow') || changed.has('size') || changed.has('density')) {
      this.scheduleRecalc();
    }
  }

  protected override render(): TemplateResult {
    const menu = this.overflow === 'menu' && this.orientation === 'horizontal';
    return html`
      <span class="target-probe" aria-hidden="true"></span>
      <div part="container" data-part="container"><slot></slot></div>
      ${menu
        ? html`<ds-menu
            part="overflowMenu"
            data-part="overflowMenu"
            label=${COPY_MORE}
            icon-only
            trigger-variant="ghost"
            trigger-icon="ellipsis"
            placement="bottom-end"
            .items=${this.overflowItems}
            ?hidden=${this.overflowItems.length === 0}
            @action=${this.handleOverflowAction}
          ></ds-menu>`
        : nothing}
    `;
  }

  // ---- discovery -------------------------------------------------------------------------------------------------

  private isSeparator(el: Element): boolean {
    return el.hasAttribute(SEPARATOR);
  }

  private isGroup(el: Element): boolean {
    return (el as HTMLElement).dataset.ds === 'ToolbarGroup';
  }

  private isControl(el: Element): boolean {
    const kind = (el as HTMLElement).dataset.ds;
    if (kind) return kind !== 'Divider' && kind !== 'ToolbarGroup';
    return el.matches(NATIVE_FOCUSABLE);
  }

  /** Top-level entries in order: groups and bare controls (separators excluded). */
  private entries(): HTMLElement[] {
    return Array.from(this.children).filter(
      (el): el is HTMLElement => !this.isSeparator(el) && (this.isGroup(el) || this.isControl(el)),
    );
  }

  private controlsOf(entry: HTMLElement): HTMLElement[] {
    return this.isGroup(entry) ? Array.from(entry.children).filter((el): el is HTMLElement => this.isControl(el)) : [entry];
  }

  /** Every control, in order, one level into groups; a control's own internals are never descended into. */
  private controls(): HTMLElement[] {
    return this.entries().flatMap((entry) => this.controlsOf(entry));
  }

  private isDisabled(el: HTMLElement): boolean {
    return el.hasAttribute('disabled') || el.getAttribute('aria-disabled') === 'true';
  }

  private isShown(el: HTMLElement): boolean {
    for (let node: HTMLElement | null = el; node && node !== this; node = node.parentElement) {
      if (node.hidden) return false;
    }
    return true;
  }

  /** What the roving tabindex may land on: shown, enabled controls, then the More trigger when it is showing. */
  private focusable(): HTMLElement[] {
    const list = this.controls().filter((el) => this.isShown(el) && !this.isDisabled(el));
    const menu = this.overflowMenuEl;
    if (menu && !menu.hidden) list.push(menu);
    return list;
  }

  // ---- roving tabindex -------------------------------------------------------------------------------------------

  private syncRovingTabindex(): void {
    const list = this.focusable();
    if (!this.focusedControl || !list.includes(this.focusedControl)) this.focusedControl = list[0] ?? null;
    for (const el of list) {
      const next = el === this.focusedControl ? 0 : -1;
      if (el.tabIndex !== next) el.tabIndex = next;
    }
    // Collapsed or disabled controls leave the sequence too.
    for (const el of this.controls()) {
      if (!list.includes(el) && el.tabIndex !== -1) el.tabIndex = -1;
    }
  }

  private readonly handleFocusIn = (event: FocusEvent): void => {
    const list = this.focusable();
    const target = event.composedPath().find((node): node is HTMLElement => node instanceof HTMLElement && list.includes(node));
    if (target && target !== this.focusedControl) {
      this.focusedControl = target;
      this.syncRovingTabindex();
    }
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    // A control with its own arrow-key model (SegmentedControl, an open Menu) handled the key first.
    if (event.defaultPrevented) return;
    const vertical = this.orientation === 'vertical';
    const rtl = !vertical && getComputedStyle(this).direction === 'rtl';
    const next = vertical ? 'ArrowDown' : rtl ? 'ArrowLeft' : 'ArrowRight';
    const prev = vertical ? 'ArrowUp' : rtl ? 'ArrowRight' : 'ArrowLeft';
    const list = this.focusable();
    if (list.length === 0) return;
    const path = event.composedPath();
    const current = list.findIndex((el) => path.includes(el));
    let index: number;
    if (event.key === next) index = current < 0 ? 0 : current + 1;
    else if (event.key === prev) index = current < 0 ? 0 : current - 1;
    else if (event.key === 'Home') index = 0;
    else if (event.key === 'End') index = list.length - 1;
    else return;
    event.preventDefault();
    const target = list[index];
    if (!target) return; // no wrap
    this.focusedControl = target;
    this.syncRovingTabindex();
    target.focus();
  };

  // ---- children --------------------------------------------------------------------------------------------------

  private handleChildrenChanged(): void {
    this.mutationObserver.disconnect();
    this.syncSeparators();
    this.mutationObserver.observe(this, { childList: true, subtree: true });
    this.syncLayout();
    this.applyDefaultSizes();
    this.syncRovingTabindex();
    this.scheduleRecalc();
  }

  /** Inserts a `<ds-divider>` between adjacent groups and removes one that no longer sits between two. Every move is
      conditional, so a pass over settled children writes nothing. */
  private syncSeparators(): void {
    for (const el of Array.from(this.children)) {
      if (!this.isSeparator(el)) continue;
      const prev = el.previousElementSibling;
      const next = el.nextElementSibling;
      if (!(prev && next && this.isGroup(prev) && this.isGroup(next))) el.remove();
    }
    for (const el of Array.from(this.children)) {
      const next = el.nextElementSibling;
      if (this.isGroup(el) && next && this.isGroup(next)) {
        const divider = document.createElement('ds-divider');
        divider.setAttribute(SEPARATOR, '');
        divider.setAttribute('data-part', 'separator');
        el.after(divider);
      }
    }
  }

  /** Group axis and separator geometry. Divider draws its own line; the toolbar forwards length and spacing through the
      Divider's host-level hooks. groupGap replaces itemGap either side of a separator: the flex gap already supplies
      itemGap, so the Divider's spacing is the difference. */
  private syncLayout(): void {
    const vertical = this.orientation === 'vertical';
    for (const el of Array.from(this.children) as HTMLElement[]) {
      if (this.isGroup(el)) {
        if (el.hasAttribute('data-vertical') !== vertical) el.toggleAttribute('data-vertical', vertical);
      } else if (this.isSeparator(el)) {
        const divider = el as DsDivider;
        const orientation = vertical ? 'horizontal' : 'vertical';
        if (divider.orientation !== orientation) divider.orientation = orientation;
        if (divider.spacing !== 'tight') divider.spacing = 'tight';
        el.style.setProperty('--ds-divider-spacing', 'calc(var(--ds-toolbar-group-gap) - var(--ds-toolbar-item-gap))');
        el.style.flex = 'none';
        el.style.alignSelf = 'center';
        el.style.blockSize = vertical ? '' : 'var(--ds-toolbar-separator-length)';
        el.style.inlineSize = vertical ? 'var(--ds-toolbar-separator-length)' : '';
      }
    }
  }

  /** A control with a `size` property that has not set its own takes the toolbar's; its own `size` wins. */
  private applyDefaultSizes(): void {
    for (const el of this.controls()) {
      // Design-system controls only: a native <input>/<select> has an unrelated numeric `size`.
      if (!el.dataset.ds || !('size' in el)) continue;
      const defaulted = el.hasAttribute(SIZED);
      if (!defaulted && el.hasAttribute('size')) continue;
      if (!defaulted) el.setAttribute(SIZED, '');
      if (el.getAttribute('size') !== this.size) el.setAttribute('size', this.size);
    }
  }

  // ---- overflow --------------------------------------------------------------------------------------------------

  /** Measurement runs a frame later, after child controls have rendered their new size or density. */
  private scheduleRecalc(): void {
    if (this.recalcFrame) return;
    this.recalcFrame = requestAnimationFrame(() => {
      this.recalcFrame = 0;
      this.recalcOverflow();
    });
  }

  private isCollapsible(entry: HTMLElement): boolean {
    const controls = this.controlsOf(entry);
    return controls.length > 0 && controls.every((el) => el.dataset.ds === 'Button');
  }

  private recalcOverflow(): void {
    if (!this.isConnected) return;
    for (const el of Array.from(this.children) as HTMLElement[]) {
      if (el.hasAttribute(COLLAPSED)) {
        el.hidden = false;
        el.removeAttribute(COLLAPSED);
      }
    }
    const collapsed = this.overflow === 'menu' && this.orientation === 'horizontal' ? this.measureCollapse() : [];
    for (const el of collapsed) {
      el.hidden = true;
      el.setAttribute(COLLAPSED, '');
    }
    this.syncSeparatorVisibility();
    this.buildOverflowItems(collapsed);
    this.syncRovingTabindex();
  }

  /** Which trailing collapsible entries must go so the rest, plus a `size.target.min` More trigger, fit the host. */
  private measureCollapse(): HTMLElement[] {
    const entries = this.entries().filter((el) => !el.hidden);
    if (entries.length === 0) return [];
    const style = getComputedStyle(this);
    const rtl = style.direction === 'rtl';
    const start = (r: DOMRect): number => (rtl ? -r.right : r.left);
    const end = (r: DOMRect): number => (rtl ? -r.left : r.right);
    const rects = entries.map((el) => el.getBoundingClientRect());
    const widths = rects.map((r) => r.width);
    // Space after each entry up to the next one: the gap, plus a separator and its spacing between groups.
    const after = rects.map((r, i) => (i < rects.length - 1 ? start(rects[i + 1]!) - end(r) : 0));
    const available = this.clientWidth - (parseFloat(style.paddingInlineStart) || 0) - (parseFloat(style.paddingInlineEnd) || 0);
    const total = (kept: number[]): number =>
      kept.reduce((sum, i, k) => sum + widths[i]! + (k < kept.length - 1 ? after[i]! : 0), 0);

    let kept = entries.map((_, i) => i);
    if (total(kept) <= available) return [];

    const reserve = (this.probeEl?.getBoundingClientRect().width ?? 0) + (parseFloat(style.columnGap) || 0);
    const budget = available - reserve;
    for (let i = entries.length - 1; i >= 0 && total(kept) > budget; i -= 1) {
      if (this.isCollapsible(entries[i]!)) kept = kept.filter((k) => k !== i);
    }
    return entries.filter((_, i) => !kept.includes(i));
  }

  /** A separator shows only between two shown groups, and never twice in a row. */
  private syncSeparatorVisibility(): void {
    let prevShown: HTMLElement | null = null;
    let pending: HTMLElement | null = null;
    for (const el of Array.from(this.children) as HTMLElement[]) {
      if (this.isSeparator(el)) {
        if (pending) {
          if (!el.hidden) el.hidden = true;
        } else {
          pending = el;
        }
        continue;
      }
      if (el.hidden) continue;
      if (pending) {
        const show = !!prevShown && this.isGroup(prevShown) && this.isGroup(el);
        if (pending.hidden === show) pending.hidden = !show;
        pending = null;
      }
      prevShown = el;
    }
    if (pending && !pending.hidden) pending.hidden = true;
  }

  private buildOverflowItems(collapsed: HTMLElement[]): void {
    this.overflowTargets = new Map();
    const items: MenuItem[] = [];
    let previousWasGroup = false;
    const toItem = (el: HTMLElement): MenuActionItem => {
      const id = `overflow-${this.overflowTargets.size}`;
      this.overflowTargets.set(id, el);
      const overflowLabel = el.getAttribute('overflow-label');
      if (import.meta.env.DEV && !overflowLabel) {
        console.warn('<ds-toolbar> a control collapsed into the More menu has no `overflow-label`.', el);
      }
      return {
        id,
        label: overflowLabel ?? el.getAttribute('label') ?? el.textContent?.trim() ?? '',
        disabled: this.isDisabled(el),
      };
    };
    for (const entry of collapsed) {
      if (this.isGroup(entry)) {
        const groupItems = this.controlsOf(entry).map(toItem);
        const heading = entry.getAttribute('label');
        if (heading) {
          items.push({ group: heading, items: groupItems });
        } else {
          if (items.length > 0) items.push({ separator: true });
          items.push(...groupItems);
        }
        previousWasGroup = true;
      } else {
        if (previousWasGroup) items.push({ separator: true });
        items.push(toItem(entry));
        previousWasGroup = false;
      }
    }
    const unchanged =
      items.length === this.overflowItems.length && JSON.stringify(items) === JSON.stringify(this.overflowItems);
    if (!unchanged) this.overflowItems = items;
  }

  private readonly handleOverflowAction = (event: CustomEvent<MenuActionDetail>): void => {
    event.stopPropagation();
    this.overflowTargets.get(event.detail.id)?.click();
  };

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ToolbarOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      if (ref === undefined) this.style.removeProperty(HOOKS[binding]);
      else this.style.setProperty(HOOKS[binding], cssVar(ref));
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-toolbar': DsToolbar;
    'ds-toolbar-group': DsToolbarGroup;
  }
}
