// packages/lit/src/Breadcrumb.ts
import { LitElement, css, html, type PropertyValues, type TemplateResult, type CSSResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import type { DsLink } from './Link.js';
import './Link.js';
import './Button.js';
import './Icon.js';

/** Shape of each entry in `items`: `{ label: string; href?: string }`. */
export interface BreadcrumbItem {
  label: string;
  href?: string | undefined;
}

/** Detail carried by the `navigate` CustomEvent. `preventDefault()` on `originalEvent` (or on the `navigate` event) cancels navigation. */
export interface BreadcrumbNavigateDetail {
  item: BreadcrumbItem;
  index: number;
  originalEvent: MouseEvent;
}

/** copy.separator — drawn with CSS from `--ds-breadcrumb-separator`, so it is not in the accessibility tree. */
const COPY_SEPARATOR = '/';
/** copy.expandLabel */
const COPY_EXPAND_LABEL = 'Show all pages';
/** copy.navLabel */
const COPY_NAV_LABEL = 'Breadcrumb';

/** Trails longer than this collapse (first, ellipsis, last two). */
const COLLAPSE_ABOVE = 4;

/** Negates a boolean attribute: `no-collapse` present means `collapse` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

/** Overridable style hooks; see the `overrides` property. `currentColor`, `itemColor`, `separatorColor` and `minTarget` are locked and excluded. */
export type BreadcrumbOverridableBinding = 'gap' | 'fontFamily' | 'fontSize' | 'fontWeight' | 'lineHeight';

const HOOKS: Record<BreadcrumbOverridableBinding, string> = {
  gap: '--ds-breadcrumb-gap',
  fontFamily: '--ds-breadcrumb-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-breadcrumb-font-size',
  fontWeight: '--ds-breadcrumb-font-weight',
  lineHeight: '--ds-breadcrumb-line-height',
};

/**
 * `<ds-breadcrumb>` — Breadcrumb (category: navigation, APG pattern: breadcrumb).
 *
 * `<ds-breadcrumb .items=${[{ label: 'Docs', href: '/docs' }, { label: 'Components' }]}>`
 * renders `<nav aria-label>` with an `<ol>` in its shadow root; landmarks
 * inside shadow roots are exposed normally. Each ancestor is a `<ds-link>`;
 * the last item is the current page, `<span aria-current="page">`. Separators
 * are CSS-generated. Activating an ancestor dispatches a composed, cancelable
 * `navigate` CustomEvent with `{ item, index, originalEvent }`; calling
 * `preventDefault()` on `originalEvent` (the retargeted native click) cancels
 * navigation. The ellipsis is a ghost `sm` icon-only `<ds-button>`, used
 * unchanged, whose `press` is stopped so consumers see only `navigate`. An
 * ancestor without an `href` renders as plain text.
 *
 * ## When to use
 *
 * Use a Breadcrumb on pages three or more levels deep in a hierarchy —
 * documentation, catalogues, settings sub-pages — placed above the page title
 * at the top of `main`. It shows the site's hierarchy, not the user's history,
 * and never replaces the primary navigation or Back.
 *
 * @fires navigate - Fired when a non-current item is activated with `{ item, index, originalEvent }` in `detail`. Cancelable: the link still navigates unless `preventDefault()` is called on it or on `originalEvent`.
 */
@customElement('ds-breadcrumb')
export class DsBreadcrumb extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-breadcrumb-gap: var(--space-2);
      --ds-breadcrumb-font-family: var(--font-family-body);
      --ds-breadcrumb-font-size: var(--font-size-sm);
      --ds-breadcrumb-font-weight: var(--font-weight-regular);
      --ds-breadcrumb-line-height: var(--font-line-height-normal);
    }

    :host([hidden]) {
      display: none;
    }

    /* fontFamily, fontSize, fontWeight, lineHeight on the nav; ds-link inherits (font: inherit on its anchor) */
    [data-part='nav'] {
      font-family: var(--ds-breadcrumb-font-family);
      font-size: var(--ds-breadcrumb-font-size);
      font-weight: var(--ds-breadcrumb-font-weight);
      line-height: var(--ds-breadcrumb-line-height);
    }

    /* the trail wraps rather than truncating; gap: after each separator */
    [data-part='list'] {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      column-gap: var(--ds-breadcrumb-gap);
      margin: 0;
      padding: 0;
      list-style: none;
    }

    /* minTarget on the list item, not the inline Link; itemColor: an ancestor without href */
    [data-part='item'] {
      display: inline-flex;
      align-items: center;
      gap: var(--ds-breadcrumb-gap);
      min-block-size: var(--size-target-min);
      color: var(--color-foreground-muted);
    }

    /* separator: copy.separator in separatorColor, gap before it; generated, so aria-hidden by construction */
    [data-part='item'] + [data-part='item']::before {
      content: var(--ds-breadcrumb-separator);
      color: var(--color-foreground-muted);
    }

    /* currentColor: the current page, rendered as text in the regular weight */
    [data-part='current'] {
      color: var(--color-foreground);
    }
  `;

  /** The trail from root to current page, in order. Every item but the last needs an `href`; the last is the current page and its `href` is ignored. A property, not an attribute. */
  @property({ attribute: false }) accessor items: BreadcrumbItem[] = [];

  /** Accessible name of the navigation landmark. Change it only if the page has another breadcrumb. */
  @property() accessor label: string = COPY_NAV_LABEL;

  /**
   * When there are more than four items, show the first, an ellipsis, and the last two; the
   * ellipsis reveals the rest. Attribute is the negation, `no-collapse`, because a boolean
   * attribute cannot express `false` for a prop that defaults `true`.
   */
  @property({ attribute: 'no-collapse', reflect: true, converter: NEGATED_BOOLEAN_CONVERTER })
  accessor collapse = true;

  /** Per-instance style overrides: `{ gap: 'space.3' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<BreadcrumbOverridableBinding, TokenRef | undefined>> | undefined;

  /** Whether the user has revealed the collapsed items (one-way). */
  @state() private accessor expanded = false;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Breadcrumb');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    const items = this.items;
    const last = items.length - 1;
    const collapsed = this.collapse && !this.expanded && items.length > COLLAPSE_ABOVE;

    const entries: TemplateResult[] = [];
    items.forEach((item, index) => {
      if (collapsed && index > 0 && index < last - 1) {
        if (index === 1) {
          entries.push(html`
            <li part="item" data-part="item">
              <span part="expand" data-part="expand">
                <ds-button
                  variant="ghost"
                  size="sm"
                  icon-only
                  label=${COPY_EXPAND_LABEL}
                  @press=${this.handleExpand}
                >
                  <ds-icon slot="leading-icon" name="ellipsis"></ds-icon>
                </ds-button>
              </span>
            </li>
          `);
        }
        return;
      }
      if (index === last) {
        entries.push(
          html`<li part="item" data-part="item" data-index=${index}><span part="current" data-part="current" aria-current="page">${item.label}</span></li>`,
        );
      } else if (item.href === undefined || item.href === '') {
        entries.push(html`<li part="item" data-part="item" data-index=${index}>${item.label}</li>`);
      } else {
        entries.push(html`
          <li part="item" data-part="item" data-index=${index}>
            <span part="link" data-part="link">
              <ds-link
                tone="default"
                href=${item.href}
                label=${item.label}
                @click=${(event: MouseEvent) => this.handleNavigate(event, item, index)}
              ></ds-link>
            </span>
          </li>
        `);
      }
    });

    return html`
      <nav part="nav" data-part="nav" aria-label=${this.label} style=${`--ds-breadcrumb-separator: ${JSON.stringify(COPY_SEPARATOR)}`}>
        <ol part="list" data-part="list">${entries}</ol>
      </nav>
    `;
  }

  private handleNavigate(originalEvent: MouseEvent, item: BreadcrumbItem, index: number): void {
    const proceed = this.dispatchEvent(
      new CustomEvent<BreadcrumbNavigateDetail>('navigate', {
        detail: { item, index, originalEvent },
        bubbles: true,
        composed: true,
        cancelable: true,
      }),
    );
    if (!proceed) {
      originalEvent.preventDefault();
    }
  }

  private async handleExpand(event: Event): Promise<void> {
    // The ellipsis is internal; consumers see only `navigate`.
    event.stopPropagation();
    const firstHidden = 1;
    const lastHidden = this.items.length - 3;
    this.expanded = true;
    await this.updateComplete;
    // Focus moves to the first revealed link, or to the first revealed item when none is a link.
    for (let index = firstHidden; index <= lastHidden; index++) {
      const link = this.renderRoot.querySelector<DsLink>(`[data-index="${index}"] ds-link`);
      if (link) {
        link.focus();
        return;
      }
    }
    const first = this.renderRoot.querySelector<HTMLElement>(`[data-index="${firstHidden}"]`);
    if (first) {
      if (first.tabIndex !== -1) first.tabIndex = -1;
      first.focus();
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as BreadcrumbOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-breadcrumb': DsBreadcrumb;
  }
}

// packages/react/src/Breadcrumb.tsx
import {
  useEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type MouseEvent,
  type Ref,
  type ReactElement,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Link } from './Link';
import { Button } from './Button';
import { Icon } from './Icon';
import './Breadcrumb.css';

/** One step of the trail. `href` is ignored on the last item, which is the current page. */
export type BreadcrumbItem = { label: string; href?: string };

/** Copy strings from the schema, used verbatim. */
const COPY = {
  separator: '/',
  expandLabel: 'Show all pages',
  navLabel: 'Breadcrumb',
} as const;

/** With `collapse`, trails longer than this show the first item, an ellipsis, and the last two. */
const COLLAPSE_ABOVE = 4;

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type BreadcrumbOverridableBinding = 'gap' | 'fontFamily' | 'fontSize' | 'fontWeight' | 'lineHeight';

const OVERRIDE_HOOK: Record<BreadcrumbOverridableBinding, string> = {
  gap: '--ds-breadcrumb-gap',
  fontFamily: '--ds-breadcrumb-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  fontSize: '--ds-breadcrumb-font-size',
  fontWeight: '--ds-breadcrumb-font-weight',
  lineHeight: '--ds-breadcrumb-line-height',
};

function overridesToStyle(overrides: Partial<Record<BreadcrumbOverridableBinding, TokenRef | undefined>>): Record<string, string> {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(OVERRIDE_HOOK) as BreadcrumbOverridableBinding[]) {
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return style;
}

export interface BreadcrumbProps
  extends Omit<ComponentPropsWithoutRef<'nav'>, 'children' | 'aria-label' | 'className' | 'style'> {
  /**
   * The trail from root to current page, in order. Every item but the last needs an `href`; an
   * ancestor without one renders as plain text (never an empty link). The last is the current page
   * and its `href` is ignored.
   */
  items: BreadcrumbItem[];
  /** Accessible name of the navigation landmark. Change it only if the page has another breadcrumb. */
  label?: string | undefined;
  /**
   * When there are more than four items, show the first, an ellipsis, and the last two; the ellipsis
   * is a button that reveals the rest. Set false for short trails that must always show in full.
   */
  collapse?: boolean | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<BreadcrumbOverridableBinding, TokenRef | undefined>> | undefined;
  /**
   * Fired when a non-current item is activated, as `(item, index, event)`. The link still navigates
   * unless the consumer calls `event.preventDefault()` or returns `false`.
   */
  onNavigate?:
    | ((item: BreadcrumbItem, index: number, event: MouseEvent<HTMLAnchorElement>) => void | boolean)
    | undefined;
}

/**
 * Breadcrumb — Design Schema, category: navigation.
 *
 * When to use:
 * Use a Breadcrumb on pages that live three or more levels deep in a hierarchy — documentation,
 * catalogues, settings sub-pages, file browsers — where the user benefits from seeing the ancestors
 * and jumping to any of them. Place it above the page title, at the top of `main`.
 */
export function Breadcrumb({
  ref,
  items,
  label = COPY.navLabel,
  collapse = true,
  overrides,
  onNavigate,
  ...rest
}: BreadcrumbProps & { ref?: Ref<HTMLElement> | undefined }): ReactElement {
  const [expanded, setExpanded] = useState(false);
  const collapsed = collapse && !expanded && items.length > COLLAPSE_ABOVE;
  const lastIndex = items.length - 1;
  // Collapsed: items[0], the ellipsis, then items[hiddenEnd..].
  const hiddenEnd = items.length - 2;

  const linkRefs = useRef(new Map<number, HTMLAnchorElement>());
  const focusRevealed = useRef(false);

  // After the ellipsis is activated, focus moves to the first revealed link.
  useEffect(() => {
    if (!focusRevealed.current) return;
    focusRevealed.current = false;
    for (let index = 1; index < hiddenEnd; index++) {
      const link = linkRefs.current.get(index);
      if (link) {
        link.focus();
        return;
      }
    }
  }, [expanded, hiddenEnd]);

  const handleExpand = (): void => {
    focusRevealed.current = true;
    setExpanded(true);
  };

  const setLinkRef =
    (index: number) =>
    (el: HTMLAnchorElement | null): void => {
      if (el) linkRefs.current.set(index, el);
      else linkRefs.current.delete(index);
    };

  const renderItem = (item: BreadcrumbItem, index: number): ReactElement => {
    let content: ReactElement;
    if (index === lastIndex) {
      content = (
        <span className="ds-breadcrumb__current" data-part="current" aria-current="page">
          {item.label}
        </span>
      );
    } else if (item.href === undefined || item.href === '') {
      // A level with no page of its own is plain text, never an empty link.
      content = <span className="ds-breadcrumb__text">{item.label}</span>;
    } else {
      content = (
        <Link
          ref={setLinkRef(index)}
          href={item.href}
          label={item.label}
          tone="default"
          data-part="link"
          onClick={onNavigate ? (event) => onNavigate(item, index, event) : undefined}
        />
      );
    }
    return (
      <li key={index} className="ds-breadcrumb__item" data-part="item">
        {content}
      </li>
    );
  };

  const first = items[0];
  const list: ReactElement[] =
    collapsed && first !== undefined
      ? [
          renderItem(first, 0),
          <li key="ellipsis" className="ds-breadcrumb__item" data-part="item">
            <Button
              variant="ghost"
              size="sm"
              iconOnly
              label={COPY.expandLabel}
              leadingIcon={<Icon name="ellipsis" inline />}
              onClick={handleExpand}
            />
          </li>,
          ...items.slice(hiddenEnd).map((item, offset) => renderItem(item, hiddenEnd + offset)),
        ]
      : items.map(renderItem);

  const style = {
    ...(overrides ? overridesToStyle(overrides) : undefined),
    // copy.separator, quoted for `content`; read by `li + li::before`.
    '--ds-breadcrumb-separator': JSON.stringify(COPY.separator),
  } as CSSProperties;

  return (
    <nav
      {...rest}
      ref={ref}
      data-ds="Breadcrumb"
      data-part="nav"
      className="ds-breadcrumb"
      style={style}
      aria-label={label}
    >
      <ol className="ds-breadcrumb__list" data-part="list">
        {list}
      </ol>
    </nav>
  );
}
