// packages/lit/src/Button.ts
import { LitElement, css, html, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { trackPress } from './custom/analytics.js';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonType = 'button' | 'submit';

/** Detail carried by the `press` CustomEvent (none). */
export type ButtonPressDetail = void;

/** Detail carried by the `track` CustomEvent. */
export interface ButtonTrackDetail {
  name: string;
  label: string;
}

/**
 * Overridable style hooks; see the `overrides` property. The accessibility-bearing
 * bindings — `background`, `backgroundHover`, `foreground`, `focusRing`,
 * `focusRingWidth`, `inverseForeground`, `inverseFocusRing`, `minTarget` and
 * `spinnerStroke` — are locked and excluded; of those, only `spinnerStroke` keeps
 * a CSS hook (`--ds-button-spinner-stroke`), the rest read their tokens directly.
 */
export type ButtonOverridableBinding =
  | 'iconGap'
  | 'paddingInline'
  | 'paddingBlock'
  | 'radius'
  | 'fontFamily'
  | 'fontWeight'
  | 'fontSize'
  | 'inverseBackgroundHover'
  | 'inverseHoverOpacity'
  | 'disabledOpacity'
  | 'transition'
  | 'loadingSpin'
  | 'spinnerSize';

const HOOKS: Record<ButtonOverridableBinding, string> = {
  iconGap: '--ds-button-icon-gap',
  paddingInline: '--ds-button-padding-inline',
  paddingBlock: '--ds-button-padding-block',
  radius: '--ds-button-radius',
  fontFamily: '--ds-button-font-family',
  fontWeight: '--ds-button-font-weight',
  fontSize: '--ds-button-font-size',
  inverseBackgroundHover: '--ds-button-inverse-background-hover',
  inverseHoverOpacity: '--ds-button-inverse-hover-opacity',
  disabledOpacity: '--ds-button-disabled-opacity',
  transition: '--ds-button-transition',
  loadingSpin: '--ds-button-loading-spin',
  spinnerSize: '--ds-button-spinner-size',
};

/** copy.loading — announced as the button's description while `loading` is true. */
const COPY_LOADING = 'Loading';

/**
 * `<ds-button>` — Button (category: action, APG pattern: button).
 *
 * Wraps a native `<button>` in a shadow root created with `delegatesFocus`, so
 * focusing the host focuses the inner button. Activation dispatches a composed,
 * bubbling `press` CustomEvent. A `type="submit"` button submits the enclosing
 * `<ds-form>` (which listens for `press`) or, only when no `ds-form` encloses it,
 * calls `requestSubmit()` on the closest native `<form>`. When `track` is set, a
 * press also calls the hand-written `trackPress` analytics module and then fires
 * a composed `track` CustomEvent with `{ name, label }`.
 *
 * `ds-button` is deliberately *not* form-associated: a form-associated custom
 * element with a reflected `disabled` attribute becomes truly disabled and
 * unfocusable, and the doc requires a disabled button to stay in the tab order.
 * The disabled state is `aria-disabled` on the inner button instead.
 *
 * ## When to use
 *
 * Use a Button when the user needs to **do something**: submit, save, confirm,
 * open, add, delete. The label should be a verb or verb phrase that describes
 * the outcome ("Save changes", not "OK").
 *
 * Use the `primary` variant for the single most important action in a view.
 * Use `secondary` for the alternatives beside it, `ghost` for low-emphasis
 * actions in dense UI such as toolbars, and `danger` only for destructive,
 * hard-to-undo actions. Navigation belongs to Link, never to Button.
 *
 * @fires press - Fired when the button is activated by pointer, keyboard
 *   (Enter/Space), or assistive technology. Not fired while `disabled` or `loading`.
 * @fires track - Fired after `press`, only when `track` is set, with `{ name, label }` in `detail`.
 * @slot leading-icon - Icon rendered before the label (anatomy: leadingIcon). Decorative.
 * @slot trailing-icon - Icon rendered after the label (anatomy: trailingIcon). Decorative.
 * @csspart container - The native `<button>` (anatomy: container).
 * @csspart label - The visible label text (anatomy: label).
 * @csspart leadingIcon - The leading-icon slot (anatomy: leadingIcon).
 * @csspart trailingIcon - The trailing-icon slot (anatomy: trailingIcon).
 */
@customElement('ds-button')
export class DsButton extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    /*
     * Hooks for the overridable bindings, plus spinnerStroke (locked, but its
     * binding keeps the hook). The other locked bindings (background,
     * backgroundHover, foreground, focusRing, focusRingWidth, inverseForeground,
     * inverseFocusRing, minTarget) have no hook: their rules read the token.
     */
    :host {
      display: inline-flex;
      vertical-align: middle;
      --ds-button-icon-gap: var(--space-2);
      --ds-button-padding-inline: var(--space-md);
      --ds-button-padding-block: var(--space-sm);
      --ds-button-radius: var(--radius-md);
      --ds-button-font-family: var(--font-family-body);
      --ds-button-font-weight: var(--font-weight-medium);
      --ds-button-font-size: var(--font-size-md);
      --ds-button-inverse-background-hover: var(--color-inverse-foreground);
      /* the base token; the rule that reads it multiplies by 0.25 */
      --ds-button-inverse-hover-opacity: var(--opacity-disabled);
      --ds-button-disabled-opacity: var(--opacity-disabled);
      --ds-button-transition: var(--motion-duration-fast);
      --ds-button-loading-spin: var(--motion-duration-loop);
      --ds-button-spinner-size: var(--font-size-md);
      --ds-button-spinner-stroke: var(--border-width-focus);
    }

    :host([hidden]) {
      display: none;
    }

    [data-part='container'] {
      position: relative;
      box-sizing: border-box;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      inline-size: 100%;
      /* minTarget: locked; the floor at every size (WCAG 2.5.8) */
      min-inline-size: var(--size-target-min);
      min-block-size: var(--size-target-min);
      margin: 0;
      padding-block: var(--ds-button-padding-block);
      padding-inline: var(--ds-button-padding-inline);
      border: 0;
      border-radius: var(--ds-button-radius);
      font-family: var(--ds-button-font-family);
      font-size: var(--ds-button-font-size);
      font-weight: var(--ds-button-font-weight);
      color: var(--color-action-primary-foreground);
      background: var(--color-action-primary-background);
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
      /* transition: only the background animates, with motion.easing.standard */
      transition: background-color var(--ds-button-transition) var(--motion-easing-standard);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='container'] {
        transition: none;
      }
    }

    /* paddingInline: space.{size}; fontSize and spinnerSize: font.size.{size} */
    :host([size='sm']) {
      --ds-button-padding-inline: var(--space-sm);
      --ds-button-font-size: var(--font-size-sm);
      --ds-button-spinner-size: var(--font-size-sm);
    }
    :host([size='md']) {
      --ds-button-padding-inline: var(--space-md);
      --ds-button-font-size: var(--font-size-md);
      --ds-button-spinner-size: var(--font-size-md);
    }
    :host([size='lg']) {
      --ds-button-padding-inline: var(--space-lg);
      --ds-button-font-size: var(--font-size-lg);
      --ds-button-spinner-size: var(--font-size-lg);
    }

    /* iconOnly: equal padding on all sides (space.sm), regardless of size */
    :host([icon-only]) {
      --ds-button-padding-inline: var(--space-sm);
      --ds-button-padding-block: var(--space-sm);
    }

    /* background / foreground: color.action.{variant}.*, locked (no hook) */
    :host([variant='primary']) [data-part='container'] {
      color: var(--color-action-primary-foreground);
      background: var(--color-action-primary-background);
    }
    :host([variant='secondary']) [data-part='container'] {
      color: var(--color-action-secondary-foreground);
      background: var(--color-action-secondary-background);
    }
    :host([variant='ghost']) [data-part='container'] {
      color: var(--color-action-ghost-foreground);
      background: var(--color-action-ghost-background);
    }
    :host([variant='danger']) [data-part='container'] {
      color: var(--color-action-danger-foreground);
      background: var(--color-action-danger-background);
    }

    /* backgroundHover: color.action.{variant}.backgroundHover on pointer hover and pressed, locked */
    :host([variant='primary']:not([disabled]):not([loading])) [data-part='container']:is(:hover, :active) {
      background: var(--color-action-primary-background-hover);
    }
    :host([variant='secondary']:not([disabled]):not([loading])) [data-part='container']:is(:hover, :active) {
      background: var(--color-action-secondary-background-hover);
    }
    :host([variant='ghost']:not([disabled]):not([loading])) [data-part='container']:is(:hover, :active) {
      background: var(--color-action-ghost-background-hover);
    }
    :host([variant='danger']:not([disabled]):not([loading])) [data-part='container']:is(:hover, :active) {
      background: var(--color-action-danger-background-hover);
    }

    /*
     * inverse: only ghost changes on an inverse surface. Its text is
     * inverseForeground, and its hover fill is inverseBackgroundHover at
     * inverseHoverOpacity (the sanctioned color-mix of tokens). Other variants
     * keep their own fills.
     */
    :host([inverse][variant='ghost']) [data-part='container'] {
      color: var(--color-inverse-link);
    }
    :host([inverse][variant='ghost']:not([disabled]):not([loading])) [data-part='container']:is(:hover, :active) {
      background: color-mix(
        in srgb,
        var(--ds-button-inverse-background-hover) calc(var(--ds-button-inverse-hover-opacity) * 0.25 * 100%),
        transparent
      );
    }

    /* focusRing / focusRingWidth: color.border.focus at border.width.focus, locked */
    [data-part='container']:focus-visible {
      outline: var(--border-width-focus) solid var(--color-border-focus);
      outline-offset: var(--border-width-focus);
    }

    /* inverseFocusRing: the ring must read against the inverse surface, for every variant */
    :host([inverse]) [data-part='container']:focus-visible {
      outline-color: var(--color-inverse-focus);
    }

    /* disabledOpacity: the whole button; colors are unchanged so the contrast math still holds */
    :host([disabled]) [data-part='container'] {
      opacity: var(--ds-button-disabled-opacity);
      cursor: not-allowed;
    }

    .content {
      display: inline-flex;
      align-items: center;
      /* iconGap: space.2 */
      gap: var(--ds-button-icon-gap);
    }

    /* iconOnly: hide the visible label; the accessible name moves to aria-label */
    :host([icon-only]) [data-part='label'] {
      display: none;
    }

    :host([loading]) [data-part='container'] {
      cursor: progress;
    }

    /* loading: a ring spinnerSize across, spinnerStroke thick, one quarter transparent, in currentColor */
    .spinner {
      display: inline-block;
      box-sizing: border-box;
      inline-size: var(--ds-button-spinner-size);
      block-size: var(--ds-button-spinner-size);
      border: var(--ds-button-spinner-stroke) solid currentColor;
      border-inline-end-color: transparent;
      border-radius: var(--radius-full);
      animation: ds-button-spin var(--ds-button-loading-spin) linear infinite;
    }
    @keyframes ds-button-spin {
      to {
        transform: rotate(1turn);
      }
    }
    @media (prefers-reduced-motion: reduce) {
      .spinner {
        animation: none;
      }
    }

    .visually-hidden {
      position: absolute;
      inline-size: 1px;
      block-size: 1px;
      margin: -1px;
      padding: 0;
      overflow: hidden;
      clip: rect(0 0 0 0);
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }
  `;

  /** The button's text. Also its accessible name. */
  @property({ type: String }) accessor label = '';

  /** Visual emphasis. One primary button per view. */
  @property({ type: String, reflect: true }) accessor variant: ButtonVariant = 'primary';

  /** Controls horizontal padding and font size. Touch targets never drop below the minimum regardless of size. */
  @property({ type: String, reflect: true }) accessor size: ButtonSize = 'md';

  /** `submit` submits the enclosing Form. Everything else is `button`. */
  @property({ type: String, reflect: true }) accessor type: ButtonType = 'button';

  /**
   * Set by a parent that the button discloses (Menu, Popover, SidePanel,
   * Disclosure): rendered as `aria-expanded` on the inner button. A JS property
   * only, and tri-state — `undefined` (the default) means this button discloses
   * nothing, so no `aria-expanded` is rendered at all. A raw `aria-expanded`
   * attribute on the host does not reach the inner button.
   */
  @property({ attribute: false }) accessor expanded: boolean | undefined;

  /**
   * Prevents activation. The button stays in the tab order and is announced as
   * disabled. Inside a disabled `ds-form` the form sets this for you.
   */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /**
   * Hides the visible label and shows only `leadingIcon`; `trailingIcon` is not
   * rendered either. `label` is still required and becomes the accessible name.
   * Padding becomes equal on all sides (`space.sm`).
   */
  @property({ type: Boolean, reflect: true, attribute: 'icon-only' }) accessor iconOnly = false;

  /**
   * Shows a ring spinner in the leading icon position, hides `trailingIcon`,
   * keeps the label visible and the layout unchanged, and blocks repeat
   * activation while an action is pending. `copy.loading` is the description.
   */
  @property({ type: Boolean, reflect: true }) accessor loading = false;

  /**
   * The button sits on an inverse surface (Toast, Tooltip-like panels): `ghost`
   * text and hover change, and the focus ring uses the inverse focus token for
   * every variant.
   */
  @property({ type: Boolean, reflect: true }) accessor inverse = false;

  /**
   * Overrides the accessible name when it must say more than the visible label
   * ("Sort by Amount, ascending" on a header that shows "Amount"). The name must
   * contain the visible label (WCAG 2.5.3 label-in-name). Maps to `aria-label`.
   */
  @property({ type: String, attribute: 'accessible-name' }) accessor accessibleName: string | undefined;

  /**
   * Text used for this button when a Toolbar collapses it into its overflow
   * Menu. Read by Toolbar from the host attribute; the button never renders it.
   */
  @property({ type: String, reflect: true, attribute: 'overflow-label' }) accessor overflowLabel:
    | string
    | undefined;

  /** An event name sent to analytics when the button is pressed. Omit for no tracking. */
  @property({ type: String }) accessor track: string | undefined;

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides:
    | Partial<Record<ButtonOverridableBinding, TokenRef | undefined>>
    | undefined;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Button');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render(): TemplateResult {
    return html`
      <button
        part="container"
        data-part="container"
        type=${this.type}
        aria-disabled=${ifDefined(this.disabled ? 'true' : undefined)}
        aria-busy=${ifDefined(this.loading ? 'true' : undefined)}
        aria-expanded=${ifDefined(this.expanded === undefined ? undefined : String(this.expanded))}
        aria-label=${ifDefined(this.accessibleName ?? (this.iconOnly ? this.label : undefined))}
        aria-describedby=${ifDefined(this.loading ? 'loading-description' : undefined)}
        @click=${this.handleClick}
      >
        <span class="content">
          ${this.loading
            ? html`<span class="spinner" aria-hidden="true"></span>`
            : html`<slot name="leading-icon" part="leadingIcon" data-part="leadingIcon"></slot>`}
          <span class="label" part="label" data-part="label">${this.label}</span>
          ${this.iconOnly || this.loading
            ? nothing
            : html`<slot name="trailing-icon" part="trailingIcon" data-part="trailingIcon"></slot>`}
        </span>
        ${this.loading
          ? html`<span id="loading-description" class="visually-hidden">${COPY_LOADING}</span>`
          : nothing}
      </button>
    `;
  }

  private handleClick(event: MouseEvent): void {
    if (this.disabled || this.loading) {
      // aria-disabled keeps the button discoverable, so the activation has to be
      // swallowed here: no `press`, no native click leaking out, no submit.
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    this.dispatchEvent(new CustomEvent<ButtonPressDetail>('press', { bubbles: true, composed: true }));

    if (this.track) {
      // The analytics seam: a hand-written module the adopter owns, called once
      // per press, after `press` and before `track`.
      trackPress(this.track, this.label);
      this.dispatchEvent(
        new CustomEvent<ButtonTrackDetail>('track', {
          detail: { name: this.track, label: this.label },
          bubbles: true,
          composed: true,
        }),
      );
    }

    if (this.type === 'submit' && !this.closest('ds-form')) {
      // The inner <button> has no form owner (it lives in the shadow root), so a
      // native <form> is submitted explicitly. Inside a ds-form the form reacts
      // to `press` instead, so a ds-form nested in a native form submits once.
      this.closest('form')?.requestSubmit();
    }
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ButtonOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-button': DsButton;
  }
}

// packages/react/src/Button.tsx
import {
  useId,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type MouseEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { useFormContext } from './FormContext';
import { trackPress } from './custom/analytics';
import './Button.css';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonType = 'button' | 'submit';

/** Copy from the component doc, used verbatim. */
const COPY: { loading: string } = { loading: 'Loading' };

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type ButtonOverridableBinding =
  | 'iconGap'
  | 'paddingInline'
  | 'paddingBlock'
  | 'radius'
  | 'fontFamily'
  | 'fontWeight'
  | 'fontSize'
  | 'inverseBackgroundHover'
  | 'inverseHoverOpacity'
  | 'disabledOpacity'
  | 'transition'
  | 'loadingSpin'
  | 'spinnerSize';

const OVERRIDE_HOOK: Record<ButtonOverridableBinding, string> = {
  iconGap: '--ds-button-icon-gap',
  paddingInline: '--ds-button-padding-inline',
  paddingBlock: '--ds-button-padding-block',
  radius: '--ds-button-radius',
  fontFamily: '--ds-button-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  fontWeight: '--ds-button-font-weight',
  fontSize: '--ds-button-font-size',
  inverseBackgroundHover: '--ds-button-inverse-background-hover',
  inverseHoverOpacity: '--ds-button-inverse-hover-opacity',
  disabledOpacity: '--ds-button-disabled-opacity',
  transition: '--ds-button-transition',
  loadingSpin: '--ds-button-loading-spin',
  spinnerSize: '--ds-button-spinner-size',
};

function overridesToStyle(overrides: Partial<Record<ButtonOverridableBinding, TokenRef | undefined>>): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as ButtonOverridableBinding[]) {
    const hook = OVERRIDE_HOOK[binding];
    const ref = overrides[binding];
    // Locked bindings are not in the type; one passed anyway has no hook and is ignored.
    if (hook && ref) style[hook] = cssVar(ref);
  }
  return style as CSSProperties;
}

export interface ButtonProps
  extends Omit<
    ComponentPropsWithoutRef<'button'>,
    'type' | 'disabled' | 'children' | 'aria-label' | 'onClick' | 'className' | 'style'
  > {
  /** The button's text. Also its accessible name. */
  label: string;
  /**
   * Visual emphasis. One primary button per view. These four are the whole set: there is no
   * `outline` variant, and a bordered low-fill emphasis would be a new value here with its own
   * colour pair and its own contrast proof, never an alias for `secondary`.
   */
  variant?: ButtonVariant | undefined;
  /** Controls horizontal padding and font size. Touch targets never drop below the minimum regardless of size. */
  size?: ButtonSize | undefined;
  /** Icon before the label. Decorative — hidden from assistive technology; the label carries the meaning. */
  leadingIcon?: ReactNode | undefined;
  /** Icon after the label. Decorative, like leadingIcon. */
  trailingIcon?: ReactNode | undefined;
  /** `submit` submits the enclosing Form. Everything else is `button`. */
  type?: ButtonType | undefined;
  /**
   * Set by a parent that the button discloses (Menu, Popover, SidePanel, Disclosure): aria-expanded
   * on web. Consumers rarely set it directly. No default, and tri-state: undefined means the button
   * discloses nothing, so no expanded state is reported at all — though an `aria-expanded` arriving
   * through `...rest` still applies.
   */
  expanded?: boolean | undefined;
  /**
   * Prevents activation. The button stays in the tab order and is announced as disabled. A press
   * blocked by `disabled` or `loading` is not a press: onPress does not fire and nothing chained from
   * it (an extension's tracking) runs. Inside a disabled Form the button is disabled whatever this
   * prop says.
   */
  disabled?: boolean | undefined;
  /**
   * Overrides the accessible name when it must say more than the visible label ("Sort by Amount,
   * ascending" on a header that shows "Amount"). The name must contain the visible label (WCAG 2.5.3
   * label-in-name); starting with it is preferred but not required. Maps to aria-label.
   */
  accessibleName?: string | undefined;
  /**
   * Text used for this button when a Toolbar collapses it into its overflow Menu. Only Buttons
   * collapse; other controls stay visible. Button itself never renders it: Toolbar reads it from the
   * Button element's props (it never reaches the DOM).
   */
  overflowLabel?: string | undefined;
  /**
   * Hides the visible label and shows only `leadingIcon`; `trailingIcon` is not rendered either.
   * `label` is still required and becomes the accessible name. Padding becomes equal on all sides
   * (`space.sm`).
   */
  iconOnly?: boolean | undefined;
  /**
   * Shows a ring spinner (spinnerSize across, spinnerStroke thick, in `currentColor`) in the leading
   * icon slot (whether or not `leadingIcon` is set; for `iconOnly` it replaces the sole glyph), hides
   * `trailingIcon`, keeps the label visible and the layout unchanged, and blocks repeat activation
   * while an action is pending. `copy.loading` is announced as a description, never as part of the
   * name.
   */
  loading?: boolean | undefined;
  /**
   * The button sits on an inverse surface (Toast, Tooltip-like panels): `ghost` text uses
   * color.inverse.link and hover uses inverseBackgroundHover at inverseHoverOpacity over the surface;
   * the focus ring uses color.inverse.focus for every variant while `inverse` is true, since the ring
   * must read against the inverse surface. Only `ghost` changes its fill on inverse surfaces; other
   * variants keep their own fills.
   */
  inverse?: boolean | undefined;
  /** An event name sent to analytics when the button is pressed. Omit for no tracking. */
  track?: string | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<ButtonOverridableBinding, TokenRef | undefined>> | undefined;
  /** Fired when the button is activated by pointer, keyboard (Enter/Space), or assistive technology. */
  onClick?: ((event: MouseEvent<HTMLButtonElement>) => void) | undefined;
  /** Fired after onPress with the `track` name and the button's label. */
  onTrack?: ((name: string, label: string) => void) | undefined;
}

/**
 * Button — Design Schema, category: action.
 *
 * When to use:
 * Use a Button when the user needs to **do something**: submit, save, confirm, open, add, delete.
 * The label should be a verb or verb phrase that describes the outcome ("Save changes", not "OK").
 *
 * Use the `primary` variant for the single most important action in a view. Use `secondary` for
 * the alternatives beside it, `ghost` for low-emphasis actions in dense UI such as toolbars, and
 * `danger` only for destructive, hard-to-undo actions.
 */
export function Button({
  ref,
  label,
  variant = 'primary',
  size = 'md',
  leadingIcon,
  trailingIcon,
  type = 'button',
  expanded,
  disabled = false,
  accessibleName,
  overflowLabel: _overflowLabel,
  iconOnly = false,
  loading = false,
  inverse = false,
  track,
  overrides,
  onClick,
  onTrack,
  'aria-expanded': ariaExpanded,
  'aria-describedby': describedBy,
  ...props
}: ButtonProps & { ref?: Ref<HTMLButtonElement> | undefined }): ReactElement {
  // `className` and `style` are not in ButtonProps; one that arrives through an untyped spread is
  // still dropped, since `overrides` is the only per-instance styling.
  const {
    className: _className,
    style: _style,
    ...rest
  } = props as typeof props & { className?: unknown; style?: unknown };
  const form = useFormContext();
  const loadingId = `ds-button${useId()}-loading`;
  const isDisabled = disabled || (form?.disabled ?? false);
  const blocked = isDisabled || loading;

  const handleClick = (event: MouseEvent<HTMLButtonElement>): void => {
    if (blocked) {
      // aria-disabled does not stop native activation (including form submission), so we do.
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    onClick?.(event);
    if (track) {
      trackPress(track, label);
      onTrack?.(track, label);
    }
  };

  const classes = [
    'ds-button',
    `ds-button--${variant}`,
    `ds-button--${size}`,
    iconOnly ? 'ds-button--icon-only' : null,
    inverse ? 'ds-button--inverse' : null,
  ]
    .filter(Boolean)
    .join(' ');

  // copy.loading is the button's description while busy, never part of its accessible name: the
  // node is aria-hidden, which an aria-describedby reference still resolves through.
  const describedByValue = loading ? [describedBy, loadingId].filter(Boolean).join(' ') : describedBy;

  const hasLeading = leadingIcon !== undefined && leadingIcon !== null;
  const hasTrailing = trailingIcon !== undefined && trailingIcon !== null;

  return (
    <button
      {...rest}
      ref={ref}
      type={type}
      data-ds="Button"
      data-part="container"
      className={classes}
      style={overrides ? overridesToStyle(overrides) : undefined}
      aria-disabled={isDisabled ? 'true' : undefined}
      aria-busy={loading ? 'true' : undefined}
      aria-label={accessibleName ?? (iconOnly ? label : undefined)}
      aria-expanded={expanded ?? ariaExpanded}
      aria-describedby={describedByValue || undefined}
      onClick={handleClick}
    >
      {loading ? (
        <span className="ds-button__spinner" aria-hidden="true" />
      ) : hasLeading ? (
        <span className="ds-button__icon" data-part="leadingIcon" aria-hidden="true">
          {leadingIcon}
        </span>
      ) : null}
      {iconOnly ? null : (
        <span className="ds-button__label" data-part="label">
          {label}
        </span>
      )}
      {!loading && !iconOnly && hasTrailing ? (
        <span className="ds-button__icon" data-part="trailingIcon" aria-hidden="true">
          {trailingIcon}
        </span>
      ) : null}
      {loading ? (
        <span className="ds-button__visually-hidden" id={loadingId} aria-hidden="true">
          {COPY.loading}
        </span>
      ) : null}
    </button>
  );
}
