// packages/lit/src/Disclosure.ts
import { LitElement, css, nothing, type PropertyValues, type CSSResult, type TemplateResult } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { html, literal, type StaticValue } from 'lit/static-html.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';

export type DisclosureHeadingLevel = '2' | '3' | '4' | '5' | '6';

/** Why the disclosure changed state. */
export type DisclosureToggleReason = 'pointer' | 'keyboard' | 'controlled';

/** Detail carried by the `toggle` CustomEvent. */
export interface DisclosureToggleDetail {
  /** The new state. */
  open: boolean;
  /** `pointer` (clicked or tapped), `keyboard` (Enter or Space), `controlled` (the consumer changed `open`). */
  reason: DisclosureToggleReason;
}

/** Overridable style hooks; see the `overrides` property. `triggerColor`, `triggerBackgroundHover`, `icon`, `panelColor`, `focusRing`, `focusRingWidth` and `minTarget` are locked and excluded. */
export type DisclosureOverridableBinding =
  | 'triggerPaddingBlock'
  | 'triggerPaddingInline'
  | 'triggerGap'
  | 'triggerFontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight'
  | 'triggerLineHeight'
  | 'triggerRadius'
  | 'panelPaddingBlock'
  | 'panelPaddingInline'
  | 'disabledOpacity'
  | 'transition';

const HOOKS: Record<DisclosureOverridableBinding, string> = {
  triggerPaddingBlock: '--ds-disclosure-trigger-padding-block',
  triggerPaddingInline: '--ds-disclosure-trigger-padding-inline',
  triggerGap: '--ds-disclosure-trigger-gap',
  triggerFontFamily: '--ds-disclosure-trigger-font-family',
  triggerFontSize: '--ds-disclosure-trigger-font-size',
  triggerFontWeight: '--ds-disclosure-trigger-font-weight',
  triggerLineHeight: '--ds-disclosure-trigger-line-height',
  triggerRadius: '--ds-disclosure-trigger-radius',
  panelPaddingBlock: '--ds-disclosure-panel-padding-block',
  panelPaddingInline: '--ds-disclosure-panel-padding-inline',
  disabledOpacity: '--ds-disclosure-disabled-opacity',
  transition: '--ds-disclosure-transition',
};

const HEADINGS: Record<DisclosureHeadingLevel, StaticValue> = {
  '2': literal`h2`,
  '3': literal`h3`,
  '4': literal`h4`,
  '5': literal`h5`,
  '6': literal`h6`,
};

function isHeadingLevel(value: unknown): value is DisclosureHeadingLevel {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(HEADINGS, value);
}

/**
 * `<ds-disclosure>` — Disclosure (category: container, APG pattern: disclosure).
 *
 * `<ds-disclosure summary="Advanced options">…</ds-disclosure>` renders a
 * native `<button aria-expanded aria-controls>` trigger in its shadow root and
 * the panel as the default `<slot>`, which exists only while open. Light-DOM
 * children that are not assigned to a slot are neither rendered nor in the
 * accessibility tree, so a closed panel is genuinely gone — the consumer's
 * nodes are never given `hidden`. With `keepMounted` the slot is always
 * rendered and its wrapper gets `hidden` while closed, which is required when
 * the panel holds form fields (a `<ds-form>` reads `currentOpen` and
 * `keepMounted` and skips fields inside a closed disclosure without it).
 *
 * Uncontrolled from `defaultOpen` unless `open` is set; a controlled element
 * shows the new state only once `open` changes. Every change dispatches a
 * composed `toggle` CustomEvent with `{ open, reason }` after the state changes.
 *
 * ## When to use
 *
 * Use a Disclosure to hide secondary content that some users need and most do
 * not: optional settings, long explanations, a list of details behind a
 * summary count. Stack several to make an accordion — each is independent.
 * Set `headingLevel` when the summaries are section titles so they appear in
 * the outline.
 *
 * @fires toggle - Fired after the state changes with `{ open, reason }` in `detail`.
 * @slot - The panel content. Rendered only while open (always, but hidden while closed, with `keep-mounted`).
 */
@customElement('ds-disclosure')
export class DsDisclosure extends LitElement {
  static override shadowRootOptions: ShadowRootInit = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles: CSSResult = css`
    :host {
      display: block;
      --ds-disclosure-trigger-padding-block: var(--space-sm);
      --ds-disclosure-trigger-padding-inline: var(--space-sm);
      --ds-disclosure-trigger-gap: var(--space-2);
      --ds-disclosure-trigger-font-family: var(--font-family-body);
      --ds-disclosure-trigger-font-size: var(--font-size-md);
      --ds-disclosure-trigger-font-weight: var(--font-weight-medium);
      --ds-disclosure-trigger-line-height: var(--font-line-height-normal);
      --ds-disclosure-trigger-radius: var(--radius-md);
      --ds-disclosure-panel-padding-block: var(--space-sm);
      --ds-disclosure-panel-padding-inline: var(--space-sm);
      --ds-disclosure-disabled-opacity: var(--opacity-disabled);
      --ds-disclosure-transition: var(--motion-duration-base);
      /* Locked: no overrides entry, but the hook stays themeable from page CSS. */
      --ds-disclosure-trigger-color: var(--color-foreground);
      --ds-disclosure-trigger-background-hover: var(--color-background-subtle);
      --ds-disclosure-icon: var(--color-foreground-muted);
      --ds-disclosure-panel-color: var(--color-foreground);
      --ds-disclosure-focus-ring: var(--color-border-focus);
      --ds-disclosure-focus-ring-width: var(--border-width-focus);
      --ds-disclosure-min-target: var(--size-target-min);
    }

    :host([hidden]) {
      display: none;
    }

    /* The heading has no styling of its own — the button carries it. */
    .heading {
      margin: 0;
      padding: 0;
      font: inherit;
    }

    [data-part='trigger'] {
      box-sizing: border-box;
      display: inline-flex;
      align-items: center;
      gap: var(--ds-disclosure-trigger-gap);
      min-inline-size: var(--ds-disclosure-min-target);
      min-block-size: var(--ds-disclosure-min-target);
      margin: 0;
      padding-block: var(--ds-disclosure-trigger-padding-block);
      padding-inline: var(--ds-disclosure-trigger-padding-inline);
      border: 0;
      border-radius: var(--ds-disclosure-trigger-radius);
      font-family: var(--ds-disclosure-trigger-font-family);
      font-size: var(--ds-disclosure-trigger-font-size);
      font-weight: var(--ds-disclosure-trigger-font-weight);
      line-height: var(--ds-disclosure-trigger-line-height);
      text-align: start;
      color: var(--ds-disclosure-trigger-color);
      /* At rest the trigger has no fill; no token expresses its absence. */
      background: transparent;
      cursor: pointer;
      appearance: none;
      -webkit-appearance: none;
    }

    /* fullWidth: the whole row is the hit area; icon and summary stay at the start. */
    :host([full-width]) [data-part='trigger'] {
      display: flex;
      inline-size: 100%;
    }

    /* triggerBackgroundHover: pointer hover and pressed state, instant, suppressed while disabled */
    :host(:not([disabled])) [data-part='trigger']:is(:hover, :active) {
      background: var(--ds-disclosure-trigger-background-hover);
    }

    [data-part='trigger']:focus-visible {
      outline: var(--ds-disclosure-focus-ring-width) solid var(--ds-disclosure-focus-ring);
      outline-offset: var(--ds-disclosure-focus-ring-width);
    }

    :host([disabled]) [data-part='trigger'] {
      opacity: var(--ds-disclosure-disabled-opacity);
      cursor: not-allowed;
    }

    /* icon: the wrapper the Disclosure owns carries the colour and the rotation; the composed
       <ds-icon inline> is never restyled and tracks the trigger's font size through 1em. */
    [data-part='triggerIcon'] {
      display: inline-flex;
      flex: none;
      color: var(--ds-disclosure-icon);
      transition: transform var(--ds-disclosure-transition) var(--motion-easing-standard);
    }
    [aria-expanded='true'] [data-part='triggerIcon'] {
      transform: rotate(90deg);
    }
    :host(:dir(rtl)) [data-part='triggerIcon'] {
      transform: scaleX(-1);
    }
    :host(:dir(rtl)) [aria-expanded='true'] [data-part='triggerIcon'] {
      transform: scaleX(-1) rotate(90deg);
    }

    @media (prefers-reduced-motion: reduce) {
      [data-part='triggerIcon'] {
        transition: none;
      }
    }

    [data-part='panel'] {
      padding-block: var(--ds-disclosure-panel-padding-block);
      padding-inline: var(--ds-disclosure-panel-padding-inline);
      color: var(--ds-disclosure-panel-color);
    }
    [data-part='panel'][hidden] {
      display: none;
    }
  `;

  /** The trigger's label. Also its accessible name. Says what will be revealed. */
  @property() accessor summary = '';

  /** Controlled open state. Omit for an uncontrolled disclosure. */
  @property({ type: Boolean, reflect: true }) accessor open: boolean | undefined;

  /** Initial state for an uncontrolled disclosure. */
  @property({ type: Boolean, attribute: 'default-open' }) accessor defaultOpen = false;

  /** The trigger cannot be activated. Stays focusable and is announced as disabled; the panel keeps its current state. */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  /** Keep the panel in the tree while closed (hidden, not unmounted). Required when the panel contains form fields. */
  @property({ type: Boolean, reflect: true, attribute: 'keep-mounted' }) accessor keepMounted = false;

  /** The trigger spans the width of its row, so the whole row is the hit area. */
  @property({ type: Boolean, reflect: true, attribute: 'full-width' }) accessor fullWidth = false;

  /** When set, the trigger is wrapped in a heading of this level so it appears in the outline. */
  @property({ attribute: 'heading-level' }) accessor headingLevel: DisclosureHeadingLevel | undefined;

  /** Per-instance style overrides: `{ triggerRadius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) accessor overrides: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>> | undefined;

  /** Uncontrolled open state (seeded from `defaultOpen`). */
  @state() private accessor internalOpen = false;

  @query('[data-part=trigger]') private accessor triggerEl!: HTMLButtonElement | null;

  /** The resolved state rendered at the last update; `undefined` before the first. */
  private renderedOpen: boolean | undefined;

  /** The state the last user activation asked for, so the resulting prop change is not re-reported as `controlled`. */
  private requestedOpen: boolean | undefined;

  /**
   * Focus entered the panel and has not demonstrably moved elsewhere. Unassigning a focused node from the slot can
   * drop focus to the body without a focusout, so the flag is cleared only when focus lands somewhere known.
   */
  private focusWithinPanel = false;

  /** Set when a close happens while focus is within the panel; resolved after the render that removes it. */
  private restoreFocusPending = false;

  /** Whether the panel is currently open (controlled `open`, else the uncontrolled state). */
  get currentOpen(): boolean {
    return this.open ?? this.internalOpen;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Disclosure');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (!this.hasUpdated) {
      this.internalOpen = this.defaultOpen;
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
    // Closing removes (or hides) the panel: focus within it is handed to the trigger once the render lands,
    // whether the close came from the trigger or from a controlled `open` change.
    if (this.hasUpdated && this.renderedOpen === true && !this.currentOpen && this.focusWithinPanel) {
      this.focusWithinPanel = false;
      this.restoreFocusPending = true;
    }
  }

  protected override render(): TemplateResult {
    const isOpen = this.currentOpen;
    const panelExists = isOpen || this.keepMounted;
    const trigger = html`
      <button
        data-part="trigger"
        part="trigger"
        type="button"
        aria-expanded=${isOpen ? 'true' : 'false'}
        aria-controls=${ifDefined(panelExists ? 'panel' : undefined)}
        aria-disabled=${ifDefined(this.disabled ? 'true' : undefined)}
        @click=${this.handleClick}
      >
        <span data-part="triggerIcon" part="triggerIcon"
          ><ds-icon name="chevron-right" inline></ds-icon
        ></span>
        <span>${this.summary}</span>
      </button>
    `;
    const level = this.headingLevel;
    const heading = isHeadingLevel(level)
      ? html`<${HEADINGS[level]} class="heading">${trigger}</${HEADINGS[level]}>`
      : trigger;

    return html`
      ${heading}
      ${panelExists
        ? html`<div
            id="panel"
            data-part="panel"
            part="panel"
            ?hidden=${!isOpen}
            @focusin=${this.handlePanelFocusIn}
            @focusout=${this.handlePanelFocusOut}
          ><slot></slot></div>`
        : nothing}
    `;
  }

  protected override updated(changed: PropertyValues): void {
    const now = this.currentOpen;
    const previous = this.renderedOpen;
    this.renderedOpen = now;
    if (this.restoreFocusPending) {
      this.restoreFocusPending = false;
      this.restoreFocus();
    }
    if (!changed.has('open') && !changed.has('internalOpen')) return;
    const requested = this.requestedOpen;
    this.requestedOpen = undefined;
    // A consumer-driven change of `open` that no user activation asked for.
    if (previous !== undefined && previous !== now && changed.has('open') && requested !== now) {
      this.dispatchToggle(now, 'controlled');
    }
  }

  private handleClick(event: MouseEvent): void {
    if (this.disabled) {
      event.preventDefault();
      return;
    }
    const next = !this.currentOpen;
    // A keyboard activation of a native button produces a click with detail 0.
    const reason: DisclosureToggleReason = event.detail === 0 ? 'keyboard' : 'pointer';
    if (this.open === undefined) {
      this.internalOpen = next;
    } else {
      // Controlled: the new state shows only once the consumer sets `open`.
      this.requestedOpen = next;
    }
    this.dispatchToggle(next, reason);
  }

  private dispatchToggle(open: boolean, reason: DisclosureToggleReason): void {
    this.dispatchEvent(
      new CustomEvent<DisclosureToggleDetail>('toggle', {
        detail: { open, reason },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private handlePanelFocusIn(): void {
    this.focusWithinPanel = true;
  }

  private handlePanelFocusOut(event: FocusEvent): void {
    const to = event.relatedTarget;
    // Slotted panel content is the host's light DOM; the trigger lives in the shadow root, so it is not contained.
    if (to instanceof Node && (to === this || !this.contains(to))) {
      this.focusWithinPanel = false;
    }
  }

  /** Focus still inside the closed panel, or dropped to the body when the panel went away, moves to the trigger. */
  private restoreFocus(): void {
    const active = document.activeElement;
    const lost = active === null || active === document.body || (active !== this && this.contains(active));
    if (lost) this.triggerEl?.focus();
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as DisclosureOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-disclosure': DsDisclosure;
  }
}

// packages/react/src/Disclosure.tsx
import {
  useEffect,
  useId,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type ElementType,
  type MouseEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Icon } from './Icon';
import './Disclosure.css';

/** Accepts the schema's string values and their numeric equivalents. */
export type DisclosureHeadingLevel = '2' | '3' | '4' | '5' | '6' | 2 | 3 | 4 | 5 | 6;

/** Why the state changed: a pointer click, a keyboard activation (Enter/Space), or an external `open` prop change. */
export type DisclosureToggleReason = 'pointer' | 'keyboard' | 'controlled';

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type DisclosureOverridableBinding =
  | 'triggerPaddingBlock'
  | 'triggerPaddingInline'
  | 'triggerGap'
  | 'triggerFontFamily'
  | 'triggerFontSize'
  | 'triggerFontWeight'
  | 'triggerLineHeight'
  | 'triggerRadius'
  | 'panelPaddingBlock'
  | 'panelPaddingInline'
  | 'disabledOpacity'
  | 'transition';

const OVERRIDE_HOOK: Record<DisclosureOverridableBinding, string> = {
  triggerPaddingBlock: '--ds-disclosure-trigger-padding-block',
  triggerPaddingInline: '--ds-disclosure-trigger-padding-inline',
  triggerGap: '--ds-disclosure-trigger-gap',
  triggerFontFamily: '--ds-disclosure-trigger-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  triggerFontSize: '--ds-disclosure-trigger-font-size',
  triggerFontWeight: '--ds-disclosure-trigger-font-weight',
  triggerLineHeight: '--ds-disclosure-trigger-line-height',
  triggerRadius: '--ds-disclosure-trigger-radius',
  panelPaddingBlock: '--ds-disclosure-panel-padding-block',
  panelPaddingInline: '--ds-disclosure-panel-padding-inline',
  disabledOpacity: '--ds-disclosure-disabled-opacity',
  transition: '--ds-disclosure-transition',
};

function overridesToStyle(overrides: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>>): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as DisclosureOverridableBinding[]) {
    // Locked bindings are not in the type; anything passed anyway has no hook and is ignored.
    const hook = OVERRIDE_HOOK[binding] as string | undefined;
    const ref = overrides[binding];
    if (hook && ref) style[hook] = cssVar(ref);
  }
  return style as CSSProperties;
}

export interface DisclosureProps
  extends Omit<
    ComponentPropsWithoutRef<'button'>,
    | 'type'
    | 'disabled'
    | 'children'
    | 'className'
    | 'style'
    | 'aria-expanded'
    | 'aria-controls'
    | 'aria-disabled'
    | 'onToggle'
    | 'onClick'
  > {
  /** The trigger's label. Also the trigger's accessible name. Says what will be revealed. */
  summary: string;
  /** The content of the panel. Rendered only while open (not merely hidden), so heavy content is not laid out until asked for. */
  children: ReactNode;
  /** Controlled open state. Omit for an uncontrolled disclosure. */
  open?: boolean | undefined;
  /** Initial state for an uncontrolled disclosure. */
  defaultOpen?: boolean | undefined;
  /** The trigger cannot be activated. Stays focusable and is announced as disabled; the panel keeps its current state. */
  disabled?: boolean | undefined;
  /**
   * Keep the panel in the tree while closed (hidden, not unmounted). Required when the panel contains form fields,
   * so the Form still collects them while the disclosure is closed.
   */
  keepMounted?: boolean | undefined;
  /**
   * The trigger spans the width of its row, so the whole row is the hit area (and the hover fill runs edge to edge)
   * rather than ending at the summary text. The icon and summary stay at the start; the rest of the row is empty
   * trigger.
   */
  fullWidth?: boolean | undefined;
  /**
   * When set, the trigger is wrapped in a heading of this level so the disclosure appears in the document outline —
   * use for FAQ and accordion sections.
   */
  headingLevel?: DisclosureHeadingLevel | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<DisclosureOverridableBinding, TokenRef | undefined>> | undefined;
  /**
   * Fired after the state changes, with the new boolean `open` and a reason: `pointer`, `keyboard`, or `controlled`
   * (Accordion relies on it). The activation method is read from the native click (`event.detail === 0` means keyboard).
   */
  onToggle?: ((open: boolean, reason: DisclosureToggleReason) => void) | undefined;
}

/**
 * Disclosure — Design Schema, category: container.
 *
 * When to use:
 * Use a Disclosure to hide secondary content that some users need and most do not: optional settings, long
 * explanations, a list of details behind a summary count. Stack several to make an accordion — each is independent;
 * nothing in this component closes its siblings. Set `headingLevel` when the summaries are section titles so they
 * appear in the outline and screen-reader heading lists.
 *
 * `ref` resolves to the trigger `<button>` (Accordion moves focus between triggers through it); the wrapping `<div>`
 * carries `data-ds="Disclosure"`.
 */
export function Disclosure({
  ref,
  summary,
  children,
  open,
  defaultOpen = false,
  disabled = false,
  keepMounted = false,
  fullWidth = false,
  headingLevel,
  overrides,
  onToggle,
  id: idProp,
  ...rest
}: DisclosureProps & { ref?: Ref<HTMLButtonElement> | undefined }): ReactElement {
  const generatedId = useId();
  const id = idProp ?? `ds-disclosure${generatedId}`;
  const panelId = `${id}-panel`;

  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  useImperativeHandle(ref, () => triggerRef.current as HTMLButtonElement, []);

  const isControlled = open !== undefined;
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const isOpen = isControlled ? open : internalOpen;
  const panelExists = isOpen || keepMounted;

  // Closing removes (or hides) the panel, so focus inside it is handed to the trigger — whether the close came from
  // the trigger or from a controlled `open` change. Removal can blur without a focusout, so the flag is only cleared
  // when focus demonstrably moved somewhere else.
  const focusWithinPanel = useRef(false);
  useLayoutEffect(() => {
    if (isOpen || !focusWithinPanel.current) return;
    focusWithinPanel.current = false;
    const active = document.activeElement;
    const lost = active === null || active === document.body || (panelRef.current?.contains(active) ?? false);
    if (lost) triggerRef.current?.focus();
  }, [isOpen]);

  // Controlled: a user toggle is reported at once (the state changes only when the consumer echoes it), and an `open`
  // change that echoes that report does not fire again; any other `open` change reports 'controlled'. Uncontrolled:
  // the toggle is reported after the new state has committed. A pending request is cleared at the next `open` change.
  const previousOpenRef = useRef(isOpen);
  const selfEmittedRef = useRef<boolean | null>(null);
  const pendingReasonRef = useRef<DisclosureToggleReason | null>(null);
  useEffect(() => {
    if (previousOpenRef.current === isOpen) return;
    previousOpenRef.current = isOpen;
    const echo = selfEmittedRef.current === isOpen;
    selfEmittedRef.current = null;
    const reason = pendingReasonRef.current;
    pendingReasonRef.current = null;
    if (isControlled) {
      if (!echo) onToggle?.(isOpen, 'controlled');
    } else if (reason !== null) {
      onToggle?.(isOpen, reason);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  const handleClick = (event: MouseEvent<HTMLButtonElement>): void => {
    if (disabled) {
      event.preventDefault();
      return;
    }
    const next = !isOpen;
    // A native button's click carries `detail: 0` when Enter or Space activated it.
    const reason: DisclosureToggleReason = event.detail === 0 ? 'keyboard' : 'pointer';
    if (isControlled) {
      selfEmittedRef.current = next;
      onToggle?.(next, reason);
    } else {
      pendingReasonRef.current = reason;
      setInternalOpen(next);
    }
  };

  const trigger = (
    <button
      {...rest}
      ref={triggerRef}
      id={id}
      type="button"
      className="ds-disclosure__trigger"
      data-part="trigger"
      aria-expanded={isOpen ? 'true' : 'false'}
      aria-controls={panelExists ? panelId : undefined}
      aria-disabled={disabled ? 'true' : undefined}
      onClick={handleClick}
    >
      <span className="ds-disclosure__icon" data-part="triggerIcon">
        <Icon name="chevron-right" inline />
      </span>
      <span className="ds-disclosure__summary">{summary}</span>
    </button>
  );

  // The heading has no styling of its own; the button carries it.
  const HeadingTag = headingLevel !== undefined ? (`h${headingLevel}` as ElementType) : null;

  const rootClass = ['ds-disclosure', isOpen && 'ds-disclosure--open', fullWidth && 'ds-disclosure--full-width']
    .filter(Boolean)
    .join(' ');

  return (
    <div
      className={rootClass}
      data-ds="Disclosure"
      style={overrides ? overridesToStyle(overrides) : undefined}
    >
      {HeadingTag ? <HeadingTag className="ds-disclosure__heading">{trigger}</HeadingTag> : trigger}
      {panelExists ? (
        <div
          ref={panelRef}
          id={panelId}
          className="ds-disclosure__panel"
          data-part="panel"
          hidden={!isOpen}
          onFocus={() => {
            focusWithinPanel.current = true;
          }}
          onBlur={(event) => {
            const to = event.relatedTarget as Node | null;
            if (to !== null && !event.currentTarget.contains(to)) focusWithinPanel.current = false;
          }}
        >
          {children}
        </div>
      ) : null}
    </div>
  );
}
