// packages/lit/src/Heading.ts
import { LitElement, css, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { html, literal, type StaticValue } from 'lit/static-html.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';

export type HeadingLevel = '1' | '2' | '3' | '4' | '5' | '6';
export type HeadingSize = '4xl' | '3xl' | '2xl' | 'xl' | 'lg' | 'md';
export type HeadingAlign = 'start' | 'center' | 'end';

/** Overridable style hooks; see the `overrides` property. `color` is locked and excluded. */
export type HeadingOverridableBinding = 'fontFamily' | 'fontWeight' | 'fontSize' | 'lineHeight' | 'marginBlockEnd';

const HOOKS: Record<HeadingOverridableBinding, string> = {
  fontFamily: `--ds-heading-font-family`,
  fontWeight: '--ds-heading-font-weight',
  fontSize: '--ds-heading-font-size',
  lineHeight: '--ds-heading-line-height',
  marginBlockEnd: '--ds-heading-margin-block-end',
};

const TAGS: Record<HeadingLevel, StaticValue> = {
  '1': literal`h1`,
  '2': literal`h2`,
  '3': literal`h3`,
  '4': literal`h4`,
  '5': literal`h5`,
  '6': literal`h6`,
};

function isHeadingLevel(value: unknown): value is HeadingLevel {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(TAGS, value);
}

/**
 * `<ds-heading>` — Heading (category: typography).
 *
 * `<ds-heading level="2">` renders a real `<h2>` inside its shadow root with
 * `part="heading"`. `level` chooses the element (document outline); `size`
 * chooses the visual size independently and defaults to the size that matches
 * the level (1→4xl, 2→3xl, 3→2xl, 4→xl, 5→lg, 6→md).
 *
 * ## When to use
 *
 * Use a Heading to title a page, a section, or a card that contains its own
 * content. Choose `level` from the document outline — the page title is `1`,
 * its major sections are `2`, their subsections `3` — and then choose `size`
 * separately if the default visual size is wrong for the layout. Decoupling
 * level from size is the whole point of this component: it lets designers pick
 * the right look without breaking the outline.
 *
 * @slot - The heading text. Keep it short and descriptive; it is what appears in the page outline.
 * @csspart heading - The rendered `<h1>`–`<h6>`.
 */
@customElement('ds-heading')
export class DsHeading extends LitElement {
  static override styles = css`
    :host {
      display: block;
      --ds-heading-font-family: var(--font-family-heading);
      --ds-heading-font-weight: var(--font-weight-semibold);
      --ds-heading-font-size: var(--font-size-3xl);
      --ds-heading-line-height: var(--font-line-height-tight);
      --ds-heading-margin-block-end: var(--space-sm);
    }

    :host([hidden]) {
      display: none;
    }

    .heading {
      margin-block: 0 var(--ds-heading-margin-block-end);
      margin-inline: 0;
      font-family: var(--ds-heading-font-family);
      font-weight: var(--ds-heading-font-weight);
      font-size: var(--ds-heading-font-size);
      line-height: var(--ds-heading-line-height);
      /* color: color.foreground.strong, locked — no override hook */
      color: var(--color-foreground-strong);
      text-align: start;
    }

    /* fontSize: font.size.{size} default per level */
    :host([level='1']) {
      --ds-heading-font-size: var(--font-size-4xl);
    }
    :host([level='2']) {
      --ds-heading-font-size: var(--font-size-3xl);
    }
    :host([level='3']) {
      --ds-heading-font-size: var(--font-size-2xl);
    }
    :host([level='4']) {
      --ds-heading-font-size: var(--font-size-xl);
    }
    :host([level='5']) {
      --ds-heading-font-size: var(--font-size-lg);
    }
    :host([level='6']) {
      --ds-heading-font-size: var(--font-size-md);
    }

    /* fontSize: an explicit size wins over the level default */
    :host([size='4xl']) {
      --ds-heading-font-size: var(--font-size-4xl);
    }
    :host([size='3xl']) {
      --ds-heading-font-size: var(--font-size-3xl);
    }
    :host([size='2xl']) {
      --ds-heading-font-size: var(--font-size-2xl);
    }
    :host([size='xl']) {
      --ds-heading-font-size: var(--font-size-xl);
    }
    :host([size='lg']) {
      --ds-heading-font-size: var(--font-size-lg);
    }
    :host([size='md']) {
      --ds-heading-font-size: var(--font-size-md);
    }

    :host([align='start']) .heading {
      text-align: start;
    }
    :host([align='center']) .heading {
      text-align: center;
    }
    :host([align='end']) .heading {
      text-align: end;
    }
  `;

  /**
   * Position in the document outline. Controls the semantic element, not the
   * visual size. Required; a missing or unknown level falls back to `<h2>`.
   */
  @property({ reflect: true }) level!: HeadingLevel;

  /** Visual size, independent of level. Defaults to the size that matches the level. */
  @property({ reflect: true }) size?: HeadingSize;

  /** Horizontal text alignment. */
  @property({ reflect: true }) align: HeadingAlign = 'start';

  /** Per-instance style overrides: `{ fontSize: 'font.size.lg' }`. `color` is locked and ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<HeadingOverridableBinding, TokenRef>>;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Heading');
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render() {
    const tag = isHeadingLevel(this.level) ? TAGS[this.level] : TAGS['2'];
    return html`<${tag} class="heading" part="heading"><slot></slot></${tag}>`;
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as HeadingOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-heading': DsHeading;
  }
}

// packages/react/src/Heading.tsx
import { type ComponentPropsWithoutRef, type CSSProperties, type ElementType, type ReactNode, type Ref, type ReactElement } from 'react';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Heading.css';

/** Position in the document outline. Accepts the schema's string values and their numeric equivalents. */
export type HeadingLevel = '1' | '2' | '3' | '4' | '5' | '6' | 1 | 2 | 3 | 4 | 5 | 6;
export type HeadingSize = '4xl' | '3xl' | '2xl' | 'xl' | 'lg' | 'md';
export type HeadingAlign = 'start' | 'center' | 'end';

/** Style bindings that can be overridden per instance; accessibility-bearing bindings are never in this list. */
export type HeadingOverridableBinding = 'fontFamily' | 'fontWeight' | 'fontSize' | 'lineHeight' | 'marginBlockEnd';

const OVERRIDE_HOOK: Record<HeadingOverridableBinding, string> = {
  fontFamily: '--ds-heading-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  fontWeight: '--ds-heading-font-weight',
  fontSize: '--ds-heading-font-size',
  lineHeight: '--ds-heading-line-height',
  marginBlockEnd: '--ds-heading-margin-block-end',
};

function overridesToStyle(overrides: Partial<Record<HeadingOverridableBinding, TokenRef | undefined>>): CSSProperties {
  const style: Record<string, string> = {};
  for (const binding of Object.keys(overrides) as HeadingOverridableBinding[]) {
    const ref = overrides[binding];
    if (ref) style[OVERRIDE_HOOK[binding]] = cssVar(ref);
  }
  return style as CSSProperties;
}

export interface HeadingProps extends Omit<ComponentPropsWithoutRef<'h1'>, 'children'> {
  /** Position in the document outline. Controls the semantic element, not the visual size. */
  level: HeadingLevel;
  /** Visual size, independent of level. Defaults to the size that matches the level. */
  size?: HeadingSize | undefined;
  /** The heading text. Keep it short and descriptive; it is what appears in the page outline. */
  children: ReactNode;
  /** Horizontal text alignment. */
  align?: HeadingAlign | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<HeadingOverridableBinding, TokenRef | undefined>> | undefined;
}

const ELEMENT_BY_LEVEL = {
  '1': 'h1',
  '2': 'h2',
  '3': 'h3',
  '4': 'h4',
  '5': 'h5',
  '6': 'h6',
} as const;

const SIZE_BY_LEVEL: Record<keyof typeof ELEMENT_BY_LEVEL, HeadingSize> = {
  '1': '4xl',
  '2': '3xl',
  '3': '2xl',
  '4': 'xl',
  '5': 'lg',
  '6': 'md',
};

/**
 * Heading — Design Schema, category: typography.
 *
 * When to use:
 * Use a Heading to title a page, a section, or a card that contains its own content. Choose
 * `level` from the document outline — the page title is `1`, its major sections are `2`, their
 * subsections `3` — and then choose `size` separately if the default visual size is wrong for the
 * layout. Decoupling level from size is the whole point of this component: it lets designers pick
 * the right look without breaking the outline.
 */
export const Heading = function Heading({ ref, level, size, children, align = 'start', overrides, className, style, ...rest }: HeadingProps & { ref?: Ref<HTMLHeadingElement> | undefined }): ReactElement {
  const key = String(level) as keyof typeof ELEMENT_BY_LEVEL;
  const Tag: ElementType = ELEMENT_BY_LEVEL[key];
  const resolvedSize = size ?? SIZE_BY_LEVEL[key];

  const classes = ['ds-heading', `ds-heading--size-${resolvedSize}`, `ds-heading--align-${align}`, className ?? null]
    .filter(Boolean)
    .join(' ');

  const overrideStyle = overrides ? overridesToStyle(overrides) : undefined;
  const mergedStyle = overrideStyle || style ? { ...overrideStyle, ...style } : undefined;

  return (
    <Tag {...rest} ref={ref as Ref<HTMLHeadingElement>} data-ds="Heading" data-part="text" className={classes} style={mergedStyle}>
      {children}
    </Tag>
  );
};
