// packages/lit/src/Toast.ts
import { LitElement, css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import './Icon.js';
import './Text.js';
import './Button.js';
import type { TextOverridableBinding } from './Text.js';

export type ToastTone = 'neutral' | 'success' | 'warning' | 'danger';
export type ToastDuration = 'short' | 'long' | 'persistent';
export type ToastDismissReason = 'timeout' | 'dismiss-button' | 'action' | 'replaced';

/** Detail carried by the `action` CustomEvent (none). */
export type ToastActionDetail = void;

/** Detail carried by the `dismiss` CustomEvent. */
export interface ToastDismissDetail {
  reason: ToastDismissReason;
}

/** copy.dismissLabel */
const COPY_DISMISS_LABEL = 'Dismiss';
/** copy.regionLabel */
const COPY_REGION_LABEL = 'Notifications';

/** Negates a boolean attribute: `no-dismiss` present means `dismissible` is `false`. */
const NEGATED_BOOLEAN_CONVERTER = {
  fromAttribute(value: string | null): boolean {
    return value === null;
  },
  toAttribute(value: boolean): string | null {
    return value ? null : '';
  },
};

/** `duration: short` multiplies motion.duration.loop by this to get ~5s. */
const SHORT_MULTIPLIER = 6;
/** `duration: long` multiplies motion.duration.loop by this to get ~10s. */
const LONG_MULTIPLIER = 12;

/**
 * Safety margin, in ms, added on top of the read `--ds-toast-exit` duration
 * before forcing removal if `transitionend` never fires. Not a design token —
 * a defensive timing, not a motion one.
 */
const EXIT_FALLBACK_BUFFER_MS = 50;

/** At most this many toasts stack; showing another evicts the oldest. */
const MAX_TOASTS = 3;

/** Overridable style hooks; see the `overrides` property. `surface`, `text`, `icon`, `actionColor`, `dismissColor`, `focusRingInverse`, `minTarget`, `focusRing` and `focusRingWidth` are locked and excluded. */
export type ToastOverridableBinding =
  | 'radius'
  | 'shadow'
  | 'paddingBlock'
  | 'paddingInline'
  | 'gap'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'enter'
  | 'exit';

const HOOKS: Record<ToastOverridableBinding, string> = {
  radius: '--ds-toast-radius',
  shadow: '--ds-toast-shadow',
  paddingBlock: '--ds-toast-padding-block',
  paddingInline: '--ds-toast-padding-inline',
  gap: '--ds-toast-gap',
  maxWidth: '--ds-toast-max-width',
  fontFamily: '--ds-toast-font-family', // literal-ok: CSS custom-property name, not a font stack
  fontSize: '--ds-toast-font-size',
  lineHeight: '--ds-toast-line-height',
  enter: '--ds-toast-enter',
  exit: '--ds-toast-exit',
};

/** Overridable style hooks for `<ds-toast-region>`; see its `overrides` property. `layer` sets the region's stacking context. */
export type ToastRegionOverridableBinding = 'stackGap' | 'regionInset' | 'layer';

const REGION_HOOKS: Record<ToastRegionOverridableBinding, string> = {
  stackGap: '--ds-toast-region-stack-gap',
  regionInset: '--ds-toast-region-inset',
  layer: '--ds-toast-region-layer',
};

function prefersReducedMotion(): boolean {
  return typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/** Reads a `--motion-duration-*`-shaped custom property off `el` and returns it in ms. */
function readDurationMs(el: HTMLElement, varName: string): number {
  const raw = getComputedStyle(el).getPropertyValue(varName).trim();
  if (raw.endsWith('ms')) {
    return parseFloat(raw);
  }
  if (raw.endsWith('s')) {
    return parseFloat(raw) * 1000;
  }
  return 0;
}

/**
 * `<ds-toast>` — Toast (category: feedback, APG pattern: alert).
 *
 * One notification. Never created directly by consumers — the `toast()`
 * function below appends it to a lazily-created `<ds-toast-region>` in
 * `document.body`. The host takes `role="status"` (`"alert"` for `tone:
 * "danger"`) and its accessible name through `ElementInternals`, set to
 * `message`, so the live region and its name live in the light DOM tree.
 * Inside the shadow root: the tone icon (`neutral` has none), the message as
 * `<ds-text>`, an inverse-ghost `<ds-button>` for the action, and an
 * inverse-ghost icon-only `<ds-button>` for dismiss. A timer dismisses the
 * toast after `duration`, pausing while hovered, focused, or the page is
 * hidden; persistent toasts have no timer. Escape and the dismiss button both
 * dismiss with a short exit transition (instant under reduced motion), after
 * which the element removes itself.
 *
 * ## When to use
 *
 * Use a Toast to confirm a completed action that the user did not have to
 * watch, to offer Undo for a reversible action, or to report a background
 * result. Match `tone` to the outcome; use `duration: "persistent"` whenever
 * there is an action, and for `danger`, so nobody misses the one they needed.
 *
 * ## When not to use
 *
 * Not for errors that need fixing (an Alert next to the problem), not for
 * anything the user must read (Alert or Dialog), and not for more than one
 * action.
 *
 * @fires action - The action button was activated. Followed by `dismiss` with `reason: 'action'`.
 * @fires dismiss - The toast left the screen, with `{ reason }` (`timeout`, `dismiss-button`, `action`, or `replaced`).
 * @csspart toast - The container (anatomy: toast).
 * @csspart icon - The tone icon (anatomy: icon).
 * @csspart message - The `<ds-text>` (anatomy: message).
 * @csspart action-button - The action `<ds-button>` (anatomy: actionButton).
 * @csspart dismiss-button - The dismiss `<ds-button>` (anatomy: dismissButton).
 */
@customElement('ds-toast')
export class DsToast extends LitElement {
  static override styles = css`
    :host {
      display: block;
      box-sizing: border-box;
      --ds-toast-radius: var(--radius-md);
      --ds-toast-shadow: var(--shadow-overlay);
      --ds-toast-padding-block: var(--space-sm);
      --ds-toast-padding-inline: var(--space-md);
      --ds-toast-gap: var(--layout-gap-normal);
      --ds-toast-max-width: var(--layout-max-width-prose);
      --ds-toast-font-family: var(--font-family-body);
      --ds-toast-font-size: var(--font-size-md);
      --ds-toast-line-height: var(--font-line-height-normal);
      --ds-toast-enter: var(--motion-duration-base);
      --ds-toast-exit: var(--motion-duration-fast);
      max-inline-size: var(--ds-toast-max-width);
    }

    :host([hidden]) {
      display: none;
    }

    .container {
      box-sizing: border-box;
      display: flex;
      align-items: center;
      gap: var(--ds-toast-gap);
      padding-block: var(--ds-toast-padding-block);
      padding-inline: var(--ds-toast-padding-inline);
      border-radius: var(--ds-toast-radius);
      box-shadow: var(--ds-toast-shadow);
      /* surface: color.inverse.surface, locked — inverted like Tooltip, so it floats above any page surface */
      background: var(--color-inverse-surface);
      opacity: 1;
      transform: translateY(0);
      transition:
        opacity var(--ds-toast-enter) var(--motion-easing-standard),
        transform var(--ds-toast-enter) var(--motion-easing-standard);
    }

    @starting-style {
      .container {
        opacity: 0;
        transform: translateY(var(--space-2));
      }
    }

    /* exit: motion.duration.fast, replacing the enter duration while leaving */
    .container.closing {
      opacity: 0;
      transform: translateY(var(--space-2));
      transition-duration: var(--ds-toast-exit);
    }

    @media (prefers-reduced-motion: reduce) {
      .container {
        transition: none;
      }
    }

    .icon {
      flex: none;
    }

    /* icon: color.inverse.status.{tone}, locked — neutral renders no icon */
    :host([tone='success']) .icon {
      color: var(--color-inverse-status-success);
    }
    :host([tone='warning']) .icon {
      color: var(--color-inverse-status-warning);
    }
    :host([tone='danger']) .icon {
      color: var(--color-inverse-status-danger);
    }

    .message {
      flex: 1 1 auto;
      min-inline-size: 0;
    }

    .action,
    .dismiss {
      flex: none;
    }
  `;

  /** One sentence, past tense, saying what happened ("Message sent", "3 files deleted"). Also the toast's accessible name. */
  @property() message!: string;

  /** Sets the leading icon; `neutral` has none. Toasts never use tinted backgrounds — the icon and message carry the tone. */
  @property({ reflect: true }) tone: ToastTone = 'neutral';

  /** Label for a single action button ("Undo", "View"). Recommended as `persistent` so there is time to use it. */
  @property({ attribute: 'action-label' }) actionLabel?: string;

  /** `short` ≈ 5s, `long` ≈ 10s (motion.duration.loop × 6 / × 12), `persistent` until dismissed. */
  @property({ reflect: true }) duration: ToastDuration = 'short';

  /** Stable identity; showing a toast with the same `toastId` replaces this one instead of stacking. Named `toastId` (attribute `toast-id`) so it does not collide with the DOM `id`. */
  @property({ attribute: 'toast-id' }) toastId?: string;

  /** Shows a dismiss button. Persistent toasts are always dismissible regardless of this value. Exposed as the negated `no-dismiss` attribute (a boolean attribute cannot express `false` for a prop that defaults `true`). */
  @property({ attribute: 'no-dismiss', converter: NEGATED_BOOLEAN_CONVERTER }) dismissible = true;

  /** Per-instance style overrides: `{ radius: 'radius.sm' }`. Locked bindings are ignored. */
  @property({ attribute: false }) overrides?: Partial<Record<ToastOverridableBinding, TokenRef>>;

  @query('.container') private readonly containerEl!: HTMLElement;

  @state() private closing = false;

  private readonly internals: ElementInternals;
  private dismissed = false;
  private timerId?: ReturnType<typeof setTimeout>;
  private remainingMs: number | null = null;
  private timerStartedAt = 0;
  private pointerOver = false;
  private focused = false;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  private get showDismiss(): boolean {
    return this.dismissible || this.duration === 'persistent';
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'Toast');
    this.addEventListener('pointerenter', this.handlePointerEnter);
    this.addEventListener('pointerleave', this.handlePointerLeave);
    this.addEventListener('focusin', this.handleFocusIn);
    this.addEventListener('focusout', this.handleFocusOut);
    this.addEventListener('keydown', this.handleKeydown);
    document.addEventListener('visibilitychange', this.handleVisibilityChange);
    this.startTimer();
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.clearTimer();
    this.removeEventListener('pointerenter', this.handlePointerEnter);
    this.removeEventListener('pointerleave', this.handlePointerLeave);
    this.removeEventListener('focusin', this.handleFocusIn);
    this.removeEventListener('focusout', this.handleFocusOut);
    this.removeEventListener('keydown', this.handleKeydown);
    document.removeEventListener('visibilitychange', this.handleVisibilityChange);
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('tone')) {
      // role="status" implies aria-live="polite"; role="alert" implies assertive.
      this.internals.role = this.tone === 'danger' ? 'alert' : 'status';
    }
    if (changed.has('message')) {
      // A literal attribute, not `internals.ariaLabel`: ARIAMixin values set through
      // ElementInternals aren't visible to the accessible-name computation the test
      // suite uses (only real attributes are), though real assistive tech reads either.
      if (this.message) {
        this.setAttribute('aria-label', this.message);
      } else {
        this.removeAttribute('aria-label');
      }
    }
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override updated(): void {
    this.warnInDev();
  }

  protected override render() {
    const textOverrides: Partial<Record<TextOverridableBinding, TokenRef>> = {
      color: 'color.inverse.foreground',
    };
    if (this.overrides?.fontFamily) {
      textOverrides.fontFamily = this.overrides.fontFamily;
    }
    if (this.overrides?.fontSize) {
      textOverrides.fontSize = this.overrides.fontSize;
    }
    if (this.overrides?.lineHeight) {
      textOverrides.lineHeight = this.overrides.lineHeight;
    }

    return html`
      <div class="container${this.closing ? ' closing' : ''}" part="toast">
        ${this.tone === 'neutral'
          ? nothing
          : html`<ds-icon class="icon" part="icon" name=${this.tone}></ds-icon>`}
        <ds-text class="message" part="message" element="span" size="md" .overrides=${textOverrides}
          >${this.message}</ds-text
        >
        ${this.actionLabel
          ? html`
              <ds-button
                class="action"
                part="action-button"
                variant="ghost"
                inverse
                size="sm"
                label=${this.actionLabel}
                @press=${this.handleActionPress}
              ></ds-button>
            `
          : nothing}
        ${this.showDismiss
          ? html`
              <ds-button
                class="dismiss"
                part="dismiss-button"
                variant="ghost"
                inverse
                size="sm"
                icon-only
                label=${COPY_DISMISS_LABEL}
                @press=${this.handleDismissPress}
              >
                <ds-icon slot="leading-icon" name="close" inline></ds-icon>
              </ds-button>
            `
          : nothing}
      </div>
    `;
  }

  private readonly handleActionPress = (event: Event): void => {
    // Keep the button's `press` inside the toast; consumers listen for `action`/`dismiss`.
    event.stopPropagation();
    this.dispatchEvent(new CustomEvent<ToastActionDetail>('action', { bubbles: true, composed: true }));
    this.requestDismiss('action');
  };

  private readonly handleDismissPress = (event: Event): void => {
    event.stopPropagation();
    this.requestDismiss('dismiss-button');
  };

  private readonly handleKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      event.stopPropagation();
      // No 'escape' reason exists on ToastDismissReason; treated as an explicit manual dismissal.
      this.requestDismiss('dismiss-button');
    }
  };

  private readonly handlePointerEnter = (): void => {
    this.pointerOver = true;
    this.pauseTimer();
  };

  private readonly handlePointerLeave = (): void => {
    this.pointerOver = false;
    this.maybeResumeTimer();
  };

  private readonly handleFocusIn = (): void => {
    this.focused = true;
    this.pauseTimer();
  };

  private readonly handleFocusOut = (): void => {
    this.focused = false;
    this.maybeResumeTimer();
  };

  private readonly handleVisibilityChange = (): void => {
    if (document.hidden) {
      this.pauseTimer();
    } else {
      this.maybeResumeTimer();
    }
  };

  /** Dispatches `dismiss` and plays the exit transition; called for every dismissal path, including eviction by `toast()`. */
  public requestDismiss(reason: ToastDismissReason): void {
    if (this.dismissed) {
      return;
    }
    this.dismissed = true;
    this.clearTimer();
    this.dispatchEvent(
      new CustomEvent<ToastDismissDetail>('dismiss', { detail: { reason }, bubbles: true, composed: true }),
    );
    this.playExit();
  }

  private computeDurationMs(): number | null {
    if (this.duration === 'persistent') {
      return null;
    }
    const loop = readDurationMs(this, '--motion-duration-loop');
    return loop * (this.duration === 'long' ? LONG_MULTIPLIER : SHORT_MULTIPLIER);
  }

  private startTimer(): void {
    const ms = this.computeDurationMs();
    if (ms === null) {
      return;
    }
    this.remainingMs = ms;
    this.scheduleTimer();
  }

  private scheduleTimer(): void {
    if (this.remainingMs === null) {
      return;
    }
    this.timerStartedAt = Date.now();
    this.timerId = setTimeout(() => this.requestDismiss('timeout'), Math.max(0, this.remainingMs));
  }

  private pauseTimer(): void {
    if (this.timerId === undefined || this.remainingMs === null) {
      return;
    }
    clearTimeout(this.timerId);
    this.timerId = undefined;
    this.remainingMs -= Date.now() - this.timerStartedAt;
  }

  private maybeResumeTimer(): void {
    if (this.dismissed || this.timerId !== undefined || this.remainingMs === null) {
      return;
    }
    if (this.pointerOver || this.focused || document.hidden) {
      return;
    }
    this.scheduleTimer();
  }

  private clearTimer(): void {
    clearTimeout(this.timerId);
    this.timerId = undefined;
  }

  /** Plays the exit transition (instant under reduced motion), then removes the element from the DOM. */
  private playExit(): void {
    const finish = (): void => {
      const region = this.closest('ds-toast-region');
      if (this.contains(document.activeElement) && region instanceof DsToastRegion) {
        region.restoreFocus();
      }
      this.remove();
    };

    if (prefersReducedMotion()) {
      finish();
      return;
    }

    this.closing = true;
    const container = this.containerEl;
    if (!container) {
      finish();
      return;
    }

    let settled = false;
    const settle = (): void => {
      if (settled) {
        return;
      }
      settled = true;
      container.removeEventListener('transitionend', handleTransitionEnd);
      finish();
    };
    const handleTransitionEnd = (event: TransitionEvent): void => {
      if (event.target === container && event.propertyName === 'opacity') {
        settle();
      }
    };
    container.addEventListener('transitionend', handleTransitionEnd);
    const exitMs = readDurationMs(this, '--ds-toast-exit');
    setTimeout(settle, exitMs + EXIT_FALLBACK_BUFFER_MS);
  }

  private applyOverrides(): void {
    for (const binding of Object.keys(HOOKS) as ToastOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }

  private warnInDev(): void {
    if (!import.meta.env.DEV) {
      return;
    }
    if (!this.message) {
      console.warn('<ds-toast> requires a `message`.', this);
    }
    if (this.actionLabel && this.duration !== 'persistent') {
      console.warn('<ds-toast> with an `action-label` should be `duration="persistent"` (WCAG 2.2.1).', this);
    }
    if (this.tone === 'danger' && this.duration !== 'persistent') {
      console.warn('<ds-toast tone="danger"> should be `duration="persistent"`.', this);
    }
  }
}

/**
 * `<ds-toast-region>` — the live region that holds `<ds-toast>` children (anatomy: region).
 *
 * Auto-created in `document.body` by `toast()`; not meant to be authored
 * directly. Takes `role="region"` and `aria-label` through `ElementInternals`
 * and `aria-live="polite"` as an attribute (an ARIAMixin property does not
 * exist for it), fixed at `regionInset` from the viewport edge — bottom-start
 * on wide screens, bottom-center on phones — stacking `<ds-toast>` children
 * with `stackGap` between them, newest at the bottom. A document-level `F6`
 * handler moves focus into the first toast's action or dismiss button, and
 * back out again on a second press.
 */
@customElement('ds-toast-region')
export class DsToastRegion extends LitElement {
  static override styles = css`
    :host {
      position: fixed;
      inset-inline: var(--ds-toast-region-inset);
      inset-block-end: var(--ds-toast-region-inset);
      z-index: var(--ds-toast-region-layer);
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: var(--ds-toast-region-stack-gap);
      pointer-events: none;
      --ds-toast-region-stack-gap: var(--layout-gap-tight);
      --ds-toast-region-inset: var(--layout-gutter);
      --ds-toast-region-layer: var(--layer-toast);
    }

    :host([hidden]) {
      display: none;
    }

    ::slotted(ds-toast) {
      pointer-events: auto;
    }

    /* Bottom-start (not centered) once there is room beside the toast's own max width. */
    @media (min-width: 572px) { /* literal-ok: breakpoint from layout.maxWidth.prose */
      :host {
        align-items: flex-start;
        inset-inline-end: auto;
      }
    }
  `;

  /** Per-instance style overrides: `{ regionInset: 'layout.gutter.wide' }`. */
  @property({ attribute: false }) overrides?: Partial<Record<ToastRegionOverridableBinding, TokenRef>>;

  private readonly internals: ElementInternals;

  /** What had focus before `F6` moved it into the region, restored on the next `F6` or on dismissal. */
  private previouslyFocused: HTMLElement | null = null;

  constructor() {
    super();
    this.internals = this.attachInternals();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('data-ds', 'ToastRegion');
    this.setAttribute('aria-live', 'polite');
    this.internals.role = 'region';
    this.internals.ariaLabel = COPY_REGION_LABEL;
    document.addEventListener('keydown', this.handleDocumentKeydown);
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener('keydown', this.handleDocumentKeydown);
  }

  protected override willUpdate(changed: PropertyValues): void {
    if (changed.has('overrides')) {
      this.applyOverrides();
    }
  }

  protected override render() {
    return html`<slot></slot>`;
  }

  /** Sends focus back to whatever had it before `F6` moved focus in here. Called on the second `F6` and on dismissal. */
  public restoreFocus(): void {
    const target = this.previouslyFocused;
    this.previouslyFocused = null;
    target?.focus();
  }

  private readonly handleDocumentKeydown = (event: KeyboardEvent): void => {
    if (event.key !== 'F6' || this.childElementCount === 0) {
      return;
    }
    if (this.contains(document.activeElement)) {
      event.preventDefault();
      this.restoreFocus();
      return;
    }
    const first = this.firstElementChild as HTMLElement | null;
    const target = first?.shadowRoot?.querySelector<HTMLElement>('.action, .dismiss') ?? first ?? undefined;
    if (target) {
      event.preventDefault();
      this.previouslyFocused = document.activeElement as HTMLElement | null;
      target.focus();
    }
  };

  private applyOverrides(): void {
    for (const binding of Object.keys(REGION_HOOKS) as ToastRegionOverridableBinding[]) {
      const ref = this.overrides?.[binding];
      const hook = REGION_HOOKS[binding];
      if (ref === undefined) {
        this.style.removeProperty(hook);
      } else {
        this.style.setProperty(hook, cssVar(ref));
      }
    }
  }
}

/** Options for `toast()`. */
export interface ToastOptions {
  message: string;
  tone?: ToastTone;
  actionLabel?: string;
  duration?: ToastDuration;
  dismissible?: boolean;
  /** Stable identity; showing a toast with the same toastId replaces the previous one instead of stacking. */
  toastId?: string;
}

/** Resolution of the promise `toast()` returns, once the toast leaves the screen. */
export interface ToastResult {
  reason: ToastDismissReason;
}

let regionEl: DsToastRegion | null = null;

function ensureRegion(): DsToastRegion {
  if (regionEl === null || !regionEl.isConnected) {
    regionEl = document.createElement('ds-toast-region') as DsToastRegion;
    document.body.appendChild(regionEl);
  }
  return regionEl;
}

/**
 * Shows a toast, since a notification is an event, not a place in the tree.
 * Returns a promise that resolves once the toast leaves the screen (see
 * `ToastResult.reason`). Showing a toast with the same `toastId` as one
 * already visible replaces it (`reason: 'replaced'` for the old one) instead
 * of stacking; more than `MAX_TOASTS` visible evicts the oldest the same way.
 */
export function toast(options: ToastOptions): Promise<ToastResult> {
  const region = ensureRegion();

  const current = Array.from(region.querySelectorAll('ds-toast')) as DsToast[];

  if (options.toastId !== undefined) {
    const existing = current.find((el) => el.toastId === options.toastId);
    existing?.requestDismiss('replaced');
  }

  if (current.length >= MAX_TOASTS) {
    current[0]?.requestDismiss('replaced');
  }

  const el = document.createElement('ds-toast') as DsToast;
  el.toastId = options.toastId;
  el.message = options.message;
  el.tone = options.tone ?? 'neutral';
  el.duration = options.duration ?? 'short';
  if (options.actionLabel !== undefined) {
    el.actionLabel = options.actionLabel;
  }
  if (options.dismissible !== undefined) {
    el.dismissible = options.dismissible;
  }

  region.appendChild(el);

  return new Promise<ToastResult>((resolve) => {
    el.addEventListener(
      'dismiss',
      (event) => resolve({ reason: (event as CustomEvent<ToastDismissDetail>).detail.reason }),
      { once: true },
    );
  });
}

declare global {
  interface HTMLElementTagNameMap {
    'ds-toast': DsToast;
    'ds-toast-region': DsToastRegion;
  }
}

// packages/react/src/Toast.tsx
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  useSyncExternalStore,
  type ComponentPropsWithoutRef,
  type Context,
  type CSSProperties,
  type ReactElement,
  type Ref,
} from 'react';
import { createPortal, flushSync } from 'react-dom';
import { createRoot, type Root } from 'react-dom/client';
import { cssVar, type TokenRef } from '@design-schema/tokens';
import { Button } from './Button';
import { Icon } from './Icon';
import { Text } from './Text';
import './Toast.css';

export type ToastTone = 'neutral' | 'success' | 'warning' | 'danger';
export type ToastDuration = 'short' | 'long' | 'persistent';
export type ToastDismissReason = 'timeout' | 'dismiss-button' | 'escape' | 'action' | 'replaced';

/**
 * Style bindings that can be overridden on a toast; accessibility-bearing bindings are never in
 * this list. `stackGap`, `regionInset` and `layer` belong to the region: see
 * `ToastRegionOverridableBinding`.
 */
export type ToastOverridableBinding =
  | 'radius'
  | 'shadow'
  | 'paddingBlock'
  | 'paddingInline'
  | 'gap'
  | 'maxWidth'
  | 'fontFamily'
  | 'fontSize'
  | 'lineHeight'
  | 'enter'
  | 'exit';

const OVERRIDE_HOOK: Record<ToastOverridableBinding, string> = {
  radius: '--ds-toast-radius',
  shadow: '--ds-toast-shadow',
  paddingBlock: '--ds-toast-padding-block',
  paddingInline: '--ds-toast-padding-inline',
  gap: '--ds-toast-gap',
  maxWidth: '--ds-toast-max-width',
  fontFamily: '--ds-toast-font-family', // literal-ok: CSS custom-property hook name, not a font stack
  fontSize: '--ds-toast-font-size',
  lineHeight: '--ds-toast-line-height',
  enter: '--ds-toast-enter',
  exit: '--ds-toast-exit',
};

/** Style bindings that can be overridden on the region (ToastRegion). */
export type ToastRegionOverridableBinding = 'stackGap' | 'regionInset' | 'layer';

const REGION_OVERRIDE_HOOK: Record<ToastRegionOverridableBinding, string> = {
  stackGap: '--ds-toast-stack-gap',
  regionInset: '--ds-toast-region-inset',
  layer: '--ds-toast-layer',
};

function hooksToStyle<Binding extends string>(
  hooks: Record<Binding, string>,
  overrides: Partial<Record<Binding, TokenRef | undefined>> | undefined,
): CSSProperties | undefined {
  if (!overrides) return undefined;
  const style: Record<string, string> = {};
  for (const binding of Object.keys(hooks) as Binding[]) {
    const ref = overrides[binding];
    if (ref) style[hooks[binding]] = cssVar(ref);
  }
  return style as CSSProperties;
}

const COPY = { dismissLabel: 'Dismiss', regionLabel: 'Notifications' };

/* Only declared when the bundler defines it; never assumed. */
declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

/** Constants `shortDuration` / `longDuration`: motion.duration.loop × 6 / × 12, in ms. */
const LOOP_MULTIPLIER: Record<Exclude<ToastDuration, 'persistent'>, number> = { short: 6, long: 12 };

/** A resolved CSS time (`800ms`, `0.8s`) in ms; `null` when it cannot be read. */
function parseTime(value: string): number | null {
  const match = /^(-?\d*\.?\d+)(ms|s)$/.exec(value.trim());
  if (!match) return null;
  const amount = Number(match[1]);
  return match[2] === 's' ? amount * 1000 : amount;
}

/** The resolved motion.duration.loop on `el`, or `null` when the theme's tokens are not loaded. */
function resolveLoopMs(el: Element): number | null {
  const ms = parseTime(getComputedStyle(el).getPropertyValue('--motion-duration-loop'));
  return ms !== null && ms > 0 ? ms : null;
}

/** jsdom (and older browsers) have no `matchMedia`; treat that as "no preference". */
function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function'
    ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
    : false;
}

const FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), input, select, textarea, [tabindex]:not([tabindex="-1"])';

/** Where focus was before it entered the toast region (by F6 or Tab); Escape and the buttons send it back. */
let returnFocusTarget: HTMLElement | null = null;

/** Moves focus to the element it came from, or else the next focusable element after `root` (the previous one when there is none). */
function returnFocus(root: HTMLElement): void {
  const target = returnFocusTarget;
  returnFocusTarget = null;
  if (target && target.isConnected && !root.contains(target)) {
    target.focus();
    return;
  }
  const candidates = Array.from(root.ownerDocument.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)).filter(
    (el) => !root.contains(el),
  );
  const isAfter = (el: HTMLElement): boolean =>
    (root.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING) !== 0;
  const next = candidates.find(isAfter);
  const previous = next === undefined ? candidates.filter((el) => !isAfter(el)).pop() : undefined;
  (next ?? previous)?.focus();
}

/** The region's timing, measured once at region mount; `loopMs` is `undefined` until then. */
interface RegionTiming {
  loopMs: number | null | undefined;
}

const ToastRegionContext: Context<RegionTiming | null> = createContext<RegionTiming | null>(null);

export interface ToastProps extends Omit<ComponentPropsWithoutRef<'div'>, 'id' | 'children' | 'role' | 'style' | 'className'> {
  /** One sentence saying what happened ("Message sent", "3 files deleted"). */
  message: string;
  /** Sets the leading icon; `neutral` has none. Toasts do not use tinted backgrounds — the icon and message carry the tone. */
  tone?: ToastTone | undefined;
  /** Label for a single action button ("Undo", "View"). When present the toast stays longer and pauses on hover and focus. */
  actionLabel?: string | undefined;
  /**
   * `short` ≈ 5s, `long` ≈ 10s (both computed from motion.duration.loop × 6 / × 12 so themes
   * without motion still get sensible times), `persistent` until dismissed. When `action` is set or
   * `tone` is danger the toast is persistent regardless of this prop (a dev warning notes the
   * override).
   */
  duration?: ToastDuration | undefined;
  /** Shows a dismiss button. Persistent toasts are always dismissible. */
  dismissible?: boolean | undefined;
  /** Stable identity; showing a toast with the same toastId replaces the previous one instead of stacking. */
  toastId?: string | undefined;
  /** The action button was activated. The toast dismisses. */
  onAction?: (() => void) | undefined;
  /** The toast left the screen: reason `timeout`, `dismiss-button`, `escape`, `action`, or `replaced`. */
  onDismiss?: ((reason: ToastDismissReason) => void) | undefined;
  /** Per-instance style overrides: each entry sets the matching CSS hook to that token, inline. */
  overrides?: Partial<Record<ToastOverridableBinding, TokenRef | undefined>> | undefined;
}

/**
 * Toast — Design Schema, category: feedback.
 *
 * When to use:
 * Use a Toast to confirm a completed action that the user did not have to watch (sent, saved,
 * deleted, copied), to offer Undo for a reversible action, or to report a background result
 * ("Export ready" with a "View" action). Match `tone` to the outcome; use `persistent` whenever
 * there is an action, and for `danger`, so nobody misses the one they needed.
 *
 * Toasts are normally shown with `toast({ message })`, which renders them in the one
 * `ToastRegion`; rendering `<Toast>` directly is for previews and custom hosts.
 */
export function Toast({
  ref,
  message,
  tone = 'neutral',
  actionLabel,
  duration,
  dismissible = true,
  toastId: _toastId,
  onAction,
  onDismiss,
  overrides,
  ...rest
}: ToastProps & { ref?: Ref<HTMLDivElement> | undefined }): ReactElement | null {
  const rootRef = useRef<HTMLDivElement | null>(null);
  useImperativeHandle(ref, () => rootRef.current as HTMLDivElement, []);

  const regionTiming = useContext(ToastRegionContext);
  const [ownLoopMs, setOwnLoopMs] = useState<number | null | undefined>(undefined);
  const loopMs = regionTiming ? regionTiming.loopMs : ownLoopMs;

  const [visible, setVisible] = useState(false);
  const [gone, setGone] = useState(false);
  const dismissedRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const exitTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const onDismissLatest = useRef(onDismiss);
  onDismissLatest.current = onDismiss;

  // An action or danger tone keeps the toast until dismissed, regardless of `duration`.
  const forcedPersistent = Boolean(actionLabel) || tone === 'danger';
  const effectiveDuration: ToastDuration = forcedPersistent ? 'persistent' : (duration ?? 'short');
  const showDismiss = dismissible || effectiveDuration === 'persistent';

  useEffect(() => {
    if (isDev && forcedPersistent && duration !== undefined && duration !== 'persistent') {
      console.warn(
        `Toast: \`duration: ${duration}\` is ignored — a toast with an action or \`tone: danger\` is persistent until dismissed.`,
      );
    }
  }, [forcedPersistent, duration]);

  // Outside a region, measure motion.duration.loop on the toast itself at mount.
  useEffect(() => {
    if (regionTiming || !rootRef.current) return;
    setOwnLoopMs(resolveLoopMs(rootRef.current));
  }, [regionTiming]);

  const dismiss = useCallback((reason: Exclude<ToastDismissReason, 'replaced'>) => {
    const node = rootRef.current;
    if (dismissedRef.current || !node) return;
    dismissedRef.current = true;
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
    if (node.contains(node.ownerDocument.activeElement)) returnFocus(node);

    const finish = (): void => {
      setGone(true);
      onDismissLatest.current?.(reason);
    };
    // The exit transition runs for the resolved `exit` hook; onDismiss fires once it has finished.
    const exitMs = prefersReducedMotion() ? null : parseTime(getComputedStyle(node).getPropertyValue('--ds-toast-exit'));
    if (exitMs === null || exitMs <= 0) {
      finish();
      return;
    }
    setVisible(false);
    exitTimerRef.current = setTimeout(finish, exitMs);
  }, []);

  useEffect(
    () => () => {
      if (exitTimerRef.current) clearTimeout(exitTimerRef.current);
    },
    [],
  );

  // Enter: reveal on the next frame so the rise-and-fade runs; instant under reduced motion.
  useEffect(() => {
    if (prefersReducedMotion() || typeof requestAnimationFrame !== 'function') {
      setVisible(true);
      return undefined;
    }
    const frame = requestAnimationFrame(() => setVisible(true));
    return () => cancelAnimationFrame(frame);
  }, []);

  // Auto-dismiss: paused while hovered or touched, focused within, or the page is hidden. Without a
  // resolvable motion.duration.loop there is no time to count, so the toast stays until dismissed.
  useEffect(() => {
    const node = rootRef.current;
    if (effectiveDuration === 'persistent' || loopMs === undefined || loopMs === null || !node) return undefined;
    let remaining = loopMs * LOOP_MULTIPLIER[effectiveDuration];
    let startedAt = 0;
    let hovering = false;
    let focused = node.contains(node.ownerDocument.activeElement);

    const start = (): void => {
      if (timerRef.current || dismissedRef.current || hovering || focused || document.hidden) return;
      startedAt = Date.now();
      timerRef.current = setTimeout(() => dismiss('timeout'), remaining);
    };
    const pause = (): void => {
      if (!timerRef.current) return;
      clearTimeout(timerRef.current);
      timerRef.current = null;
      remaining -= Date.now() - startedAt;
    };
    const handlePointerEnter = (): void => {
      hovering = true;
      pause();
    };
    const handlePointerLeave = (): void => {
      hovering = false;
      start();
    };
    const handleFocusIn = (): void => {
      focused = true;
      pause();
    };
    const handleFocusOut = (event: FocusEvent): void => {
      if (node.contains(event.relatedTarget as Node | null)) return;
      focused = false;
      start();
    };
    const handleVisibilityChange = (): void => {
      if (document.hidden) pause();
      else start();
    };

    start();
    node.addEventListener('pointerenter', handlePointerEnter);
    node.addEventListener('pointerleave', handlePointerLeave);
    node.addEventListener('focusin', handleFocusIn);
    node.addEventListener('focusout', handleFocusOut);
    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
      node.removeEventListener('pointerenter', handlePointerEnter);
      node.removeEventListener('pointerleave', handlePointerLeave);
      node.removeEventListener('focusin', handleFocusIn);
      node.removeEventListener('focusout', handleFocusOut);
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, [effectiveDuration, loopMs, dismiss]);

  // Remember where focus came from when it enters by Tab, and dismiss on Escape.
  useEffect(() => {
    const node = rootRef.current;
    if (!node) return undefined;
    const handleFocusIn = (event: FocusEvent): void => {
      const from = event.relatedTarget;
      const region = node.closest('[data-ds="ToastRegion"]') ?? node;
      if (from instanceof HTMLElement && !region.contains(from)) returnFocusTarget = from;
    };
    const handleKeyDown = (event: KeyboardEvent): void => {
      if (event.key !== 'Escape') return;
      event.preventDefault();
      event.stopPropagation();
      dismiss('escape');
    };
    node.addEventListener('focusin', handleFocusIn);
    node.addEventListener('keydown', handleKeyDown);
    return () => {
      node.removeEventListener('focusin', handleFocusIn);
      node.removeEventListener('keydown', handleKeyDown);
    };
  }, [dismiss]);

  if (gone) return null;

  const handleActionClick = (): void => {
    onAction?.();
    dismiss('action');
  };

  return (
    <div
      {...rest}
      ref={rootRef}
      data-ds="Toast"
      data-part="toast"
      className={`ds-toast ds-toast--${tone}${visible ? ' ds-toast--entered' : ''}`}
      style={hooksToStyle(OVERRIDE_HOOK, overrides)}
      role={tone === 'danger' ? 'alert' : 'status'}
    >
      {tone !== 'neutral' ? (
        <Icon data-part="icon" name={tone} overrides={{ color: `color.inverse.status.${tone}` as TokenRef }} />
      ) : null}
      <Text element="span" data-part="message">
        {message}
      </Text>
      {/* Button owns its root's data-part, so each button part is a wrapper around it (as in Alert). */}
      {actionLabel ? (
        <span className="ds-toast__action" data-part="actionButton">
          <Button variant="ghost" inverse label={actionLabel} onClick={handleActionClick} />
        </span>
      ) : null}
      {showDismiss ? (
        <span className="ds-toast__dismiss" data-part="dismissButton">
          <Button
            variant="ghost"
            inverse
            iconOnly
            label={COPY.dismissLabel}
            leadingIcon={<Icon name="close" inline />}
            onClick={() => dismiss('dismiss-button')}
          />
        </span>
      ) : null}
    </div>
  );
}

/** Options for `toast()`: the toast's props, shown in the region. */
export interface ToastOptions {
  /** One sentence saying what happened ("Message sent", "3 files deleted"). */
  message: string;
  /** Sets the leading icon; `neutral` has none. */
  tone?: ToastTone | undefined;
  /** Label for a single action button ("Undo", "View"). */
  actionLabel?: string | undefined;
  /** `short` ≈ 5s, `long` ≈ 10s, `persistent` until dismissed. */
  duration?: ToastDuration | undefined;
  /** Shows a dismiss button. Persistent toasts are always dismissible. */
  dismissible?: boolean | undefined;
  /** Stable identity; showing a toast with the same toastId replaces the previous one instead of stacking. */
  toastId?: string | undefined;
  /** The action button was activated. The toast dismisses. */
  onAction?: (() => void) | undefined;
  /** The toast left the screen. */
  onDismiss?: ((reason: ToastDismissReason) => void) | undefined;
}

interface ToastEntry {
  key: number;
  options: ToastOptions;
  resolve: (result: { reason: ToastDismissReason }) => void;
}

/** "Do not stack more than three; the region replaces the oldest." */
const MAX_STACKED = 3;

let entries: ToastEntry[] = [];
const listeners = new Set<() => void>();
let entryCounter = 0;
let regionMountCount = 0;
let autoRoot: Root | null = null;

function notify(): void {
  for (const listener of listeners) listener();
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

function getSnapshot(): ToastEntry[] {
  return entries;
}

function settle(entry: ToastEntry, reason: ToastDismissReason): void {
  entry.options.onDismiss?.(reason);
  entry.resolve({ reason });
}

/** A toast finished leaving on its own (timeout, button, Escape, action). */
function removeEntry(key: number, reason: ToastDismissReason): void {
  const entry = entries.find((item) => item.key === key);
  if (!entry) return;
  entries = entries.filter((item) => item.key !== key);
  notify();
  settle(entry, reason);
}

/** Adds a toast; one with the same toastId, or the oldest beyond three, leaves immediately as `replaced`. */
function pushEntry(entry: ToastEntry): void {
  const id = entry.options.toastId;
  const replaced = id === undefined ? undefined : entries.find((item) => item.options.toastId === id);
  let next = replaced ? entries.map((item) => (item === replaced ? entry : item)) : [...entries, entry];
  const evicted = next.length > MAX_STACKED ? next.slice(0, next.length - MAX_STACKED) : [];
  next = next.slice(evicted.length);
  entries = next;
  notify();
  if (replaced) settle(replaced, 'replaced');
  for (const item of evicted) settle(item, 'replaced');
}

export interface ToastRegionProps {
  /** Per-instance style overrides for the region's own bindings (`stackGap`, `regionInset`, `layer`). */
  overrides?: Partial<Record<ToastRegionOverridableBinding, TokenRef | undefined>> | undefined;
  /** Portal target; defaults to `document.body`. */
  container?: HTMLElement | undefined;
}

/**
 * ToastRegion — the one persistent `role="region"` live region that holds every visible Toast.
 *
 * Mount it once at the app root, or let `toast()` create it on first use. It exists before any
 * toast so announcements fire; F6 moves focus into it from anywhere and back again.
 */
export function ToastRegion({
  ref,
  overrides,
  container,
}: ToastRegionProps & { ref?: Ref<HTMLDivElement> | undefined }): ReactElement | null {
  const list = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  const regionRef = useRef<HTMLDivElement | null>(null);
  useImperativeHandle(ref, () => regionRef.current as HTMLDivElement, []);
  const [timing, setTiming] = useState<RegionTiming>({ loopMs: undefined });

  useEffect(() => {
    regionMountCount += 1;
    return () => {
      regionMountCount -= 1;
    };
  }, []);

  // The two durations come from motion.duration.loop as resolved on the region at mount.
  useEffect(() => {
    if (regionRef.current) setTiming({ loopMs: resolveLoopMs(regionRef.current) });
  }, []);

  // F6 moves focus to the first toast's first button from anywhere, and back where it was on the next press.
  useEffect(() => {
    if (list.length === 0) return undefined;
    const handleKeyDown = (event: KeyboardEvent): void => {
      if (event.key !== 'F6') return;
      const region = regionRef.current;
      if (!region) return;
      if (region.contains(document.activeElement)) {
        const target = returnFocusTarget;
        returnFocusTarget = null;
        if (!target || !target.isConnected) return;
        event.preventDefault();
        target.focus();
        return;
      }
      const first = region.querySelector<HTMLElement>(FOCUSABLE_SELECTOR);
      if (!first) return;
      event.preventDefault();
      const active = document.activeElement;
      returnFocusTarget = active instanceof HTMLElement && active !== document.body ? active : null;
      first.focus();
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [list.length]);

  if (typeof document === 'undefined') return null;

  return createPortal(
    <div
      ref={regionRef}
      role="region"
      aria-label={COPY.regionLabel}
      aria-live="polite"
      data-ds="ToastRegion"
      data-part="region"
      className="ds-toast-region"
      style={hooksToStyle(REGION_OVERRIDE_HOOK, overrides)}
    >
      <ToastRegionContext.Provider value={timing}>
        {list.map((entry) => (
          <Toast
            key={entry.key}
            message={entry.options.message}
            tone={entry.options.tone}
            actionLabel={entry.options.actionLabel}
            duration={entry.options.duration}
            dismissible={entry.options.dismissible}
            toastId={entry.options.toastId}
            onAction={entry.options.onAction}
            onDismiss={(reason) => removeEntry(entry.key, reason)}
          />
        ))}
      </ToastRegionContext.Provider>
    </div>,
    container ?? document.body,
  );
}

/**
 * Shows a toast. A notification is an event, not a place in the tree, so it is called rather than
 * rendered: `toast({ message: 'Link copied' })`. Resolves with `{ reason }` when the toast leaves.
 */
export function toast(options: ToastOptions): Promise<{ reason: ToastDismissReason }> {
  return new Promise((resolve) => {
    const entry: ToastEntry = { key: ++entryCounter, options, resolve };
    if (regionMountCount > 0 || autoRoot || typeof document === 'undefined') {
      pushEntry(entry);
      return;
    }
    // Create the region empty first, so the live region exists before the content it announces.
    const host = document.createElement('div');
    document.body.appendChild(host);
    const root = createRoot(host);
    autoRoot = root;
    flushSync(() => root.render(<ToastRegion />));
    if (typeof requestAnimationFrame === 'function') requestAnimationFrame(() => pushEntry(entry));
    else pushEntry(entry);
  });
}
